### PR TITLE
[Tablet Products] Fix product list scrolled to the selected product when loading new products from infinite scroll

### LINKED ISSUE #12050: After new products are loaded from infinite scroll, it scrolls back to the previously selected row
https://github.com/woocommerce/woocommerce-ios/assets/1945542/f3dd1e85-5486-4090-a8b6-51873111a37a

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #12050

## Why

In the product list selection/deselection logic `ProductsViewController.observeSelectedProductAndDataLoadedStateToUpdateSelectedRow`, the `tableView.selectRow` call currently sets the flag to scroll to the selected row in the middle if it's not visible. This is useful when the product name changes from the product form in the secondary view and the selected product's index path becomes invisible, but this becomes an issue when the merchant does an infinite scroll (new data loaded when scrolling near the bottom). Because the data for the next page are reloaded, it triggers the selection/deselection logic to scroll to the selected row while the merchant intends to see new data toward the bottom of the list.

## How

It prompted me to revisit the question: when do we want to scroll to the selected product?

I think we'd only want to do this when: (open to feedback here)
- The selected product changes, which includes the following scenarios:
  - After publishing a new product
  - The product in the secondary view is deleted, the first product becomes auto-selected, then the table view should be scrolled back to the top (this will be implemented in https://github.com/woocommerce/woocommerce-ios/issues/12067)
- For the same selected product, its position (index path) in the product list changes from the product updates in the secondary view (e.g. the product name)

This PR updates the scroll position in `ProductsViewController.observeSelectedProductAndDataLoadedStateToUpdateSelectedRow` so that the table view is scrolled to the selected row only when it's not visible and the selected product changes. To implement the second scenario where the selected product's properties change, it observes the `selectedProduct` (`Product`) and uses `EntityListener` to listen to any changes of this product in storage (like from any save actions). `EntityListener` still uses a callback closure so it's not the prettiest with Combine.

## Testing instructions

Prerequisite: the device/simulator allows switching between expanded and collapsed states like a tablet

- [ ] @jaclync makes sure the product form works as expected when the feature flag is off
- [ ] @jaclync tests on iPhone

---

### Scenario 1: creating a new product

- In code, enable `splitViewInProductsTab` feature flag in `DefaultFeatureFlagService`
- Launch the app
- Go to the products tab
- Tap + to create a product
- Enter a product name that won't show up in the currently visible section of the product list (depending on the sort order)
- Publish the product --> the product list should be scrolled to the updated position (🗒️ from my testing, there's a scenario when the the updated position is toward the bottom of the table view which triggers infinite scroll, then the selected row isn't visible anymore. I think this is likely an edge case, we can handle it if we hear from the merchants)

### Scenario 1: updating a product's name

- Go to the products tab
- Select a product from the list
- In the secondary view product form, change the product name so that the product won't show up in the currently visible section of the product list (depending on the sort order)
- Save the product --> the product list should be scrolled to the updated position

## Screenshots

Scenario 1: creating a new product

https://github.com/woocommerce/woocommerce-ios/assets/1945542/69eb5d90-5d3b-4cef-8a5c-7fd773a45826

Scenario 2: updating a product's name

https://github.com/woocommerce/woocommerce-ios/assets/1945542/afd28875-2869-4491-a00b-78f8f2c04e0d

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/187">17.5</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bozidarsevo — APPROVED** [review]
🚀

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 1]
```diff
@@ -955,9 +958,12 @@ private extension ProductsViewController {
                                   onDataReloaded.merge(with: Just<Void>(())),
                                   // Giving it an initial value to enable the combined publisher from the beginning.
                                   onTableViewEditingEnd.merge(with: Just<Void>(())))
-            .sink { [weak self] selectedProduct, _, _ in
+            .withPrevious()
+            .sink { [weak self] previous, current in
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Since you only used `.0` of these two tuples, I looked at adding a `.map` in between to unwrap the tuple. I couldn't make it particularly neat, but perhaps you'd have more luck? the `.0` notation further down, especially in `hasSelectedProductChanged` isn't super nice.

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 2]
```diff
@@ -969,15 +975,41 @@ private extension ProductsViewController {
                     if let currentSelectedIndexPath {
                         tableView.deselectRow(at: currentSelectedIndexPath, animated: false)
                     }
-                    let scrollPosition: UITableView.ScrollPosition = tableView.indexPathsForVisibleRows?.contains(selectedIndexPath) == true ?
-                        .none: .middle
+
+                    let scrollPosition: UITableView.ScrollPosition = {
+                        let hasSelectedProductChanged = (selectedProduct != previous?.0)
+                        let isSelectedIndexPathVisible = self.tableView.indexPathsForVisibleRows?.contains(selectedIndexPath) == true
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Since we use this further down in `ProductsViewController.listenToSelectedProductToAutoScrollWhenProductChanges(product:)`, perhaps it should be a function?

```
 func isIndexPathVisible(_ indexPath: IndexPath) -> Bool {
        guard let indexPathsForVisibleRows = tableView.indexPathsForVisibleRows else {
            return false
        }
        return indexPathsForVisibleRows.contains(indexPath)
    }
```

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 3]
```diff
@@ -969,15 +975,41 @@ private extension ProductsViewController {
...
+                        return hasSelectedProductChanged && !isSelectedIndexPathVisible ? .middle : .none
+                    }()
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]:
```suggestion
                        let hasSelectedProductChanged = (selectedProduct != previous?.0)
                        guard hasSelectedProductChanged else { return .none }
                        let isSelectedIndexPathVisible  = self.isIndexPathVisible(selectedIndexPath)
                        return isSelectedIndexPathVisible ? .none : .middle
                    }()
```

Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Not required, I just think it makes the ternary a little more readable.

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 4]
```diff
@@ -969,15 +975,41 @@ private extension ProductsViewController {
...
+            .store(in: &subscriptions)
+    }
+
+    func listenToSelectedProductToAutoScrollWhenProductChanges(product: Product) {
+        selectedProductListener = .init(storageManager: ServiceLocator.storageManager, readOnlyEntity: product)
+        selectedProductListener?.onUpsert = { [weak self] product in
+            guard let self,
+                  let selectedIndexPath = tableView.indexPathForSelectedRow,
+                  let visibleIndexPaths = tableView.indexPathsForVisibleRows,
+                  !visibleIndexPaths.contains(selectedIndexPath) else {
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: The function suggested above could be used here too

**Review by joshheald — APPROVED** [review]
Works well, and I agree the edge case feels OK.

Some suggestions for readability, but all up to you.

One thing unrelated to this PR – is there a plan to add a confirmation alert, telling users that they will lose their changes if they tap on another row in the list while creating/editing a product? It's easy to do accidentally.

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Nice suggestion! Since only the selected product is used, great idea to map the combined publisher to what's being used downstream. Updated in https://github.com/woocommerce/woocommerce-ios/pull/12060/commits/25d62b8c13f57d9c9664a63d9974525f462ef894

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Thanks for the suggestion! Updated in https://github.com/woocommerce/woocommerce-ios/pull/12060/commits/5adf6fb1319bf2277de8423cbe0c4d056ee261e6 for this and the following 2 comments

**Comment by jaclync** [comment]
Thank you for the review & testing both!

> One thing unrelated to this PR – is there a plan to add a confirmation alert, telling users that they will lose their changes if they tap on another row in the list while creating/editing a product? It's easy to do accidentally.

Thanks for bringing up this scenario, it didn't occur to me as a dev testing the split view but it sounds like a valid issue for merchants. I created an issue https://github.com/woocommerce/woocommerce-ios/issues/12086 to prevent any data loss.
