### PR TITLE
[Universal Links] Do not enter undetermined state if the user does not have access to the passed blog Id

### LINKED ISSUE #7864: [Universal Links - Notifications] App gets in undetermined state when opening universal link with unknown site id
**Describe the bug**
When opening the app from an orders universal link with a site id the user cannot access, the app gets in an undetermined state. No data can be loaded, and the site does not have any name. The same happens for push notifications.

**To Reproduce**
1. Add a link to the Notes app with a blog id you don't have access to E.g https://woocommerce.com/mobile/orders/details?blog_id=1&order_id=240
2. Tap on the Link
3. App opens, the order load fails and the app cannot retrieve data anymore until you switch store again in settings.

**Screenshots**

https://user-images.githubusercontent.com/1864060/195868855-b2886f15-4f60-4e84-8502-eafdf3fccf93.MP4

**Expected behavior**
The app opens, and navigates to Orders, but, since we cannot switch to the store, no order details are shown. This way we still communicate to the users that they can check the orders in the app while keeping it in a safe state.

### PR DESCRIPTION
**Pull request by toupper**
Closes: #7864

### Description

Before, when the user tapped on "order details" universal link with a blog Id parameter value they couldn't access, the app opened and switched to an undetermined state where data couldn't be loaded (see video below).
The reason is that, when switching to the new store, we logged out from the previous one without checking if the user could actually access the new site. Once we do that, the app cannot load any data (stats, orders, products ...) of the new site because the user doesn't have access.
With this PR we check first if the switching store was previously synced and stored in CoreData, which means the user has access to it. Since we synchronize the sites remotely on every startup and we want the navigation to be quick, I consider enough checking locally for the store instead of syncing remotely after opening the app following a universal link.

### Testing instructions

1. Add a link to the Notes app with a blog id you don't have access to E.g https://woocommerce.com/mobile/orders/details?blog_id=1&order_id=240
2. Tap on the Link
3a. Before: App opens, the order load fails and the app cannot retrieve data anymore until you switch store again in settings.
3b. After: App opens and navigates to orders.

#### Before

https://user-images.githubusercontent.com/1864060/195874181-59005dd0-2675-4903-8f42-9af7aee8c5f4.MP4

#### After

https://user-images.githubusercontent.com/1864060/195874227-02817e66-be96-4a8d-b72a-f13cd7e31206.MP4

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift [hunk 1]
```diff
@@ -28,6 +39,25 @@ final class SwitchStoreUseCase: SwitchStoreUseCaseProtocol {
...
 
+    /// Switches the to store with the given id if it was previously synced and stored.
+    /// This is done to check whether the user has access to that store, avoiding undetermined states if we log out
+    /// from the current one and try to switch to a store they don't have access to.
+    ///
+    /// - Parameter storeID: target store ID.
+    /// - Returns: a boolean that indicates whether the site was changed.
+    ///
+    func switchToStoreIfSiteIsStored(with storeID: Int64, onCompletion: @escaping (Bool) -> Void) {
+        self.refreshStoredSites()
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift]:
```suggestion
       refreshStoredSites()
```

File: WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift [hunk 2]
```diff
@@ -28,6 +39,25 @@ final class SwitchStoreUseCase: SwitchStoreUseCaseProtocol {
...
+
+        let siteWasStored = self.wooCommerceSites.first(where: { $0.siteID == storeID }) != nil
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift]:
```suggestion
        let siteWasStored = wooCommerceSites.first(where: { $0.siteID == storeID }) != nil
```

**Review by Ecarrion — APPROVED** [review]
🚀
