### PR TITLE
[Tablet orders] Fix deep-linked order overridden by the auto-selected first order

### LINKED ISSUE #11674: [Tablet Orders] Fix deeplink to Order Details when SplitViewOrders is enabled
When the `splitViewInOrdersTab` feature flag is enabled, Universal URLs such as `https://woo.com/mobile/orders/details?blog_id={id}&order_id={id}` only navigate to the Orders tab, but don't open the specific order.

This also affects order notifications, both displayed as a Notice in the app, or as a system notification when backgrounded.

The routing in MainTabViewController needs to be updated to take account of the WooTabContainerController use for the split view, rather than expecting a navigation controller as the container. See #11673 for context.

## Subtasks

- [x] Handle universal links in `OrdersSplitViewWrapperController` https://github.com/woocommerce/woocommerce-ios/pull/11718

### Split view specific issues

The following issues only happen when the split view is shown (two panes).

- [ ] Fix an issue where deep deep-linked order is overridden by the auto-selected order in `OrderListViewController.checkSelectedItem` in `viewWillAppear`

Repro steps:

- Prepare an order link in a separate app
- Switch to a different store from the store ID in the link
- Tap on an order universal link --> notice that the first order of the store is shown instead of the order ID in the link

https://github.com/woocommerce/woocommerce-ios/assets/1945542/7fecc721-3e80-470e-b0e7-abe1b945058e

- [x] Fix the order not appearing as selected in the primary view (order list) https://github.com/woocommerce/woocommerce-ios/pull/11729

Notice that the order ID in the two views do not match.

### LINKED ISSUE #11795: [Tablet Orders] Mismatch between selection in order list and which order details are shown
**Describe the bug**
If I interact with certain order details and then create a new order, the order details will show the details for the new order but the selected order in the list will be the first order I edited.

**To Reproduce**
1. Edit customer details or billing info (or potentially other fields?) in an order
2. Tap the + to create a new order
3. Accept
4. Note the difference between what's selected in the orders lsit and which details are shown

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/103850310/520df453-1b71-4830-a710-140152a174ca

**Expected behavior**
The selected order in the list should always match which details are shown

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air
- iOS version: iPadOS 17.1
- WooCommerce iOS version: built from PR

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #11674
Closes: #11795

## Why

In the split view implementation, there's an auto-selection behavior where the first order is auto-selected in `viewDidLayoutSubviews` when the split view collapsed state is known. However, when a deep-linked order is also being shown while the orders tab is being shown for the first time (e.g. previously logged in to a different store), the auto-selected first order can override the deep-linked order so that the linked order is never shown. This PR fixes this race condition by only showing the auto-selected order if the secondary view is showing the empty view. If a non-empty view is being shown in the secondary view, I don't think we need to auto-select the first order but please lemme know if I missed anything.

## How

To fix the issue, the `switchDetailsHandler` callback was updated to include two info:

- `isSelectedManually`: whether the order details are selected manually (so that it's `false` for auto-selection in `viewDidLayoutSubviews`). When `isSelectedManually` is `true`, order details are always shown. But when `isSelectedManually` is `false`, it might not be shown depending on the secondary view state
- In `onCompletion`, a boolean was added that indicates if the selection is successful. This addition is for `OrderListViewController`'s `selectedIndexPath` and `selectedOrderID` to be set only if the order details presentation is successful 

Then, all the logic that shows the secondary view was moved to `OrdersSplitViewWrapperController` so that we can consolidate the secondary view presentation logic in one place. This includes `switchDetailsHandler`, which now skips order details presentation if `isSelectedManually` is `false` and the secondary view is not the empty view.

`OrderListViewController.highlightSelectedRowIfNeeded` was also updated to highlight the row based on the selected order instead of the index path state because the index path can get outdated.

🗒️ I've been struggling with fixes in the order split view - making one change breaks some other scenario 😓 . In a split view where the primary is a list and the secondary view is based on the selected row, the selected item & index path states in `OrderListViewController` can get out of sync from the secondary view like when the user navigates back from the order details in collapsed mode. The selected index path can also get outdated like when some orders are loaded individually, and the data source changes. I was inclined to remove `OrderListViewController.selectedIndexPath` but the changes would be out of scope and I'm sure something will break. We can consider a different approach when we implement split view for the products tab like with a source of truth of the secondary view state that works for both expanded and collapsed states.

## Testing instructions

Prerequisite: the account is connected to more than one store

- Launch the app in the multi-column state in a wide device
- Prepare an order link in a separate app
- Switch to a different store from the store ID in the link
- Tap on an order universal link --> the order in the link should be shown. before this PR, the first order of the store is shown instead of the order ID in the link

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/1945542/0ed7a942-4aec-438b-bd21-5b6a06cacc5f

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/182">17.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift [hunk 1]
```diff
@@ -57,19 +57,59 @@ final class OrdersSplitViewWrapperController: UIViewController {
...
-        ordersNavigationController.viewControllers = [ordersViewController]
-
+    func showEmptyView() {
         let emptyStateViewController = EmptyStateViewController(style: .basic)
         let config = EmptyStateViewController.Config.simple(
             message: .init(string: Localization.emptyOrderDetails),
             image: .emptySearchResultsImage
         )
         emptyStateViewController.configure(config)
+        showSecondaryView(emptyStateViewController)
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift]: This should be wrapped in a `UINavigationController`, or a `WooNavigationController`, before we show it in the split view. If it's not, `UISplitViewController` automatically wraps it, which sounds convenient, but the nav controller it gets wrapped in behaves a little strangely. For the empty view it might not cause any issues, but it's safer to avoid the default nav controller altogether.

Given that we should do this for anything we show in the secondary pane, we could do the wrapping in the `showSecondaryView` function which you've added.

**Review by joshheald — APPROVED** [review]
Works as expected, for the most part. 
Only thing which doesn't (as in your video) is highlighting the selected order if you switch stores by following the deeplink. The important thing is that the correct order gets shown though.

We could perhaps fix that by adding something which checks for the order shown in the secondary view when the Order List updates its data, and highlights the review once the relevant order is loaded, but that seems like adding unnecessary complexity for this case.

I noticed one potential issue with nav controller wrapping being removed for the empty state; see the suggestion in the comments.

**Comment by joshheald** [comment]
I've noticed after reviewing this, that it makes #11795 100% reproducible without doing any editing of billing info/customer notes.

This might be the best place to fix that issue, or at least following up after this PR is merged. It's an auto-selection which should always highlight the new row. I suspect it's being blocked by the new flag.

File: WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift]: Good catch! Updated in https://github.com/woocommerce/woocommerce-ios/pull/11799/commits/240edf6b703bb819abf6d11537a9b1a0e760b159. I didn't move `UINavigationController` wrapping to `showSecondaryView` just to be more flexible, but we can consider moving the wrapping logic there if it's easy to miss it.

**Comment by jaclync** [comment]
> I've noticed after reviewing this, that it makes #11795 100% reproducible without doing any editing of billing info/customer notes.

Yes I was able to repro this consistently. It's because the `switchDetailsHandler` for the new order -> order details navigation is called in `OrdersRootViewController`, which doesn't set `OrderListViewController`'s selected order ID / index path states to highlight the correct row. In https://github.com/woocommerce/woocommerce-ios/pull/11799/commits/2c3366d1b86f498c617a0ff69c749eca82503f7b, I moved `switchDetailsHandler` to `OrderListViewController` so that it can set the selected states internally then highlight the row.

Example screencast after the fix:

https://github.com/woocommerce/woocommerce-ios/assets/1945542/d2bb9c98-f2ad-4d2a-84f3-f4e9269a7ff8

**Comment by jaclync** [comment]
> Only thing which doesn't (as in your video) is highlighting the selected order if you switch stores by following the deeplink. The important thing is that the correct order gets shown though.
> 
> We could perhaps fix that by adding something which checks for the order shown in the secondary view when the Order List updates its data, and highlights the review once the relevant order is loaded, but that seems like adding unnecessary complexity for this case.

Yup I noticed that too, it can be tricky when the linked order doesn't exist locally and the order list data is refreshed later. I will create a separate issue for this and fix it later. For now, the correct order is shown at least.
