### PR TITLE
[Mobile Payments] Fix momentarily-shown error during every card reader connection

### LINKED ISSUE #11483: [Mobile Payments] `discoveryCancellable` is called with `nil` for every connection attempt
## Description

When connecting a bluetooth reader, or TTP, an error is shown: `Connecting reader failed`.

This is shown because the discoveryCancellable's completion is called with `nil` error for every connection.
The connection attempt continues, and will still succeed and show all the UI it's supposed to... but that error can be on screen for a couple of seconds and suggests everything has failed.

Stripe SDK 3.2 doesn't fix it, and it's reproducible on iOS 16 and 17.

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11483 

## Description

In this PR, we fix an issue where successful reader discovery completion was treated as an error.

As of SDK version 3, the discovery completion handler behaviour has changed.

Previously, we treated any `nil` property for `receivedError` in this completion handler as an indication that discovery had been canceled. Since the SDK migration, we’ve been look for the specific SCPErrorCanceled to check that.

However, we also started to treat `nil` as an error, as we weren’t expecting it to happen, and we were a little confused by discrepancies in Stripe’s documentation, which said that it indicated cancelation in one place.

This quote appears to be key:
> discoverReaders is now completed successfully when connectReader is called.
– https://stripe.com/docs/terminal/references/sdk-migration-guide#update-your-discoverreaders-and-connectreader-usage

i.e. the completion handler is called. And there’s no error. So the property is nil.

I’ve confirmed that we get the call every time `connect` is called on a card reader, and previously that meant momentarily showing an error.

This PR removes that incorrect handling of `nil` and instead does nothing for discovery completion. The momentary errors no longer show during connection

## Testing instructions

Ensure you're disconnected from any card readers
Launch the app
Navigate to `Menu > Payments > Collect Payment`
Take a payment for some amount – pick card reader for payment
Observe that the reader connects without showing an error

Repeat the above with Tap to Pay, observe that the TTP connection flow also completes without showing an error.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/f1c32da0-64c2-408e-b524-d4762cb50149

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 1]
```diff
@@ -170,16 +170,16 @@ extension StripeCardReaderService: CardReaderService {
...
-            case .none:
-                let error = NSError(domain: "DiscoveryCancellable received nil error on completion", code: 0)
-                DDLogError(error.localizedDescription)
-                self?.switchStatusToFault(error: error)
+            guard let receivedError else {
+                // Discovery completed successfully
                 return
+            }
+
+            switch receivedError {
```
Comment (toupper) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift:178]: Nice change! Now this logic is clearer and more readable.

**Review by toupper — APPROVED** [review]
LGTM and tests well 👏
