### PR TITLE
Settings: fix footer covered for larger font sizes

### LINKED ISSUE #910: Settings: `Made with Love by Automattic` is covered by the tab bar for large font sizes
Simulator Screen Shot - iPhone 8 - 2019-04-23 at 09 27 33

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #910 

## Changes
- Added a `UIViewController` extension to update height for table footer view. With a frame-based container view as `tableView.tableFooterView`, an Auto Layout based subview does not trigger its parent frame based view to update its height. From my experiments, it is necessary to calculate the table footer view height in view controller's `viewDidLayoutSubviews`, update the height and reassign the footer view if the new height is different
- Added an Auto Layout constraint to pin the footnote label's bottom to the footer view's bottom safe area with 20 spacing. Without this constraint, the calculated height for the footer view would be 0 as there is no constraint at the bottom

## Testing
- Launch the app with a store
- On "My store" tab, tap the Settings icon on the top right
- Scroll to the bottom where the footer is with `Made with Love by Automattic`
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the Settings footer view --> The view should not be covered with larger font sizes

## Example screenshots

portrait | landscape
--- | ---
Simulator Screen Shot - iPhone Xʀ - 2019-06-25 at 09 38 51 | Simulator Screen Shot - iPhone Xʀ - 2019-06-25 at 09 38 54
Simulator Screen Shot - iPhone Xʀ - 2019-06-25 at 09 38 33 | Simulator Screen Shot - iPhone Xʀ - 2019-06-25 at 09 38 36
Simulator Screen Shot - iPhone Xʀ - 2019-06-25 at 09 38 00 | Simulator Screen Shot - iPhone Xʀ - 2019-06-25 at 09 38 04

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/Classes/Extensions/UIViewController+TableViewHelpers.swift [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import UIKit
+
+extension UIViewController {
+    /// Called in `viewDidLayoutSubviews`. If input table view has a footer view, calculates the new height.
+    /// If new height is different from current height, updates the footer view with the new height and reassigns the table footer view.
+    /// Note: make sure the top-level footer view (`tableView.tableFooterView`) is frame based as a container of the Auto Layout based subview.
+    ///
+    /// - Parameter tableView: a table view that is a subview of the view controller.
+    func updateFooterHeight(for tableView: UITableView) {
```
Comment (ctarda) [inline WooCommerce/Classes/Extensions/UIViewController+TableViewHelpers.swift]: How would you feel about making this an extension of UITableView instead of UIViewController? Somehow it seems to me like that would be more cohesive

Comment (jaclync) [reply WooCommerce/Classes/Extensions/UIViewController+TableViewHelpers.swift]: yep good question, it's not dependent on the view controller. will update!

Comment (jaclync) [reply WooCommerce/Classes/Extensions/UIViewController+TableViewHelpers.swift]: updated in https://github.com/woocommerce/woocommerce-ios/pull/1048/files/eb4707d17249f99fd6789eee7cca5041f4f423fd#diff-acdc002fddfcc830a3990d003accddb5

**Comment by jaclync** [comment]
merging after updating based on CR suggestion & fixing merge conflicts!
