### PR TITLE
IPP Analytics: track Interac events

### LINKED ISSUE #6655: [Mobile Payments] New Interac analytic events for Canada IPP launch
These events are the highest priority to be done pre-launch, so I've broken them out of this ticket to make prioritisation clearer...

## New events

Event | Properties | Trigger | PR
-- | -- | -- | --
*_card_interac_collect_payment_success | `plugin_slug`, `card_reader_model`, `country` | Tracked right after processing succeeds. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_success | `plugin_slug`, `card_reader_model`, `country` | Tracked when an Interac in-person refund succeeds on the client side. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_failed | `error`, `plugin_slug`, `card_reader_model`, `country` | Tracked when an Interac in-person refund fails on the client side. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_cancelled | `plugin_slug`, `card_reader_model`, `country` | Tracked when the user cancels an Interac in-person refund before it's complete.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/issues/5984#issuecomment-1099969660_

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #6655 

### Description

Please note that there is a p2 post pdfdoF-ET-p2 with next steps that might change the collect payment flow updated in this PR.

This PR tracks 3 new events for Moose on the Loose for Interac payment method:

Event | Properties | Trigger
-- | -- | --
*_card_interac_collect_payment_success | | Tracked right after processing succeeds.
*_interac_refund_success | | Tracked when an Interac in-person refund succeeds on the client side.
*_interac_refund_failed | error | Tracked when an Interac in-person refund fails on the client side.

The trickiest part is to track `*_card_interac_collect_payment_success`, which is logged right after client-side processing. However, the client-side processing code is currently in a chain of steps:

https://github.com/woocommerce/woocommerce-ios/blob/d5586d2cf086852b4438fed953f9aaa0429dddc4/Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift#L236-L247

After client-side processing, there is still one step to wait for chip card removal before server-side processing as in the full collect payment flow below.

ipp-collect-payment-detailed-background

In order to track `*_card_interac_collect_payment_success` right after client-side processing, I added another publisher `processingCompleted: AnyPublisher<PaymentIntent, Never>` to return in addition to the original `future`. If the proposed iOS changes in pdfdoF-ET-p2 are approved, then we are probably going to return the `future` after client-side processing and then wait for chip card removal and dispatch server-side processing in parallel.

### Testing instructions

Prerequisites: the store is in Canada and eligible for IPP (setup instructions PdfdoF-D-p2)

- Go to the orders tab
- Create an order or a simple payment
- Go to order details
- Tap “Collect Payment” CTA
- Connect to a WisePad 3 card reader
- Insert the Interac test card and enter the pin code --> after the "Remove card" prompt appears, you should see `🔵 Tracked card_interac_collect_payment_success, properties: [AnyHashable("country"): "CA", AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("plugin_slug"): "woocommerce-payments", ...]` in the console
- Remove the Interac test card
- Back in order details, tap "Issue Refund" CTA
- Try inserting a non-Interac card to generate an error --> after the "Remove card" prompt appears, you should see `🔵 Tracked interac_refund_failed, properties: [AnyHashable("country"): "CA", AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("plugin_slug"): "woocommerce-payments", ...]` in the console
- Remove the card in the previous step
- Tap "Try again" to retry refund
- Insert the Interac test card and enter the pin code --> after the "Remove card" prompt appears, you should see `🔵 Tracked interac_refund_success, properties: [AnyHashable("country"): "CA", AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("plugin_slug"): "woocommerce-payments", ...]` in the console

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Hardware/Hardware/CardReader/CardReaderService.swift [hunk 1]
```diff
@@ -38,7 +38,9 @@ public protocol CardReaderService {
 
     /// Captures a payment after collecting a payment method succeeds.
     /// The returned publisher will behave as a Future, eventually producing a single value and finishing, or failing.
-    func capturePayment(_ parameters: PaymentIntentParameters) -> AnyPublisher<PaymentIntent, Error>
+    func capturePayment(_ parameters: PaymentIntentParameters) ->
+    (future: AnyPublisher<PaymentIntent, Error>,
```
Comment (toupper) [inline Hardware/Hardware/CardReader/CardReaderService.swift]: nit: I am wondering, could we return Combine's `Future` type there instead of `AnyPublisher`? Since we are already revealing the type of `Publisher` we are returning, it would be even more clear if we specify the type.

File: Hardware/Hardware/CardReader/CardReaderService.swift [hunk 2]
```diff
@@ -38,7 +38,9 @@ public protocol CardReaderService {
 
     /// Captures a payment after collecting a payment method succeeds.
     /// The returned publisher will behave as a Future, eventually producing a single value and finishing, or failing.
```
Comment (toupper) [inline Hardware/Hardware/CardReader/CardReaderService.swift]: I wonder why we need two publishers here instead of just one that is updated with all the events (maybe in an enum?):

- processPaymentCompleted
- cardWasRemoved (or finish in that case)
- errors
- ...
- 😎 

If that is not feasible, could we document that we are now returning a tuple instead of a publisher, and what is the point of each tuple property? Furthermore, as I see it, the future is triggered when the card is removed? I would rename the tuple somehow property to include this meaning. 😄

**Comment by toupper** [comment]
Great job @jaclync 🚀 ! I added a couple of comments. 

I tested it successfully, I have one question though: 

`🔵 Tracked card_interac_collect_payment_success, properties: [AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("blog_id"): 205293073, AnyHashable("is_wpcom_store"): true, AnyHashable("country"): "CA"]` ✅ 

`🔵 Tracked interac_refund_failed, properties: [AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("country"): "CA", AnyHashable("error_domain"): "Hardware.CardReaderServiceError", AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("error_description"): "Hardware.CardReaderServiceError.refundPayment(underlyingError: Hardware.UnderlyingError.processorAPIError)", AnyHashable("blog_id"): 205293073, AnyHashable("error_code"): "9", AnyHashable("is_wpcom_store"): true] ✅ `

```
🔵 Tracked interac_refund_success, properties: [AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("country"): "CA", AnyHashable("blog_id"): 205293073, AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("is_wpcom_store"): true]
2022-04-19 16:51:36.721574+0200 WooCommerce[455:14257] 🔵 Tracked refund_create, properties: [AnyHashable("method"): "ITEMS", AnyHashable("is_full"): "false", AnyHashable("is_wpcom_store"): true, AnyHashable("gateway"): "woocommerce_payments", AnyHashable("order_id"): "43", AnyHashable("amount"): "10", AnyHashable("blog_id"): 205293073] ✅ 
```
❓ Note here that right after the `interac_refund_success` another event was triggered `refund_create`, which didn't happen when failed, is that OK?

Furthermore, do we need unit tests for these cases?

Thanks a lot!!

File: Hardware/Hardware/CardReader/CardReaderService.swift (hunk 1 above)
Comment (jaclync) [reply Hardware/Hardware/CardReader/CardReaderService.swift]: Yea it'd be nice if we can return a `Future` to ensure the one-time completion behavior. Unfortunately, I don't think we can keep the `Future` type after chaining multiple `Future`s with `flatMap` as in the current implementation 😞 I think we could update each step in the chain to a completion block (or even better with async/await when we can use it) and chain them in a single `Future`, but that might be too big of a change. Curious to hear what you think about this and I can create a separate task to refactor this!

**Comment by jaclync** [comment]
> ❓ Note here that right after the `interac_refund_success` another event was triggered `refund_create`, which didn't happen when failed, is that OK?

From documentation on `refund_create` in the events spreadsheet:
> A refund request was submitted to the API 

Since the Interac refund already failed at client-side, a refund API request to the site wasn't needed anymore and thus `refund_create` wasn't logged 🙂 

> Furthermore, do we need unit tests for these cases?

Great reminder! I wasn't sure about adding test cases since we might change the flow per next steps in pdfdoF-ET-p2. Now that we know that we can try making card removal and server-side processing in parallel, I will update the PR to make it easier for the future change with unit tests 👍

File: Hardware/Hardware/CardReader/CardReaderService.swift (hunk 2 above)
Comment (jaclync) [reply Hardware/Hardware/CardReader/CardReaderService.swift]: I was really hoping not to make a separate publisher since it just looks so odd and confusing, but I also didn't want to break the existing behavior which is a Future that only triggers completion once as in the original documentation. As you said, the future is only triggered when the card is removed as the last step. However, since we need to log the event in the previous step (client-side processing) we need a separate publisher if we don't want to affect the usage of the main publisher 😓 

I think this tuple of publishers is just too confusing, I'm going to update the PR to allow a future change to run card removal and server-side processing in parallel. Will update!

File: Hardware/Hardware/CardReader/CardReaderService.swift (hunk 1 above)
Comment (toupper) [reply Hardware/Hardware/CardReader/CardReaderService.swift]: Ah I see, thanks for the explanation!

>  I think we could update each step in the chain to a completion block (or even better with async/await when we can use it) and chain them in a single Future, but that might be too big of a change.

It is true that we wouldn't keep the `Future` type after chaining it with the `flatMap`. Maybe we can revisit it when we can use `async/await`, perhaps even using an `AsyncSequence` for tackling it :)

File: Hardware/Hardware/CardReader/CardReaderService.swift (hunk 2 above)
Comment (toupper) [reply Hardware/Hardware/CardReader/CardReaderService.swift]: Great! looking forward to seeing that update 👍

**Comment by jaclync** [comment]
@toupper I'm really sorry that this PR went over 500 diffs after adding unit tests 😞 in order to mock objects in the Hardware framework, which currently doesn't support [Copiable](https://github.com/woocommerce/woocommerce-ios/blob/trunk/docs/copiable.md) and [Fakeable](https://github.com/woocommerce/woocommerce-ios/blob/trunk/docs/fakeable.md), the code for the mocks is quite long.

In https://github.com/woocommerce/woocommerce-ios/pull/6665/commits/fed36d9f144be11132199f0ae9119ca22d821b50, I reverted the tuple return value from `CardReaderService.capturePayment` and separated `waitForInsertedCardToBeRemoved` (card removal as the last step) to a new function so that we can do analytics after client-side refund and also wait for card removal in parallel to server-side processing in the future.

Please share any feedback on the changes! 🙏

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 3]
```diff
@@ -207,6 +207,29 @@ extension StripeCardReaderService: CardReaderService {
...
     }
 
+    public func waitForInsertedCardToBeRemoved() -> Future<Void, Error> {
+        return Future() { [weak self] promise in
+            guard let self = self else {
+                return
+            }
+
+            // If there is no chip card inserted, it is ok to immediately return. The payment method may have been swipe or tap.
+            if !self.isChipCardInserted {
```
Comment (toupper) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift]: nit: Maybe this could be a guard:

```
guard self.isChipCardInserted else {
     return promise(.success(()))
}
```

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 4]
```diff
@@ -207,6 +207,29 @@ extension StripeCardReaderService: CardReaderService {
         }
     }
 
+    public func waitForInsertedCardToBeRemoved() -> Future<Void, Error> {
```
Comment (toupper) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift]: nit: Since it never fails we could have the declaration as

`public func waitForInsertedCardToBeRemoved() -> Future<Void, Never>`

That would be also meaningful for the clients of `CardReaderService`. But now I see that in `NoOpCardReaderService` it always fails right?

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 5]
```diff
@@ -207,6 +207,29 @@ extension StripeCardReaderService: CardReaderService {
...
+            guard let self = self else {
+                return
+            }
+
+            // If there is no chip card inserted, it is ok to immediately return. The payment method may have been swipe or tap.
+            if !self.isChipCardInserted {
+                return promise(.success(()))
+            }
+
+            self.timerCancellable = Timer.publish(every: 1, tolerance: 0.1, on: .main, in: .default)
```
Comment (toupper) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift:221]: Nice use of Timer Publisher instead of `Foundation` Timers! 👏

**Review by toupper — APPROVED** [review]

**Comment by toupper** [comment]
@jaclync LGTM 😄 I added a couple of nits, great job!

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift (hunk 5 above)
Comment (jaclync) [reply Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift:221]: Kudos to Allen on this https://github.com/woocommerce/woocommerce-ios/commit/55807d8791e9a71f2f398e332a6d65d6e64c2e8f 👏

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift (hunk 3 above)
Comment (jaclync) [reply Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift]: Nice catch! updated as part of https://github.com/woocommerce/woocommerce-ios/pull/6665/commits/f0b4a6f5e5c1845d840be7444a21dd483f433442

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift (hunk 4 above)
Comment (jaclync) [reply Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift]: > nit: Since it never fails we could have the declaration as
> 
> `public func waitForInsertedCardToBeRemoved() -> Future<Void, Never>`
> 
> That would be also meaningful for the clients of `CardReaderService`. But now I see that in `NoOpCardReaderService` it always fails right?

Great suggestion 👍 updated in https://github.com/woocommerce/woocommerce-ios/pull/6665/commits/f0b4a6f5e5c1845d840be7444a21dd483f433442. Since `waitForInsertedCardToBeRemoved` is the last step of the card reader connection and payment flow, it would not be executed if any of the previous steps fails with an error. Also, `NoOpCardReaderService` is only used in Mac Catalyst (which doesn't support payments) and is not officially available yet

**Comment by jaclync** [comment]
Thank you for the great questions to make our code better @toupper! Merging this now after some updates based on your feedback 😄
