### PR TITLE
[Woo POS] Fix extra padding appearing after removing the tab

### LINKED ISSUE #13432: [Woo POS] M2: Fix extra padding appearing after removing the tab
## Steps

1. Open Woo app (I use iPad Air 11 inch iOS 17.5 simulator)
2. Open Menu -> Point of Sale
3. Notice extra padding at the bottom
4. Rotate iPad / Click dots at the top
5. Notice it fixes

Probably we need to do some extra layout code when tabs are removed so the whole UI would be refreshed

## Video

https://github.com/user-attachments/assets/005392d4-06e5-43d7-ac0e-d78690db3be9

### LINKED ISSUE #13679: [Woo POS] Improvement: Extract `updateSharedConfiguration` to separate methods
Follow-up from https://github.com/woocommerce/woocommerce-ios/pull/13670#discussion_r1724646148

> I think we'd have problems if there was no tabBarController, but strictly there's no reason that this should prevent us from disabling the in app notifications – perhaps this should become an if let, or separated into another function.

When we switch modes between POS and App, we make some changes in the shared app delegate regarding the main tab and in-app notifications. If the initial guard does not pass, it would also make the notifications not work as expected, but technically there's no reason this should happen as both are separate bits of logic, they just happen when we switch modes.

It would be good to add some logs as well, just for support reference.

```
// MARK: - Helper method for WooCommerce POS
//
extension AppDelegate {
    func updateSharedConfiguration(_ isPointOfSaleActive: Bool) {
        // Show/hide app's tab bars
        guard let tabBarController = AppDelegate.shared.tabBarController else {
            return
        }
        tabBarController.tabBar.isHidden = isPointOfSaleActive
        tabBarController.selectedViewController?.view.layoutIfNeeded()

        // Enable/disable foreground in-app notifications
        if isPointOfSaleActive {
            ServiceLocator.pushNotesManager.disableInAppNotifications()
        } else {
            ServiceLocator.pushNotesManager.enableInAppNotifications()
        }
    }
}
```

We could simply do something like:
```
func updateSharedConfiguration(_ isPointOfSaleActive: Bool) {
    updateTabBarVisibility(isPointOfSaleActive)
    updateInAppNotifications(isPointOfSaleActive)
}
```

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #13432 
Closes: #13679

## Description
This PR addresses the issue of additional padding appearing in the bottom of the screen when we load the POS for first time. 

After some investigation the issue was reintroduced on [this PR](https://github.com/woocommerce/woocommerce-ios/pull/13671/), which replaces the `WooTabNavigationController` in the `HubMenu` for a `TabContainerController` in order to address a crash in the iOS18 beta when switching stores. It's not clear why, but this update seems to introduce other UI glitches across the app (for example some titles disappearing in other tabs) mainly due to the nested wrapping of UIKit and SwiftUI components, so this regression wasn't found during smoke testing the changes as these were focused on the app side.

I'd like some advice if this PR seems a good approach to resolve the issue, or perhaps this glitch is something we should leave out of M2 until we can test it more throughly (example: iOS18 beta and non-beta)

## Screenshots

https://github.com/user-attachments/assets/4eaaabb8-174a-4bcf-a432-6fe6ee41ca46

## Changes
- Adds a `viewSafeAreaInsetsDidChange` override to the `MainTabBarController` that resets its UIEdgeInsets when it's hidden. We call this override method specifically when updating the app's tab bar.
- We also close the enhancement request of #13679 by just separating the logic into different methods, this is pure refactoring and there's no changes in the logic.

## Testing information
- On an iPad Air 11 simulator, running iOS 17.5, open POS (it might happen with other devices and/or runtimes, I was only able to reproduce it with this specific setup)
- Observe the Loading screen does not "jump" slightly up while loading
- Add some items to the cart
- Observe that the `POSFloatingControlView` and the `Checkout` button do not re-position themselves upon tapping the `...` button at the top of the screen
- Exit the POS, re-enter
- Observe the same behaviour

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/221">20.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/MainTabBarController.swift [hunk 1]
```diff
@@ -183,6 +183,17 @@ final class MainTabBarController: UITabBarController {
         }
     }
 
+    override func viewSafeAreaInsetsDidChange() {
+        super.viewSafeAreaInsetsDidChange()
+
+        if tabBar.isHidden {
+            let bottomInset = 8.0
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/MainTabBarController.swift]: I've also attempted to set the `bottomInset` by calculating it via `-tabBar.frame.height + 8` but doesn't seem to play nice with the `POSFloatingControlView` and the `Checkout` button, as both elements seem to set themselves at different heights if we do so 🤔

Comment (staskus) [reply WooCommerce/Classes/ViewRelated/MainTabBarController.swift]: There are a few things I don't know if I understand:

1. Do you know why we need to put this code within `viewSafeAreaInsetsDidChange` override that we then call manually? Could we set `updateTabBarVisibility` directly within `updateTabBarVisibility` method?

2. Would setting `additionalSafeAreaInsets = .zero` for both cases be enough or we need that additional 8 inset when tab bar disappears?

File: WooCommerce/Classes/AppDelegate.swift [hunk 2]
```diff
@@ -279,14 +279,23 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
 //
 extension AppDelegate {
     func updateSharedConfiguration(_ isPointOfSaleActive: Bool) {
-        // Show/hide app's tab bars
-        guard let tabBarController = AppDelegate.shared.tabBarController else {
+        updateTabBarVisibility(isPointOfSaleActive)
```
Comment (staskus) [inline WooCommerce/Classes/AppDelegate.swift]: np;

Is there a good reason we put all this code within `AppDelegate`? If not, I suggest moving into a separate place. It could complement the changes you mentioned in this task:

> We also close the enhancement request of https://github.com/woocommerce/woocommerce-ios/issues/13679 by just separating the logic into different methods, this is pure refactoring and there's no changes in the logic.

image

**Review by staskus — COMMENTED** [review]
Thanks for the solution and all the work 👍 It's a weird issue. I'll continue looking at it. I admit, I don't quite understand how and why it works.

File: WooCommerce/Classes/ViewRelated/MainTabBarController.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/MainTabBarController.swift]: Great questions!
1. I don't think there's a good reason. Most likely comes from having narrow vision after trying multiple approaches. I've updated it here https://github.com/woocommerce/woocommerce-ios/pull/13785/commits/2c287f4178b29f699286605cc476b5e2e806a2fc so we don't need the override
2. We do, if we set it to .zero then we see the problem above. I'm not really sure why, but perhaps internal optimization? Like it doesn't apply insets if there are no changes to the default ones through the lifecycle.

File: WooCommerce/Classes/AppDelegate.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/AppDelegate.swift]: Another great question and a meme that goes into my Swift folder 😂 

At this point there's no reason to keep this in the AppDelegate, since we're calling its shared instance and the ServiceLocator's one we can just do this from anywhere. I've moved it to the HubMenu view model as it's where we setup the rest of services that we pass into the point of entry. Happy to update it if you think should go somewhere else instead!

Updated on https://github.com/woocommerce/woocommerce-ios/pull/13785/commits/649a33e56aae583a92e536f9c6c3602a5e9f1745

File: WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift [hunk 3]
```diff
@@ -214,11 +214,50 @@ final class HubMenuViewModel: ObservableObject {
...
+        mainTabBarController.tabBar.isHidden = isPointOfSaleActive
+
+        let bottomInset = 8.0
+        if mainTabBarController.tabBar.isHidden {
+            mainTabBarController.additionalSafeAreaInsets = UIEdgeInsets(top: 0, left: 0, bottom: bottomInset, right: 0)
+        } else {
+            mainTabBarController.additionalSafeAreaInsets = .zero
+        }
+
+        mainTabBarController.selectedViewController?.view.layoutIfNeeded()
```
Comment (staskus) [inline WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift]: Yes, you're right.

Setting a non-zero `additionalSafeAreaInsets` triggers a layout update we need. Given we don't want to actually have a larger additional safe area inset, I think we could compromise on setting it to `.leastNonzeroMagnitude`.

Also, we don't need to call `layoutIfNeeded` anymore.

Given how hacky a solution is, we should leave a good comment explaining the solution. 

```suggestion
        mainTabBarController.additionalSafeAreaInsets.bottom = isPointOfSaleActive ? .leastNonzeroMagnitude : .zero
```

I think the best solution in the future could be presenting POS as a modal, and not pushing it into navigatation stack. In this case it should be presented above tab controller and we would avoid any issues such as this.

Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift]: I think presenting as a modal can cause issues with presenting other modals, and calling `dismiss` on the environment. We don't do that much, because of `posModal`, but we might in future use those things more...

Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift]: > Setting a non-zero additionalSafeAreaInsets triggers a layout update we need. 

That sounds good, thanks for digging into this 🙇 It does work the same with a non-zero value indeed. 

In https://github.com/woocommerce/woocommerce-ios/pull/13785/commits/a44f15cb0a71c46b50d8b89b8546f2ed054ec996 we update the inset to use `.leastNonzeroMagnitude`, removed the call to `layoutIfNeeded`, and added a longer comment with a reference to this issue.

File: WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift [hunk 4]
```diff
@@ -233,18 +233,22 @@ private extension HubMenuViewModel {
         guard let mainTabBarController = AppDelegate.shared.tabBarController else {
             return
         }
-        // If hidden, modifies the safeAreaInsets so that the view controller's view can occupy the space left by the hidden tab bar.
-        // Otherwise resets safeAreaInsets
         mainTabBarController.tabBar.isHidden = isPointOfSaleActive
 
-        let bottomInset = 8.0
+        /*
```
Comment (staskus) [inline WooCommerce/Classes/ViewRelated/Hub Menu/HubMenuViewModel.swift:238]: 👍 🙇

**Review by staskus — APPROVED** [review]
Thanks for digging deep into this! We stepped onto some weird SwiftUI <-> UIKit issue that only happens on specific iOS versions. I think this workaround fix is appropriate.
