### PR TITLE
Xcode 15: Fix runtime warning for uploading media files

### LINKED ISSUE #11354: Xcode 15 runtime warning for multipart-form requests when uploading files
When building the app with Xcode 15 and running the simulator, uploading files causes a runtime warning:

> The request of a upload task should not contain a body or a body stream, use `uploadTask(with:fromFile:)` or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.

We might need to revise how we send the upload request to make sure not to attach an `httpBody`.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #11354 

## What

This PR adds a fix to get rid of the runtime warning for uploading media files on Xcode 15.

## Why
We were sending a non-empty `httpBody` for the upload requests. The compiler complains as it only processes the uploaded data, and the data sent in the `httpBody` is ignored.

## How
The fix is not to encode anything to send to the body of the upload requests. Specifically, I made the `encoding` optional for `DotcomRequest` to skip encoding request body for upload requests.

## Testing instructions

Prerequisite: to confirm the fix, please build and run the app on Xcode 15.
- Log in to a store and navigate to the Products tab.
- Select any existing product or create a new one.
- Upload at least one photo from the device and save the product.
- The photo should be uploaded successfully to the store media library and the product should be saved successfully. No runtime warning should be displayed on Xcode.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for working on this, Huong!

I tried testing this using application password login and see the following error while trying to upload image for a product.

```
The request of a upload task should not contain a body or a body stream, use `uploadTask(with:fromFile:)` or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```

**Comment by itsmeichigo** [comment]
Nice catch @selanthiraiyan! I added a new property to skip encoding body for RESTRequests in 6d4d9b45e15f763f504505fdf78a0ba7baee3ea1 and added new tests in a414d75f4769a77606ec7b3994aaf9b61e4a1af3. This PR is ready for another look.

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for fixing it, @itsmeichigo!

To discuss a different approach, I think making the `parameters` value `nil` in both `DotcomRequest` and `RESTRequest` will prevent the body from having unnecessary value. 

I tried the above solution in [this branch](https://github.com/woocommerce/woocommerce-ios/compare/try/parameter-nil?expand=1). Kindly let me know your thoughts.

**Comment by itsmeichigo** [comment]
Thanks @selanthiraiyan! I've pushed new changes following your suggestions - please take a look at them when you can.

File: Networking/Networking/Requests/RESTRequest.swift [hunk 1]
```diff
@@ -88,6 +88,9 @@ struct RESTRequest: Request {
             .filter { $0.isEmpty == false }
         let url = try components.joined(separator: "/").asURL()
         let request = try URLRequest(url: url, method: method)
+        guard let parameters else {
+            return request
+        }
```
Comment (selanthiraiyan) [inline Networking/Networking/Requests/RESTRequest.swift]: I think we don't have to return here because the `encode` methods from `JSONEncoding` and  `URLEncoding` will return the `urlRequest` when `parameters` is nil.

File: Networking/Networking/Requests/DotcomRequest.swift [hunk 2]
```diff
@@ -96,7 +97,11 @@ struct DotcomRequest: Request, RESTRequestConvertible {
     func asURLRequest() throws -> URLRequest {
         let dotcomURL = URL(string: Settings.wordpressApiBaseURL + wordpressApiVersion.path + path)!
         let dotcomRequest = try URLRequest(url: dotcomURL, method: method, headers: headers)
-        return try encoding.encode(dotcomRequest, with: parameters)
+        if let parameters {
+            return try encoding.encode(dotcomRequest, with: parameters)
+        } else {
+            return dotcomRequest
+        }
```
Comment (selanthiraiyan) [inline Networking/Networking/Requests/DotcomRequest.swift]: Same as the other comment. I think we don't have to include this change as `encoding.encode(dotcomRequest, with: parameters)` won't alter the request if `parameters` is nil.

File: Networking/Networking/Requests/DotcomRequest.swift [hunk 3]
```diff
@@ -69,6 +69,7 @@ struct DotcomRequest: Request, RESTRequestConvertible {
     ///     - path: RPC that should be executed.
     ///     - parameters: Collection of String parameters to be passed over to our target RPC.
     ///     - headers: Headers used in the URLRequest
+    ///     - encoding: How the parameters are encoded. Default to use `URLEncoding`.
```
Comment (selanthiraiyan) [inline Networking/Networking/Requests/DotcomRequest.swift:72]: We can remove this comment.

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for the updates, Huong! 

I added a comment about always calling the `encode` method without having to check the `parameters`. I suggest this because `encode` method of different encoding types return the request without adding body when `parameters` is nil.

Kindly let me know your thoughts.

File: Networking/Networking/Requests/RESTRequest.swift (hunk 1 above)
Comment (itsmeichigo) [reply Networking/Networking/Requests/RESTRequest.swift]: Good point! Updated in 90fcb74f9948848c27b2251fe81495b3dccb2fd3.

File: Networking/Networking/Requests/DotcomRequest.swift (hunk 2 above)
Comment (itsmeichigo) [reply Networking/Networking/Requests/DotcomRequest.swift]: Also updated in 90fcb74f9948848c27b2251fe81495b3dccb2fd3.

File: Networking/Networking/Requests/DotcomRequest.swift (hunk 3 above)
Comment (itsmeichigo) [reply Networking/Networking/Requests/DotcomRequest.swift:72]: I think we can keep this because `encoding` is a param in the initializer so it should be documented.

Comment (selanthiraiyan) [reply Networking/Networking/Requests/DotcomRequest.swift:72]: Oh right. 👍

**Review by selanthiraiyan — APPROVED** [review]
Thanks for the updates, Huong! 🎉
