### PR TITLE
[Woo POS] M2: Fix extra padding appearing after removing the tab

### LINKED ISSUE #13432: [Woo POS] M2: Fix extra padding appearing after removing the tab
## Steps

1. Open Woo app (I use iPad Air 11 inch iOS 17.5 simulator)
2. Open Menu -> Point of Sale
3. Notice extra padding at the bottom
4. Rotate iPad / Click dots at the top
5. Notice it fixes

Probably we need to do some extra layout code when tabs are removed so the whole UI would be refreshed

## Video

https://github.com/user-attachments/assets/005392d4-06e5-43d7-ac0e-d78690db3be9

### PR DESCRIPTION
**Pull request by bozidarsevo**
Closes: #13432

## Description

- There was an issue with the POS view layout when we initially enter POS.
- We are hiding the tabbar when we are entering POS but the system does not layout the view properly (probably some Swiftui and UIKit combo issue), so there was a need for calling `layoutIfNeeded` on the current tabBarViewControllers viewController.

## Testing information

- Open Woo app
- Open Menu -> Point of Sale
- Check that there is no extra bottom space below the floating action control

## Screenshots

| Before      | After |
| ----------- | ----------- |
| Simulator Screenshot - iPad Pro (11-inch) (4th generation) 17 2 - 2024-08-09 at 11 47 34      | Simulator Screenshot - iPad Pro (11-inch) (4th generation) 17 2 - 2024-08-09 at 11 44 35       |

fab toolbar

---
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/AppDelegate.swift [hunk 1]
```diff
@@ -278,6 +278,7 @@ extension AppDelegate {
             return
         }
         tabBarController.tabBar.isHidden = hidden
+        tabBarController.selectedViewController?.view.layoutIfNeeded()
```
Comment (staskus) [inline WooCommerce/Classes/AppDelegate.swift:281]: 😀 classic, never disappoints

**Review by staskus — APPROVED** [review]
Thanks for fixing this. 🚀  It was a super annoying issue!

**Comment by bozidarsevo** [comment]
I see this it is not working any more, @staskus did we do any changes that might need some other fixing approach?

**Comment by iamgabrielma** [comment]
> I see this it is not working any more, @staskus did we do any changes that might need some other fixing approach?

Yeah, unfortunately the issue this time has regressed due to what seems to be a fix for a crash in the Tab menu in the iOS18 beta when switching stores, but nothing specific to the work on POS. I'll write up a slack thread or P2 shortly, since fixing it carries a bit more risk 👍
