### PR TITLE
Fix placeholders in dashboard charts and orders tab

### LINKED ISSUE #2801: Orders tab > placeholder state: empty cells show below the placeholder cells & header background color is different from the space below the placeholder cells
**Describe the bug**

On the Orders tab, the space above the placeholder cells has a different background color from the space below in both light and dark mode.

**To Reproduce**

- Launch the app or switch store so that the placeholder state is shown
- Go to the orders tab --> notice the background color of the space above and below the placeholder cells, and there are empty cells with dividers below the placeholder cells

**Screenshots**

\ | light | dark
-- | -- | --
Orders tab | Simulator Screen Shot - iPhone 11 - 2020-09-11 at 11 28 10 | Simulator Screen Shot - iPhone 11 - 2020-09-11 at 11 31 35
Reviews tab (for reference) | Simulator Screen Shot - iPhone 11 - 2020-09-11 at 11 29 18 | Simulator Screen Shot - iPhone 11 - 2020-09-11 at 11 31 38

**Expected behavior**

The background color of the space above and below the placeholder cells should be the same, and there should be no cell dividers below the placeholder cells.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11 simulator
- iOS version: iOS 13.5
- WooCommerce iOS version: any

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### LINKED ISSUE #3043: iOS 14: some ghost views have light background color in dark mode
**Describe the bug**

When building from Xcode 12 to an iOS 14 simulator/device, one ghost view on the dashboard and orders tab that we show when data are loading have unexpected light background color in dark mode. This does not happen in iOS 13.

**To Reproduce**

- Launch the app in iOS 14 simulator/device from Xcode 12 & dark mode --> notice that one ghost view on the dashboard tab has light background
- Go to the orders tab when the data are still loading --> notice that the section header view has light background

**Screenshots**

dashboard tab| orders tab
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-22 at 14 37 26 | Simulator Screen Shot - iPhone 11 - 2020-10-22 at 17 13 32

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11 simulator
- iOS version: iOS 14.0
- WooCommerce iOS version: 5.4

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #2801 
Fixes #3043 

These dark mode color / placeholder bugs have been bugging me for a while (felt like broken windows)!

## Changes

I'm guessing the default background color in some views got changed in iOS 14, so that it shows white background color in some placeholder views in dark mode only in iOS 14 (both iOS 14.0 and 14.1).

- Fixed the white background color in chart placeholder view (`ChartPlaceholderView`) by setting the top stack view's background color explicitly.
- In `OrderListViewController`, updated its ghostable table view from the default `plain` style to `grouped` to remove empty cells (#2801) and then disabled section header now that it's a grouped table view with padding at the top.

## Testing

The best way to see placeholder state without manual code changes is to switch to another store. I also tested in iOS 13.1 simulator in both light and dark mode.

- Launch the app in **iOS 14** sim/device and **dark mode**
- Switch to another store --> the chart placeholder view should look good (no unexpected white background color)
- Go to the orders tab --> the placeholder table view should look good (no empty cells below and no unexpected white background color above the placeholder cells)

## Example screenshots

before | after
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-27 at 17 05 10 | Simulator Screen Shot - iPhone 11 - 2020-10-27 at 16 37 23
Simulator Screen Shot - iPhone 11 - 2020-10-27 at 17 05 12 | Simulator Screen Shot - iPhone 11 - 2020-10-27 at 16 56 37

Light mode screenshots

dashboard tab | orders tab
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-27 at 16 37 59 | Simulator Screen Shot - iPhone 11 - 2020-10-27 at 16 57 00

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/MyStore/ChartPlaceholderView.swift [hunk 1]
```diff
@@ -31,6 +31,7 @@ private extension ChartPlaceholderView {
     ///
     func setupView() {
         backgroundColor = .listForeground
+        topStackView.backgroundColor = .listForeground
```
Comment (Ecarrion) [inline WooCommerce/Classes/ViewRelated/Dashboard/MyStore/ChartPlaceholderView.swift:34]: Oh! Until iOS 13 stack views didn't have any renderable background-color, nice to see that changed on iOS 14!

**Review by Ecarrion — APPROVED** [review]
Thank you for doing this! 🚀 🚀 🚀

File: WooCommerce/Classes/ViewRelated/Dashboard/MyStore/ChartPlaceholderView.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Dashboard/MyStore/ChartPlaceholderView.swift:34]: Ooh right, this is a new change in iOS 14! (a [blog post](https://useyourloaf.com/blog/stack-view-background-color-in-ios-14/) about it) That explains the bug, the stack view's background color is set to white in the xib
