### PR TITLE
Core Data Stack updates

### LINKED ISSUE #2370: Untangle Core Data Setup and CrashLogging
Found by @jaclync in p91TBi-2PM-p2#comment-860. When CrashLogging is initialized, the Core Data setup is also unexpectedly started because of this line: 

https://github.com/woocommerce/woocommerce-ios/blob/a10080aa477ba4388c7af5eb63f70ec813ddafd9/WooCommerce/Classes/Tools/Logging/CrashLogging.swift#L17-L24

### LINKED ISSUE #14054: Update Core Data Stack following WP/JP
- Make the background context independent of the view context.
- Add new helper methods for enforcing writing in background context.
- Mark old access to writerDerivedStorage and saveDerivedStorage as deprecated.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #14054 
Also closes: #2370 

## Description

This PR adds a few improvements to the Core Data stack: 
- Updated the `writerDerivedStorage` to be independent of the main context. Instead, the background context is now directly associated with the persistent container following Apple's [recommendation](https://href.li/?https://developer.apple.com/documentation/coredata/using_core_data_in_the_background#2904035). The main context now merges changes from the persistent container automatically.
- A writer operation queue has been introduced to take care of write operations one-by-one following WP/JP's implementation [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/d30b801b5be1f23db0f2143a27389f0966f27a7e/WordPress/Classes/Utility/ContextManager.swift#L118). I'm following the simple variation for the completion handler without the result parameter as we don't currently have any failure handling for the write operations - I suppose we can add that variation when we need it.
- Removed the unused method `performBackgroundTask` - we want to avoid creating too many background context through this method.
- Updated `saveDerivedType` to only save the background context to the persistent container.
- Marked access to `writerDerivedStorage` and `saveDerivedType` as deprecated and added a helper method `performAndSave` for performing write operations similarly to WP/JP's Core Data stack. Updates for the stores will be handled in future PRs.
- Added check to ensure write operations are handled in a background context. The checks are handled in debug mode only, and a new launch argument `-enforce-core-data-write-in-background` has been added to enable `assert` when writing is done on the main context.
- Initialize the storage manager along with `AppDelegate` to ensure that the Core Data stack is created before the stores manager. This is an attempt to eliminate confusing stack traces [peaMlT-Rx-p2#comment-2194]. The order of initialization should now be as follows: CrashLogging > CoreDataManager > DefaultStoresManager.
- Keep product's `date` and `dateCreated` Swift properties optional to avoid crashes when transforming deleted product objects in Core Data.

TODO: @itsmeichigo to update the release notes before merging.

## Steps to reproduce

Smoke testing the app
- With `-enforce-core-data-write-in-background` disabled, build and run the app in debug mode. 
- Log in to a test store with existing products/orders/Blaze campaigns.
- Smoke test the app following the guide P91TBi-bVe-p2.

Testing enforcing write in background
- With `-enforce-core-data-write-in-background` enabled, build and run the app in debug mode. 
- Log in to a test store with existing products/orders/Blaze campaigns.
- Confirm that the `assert` causes a fatal error where a write operation is handled in the main context.

## Testing information

Tested on device iPad pro 4th gen iOS 17.6:
- Logged in to an atomic store with wpcom account successfully.
- Confirmed that dashboard works as before: stats cards with different time ranges, all cards enabled with different filters.
- Confirmed that orders work normally: pagination, searching, order creation and edit, creating shipping labels, marking orders as complete.
- Confirmed that products work normally: pagination, searching, bulk update, product creation with AI, creating & editing variable products, updating product details.
- Confirmed that hub menu works normally: store switching, settings, payments, google ads, blaze, woo admin, view store, coupons, reviews, inbox, customers.

Tested on simulator iPhone 15 Pro iOS 17.4 and `-enforce-core-data-write-in-background` enabled and confirmed that write operations in the main context causes assertion failure.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift [hunk 1]
```diff
@@ -175,4 +178,16 @@ extension NSManagedObjectContext: StorageType {
     private func fetchRequest<T: Object>(forType type: T.Type) -> NSFetchRequest<NSFetchRequestResult> {
         return NSFetchRequest<NSFetchRequestResult>(entityName: type.entityName)
     }
+
+    /// Helper to trigger failure in debug mode or print warning when write operations are called from the view context (main thread).
```
Comment (shiki) [inline Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift:185]: Do you think using compiler flags would be better? As far as I know, this method will still be part of the production code. But compiler flags could ensure they don't show up in production.

Comment (itsmeichigo) [reply Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift:185]: I moved the content of the method inside a `#if DEBUG` check to make the code run only in debug.

**Comment by itsmeichigo** [comment]
Moved the milestone to 20.8 to avoid causing any issue during the Woo DM. Other PRs will be based on top of this PR and merged gradually after this PR is merged.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/228">20.8</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift (hunk 1 above)
Comment (shiki) [reply Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift:185]: Thanks! I'm gonna let @selanthiraiyan review this. 🙂

File: Storage/Storage/CoreData/CoreDataManager.swift [hunk 2]
```diff
@@ -59,16 +65,20 @@ public final class CoreDataManager: StorageManagerType {
     /// Returns the Storage associated with the View Thread.
     ///
     public var viewStorage: StorageType {
-        return persistentContainer.viewContext
+        let context = persistentContainer.viewContext
+        /// This simplifies the process of merging updates from persistent container to view context.
+        /// When disable auto merge, we need to handle merging manually using `NSManagedObjectContextDidSave` notifications.
+        context.automaticallyMergesChangesFromParent = true
```
Comment (selanthiraiyan) [inline Storage/Storage/CoreData/CoreDataManager.swift:71]: nit: Kindly consider adding a unit test to check that the view context is updated when we save data to the `writerDerivedStorage`. We may have to test both `saveDerivedType` and `performAndSave` methods. What do you think?

File: Storage/Storage/CoreData/CoreDataManager.swift [hunk 3]
```diff
@@ -130,25 +140,36 @@ public final class CoreDataManager: StorageManagerType {
...
+    ///         by the `block` is saved.
+    ///   - queue: A queue on which to execute the completion block.
+    public func performAndSave(_ closure: @escaping (StorageType) -> Void, completion: (() -> Void)?, on queue: DispatchQueue) {
+        let derivedStorage = writerDerivedStorage
+        self.writerQueue.addOperation(AsyncBlockOperation { done in
+            derivedStorage.perform {
+                closure(derivedStorage)
+
+                derivedStorage.saveIfNeeded()
+                queue.async { completion?() }
```
Comment (selanthiraiyan) [inline Storage/Storage/CoreData/CoreDataManager.swift:169]: Super nit: I think we could add unit tests for each of these method calls. i.e. Ensure that closure is called, the `derivedStorage` is saved and the completion block is called. WDYT?

File: Storage/Storage/CoreData/CoreDataManager.swift [hunk 4]
```diff
@@ -323,3 +344,66 @@ extension CoreDataManagerError: CustomStringConvertible {
...
     }
 }
+
+/// Helper types to support writing operations to be handled one by one.
+/// This implementation follows WP/JP's work at
+/// WordPress/Classes/Utility/ContextManager.swift#L131
+///
+extension CoreDataManager {
+    /// Helper type to support handling async operations by keeping track of their states
+    class AsyncOperation: Operation {
```
Comment (selanthiraiyan) [inline Storage/Storage/CoreData/CoreDataManager.swift:354]: I compared this code with the JP/WP repo, and these changes LGTM.

File: WooCommerce/Classes/AppDelegate.swift [hunk 5]
```diff
@@ -191,7 +194,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
 
             // When the app is put into an incative state, it's important to ensure that any pending changes to
             // Core Data context are saved to avoid data loss.
-            ServiceLocator.storageManager.viewStorage.saveIfNeeded()
+            storageManager.viewStorage.saveIfNeeded()
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/AppDelegate.swift]: I am trying to understand whether we still need to save the `viewStorage` during app transitions. 

As per my understanding,

- We always perform the write operations to the `writerDerivedStorage`. 
- The `viewContext` will automatically receive these changes as we have set `automaticallyMergesChangesFromParent` as true on `viewContext`. 
- The `viewContext` should never have changes that are different from the `persistentContainer` that needs to be saved before quitting the app. 

What do you think? 

Tagging @pmusolino as he authored the changes [here](https://github.com/woocommerce/woocommerce-ios/pull/13247)

**Review by selanthiraiyan — APPROVED** [review]
Thanks for working on this, Huong! 👏 

The changes LGTM, and it works well on an iPhone simulator running iOS 17.4. 

I left a few non-blocking suggestions and questions.

File: WooCommerce/Classes/AppDelegate.swift (hunk 5 above)
Comment (pmusolino) [reply WooCommerce/Classes/AppDelegate.swift]: As mentioned in the reference of my PR peaMlT-Jf#comment-1773, this is used also in example provided by Apple. There does not have to be changes, so it is just an extra check to be sure, in fact it will only be saved if there really are changes, otherwise it will do nothing.

Comment (selanthiraiyan) [reply WooCommerce/Classes/AppDelegate.swift]: Thanks, @pmusolino! 

As I explained earlier, I think the `viewContext` will not have any changes to save, and I propose removing this code. If you and @itsmeichigo agree, we can add a subtask and deal with it as part of the core data usage update project.

Comment (itsmeichigo) [reply WooCommerce/Classes/AppDelegate.swift]: I agree, and I can remove these lines in this PR directly. `saveIfNeeded` has been marked as deprecated already and we should be saving changes in the background context right after the write operations.

File: Storage/Storage/CoreData/CoreDataManager.swift (hunk 2 above)
Comment (itsmeichigo) [reply Storage/Storage/CoreData/CoreDataManager.swift:71]: Hey @selanthiraiyan - `saveDerivedType` is marked as deprecated (in `StorageManagerType`), so I believe it's redundant to add tests for it. As for `performAndSave`, I added tests in #14090 - back-merging can be complicated due to how the branches are based on each other. We'll have to wait until that PR is merged for the tests to be in `trunk`. How does that sound?

File: Storage/Storage/CoreData/CoreDataManager.swift (hunk 3 above)
Comment (itsmeichigo) [reply Storage/Storage/CoreData/CoreDataManager.swift:169]: This should be covered in the tests added in #14090. Let me know if those tests are what you expect.

File: WooCommerce/Classes/AppDelegate.swift (hunk 5 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/AppDelegate.swift]: Done in e6e644d9d5f50c092f73b351d9361b812faa20ea.

**Comment by itsmeichigo** [comment]
Thanks @selanthiraiyan for the reviews! I responded to your comments regarding the unit tests, let me know what you think. I'll merge the PR once I get another green light from you.

File: Storage/Storage/CoreData/CoreDataManager.swift (hunk 2 above)
Comment (selanthiraiyan) [reply Storage/Storage/CoreData/CoreDataManager.swift:71]: I agree. Thanks, Huong!

File: Storage/Storage/CoreData/CoreDataManager.swift (hunk 3 above)
Comment (selanthiraiyan) [reply Storage/Storage/CoreData/CoreDataManager.swift:169]: Sorry, the given GH link #14090 opens an issue. Could you let me know if you meant to link a PR there?

Comment (itsmeichigo) [reply Storage/Storage/CoreData/CoreDataManager.swift:169]: Oops sorry - I meant #14099  @selanthiraiyan

Comment (selanthiraiyan) [reply Storage/Storage/CoreData/CoreDataManager.swift:169]: Those tests look great. Thanks!

**Review by selanthiraiyan — APPROVED** [review]
Thanks for the updates and comments, Huong! Let us merge this PR. 🚢
