### PR TITLE
Reviews: Fix missing product information on first load

### LINKED ISSUE #1907: Reviews: First recent review for product can have "Unknown" product name
**Describe the bug**

After receiving a new review notification and opening the review details, the product name can show up as "Unknown." I found this most consistently happened for products that hadn't been shown recently in the app (no recent orders, hadn't viewed product details, didn't have another recent review).

In some cases, going back to the review list was sufficient for the product name to appear the next time I opened the review detail. But in other cases, navigating around the app and even force-closing and relaunching the app didn't resolve it. In those cases, the product name was also missing from the review in the reviews list.

In one case, I noticed that it was only resolved when I enabled the Products tab and scrolled down until that product was loaded in the products list. Then, when I went back to the review detail the product name appeared. Once it was fixed, any subsequent reviews for the same product worked as expected.

(This was also mentioned in https://github.com/woocommerce/woocommerce-ios/issues/1810 but I saw it separate from that issue.)

**To Reproduce**

1. Create a new review for a product you haven't viewed in the app recently (no orders or reviews, etc.).
2. Tap the push notification to open the review detail.
3. Notice that the product name in the review detail is "Unknown" and tapping it does not open a link to the product.
4. Go back to the reviews list and check if the review has the product name.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.7.0.0 TestFlight beta

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #1907 

### Description

Previously we were synchronizing reviews by concurrently fetching reviews, products, and notifications and waiting until all these requests succeed to complete the synching.

Fetching products requires a list of product IDs from the fetched reviews. So there's a potential issue: if the request to fetch products starts before the request to fetch reviews completes, we'll send a request to fetch products with an empty ID list. If we haven't fetched products for the store before, we'll end up with reviews without product information.

The solution is to only sync products after the review synching is done. Required product IDs are taken from the fetched reviews and sent directly to the product synching request. This leads to the need to change the return result of `synchronizeProductReviews` to the modern `Result` with a list of reviews (hence changes in Yosemite and Networking layers).

### Testing instructions

- Log out from your account and log back in.
- Switch immediately to the Menu tab and select Reviews.
- Notice that after loading is done, all the reviews have correct product information.

Note: you may find that the first fetch will take quite a while. We'll have to look into why it takes so long and optimize it.

### Screenshots

https://user-images.githubusercontent.com/5533851/156700129-872ac2a1-bbc0-43f0-9c65-4f0548ed624c.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift [hunk 1]
```diff
@@ -34,78 +34,81 @@ final class ProductReviewsRemoteTests: XCTestCase {
...
 
         // When
-        var result: (reviews: [ProductReview]?, error: Error?)
-        remote.loadAllProductReviews(for: sampleSiteID) { reviews, error in
-            result = (reviews, error)
+        var result: Result<[ProductReview], Error>?
+        remote.loadAllProductReviews(for: sampleSiteID) { loadResult in
+            result = loadResult
             expectation.fulfill()
         }
```
Comment (jaclync) [inline Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift]: nit: can save some unwrapping (similar for the other test cases in the diffs)

```suggestion
        let result: Result<[ProductReview], Error> = try waitFor { promise in
            remote.loadAllProductReviews(for: sampleSiteID) { result in
                promise(result)
            }
        }
```

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/Reviews/ProductReviewsViewModel.swift [hunk 2]
```diff
@@ -84,15 +84,15 @@ extension ProductReviewsViewModel {
...
-                                                                    onCompletion?()
+                                                                   status: .approved) { result in
+            switch result {
+            case .failure(let error):
+                DDLogError("⛔️ Error synchronizing reviews for product ID :\(productID). Error: \(error)")
+                ServiceLocator.analytics.track(.productReviewListLoadFailed, withError: error)
+            case .success:
+                ServiceLocator.analytics.track(.productReviewListLoaded)
+            }
+            onCompletion?()
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/Reviews/ProductReviewsViewModel.swift:95]: looks so much nicer with the modern `Result`!

File: WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift [hunk 3]
```diff
@@ -94,36 +121,85 @@ final class ReviewsViewModelTests: XCTestCase {
...
     }
+
+    func test_synchronizeReviews_triggers_retrieveProducts_with_all_reviewsProductIDs() {
+        // Given
+        let mockDataSource = MockReviewsDataSource()
+        let mocks = MockReviews()
+        let sampleReviews: [ProductReview] = [
+            mocks.review(injectedReviewID: sampleSiteID, injectedProductID: 55),
+            mocks.review(injectedReviewID: sampleSiteID, injectedProductID: 668),
+            mocks.review(injectedReviewID: sampleSiteID, injectedProductID: 789)
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift]: nit: how about adding `GeneratedCopiable` to `ProductReview` and using `copy` with Fakeable here? then we can move away from `MockReviews` (which we can replace with Fakeable and Copeable gradually)

```suggestion
            ProductReview.fake().copy(reviewID: sampleSiteID, productID: 55),
            ProductReview.fake().copy(reviewID: sampleSiteID, productID: 668),
            ProductReview.fake().copy(reviewID: sampleSiteID, productID: 789)
```

**Review by jaclync — APPROVED** [review]
Great catch, working nicely on a few different stores! :shipit:

File: Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift (hunk 1 above)
Comment (itsmeichigo) [reply Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift]: Updated in 75ae195675812bd7e3454ae8db51e041dc08e8a8 👍

File: WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift (hunk 3 above)
Comment (itsmeichigo) [reply WooCommerce/WooCommerceTests/Reviews/ReviewsViewModelTests.swift]: Good point! Updated in 6de17d180384cafbd14a7d4c0e9a331d5a558ec5
