### PR TITLE
Fix broken CurrencySettings unit test - Mark II

### LINKED ISSUE #1398: Unit Tests: `CurrencySettingTests` fail on first run
**Describe the bug**
The `testInitWithIndividualParameters` unit test in `CurrencySettingsTests` fails on the first run only. Any subsequent runs are fine. 

**To Reproduce**
This happens most often when I switch to a branch that's not mine, I have to run `bundle install`, followed by `bundle exec pod install`. After I install pods, I use Cmd + B to build, and then I run the unit tests. Getting Xcode in this specific state has been difficult to reproduce.

**Steps to reproduce the behavior:**
Unknown. Whatever requirement causes `bundle install` to be needed, sets the environment in the state that causes the unit test to fail. Deleting derived data doesn't seem to be enough. Cleaning the project doesn't trigger the unit test to fail either.

**Screenshots**

**Expected behavior**
I _think_ this is happening because `CurrencySettings` is a singleton, and the setUp() and teardDown() methods aren't impelmented.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #1398

Deauthentication forces log-out after running unit tests, which is not ideal because then it's impossible to test if data migrations are successful, because logging out clears the database. Reset moneyFormat and siteSettings after each unit test.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/Tools/CurrencySettingsTests.swift [hunk 1]
```diff
@@ -6,14 +6,21 @@ import Yosemite
 ///
 class CurrencySettingsTests: XCTestCase {
 
-    override func setUp() {
-        ServiceLocator.stores.deauthenticate()
+    var moneyFormat = CurrencySettings()
+    var siteSettings: [SiteSetting] = []
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/Tools/CurrencySettingsTests.swift]: nit: these properties could be private?

**Review by jaclync — APPROVED** [review]
The fix looks good!

**Review by pmusolino — APPROVED** [review]
LGTM :shipit:
