### PR TITLE
[Mobile Payments] Track IPP onboarding CTA plugin install failed

### LINKED ISSUE #10567: [Mobile Payments] Add tracking for IPP onboarding CTA failed
Ref: pdfdoF-3ED-p2

- [x] **_card_present_onboarding_cta_failed: plugin_install_tapped**
- [x] **_card_present_onboarding_cta_failed: plugin_activate_tapped**
- [x] **_card_present_onboarding_cta_failed: plugin_setup_tapped**
- [x] **_card_present_onboarding_cta_failed: stripe_account_setup_tapped**
```
event: *_card_present_onboarding_cta_failed
reason: plugin_install_tapped/plugin_activate_tapped/plugin_setup_tapped/stripe_account_setup_tapped
description: Whatever comes from the API
```

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #10567 . Based on #10565 

## Description
This PR adds the `card_present_onboarding_cta_failed` track event which will help us track when there's a failed outcome from tapping on a CTAs during the IPP onboarding flow, as well as improves the UX for state handling when install is called and fails.

At the moment, we're only tracking the case for `plugin_install_tapped` when the plugin installation fails. More cases will be added in future PRs.

Simulator Screen Recording - iPhone 11 Pro - 2023-09-04 at 11 51 16

## Testing instructions
1. On a WCPay eligible store, with WCPay not installed ( you can use https://atomicippwcpaytests.wpcomstaging.com/ ):

2. Change the plugin slug in `CardPresentPaymentsOnboardingUseCase` [here](https://github.com/woocommerce/woocommerce-ios/blob/64d42ea8e16c5c03047f604daa0061a4913b43a4/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/CardPresentPaymentsOnboardingUseCase.swift#L117) to a non-existent plugin slug:
```diff
- let pluginSlug = CardPresentPaymentsPlugin.wcPay.gatewayID
+ let pluginSlug = "so much fail"
```

3. Now go to `Menu` > `Payments` > See the notice at the bottom that says that `In-Person Payments setup is incomplete. Continue setup`. Tap the link.
4. Observe the following: 
* See the `Install WooCommerce Payments` button. Tap on Install
* The loading screen might appear (depends on how fast the failure happens)
* The following events are tracked:
* `card_present_onboarding_cta_tapped`, with reason `wcpay_not_installed`
```
2023-09-01 10:47:40.895200+0200 WooCommerce[25224:24233219] 🔵 Tracked card_present_onboarding_cta_tapped, properties: [AnyHashable("is_wpcom_store"): true, AnyHashable("was_ecommerce_trial"): false, AnyHashable("country"): "US", AnyHashable("reason"): "wcpay_not_installed", AnyHashable("blog_id"): 222904906, AnyHashable("plan"): "business-bundle"]
```
* `card_present_onboarding_cta_failed` with reason `plugin_install_tapped`, and `error_description` 
```
2023-09-01 11:07:21.617058+0200 WooCommerce[26632:24252223] 🔵 Tracked card_present_onboarding_cta_failed, properties: [AnyHashable("blog_id"): 222904906, AnyHashable("reason"): "plugin_install_tapped", AnyHashable("error_description"): "Dotcom Error: [plugins_api_failed] Plugin not found.", AnyHashable("country"): "US", AnyHashable("was_ecommerce_trial"): false, AnyHashable("is_wpcom_store"): true, AnyHashable("plan"): "business-bundle"]
```
* The generic error view is displayed (a more specific error view might be implemented in the future)
* Go back 2 steps to the `Menu` > tap on `Payments` > Tap on `Continue setup` again.
* See that `Install WooCommerce Payments` is available again. 

Note that at the moment we do not seem to refresh the onboarding state until we leave the Payments view, so the failure state will remain if we just go back and  tap on "Continue Setup" immediately. This is done for all flows, and might require further discussion outside of this project.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift [hunk 1]
```diff
@@ -518,6 +521,19 @@ private extension CardPresentPaymentsOnboardingUseCase {
...
 }
 
+// MARK: - Analytics
+private extension CardPresentPaymentsOnboardingUseCase {
+    func trackPluginInstallFailed(_ error: Error) {
+        guard let countryCode = self.storeCountryCode else {
+            DDLogError("Error installing plugin: \(error)")
+            return
+        }
+        ServiceLocator.analytics.track(event: .InPersonPayments.cardPresentOnboardingCtaFailed(reason: "plugin_install_tapped",
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift:531]: Since there's only one call to analytics I opted to use a ServiceLocator instance for now. I might change this to inject it into the initializer if we add more event tracking to the class. Happy to change it with this PR if you think is appropriate though 👍

File: WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift [hunk 2]
```diff
@@ -1820,6 +1820,22 @@ extension WooAnalyticsEvent {
...
+        ///   - reason: the reason why the onboarding step was shown (effectively the name of the step)
+        ///   - countryCode: the country code of the store
+        ///   - error: the logged error
+        ///
+        static func cardPresentOnboardingCtaFailed(reason: String, countryCode: String, error: Error) -> WooAnalyticsEvent {
+            WooAnalyticsEvent(statName: .cardPresentOnboardingCtaFailed,
+                              properties: [
+                                Keys.countryCode: countryCode,
+                                Keys.reason: reason,
+                                Keys.errorDescription: error.localizedDescription
```
Comment (toupper) [inline WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift]: I know that we do this with other events, but is it really beneficial to provide the localized description of the error? We get a bunch of strings in different languages, that we can't ascertain without further action. Furthermore, we can't group them either. I would try to make the events uniquely identifiable, perhaps with the error code.

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift (hunk 1 above)
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift:531]: Is `"plugin_install_tapped"` the reason why the onboarding cta failed? I would try to be more specific, Why did it actually fail? Or perhaps we want to add the context, in which case I would replace the "reason" property with "context". If we cannot provide extra information I would remove this property.

File: WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift]: That's a good point, I changed it here: https://github.com/woocommerce/woocommerce-ios/pull/10601/commits/b5c095c5dbe8f8e83ab49e982162d7efad17f37a so we don't pass the localized error as one of the properties, but the non-localized error itself to be tracked with the event.

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift:531]: Yes, we use the `reason` as the the CTA step since we're building on top of the existing ones ( context: pdfdoF-3HA#comment-4930-p2 ) and then details of the error itself are logged into the error description, in this case since they come from the API:

```Dotcom Error: [plugins_api_failed] Plugin not found```

We'll use the reason as well for future CTA failure steps, like `plugin_activate_tapped`, `plugin_setup_tapped`, or 
 `stripe_account_setup_tapped`

Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift:531]: Thanks for the answer and the link! What I referred to is more of a semantic question. We track these values as a `reason` for the failure:

```
plugin_install_tapped
plugin_activate_tapped
plugin_setup_tapped
stripe_account_setup_tapped
```

But in reality, I see these more like `context`, or `trigger`, than the reason why it failed. If we already tracked events with that key it's ok as it is, it's not worth to change it now :)

**Review by toupper — APPROVED** [review]
LGTM 🎉 🚢

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person Payments/CardPresentPaymentsOnboardingUseCase.swift:531]: > I see these more like context, or trigger, than the reason why it failed. If we already tracked events with that key it's ok as it is, it's not worth to change it now :)

Agree!
