### PR TITLE
Fix irresponsive button when connecting to an existing site

### LINKED ISSUE #13745: EXC_BREAKPOINT: Fatal error > WordPressAuthenticator/LoginViewController.swift
Sentry Issue: [WOOCOMMERCE-IOS-1MWK](https://a8c.sentry.io/issues/5517201305/?referrer=github_integration)

```
EXC_BREAKPOINT: Fatal error > WordPressAuthenticator/LoginViewController.swift
  File "SiteAddressViewController.swift", in closure in SiteAddressViewController.checkSiteExistence
  File "<compiler-generated>", in thunk for closure
  File "main.swift", line 7, in main
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13745 

## Description

The site discovery flow from the store picker uses the logic in the authenticator library, but there is no guarantee that the delegate for the authenticator is set when the flow starts. 

This PR ensures that a delegate is set to the authenticator when the site discovery flow starts to make the flow functional.

🗒️ No unit test was added as it's not straightforward to do so. Any suggestions are welcome.

## Steps to reproduce

Pre-requisite: set up a JN site with Woo but no Jetpack.
- Log in to the test store.
- Install and connect Jetpack from the Jetpack benefit banner.
- After the setup is completed, navigate to the store picker > connect to an existing site.
- Enter a random site address and tap Continue.
- Confirm that either an error screen or the Jetpack connect screen is presented.

## Testing information

Tested on simulator iPhone 15 iOS 17.4:
- Confirmed that the fix works after setting up Jetpack for a JCP site.
- Confirmed that the fix works after setting up Jetpack for a non-JP site.
- Confirmed that the site discovery flow works for a Jetpack site.

## Screenshots

https://github.com/user-attachments/assets/a92e4824-5ff3-4bdd-b77d-4fc0eefd363f

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/221">20.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift [hunk 1]
```diff
@@ -355,6 +355,7 @@ private extension StorePickerViewController {
     }
 
     func presentSiteDiscovery() {
+        ServiceLocator.authenticationManager.initialize()
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:358]: Excellent investigation, Huong! This works as described. 

I have a question about our fix. 

The `.initialize()` method calls `initializeWithCustomConfigs` before setting the `WordPressAuthenticator` delegate. I wonder whether it will have any side effects. i.e. Will any previously made configuration be reset? For example, I see a similar code which configures authenticator [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/AppCoordinator.swift#L67-L68), and it performs a few other setups. 

Would it be possible to find a central place to add the `ServiceLocator.authenticationManager.initialize()` call which will always make sure that the authenticator is iniitialized and delegate is set? (For all login flows)

What do you think?

Comment (itsmeichigo) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:358]: Hey @selanthiraiyan, thanks for sharing your concern. The code you linked to is not the only place the authentication manager is configured in the `AppCoordinator`. Upon logout, the authentication manager is configured again [here](https://github.com/woocommerce/woocommerce-ios/blob/57d3faa1bc057963a8a75ffd8b280670d077e89d/WooCommerce/Classes/ViewRelated/AppCoordinator.swift#L177), so that ensures that the authenticater is set up properly for the logged-out state.

With that, calling `initialize()` should be efficient to start the site discover flow in the logged-in state IMO. Do you think that makes sense?

Comment (selanthiraiyan) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:358]: Thanks for the explanation, Huong! That sounds good to me.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for working on this, Huong! This works as described. 

Your explanation about configuring the Authenticator makes sense to me. 🚀
