### PR TITLE
[Product Multi-selection] Adapt UI tests for `test_create_new_order`

### LINKED ISSUE #8932: [Product Multi-selection] Adapt UI tests for `test_create_new_order`
Part of https://github.com/woocommerce/woocommerce-ios/issues/8888

Speedy IPP context: pdfdoF-2gW-p2
Subproject context: pdfdoF-2lX-p2

### Description

With the product multi-selection flag enabled, UI tests for `test_create_new_order` fail with:

```
✗ test_create_new_order, failed: caught error: "timedOut"
✗ test_create_new_order, failed: caught error: "timedOut"
✗ test_create_new_order, failed: caught error: "timedOut"
```

We're temporarily bypassing these via feature flag, while the feature is worked on, with:

```
case .productMultiselectionM1:
  return ( buildConfig == .localDeveloper || buildConfig == .alpha ) && !isUITesting
```

We need to revisit and fix the UI tests before switching the feature flag on.

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #8932 

## Description
As part of Speedy IPP' Product Multi-selection project (pdfdoF-2lX-p2) we're changing the UI related to adding products to an order, to accept multiple products rather than a single product. This change will make the `test_create_new_order` fail as now we're not immediately returning `UnifiedOrderScreen` after a product is selected, but we need to tap on a "Done" button to complete the product selection.

This PR modifies the UI test the bare minimum to make it pass with the new UI changes, we'll iterate over the flow in future UI tests as necessary.

| Before  | After |
|---|---|
|  |  |

## Changes
- Added an accessibility identifier to the "Done" button that appears when we enable product multi-selection. This allows us to target the button element during UI tests.
- Added a new `selectMultipleProducts()` method to `AddProductScreen`, which selects multiple products from the list, and then taps the Done button
- Changed the OrderTests `addProduct()` for `addProducts()`, which accepts one or multiple inputs.

## Testing instructions
- CI should pass
- Switch the `productMultiSelectionM1` feature flag temporarily to `true`
- Run `rake mocks` in terminal
- In Xcode, switch to the `Test Plan: UITests`
- Search for `test_create_new_order` and run it. Test should pass.
- Try again with the `productMultiSelectionM1` feature flag switched to `false`, to confirm that works for single-selection as well.

### CODE REVIEW

File: WooCommerce/UITestsFoundation/Screens/Orders/AddProductScreen.swift [hunk 1]
```diff
@@ -21,4 +27,16 @@ public final class AddProductScreen: ScreenObject {
         app.buttons.staticTexts[name].tap()
         return try UnifiedOrderScreen()
     }
+
+    /// Selects multiple products from the list.
+    /// - Returns: Unified Order screen object.
+    @discardableResult
+    public func selectMultipleProducts(byName names: [String]) throws -> UnifiedOrderScreen {
+        app.buttons.staticTexts[names[0]].tap()
+        // TODO: Add a wait, and a second product
```
Comment (iamgabrielma) [inline WooCommerce/UITestsFoundation/Screens/Orders/AddProductScreen.swift:36]: This `TODO` will be done for M1.1 as per the conversation here p1677471329332259-slack-C02H2SVA1L5 . I'll remove the comment and add a link to the new GH issue before merging.

File: WooCommerce/UITestsFoundation/Screens/Orders/AddProductScreen.swift [hunk 2]
```diff
@@ -21,4 +27,16 @@ public final class AddProductScreen: ScreenObject {
...
+    /// - Returns: Unified Order screen object.
+    @discardableResult
+    public func selectMultipleProducts(byName names: [String]) throws -> UnifiedOrderScreen {
+        app.buttons.staticTexts[names[0]].tap()
+        // TODO: Add further scenarios in next iterations: https://github.com/woocommerce/woocommerce-ios/issues/8997
+        if doneButton.exists {
+            doneButton.tap()
+        }
+        return try UnifiedOrderScreen()
+    }
```
Comment (jostnes) [inline WooCommerce/UITestsFoundation/Screens/Orders/AddProductScreen.swift]: We should be able to get this method to work with the new screen already by doing something like this:
```
    public func selectMultipleProducts(numberOfProductsToAdd: Int) throws -> UnifiedOrderScreen {
        for number in 0...numberOfProductsToAdd-1 {
            // add accessibilityIdentifier for the product items on list and find buttons matching that identifier
            let products = app.buttons.matching(identifier: "product-item")
            products.element(boundBy: number).tap()
        }
        if doneButton.exists {
            doneButton.tap()
        }
        return try UnifiedOrderScreen()
    }
```

The parameter accepts the number of products the test should select instead of an array of product names (which adds a layer of complexity as that would depend on the values from the mock file, which could change), so from the test it would be something like:
```
...
.editOrderStatus()
.addProducts(numberOfProductsToAdd: 1)
.addCustomerDetails(name: order.billing.first_name)
...
```

The `accessibilityIdentifier` for `"product-item"` can be added after this line:
https://github.com/woocommerce/woocommerce-ios/blob/6b580f7ea8ec95a9278517091c965bffbd6e1c62/WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift#L74

This way, we don't have to revisit this method again when creating the new test to cover the multi-selection scenario. And since this change is pretty straightforward, I would recommend making it now rather than later.

Comment (iamgabrielma) [reply WooCommerce/UITestsFoundation/Screens/Orders/AddProductScreen.swift]: Thanks for the review! That sounds good, changed the method to accept a number of products rather than specific product names here: https://github.com/woocommerce/woocommerce-ios/pull/8989/commits/351e139a65cf8966bbfe387d8195f61ed96b3f77

**Review by jostnes — APPROVED** [review]
thanks for making the changes and thinking about UI tests as you're working on this project! changes look good to me, test works as expected with the feature flag on and off. :shipit:

**Review by toupper — APPROVED** [review]
LGTM :shipit:
