### PR TITLE
Coupons: Resolve filters and search queries working combined in product selector

### LINKED ISSUE #9098: Coupons: updating filters in product selector have no effect before changing the search query
**Describe the bug**

When updating the filters in the product selector in the coupon form (either adding products or in coupon restrictions), the product results stay the same and don't match the latest filters. After changing the search query, the filters start working. I set the priority as low since coupon management is still behind the feature switch and the filters still work after changing the search query.

🗒️ After taking a look in the code, the issue is from the use of `@Published var` for the filters. In the view model, it observes the combination of the query and `$filters`, but [`self.filters` is used for the product search API request](https://github.com/woocommerce/woocommerce-ios/blob/55fccba12ffe252479c8007cfe138221a2521925/WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift#L292-L300) after `syncingCoordinator.resynchronize()` is called. For `@Published var`, when the value changes the latest value in `sink` is in `willSet` and access to `self.filters` is getting the old values (better explained in [this blog post](https://www.avanderlee.com/swiftui/published-property-wrapper/#the-importance-of-understanding-the-willset-trigger)). It's a tricky case since the sync callback is separate in the delegate, maybe we can use a subject instead of `@Published var` here.

https://github.com/woocommerce/woocommerce-ios/blob/55fccba12ffe252479c8007cfe138221a2521925/WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift#L467-L473

**To Reproduce**

Prerequisites: the site has at least one product for the filters to work

- Log in if needed
- Go to the Menu tab
- Tap Settings > Experimental Features, enable `Coupon Management`
- Go back to the root of the Menu tab
- Tap `Coupons`
- Tap `+` to add a coupon and select a type
- Tap `All Products` --> the product selector is shown with all products shown
- Tap `Filters`, and add some filters that can change the current results (changing product type is probably the easiest)

What happened: the product results didn't change at all

**Screenshots**

https://user-images.githubusercontent.com/1945542/224257396-13c9f532-e8e2-43fe-95c8-dac0ca9e08d1.mov

**Expected behavior**
The filters should be applied to the product results.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 12.4

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #9098 

## Description

This PR fixes the current Coupons filters implementation by wrapping the current `FilterProductListViewModel.Filters` struct into a `CurrentValueSubject` type, so filters and search queries work properly when combined.

Why? Subscribing to the publisher of a `@Published` variable gets the updated result when it changes, however, the notification is sent before the variable itself is updated (the latest value in `.sink` is in `willSet`, not in `didSet`), so we cannot use this update to trigger other methods that rely on the property, as we're passing the old value.

## Changes
* Changes the `FilterProductListViewModel.Filters` from using a `@Published` property wrapper to use `CurrentValueSubject` instead.
* Removes `.dropFirst()` from the search term publisher. This is necessary so we can combine the filter publisher notifications without having to rely on changes in the search terms happening first.
* Unit Test changes:
  * Inject mock storage on some tests that require synching and inserting products, as these would be flaky and crash when we attempt to mutate from a different context queue (I intend to do the same for all test as an improvement, but perhaps this is more suited for a different PR)
  * Declares `@MainActor` for these same tests, so we're sure they run in the main thread. This is necessary because the action Dispatcher requires it while async-await delegates those to background threads if needed.

## Testing instructions

- Go to Menu > Settings > Experimental toggle > Enable `Coupon Management`
- Go to Menu > Coupons > `+` > `Percentage discount` > All Products
- See that using the "search products" field and/or the "Filter" button now works as expected.

## Screenshots

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift [hunk 1]
```diff
@@ -872,11 +872,6 @@ final class ProductSelectorViewModelTests: XCTestCase {
             numberOfActiveFilters: 1
         )
         viewModel.filters = updatedFilters
-
-        // Then
-        XCTAssertEqual(viewModel.productRows.count, 0) // no product matches the filter and search term
-
-        // When
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift:879]: Removed temporarily, this test checks the case described in the PR that still needs to be resolved: 

> When we've searched for a term, and select a Filter afterwards, the first sync will supersede the Filter over the search terms. Both won't be updated until we alter the search again, with the filter enabled.

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift [hunk 2]
```diff
@@ -116,15 +116,27 @@ final class ProductSelectorViewModelTests: XCTestCase {
...
             case let .synchronizeProducts(_, _, _, _, _, _, _, _, _, _, onCompletion):
-                XCTAssertEqual(viewModel.syncStatus, .firstPageSync)
-                let product = Product.fake().copy(siteID: self.sampleSiteID, purchasable: true)
-                self.insert(product)
+                if let syncStatus = viewModel.syncStatus {
+                    syncStatusSpy.append(syncStatus)
+                }
+                let readOnlyProduct = Product.fake().copy(siteID: self.sampleSiteID, purchasable: true)
+                let product = mockStorageManager.viewStorage.insertNewObject(ofType: StorageProduct.self)
+                product.update(with: readOnlyProduct)
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift:139]: I didn't extract this bit into a different function because this is the only test that requires we're specific about which storage we're inserting objects to. Due to its async nature it is relegated to a different thread that the one used for the test class, so if we use the `insert(_:)` helper method and run the whole test class it will crash as we're attempting to mutate a context queue from a different context queue.

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift [hunk 3]
```diff
@@ -139,7 +139,7 @@ struct ProductSelectorView: View {
         .notice($viewModel.notice, autoDismiss: false)
         .sheet(isPresented: $showingFilters) {
             FilterListView(viewModel: viewModel.filterListViewModel) { filters in
-                viewModel.filters = filters
+                viewModel.filters.send(filters)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift]: nit: the implementation detail of the filters updates is now exposed, and the view has to be updated whenever the implementation changes. I'd recommend adding a function to the view model like `updateFilters(_:)` and then marking `viewModel.filters` as private. This way, the view can keep calling the same function while the filters changes from a `@Published var` to a `CurrentValueSubject` or anything else.

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift [hunk 4]
```diff
@@ -32,12 +32,12 @@ final class ProductSelectorViewModel: ObservableObject {
...
     var filterListViewModel: FilterProductListViewModel {
-        FilterProductListViewModel(filters: filters, siteID: siteID)
+        FilterProductListViewModel(filters: filters.value, siteID: siteID)
     }
 
-    /// Selected filter for the product list
+    /// Selected filters for the product list
     ///
-    @Published var filters = FilterProductListViewModel.Filters()
+    var filters = CurrentValueSubject<FilterProductListViewModel.Filters, Never>(.init())
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift]: nit: any reasons this has to be a `var`? It looks like it can be a `private let` similar to the comment above. if the filters value has to be public, I'd recommend creating another variable with the subject type erased `AnyPublisher` (an example is `ProductImageUploader.errors`).

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift [hunk 5]
```diff
@@ -510,13 +510,14 @@ private extension ProductSelectorViewModel {
 
     /// Updates the product results predicate & triggers a new sync when search term changes
     ///
-    func configureProductSearch() {
+    func synchronizedProductFilterSearch() {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift]: nit: what are the reasons it's `synchronized*` vs. `synchronize*`? usually the function name uses the present tense.

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift:139]: ❓  I was wondering why the insertion of the product isn't needed before the PR changes. what are the changes in the view model that affect the storage behavior?

> Due to its async nature it is relegated to a different thread that the one used for the test class, so if we use the insert(_:) helper method and run the whole test class it will crash as we're attempting to mutate a context queue from a different context queue.

How about waiting for the completion of `ProductAction.synchronizeProducts` by `waitFor` in the When block, `viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { _ in })` below? Then the test case will only finish after the sync is complete.

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift [hunk 6]
```diff
@@ -135,6 +147,7 @@ final class ProductSelectorViewModelTests: XCTestCase {
         viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { _ in })
 
         // Then
+        XCTAssertTrue(syncStatusSpy.contains(.firstPageSync))
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift]: nit: how about asserting on the full array of `syncStatusSpy` so that we can ensure the values stay the same?

**Review by jaclync — COMMENTED** [review]
Works as expected 👍  just had some suggestions on the public interface and questions about the tests

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift]: Sounds great, changed on https://github.com/woocommerce/woocommerce-ios/pull/9387/commits/55600d6967afe03eb0dd7de18be295244e572891

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift (hunk 4 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift]: No reason, I'm just not acquainted to use Combine and I though "if it changes, it is a var" 😅  

I just made it `let` to avoid complexity for the moment, since we don't need to re-assign the subject. Change on 55600d6967afe03eb0dd7de18be295244e572891

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift (hunk 5 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift]: No reason, my English could be better sometimes. Changed on 1a62947e824d961b7f368cf96e95f74e4dd4b8ff

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift (hunk 6 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift]: Definitely, changed on https://github.com/woocommerce/woocommerce-ios/pull/9387/commits/0ed4a6ff0c4475a18f6e6075f88cc4ea3ad0bea0 so we intercept both statuses.

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift:139]: > I was wondering why the insertion of the product isn't needed before the PR changes. what are the changes in the view model that affect the storage behavior?

I may be off here, but as far as I could see when debugging, this is due to the removal of `.dropFirst()` in the `.sink`. From the previous existing implementation, we seem to call the former `configureProductSearch()` twice on initialization, and with this calling resynchronize to storage. Using `.dropFirst()` had the side-effect of removing one of the sync calls, hiding the issue of attempting to write and read from the same thread (at least in unit tests)

Here's the slack thread for context: p1681094050104429-slack-CGPNUU63E

Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift:139]: > How about waiting for the completion of ProductAction.synchronizeProducts by waitFor in the When block, viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { _ in }) below? Then the test case will only finish after the sync is complete.

Just to clarify: Are you referring to add the assertions inside the waitFor block? Such as:

```
        // When
        let _: Bool = waitFor { completion in
            viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { sync in
                if let syncStatus = viewModel.syncStatus {
                    syncStatusSpy.append(syncStatus)
                }
                completion(sync)
            })
            XCTAssertEqual(syncStatusSpy, [.firstPageSync, .results])
            XCTAssertEqual(viewModel.syncStatus, .results)
        }
```

Rather than 

```
        // When
        let _: Bool = waitFor { completion in
            viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { sync in
                if let syncStatus = viewModel.syncStatus {
                    syncStatusSpy.append(syncStatus)
                }
                completion(sync)
            })
        }
        XCTAssertEqual(syncStatusSpy, [.firstPageSync, .results])
        XCTAssertEqual(viewModel.syncStatus, .results)
```

Or you meant just regarding when we intercept the sync status?

**Comment by iamgabrielma** [comment]
Thanks for the review and the feedback @jaclync, this is ready for re-review. I just have a question regarding the feedback here: https://github.com/woocommerce/woocommerce-ios/pull/9387#discussion_r1162297531

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift:139]: It generally looks more organized to assert outside of the async task. The latest changes LGTM 👍

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift [hunk 7]
```diff
@@ -116,25 +116,45 @@ final class ProductSelectorViewModelTests: XCTestCase {
...
         // When
-        viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { _ in })
+        let _: Bool = waitFor { completion in
+            viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { sync in
+                if let syncStatus = viewModel.syncStatus {
+                    syncStatusSpy.append(syncStatus)
+                }
+                completion(sync)
+            })
+        }
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift]: nit: since the boolean value isn't used, it can probably be simplified like
```suggestion
        waitFor { promise in
            viewModel.sync(pageNumber: 1, pageSize: 25, onCompletion: { _ in
                if let syncStatus = viewModel.syncStatus {
                    syncStatusSpy.append(syncStatus)
                }
                promise(())
            })
        }
```

We usually call the callback that we call after the async task is done ["promise"](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises) in the code base, a concept from web.

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift [hunk 8]
```diff
@@ -426,6 +426,18 @@ extension ProductSelectorViewModel: SyncingCoordinatorDelegate {
...
+
+    /// Updates the selected filters for the product list
+    ///
+    func updateFilters(_ filters: FilterProductListViewModel.Criteria) {
+        filtersSubject.send(filters)
+    }
+
+    /// Retrieves the latest selected filters from the product list
+    ///
+    func retrieveUpdatedFilters() -> FilterProductListViewModel.Filters {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift]: 💭 this seems to be only called in unit tests and not in the app. generally, we want to avoid making functions just for testing. Instead, we want to test the public states that are affected by `updateFilters` in this case, which is probably the related parameters in `ProductAction.synchronizeProducts` and `ProductAction.searchProducts`.

This might be a bigger change and there are some pre-existing test cases accessing the filters directly. For now, maybe we can update the test cases to access filters through another public variable `ProductSelectorViewModel.filterListViewModel.criteria` instead of this function.

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift [hunk 9]
```diff
@@ -792,15 +833,16 @@ final class ProductSelectorViewModelTests: XCTestCase {
...
         // Then
-        assertEqual(filteredStockStatus, filters.stockStatus)
-        assertEqual(filteredProductType, filters.productType)
-        assertEqual(filteredProductStatus, filters.productStatus)
-        assertEqual(filteredProductCategory, filters.productCategory)
+        let currentFilters = viewModel.retrieveUpdatedFilters()
+        assertEqual(filteredStockStatus, currentFilters.stockStatus)
+        assertEqual(filteredProductType, currentFilters.productType)
+        assertEqual(filteredProductStatus, currentFilters.productStatus)
+        assertEqual(filteredProductCategory, currentFilters.productCategory)
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift]: ❓ if I understand the test case correctly, we want to make sure the `filtered*` parameters match the `filters` in the `updateFilters` function? I'm not sure if I missed something 🤔 

```suggestion
        assertEqual(filteredStockStatus, filters.stockStatus)
        assertEqual(filteredProductType, filters.productType)
        assertEqual(filteredProductStatus, filters.productStatus)
        assertEqual(filteredProductCategory, filters.productCategory)
```

**Review by jaclync — APPROVED** [review]
Thanks for making the changes, LGTM :shipit: mostly a comment on a function only used in unit tests

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift (hunk 8 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift]: That makes sense. Changes on https://github.com/woocommerce/woocommerce-ios/pull/9387/commits/eb560a94d6ccdc4a9c81c5f6eef2a54c0a27219a

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift (hunk 9 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift]: That's right, we can remove the `currentFilters` declaration. Changes on https://github.com/woocommerce/woocommerce-ios/pull/9387/commits/e389ebf88b17efa4b10f4569d0abb9f41cacac55

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift (hunk 7 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/ProductSelectorViewModelTests.swift]: Gotcha! Changed on https://github.com/woocommerce/woocommerce-ios/pull/9387/commits/349036c3c56effac85b1810a19ea788879af1045
