### PR TITLE
Hide orders that have a `createdDate` that exists in the future.

### LINKED ISSUE #367: Orders with `scheduled-payment` Order Status always appear in `Today` Orders View
### Expected behavior

Orders with `scheduled-payment` Order Status should not appear in `Today` Orders View. 

### Actual behavior

Orders with `scheduled-payment` Order Status always appear in `Today` Orders View:

Image Link: https://cloudup.com/c2n7LRiVr4T

Here is Order #1178 page:

Image Link: https://cloudup.com/cE0llFOBUZn

Here is Order #1179 page:

Image Link: https://cloudup.com/cgJkg1Ks3PG

### Steps to reproduce the behavior

1) Download [WooCommerce Deposits](https://woocommerce.com/products/woocommerce-deposits/) extension.

2) Create a **Payment Plan** as follows:

Image Link: https://cloudup.com/cGwAhEGkNmc

3) Create a product and assign the Payment Plan to it in **Deposits** section:

Image Link: https://cloudup.com/c4vPhcfuP0M

4) Place an order for that product on the site. Select `Deposit` and `Payment Plan` upon placing item to the cart:

Image Link: https://cloudup.com/c3k0-RPN0cG

5) Once the order is placed, you should have the initial order for the item for which you paid the deposit + 3 orders that are visible in the **Payment Plan** section. The 3 orders should have a status `scheduled-payment`. In my case, it looks like this:

**Payment Plan (has 2 orders but your view will have 3):**

Image Link: https://cloudup.com/c6AP50jkphZ

**Order 1176 (Deposit Payment - Payment 1) - placed on June 22, 2018:**

Image Link: https://cloudup.com/cboR3744oLY

**Order 1177 (Payment 2) - placed on August 22, 2018:**

Image Link: https://cloudup.com/cVB7-zlGuAt

**Order 1178 (Payment 3) - payment scheduled for October 22, 2018:**

Image Link: https://cloudup.com/c_OuC7IXX0A

**Order 1179 (Payment 4) - payment scheduled for December 22, 2018:**

Image Link: https://cloudup.com/cQ28K8FSX-m

6) Open the app and you will see that orders that are a part of the Payment Plan and have `scheduled-payment` Order Status appear in `Today` Orders View when they have future date as an Order Date. 

Image Link: https://cloudup.com/c2n7LRiVr4T

These orders will be appearing every day in `Today` Orders View section. I tested it for several days and they keep moving. 

Ideally, I think we should hide them until they are "placed" (go through as per Payment Plan) and will be actually relevant for `Today` view. 

### Tested in WooCommerce Android App?

Yes. Same issue is present there. 

##### Tested on [device], iOS [version], WCiOS [version]

- iPhone 6S
- iOS v 12.0.1
- WCiOS v 0.8(20181002)

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #367.

In this PR, the predicate filters out dates that happen in the future. It also removes the "On Hold" order status from the filter action sheet.

cc: @astralbodies because dates.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift [hunk 1]
```diff
@@ -33,6 +33,13 @@ class OrdersViewController: UIViewController {
         let storageManager = AppDelegate.shared.storageManager
         let descriptor = NSSortDescriptor(keyPath: \StorageOrder.dateCreated, ascending: false)
 
+        let futureDate = getTomorrow()
+
+        if let tomorrow = futureDate {
+            let predicate = NSPredicate(format: "dateCreated < %@", tomorrow as NSDate)
+            return ResultsController<StorageOrder>(storageManager: storageManager, sectionNameKeyPath: "normalizedAgeAsString", matching: predicate, sortedBy: [descriptor])
+        }
+
```
Comment (mindgraffiti) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: Honestly it looks like the `resultsController.predicate` assignment in L159 is overwriting anything I put in here. I'm really not sure if it's good to even add the predicate here, considering that.

File: WooCommerce/Classes/Model/OrderStatus+Woo.swift [hunk 2]
```diff
@@ -9,6 +9,7 @@ extension OrderStatus {
     /// Returns a collection of all of the known Order Status
     ///
     static var knownStatus: [OrderStatus] {
-        return [.pending, .processing, .onHold, .failed, .cancelled, .completed, .refunded]
+        // .onHold is an existing status but we don't want it to display.
```
Comment (bummytime) [inline WooCommerce/Classes/Model/OrderStatus+Woo.swift]: Perhaps I don't understand the issue here fully, but I don't think we want to remove the `on hold` order status completely from filtering:

simulator screen shot - iphone xs - 2019-01-22 at 10 36 36

I am assuming there is a use case where the customer will want to filter on orders with this status (in the past).

/cc @juliaamosova

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift [hunk 3]
```diff
@@ -517,6 +533,15 @@ private extension OrdersViewController {
         let order = resultsController.object(at: indexPath)
         return OrderDetailsViewModel(order: order)
     }
+
+    func getTomorrow() -> Date? {
```
Comment (bummytime) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: This func feels like it should be in a `Date` extension (`Date+Woo.swift`)...like something that could be summoned by calling: 

`Date.tomorrow()`

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift [hunk 4]
```diff
@@ -152,7 +159,16 @@ private extension OrdersViewController {
...
             let excludeSearchCache = NSPredicate(format: "exclusiveForSearch = false")
             let excludeNonMatchingStatus = statusFilter.map { NSPredicate(format: "status = %@", $0.rawValue) }
-            let predicates = [ excludeSearchCache, excludeNonMatchingStatus ].compactMap { $0 }
+
+            let futureDate = getTomorrow()
+            var predicates: [NSPredicate]
+            
+            if let tomorrow = futureDate {
+                let dateSubPredicate = NSPredicate(format: "dateCreated < %@", tomorrow as NSDate)
+                predicates = [ excludeSearchCache, excludeNonMatchingStatus, dateSubPredicate ].compactMap { $0 }
```
Comment (bummytime) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: Style nit: You could probably tighten up this code with something like:

```
...
var predicates = [ excludeSearchCache, excludeNonMatchingStatus ].compactMap { $0 }
if let tomorrow = getTomorrow() {
    let dateSubPredicate = NSPredicate(format: "dateCreated < %@", tomorrow as NSDate)
    predicates.append(dateSubPredicate)
}
...
```

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift (hunk 1 above)
Comment (bummytime) [reply WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: @mindgraffiti I would agree with your assessment since `refreshResultsPredicate()` is called in both `viewDidLoad()` and `didChangeFilter()` — go ahead and delete this new code block.

File: WooCommerce/Classes/Model/OrderStatus+Woo.swift (hunk 2 above)
Comment (mindgraffiti) [reply WooCommerce/Classes/Model/OrderStatus+Woo.swift]: You are correct. I mis-read some of the conversations in the Android ticket. Thanks for catching that. I'll restore `On Hold` in the filter menu.

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift (hunk 4 above)
Comment (mindgraffiti) [reply WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: thank you! That `if/else` was really bothering me.

**Comment by mindgraffiti** [comment]
Ready for another 👀 @bummytime
