### PR TITLE
[Custom Fields] Fix issue of not updating the parent item after saving changes

### LINKED ISSUE #14199: Custom Fields: changes are not reflected on parent item after saving
https://github.com/woocommerce/woocommerce-ios/pull/14194#pullrequestreview-2386955952

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #14199 

## Description
This PR adds a fix to the linked issue, the issue was that after saving changes (#14194), then the new changes weren't reflected in some cases:
- ~~In OrderDetails, after going back, the changes were loading asynchronously, meaning that if we open the custom fields later quickly, we could see the state before saving.~~ As discussed below, the issue for order details was just that deleted custom fields weren't deleted from storage.
- In ProductDetails, the changes were never elected.

These issues were caused by two issues:
- For Order Details, the issue was that the logic of `MetaDataStore` was broken, and wasn't cleaning up deleted custom fields.
- For Product Details, the parent screen was holding a reference to the outdated object, and wasn't updated when the custom fields list changes.

## Steps to reproduce
1. Open a product or an order in the app.
2. Tap on Custom Fields button (or row)
3. Make some changes.
4. Save changes.
5. Navigate back.
6. Re-open custom fields.

## Testing information
- Confirm that the changes are reflected immediately.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift [hunk 1]
```diff
@@ -224,4 +226,8 @@ extension ProductFormViewModelProtocol {
             return true
         }
     }
+
+    func updateProductCustomFields(customFields: [MetaData]) {
+        // Default implementation does nothing
+    }
```
Comment (hichamboushaba) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift]: Please let me know if you have something against using a default implementation here instead of a `no-op` override in the `ProductVariationFormViewModel`

Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModelProtocol.swift]: There are [a few reasons](https://betterprogramming.pub/swift-why-you-should-avoid-using-default-implementations-in-protocols-eeffddbed46d) why we should avoid adding a default implementation for protocol. It's best to not use it where you can - unless in cases that you have no choice. 

An example for that is when you add a new method to a protocol but not wanting to cause breaking changes, like updating a public library (e.g. WPAuthenticator delegate) that is used by other apps. It's still codesmell, but at least you don't break existing dependent apps.

**Review by itsmeichigo — COMMENTED** [review]
Thank you Hicham for the fix. However, I'm still seeing some issues:

### Product
Updating the parent item for product works as expected if you add a new custom field or edit an existing one. However, if you delete an item, the change is not reflected if you navigate back to the product from the product list:


https://github.com/user-attachments/assets/1993a0ea-12a3-48aa-9295-0a3e6577659b

The reason is as I shared in the previous PR - there's an issue with how we handle changes in storage in `MetaDataStore` - specifically this [method](https://github.com/woocommerce/woocommerce-ios/blob/316063cc980ebf2231fa69411940364f3e1706ec/Yosemite/Yosemite/Stores/MetaDataStore.swift#L193-L208). 

You can see that here we are only updating the existing metadata or add a new one to the stored product, but we don't remove the deleted one. That's something we need to do to fix the above issue.

## Order
Since the implementation of storage update for product was essentially copied-pasted from the update for order, I believe the same issue about deleting happens to order. I managed to reproduce the same issue even though it looks like the order is loaded again from remote in the order detail screen (I haven't checked closely in code if that's the case).



https://github.com/user-attachments/assets/544af530-9ab6-442e-83a6-c22a886d35f1

Once you make the necessary changes to `MetaDataStore`, could you also add the missing unit tests to confirm the value in the stored product and order after the update? Thank you!

**Comment by hichamboushaba** [comment]
Thank you @itsmeichigo for the review, and sorry for missing the deletion case.
I updated the `MetaDataStore` to handle this case, I'm going to leave some comments below with some questions or remarks to help with the review.

**Important:** I force pushed the branch to remove the previous commits from history, so you'll need to remove your local one before pulling (or you can just `reset`).

File: Yosemite/Yosemite/Stores/MetaDataStore.swift [hunk 2]
```diff
@@ -117,9 +117,18 @@ private extension MetaDataStore {
                                                siteID: Int64,
                                                onCompletion: @escaping () -> Void) {
         let derivedStorage = sharedDerivedStorage
+
         derivedStorage.perform {
+            let storedMetaData = derivedStorage.loadOrderMetaData(siteID: siteID, orderID: orderID)
+
             for readOnlyOrderMetaData in readOnlyOrderMetaDatas {
-                self.saveMetaData(derivedStorage, readOnlyOrderMetaData, orderID: orderID, siteID: siteID)
+                self.saveMetaData(derivedStorage, readOnlyOrderMetaData, storedMetaData, orderID: orderID, siteID: siteID)
```
Comment (hichamboushaba) [inline Yosemite/Yosemite/Stores/MetaDataStore.swift:125]: I'm passign the `storedMetaData` to the `saveMetaData` function to avoid doing two calls to fetch the items from storage, please let me know if this is not needed.

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift [hunk 3]
```diff
@@ -771,6 +776,18 @@ private extension ProductFormViewModel {
...
+    /// Only needed for updates that are saved remotely on other screens
+    ///
+    private func configureEntityListener() {
+        entityListener.onUpsert = { [weak self] product in
+            guard let self = self else { return }
+            // Custom fields are updated on a different screen, update the product to reflect the last changes
+            resetProduct(EditableProductModel(product: originalProduct.product.copy(customFields: product.customFields)))
+            self.product = EditableProductModel(product: product.copy(customFields: product.customFields))
+        }
+    }
```
Comment (hichamboushaba) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift]: After implementing the `MetaDataStore` changes, I noticed that the root issue was fixed for orders and not for products (when I go back then re-open the custom fields, the changes are not reflected), then I noticed that the Order Details screen uses an `EntityListener` to observe the storage changes of the order then [updates](https://github.com/woocommerce/woocommerce-ios/blob/685602e979a15339b7006b36bdd541dc756b3078/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/OrderDetailsViewController.swift#L210-L218) the `order` property, which is why the issue is not present there.

I tried to replicate this here instead of my previous attempt using the callback, I think this is cleaner, the only difference from what we do in order details is that I update only the customFields to preserve the other user changes (if any), I think this solution would work also to replace the `updateProductVariations` function, but it's another topic.

Please let me know what you think, if you think the callback function is better I can revert to using it.

File: Yosemite/Yosemite/Stores/MetaDataStore.swift (hunk 2 above)
Comment (itsmeichigo) [reply Yosemite/Yosemite/Stores/MetaDataStore.swift:125]: Thanks, this would help with optimizing our storage usage!

File: Storage/Storage/Tools/StorageType+Extensions.swift [hunk 4]
```diff
@@ -766,11 +766,24 @@ public extension StorageType {
         return firstObject(ofType: MetaData.self, matching: predicate)
     }
 
+    /// Retrieves all stored MetaData of a given Order
+    ///
+    func loadOrderMetaData(siteID: Int64, orderID: Int64) -> [MetaData] {
+        let predicate = \MetaData.order?.siteID == siteID && \MetaData.order?.orderID == orderID
+        return allObjects(ofType: MetaData.self, matching: predicate, sortedBy: nil)
+    }
```
Comment (itsmeichigo) [inline Storage/Storage/Tools/StorageType+Extensions.swift:774]: Thanks for adding this! Can you please also add a unit test for this in `StorageTypeExtensionsTests`?

File: Storage/Storage/Tools/StorageType+Extensions.swift [hunk 5]
```diff
@@ -766,11 +766,24 @@ public extension StorageType {
...
         let predicate = \MetaData.product?.siteID == siteID && \MetaData.product?.productID == productID && \MetaData.metadataID == metadataID
         return firstObject(ofType: MetaData.self, matching: predicate)
     }
 
+    /// Retrieves all stored MetaData of a given Product
+    ///
+    func loadProductMetaData(siteID: Int64, productID: Int64) -> [MetaData] {
+        let predicate = \MetaData.product?.siteID == siteID && \MetaData.product?.productID == productID
+        return allObjects(ofType: MetaData.self, matching: predicate, sortedBy: nil)
+    }
```
Comment (itsmeichigo) [inline Storage/Storage/Tools/StorageType+Extensions.swift:788]: Same comment as above about adding unit test.

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift (hunk 3 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift]: I was concerned that this would cause other fields to be updated more than once but then I realized from [here](https://github.com/woocommerce/woocommerce-ios/blob/2077debb97b5020c3aa1faaece30961beabf73e8/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/ProductFormViewModel.swift#L416-L446) that we were not updating storage from each individual screen for other fields. Instead, we use the Save button on the main product form to send all the changes to remote and storage.

I believe there's such difference because we are reusing the same `CustomFieldsListView` with order, and in the order details screen we save each details individually.

I suppose we don't want to change this behavior for the custom fields in the product form at this late stage. However, I'd prefer reverting back to the previous way of saving the parent product as you pointed out that only custom fields are using it. Hopefully we'll revisit all this inconsistency when we start the product form update project in the near future.

**Review by itsmeichigo — APPROVED** [review]
Thanks for the updates Hicham! This works as expected now 🎉 

I left some non-blocking comments regarding the unit tests. I also followed up with the question regarding the entity listener in the product form. tl;dr I prefer keeping the previous change - but I'm pre-approving this PR so please feel free to merge after addressing that.

**Comment by hafizrahman** [comment]
Since Huong is AFK, I'm assigning myself to review this also so I can get notification for more reviews request (I think that's how GH works anyway).

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewModel.swift]: > I was concerned that this would cause other fields to be updated more than once but then I realized from [here](https://github.com/woocommerce/woocommerce-ios/blob/2077debb97b5020c3aa1faaece30961beabf73e8/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/ProductFormViewModel.swift#L416-L446) that we were not updating storage from each individual screen for other fields. Instead, we use the Save button on the main product form to send all the changes to remote and storage.
>
> I believe there's such difference because we are reusing the same CustomFieldsListView with order, and in the order details screen we save each details individually.

Yes, this is a tradeoff we decided to accept to allow better reusability of the screen, and to decided to add a top banner to make it less confusing for the users.

> However, I'd prefer reverting back to the previous way of saving the parent product as you pointed out that only custom fields are using it.

Although I would love to know why you think that the previous way is better than using `EntityListener`, I applied the revert [05f78e9](https://github.com/woocommerce/woocommerce-ios/pull/14201/commits/05f78e971d67cddf65b8b8e03c51d3483595234f) to move forward with merging the PR.

File: Storage/Storage/Tools/StorageType+Extensions.swift (hunk 4 above)
Comment (hichamboushaba) [reply Storage/Storage/Tools/StorageType+Extensions.swift:774]: Done in 76eee74

**Comment by hichamboushaba** [comment]
> Since Huong is AFK, I'm assigning myself to review this also so I can get notification for more reviews request (I think that's how GH works anyway).

Thanks @hafizrahman, I finished applying Huong's suggestions, Please feel free to review the last changes, and then we can merge the PR.

File: Storage/Storage/Tools/StorageType+Extensions.swift (hunk 5 above)
Comment (hichamboushaba) [reply Storage/Storage/Tools/StorageType+Extensions.swift:788]: Done in https://github.com/woocommerce/woocommerce-ios/commit/76eee743a9262d700caa0a06b19a3828257b9ade

File: Storage/Storage/Tools/StorageType+Extensions.swift (hunk 4 above)
Comment (hafizrahman) [reply Storage/Storage/Tools/StorageType+Extensions.swift:774]: https://github.com/woocommerce/woocommerce-ios/pull/14201/commits/76eee743a9262d700caa0a06b19a3828257b9ade

File: Storage/Storage/Tools/StorageType+Extensions.swift (hunk 5 above)
Comment (hafizrahman) [reply Storage/Storage/Tools/StorageType+Extensions.swift:788]: https://github.com/woocommerce/woocommerce-ios/pull/14201/commits/76eee743a9262d700caa0a06b19a3828257b9ade

**Review by hafizrahman — APPROVED** [review]
Thanks for the updates (and the revert also). Can confirm that we did agree to have this different behavior for saving custom fields. Let's revisit it when reworking the Product Details screen, seems like that's the right timing to further discuss it.

I tested this in iPhone Simulator with iOS 17.5 and it looks good to merge.
