### PR TITLE
[Woo POS] Payment error exit buttons

### LINKED ISSUE #13481: [Woo POS] M2 Errors: Payment failed
Implement UI for Payment Failures:
- paymentError
- paymentErrorNonRetryable

Image

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #13481

## Description

This PR adds the actions to payment errors which take the merchant back to the checkout screen, rather than using the payments-provided retry handlers.

This applies to non-retryable errors, and errors which (might) retry using the same card details as the previous attempt.

- Non-retryable errors: `Try another payment method` button (it's not really a retry, it takes you back to the checkout)
- Try payment again errors: `Go back to checkout` secondary button

### Refactoring payment event view model creation
I moved the logic to determine the presentation style for an error from an extension on `CardPresentPaymentEvent`, to a factory: `PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer`. This let me improve the "annotation" approach we used to add more information to the message/alert view models. Previously, this was only used to set the order total on the `Order Complete` screen, but required a `mutating func` on that view model.

It seems better to provide the dependencies when we create those view models, then keep them immutable.

Now we have a static method which takes the event and the additional information required to create _any_ payment message view model for POS. That includes the new `cancelThenCollectPayment` action we use for the two buttons implemented here.

## Steps to reproduce

Edit a POS-eligible product to have a sale price ending in `.01` – [see error amounts here](https://docs.stripe.com/terminal/references/testing#physical-test-cards)

### Non-retryable errors
1. Lauch the app and go to POS
2. Add your error product to the cart
3. Check out
4. Tap your card
5. Observe that you're shown a retryable `Try another payment method` error
6. Tap the button
7. Tap your card again
8. Observe that you're shown a different (but similar) error screen.
9. Tap the `Try another payment method` button – observe it takes you back to the checkout and prepares the payment again.

These are only subtly different, but the second is using a new payment intent.

### Try payment again errors
1. Launch the app and go to POS
2. Add a non-error product to the cart
3. Check out
4. Tap your card, and immediately disable network connectivity on the iPad
5. Observe that you're shown a retryable `Try payment again` error
11. Re-enable the network
12. Tap `Go back to checkout` (if you do this too soon, you'll see other errors, but they are recoverable.)
13. Observe that you're taken back to the checkout and the reader gets ready to take payment again. 

## Testing information

I've tested with both the flows above, and also that the general payment flows still work as expected.

No testing on phones, as this only affects POS.

Unit tests for the view model creation logic.

## Screenshots

https://github.com/user-attachments/assets/d29c8915-ddd0-4664-b1b3-d60ecea6d302

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift [hunk 1]
```diff
@@ -341,25 +347,37 @@ private extension TotalsViewModel {
...
+
+    func presentationStyle(for eventDetails: CardPresentPaymentEventDetails) -> PointOfSaleCardPresentPaymentEventPresentationStyle? {
+        PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer.presentationStyle(
+            for: eventDetails,
+            dependencies: presentationStyleDeterminerDependencies)
+    }
+
+    var presentationStyleDeterminerDependencies: PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer.Dependencies {
+        PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer.Dependencies(
+            tryPaymentAgainBackToCheckoutAction: cancelThenCollectPayment,
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift]:
```suggestion
            tryPaymentAgainBackToCheckoutAction: { [weak self] in self?.cancelThenCollectPayment() },
```

The flows themselves worked great except for quite a lot of crashes. It would happen when retrying payment or exiting the POS.

<details>
<summary>Example log</summary>

```
#0	0x0000000109042214 in _os_unfair_lock_recursive_abort ()
#1	0x000000010903da30 in _os_unfair_lock_lock_slow ()
#2	0x00000001b87b3248 in PublishedSubject.disassociate(_:) ()
#3	0x00000001b87b3e8c in PublishedSubject.Conduit.cancel() ()
#4	0x00000001b87eab50 in protocol witness for Cancellable.cancel() in conformance ConduitBase<τ_0_0, τ_0_1> ()
#5	0x00000001b87baf74 in AbstractCombineLatest.cancel() ()
#6	0x00000001b87bb514 in protocol witness for Cancellable.cancel() in conformance AbstractCombineLatest<τ_0_0, τ_0_1, τ_0_2> ()
#7	0x00000001b87b2dac in PublishedSubject.deinit ()
#8	0x00000001b87b2e44 in PublishedSubject.__deallocating_deinit ()
#9	0x00000001932a4d40 in _swift_release_dealloc ()
#10	0x00000001932a576c in bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1>>::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) ()
#11	0x0000000104887498 in TotalsViewModel.deinit ()
#12	0x000000010488769c in TotalsViewModel.__deallocating_deinit ()
#13	0x00000001932a4d40 in _swift_release_dealloc ()
#14	0x00000001932a576c in bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1>>::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) ()
#15	0x000000010423a304 in destroy for PointOfSaleCardPresentPaymentMessageType ()
#16	0x0000000193281774 in assignWithCopy for ClosedRange<>.Index ()
#17	0x00000001b87b31e0 in PublishedSubject.send(_:) ()
#18	0x00000001b87d1b3c in PublishedSubscriber.receive(_:) ()
#19	0x00000001b87d1b64 in protocol witness for Subscriber.receive(_:) in conformance PublishedSubscriber<τ_0_0> ()
#20	0x00000001b88358bc in Publishers.Map.Inner.receive(_:) ()
#21	0x00000001b87de3d0 in closure #1 in Publishers.ReceiveOn.Inner.receive(_:) ()
#22	0x00000001c5c00e60 in thunk for @escaping @callee_guaranteed () -> () ()
#23	0x000000010bea7ec4 in _dispatch_call_block_and_release ()
#24	0x000000010bea973c in _dispatch_client_callout ()
#25	0x000000010beb93f8 in _dispatch_main_queue_drain ()
#26	0x000000010beb8f1c in _dispatch_main_queue_callback_4CF ()
#27	0x000000018040e960 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#28	0x0000000180409078 in __CFRunLoopRun ()
#29	0x00000001804084d4 in CFRunLoopRunSpecific ()
#30	0x000000018ef2aae4 in GSEventRunModal ()
#31	0x00000001853d0a28 in -[UIApplication _run] ()
#32	0x00000001853d46b0 in UIApplicationMain ()
#33	0x0000000103ecd6c8 in main at /Users/povilasstaskus/Projects/woocommerce-ios/WooCommerce/Classes/System/main.swift:7
#34	0x000000010909d544 in start_sim ()
#35	0x000000010924a0e0 in start ()
```
</details>

https://github.com/user-attachments/assets/d64af33d-a200-4ee8-b998-a22b0bbccafd

From what I understood when analyzing these logs it suggested issues with memory management. I immediately started looking for some retain cycles and I think this may be the place. 

When we pass a method to a closure, it's easy to miss that we capture `self` strongly.

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift [hunk 2]
```diff
@@ -341,25 +347,37 @@ private extension TotalsViewModel {
...
+            nonRetryableErrorExitAction: cancelThenCollectPayment,
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift]:
```suggestion
            nonRetryableErrorExitAction: { [weak self] in self?.cancelThenCollectPayment() },
```

File: WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift [hunk 3]
```diff
@@ -5,11 +5,19 @@ enum PointOfSaleCardPresentPaymentEventPresentationStyle {
...
-/// View Models are created here, but can be "annotated" where they are used if the `CardPresentPaymentEventDetails` is
-/// not enough to fully populate the view model. See `TotalsViewModel.observeCardPresentPaymentEvents` for an example.
-extension CardPresentPaymentEventDetails {
-    var pointOfSalePresentationStyle: PointOfSaleCardPresentPaymentEventPresentationStyle? {
-        switch self {
+/// A factory for payment alert/message view models, so we can provide information beyond what's available from  `CardPresentPaymentEventDetails`
+/// To avoid keeping the additional information up to date as it changes, we pass it to every call to `presentationStyle`
+/// See `TotalsViewModel.observeCardPresentPaymentEvents` for an example.
+struct PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer {
+    struct Dependencies {
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift:7]: Clever 👍 Happy you found a better way to solve the dependency issue

File: WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentSuccessMessageViewModel.swift [hunk 4]
```diff
@@ -2,10 +2,14 @@ import Foundation
 
 struct PointOfSaleCardPresentPaymentSuccessMessageViewModel {
     let title: String = Localization.title
-    var message: String? = nil
+    let message: String?
 
-    mutating func updateMessage(formattedOrderTotal: String) {
-        message = String(format: Localization.message, formattedOrderTotal)
+    init(formattedOrderTotal: String?) {
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentSuccessMessageViewModel.swift:7]: 💯

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift [hunk 5]
```diff
@@ -341,25 +347,37 @@ private extension TotalsViewModel {
...
+            formattedOrderTotalPrice: formattedOrderTotalPrice)
+    }
+
+    func cancelThenCollectPayment() {
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:374]: I see that both buttons do the same action. And you mentioned in the description that:

> (it's not really a retry, it takes you back to the checkout)

Are we planning for 'Try payment again' button to retry the same payment? 

image

**Review by staskus — COMMENTED** [review]
👏 Amazing solution, cleanly done!

There's a crash in the flow that needs to be fixed and retested but I think breaking the retain cycles should be enough 👍 

----

Not sure if it's related, I found it pretty easy to reproduce this flow specifically when restarting the payment. It's a case where we allow coming back without properly canceling the flow or dealing with TotalsViewModel affecting the dashboard state. Could be a separate bug:

https://github.com/user-attachments/assets/b23a88be-2ca4-426c-baf9-8f51fe67691b

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift]: Great catch, thank you for investigating it!

File: WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift (hunk 3 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift:7]: Me too 😂

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift (hunk 5 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:374]: So, the two buttons are subtly different. The retry button retries the payment as late in the flow as it can. Depending on the error, it might not require another card tap to retry. That's why it doesn't say `Try another payment method`.

Note that in `PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer.presentationStyle(for:dependencies:)` we use `retryAction` from the payment event for the try payment again button:

```
                    return .message(.paymentError(
                        viewModel: PointOfSaleCardPresentPaymentErrorMessageViewModel(
                            error: error,
                            tryPaymentAgainButtonAction: retryAction,
                            backToCheckoutButtonAction: dependencies.tryPaymentAgainBackToCheckoutAction)))
```

Because the merchant may be nervous about this kind of retry, and just wants to go back, we give them the other button rather than force them into the second attempt.

It might seem confusing to use `cancelThenCollectPayment` to go back; we do it because it guarantees that the card will need to be tapped again. The checkout is strange if you don't prepare the reader for payment, because it just shows the totals, with no action to take.

File: WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift [hunk 6]
```diff
@@ -5,11 +5,19 @@ enum PointOfSaleCardPresentPaymentEventPresentationStyle {
...
+        let tryPaymentAgainBackToCheckoutAction: () -> Void
+        let nonRetryableErrorExitAction: () -> Void
+        let formattedOrderTotalPrice: String?
+    }
+
+    static func presentationStyle(for eventDetails: CardPresentPaymentEventDetails,
+                                  dependencies: Dependencies) -> PointOfSaleCardPresentPaymentEventPresentationStyle? {
+        switch eventDetails {
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift]: Perhaps this should actually be an init on `PointOfSaleCardPresentPaymentEventPresentationStyle` – I had it in a new object because it kept some state, originally, but I decided that was a bit risky and went for static to avoid it.

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift (hunk 5 above)
Comment (staskus) [reply WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:374]: > Note that in PointOfSaleCardPresentPaymentEventPresentationStyleDeterminer.presentationStyle(for:dependencies:) we use retryAction from the payment event for the try payment again button:

Oh, got it. Thanks for the explanation!

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift]: Fixed in c1c0f89

File: WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift (hunk 6 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/Card Present Payments/PointOfSaleCardPresentPaymentEventPresentationStyle.swift]: Done in 4fe3e0a

**Comment by joshheald** [comment]
@staskus Thanks again for the review.

Note that the checklist on the description is for the reviewer now, not the author, so please take a look over and tick those off as appropriate 😊

**Review by staskus — APPROVED** [review]
Thank you for the fixes!
