### PR TITLE
[Tablet Orders] Fix both columns showing order details after quick navigation (up and down arrows in order details)

### LINKED ISSUE #11794: [Tablet Orders] Order list column shows order details
**Describe the bug**
In the new side-by-side layout on tablets, I can get into a state where both columns (usually taken up by orders list on one side, order details on the other) both show order details.

**To Reproduce**
1. Start splitview with the Woo app open to the orders tab
2. Either by changing real estate the Woo app gets or by being in portrait orientation (or both), get the Woo app to a state where it only shows order details
3. Use the arrow buttons in the header to navigate to another order
4. Close split view
5. Note behavior

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/103850310/61e2a04d-f946-469c-b6e2-db7646e74d56

**Expected behavior**
The orders list should not be over taken by roder details

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air
- iOS version: iPadOS 17.1
- WooCommerce iOS version: built from PR 11731

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #11794 

## Why

In the order details collapsed mode, there's another way to show a different order by tapping the 🔼 and 🔽 arrows in the navigation bar. After tapping to a different order this way and then expanding to the multi-column state, the new order details view controller [replaces the top of the **primary navigation controller**](https://github.com/woocommerce/woocommerce-ios/blob/98a17f93778443ec01ce53895008656de438d9a0/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/OrderDetailsViewController.swift#L204) while the secondary navigation controller still contains the first order details. Therefore, when transitioning from collapsed to multi-column state, the primary view is showing the latest order details while the secondary view shows the first order details.

## How

To properly fix it and also highlight the latest selected order in the order list in multi-column state, the order details presentation logic was moved from `OrderDetailsViewController` to `OrdersSplitViewWrapperController` so that this special case logic for "quick navigation" (top/down arrows) is handled altogether in `OrdersSplitViewWrapperController.handleSwitchingDetails`. This way, we can also sync the selected order/index path states in the order list by calling the now public `onOrderSelected`.

## Testing instructions

Prerequisite: please test this on a wide device where it can switch between collapsed & expanded states. the store has at least 2 orders to test quick navigation

- Start split view with the Woo app open to the orders tab in the **collapsed mode**
- Tap on an order
- Use the arrow buttons in the header to navigate to another order
- Expand the split view to the multi-column state --> the secondary view should show the last selected order, and the primary view should highlight the selected order

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/1945542/491ae4ab-be2c-4a5c-b291-4c05b13bb2b5

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/182">17.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift [hunk 1]
```diff
@@ -164,6 +169,9 @@ private extension OrderDetailsViewController {
         editButton.accessibilityIdentifier = "order-details-edit-button"
         editButton.isEnabled = viewModel.editButtonIsEnabled
         navigationItem.rightBarButtonItems = [editButton] + orderNavigationRightBarButtonItems()
+
+        // Disables large title.
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift]: I don't think this comment adds any value, the quick help can easily explain this if someone doesn't know what it does.
```suggestion
```

File: WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift [hunk 2]
```diff
@@ -97,10 +97,33 @@ private extension OrdersSplitViewWrapperController {
...
+            switchDetailsHandler: { [weak self] viewModels, currentIndex, isSelectedManually, completion in
+                self?.handleSwitchingDetails(viewModels: viewModels,
+                                             currentIndex: currentIndex,
+                                             isSelectedManually: isSelectedManually,
+                                             onCompletion: completion)
+            })
+
+        // When showing an order with multiple order view models to support quick navigation (up and down arrows),
+        // subsequent order details should replace the top order details view controller to avoid multiple order details
+        // in the navigation stack.
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift]:
```suggestion
        // When navigating between orders using up and down arrows, each new Order Details screen shown
        // should replace the topViewController, to avoid having to tap back through several Order Details
        // screens in the navigation stack. The back button should always go to the Order List.
        // The up and down arrows are enabled when there is more than one item in `viewModels`.
```

File: WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift [hunk 3]
```diff
@@ -97,10 +97,33 @@ private extension OrdersSplitViewWrapperController {
...
+        guard viewModels.count > 1,
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift]: We could extract this to a bool named `hasQuickOrderNavigation` or similar, to add some meaning in the code.

**Review by joshheald — APPROVED** [review]
Works well. Kudos on the explanatory comments, I've suggested some tweaks to explain a little more clearly, feel free to either accept or ignore.

File: WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift (hunk 3 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/OrdersSplitViewWrapperController.swift]: Good point! updated in https://github.com/woocommerce/woocommerce-ios/pull/11813/commits/4f51e35188f6da83c1b86f47d110beb2164bbd63

**Comment by jaclync** [comment]
Merging this after responding to all the comments for the release!
