### PR TITLE
Handle Stripe bluetoothAccessDenied error after Bluetooth access is denied

### LINKED ISSUE #13987: [Mobile Payments] Incorrect bluetooth permission error while connecting to a reader upon fresh installation
**Describe the bug**
When attempting to connect to a card reader from the Payment Hub menu with Bluetooth turned off, the app prompts the user to enable Bluetooth. If the user denies the request, an incorrect ‘Payment Failed’ error message appears. However, on subsequent attempts, the correct error message is shown. This issue seems to occur only on a fresh installation.

**To Reproduce**
1. Freshly install the WooCommerce iOS app
2. Navigate to payments settings (more menu -> payments)
3. Click on "Manage card reader"
4. Ensure bluetooth is turned off
5. Try connecting to the card reader
6. When asked for bluetooth permission, deny it
7. Observe the error message says payment failed instead of bluetooth permission missing.

https://github.com/user-attachments/assets/9a6af1ea-e0ee-4182-8c84-c166e3917ee8

**Expected behavior**
Error message should clearly indicate that the bluetooth permission must be granted to connect to a reader.

### PR DESCRIPTION
**Pull request by staskus**
Closes: #13987

## Description

When Bluetooth access is denied during the first payment, we show generic `Payment Failed` error.  On subsequent attempts, the correct error message is shown. 

## Investigation

We show correct Bluetooth access denied error on subsequent attempts because `StripeCardReaderService start(...)` explicitly checks for  `CBCentralManager.authorization != .denied` and throws  `CardReaderServiceError.bluetoothDenied`.

However, when the permission is denied during the first connection, we handle an error thrown by `Stripe` which we don't explicitly handle.

## Solution

Map Stripe `bluetoothAccessDenied` error to explicitly handle this case.

## Steps to reproduce

1. Freshly install the WooCommerce iOS app
2. Navigate to payments settings (more menu -> payments)
3. Click on "Manage card reader"
4. Ensure Bluetooth is turned off
5. Try connecting to the card reader
6. When asked for Bluetooth permission, deny it
7. Confirm a Bluetooth-denied messaging is shown
8. Make additional attempts
9. Confirm the same Blueeoth-denied messaging is shown

## Testing information

Tested different payment entry points. All result in the expected error now. iPhone 14 Po 17.7.

## Screenshots

https://github.com/user-attachments/assets/d0ad8816-6983-43d8-8197-bb7b8f69b5e0

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

File: Hardware/Hardware/CardReader/UnderlyingError.swift [hunk 1]
```diff
@@ -324,6 +327,12 @@ extension UnderlyingError: LocalizedError {
             return NSLocalizedString("Unable to connect to reader - the reader has a critically low battery - charge the reader and try again.",
                                      comment: "Error message the card reader battery level is too low to connect to the phone or tablet.")
 
+        case .bluetoothDenied:
+            return NSLocalizedString(
+                "hardware.cardReader.underlyingError.bluetoothDenied",
+                value: "This app needs permission to access Bluetooth to connect to a card reader, please change the privacy settings if you wish to allow this.",
```
Comment (joshheald) [inline Hardware/Hardware/CardReader/UnderlyingError.swift]:
```suggestion
                value: "This app needs permission to access Bluetooth to connect to your card reader. You can grant permission in the system's Settings app, in the Woo section.",
```

A button which took them to the right place would obviously be better, but if you use wording like this it may help steer some people to the right place.

**Review by joshheald — APPROVED** [review]
Works well, thanks for fixing this! One wording suggestion added. There's potential to add a button to go to the right place in settings but worth merging this first and having that as another issue which maybe tackles any error that needs dealing with in settings.

File: Hardware/Hardware/CardReader/UnderlyingError.swift (hunk 1 above)
Comment (staskus) [reply Hardware/Hardware/CardReader/UnderlyingError.swift]: Thanks for the suggestion! 

Yes, I agree that having a button to go straight into the privacy settings would be more convenient. I'll check if it's a quick improvement and can make another PR, or just create another improvement task in the backlog.
