### PR TITLE
[Mobile Payments] Refresh Upsell Card Readers Banner when opening Settings.

### LINKED ISSUE #7322: [Upsell Card Readers] Upsell Banner is not getting removed after going back to "Settings"
**Describe the bug**
From [comment](https://github.com/woocommerce/woocommerce-ios/pull/7308#pullrequestreview-1046581884) to #7308
In essence, it's about Setting screen not being refreshed when the merchant goes back to it from the other screen:

https://user-images.githubusercontent.com/73365754/180305937-de59d93f-27d7-4903-85f5-c339dbf9e6e7.MP4

**To Reproduce**

1. Open Settings and make sure the banner is there
2. Tap Orders (the important part here is that Settings remain the active screen in Menu)
3. Dismiss a banner via collect payment screen
4. Open Menu ~> the Settings will still contain the banner.

**Expected behavior**
The banner should be removed after going back to "Settings"

### PR DESCRIPTION
**Pull request by toupper**
Closes: #7322

⛔ Do not merge until [ebc8bb39a6810a1535aff8bea6a157a251fa4003](https://github.com/woocommerce/woocommerce-ios/commit/ebc8bb39a6810a1535aff8bea6a157a251fa4003) is reverted: This is just to make testing easier. With that test code we:
- Reset the banner policy show when starting the app, so it can be shown again even if the user dismissed it before.
- Set the remind me later to 20 seconds instead of 14 days, so it can be tested faster.

Reverted in https://github.com/woocommerce/woocommerce-ios/pull/7348/commits/3c543d685e0b20d8e6a776c05bd1620da50b78fe

### Description

As @pachlava  explained [here](https://github.com/woocommerce/woocommerce-ios/issues/7322) we were not refreshing the settings view when it appears. Because of that, if while the settings view is loaded (by opening it) we dismiss the upsell card reader banner in other places (e.g orders list, payment methods screen) the banner remains in settings. Once we go back and open it again it disappears.
By reloading settings in `viewWillAppear` we are sure to refresh the banner visibility logic, removing it if it was dismissed elsewhere.
Furthermore, we remove the `onUpsellCardReadersAnnouncementDismiss` method that was calling `reloadSettings` internally, because the latter is now public and we can call it directly. Because of that, the former is no longer needed.
#### Before - The banner remains in Settings

https://user-images.githubusercontent.com/1864060/181010415-534a8816-6e85-4333-8cde-c06e3b2df6c9.mp4

#### After - The banner is also dismissed in Settings

https://user-images.githubusercontent.com/1864060/181011718-431d1186-3da4-47dc-99cc-884eab35dee3.mp4

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by pachlava — APPROVED** [review]
Thanks for fixing this @toupper 👋 !

All good from my side: I've checked with real iPhone 13 Pro, and iPad Air Simulator, and noticed no issues 👍  :shipit:

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift [hunk 1]
```diff
@@ -59,6 +59,12 @@ final class SettingsViewController: UIViewController {
         viewModel.onViewDidLoad()
     }
 
+    override func viewWillAppear(_ animated: Bool) {
+        super.viewWillAppear(animated)
+
+        viewModel.reloadSettings()
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift:65]: I'm wondering if we want to reload all settings sections every time we land on the settings screen? Just raising the question because you're much more experienced:

If `viewWillAppear` is called each time we land on the page, and we're reloading all `Sections` on the main thread, I was wondering if there's something in these `Sections` that is happening in a background thread and could cause data to not be updated properly, for example `isJetpackCPConnected` seems to be coming from Networking.

**Review by iamgabrielma — APPROVED** [review]
LGTM! 🚀  

I left a comment that is more of a question 👍

As the previous ones, the failing test is expected to fail while the testing code is active  :
```
YosemiteTests.AppSettingsStoreTests
test_setFeatureAnnouncementDismissed_with_remindLater_true_stores_reminder_date_in_two_weeks
```

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift (hunk 1 above)
Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/Settings/SettingsViewController.swift:65]: Good point here @iamgabrielma :) 

> If viewWillAppear is called each time we land on the page, and we're reloading all Sections on the main thread, I was wondering if there's something in these Sections that is happening in a background thread and could cause data to not be updated properly, for example isJetpackCPConnected seems to be coming from Networking.

Actually, I do not see any call that might make us refresh in a background thread here :) `stores.sessionManager.defaultSite?.isJetpackCPConnected == true` is not changing the thread, it is just checking for that property in the same thread as it was called, presumably in the main one. As the method is totally synchronous, we can be certain about this assumption.
Nevertheless, I considered that it might be a little bit overkill to load all settings when we just want to hide the banner. After that consideration, I assumed that the simplicity of code and easiness of effort is a good trade-off for this. In any case, we are not applying large computations for reloading the settings, so after all it might not be that expensive.
