### PR TITLE
Keep track of notification count and update the badges on Orders/Reviews tab and application icon accordingly

### LINKED ISSUE #1388: Notification Badge: it doesn't disappear when you select Orders tab
#2438723-zen

It appears that the red badge count on the app icon is tied only to the Reviews screen, and not to the Orders screen.

The only way to get rid of the notification badge is to visit the reviews tab (also if reviews are disabled on the website).

Seems that the notification badge needs to be tied also to the Orders screen, and not only to Reviews.

Looking at the code
```
ServiceLocator.pushNotesManager.resetBadgeCount()
```
this method is called only inside `ReviewsViewController`, `NotificationsViewController` and `DefaultStoresManager`.

**Steps to reproduce the behavior:**
1. Get some push notifications about a new order.
2. Open the app.
3. Tap on Orders tab
4. The red badge on the app is still there.
5. Tap the Reviews tab.
6. The red badge disappear.

### LINKED ISSUE #1735: Orders/Notifications: Reviews tab gets a badge when a new order is received
**Describe the bug**

After receiving a new order, the Reviews tab in the app gets a badge even though there are no new reviews.

**To Reproduce**
1. Open the app and visit the Reviews tab to clear any badge on the Reviews tab icon.
2. Exit the app.
3. Receive a new order on your store.
4. Tap the push notification for the new order.
5. Confirm the new order details open (expected) but the Reviews tab also gets a badge (unexpected).

**Screenshots**

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.4.0.0 TestFlight build

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1388 
Fixes #1735 

- [x] ⚠️ Update PR base to `develop` after https://github.com/woocommerce/woocommerce-ios/pull/2318 is merged ⚠️ 

Discussion & proposed implementation plan: p91TBi-2pK-p2

Before this PR, we handled push notifications from a new order and review all the same, which resulted in issues #1388 and #1735. In this PR, we start keeping track of the notification count for each type and site so that we can update the dot on the Reviews tab and app badge count accordingly.

## Notification count definition (per site)
- Each site has a dictionary if the app has received push notifications of type `Dictionary<Note.Kind, Int>`. The key (`Note.Kind`) is the notification type:
    - `storeOrder`: incremented when a new order push notification is received (this number is different from the badge number we show on the Orders tab, which is the number of processing orders)
    - `comment`: incremented when a new review push notification is received
- The tracking is preserved when the user switches to another site
- The tracking is only reset after the user logs out
- We only start tracking the notification count from the version this fix is released. This means that if the app has pre-existing app badge count or a badge on the Reviews tab, we won’t restore them since we didn’t track which type(s) of push notifications the pre-existing app badge number has. Please let me know if you have any concerns about this behavior!

## Application badge number & Reviews tab dot update timing

- When a push notification of a supported type is received (so far just new order and review): after the notification count is incremented internally, loads the latest notification count and sets the app badge number with the value
- When the user clears the notification count for a type (e.g. from visiting the Orders or Reviews tab): loads the latest notification count and sets the app badge number with the value
- When switched to another store: loads the notification count of the new site and sets the app badge number with the value
- When the user logs out: resets to 0

## Changes

- Added a new notification `reviewsBadgeReloadRequired` for `PushNotificationsManager` to post updates when it should reload the notification count for the Reviews tab
- Created `NotificationCountAction` and `NotificationCountStore` that handles the actions. There are 4 types of actions:
  - `incrementNotificationCount(siteID: Int64, type: Note.Kind, incrementCount: Int, onCompletion: () -> Void)`: called when a push notification is received
  - `loadNotificationCount(siteID: Int64, type: Note.Kind?, onCompletion: (_ count: Int) -> Void)`: called when we want to get the latest notification count
  - `resetNotificationCount(siteID: Int64, type: Note.Kind, onCompletion: () -> Void)`: called when we are clearing the notifications for a given type (e.g. when visiting the Orders or Reviews tab)
  - `resetNotificationCountForAllSites(onCompletion: () -> Void)`: called when the user logs out
- Updated unit tests

### Step 0: clear all app badge number and Reviews tab badge

- Before testing for this PR, please make sure the app badge number is 0 (no badge number), and there's no dot on the Reviews tab by navigating to the Reviews tab

### Receiving a new order push notification

- On web, place a new order on the site that the app is logged in to —> the app should receive a push notification, and the app icon has a badge of 1
- Tap on the push notification —> should be brought to the Order details, and there should be **no dot on the Reviews tab** (issue #1735)
- After the Order details are loaded, the app icon should not have a badge anymore (issue #1388)

### Receiving a new review push notification

- On web, submit a new review for a product on the site that the app is logged in to —> the app should receive a push notification, and the app icon has a badge of 1
- Go back to the app (make sure it wasn't on the Reviews tab beforehand)  —> there should be a purple dot on the Reviews tab
- Go to "My store" tab and switch to another store --> the app icon should have no badge and there is no purple dot on the Reviews tab
- Switch back to the original store --> the app icon should have badge of 1 and there is a purple dot on the Reviews tab
- Go to the Reviews tab --> the app icon should have no badge and there is no purple dot on the Reviews tab

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+        try! fileStorage.write(data, to: URL(fileURLWithPath: ""))
+
+        var notificationCount: Int?
+        waitForExpectation { expectation in
+            let action = NotificationCountAction.incrementNotificationCount(siteID: defaultSiteID, type: .comment, incrementCount: 10) {
+                let loadAction = NotificationCountAction.loadNotificationCount(siteID: self.defaultSiteID, type: .comment) { count in
+                    notificationCount = count
+                    expectation.fulfill()
+                }
+                self.subject.dispatcher.dispatch(loadAction)
```
Comment (shiki) [inline Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift:54]: I'm curious why the `self.dispatcher` is not enough. The test still seems to pass. 🤔 Or maybe `subject.onAction`?

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+            }
+            subject.dispatcher.dispatch(action)
+        }
+
+        XCTAssertEqual(notificationCount, 0)
+    }
+
+    func testResettingNotificationCountForASiteDoesNotAffectAnotherSite() {
```
Comment (shiki) [inline Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift:98]: Nice test names! 🎉

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+    // MARK: `resetNotificationCount`
+
+    func testResettingNotificationCountOfAGivenTypeReturns0() {
+        let data = NotificationCountPListWrapper(notificationCountBySite: [defaultSiteID: [.comment: 2, .storeOrder: 6]])
+        try! fileStorage.write(data, to: URL(fileURLWithPath: ""))
+
+        var notificationCount: Int?
+        waitForExpectation { expectation in
+            let action = NotificationCountAction.resetNotificationCount(siteID: defaultSiteID, type: .comment) {
+                let loadAction = NotificationCountAction.loadNotificationCount(siteID: self.defaultSiteID, type: .comment) { count in
```
Comment (shiki) [inline Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift:86]: This makes me wonder whether we should return the current count in the `resetNotificationCount` callback. 😄

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+
+        // Action
+        var notificationCountOfDefaultSite: Int?
+        var notificationCountOfAnotherSite: Int?
+        waitForExpectation { expectation in
+            let action = NotificationCountAction.resetNotificationCountForAllSites {
+                let loadDefaultSiteCountAction = NotificationCountAction.loadNotificationCount(siteID: self.defaultSiteID, type: nil) { count in
+                    notificationCountOfDefaultSite = count
+
+                    if notificationCountOfDefaultSite != nil && notificationCountOfAnotherSite != nil {
```
Comment (shiki) [inline Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift:143]: Perhaps we can do something like:

1. Add a `count` (default 1) argument in `waitForExpectation` which sets:

    ```swift
        exp.expectedFulfillmentCount = count
    ```
2. Use that in here:

    ```swift
        waitForExpectation(count: 2) { expectation in
    ```
3. Remove this code. 🙂

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift [hunk 5]
```diff
@@ -0,0 +1,166 @@
+import XCTest
+
+@testable import Storage
+@testable import Yosemite
+
+final class NotificationCountStoreTests: XCTestCase {
```
Comment (shiki) [inline Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift:6]: 👏 Really nice tests!

File: Yosemite/Yosemite/Actions/NotificationCountAction.swift [hunk 6]
```diff
@@ -0,0 +1,23 @@
+import Foundation
+import Storage
+
+// MARK: - NotificationCountAction: Defines all of the Actions supported by the NotificationCountStore.
+//
+public enum NotificationCountAction: Action {
+    /// Increments the notification count by a given amount and type for a site of the given ID.
+    ///
+    case incrementNotificationCount(siteID: Int64, type: Note.Kind, incrementCount: Int, onCompletion: () -> Void)
```
Comment (shiki) [inline Yosemite/Yosemite/Actions/NotificationCountAction.swift:9]: I always wonder whether we're being too verbose in our action names. For example, I feel like `NotificationCountAction` gives me enough context to know that this shortened name:

```swift
    case increment(siteID: Int64, type: Note.Kind, change: Int, onCompletion: () -> Void)
```

Will “increment the notification count”. 

🤷

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift [hunk 7]
```diff
@@ -0,0 +1,166 @@
+import XCTest
+
+@testable import Storage
```
Comment (shiki) [inline Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift:3]: This import does not seem to be needed.

```suggestion

```

File: WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift [hunk 8]
```diff
@@ -42,7 +42,11 @@ final class PushNotificationsManagerTests: XCTestCase {
         defaults = UserDefaults(suiteName: Sample.defaultSuiteName)
         defaults.removePersistentDomain(forName: Sample.defaultSuiteName)
 
+        // Most of the test cases expect a nil site ID, otherwise the dispatched actions would not match.
         storesManager = MockupStoresManager(sessionManager: .testingInstance)
+        storesManager.sessionManager.setStoreId(nil)
+        ServiceLocator.setStores(storesManager)
```
Comment (shiki) [inline WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift:48]: When I removed this, the tests still passed. 🤔 Maybe it's not needed?

```suggestion

```

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift [hunk 9]
```diff
@@ -51,6 +51,9 @@ final class PushNotificationsManager: PushNotesManager {
         }
     }
 
+    private var siteID: Int64? {
+        ServiceLocator.stores.sessionManager.defaultStoreID
```
Comment (shiki) [inline WooCommerce/Classes/Notifications/PushNotificationsManager.swift:55]: ⚠️  There's an injected `storesManager` via `configuration`:

```suggestion
        configuration.storesManager.sessionManager.defaultStoreID
```

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift [hunk 10]
```diff
@@ -121,10 +124,30 @@ extension PushNotificationsManager {
...
-    func resetBadgeCount() {
-        configuration.application.applicationIconBadgeNumber = 0
+    func resetBadgeCount(type: Note.Kind) {
+        guard let siteID = siteID else {
+            return
+        }
+        let action = NotificationCountAction.resetNotificationCount(siteID: siteID, type: type) { [weak self] in
+            self?.loadNotificationCountAndUpdateApplicationBadgeNumberAndPostNotifications(siteID: siteID, type: type)
+        }
+        ServiceLocator.stores.dispatch(action)
```
Comment (shiki) [inline WooCommerce/Classes/Notifications/PushNotificationsManager.swift:134]: ⚠️  Same as above, we don't need to use `ServiceLocator` since there is an injected `configuration`.

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift [hunk 11]
```diff
@@ -121,10 +124,30 @@ extension PushNotificationsManager {
...
+    }
+
+    func resetBadgeCountForAllStores(onCompletion: @escaping () -> Void) {
+        let action = NotificationCountAction.resetNotificationCountForAllSites() { [weak self] in
+            self?.configuration.application.applicationIconBadgeNumber = 0
+            onCompletion()
+        }
+        ServiceLocator.stores.dispatch(action)
```
Comment (shiki) [inline WooCommerce/Classes/Notifications/PushNotificationsManager.swift:142]: ⚠️  Same as above, we don't need to use `ServiceLocator` since there is an injected `configuration`.

File: WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift [hunk 12]
```diff
@@ -82,8 +87,21 @@ final class PushNotificationsManagerTests: XCTestCase {
     /// Verifies that `resetBadgeCount` sets the badgeNumber to zero
     ///
     func testResetBadgeCountEffectivelyDropsTheBadgeNumberToZero() {
+        // Arrange
+        // The default stores are required to update the application badge number.
+        let stores = DefaultStoresManager.testingInstance
+        ServiceLocator.setStores(stores)
```
Comment (shiki) [inline WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift:93]: Same as above, I don't think we need the `ServiceLocator.setStores` since the `storesManager` is injected.

File: WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift [hunk 13]
```diff
@@ -2,6 +2,7 @@
 import Foundation
 import UIKit
 @testable import WooCommerce
+@testable import Yosemite
```
Comment (shiki) [inline WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift:5]: I don't think we need the `@testable`

```suggestion
import Yosemite
```

File: WooCommerce/Classes/ViewRelated/MainTabBarController.swift [hunk 14]
```diff
@@ -333,28 +331,36 @@ extension MainTabBarController {
 }
 
 
-// MARK: - Tab dot madness!
+// MARK: - Reviews Tab Badge Updates
```
Comment (shiki) [inline WooCommerce/Classes/ViewRelated/MainTabBarController.swift:334]: I'm introducing a `ReviewsCoordinator` in a future PR to hopefully encapsulate some of these. Hopefully. 😄 

It looks like we started using Coordinators but it never took off. 

https://github.com/woocommerce/woocommerce-ios/blob/eec8ec29b4cfc8e215ecd1550d6f5ee434d07dcd/WooCommerce/Classes/Tools/Coordinator.swift#L4-L12

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift [hunk 15]
```diff
@@ -213,6 +234,46 @@ extension PushNotificationsManager {
...
+    func loadNotificationCountAndUpdateApplicationBadgeNumberAndPostNotifications(siteID: Int64, type: Note.Kind?) {
+        loadNotificationCountAndUpdateApplicationBadgeNumber(siteID: siteID)
+        postBadgeReloadNotifications(type: type)
+    }
+
+    func loadNotificationCountAndUpdateApplicationBadgeNumber(siteID: Int64) {
+        let action = NotificationCountAction.loadNotificationCount(siteID: siteID, type: nil) { [weak self] count in
+            self?.configuration.application.applicationIconBadgeNumber = count
+        }
+        ServiceLocator.stores.dispatch(action)
```
Comment (shiki) [inline WooCommerce/Classes/Notifications/PushNotificationsManager.swift:254]: ⚠️  Same as above, we don't need to use `ServiceLocator` since there is an injected `configuration`.

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift [hunk 16]
```diff
@@ -213,6 +234,46 @@ extension PushNotificationsManager {
...
 
+// MARK: - Notification count & app badge number update
+//
+private extension PushNotificationsManager {
+    func incrementNotificationCount(siteID: Int64, type: Note.Kind, incrementCount: Int, onCompletion: @escaping () -> Void) {
+        let action = NotificationCountAction.incrementNotificationCount(siteID: siteID, type: type, incrementCount: incrementCount, onCompletion: onCompletion)
+        ServiceLocator.stores.dispatch(action)
+    }
+
+    func loadNotificationCountAndUpdateApplicationBadgeNumberAndPostNotifications(siteID: Int64, type: Note.Kind?) {
```
Comment (shiki) [inline WooCommerce/Classes/Notifications/PushNotificationsManager.swift:245]: What a mouthful. 😄

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 17]
```diff
@@ -0,0 +1,117 @@
...
+            resetNotificationCount(siteID: siteID, type: type, onCompletion: onCompletion)
+        case .resetNotificationCountForAllSites(let onCompletion):
+            resetNotificationCountForAllSites(onCompletion: onCompletion)
+        }
+    }
+}
+
+
+private extension NotificationCountStore {
+    func incrementNotificationCount(siteID: Int64, type: Note.Kind, incrementCount: Int, onCompletion: () -> Void) {
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift:58]: yea I guess we could go without a callback with the current PList implementation, the file read/write just felt like an async operation to me (like if we ever switch to writing data to a database, or moving the file I/O to the background thread as you mentioned)

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift (hunk 3 above)
Comment (jaclync) [reply Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift]: yea I thought about it, but we don't currently use the reset count in the app 😐 okay to keep it this way for now?

File: Yosemite/Yosemite/PListStorage/NotificationCountPListWrapper.swift [hunk 18]
```diff
@@ -0,0 +1,25 @@
+extension Note.Kind: Codable {}
+
+/// A wrapper of a dictionary that maps from a site ID to a dictionary from notification type to count.
+///
+struct NotificationCountPListWrapper: Codable, Equatable {
+    let notificationCountBySite: [Int64: [Note.Kind: Int]]
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/PListStorage/NotificationCountPListWrapper.swift]: updated in: https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/a8f99d364295b007562964e0cf49490e12a495f8

File: Yosemite/Yosemite/PListStorage/NotificationCountPListWrapper.swift [hunk 19]
```diff
@@ -0,0 +1,25 @@
+extension Note.Kind: Codable {}
+
+/// A wrapper of a dictionary that maps from a site ID to a dictionary from notification type to count.
+///
+struct NotificationCountPListWrapper: Codable, Equatable {
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/PListStorage/NotificationCountPListWrapper.swift]: good point! updated in: https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/d23716f2f75f51079e11d2f64986a070cdcc16fa

File: Yosemite/Yosemite/PListStorage/NotificationCountPListWrapper.swift [hunk 20]
```diff
@@ -0,0 +1,25 @@
...
+    let notificationCountBySite: [Int64: [Note.Kind: Int]]
+
+    public init(notificationCountBySite: [Int64: [Note.Kind: Int]]) {
+        self.notificationCountBySite = notificationCountBySite
+    }
+}
+
+extension NotificationCountPListWrapper {
+    func notificationCount(siteID: Int64, type: Note.Kind?) -> Int {
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/PListStorage/NotificationCountPListWrapper.swift]: yea I like it! updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/529fc80d4367a410d39469a48d7c1a655eb291c1

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 21]
```diff
@@ -0,0 +1,117 @@
...
+            return
+        }
+
+        var notificationCountBySite = existingData.notificationCountBySite
+        if let existingNotificationCountByType = notificationCountBySite[siteID] {
+            let newCount = (existingNotificationCountByType[type] ?? 0) + incrementCount
+            notificationCountBySite[siteID]?[type] = newCount
+        } else {
+            notificationCountBySite[siteID] = [type: incrementCount]
+        }
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift]: great idea! I moved these dictionary updates to functions that return updated data (so no need to use `mutating`): https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/eb6c89641298ec7164416beebffba5c61d50bf90

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 22]
```diff
@@ -0,0 +1,117 @@
+import Storage
+import Networking
+
+// MARK: - NotificationCountStore
+//
+public class NotificationCountStore: Store {
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift]: yup! updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/a1e306b12077c93ffacb2d7b6467e1be0316f97f

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 23]
```diff
@@ -0,0 +1,117 @@
...
+        super.init(dispatcher: dispatcher,
+                   storageManager: storageManager,
+                   network: NullNetwork())
+    }
+
+    /// URL to the plist file that we use to determine the notification count.
+    ///
+    private lazy var notificationCountURL: URL = {
+        let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first
+        return documents!.appendingPathComponent(Constants.notificationCountFileName)
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift]: yep I generally prefer `fatalError` to `!` as well (but forgot to update from borrowing code from somewhere else), updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/a1e306b12077c93ffacb2d7b6467e1be0316f97f

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 24]
```diff
@@ -0,0 +1,117 @@
...
+                fileStorage: FileStorage) {
+        self.fileStorage = fileStorage
+        super.init(dispatcher: dispatcher,
+                   storageManager: storageManager,
+                   network: NullNetwork())
+    }
+
+    /// URL to the plist file that we use to determine the notification count.
+    ///
+    private lazy var notificationCountURL: URL = {
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift]: yup! updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/a1e306b12077c93ffacb2d7b6467e1be0316f97f

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 25]
```diff
@@ -0,0 +1,117 @@
...
+            resetNotificationCountForAllSites(onCompletion: onCompletion)
+        }
+    }
+}
+
+
+private extension NotificationCountStore {
+    func incrementNotificationCount(siteID: Int64, type: Note.Kind, incrementCount: Int, onCompletion: () -> Void) {
+        let fileURL = notificationCountURL
+        guard let existingData: NotificationCountPListWrapper = try? fileStorage.data(for: fileURL) else {
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift]: good idea! updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/dfebb67963c1ba2dfe5b68ca409c30474f7e1d88

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift (hunk 1 above)
Comment (jaclync) [reply Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift]: no particular reason, just from the other tests in the codebase 😅 I like `subject.onAction` so that it doesn't depend on how the dispatcher works 👍 updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/df4256ff84a5821d71b53e43c44c217f4696eb67

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift (hunk 4 above)
Comment (jaclync) [reply Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift]: this is a really cool suggestion! updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/829ae5239a4e82485be4811c9bc1c383ba715982

File: Yosemite/Yosemite/Actions/NotificationCountAction.swift (hunk 6 above)
Comment (jaclync) [reply Yosemite/Yosemite/Actions/NotificationCountAction.swift]: I agree, these action names could be more concise since we always call with the enum name. updated in: https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/5d4ac44b89a427313c829dc21062539b2427c8ce

File: Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift (hunk 7 above)
Comment (jaclync) [reply Yosemite/YosemiteTests/Stores/NotificationCountStoreTests.swift]: yup updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/674b6fbf3cb42be622dfaad802ab34e20d3b3b7c

File: WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift (hunk 13 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/Mockups/MockPushNotificationsManager.swift]: updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/bb9b20151fad7435498c43f544ba7ba7db59bb78

File: WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift (hunk 8 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift]: I struggled with these app singletons (`storesManager` and `sessionManager`) for quite a while before making the PR 😓 

thanks to your suggestions below about using `storesManager` from `configuration` instead of the global singleton, it's indeed not needed anymore! removed in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/7620bb0da4f901ebfd141939e5511a9ab657c39e

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift (hunk 9 above)
Comment (jaclync) [reply WooCommerce/Classes/Notifications/PushNotificationsManager.swift]: thanks for the suggestion! this made it possible to DI the `storesManager`. updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/7620bb0da4f901ebfd141939e5511a9ab657c39e

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift (hunk 10 above)
Comment (jaclync) [reply WooCommerce/Classes/Notifications/PushNotificationsManager.swift]: similar to above, updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/7620bb0da4f901ebfd141939e5511a9ab657c39e

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift (hunk 11 above)
Comment (jaclync) [reply WooCommerce/Classes/Notifications/PushNotificationsManager.swift]: similar to above, updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/7620bb0da4f901ebfd141939e5511a9ab657c39e

File: WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift (hunk 12 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/Notifications/PushNotificationsManagerTests.swift]: similar to above, updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/7620bb0da4f901ebfd141939e5511a9ab657c39e

File: WooCommerce/Classes/ViewRelated/MainTabBarController.swift (hunk 14 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/MainTabBarController.swift:334]: sounds like a great idea! the navigation code is now scattered in the view controllers. it would be cool to try using Coordinators 👍

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift (hunk 15 above)
Comment (jaclync) [reply WooCommerce/Classes/Notifications/PushNotificationsManager.swift]: similar to previous comments, updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/7620bb0da4f901ebfd141939e5511a9ab657c39e

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift [hunk 26]
```diff
@@ -129,6 +129,8 @@ class OrdersViewController: UIViewController {
         // Fix any _incomplete_ animation if the orders were deleted and refetched from
         // a different location (or Orders tab).
         tableView.reloadData()
+
+        ServiceLocator.pushNotesManager.resetBadgeCount(type: .storeOrder)
```
[the remark this answers is not in the document]
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: great catch! updated in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/eb21b747027fd43fae2e337186b687508e354aae

**Comment by jaclync** [comment]
thanks a lot for the helpful feedback @shiki ! I believe I responded to all the comments for another pass 😄 (I also tested the flow again)

File: Yosemite/Yosemite/Stores/NotificationCountStore.swift [hunk 27]
```diff
@@ -0,0 +1,122 @@
...
+        super.init(dispatcher: dispatcher,
+                   storageManager: storageManager,
+                   network: NullNetwork())
+    }
+
+    /// URL to the plist file that we use to determine the notification count.
+    ///
+    private lazy var fileURL: URL = {
+        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
+            fatalError()
```
[the remark this answers is not in the document]
Comment (jaclync) [reply Yosemite/Yosemite/Stores/NotificationCountStore.swift]: 😅 added in https://github.com/woocommerce/woocommerce-ios/pull/2320/commits/30b292c34a75b75901ce6def62eebe0ec9831166

**Comment by jaclync** [comment]
thanks a lot for the review & testing 🙏 merging now!
