### PR TITLE
Fix: password encoding in application passwords login

### LINKED ISSUE #9051: Cannot login to self-hosted site with store credentials
**Describe the bug**
The WooCommerce iOS app [link](https://apps.apple.com/us/app/woocommerce/id1389130815) does not allow an admin to login to the store using their Wordpress username+password. **Please notice that the same credentials work perfectly fine in WooCommerce Android app.** We are not using Jetpack.

**To Reproduce**
1. Download the WooCommerce iOS app and open it
2. Click on 'Enter your store address'
3. Type in the URL (https://boycapelvintage.com/)
4. Type in the user credentials of any admin
5. Notice the error: "It looks like this username/password isn't associated with this site."

**Expected behavior**
The login process can finish successfully and the administrators can use the iOS app to manage the store/inventory.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Other details**
- As mentioned before, the same user+password combinations work fine on the Android app.
- When entering the URL, we've prefixed the HTTPS, as well as www without success
- We tried logging in with usernames or their emails too, it doesn't work.
- XMLRPC is enabled.
- We tried using the apps with the Jetpack plug-in but it was too bothersome. It is currently disabled.

**Screenshots**

IMG_7345

Discord_44FRnDM7z4 mp4_snapshot_00 59 550

**Mobile Environment**
Please include:
- Device: iPhone 13, iPhone X
- iOS version: latest version

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.boycapelvintage.com
Site address (URL): https://www.boycapelvintage.com
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.17
PHP Post Max Size: 0 B
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.6.7-MariaDB
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 479.76MB
Database Data Size: 413.27MB
Database Index Size: 66.49MB
wp_woocommerce_sessions: Data: 66.09MB + Index: 3.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.52MB + Index: 3.88MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_awb_critical_css: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_braapf_product_variation_attributes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variable_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 9.06MB + Index: 1.19MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 124.67MB + Index: 16.03MB + Engine InnoDB
wp_posts: Data: 138.16MB + Index: 8.97MB + Engine InnoDB
wp_redirection_404: Data: 6.02MB + Index: 4.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 1.02MB + Index: 0.30MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stock_log: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_tinvwl_analytics: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
wp_tinvwl_items: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_todopago_google_address: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_todopago_transaccion: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_todopago_transaccion2: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.23MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 0.95MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_remove_bg: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_remove_bg_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_slazzer_process_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_slazzer_process_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 3.52MB + Index: 6.88MB + Engine InnoDB
wp_wsal_occurrences: Data: 2.52MB + Index: 0.59MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 37.44MB + Index: 11.34MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.16MB + Index: 0.58MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.27MB + Index: 0.16MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 2
attachment: 28369
awb_off_canvas: 5
br_filters_group: 2
br_product_filter: 18
custom_css: 1
customize_changeset: 1
fusion_element: 60
fusion_form: 6
fusion_icons: 3
fusion_tb_layout: 20
fusion_tb_section: 42
fusion_template: 1
nav_menu_item: 185
page: 37
post: 12
product: 7473
revision: 2819
shop_coupon: 1
shop_order: 178
shop_order_refund: 3
slide: 3
wpcode: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

A-Z Listing: by Dani Llewellyn – 4.3.1
Advanced Custom Fields: by WP Engine – 6.0.7
All-in-One WP Migration FTP Extension: by ServMask – 2.73
All-in-One WP Migration: by ServMask – 7.71
Better Search Replace: by WP Engine – 1.4.2
WordPress Backup & Security Plugin - BlogVault: by Backup by BlogVault – 4.87
Payment Gateway Based Fees and Discounts for WooCommerce: by Tyche Softwares – 2.9.0
Click to Chat: by HoliThemes – 3.23
Duplicate Menu: by Jonathan Christopher – 0.2.2
Fr Multi Bank Transfer Payment Gateways for WooCommerce: by Fahri Rusliyadi – 1.1.0
Avada Builder: by ThemeFusion – 3.9.2
Avada Core: by ThemeFusion – 5.9.2
Avada Custom Branding: by ThemeFusion – 1.2
WPCode Lite: by WPCode – 2.0.8.1
Smash Balloon Instagram Feed: by Smash Balloon – 6.1.2
Loco Translate: by Tim Whitlock – 2.6.3
Nextend Social Login: by Nextendweb – 3.1.7
Nextend Social Login Pro Addon: by Nextendweb – 3.1.7
Really Simple SSL: by Really Simple Plugins – 6.2.0
Redirection: by John Godley – 5.3.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Slider Revolution: by ThemePunch – 6.6.10
SMNTCS Disable REST API User Endpoints: by Niels Lange – 2.0
TI WooCommerce Wishlist: by TemplateInvaders – 2.3.5
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.6.3.4
Call for Price for WooCommerce: by Tyche Softwares – 3.5.0
WooCommerce Stripe Gateway: by WooCommerce – 7.1.0
Mercado Pago payments for WooCommerce: by Mercado Pago – 6.7.1
CURCY - WooCommerce Multi Currency Premium: by VillaTheme – 2.2.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.2
Stock Manager for WooCommerce: by StoreApps – 2.10.0
WooCommerce: by Automattic – 7.4.1
Yoast SEO: by Team Yoast – 20.2.1
WP Activity Log for WooCommerce: by WP White Security – 1.5.0
WP Add Mime Types: by Kimiya Kitani – 3.0.3
WP All Import Pro: by Soflyy – 4.7.8
WP Frontend Delete Account: by Sanjeev Aryal – 1.7.0
WP Mail SMTP: by WPForms – 3.7.0
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.5
WP Activity Log: by WP White Security – 4.4.3.2
WP All Import - ACF Add-On: by Soflyy – 3.3.8
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.4

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 5.0.2
AMP: by AMP Project Contributors – 2.4.0
CURCY - Multi Currency for WooCommerce: by VillaTheme – 2.1.28
Jetpack: by Automattic – 11.8.4
PWA: by PWA Plugin Contributors – 0.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #2110 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #1070 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada
Version: 7.9.2
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-07 13:48:52 -03:00
Options: ✔
Notes: 82
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,229
Oldest: 2023-02-06 18:47:20 +0000
Newest: 2023-03-06 13:21:37 +0000

Failed: 1
Oldest: 2023-03-06 13:44:22 +0000
Newest: 2023-03-06 13:44:22 +0000

Pending: 2
Oldest: 2023-03-06 19:26:39 +0000
Newest: 2023-03-07 01:27:40 +0000


### Status report information ###

Generated at: 2023-03-06 13:02:13 -03:00
````
</details>

### PR DESCRIPTION
**Pull request by pmusolino**
Closes #9051 

## Description
A user of an agency opened an issue on Github, detailing how he could log in with the Android app but not the iOS app due to an invalid credentials error using application passwords. The issue was on the app and was able to work with the user to carry out tests. The cause of the issue was a special `+` sign in the password that was not being converted to `%2B` during the API call, which it should have been.
More here: wp-pe5sF9-1gt

## Testing instructions
1. Use a WooCommerce store without Jetpack and configure an admin user.
2. Configure a password that contains the `+` character.
3. Try to login into the app.
4. It should work as expected.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/NetworkingTests/ApplicationPassword/CookieNonceAuthenticatorTests.swift [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+        // Given
+        let config = CookieNonceAuthenticatorConfiguration(username: sampleUser,
+                                                           password: samplePassword,
+                                                           loginURL: loginURL,
+                                                           adminURL: adminURL)
+        let authenticator = CookieNonceAuthenticator(configuration: config)
+
+
+        let generatedBodyAsData = authenticator.authenticatedRequest().urlRequest!.httpBody!
+        let generatedBodyAsString = String(data: generatedBodyAsData, encoding: .utf8)
```
Comment (itsmeichigo) [inline Networking/NetworkingTests/ApplicationPassword/CookieNonceAuthenticatorTests.swift]: Nit: we should use `try XCTUnwrap` instead of forced unwrapping to avoid crashing the test:

```suggestion
        let generatedBodyAsData = try XCTUnwrap(authenticator.authenticatedRequest().urlRequest?.httpBody)
        let generatedBodyAsString = try XCTUnwrap(String(data: generatedBodyAsData, encoding: .utf8))
```

**Review by itsmeichigo — APPROVED** [review]
Thanks for the fix! 🚀
