### PR TITLE
Fixed footer overlapping bottom row with larger font size in Settings > About

### LINKED ISSUE #1122: Settings > About: app version footer is overlapping the bottom row with larger font sizes
**Describe the bug**
When the device is on the larger font sizes, the app version footer text in `Settings > About` could overlap with other rows on certain screen sizes.

**To Reproduce**
- Go to Settings
- Tap "WooCommerce" row under `ABOUT THE APP` section
- Scroll to the bottom
- Try a few font sizes from accessibility larger font settings

**Screenshots**
Simulator Screen Shot - iPhone 5s - 2019-07-24 at 08 13 08

**Expected behavior**
Expected: the app version footer text should be shown with proper margin and not overlap with any other UI
Actual: the app version footer text overlaps with the bottom row as in screenshot

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 5s
- iOS version: iOS 12
- WooCommerce iOS version: 2.3

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #1122 

## Description
When the device is on the larger font sizes, the app version footer text in Settings > About could overlap with other rows on certain screen sizes.

## Testing
1) Go in Device Settings > Accessibility > Display & Text Size > Larger Text
2) Turn Larger Accessibility Sizes to ON, and move the cursor to the largest text
3) Open the app, go to Settings
4) Tap under the section "About the app" the first cell "WooCommerce"
5) Check that the footer now is not overlapping the last cell

## Screenshots
| Before             |  After |
:-------------------------:|:-------------------------:
Simulator Screen Shot - iPhone 11 Pro - 2019-12-12 at 13 23 06 | Simulator Screen Shot - iPhone 11 Pro - 2019-12-12 at 16 09 16

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift [hunk 1]
```diff
@@ -74,6 +79,13 @@ private extension AboutViewController {
         tableView.estimatedRowHeight = Constants.rowHeight
         tableView.rowHeight = UITableView.automaticDimension
         tableView.backgroundColor = .listBackground
+
+        guard let tabBarHeight = tabBarController?.tabBar.frame.height else {
+            return
+        }
+        let adjustForTabbarInsets: UIEdgeInsets = UIEdgeInsets(top: 0, left: 0, bottom: tabBarHeight, right: 0)
+        self.tableView.contentInset = adjustForTabbarInsets
+        self.tableView.scrollIndicatorInsets = adjustForTabbarInsets
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift]: nit: `self` might not be needed? 😄

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift [hunk 2]
```diff
@@ -74,6 +79,13 @@ private extension AboutViewController {
         tableView.estimatedRowHeight = Constants.rowHeight
         tableView.rowHeight = UITableView.automaticDimension
         tableView.backgroundColor = .listBackground
+
+        guard let tabBarHeight = tabBarController?.tabBar.frame.height else {
+            return
+        }
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift]: non-blocking question: just wondering, could the tab bar height change over the view controller life cycle?

Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/About/AboutViewController.swift]: You are right. Yes, it can change, for example during the device rotation. I updated the code to manage it 🙇
