### PR TITLE
IPP: pass formatted amount with currency symbol from `OrderDetailsViewModel` to `PaymentMethodsViewModel`

### LINKED ISSUE #7263: In-person Payments: Missing currency on the collect payment alert
**Describe the bug**
The amount on the Collect Payment alert is missing currency.

**To Reproduce**
1. Make sure your store is eligible for in-person payment
2. Select an order that is pending for payment.
3. Select Collect Payment > select Card payment method > complete the onboarding steps if needed.
4. When the Collect Payment alert is displayed, notice that the amount is formatted without currency.

**Screenshots**

**Expected behavior**
The currency should be present on the alert.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #7263 

### Description

From @itsmeichigo's screenshots work https://github.com/woocommerce/woocommerce-ios/pull/7217, we noticed that the order amount in the collect payment alert doesn't contain a currency symbol. It's because the `formattedTotal` just uses `order.total` without formatting with a currency formatter. This PR updated the `PaymentMethodsViewModel` initialization in `OrderDetailsViewModel` to pass a formatted amount from `order.total` and `order.currency`.

### Testing instructions

- Make sure your store is eligible for in-person payment
- Select an order that is pending for payment
- Select Collect Payment --> the payment method selector screen title should contain the formatted order amount
- Select the Card payment method and complete the onboarding steps if needed --> when the Collect Payment alert is displayed, the amount should be formatted with the order currency

### Screenshots

\ | before | after
-- | -- | --
the title now includes the currency | Simulator Screen Shot - iPhone 13 Pro - 2022-07-08 at 13 52 34 | Simulator Screen Shot - iPhone 13 Pro - 2022-07-08 at 13 51 29
collect payment alert | Simulator Screen Shot - iPhone 13 Pro - 2022-07-08 at 13 52 42 | Simulator Screen Shot - iPhone 13 Pro - 2022-07-08 at 13 52 06

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
I think we'd want this PR included in release 9.6 for screenshots generation and also for IPP UX. Please feel free to merge this on my behalf if it's approved before the code freeze on Monday. If this is reviewed after the code freeze, I can ping Platform9 to include this for the beta release.

File: WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift [hunk 1]
```diff
@@ -104,4 +105,16 @@ final class OrderDetailsViewModelTests: XCTestCase {
...
+        // Given
+        let order = Order.fake().copy(currency: "EUR", total: "10.0")
+
+        // When
+        let currencyFormatter = CurrencyFormatter(currencySettings: .init())
+        let title = OrderDetailsViewModel(order: order, currencyFormatter: currencyFormatter).paymentMethodsViewModel.title
+
+        // Then
+        XCTAssertTrue(title.contains("\u{20AC}10.0"))
+    }
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift:119]: Nit: Should we change this test to USD or CAD and assert `\u{0024}10.0` instead? This test should fail (but passes!) as the `currencyFormatter` should return the Euro sign at the end of the value rather than at the beginning: `10.0€`, but it doesn't.

I'll open a new issue to investigate this, as I could reproduce it all through the app with a Store set up to Euros.

**Review by iamgabrielma — APPROVED** [review]
LGTM! 

I left a nit regarding the Unit Tests currency as these should fail if we actually use Euros.  

Related to the currency formatter, while testing this I realized that we use the same `$` symbol without specifying the currency code during the payment flow for both USD and CAD, which could be confusing. This is unrelated to the PR so I'll open a new issue to track it 👍

File: WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift:119]: Hey @iamgabrielma thanks for reviewing the PR promptly! I think having the currency to the left of the value is expected in this test case, because it uses the default `CurrencySettings` in L114 here which has `CurrencyPosition.left`:

https://github.com/woocommerce/woocommerce-ios/blob/755e0af21807d0fc0d0069fcf232b0ac7066ecbb/WooFoundation/WooFoundation/Currency/CurrencySettings.swift#L22 

this position is a WC setting that a merchant can configure in core 🙂
