### PR TITLE
[Woo POS] Fix try again buttons when payment cancellation fails

### LINKED ISSUE #14996: [Woo POS] `Try again` buttons don't work for payments when the payment can't be cancelled
## Description

We recently updated the handling of `cancelThenCollectPayment` to wait for cancellation to complete before starting a new payment. This was to support cash payments, but the same function is used for the `Try another payment method` button on non-retryable errors.

In some cases, the payment cancellation step can fail, and when that happens, it doesn't go on to collect payment.

This results in the error remaining on screen and the user being stuck.

## Repro
There are probably other ways to do this, but here's one

1. Launch the app and go to POS
2. Connect your card reader
3. Check out
4. Open control centre
5. As you tap your card, turn off bluetooth
6. Observe that an error's shown saying there's no card reader connected. If this doesn't happen, you weren't quick enough.
7. Tap the button – observe that it doesn't do anything.

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #14996
Merge after: #14995

## Description

This PR fixes the `Try again` button on some payment errors, so that it does retry even if the cancellation attempt fails.

In the cash collection project, we made `cancelPayment` async, so we could cancel first, then collect the cash payment, so that the cash payment view wouldn't be presented until after the cancellation completed – this avoided having card payment messages interrupt cash payment.

However, in `cancelThenCollectPayment` we didn't account for times when the cancellation fails. In that case, it's more appropriate to continue to try to collect the payment. This case was handled in `startCashPayment`, but not the function used to try a new payment method.

## Steps to reproduce

There are probably other ways to do this, but here's one

1. Launch the app and go to POS
2. Connect your card reader
3. Check out
4. Open control centre
5. As you tap your card, turn off bluetooth
6. Observe that an error's shown saying there's no card reader connected. If this doesn't happen, you weren't quick enough.
7. Tap the button – observe that it restarts the payment (and prompts you to turn bluetooth back on.)

Note that connecting the reader right after disconnecting it with bluetooth isn't the best; I find it works better if you turn the reader off before attempting the connection again.

When it takes you back to the Checkout screen, the `Enable bluetooth` error shows for a few seconds, before it gets dismissed by the preflight handler failing (due to bluetooth being disabled.) This flow isn't perfect, but it's totally recoverable and easy enough to understand. To fix it would mean a significant delve into the existing code, and I don't think it's worth doing for this edge case.

## Testing information

This code doesn't actually change anything to do with Cash payments, despite its proximity, but it's worth checking that they work correctly even when a card reader is connected.

I've tested using an iPad Air on 17.7.

## Screenshots

https://github.com/user-attachments/assets/e81a1f22-6a5e-4bdc-a02e-ebc9f6390e6a

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Models/PointOfSaleAggregateModel.swift [hunk 1]
```diff
@@ -245,11 +245,15 @@ extension PointOfSaleAggregateModel {
...
         Task { [weak self] in
             guard let self else { return }
-            try await cardPresentPaymentService.cancelPayment()
-            await collectCardPayment()
+            await cancelThenCollectPayment()
         }
     }
 
+    func cancelThenCollectPayment() async {
+        try? await cardPresentPaymentService.cancelPayment()
```
Comment (staskus) [inline WooCommerce/Classes/POS/Models/PointOfSaleAggregateModel.swift:253]: Such a subtle change. I haven't internalized the dangers of [Task swallowing the error](https://forums.swift.org/t/task-initializer-with-throwing-closure-swallows-error/56066). We should be careful with this.

**Review by staskus — APPROVED** [review]
Thanks for the fix. I was able to reproduce by following the steps 👍

File: WooCommerce/Classes/POS/Models/PointOfSaleAggregateModel.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Models/PointOfSaleAggregateModel.swift:253]: Yep, it surprised me that you don't need to declare it as a throwing task or anything like that.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/236">21.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
