### PR TITLE
Blaze: Fallback to default URL when product permalink cannot be decoded

### LINKED ISSUE #13355: [Blaze] Select destination URL when product URL is empty
Originally raised during a PR review https://github.com/woocommerce/woocommerce-ios/pull/13351#pullrequestreview-2181859166

Sometimes a product can have a empty `permanlink` due to some unexpected reasons, as mentioned [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/Product/Product.swift#L349-L359).

Allow the user to select or type a custom product URL. 

Explore any of the following options

- Display a screen with a text field where the user can paste a URL.
- Display a web view pointing to the site home. The user can navigate to the page they want and tap Done to select the URL of that page.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13355 

## Description

This PR updates the logic of Blaze's ad destination to support sites with custom permalink settings and applies a fallback URL when product permalinks cannot be decoded.

Changes include:
- `BlazeCampaignCreationFormViewModel`:
  - Keep `adDestinationViewModel` a lazy variable to avoid unnecessary recreating the view model when the creation form is re-rendered.
  - Fallback to a default form for the product URL when product permalink cannot be decoded following Hicham's suggestion (p1722281016526459/1722280392.435889-slack-C03L1NF1EA3).
- `BlazeAdDestinationSettingsViewModel`:
  - Update the logic to not include the default params in the base URL in the param list.
  - Update the count of remaining characters for params when there are params in the base URL.

## Steps to reproduce

- In a test store eligible for Blaze, go to wp-admin > Settings > Permalink > switch to Plain option.
- Log in to your test store on the app.
- Select an existing published product and tap Promote with Blaze.
- Select Ad destination and confirm that:
  - The product URL includes a default param for the product page. 
  - The default param should not be included in the param list (not editable)
  - The remaining character count for URL param should be correct for both the product URL and home URL.
  - Enter a custom param and save the change.
  - Select Ad destination again and confirm that only the custom param is listed in the param list.
- Change [this line](https://github.com/woocommerce/woocommerce-ios/blob/599d1d95e712aaccaa65babdc81b594b2ce40ffd/Networking/Networking/Model/Product/Product.swift#L358) in the Product.swift file to return an empty string instead of decoding the value.
- Rebuild and run the app. 
- Select an existing published product and tap Promote with Blaze.
- Select Ad destination and confirm that the product URL is available in the default form `{site_url}?post_type=product&p={product_id}`. All the logic regarding param list and remaining character count should still be correct.

## Screenshots

Product URL | Home URL
--- | ---
 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Blaze/AdDestination/BlazeAdDestinationSettingViewModel.swift [hunk 1]
```diff
@@ -68,7 +68,7 @@ final class BlazeAdDestinationSettingViewModel: ObservableObject {
                     // Once a parameter is updated, clear the selected parameter to prepare for the next add/update action.
                     clearSelectedParameter()
                 } else {
-                    self.parameters.append(BlazeAdURLParameter(key: key, value: value))
+                    self.addNewParameter(item: BlazeAdURLParameter(key: key, value: value))
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Blaze/AdDestination/BlazeAdDestinationSettingViewModel.swift]: Super nit: `self` can be removed.

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift [hunk 2]
```diff
@@ -142,10 +142,17 @@ final class BlazeCampaignCreationFormViewModel: ObservableObject {
...
-    }
+    }()
 
     // For Ad destination purposes
-    private var productURL: String? { product?.permalink }
+    private var productURL: String? {
+        let productLink = product?.permalink
+        if let productLink, let siteURL, productLink.isEmpty {
+            /// fallback to the default product URL {site_url}?post_type=product&p={product_id}
+            return String(format: "%@?post_type=product&p=%d", siteURL, productID)
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: TIL about this. Nice. 

Suggestion: Can we make this URL creation logic inside a function as an extension to `Product`? We can keep this extension in this view model file for now. We could also add unit tests.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for working on this, Huong!

The code looks good to me, and the ad destination URL screen works as described. 🚢

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/216">19.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Blaze/AdDestination/BlazeAdDestinationSettingViewModel.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Blaze/AdDestination/BlazeAdDestinationSettingViewModel.swift]: Done in 80b49327907ce25b5c44609254f9cdb6e7f61be6.

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift (hunk 2 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: Good point! I moved this logic to a public extension of `Product` in b58cf613407052c17a37e0f6eb4667a779ae4e15 to reuse the logic when necessary. Also added a new test in 2c7585e68814d9096b1f469d0928ff35eaef2fb6 and removed a legacy one in de4dbc2ede784b49da7e12f2c22f5c4ae2be29f3.
