### PR TITLE
[Product Multi-selection] Sync selected items when view is dismissed or closed

### LINKED ISSUE #9319: [Product Multi-selection] Order not updated when item selector closes, or is dismissed
From QE testing pdcxQM-1Wb#comment-1813-p2

- Add some products > tap done
- On New Order screen > tap Add Products again
- Remove some products > tap Close (or pull to dismiss but not the Done button)
- See that the Products on Order screen are not updated (expected)
- Tap Add Products again > see that the selected products no longer match what’s displayed on New Order

Possibly related, as this is logged when `CurrencyFormatter.convertToDecimal()`

>  tapping on the Done button when the two screens no longer match, I see this error printed on Xcode

```
2023-03-29 12:31:56.049628+0800 WooCommerce[363:27354] Error: string input is not a number:
2023-03-29 12:31:56.049680+0800 WooCommerce[363:27354] Error: string input is not a number:
```

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #9319 

## Description
During QE testing we discovered that if a merchant dismisses or closes the product selector without saving changes, there will be discrepancies between which items are part of an order and which ones appear selected the next time they open the Product Selector.  With this PR we're sure to keep these in sync.

## Changes
- Disallows dismiss on swipe for the Product Selector and Product Variation Selector by using `.interactiveDismissDisabled()`. I considered potential improvements like intercepting the SwiftUI swipe action, or making these views non-modal by using [fullScreenCover](https://developer.apple.com/documentation/swiftui/view/fullscreencover(ispresented:ondismiss:content:)) instead, but adds extra complexity and we can revisit this again once we get a design review, they can still close the views by tapping either on `<` or `Close`.
- When the `Close` button is tapped, we 1. Clear all selections, and 2. Sync the current Order state. This way we're sure to only display exactly what's part of the Order the next time the selector is opened.

## Testing instructions
- Go to Menu > Settings > Experimental features > and enable "Product Multi-Selection"
- Go to Orders > Tap `+` > Tap on `+ Add Products`.
- Attempt to swipe down to dismiss the Product Selector view, see how it can't be dismissed. The same will happen for Product Variations Selector.
- Select some items and tap `X product selected` to create an Order.
- Tap on `+ Add Products` again, select some more items, but this time tap `Close` to not save any update. See how the Order still contains the initial items, and by tapping on `+ Add Products` again the correct items are selected as well.

Simulator Screen Recording - iPhone Xs - 2023-03-30 at 08 29 51

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift [hunk 1]
```diff
@@ -125,6 +125,9 @@ struct ProductSelectorView: View {
                 if let cancelButtonTitle = configuration.cancelButtonTitle {
                     Button(cancelButtonTitle) {
                         isPresented.toggle()
+                        if !isPresented {
+                            viewModel.clearSelection()
+                        }
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift:130]: Super nit: 

If the purpose of this button is to set `isPresented` as false. For slightly better readability, can we rewrite this into 
```suggestion
                        isPresented = false
                        viewModel.clearSelection()
```

**Review by selanthiraiyan — APPROVED** [review]
This works as expected. 

I just have a suggestion not to disable the swipe-to-dismiss gesture. 

> I considered potential improvements like intercepting the SwiftUI swipe action, or making these views non-modal by using [fullScreenCover](https://developer.apple.com/documentation/swiftui/view/fullscreencover(ispresented:ondismiss:content:)) instead, but adds extra complexity

Instead of disabling the dismiss gesture, you can use `UIAdaptivePresentationControllerDelegate` to know when the user cancels the flow by swiping down. You can probably use that to sync back to the original state. 

If you are not familiar with this, you can take a look at `UIAdaptivePresentationControllerDelegate`'s usage in our codebase. [Example usage](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Orders/Payment%20Methods/PaymentMethodsHostingController.swift#L76-L78)

**Comment by iamgabrielma** [comment]
Thanks for the review! 

> Instead of disabling the dismiss gesture, you can use UIAdaptivePresentationControllerDelegate to know when the user cancels the flow by swiping down

I see what you mean, by wrapping the current View in an `UIHostingController` we can intercept the dismiss via the conformance to the delegate 👍 Logged it here: https://github.com/woocommerce/woocommerce-ios/issues/9334

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorView.swift:130]: In this case we're not setting `isPresented` but just checking if it is false after being toggled. I guess I can use a ternary operator here as well for readability 👍
