### PR TITLE
Crash: Orders table row count in section zero is invalid during a refresh

### LINKED ISSUE #1543: Invalid Number Of Rows/Sections Crash
**Describe the bug**
Text from one of the crashes:

```Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (8) must be equal to the number of rows contained in that section before the update (7), plus or minus the number of rows inserted or deleted from that section (1 inserted, 7 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).```

Crash report: https://sentry.io/share/issue/63aa8ffcc1634d5da1c7c2c0f8155ac8/

**To Reproduce**
Unsure of how to reproduce.

**Expected behavior**
No crashes when orders list is updated.

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #1543.

There are no steps to reproduce. I tried to follow the steps in [WPiOS fix](https://github.com/wordpress-mobile/WordPress-iOS/pull/12974) but it never successfully caused a crash for me. 

**Steps I tried:**
1. Delete the app from the sim
2. Build and run the app
3. Upon login, quickly switch to the Orders tab and pull-to-refresh while the ghostable table view is visible. 

Also tried Steps 1&2, followed by 3. Quickly tapping the filters button while the ghostable table view was visible.

From the crashes reported in Sentry, the fetchedResultsController appears to send inconsistent data to the Orders table view. Many of our Sentry reports for this issue mirror the problems WPiOS had experienced with ghostable tables. (See also: https://github.com/wordpress-mobile/WordPress-iOS/pull/12974)

My main concern is that changing from the main table to adding a ghostable table blindly (as in, no exact steps to reproduce on our app) could cause new bugs.

### Changes
- make ghostable its own table instead of 1 table doing 2 things
- don't allow ghostable table to pull-to-refresh

### To test
- try to break the Order list view controller

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
oops I commented on the closed PR https://github.com/woocommerce/woocommerce-ios/pull/1603

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift [hunk 1]
```diff
@@ -513,25 +538,30 @@ extension OrdersViewController {
...
-        tableView.displayGhostContent(options: options,
-                                      style: .wooDefaultGhostStyle)
 
-        resultsController.stopForwardingEvents()
+        // If the ghostable table view gets stuck for any reason,
+        // let's reset the state before using it again
+        ghostableTableView.removeGhostContent()
+        ghostableTableView.displayGhostContent(options: options,
+                                               style: .wooDefaultGhostStyle)
+        ghostableTableView.startGhostAnimation()
```
Comment (mindgraffiti) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: the ghost animation will start if you add ghost content, but I'm starting it here just to make it explicit

File: WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift [hunk 2]
```diff
@@ -513,25 +538,30 @@ extension OrdersViewController {
...
+        ghostableTableView.isHidden = false
     }
 
     /// Removes the Placeholder Orders (and restores the ResultsController <> UITableView link).
     ///
     func removePlaceholderOrders() {
-        tableView.removeGhostContent()
-        resultsController.startForwardingEvents(to: self.tableView)
+        ghostableTableView.isHidden = true
+        ghostableTableView.stopGhostAnimation()
```
Comment (mindgraffiti) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersViewController.swift]: the ghostable table doesn't stop the animation inside of `removeGhostContent`, so we call it here

**Comment by mindgraffiti** [comment]
@pmusolino good point, I should have mentioned turning on the Network Link Conditioner in the testing instructions.
