### PR TITLE
[Mobile Payments] Allow retries of failed interac refunds

### LINKED ISSUE #6643: [Mobile Payments] Handle retry from failed Interac refund
`StripeCardReaderService.cancelRefund` never returns when retrying refund after failure - implement timeout. Tap "Try Again" on the error alert does nothing

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #6643 

### Description

When an interac refund fails, we show an error with a “Try again” button.

When the user taps that, we attempt to cancel the Interac refund “intent” using the `refundCancelable` that Stripe Terminal gives us in response to `SCPTerminal.collectRefundPaymentMethod()`

When there’s been a failure or error in the refund, the `refundCancelable` that Stripe gave us ends up in an unexpected situation: it’s not `completed`, but it also doesn’t call back the completion handler when we call `cancel`. This meant that our previous “Try again” handler did not start the new refund attempt.

Cancelling a refund after Stripe have called the completion handler from `processRefund`, or given us an error from `collectRefundPaymentMethod`, shouldn’t be required: those calls from Stripe have already told us that the original refund attempt is complete (even if failed), so we can’t cancel it anyway.

This change sets the `refundCancelable` to nil when Stripe have told us that the refund is complete, resulting in a `noRefundInProgress` error being returned to the `handleRefundFailureAndRetryRefund` handler. We don’t need to worry about this error or whether the cancellation was successful: in either case, we should try the refund again.

This change does not address that some refund errors should not be retriable: that will follow in future work.

N.B. the creation of `alerts` in `RefundSubmissionUseCase` is moved to `init`, because doing it in the refund retry attempt (for a second time) results in an error when we try to present the view controller container modally again without dismissing the one with the error in it. Moving the creation avoids the need to dismiss, and that keeps the visual flow consistent.

### Testing instructions

1. Make an order for a product, with shipping cost ending in .01, and a fee ending in .99 so that we can take payment
2. Take IPP payment with an interac card
3. Refund the shipping only
4. Observe that the refund fails
5. Tap "Try again" on the error alert
6. Observe that the refund is retried

### Screenshots

https://user-images.githubusercontent.com/2472348/163441454-f35c40fe-a04c-42c9-88ce-98e2c0eefde3.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift [hunk 1]
```diff
@@ -275,20 +275,12 @@ private extension RefundSubmissionUseCase {
         // TODO: 5984 - tracks in-person refund error
         DDLogError("Failed to refund: \(error.localizedDescription)")
         // Informs about the error.
+        //TODO: Check which refund errors can't be retried, and use that to call nonRetryableError(from: self.rootViewController, error: cancelError)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift:293]: Great point on this TODO, do we have a way to tell if an error is non-retryable? In IPP, it just considers a failure case as non-retryable if the payment cancellation fails 🤔

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift [hunk 2]
```diff
@@ -107,6 +107,11 @@ final class RefundSubmissionUseCase: NSObject, RefundSubmissionProtocol {
         self.stores = stores
         self.storageManager = storageManager
         self.analytics = analytics
+
+        // Instantiates the alerts coordinator.
+        let alerts = OrderDetailsPaymentAlerts(transactionType: .refund,
+                                               presentingController: rootViewController)
+        self.alerts = alerts
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift]: there might be a merge conflict from https://github.com/woocommerce/woocommerce-ios/pull/6639 which DIs the `alerts` so this isn't needed anymore 🙂

**Review by jaclync — APPROVED** [review]
Thanks for fixing this retry case with a detailed PR description! The changes LGTM :shipit: 

There's a side issue I noticed now that retry is working, where Apple pass is allowed briefly right after tapping "Try Again":

https://user-images.githubusercontent.com/1945542/163513728-4ac1ab82-a1d0-4d9e-b662-736286d268ef.MP4

This is because `CardPresentRefundOrchestrator.cancelRefund` calls `allowPassPresentation` when we cancel the refund as the first step of retry. Even though we call `CardPresentRefundOrchestrator.refund` right after to suppress the pass presentation, it might be a bug or unexpected behavior in `PassKit` that `PKPassLibrary.isSuppressingAutomaticPassPresentation()` still returns `true` after `allowPassPresentation` is called before so that the suppression is not called again. To fix this, I think we can:
- Always request pass presentation suppression by removing the check on the current suppression state below:
https://github.com/woocommerce/woocommerce-ios/blob/fb5b514e75f7abe7cce9a32c4080839d6cf11a14/WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentRefundOrchestrator.swift#L81-L83
- Only call `allowPassPresentation` in `CardPresentRefundOrchestrator.deinit` - this is currently not working because of some retain cycles, but we can test this after https://github.com/woocommerce/woocommerce-ios/pull/6639 is merged

What do you think? I personally prefer the latter so that we don't have to manually call `allowPassPresentation` for all code paths. I added a subtask to https://github.com/woocommerce/woocommerce-ios/issues/5983 for this!

**Comment by jaclync** [comment]
Hi @joshheald! I fixed the merge conflicts in https://github.com/woocommerce/woocommerce-ios/pull/6654/commits/369a3806c26cf96171124841da367fc765e3db0e on your behalf since the PR is ready to merge. also tested the retry again and feel free to merge anytime!

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift:293]: Android have this implemented already, I just didn't dig in to it enough yesterday to pull out their list. I was just going to steal that though! It's in the app, [Stripe have a bit of guidance](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)processRefund)...

> When processRefund fails, the SDK returns an error that either includes the failed [SCPRefund](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPRefund.html) or the [SCPRefundParameters](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPRefundParameters.html) that led to a failure. Your app should inspect the [SCPProcessRefundError](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPProcessRefundError.html) to decide how to proceed.
> 
> If the refund property is nil, the request to Stripe’s servers timed out and the refund’s status is unknown. We recommend that you retry processRefund with the original [SCPRefundParameters](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPRefundParameters.html).
> 
> If the [SCPProcessRefundError](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPProcessRefundError.html) has a failure_reason, the refund was declined. We recommend that you take action based on the decline code you received.

... but it's not exactly definite about which ones are retryable!

**Comment by joshheald** [comment]
> There's a side issue I noticed now that retry is working, where Apple pass is allowed briefly right after tapping "Try Again":

Great catch!

> What do you think? I personally prefer the latter so that we don't have to manually call `allowPassPresentation` for all code paths. I added a subtask to #5983 for this!

Nice one. I'll pop some comments there... #6656
