### PR TITLE
IPP Analytics: track event when an Interac refund is canceled

### LINKED ISSUE #6655: [Mobile Payments] New Interac analytic events for Canada IPP launch
These events are the highest priority to be done pre-launch, so I've broken them out of this ticket to make prioritisation clearer...

## New events

Event | Properties | Trigger | PR
-- | -- | -- | --
*_card_interac_collect_payment_success | `plugin_slug`, `card_reader_model`, `country` | Tracked right after processing succeeds. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_success | `plugin_slug`, `card_reader_model`, `country` | Tracked when an Interac in-person refund succeeds on the client side. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_failed | `error`, `plugin_slug`, `card_reader_model`, `country` | Tracked when an Interac in-person refund fails on the client side. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_cancelled | `plugin_slug`, `card_reader_model`, `country` | Tracked when the user cancels an Interac in-person refund before it's complete.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/issues/5984#issuecomment-1099969660_

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #6655

### Description

Implementing the event was quick, but I spent quite some time on the unit tests debugging why the refund completion block isn't invoked and fixed/refactored some implementation details. There are also various triggers to cancel an in-person refund, multiple during the card reader connection process (which is mostly covered in unit tests `CardReaderConnectionControllerTests` and `RefundSubmissionUseCaseTests`) and client-side payment capture ("reader is ready" and "tap or insert card" alerts). I felt pretty confident about the changes in this PR with the unit testing coverage, since it could be time-consuming to manually test all the cancellation paths.

#### Major changes:

- Added a new event `interac_refund_cancelled`
- Cancellation paths before a successful card reader connection:
  - In `CardReaderConnectionController`: updated the `onCompletion` success result from a `Bool` (whether a reader is connected or not) to an enum `ConnectionResult` with two cases `connected` or `canceled` to be more clear
  - While debugging a test case, `CardReaderConnectionController` requires a non-nil payment gateway account from storage but it didn't recognize a valid one that was stored earlier in the test. Then I saw that `CardReaderConnectionController` only updated its state after a payment gateway account is "updated" - **after** one is inserted to or updated in storage. Thus, I set `gatewayID = dataSource.cardPresentPaymentGatewayID()` right after configuring the storage results controller for payment gateway accounts
  - `CollectOrderPaymentUseCase`: handled the new card reader connection success result for the `canceled` case. For the `connected` case, it's handled in the `receiveCompletion` block which I found a bit confusing. I think the code might look more clear if we just handle the `connected` case in the `receiveValue` block along with other cases but I didn't want to change it in this PR at least
  - `RefundSubmissionUseCase`: handled the new card reader connection success result for the `canceled` case, and tracked the new event `interac_refund_cancelled` here. A few dependencies were injected for `CardReaderConnectionController` so that we can mock them in unit tests
- Cancellation paths after a successful card reader connection:
  - There are two triggers: from the "Cancel" CTA in `alerts.readerIsReady` and `alerts.tapOrInsertCard`. From debugging unit tests, a call to completion was missed in these two cancellation paths and thus I added a call to `onCompletion(.failure(RefundSubmissionError.canceledByUser))` after internal cancellation step finishes
- Updated `RefundSubmissionUseCaseTests` and `CardReaderConnectionControllerTests` to add test cases for 3 cancellation paths with some refactoring

### Testing instructions

Prerequisites: the store is in Canada and eligible for IPP (setup instructions PdfdoF-D-p2)

- Go to the orders tab
- Create an order and pay it with Interac using a physical card reader, if you don't have one already
- We will use this order to test 3 cancellation paths below

#### Cancel while searching for card readers

(Please note that there are other alerts during this connection flow that could lead to cancellation, but it's hard to test all of them. We do have test coverage on other paths in `CardReaderConnectionControllerTests` to make sure they trigger `canceled` success result like in this scenario)

- Disconnect the reader if it's currently connected to one (you can disconnect a reader in Settings > In-Person Payments > Manage card reader, or relaunch the app)
- Go to the order created in the prerequisites
- Tap "Issue Refund" and select the refund amount to confirm --> the card reader connection alerts should appear
- Tap "Cancel" quickly while it's still searching for card readers --> in the console, you should see `🔵 Tracked interac_refund_cancelled, properties: [AnyHashable("card_reader_model"): "", AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("country"): "CA", ...]`

#### Cancel when the card reader is ready

(Please note that both "reader is ready" and "tap or insert card" alerts look exactly the same and it's hard to time it. We do have test coverage on both paths in `RefundSubmissionUseCaseTests`) 

- Go to the order created in the prerequisites if needed
- Tap "Issue Refund" and select the refund amount to confirm --> the card reader connection alerts should appear
- Connect to a WisePad 3 reader --> an alert that shows "Reader is ready" should be shown
- Tap "Cancel" on this "Reader is ready" alert --> in the console, you should see `🔵 Tracked interac_refund_cancelled, properties: [AnyHashable("plugin_slug"): "woocommerce-payments", AnyHashable("card_reader_model"): "WISEPAD_3", AnyHashable("country"): "CA", ...]`

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift [hunk 1]
```diff
@@ -181,10 +181,14 @@ private extension CollectOrderPaymentUseCase {
...
                         guard let self = self else { return }
                         switch result {
-                        case let .success(isConnected):
-                            if isConnected == false {
+                        case let .success(connectionResult):
+                            switch connectionResult {
+                            case .canceled:
                                 self.readerSubscription = nil
                                 onCompletion(.failure(CollectOrderPaymentUseCaseError.cardReaderDisconnected))
+                            default:
```
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift]: Super non blocker here 😆 
By adding a default statement we assume that the rest of the cases other than canceled will always be `connected`. While this is true now, it might not be the case in the future (we could add a `.disconnected` case for instance). If that happens, this `switch` would not trigger a compilation error, which might lead to unexpected behaviors (treat the new case in the same way as `.connected`) Because of that it might be safer if we do not assume that here, being exhaustive as
```
case .connected:
break
```

But again, this might be a matter of personal opinion and it is of course a non blocker :)

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift [hunk 2]
```diff
@@ -212,10 +229,15 @@ private extension RefundSubmissionUseCase {
...
-                        case let .success(isConnected):
-                            if isConnected == false {
+                        case let .success(connectionResult):
+                            switch connectionResult {
+                            case .canceled:
                                 self.readerSubscription = nil
+                                self.trackClientSideRefundCanceled(charge: charge, paymentGatewayAccount: paymentGatewayAccount)
                                 onCompletion(.failure(RefundSubmissionError.cardReaderDisconnected))
+                            default:
+                                // Connected case will be handled in `receiveCompletion`.
```
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift:239]: Same here about the default case in switch as before :)

File: WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift [hunk 3]
```diff
@@ -69,18 +69,24 @@ final class CardReaderConnectionController {
...
     private var state: ControllerState {
         didSet {
             didSetState()
         }
     }
     private weak var fromController: UIViewController?
-    private var siteID: Int64
-    private var knownCardReaderProvider: CardReaderSettingsKnownReaderProvider
-    private var alerts: CardReaderSettingsAlertsProvider
+    private let siteID: Int64
```
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift:87]: Nice one making these `lets` 👏

**Comment by toupper** [comment]
Great job @jaclync ! LGTM:

Cancel while searching for card readers: Tracked ✅ 
Cancel when the card reader is ready: Tracked ✅ 

Just added a couple of non blocker comments :)

**Review by toupper — APPROVED** [review]

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift]: Great point! Updated in https://github.com/woocommerce/woocommerce-ios/pull/6747/commits/0183dd100408944ed9d7ca13e6f42d8027d3342b

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift:239]: Also updated in https://github.com/woocommerce/woocommerce-ios/pull/6747/commits/0183dd100408944ed9d7ca13e6f42d8027d3342b 🙂
