### PR TITLE
[Blaze] Retrieve Media or Upload asset before submitting campaign

### LINKED ISSUE #11984: Blaze: Upload campaign image
We need to upload the Blaze campaign image before submitting a create campaign request. 

- We can upload the image right before submitting the campaign.
- Regarding errors, I think we can use the same error screen pattern that we use for showing Blaze campaign creation errors. We can change the error message.
- We can retry one time before showing an error if the image upload fails, as the media uploads could fail often.

Tasks
- [x] Media Action to retrieve Media using product image's ID #12001
- [ ] Upload images and handle error #12006

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #11984

## Description

This PR prepares the Blaze campaign image before sending a create campaign request.

Blaze campaign's image can come from the following sources,
1. The promoted product's image
3. From camera/device
4. From the WP Media library

This PR handles the above image types in the following ways,
1. The promoted product's image doesn't need to be uploaded. But, a `ProductImage` doesn't have a `mimeType` value. 
    - So, we send a separate API request to retrieve the corresponding `Media` from the WP Media library. The retrieved Media contains the `mimeType`. 
    - Internal - p1707828165902379-slack-C03L1NF1EA3
2. The image selected from the camera/device is uploaded before submitting the Blaze campaign. 
    - The upload request is tried once again upon failure as the image upload could fail due to network issues. 
    - Internal - p1707821290862699/1704188207.780169-slack-C03L1NF1EA3
3. The image selected from WP Media can be used directly. 

We have also started showing custom error messages for image-related failures. Internal - p1707896051842299-slack-C03L1NF1EA3

## Testing instructions

**Prerequisites**
- Create JN site with Woo and Jetpack
- Publish a product with an image
- Login into the app using the JN site

#### Using product image for campaign
- Open product details page and tap "Promote with Blaze" -> "Create Your Campaign"
- From the Blaze preview screen tap "Confirm Details"
- You will land on the "Payment" screen
- Tap "Submit Campaign"
- The campaign should be submitted successfully.

#### Using image from camera/device for campaign
- Open product details page and tap "Promote with Blaze" -> "Create Your Campaign"
- Tap "Edit ad" -> "Change image"
- Take a photo or choose an image from the device library
- From the Blaze preview screen tap "Confirm Details"
- You will land on the "Payment" screen
- Tap "Submit Campaign"
- The campaign should be submitted successfully
- Check that the selected image is added to your site's WP Media library from the `wp-admin` page

#### Using an image from the WP Media library
- Open product details page and tap "Promote with Blaze" -> "Create Your Campaign"
- Tap "Edit ad" -> "Change image"
- Tap "WordPress Media Library" and choose an image from your site's library
- From the Blaze preview screen tap "Confirm Details"
- You will land on the "Payment" screen
- Tap "Submit Campaign"
- The campaign should be submitted successfully

## Screenshots

| Using product image for campaign | Using image from camera/device for campaign | Using an image from the WP Media library |
|--------|--------|--------|
| Simulator Screen Recording - iPhone 15 Pro Max - 2024-02-15 at 08 38 11 | Simulator Screen Recording - iPhone 15 Pro Max - 2024-02-15 at 08 39 00 | Simulator Screen Recording - iPhone 15 Pro Max - 2024-02-15 at 08 40 02 | 

#### Error messages
| Campaign creation failed  | Unable to load `ProductImage`'s `Media` | Upload image failed |
|--------|--------|--------|
| GenericError | UnableToLoadMedia | UploadImage | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/186">17.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift [hunk 1]
```diff
@@ -112,17 +119,47 @@ final class BlazeConfirmPaymentViewModel: ObservableObject {
...
+                    DDLogError("⛔️ Error fetching product image's Media: \(error)")
+                    throw BlazeCampaignCreationError.failedToFetchCampaignImage
+                }
+            }
+
+            var updatedDetails = campaignInfo
+            // Set image URL and mimeType
+            updatedDetails = updatedDetails.copy(mainImage: .init(url: campaignMedia.src, mimeType: campaignMedia.mimeType))
+            // Set payment method ID
+            updatedDetails = updatedDetails.copy(paymentMethodID: selectedPaymentMethod.id)
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift]: Suggestion: this can be simplify to one call:

```suggestion
            // Set payment method ID, image URL and mimeType
            let updatedDetails = campaignInfo
                .copy(paymentMethodID: selectedPaymentMethod.id,
                      mainImage: .init(url: campaignMedia.src, mimeType: campaignMedia.mimeType))
```

File: WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift [hunk 2]
```diff
@@ -112,17 +119,47 @@ final class BlazeConfirmPaymentViewModel: ObservableObject {
...
+            case .media(let media):
+                campaignMedia = media
+            case .productImage(let image):
+                do {
+                    campaignMedia = try await retrieveMedia(mediaID: image.imageID)
+                } catch {
+                    DDLogError("⛔️ Error fetching product image's Media: \(error)")
+                    throw BlazeCampaignCreationError.failedToFetchCampaignImage
+                }
+            }
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift]: Suggestion: should we move this to a separate method for readability?

```suggestion
            let campaignMedia = prepareImage(from: image.source)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Blaze/BlazeConfirmPaymentViewModelTests.swift [hunk 3]
```diff
@@ -166,11 +214,156 @@ final class BlazeConfirmPaymentViewModelTests: XCTestCase {
...
+        await viewModel.updatePaymentInfo()
+        await viewModel.submitCampaign()
+
+        // Then
+        let campaign = try XCTUnwrap(submittedCampaign)
+        XCTAssertEqual(campaign.mainImage.url, media.src)
+        XCTAssertEqual(campaign.mainImage.mimeType, media.mimeType)
+    }
+
+    func test_upload_image_is_retired_one_time_if_upload_fails() async throws {
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Blaze/BlazeConfirmPaymentViewModelTests.swift]: Nit:

```suggestion
    func test_upload_image_is_retried_one_time_if_upload_fails() async throws {
```

**Review by itsmeichigo — APPROVED** [review]
LGTM :shipit:

File: WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift]: Nice. Done in https://github.com/woocommerce/woocommerce-ios/pull/12006/commits/2c0dfb062100be3cd8f0897f133441b2ee3f68f4

File: WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift (hunk 2 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Blaze/ConfirmPayment/BlazeConfirmPaymentViewModel.swift]: Good suggestion. Done in https://github.com/woocommerce/woocommerce-ios/pull/12006/commits/59d959ce08bc28846d063f7c25c502368cecd6b8

File: WooCommerce/WooCommerceTests/ViewRelated/Blaze/BlazeConfirmPaymentViewModelTests.swift (hunk 3 above)
Comment (selanthiraiyan) [reply WooCommerce/WooCommerceTests/ViewRelated/Blaze/BlazeConfirmPaymentViewModelTests.swift]: 🕵️ Fixed in https://github.com/woocommerce/woocommerce-ios/pull/12006/commits/96bfd7bd52d7a075c199e70cb19efa564bd1bcfa

**Comment by selanthiraiyan** [comment]
Thanks for the review and nice suggestions, Huong! 🙇 

Enabling auto-merge now. Please feel free to add comments, if any.
