### PR TITLE
[Mobile Payments] Decode decline codes correctly

### LINKED ISSUE #13595: [Mobile Payments] Decline reasons are not decoded
## Description

During development on #13578, I found that all `UnderlyingError.paymentDeclinedByPaymentProcessorAPI(declineReason:)` errors are decoded with the default `DeclineReason.unknown`.

This is because [when we check the user info from the error](https://github.com/woocommerce/woocommerce-ios/blob/2d21789c5f74db0ee7d6b224efb42e768961e5a1/Hardware/Hardware/CardReader/StripeCardReader/UnderlyingError%2BStripe.swift#L76), we use an incorrect key to fetch the decline info.

We use `stripeAPIDeclineCode`, but Stripe use `com.stripe-terminal:StripeAPIDeclineCode`.

This should be checked in case there's a better way to get the key in future.

## Impact
This means that in decline situations, merchants will have received less detailed instructions on what to do next and what caused the error. However, for all declines, the approach is to try again and they were invited to do that.

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #13595 

## Description

During development of the POS's error messages, I discovered that we weren't correctly showing decline reasons we got from the Stripe SDK. We always showed the generic decline message, both for POS and other IPP payments in the app.

This is because we were using the wrong key to decode the `DeclineCode` that Stripe give us in the error.

I've fixed it by using the `stripeAPIDeclineCode` definition included in the Terminal SDK

## Steps to reproduce

1. Launch the app
2. Go to the orders tab
3. Create an order with a custom amount using [one of the error amounts defined by Stripe](https://docs.stripe.com/terminal/references/testing#physical-test-cards) (note that it must be more than $0.50, so to do the `.01` code, use `1.01`.)
4. Take payment for the order
5. Observe that different error messages are shown for each of the amounts.

## Testing information

I've tested this in the main app, and POS. Note that POS error display is incomplete, so some buttons won't work – the messages should still display though.

### PIN errors
If possible, test the PIN error messages using a WisePad 3 and a M2, to check that the PIN challenges still work. 

Note that the `.02` and `.03` amounts will cause a PIN challenge, which you'll have to insert your card for. Make sure you select the PIN card variant on the reader, if prompted. Correctly entering the PIN results in a successful transaction. 

The `.55` and `.75` error codes do not recover when you enter the correct PIN code, as they are repeatedly returned by the API in test mode.

### Before

https://github.com/user-attachments/assets/41176427-4be2-4c93-b209-6f74db6cf968

### After
https://github.com/user-attachments/assets/9b63d886-1461-471d-ad15-901441222d56

---
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/218">20.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
@staskus @iamgabrielma Only one review required, and it might need to be you Gabriel as I don't think Povilas has the correct hardware for testing this.

File: Hardware/HardwareTests/UnderlyingError+StripeTests.swift [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import XCTest
+@testable import Hardware
+import StripeTerminal
+
+final class UnderlyingError_StripeTests: XCTestCase {
+
+    func test_stripe_offlineDeclineCode_used_to_determine_decline_reason() {
```
Comment (iamgabrielma) [inline Hardware/HardwareTests/UnderlyingError+StripeTests.swift]: Just curious: Why the _offline_ mention in the test name?

**Comment by iamgabrielma** [comment]
Code looks good! I'll wrap testing EOD since I don't have the WisePad 3 by hand 🙇

**Comment by iamgabrielma** [comment]
> Launch the app
> Go to the orders tab
> Create an order with a custom amount using [one of the error amounts defined by Stripe](https://docs.stripe.com/terminal/references/testing#physical-test-cards) (note that it must be more than $0.50, so to do the .01 code, use 1.01.)
> Take payment for the order
> Observe that different error messages are shown for each of the amounts.

I cannot seem to be able to reproduce this fully, maybe I'm missing a step? So far I've tried with the M2 and by using the physical device + reader + test card, transactions ending in .01, .02, .03 are collected successfully by tapping. Is my understanding that for M2 I should see an error by tapping and I'm forced to insert the card?

In the case of .55 and .75 forced me to introduce the card (tapping didn't work) and then returned the incorrect PIN error as expected.

Do you happen to have a UK or CAD site I can use for the W3 testing?

**Comment by joshheald** [comment]
> I cannot seem to be able to reproduce this fully, maybe I'm missing a step? So far I've tried with the M2 and by using the physical device + reader + test card, transactions ending in .01, .02, .03 are collected successfully by tapping. Is my understanding that for M2 I should see an error by tapping and I'm forced to insert the card?

That's strange. `.01` should be an error with any reader. `.02` and `.03` are always errors with M2, as there's no way to enter a PIN. It doesn't force you to insert the card in this case, but you shouldn't be able to complete the payment.

I'll check this again from my end, in case other changes are at play here.

With W3, IIRC the `.02` and `.03` errors show as errors when you tap, then tell you to insert the card on retry. Inserting the card makes you enter the PIN, and then they succeed. This behaviour may be different in different regions though, these rules tend to vary a bit and they're Stripe's responsibility to get right.

> In the case of .55 and .75 forced me to introduce the card (tapping didn't work) and then returned the incorrect PIN error as expected.
> 
> Do you happen to have a UK or CAD site I can use for the W3 testing?

Sure, I'll invite you to my UK site.

**Review by iamgabrielma — APPROVED** [review]
All works as expected for Wisepad3, but as mentioned in the comment above .01, .02, and .03 didn't seem to trigger the expected errors on M2 on my end, but it worked for the other cases (I used the indiemelon site if you want to give it a go).

**Comment by joshheald** [comment]
> ).

Thanks, I'll try before I merge. They show the errors as expected with M2 on my site.

**Comment by joshheald** [comment]
@iamgabrielma Could you check M2 with the .01/.02/.03 error amounts again, and maybe grab the network and device logs? I've not changed anything about the code and it shows those errors correctly for me using your Indie Melon store.

File: Hardware/HardwareTests/UnderlyingError+StripeTests.swift (hunk 1 above)
Comment (joshheald) [reply Hardware/HardwareTests/UnderlyingError+StripeTests.swift]: Because I didn't fully correct it from a previous reference to `offlineDeclineReason`, which is a different Stripe error key. I've fixed it in e81f64f, thanks for pointing that out!

**Comment by iamgabrielma** [comment]
> @iamgabrielma Could you check M2 with the .01/.02/.03 error amounts again, and maybe grab the network and device logs? I've not changed anything about the code and it shows those errors correctly for me using your Indie Melon store.

Alright, so after debugging and copy-pasting all logs below I've discovered my problem, so i'm removing them. My problem was the `Charge taxes` toggle, which I had enabled by default, so it was changing `1.01` to `1.11`. I assumed this was fine because ends in one cent as well, but nope, has to be exactly .01 ending to trigger the simulated error 🤦 

All good!
