### PR TITLE
[Mobile Payments] Fix Email receipt not being presented 

### LINKED ISSUE #4272: [Mobile Payments] Email receipt doesn't work
This was working a few days ago, but I was testing with the latest changes (603c409d6) and tapping on "Email receipt" after completing a payment doesn't work. I see this in the console:

> 2021-05-25 10:29:01.965678+0200 WooCommerce[48237:3663251] 🔵 Tracked receipt_email_tapped, properties: [AnyHashable("blog_id"): 191646963, AnyHashable("is_wpcom_store"): false]
2021-05-25 10:29:02.086580+0200 WooCommerce[48237:3660434] [Presentation] Attempt to present <MFMailComposeViewController: 0x15a34d200> on <WooCommerce.MainTabBarController: 0x15a0d0c00> (from <WooCommerce.OrderDetailsViewController: 0x15af0e2b0>) while a presentation is in progress

### PR DESCRIPTION
**Pull request by ctarda**
Closes #4272 

⚠️ This PR is against the feature branch implementing support for Card Present Payments, not against develop ⚠️

https://user-images.githubusercontent.com/2722505/119479732-f14dac00-bd1e-11eb-938e-a68fa9582f63.MP4

## Changes
* Call "email receipt action" after the modal has been completely dismissed. I have no idea why this used to work before the way it was.

## How to test
Testing requires:

1. Setting up a store for Card Present Payment Testing (also P91TBi-4BH-p2 for more specific instructions)
2. WCPay 2.4.0
3. The site being enrolled into the beta (p91TBi-5cf-p2)

* Checkout the branch
* Connect to a reader
* Navigate to an eligible order. Tap "Collect Payment" and complete the payment collection process
* When prompted, tap "Email receipt"
Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalSuccess.swift [hunk 1]
```diff
@@ -48,7 +48,9 @@ final class CardPresentModalSuccess: CardPresentPaymentsModalViewModel {
 
     func didTapSecondaryButton(in viewController: UIViewController?) {
         emailReceiptAction()
```
Comment (koke) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalSuccess.swift]: Shouldn't this one be deleted?

**Review by koke — APPROVED** [review]
I think there's an extra call to `emailReceiptAction` that we can remove, but the rest looks good and it seems to work 👍🏽

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalSuccess.swift (hunk 1 above)
Comment (ctarda) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalSuccess.swift]: 🤦🏼

**Comment by ctarda** [comment]
Thanks for the review @koke  There was definitely a duplicate call to generate the email. I've pushed an update to remove it and will merge when ci is ✅
