### PR TITLE
Set background color of StorePickerViewController to match the background color provided by WPAuthenticator

### LINKED ISSUE #3364: [UL&S] Mixed styles on epilogue/error screen when WordPress.com account has no connected WooCommerce stores
**Describe the bug**

There are odd, mixed styles on the epilogue/error screen when WordPress.com account has no connected WooCommerce stores.

**To Reproduce**
1. Start logged out of the app.
2. Select the WordPress.com login option.
3. Enter the email address for a WordPress.com account that is *not* connected to any WooCommerce stores.
4. Finish logging in with the account password or magic link.
5. Notice that the epilogue/error screen shows the error message, illustration, and primary CTA in the middle of the screen with a white background, surrounded by the old epilogue styling (grey background).

**Screenshots**

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

### PR DESCRIPTION
**Pull request by ctarda**
Closes #3364 

| Before | After |
| ---- | ---- |
|  |  |

## Changes
* Set the background color of StoresPickerView controller to the background color provided by WPAuthenticator

## How to test
* Checkout the branch, run `bundle exec pod install`
* Follow the repro instructions in the original issue: login with magic link to an account without linked stores

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift [hunk 1]
```diff
@@ -243,6 +243,10 @@ private extension StorePickerViewController {
         preselectStoreIfPossible()
         reloadInterface()
     }
+
+    func backgroundColor() -> UIColor {
+        return WordPressAuthenticator.shared.unifiedStyle?.viewControllerBackgroundColor ?? .listBackground
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:248]: Isn't this style defined in our styles? 
I see a big optional change and also a singleton usage that makes me a bit nervous 😓

**Review by Ecarrion — APPROVED** [review]
Left a small comment 😇

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift (hunk 1 above)
Comment (ctarda) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:248]: It is, but... WordPresAuthenticator is a singleton, so there isn't much we can do there, and the style needs to match the style exposed by WPAuthenticator. 

That being said, in my opinion, exposing authentication as we do with any other global service would make sense in the long run.
