### PR TITLE
[Login] Allow login for WPCOM suspended sites

### LINKED ISSUE #14196: Improve error parsing for the WPCom endpoint `/connect/site-info` to allow identifying black-flagged websites.
`connect/site-info` endpoint sends the following response while trying to connect to a suspended site.  

```
{
  "error": "connection_disabled",
  "message": "This site has been suspended."
}
```

We should parse this in the authenticator library.

### LINKED ISSUE #14255: Direct black-flagged websites to use site credentials instead of failing.

### LINKED ISSUE #14256: Hide Jeptack upselling points from the app when using a black-flagged website.

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #14196
Closes: #14255
Closes: #14256
Part of: #14384

## Description

⚠️ Don't merge until https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/858 is merged.

Adds code to allow login for WPCOM suspended sites. This logic is added behind a configuration flag in the authenticator library. 

## Steps to reproduce

Prerequisites
- Create a JN site with Woo and Jetpack
- Connect Jetpack from `wp-admin` page
- Follow the steps to mark it as suspended in WPCOM. Internal - p1729584367490299/1729584240.840689-slack-C03L1NF1EA3
- Reach out to me or @hichamboushaba if you need help suspending a site.

Login into a suspended site
- Build and run the app
- Logout if needed
- Login into the app using the JN site
- Check Xcode logs and you should see the following event being tracked.
```
Tracked black_flagged_website_detected, properties: [event: login]
```
- You should be able to login into the app using .org site credentials
- Validate that you don't see the Jetpack banner in the dashboard.

WPCOM credentials login
- Follow the steps and mark the site as not suspended. (Remove flags) Internal - p1729584367490299/1729584240.840689-slack-C03L1NF1EA3
- Logout from the app.
- Try logging in using the same JN site.
- You should be navigated to WPCOM login flow and validate that WPCOM login works.

JN site .org credentials login
- Create a JN site with Woo and no Jetpack
- Logout from the app
- Login into the app using .org site credentials
- Validate that you see the Jetpack banner in the dashboard

## Testing information

I tested the following scenarios.

- Suspended site's .org site credentials login works. The Jetpack banner is hidden. 
- Normal site credentials login works as before. The Jetpack banner is displayed for eligible sites. 
- Normal WPCOM credentials login works as before.

#### Suspended site
| Before | Now |
|--------|--------|
| Simulator Screenshot - iPhone 15 Pro Max - 2024-10-30 at 13 45 21 | Simulator Screenshot - iPhone 15 Pro Max - 2024-10-30 at 13 52 15 |

#### Dashboard - Jetpack banner of site without Jetpack

| Normal JN site (without Jetpack) | Suspended JN site  |
|--------|--------|
| image | image | 

#### Settings - Install Jetpack setting

| Normal JN site (without Jetpack) | Suspended JN site  |
|--------|--------|
| Simulator Screenshot - iPhone 15 Pro Max - 2024-11-12 at 14 24 51 | Simulator Screenshot - iPhone 15 Pro Max - 2024-11-12 at 14 23 43 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/Extensions/UserDefaults+Woo.swift [hunk 1]
```diff
@@ -65,6 +65,10 @@ extension UserDefaults {
 
         // Selected campaign objective saved for future campaigns
         case blazeSelectedCampaignObjective
+
+        // Whether the site is suspended on WordPress.com and can't be connected using Jetpack
+        //
+        case wpcomSiteSuspended
```
Comment (hichamboushaba) [inline WooCommerce/Classes/Extensions/UserDefaults+Woo.swift:71]: Just a question for my learning, do we have any guidelines on where to use `UserDefaults` vs something like `GeneralAppSettings` in the app? in the custom fields project, I used `GeneralAppSettings`, and it needed a lot of boilerplate to my liking, so I'm not sure if I should've used `UserDefaults` instead 😅

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift [hunk 2]
```diff
@@ -60,6 +60,8 @@ final class DashboardViewModel: ObservableObject {
 
     @Published private(set) var jetpackBannerVisibleFromAppSettings = false
 
+    @Published private(set) var isSiteEligibleToInstallJetpack = true
```
Comment (hichamboushaba) [inline WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift:63]: We need a similar logic for the app settings to hide the "Install Jetpack" button.

**Review by hichamboushaba — COMMENTED** [review]
Nice work @selanthiraiyan, the logic works well.

There are just two points that needs addressing before approving the PR, the unit tests are failing, and the "Install jetpack" button is still shown in the app settings.

File: WooCommerce/Classes/Extensions/UserDefaults+Woo.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/Extensions/UserDefaults+Woo.swift:71]: > do we have any guidelines on where to use UserDefaults vs something like GeneralAppSettings in the app?

Good question. I don't think there are any guidelines. 

Personally, I prefer user defaults when I have to update UI when the values change. Because, we can do [this](https://github.com/woocommerce/woocommerce-ios/pull/14257/files#diff-5e4b4001de415046921cf84e4ce2b6c16646ae1bb2067aa6d9ec1fbfa2a855e5R499-R504) to listen to the value using Combine and update UI.

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift (hunk 2 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift:63]: Great catch. Done in 59a6121ff0e211d38068c683e5749c01ec07b8f2. Thank you!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by selanthiraiyan** [comment]
Thank you for the review, @hichamboushaba! 

I addressed your comments and added tracking. I have also enabled this feature and updated the PR description accordingly. 

The PR is ready for another look. 🙏

**Review by hichamboushaba — APPROVED** [review]
Nice work @selanthiraiyan, this works well.

Just a **non blocking** nitpick, I'm aware most of us don't care about a good git history, but personally I do, and find it quite useful when debugging something, so I would suggest to write this branch's history by squashing the last commits that were about fixing the unit tests.

**Comment by selanthiraiyan** [comment]
> I would suggest to write this branch's history by squashing the last commits that were about fixing the unit tests.

I agree. Done.
