### PR TITLE
[Woo POS]Track new cash events

### LINKED ISSUE #15270: [Woo POS] Track new cash events
Ref: pdfdoF-6hn-p2#comment-7662

```
“Cash Payment” tapped: cash_payment_tapped
“Cash Payment” failed: cash_payment_failed
```

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #15270 

## Description
This PR adds two new cash events to POS, ref: pdfdoF-6hn-p2#comment-7662
- `pos_cash_payment_tapped`
- `pos_cash_payment_failed`

## Testing information
1. On success:
  * In POS, process a cash-paid order. Upon tapping the cash collection button in the totals view, observe the `pos_cash_payment_tapped` tapped message is logged in the console:

```
🔵 Tracked pos_cash_payment_tapped, properties: [was_ecommerce_trial: false, blog_id: -1, site_url: https://indiemelon.mystagingwebsite.com, store_id: c5bd46cc-1804-4f7b-badb-bb98c449127f, plan: , is_wpcom_store: false]
```

2. On failure:
  * In `OrderStore`, within `func updateOrder(siteID: Int64, ...` force a failure from the service by returning some error like `return onCompletion(.failure(NSError(domain: "oops", code: -1)))`
  * In POS, attempt to process a cash-paid order, observe it fails and the event `pos_cash_payment_failed` is logged:
```
🔵 Tracked pos_cash_payment_failed, properties: [blog_id: -1, plan: , store_id: c5bd46cc-1804-4f7b-badb-bb98c449127f, is_wpcom_store: false, was_ecommerce_trial: false, site_url: https://indiemelon.mystagingwebsite.com]
```

🐰  @coderabbitai review

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleOrderControllerTests.swift [hunk 1]
```diff
@@ -406,6 +406,51 @@ struct PointOfSaleOrderControllerTests {
...
+                        #expect(Bool(false), "Unexpected action \(action)")
+                    }
+                }
+                Task { @MainActor in
+                    try await sut.collectCashPayment()
+                }
+            }
+
+            // Then
+            #expect(completionResult == true)
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleOrderControllerTests.swift]: nit: it looks like the returning value can only be `true`, maybe the assertion isn't needed? The `withCheckedContinuation` can also return Void.

File: WooCommerce/WooCommerceTests/POS/Models/PointOfSaleAggregateModelTests.swift [hunk 2]
```diff
@@ -869,6 +869,24 @@ struct PointOfSaleAggregateModelTests {
             // Then
             #expect(analyticsProvider.receivedEvents.first(where: { $0 == "back_to_checkout_from_cash" }) != nil)
         }
+
+        @available(iOS 17.0, *)
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/POS/Models/PointOfSaleAggregateModelTests.swift:873]: just curious, could `@available(iOS 17.0, *)` be moved to the struct level since every test function seems to need this?

**Review by jaclync — APPROVED** [review]
Thanks for adding the test cases! LGTM :shipit:

File: WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleOrderControllerTests.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleOrderControllerTests.swift]: Good point, updated on https://github.com/woocommerce/woocommerce-ios/pull/15293/commits/8c4d43aec8529335a7e40cd1f0a7e49a9a12c412

File: WooCommerce/WooCommerceTests/POS/Models/PointOfSaleAggregateModelTests.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/POS/Models/PointOfSaleAggregateModelTests.swift:873]: It doesn't seem to be the case 😞 , there might be some internals that require this to be explicitly declared on the test level due being a macro, otherwise the compiler complains with `Attribute 'Test' cannot be applied to this function because it has been marked '@available(iOS 17.0, *)' (from macro 'Test')`
