### PR TITLE
Variations: Error handling

### LINKED ISSUE #8536: Variations: Error Handling
The create all variations flow can fail at multiple places, like

- Fetching existing variations
- Creating variations locally
- Creating variations remotely 

We need to make sure these errors are properly informed to the user and handled correctly.

### PR DESCRIPTION
**Pull request by Ecarrion**
Closes: #8536

# Why

This PR adds error handling for the cases where there is a problem fetching variations or there is a problem creating variations remotely.

# How

- Define and send the corresponding error states.
- One workaround to properly dismiss the blocking loading indicator right after its presentation has been issued.

Fetching Error | Creating Error
--- | ---
fetch | create

# Testing Step

- Go to a variable product that is missing variations.
- Turn off wifi and start the generate variations process.
- See that the error notice is presented.

- Turn on wifi and start the generate variations process.
- Before confirming the variations to generate, turn off wifi and then tap "OK" on the alert.
- See that the error notice is presented.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift [hunk 1]
```diff
@@ -64,6 +64,7 @@ final class ProductVariationsViewController: UIViewController, GhostableViewCont
     ///
     private let syncingCoordinator = SyncingCoordinator()
 
+
```
Comment (rachelmcr) [inline WooCommerce/Classes/ViewRelated/Products/Variations/ProductVariationsViewController.swift:67]: nit: This extra line break looks like it was added accidentally?

**Review by rachelmcr — APPROVED** [review]
🚀 Looks good and tests well!
