### PR TITLE
[Order Details] Allow failed orders to show receipt if eligible

### LINKED ISSUE #14863: [Mobile Payments] Allow failed order receipt to be opened from Order Details
The latest WooCommerce and Stripe Extension versions should allow generating and opening a receipt from Order Details both for completed and failed Orders.

Currently, we only allow opening receipts for completed orders.

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #14863
Closes: WOOMOB-104

## Description
This PR updates the logic around rendering "See Receipt" in Order Details to take into account that now failed orders can also contain receipts. Before this, we only shows receipts for orders with `datePaid != nil`, but this is unreliable.

https://github.com/user-attachments/assets/3dbda6cf-0084-40f3-9f3c-119bc38d3955

## Changes
- Made explicit `isOrderStatusEligibleForReceipt` by checking specific order statuses, rather than rely on `datePaid`
- Added a case to handle showing `.failed` receipts if the site is eligible for sending them.
- Removed references to wcPluginDevVersion, we no longer need to check dev versions.
- Refactored `isEligibleForFailedPaymentEmailReceipts to` not use async await. The mix between this bit and the rest of the closure-based logic in Order Details seems to produce inconsistent results. Ref: p1745894442252789-slack-CGPNUU63E

## Testing information
- In order to mock a failed transaction via card present, you can simulate a payment for an order that ends in $0.05, eg: product valued at $1.05 taxes included.
- Confirm that "See Receipt" appears and the receipt can be opened, confirm the status is "Failed"
- Confirm that you receive the failed email as well:

Screenshot 2025-04-29 at 10 33 50

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift [hunk 1]
```diff
@@ -2033,3 +2049,13 @@ extension OrderDetailsDataSource {
         static let cellDefaultMargin: CGFloat = 16
     }
 }
+
+// MARK: - Receipts helpers
+private extension OrderDetailsDataSource {
+    var isOrderStatusEligibleForReceipt: Bool {
+        order.status == .completed ||
+        order.status == .processing ||
+        order.status == .refunded ||
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift]: Without knowing the backend support for different order statuses, just wanted to sure that these two statuses are supported as the original issue is for **completed** and **failed** statuses https://github.com/woocommerce/woocommerce-ios/issues/14863.

File: WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift [hunk 2]
```diff
@@ -1517,11 +1517,27 @@ extension OrderDetailsDataSource {
...
         }
-        ReceiptEligibilityUseCase().isEligibleForBackendReceipts { isEligibleForReceipt in
-            completion(isEligibleForReceipt)
+        let receiptEligibility = ReceiptEligibilityUseCase()
+
+        switch order.status {
+        case .completed, .processing, .refunded:
+            receiptEligibility.isEligibleForBackendReceipts { isEligibleForReceipt in
+                completion(isEligibleForReceipt)
+        }
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift]: nit: the earlier indentation here might make it look like the switch statement ends here

```suggestion
            }
```

Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift]: ❓ About having separate checks from `ReceiptEligibilityUseCase` in different order statuses:

Could the implementation details for different order statuses be in the `ReceiptEligibilityUseCase` - maybe a new function that takes in an order status so that it's just one check here? `OrderDetailsDataSource` is already quite huge, and it'd be easier to unit test for different order statuses when all the logic is in a use case. This way, `ReceiptEligibilityUseCase.selectedPaymentGatewayID`, which isn't in the `ReceiptEligibilityUseCaseProtocol` protocol, can be private.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift [hunk 3]
```diff
@@ -69,30 +65,52 @@ final class ReceiptEligibilityUseCase: ReceiptEligibilityUseCaseProtocol {
...
+                                       onCompletion: onCompletion)
+            case CardPresentPaymentsPlugin.stripe.gatewayID:
+                self.isPluginSupported(CardPresentPaymentsPlugin.stripe.pluginName,
+                                       minimumVersion: Constants.FailedReceiptAfterPayment.stripePluginMinimumVersion,
+                                       onCompletion: onCompletion)
+            default:
+                onCompletion(false)
+            }
+        }
+    }
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: I see the async/await vs. closure issue now. After some debugging, I think the root cause is that the check for showing the receipt row in order details is async:

https://github.com/woocommerce/woocommerce-ios/blob/9248c6a8e4e73d0306e14a1b950a629efd24b629/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L1364-L1368

While the display logic for all other rows are synchronous. For some reason, block-based checks (which don't involve a network request) return quickly before the final sections are set:

https://github.com/woocommerce/woocommerce-ios/blob/9248c6a8e4e73d0306e14a1b950a629efd24b629/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L1486-L1502

Whereas async/await + Task approach doesn't always come back before the sections are set.

Personally, I'd refactor `OrderDetailsDataSource.reloadSections` to not assume `isEligibleForBackendReceipt` closure always come back immediately. What if we're adding a network request in the future? It's an async call, and all dependent results like the final sections are expected to be in the completion block.

Here's a POC commit I tested for failed orders with async/await in the plugin checks, it could be polished:

https://github.com/woocommerce/woocommerce-ios/commit/2cc6ceb53c30e40915d0a3743c19627d0a4dbf18

Another approach for the async receipt eligibility check is to follow other async checks like how `orderHasLocalReceipt: Bool` is set by an async call then used in `reloadSections` as a synchronous check.

**Review by jaclync — COMMENTED** [review]
Thanks for starting the discussion yesterday, I didn't fully understand the issue until I reviewed the PR. While the closure based approach works, I think we can address the root cause in order details regarding the async receipt eligibility check. I'd also suggest adding a new function in the receipt eligibility use case to check for receipt eligibility given an order status for easier unit testing and simpler call from order details.

File: WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/OrderDetailsDataSource.swift]: That's a good point. By making the order status explicit rather than relying on `datePaid != nil` then we have to also declare which other statuses would allow for a receipt, that said, maybe is best to keep this as it was just for safety in case we're missing something (i.e: .custom). I'll make the changes to handle `.failed`, but keep previous statuses still relying on datePaid, this can be updated/tested separately.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: Thanks for testing this and sharing the experimental branch 🙇 

I'd personally wouldn't make these changes in the context of this PR. OrderDetails and its data source are pretty big, so I'd make these separately so can be tested properly for all cases, but I agree that the refactor is a better way to handle the receipts bit (and further changes in the future that may bring the same closure vs async/await problems).

I'll cherry pick your POC into a separate branch, work with it and submit it first before coming back to this one 👍

**Comment by jaclync** [comment]
Hi @iamgabrielma, lemme know if the PR is ready for review and I'll get to it tomorrow the latest!

**Comment by iamgabrielma** [comment]
> Hi @iamgabrielma, lemme know if the PR is ready for review and I'll get to it tomorrow the latest!

Thanks! While testing it after the latest changes to [async rows](https://github.com/woocommerce/woocommerce-ios/pull/15588/files), we seem to have introduced a bug in the `isEligibleForBackendReceipt` logic: since `date.paid` property is set during processing before we have the chance to reach receipt eligibility use case, we always skip it because does not pass the guard. There's also the side effect of any order that already has a `date.paid` set but later on switches state (either failed again or a correct state) won't generate a receipt for the same reason.

Should be fine to remove this guard now that we rely on specific order status when checking the order requirements, but I'll test this today before trying to wrap up this PR 👍

**Comment by iamgabrielma** [comment]
This is ready for review @jaclync , this is simplified from the first approach:
- Receipts eligibility only relies on `meetsOrderStatusRequirement`, I've restored the original async-await implementation since the order details now can handle it.
- Removed the logic to handle `dev` woocommerce versions

I'm not sure why the diff for `ReceiptEligibilityUseCaseTests` shows the some tests as they show, for example `test_when_WooCommerce_version_is_below_minimum_then_returns_false` shows the version 8.5 has been updated to ...8.5. I suspect because I removed some dev-related tests at the beginning of the file, if you check for the tests that shows these modifications you'll see that haven't changed:

```
test_when_WooCommerce_version_is_equal_or_above_minimum_then_returns_true
test_isEligibleForFailedPaymentEmailReceipts_when_plugins_are_inactive_then_returns_false
test_isEligibleForFailedPaymentEmailReceipts_when_plugins_are_supported_then_returns_true
test_isEligibleForFailedPaymentEmailReceipts_when_woopayments_version_is_incorrect_then_returns_false
test_isEligibleForFailedPaymentEmailReceipts_when_stripe_gateway_then_returns_true
test_isEligibleForFailedPaymentEmailReceipts_when_stripe_gateway_is_outdated_then_returns_false
```

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift [hunk 4]
```diff
@@ -5,6 +5,7 @@ protocol ReceiptEligibilityUseCaseProtocol {
     func isEligibleForBackendReceipts(onCompletion: @escaping (Bool) -> Void)
     func isEligibleForSuccessfulPaymentEmailReceipts(onCompletion: @escaping (Bool) -> Void)
     func isEligibleForFailedPaymentEmailReceipts(paymentGatewayID: String, onCompletion: @escaping (Bool) -> Void)
+    func meetsOrderStatusRequirement(_ orderStatus: OrderStatusEnum, onCompletion: @escaping (Bool) -> Void)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: nit: how about keeping a consistent name `isEligibleForReceipts(_ orderStatus: OrderStatusEnum, onCompletion: @escaping (Bool) -> Void)`? When I saw the function name without the implementation, I thought this function just checks for if the order status meets the requirement.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift [hunk 5]
```diff
@@ -102,11 +133,6 @@ private extension ReceiptEligibilityUseCase {
                     return continuation.resume(returning: false)
                 }
 
-                // Checking for concrete versions to cover dev and beta versions
-                if plugin.version.contains(minimumVersion) {
-                    return continuation.resume(returning: true)
-                }
-
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift:109]: ❓ What are the reasons for removing the check that supports dev and beta versions?
Saw this mentioned in the PR description:

> Removed the logic to handle dev woocommerce versions

When testing with Woo Beta Tester plugin or for core development, I thought it's common to have the WC version as the dev/beta versions.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift [hunk 6]
```diff
@@ -90,9 +86,44 @@ final class ReceiptEligibilityUseCase: ReceiptEligibilityUseCaseProtocol {
...
+                }
+            }
+        default:
+            return onCompletion(false)
+        }
+    }
 }
 
 private extension ReceiptEligibilityUseCase {
+    func isPluginSupported(_ pluginName: String, minimumVersion: String, onCompletion: @escaping (Bool) -> Void) {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: nit: is this still used?

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 4 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: nit: how about making this new function async/await friendly? It'd simplify the use case in `OrderDetailsDataSource`.

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift [hunk 7]
```diff
@@ -32,11 +31,11 @@ final class ReceiptEligibilityUseCaseTests: XCTestCase {
         XCTAssertFalse(isEligible)
     }
 
-    func test_when_WooCommerce_version_is_correct_dev_version_then_returns_true() {
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift:35]: If we do decide not to support WC dev version, it might be worth keeping the test and flipping the assertion.

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift [hunk 8]
```diff
@@ -205,92 +210,133 @@ final class ReceiptEligibilityUseCaseTests: XCTestCase {
...
+            sut.isEligibleForFailedPaymentEmailReceipts(paymentGatewayID: "woocommerce-stripe", onCompletion: { result in
                 promise(result)
             })
         }
 
         // Then
+        XCTAssertFalse(isEligible)
+    }
+
+    func test_meetsOrderStatusRequirement_with_completed_status_returns_true() {
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift]: nit: would be nice keeping the Given/When/Then comments for consistency and clearer structure of the test case. Same for other `meetsOrderStatusRequirement` test cases as well.

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift [hunk 9]
```diff
@@ -205,92 +210,133 @@ final class ReceiptEligibilityUseCaseTests: XCTestCase {
...
+        let plugin = SystemPlugin.fake().copy(name: "WooCommerce", version: "9.5.0", active: true)
+
+        stores.whenReceivingAction(ofType: SystemStatusAction.self) { action in
+            switch action {
+            case let .fetchSystemPlugin(_, _, onCompletion):
+                onCompletion(plugin)
+            default:
+                XCTFail("Unexpected action")
+            }
+        }
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift:234]: nit: this could be extracted to private helper function for reuse.

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift [hunk 10]
```diff
@@ -205,92 +210,133 @@ final class ReceiptEligibilityUseCaseTests: XCTestCase {
...
+                promise(result)
+            }
+        }
+
         XCTAssertTrue(isEligible)
     }
 
-    func test_isEligibleForFailedPaymentEmailReceipts_when_woopayments_version_is_incorrect_then_returns_false() {
-        // Given
+    func test_meetsOrderStatusRequirement_with_processing_status_returns_true() {
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift]: nit: might be worth mentioning the condition when it's true (otherwise it could sound like processing status always meets the requirement) - from my understanding, it's when the WC version is above a minimum version. Same for the refunded status test case.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift [hunk 11]
```diff
@@ -90,9 +86,44 @@ final class ReceiptEligibilityUseCase: ReceiptEligibilityUseCaseProtocol {
...
+
+    func meetsOrderStatusRequirement(_ orderStatus: OrderStatusEnum, onCompletion: @escaping (Bool) -> Void) {
+        switch orderStatus {
+        case .completed, .processing, .refunded:
+            isEligibleForBackendReceipts { isEligibleForReceipt in
+                onCompletion(isEligibleForReceipt)
+            }
+        case .failed:
+            selectedPaymentGatewayID { [weak self] gatewayID in
+                guard let gatewayID = gatewayID else {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: super nit:
```suggestion
                guard let gatewayID else {
```

**Review by jaclync — APPROVED** [review]
Works as expected, thanks for the updates it's much easier to review now! Mostly a question about support for dev/beta versions.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 5 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift:109]: Yes, this was very specific to this project: The internals of `VersionHelpers` used in the same function already checks for beta and dev version that might come with Woo Beta Tester, so it will pass the check as expected. This additional check was put in place just for testing, due to how the changes were provided by core folks with specific development branches to be installed in the test site, which sometimes were behind the latest versions.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 6 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: Is not! https://github.com/woocommerce/woocommerce-ios/pull/15558/commits/d2fda6cebb587b49f58c2dc33e52a2b4adb0f55a

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/244">22.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 4 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: Agree: https://github.com/woocommerce/woocommerce-ios/pull/15558/commits/9eb07735c03979fdbea4cfc218da0fb47d7739b7

I'll leave the closure based for now, so I don't have to redo the tests 👍

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift (hunk 7 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift:35]: Same as above, the dev/beta versions that follow the actual core deployment process are already covered by the version helper class. This was a very specific case on how the feature was delivered by core (eg: feature released publicly on 9.7 last minute, but we had to work with 9.6 internally) so we added the tests as well. Now are no longer necessary as it's part of the correct core version.

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift (hunk 8 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEligibilityUseCaseTests.swift]: True that! https://github.com/woocommerce/woocommerce-ios/pull/15558/commits/fcbbcb0ca4804755f8decdff84272a370890ac49

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 11 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: https://github.com/woocommerce/woocommerce-ios/pull/15558/commits/2b185a6c47d149eec63f011d2d3a7cfa68ba547e 🚀

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 5 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift:109]: I'm actually having a similar plugin version check in a separate PR and removing this check blocks `-beta/-dev/-alpha/-rc`. From the test cases for the VersionHelpers, this blocking behavior also seems intentional:

https://github.com/woocommerce/woocommerce-ios/blob/d6d6c560996ff84220dc282e464b9c4703793262/WooCommerce/WooCommerceTests/Extensions/VersionHelpersTests.swift#L34-L40

If we want to support alpha/beta/dev/rc builds of the same version, I think we do need to keep this check.

Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift:109]: > If we want to support alpha/beta/dev/rc builds of the same version

Interesting, I see what you mean: Anything tagged as -dev or other for the same version we're checking, is always below the non-tagged version:

```
po VersionHelpers.isVersionSupported(version: "9.0-dev", minimumRequired: "9.0.0")
false

po VersionHelpers.isVersionSupported(version: "9.0.1-dev", minimumRequired: "9.0.0")
true
```
