### PR TITLE
Quick Fix: Don't highlight order cell on iPad OS 16 and 16.1 to avoid crashes

### LINKED ISSUE #13485: NSInternalInconsistencyException: Focus item <WooCommerce.OrderTableViewCell: 0x14c946a00> does not provide a parentFocusEnvironment.
Sentry Issue: [WOOCOMMERCE-IOS-1MV2](https://a8c.sentry.io/issues/5508158455/?referrer=github_integration)

```
NSInternalInconsistencyException: Focus item <WooCommerce.OrderTableViewCell: 0x14c946a00> does not provide a parentFocusEnvironment.
  File "OrderListViewController.swift", line 298, in closure in OrderListViewController.configureViewModel
  File "FetchResultSnapshotsProvider.swift", line 259, in FetchResultSnapshotsProvider.HiddenFetchedResultsControllerDelegate.controller
  File "<compiler-generated>", in FetchResultSnapshotsProvider.HiddenFetchedResultsControllerDelegate.controller
  File "<compiler-generated>", line 256, in FetchResultSnapshotsProvider.HiddenFetchedResultsControllerDelegate.controller
  File "NSManagedObjectContext+Storage.swift", line 138, in NSManagedObjectContext.saveIfNeeded
...
(66 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by staskus**
Closes: #13485

## Description
Context peaMlT-Ng-p2

This a quick fix to avoid a crash on iPadOS 16 and 16.1 when selecting order and refreshing. Given the low usage of this particular setup and the fact that it no longer crashes with a higher iOS version, disabling `allowFocus` looks to be enough.

### iPadOS 16 / 16.1

1. Select orders tab
2. Tap on the order
3. Pull to refresh
4. Confirm there's no crash

### iPadOS 16.2+

1. Select orders tab
2. Tap on the order
3. Pull to refresh
4. Confirm there's no crash

## Screenshots

---
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift [hunk 1]
```diff
@@ -570,6 +570,10 @@ private extension OrderListViewController {
     /// Removes the selected state otherwise.
     ///
     func highlightSelectedRowIfNeeded(shouldScrollIfNeeded: Bool = false) {
+        guard supportsHighlighting() else {
```
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]: Great work finding the cause of this bug @staskus 

I am adding a quick warning to check that that guard doesn't prevent any necessary action from happening. As you can see, that function(`highlightSelectedRowIfNeeded`) contains logic not strictly related to highlight, such as deselecting or scrolling. Would it be ok if we don't execute these actions for iPad OS 16 and 16.1?
I remember that this [PR](https://github.com/woocommerce/woocommerce-ios/pull/12053) addressed a regression caused by a similar change :)

Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]: Thanks, this is a good comment!

Yes, I haven't found out which part exactly causes the issue since I spent only a few minutes on this PR. However, I can see if adding `highlightSelectedRowIfNeeded` only on `selectRow` part would solve the issue 👍

Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]: While testing I managed to crash even with this quick fix, so there are more issues 😕

Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]: It looks like disabling `allowFocus` on `tableView` works, and works better to avoid the crash

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift [hunk 2]
```diff
@@ -584,6 +585,25 @@ private extension OrderListViewController {
...
+
+        let systemVersion = ProcessInfo.processInfo.operatingSystemVersion
+        let majorVersion = systemVersion.majorVersion
+        let minorVersion = systemVersion.minorVersion
+
+        if majorVersion == 16 && (minorVersion == 0 || minorVersion == 1) {
+            return false
+        }
+
+        return true
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]:
```suggestion
        let iOS16dot2 = OperatingSystemVersion(majorVersion: 16, minorVersion: 2, patchVersion: 0)

        return ProcessInfo().isOperatingSystemAtLeast(iOS16dot2)
```

This is equivalent, and I've checked it – just seems a little more readable. Up to you though, either approach is fine.

File: RELEASE-NOTES.txt [hunk 3]
```diff
@@ -6,6 +6,7 @@
 -----
 - [**] Fixed Collect Payment from the menu on iPads running iOS 16 [https://github.com/woocommerce/woocommerce-ios/pull/13491]
 - [Internal] Added missing events for custom range on the stats dashboard card. [https://github.com/woocommerce/woocommerce-ios/pull/13506]
+- [Internal] Disable focus for order rows on iPadOS 16 and 16.1 to avoid crashes. [https://github.com/woocommerce/woocommerce-ios/pull/13512]
```
Comment (joshheald) [inline RELEASE-NOTES.txt]: It doesn't need to be internal, fixing crashes can/should be mentioned in release notes, even if we aren't specific about how/which one we fix.

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift (hunk 2 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]: Alternatively, this might be easier to spot with a search when we drop iOS 16?

```suggestion
        if #available(iOS 16.2, *) {
            return true
        } else {
            return false
        }
```

**Review by joshheald — APPROVED** [review]
Suggested some alternate approaches to the version check, but overall well done for finding this fix!

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift (hunk 2 above)
Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift]: > Alternatively, this might be easier to spot with a search when we drop iOS 16?

Yes, that's a great idea!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/217">19.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
