### PR TITLE
[Orders] Ensure last order item can be removed from stored order

### LINKED ISSUE #13664: Product is not removed from order when it's the only one
**Describe the bug**
When the order has just one product, removing that product from the order has no effect on the order details. The Order total is updated though, showing $0

**To Reproduce**
1. Go to Orders
2. Tap on + to create a new order.
3. Add a product.
4. Tap on Create
5. Tap on Edit
6. Remove the product and tap on Done
7. The order still contains that product (wrong)
8. Go back and enter again in the order
9. The product is still there
10. Tap on Edit. The product is still there.

**Screenshots**

https://github.com/user-attachments/assets/c64221e3-6f79-4dcb-9907-7d43993e81d8

**Expected behavior**
The product should be removed from the order right away.

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #13664

## Description

This fixes a bug: when an order only had one product in it, removing that product did not update the order details.

We were sending the correct remote request, and the order was updated remotely as expected. However, we were not upserting the order correctly in the storage layer — we only upserted the order line items (products) if there was at least one item in the order. We showed incorrect products in the order unless the entire order list was refreshed.

This PR removes a check so the order line items are upserted even if the order has no line items (i.e. the last product is removed from the order). I don't see any potential negative side effects from removing this check, since we want to be able to update the stored order items even if there are none.

## Testing information

1. Go to Orders.
2. Tap on + to create a new order.
3. Add a product.
4. Tap on Create.
5. Tap on Edit.
6. Remove the product and tap on Done.
7. Confirm the order details contain no products.
8. Tap on Edit. Confirm there are no products in the order form.

## Screenshots

https://github.com/user-attachments/assets/aedcd4a1-1cc2-4f0f-801f-1e136755769b

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bozidarsevo — APPROVED** [review]

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift [hunk 1]
```diff
@@ -72,10 +72,6 @@ struct OrdersUpsertUseCase {
         let siteID = readOnlyOrder.siteID
         let orderID = readOnlyOrder.orderID
 
-        guard readOnlyOrder.items.count > 0 else {
```
Comment (toupper) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift:75]: I'm curious, are we sure that removing this code won't add any regression? I see the commit message from @pmusolino when added with the message 

> fix: handle order items in OrdersUpsertUseCase

Comment (toupper) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift:75]: Do you think it's worth adding a unit test for this case? Or given that we're just removing a condition, they aren't necessary?

Comment (bozidarsevo) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift:75]: I was looking at the code below that has the comment
`// Now, remove any objects that exist in storageOrder.items but not in readOnlyOrder.items`
And if we do not remove this `guard` then the removing of the objects in storage might not happen?

Comment (rachelmcr) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift:75]: > And if we do not remove this guard then the removing of the objects in storage might not happen?

This is exactly why we need to remove this `guard`, because otherwise we don't update the stored order items when there are no items in the updated order.

I can't think of any situation where this would cause a regression. It was added in #6401 and I don't see any context there that would prevent us from handling the case where there are no order items. I expect that the check was added to bail early in case no items need to be added/updated, but we shouldn't bail in case all the order items need to be removed.

Comment (rachelmcr) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift:75]: Good thought. I wasn't going to add one since it's just removing a condition, but I realized there aren't any unit tests that cover removing order items from storage. I went ahead and added one in [9c7bfad](https://github.com/woocommerce/woocommerce-ios/pull/13665/commits/9c7bfad0dd9477cfd926292002458a069e2ffd11).
