### PR TITLE
Order badge cuts off with two characters

### LINKED ISSUE #1176: Notification Badge: badge is cut off when using two characters
**Describe the bug**
9+ on the badge is squished / cut off. Both characters need to fit comfortably within a circle.

**To Reproduce**
1. Have 10 orders or more waiting to be fulfilled (pending status)
2. Go to the Orders tab
3. Note the badge. Characters don't fit inside the circle.

**Screenshots**

**Expected behavior**
The new orders badge has enough space to display "9+" 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: all
- iOS version: any 
- WooCommerce iOS version: 2.5

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #1176.

This PR tweaks the badge location, spacing and sizing for the Orders badge, based on the numbers found in the [designs file](https://www.figma.com/file/JCbo1C7AKprTKGsCFkQo0Sk9/Stats-Improvements?node-id=617%3A312)

**Before**

**After**

### To Test
1. Run the app from develop
2. Change to a store with more than 9 new orders
3. Check out the badge
4. Check out this branch & re-run the app
5. Observe badge size

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift [hunk 1]
```diff
@@ -34,25 +34,36 @@ private extension OrdersBadgeController {
...
+        static let extendWidth = CGFloat(23)
+        static let height      = CGFloat(15)
     }
 
     func badge(for tab: WooTab, with text: String) -> BadgeLabel {
+        var width = Constants.width
+        var horizontalPadding = CGFloat(2)
+
+        let ninePlus = NSLocalizedString("9+", comment: "A badge with the number of orders. More than nine new orders.")
+        if text == ninePlus {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift]: would it be more flexible if this check is on the text length, like `text.count > 1`?

File: WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift [hunk 2]
```diff
@@ -252,7 +252,12 @@ final class AddCustomTrackingViewModel: ManualTrackingViewModel {
         self.order = order
         self.providerName = initialName
 
-        loadSelectedCustomShipmentProvider()
+        // if we don't have a provider name, try to load a previous one
+        guard let providerName = self.providerName,
+            !providerName.isEmpty else {
+                loadSelectedCustomShipmentProvider()
+                return
+        }
```
[the remark this answers is not in the document]
Comment (jaclync) [reply WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift]: ooh looks like it's from this PR? https://github.com/woocommerce/woocommerce-ios/pull/1186/files 😆

[the remark this answers is not in the document]
Comment (mindgraffiti) [reply WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift]: haha, that's what I get for being sidetracked and fixing a bug in the middle of another bug fix 😛

File: WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift (hunk 1 above)
Comment (mindgraffiti) [reply WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift]: Maybe. I try not to assuming things based on English (for example, a language may just stop counting and say "ten", and it may be a single character to represent "ten"), and I'm not sure what it looks like for non-roman numeral systems.

**Comment by mindgraffiti** [comment]
Updated. Now with non-fuzzing borders and text that disables dynamic type.

not-fuzzy

File: WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift [hunk 3]
```diff
@@ -32,31 +32,52 @@ final class OrdersBadgeController {
...
+        var horizontalPadding = CGFloat(2)
+        var xOffset = Constants.xOffset
+
+        let ninePlus = NSLocalizedString("9+", comment: "A badge with the number of orders. More than nine new orders.")
+        if text == ninePlus {
+            horizontalPadding = CGFloat(4)
+            width = Constants.extendWidth
+        }
+
+        if UIApplication.shared.statusBarOrientation.isLandscape {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift]: I think the check on `isLandscape` will miss the iPad portrait case, where the tab icon and title also have a horizontal layout (screenshot below). I couldn't find the official documentation on the conditions for horizontal/vertical tab bar item layout, but it seems to have horizontal layout when the screen is landscape OR has [regular horizontal size class](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/)

Simulator Screen Shot - iPad Air 2 - 2019-08-16 at 12 52 51

File: WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift [hunk 4]
```diff
@@ -252,7 +252,7 @@ final class AddCustomTrackingViewModel: ManualTrackingViewModel {
         self.order = order
         self.providerName = initialName
 
-        loadSelectedCustomShipmentProvider()
```
[the remark this answers is not in the document]
Comment (mindgraffiti) [reply WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift]: Thanks for the reminder! I didn't merge from develop yesterday. Fixed.

File: WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift (hunk 3 above)
Comment (mindgraffiti) [reply WooCommerce/Classes/ViewRelated/OrdersBadgeController.swift]: Good catch! I forgot to address this with my last set of changes, thanks for reminding me. This is why I prefer .xib files when working with UI. Size classes make it more obvious when I miss cases like this.

**Comment by mindgraffiti** [comment]
>I saw that the tab bar item has a badge feature where we can set the value and color: 

TIL! That's so exciting. Reverting my changes for the screen orientation adjustments and restoring Cesar's original positioning. Updated the main PR description screenshots. Thanks for all the reviews!
