### PR TITLE
[Woo POS] Fix `Add More` payment race condition

### LINKED ISSUE #13495: [Woo POS] Possible to come back from checkout when payment is processed
POS allows one to come back from the checkout screen while in "Tap, swipe, insert" state. However, if we press back and at the same time payment starts being processed, POS gets stuck in the wrong state.

I'm not sure if it should be solved from View Model site or from the Services side. However, I expect that after we call `cancelPayment`, the previous payment should no longer affect the POS state. 

https://github.com/user-attachments/assets/ac54d32f-0daa-42ee-97e1-8eef696b5b23

It could be related to https://github.com/orgs/woocommerce/projects/247/views/7?sliceBy%5Bvalue%5D=iOS+%F0%9F%8D%8E&pane=issue&itemId=73045105

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #13495 

## Description

Previously, it was possible to go back from the Checkout screen, and still tap a card on the payment before it's cancelled.

This left the POS in a broken state, and required the app to be force quit to resolve it.

The issue was caused by the cancellation call happening when the `TotalsView` disappeared – i.e. when it finished transitioning off screen, which takes some time.

To fix it, we now call cancellation when the back button is tapped.

## Steps to reproduce

This is easiest with the simulated card reader, but can be done with a real reader as well

1. Launch the app and go to POS mode
2. Connect the reader
3. Add something to the cart
4. Tap `Check out`
5. Wait until the screen shows `Tap, swipe, or insert your card`
6. If using the simulated reader, wait 3-4 seconds and then tap back. If using a physical reader, tap back and tap the card simultaneously.
7. Observe that it goes back as expected, you can change the order, and check out with a new total

## Testing information

Cancel will be called multiple times – this is fine, the first call will win.

### After fix

https://github.com/user-attachments/assets/1346a27f-508e-4d31-97b2-bdd96b8d033a

### Before fix
(note the state at the very end of this video)

https://github.com/user-attachments/assets/d4f939a5-8c2f-4fb8-af81-6470a13555eb

---
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] This PR includes refactoring; smoke testing of the entire section is needed.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
N.B. I've moved the responsibility for `orderState` related logic to the `PointOfSaleDashboardViewModel` – it would be good to get thoughts on this, but I felt that the TotalsViewModel and CartViewModel shouldn't need to know about the OrderState to do their work.

It's arguable that it does make sense for CartViewModel to know about this  – so let's discuss if you disagree: @bozidarsevo @iamgabrielma @staskus tagging you all just for this discussion point.

File: WooCommerce/Classes/POS/Presentation/TotalsView.swift [hunk 1]
```diff
@@ -168,6 +165,7 @@ private extension TotalsView {
 private extension TotalsView {
     private var newTransactionButton: some View {
         Button(action: {
+            // TODO: This is the only place we use PointOfSaleDashboardViewModel in TotalsView – let's break that link.
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/TotalsView.swift:168]: 💯

**Review by staskus — APPROVED** [review]
Works great! 👍 

Also thanks for refactoring CartViewModel out of TotalsView and removing this awkward orderStage binding.

**Comment by iamgabrielma** [comment]
> it would be good to get thoughts on this, but I felt that the TotalsViewModel and CartViewModel shouldn't need to know about the OrderState to do their work.

Thanks for changing this 💯 . I agree that the cart and totals shouldn't need to know about this state. I believe we've tried to do this when we did the previous dashboard refactoring into smaller view models, but there was some bottlenecks that didn't allow to set a clean separation right away.
