### PR TITLE
Blaze: Fix incorrect order for campaigns

### LINKED ISSUE #12975: Blaze: Incorrect order for items in campaign list
**Describe the bug**
When a store has campaign IDs from 9999 to 10000, the campaign list displays the item with ID 9999 first even though it's older.

**Steps to reproduce**
- Log in to a store with more than 9 campaigns.
- Create a new campaign.
- Notice that the latest campaign is not at the top of the list.

**Expected behavior**
Latest items should be displayed at the top of the list

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12975 

## Description

Previously, when a store has campaign IDs from 9999 to 10000, the campaign list displays the item with ID 9999 first even though it's older. The reason is that the IDs are string, and by default, strings starting with "9" go before those starting with "1" descendingly.

This PR fixes this logic by using `NSString.localizedStandardCompare` to order numeric strings as expected.

## Testing information

- Log in to a store with 9 campaigns.
- Create a new campaign.
- On the My Store screen, confirm that the latest campaign is displayed.
- Switch to the Menu tab > Blaze.
- Confirm that the latest campaign with ID "10" should be on the top of the list and go before the campaign with ID "9".

## Screenshots

Dashboard card | Campaign list
--- | ---
 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/208">19.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModelTests.swift [hunk 1]
```diff
@@ -517,6 +517,39 @@ final class BlazeCampaignDashboardViewModelTests: XCTestCase {
         }
     }
 
+    @MainActor
+    func test_latest_campaign_is_displayed() async {
```
Comment (selanthiraiyan) [inline WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModelTests.swift:521]: Nice test. ❤️

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeCampaignList/BlazeCampaignListViewModel.swift [hunk 2]
```diff
@@ -46,7 +46,9 @@ final class BlazeCampaignListViewModel: ObservableObject {
     /// Blaze campaign ResultsController.
     private lazy var resultsController: ResultsController<StorageBlazeCampaignListItem> = {
         let predicate = NSPredicate(format: "siteID == %lld", siteID)
-        let sortDescriptorByID = NSSortDescriptor(keyPath: \StorageBlazeCampaignListItem.campaignID, ascending: false)
+        let sortDescriptorByID = NSSortDescriptor(key: "campaignID",
+                                                  ascending: false,
+                                                  selector: #selector(NSString.localizedStandardCompare))
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Blaze/BlazeCampaignList/BlazeCampaignListViewModel.swift:51]: TIL

**Review by selanthiraiyan — APPROVED** [review]
🚀
