### PR TITLE
[Woo POS] Order total calculations ignore "Prices entered with tax" settings

### LINKED ISSUE #13324: [Woo POS] Order total calculations ignore "Prices entered with tax" settings
**Describe the bug**

When `Prices entered with tax`: `Yes, I will enter prices inclusive of tax` tax setting is enabled, iOS POS mode still treats all product prices as pre-tax, resulting in a wrong Order Totals calculation. 

**To Reproduce**
1. Enable `Yes, I will enter prices inclusive of tax` (WooCommerce -> Settings -> Tax -> Prices entered with tax)
2. Enter POS mode
3. Add a product
4. Check out
5. Notice that the order total adds a tax on top of the tax-inclusive product

**Screenshots**

| POS | IPP |
| --- | --- |
| image 1 | image 2 |

**Expected behavior**

Order Totals on POS should be calculated taking `Yes, I will enter prices inclusive of tax` setting into consideration.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air 11
- iOS version: 17.5
- WooCommerce iOS version: 9.1

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://testpovilasstore.mystagingwebsite.com
Site address (URL): https://testpovilasstore.mystagingwebsite.com
WC Version: 9.1.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.21
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.0.2
WC Database Prefix: wp_
Total Database Size: 5.08MB
Database Data Size: 2.56MB
Database Index Size: 2.52MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.36MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
page: 7
post: 1
product: 25
product_variation: 11
shop_coupon: 4
shop_order_placehold: 146
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Bulk Discounts for WooCommerce: by Plugify – 2.0.2 (update to version 2.0.3 is available)
Code Snippets: by Code Snippets Pro – 3.6.5.1
Jetpack Protect: by Automattic - Jetpack Security team – 2.2.0
Jetpack: by Automattic – 13.7-a.1
Product Bundle Discount: by Codup – 1.1.4.1
Smart Product Quantity: by HighAddons – 1.0.6
Woo All Products For Subscriptions: by Woo – 5.0.5 (update to version 5.0.7 is available)
WooCommerce Beta Tester: by WooCommerce – 2.3.1
WooCommerce Stripe Gateway: by WooCommerce – 8.4.0
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 7.8.1 (update to version 7.9.1 is available)
Woo Product Bundles: by Woo – 7.2.0
WooCommerce Stripe Dev Tools: by  –
WooCommerce Subscriptions: by WooCommerce – 6.4.1
WooCommerce: by Automattic – 9.1.1 (update to version 9.1.2 is available)

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 5 MB

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /cart/ -  Contains the woocommerce/cart block
Checkout: #11 - /checkout/ -  Contains the woocommerce/checkout block
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### WooPayments ###

Version: 7.8.1
Connected to WPCOM: Yes
WPCOM Blog ID: 234565615
Account ID: acct_1PVtvXC2Xmo7UoLK
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://testpovilasstore.mystagingwebsite.com
Subscriptions-core Library Version: 7.2.0
Subscription Statuses: –
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###


### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Cash on delivery: products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### Product Bundles ###

Database Version: 7.2.0
Loopback Test: –
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-07-15 19:15:11 +00:00
Options: ✔
Notes: 75
Onboarding: skipped

### All Products for Woo Subscriptions ###

Template Overrides: –

### Action Scheduler ###

Canceled: 9
Oldest: 2024-07-02 08:15:21 +0000
Newest: 2024-07-12 06:41:10 +0000

Complete: 514
Oldest: 2024-06-27 19:16:15 +0000
Newest: 2024-07-15 07:15:05 +0000

Failed: 2
Oldest: 2024-06-27 19:19:28 +0000
Newest: 2024-06-28 08:05:06 +0000

Pending: 1
Oldest: 2024-07-15 12:39:26 +0000
Newest: 2024-07-15 12:39:26 +0000


### Status report information ###

Generated at: 2024-07-15 09:14:02 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by bozidarsevo**
Closes: #13324

## Description

@staskus noticed and created the issue #13324 where POS had the issue with orders and taxes being always added on top of products.

While debugging this I found that in `RemoteOrderSynchronizer` the app used `sanitizingLocalItems()` function which "Removes the `itemID`, `total` & `subtotal` values from local items.".

Since in POS we are not using `RemoteOrderSynchronizer` we were not calling `sanitizingLocalItems()` we had this issue where `total` and `subtotal` were sent with order items and therefor overriding amounts calculations.

By calling `sanitizingLocalItems()` in `POSOrderService` `syncOrder` function this is now fixed.

### Inclusive tax

- Enable "Yes, I will enter prices inclusive of tax" (WooCommerce -> Settings -> Tax -> Prices entered with tax)
- Enter POS mode
- Add 1 product to cart
- Check out
- Notice that the subtotal has the product amount without a tax and total has subtotal + tax, and the price of the product in the cart and product list has full price of the product (with tax)

Screenshot 2024-07-18 at 11 26 34

Simulator Screenshot - iPad Pro (11-inch) (4th generation) 17 2 - 2024-07-18 at 11 20 17

in order list:

IMG_0318

### Exclusive tax

- Enable "No, I will enter prices exclusive of tax" (WooCommerce -> Settings -> Tax -> Prices entered with tax)
- Enter POS mode
- Add 1 product to cart
- Check out
- Notice that the subtotal has the product amount without a tax and total has subtotal + tax, and the price of the product in the cart and product list is the same as the subtotal

Screenshot 2024-07-18 at 11 26 29

Simulator Screenshot - iPad Pro (11-inch) (4th generation) 17 2 - 2024-07-18 at 11 20 43

in order list:

IMG_0319

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/214">19.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Yosemite/Yosemite/Model/Extensions/Order+LocalItems.swift [hunk 1]
```diff
@@ -0,0 +1,43 @@
+/// Simple type to serve negative IDs.
```
Comment (bozidarsevo) [inline Yosemite/Yosemite/Model/Extensions/Order+LocalItems.swift:1]: Move LocalIDStore and sanitizingLocalItems to Yosemite so it can be easily used in POS and normal orders

File: WooCommerce/Classes/POS/Presentation/TotalsView.swift [hunk 2]
```diff
@@ -23,15 +23,15 @@ struct TotalsView: View {
                             VStack(spacing: Constants.totalsVerticalSpacing) {
                                 priceFieldView(title: "Subtotal",
                                                formattedPrice: totalsViewModel.formattedCartTotalPrice,
-                                               shimmeringActive: false,
-                                               redacted: false)
```
Comment (bozidarsevo) [inline WooCommerce/Classes/POS/Presentation/TotalsView.swift:27]: Added redaction and shimmering to subtotal

File: WooCommerce/Classes/POS/Presentation/TotalsView.swift [hunk 3]
```diff
@@ -23,15 +23,15 @@ struct TotalsView: View {
...
+                                               shimmeringActive: totalsViewModel.isShimmering,
+                                               redacted: totalsViewModel.isSubtotalFieldRedacted)
                                 Divider()
                                     .overlay(Color.posTotalsSeparator)
                                 priceFieldView(title: "Taxes",
                                                formattedPrice:
                                                 totalsViewModel.formattedOrderTotalTaxPrice,
                                                shimmeringActive: totalsViewModel.isShimmering,
-                                               redacted: totalsViewModel.isPriceFieldRedacted)
```
Comment (bozidarsevo) [inline WooCommerce/Classes/POS/Presentation/TotalsView.swift:34]: Renamed since it is used for tax

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift [hunk 4]
```diff
@@ -144,18 +148,6 @@ extension TotalsViewModel {
         }
     }
 
-    func calculateCartTotal(cartItems: [CartItem]) {
```
Comment (bozidarsevo) [inline WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:147]: Not used anymore

File: WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizer.swift [hunk 5]
```diff
@@ -545,30 +545,6 @@ private extension RemoteOrderSynchronizer {
 
 // MARK: Definitions
 private extension RemoteOrderSynchronizer {
-    /// Simple type to serve negative IDs.
```
Comment (bozidarsevo) [inline WooCommerce/Classes/ViewRelated/Orders/Order Creation/Synchronizer/RemoteOrderSynchronizer.swift:548]: https://github.com/woocommerce/woocommerce-ios/pull/13381/files#r1682567111

File: Yosemite/Yosemite/Model/Extensions/Order+LocalItems.swift (hunk 1 above)
Comment (staskus) [reply Yosemite/Yosemite/Model/Extensions/Order+LocalItems.swift:1]: Great that it can be reused by both 👍

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift [hunk 6]
```diff
@@ -23,6 +24,13 @@ public struct POSOrder {
     public let totalTax: String
     public let currency: String
     let items: [POSOrderItem]
+
+    public func subtotal(_ currencyFormatter: CurrencyFormatter) -> String {
```
Comment (staskus) [inline Yosemite/Yosemite/Tools/POS/POSOrderService.swift]: As we talked, local calculations are a sensitive area.

Could we reuse `OrderTotalsCalculator.itemsTotal` here, as it's done in `Orders` view?

**Review by staskus — COMMENTED** [review]
Works well! Thank you for moving some of the code for `Yosemite` for easier reusability. I left the question of whether we could do the same for Order calculations.

One more question.

Is there a reason we don't use `RemoteOrderSynchronizer.createOrderRemotely / updateOrderRemotely` instead of separate `POSOrderService` calls? I see it already calls `sanitizingLocalItems` the same way.

File: Yosemite/Yosemite/Model/Extensions/User+Roles.swift [hunk 7]
```diff
@@ -1,7 +1,7 @@
 import Foundation
 
 /// Convenient extension methods for User model to support role eligibility feature.
-extension User {
+extension User {//
```
Comment (staskus) [inline Yosemite/Yosemite/Model/Extensions/User+Roles.swift]:
```suggestion
extension User {
```

Comment (bozidarsevo) [reply Yosemite/Yosemite/Model/Extensions/User+Roles.swift]: Must have commited by accident.. I sometimes put // in files while I debug so I can easily just look at "changed" files and quickly switch between.. but I must have forgot to discard this in commit.. tnx!

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift (hunk 6 above)
Comment (bozidarsevo) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift]: Good idea! Will do!

Comment (bozidarsevo) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift]: Hm, the problem is that OrderTotalsCalculator works with Order and not POSOrder.. that is why I basically copied it..
I will look a bit more and see if we can reuse OrderTotalsCalculator.itemsTotal 👍

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift [hunk 8]
```diff
@@ -16,74 +17,14 @@ public struct POSCartItem {
     }
 }
 
-public struct POSOrder {
```
Comment (bozidarsevo) [inline Yosemite/Yosemite/Tools/POS/POSOrderService.swift:19]: I decided to remove `POSOrder` to avoid duplicate creation of objects when we go back and forth between `POSOrder` and `Order`

**Comment by bozidarsevo** [comment]
> Is there a reason we don't use `RemoteOrderSynchronizer.createOrderRemotely / updateOrderRemotely` instead of separate `POSOrderService` calls? I see it already calls `sanitizingLocalItems` the same way.

I am not sure at the moment, there was some reason.. I will try to find it! 👍

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift (hunk 8 above)
Comment (staskus) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift:19]: Interesting! 

I don't want to make this task too huge for you, so let me know if removing POSOrders and reusing all the logic of `RemoteOrderSynchronizer` doesn't make sense. I don't know a lot of the backstory.

File: WooCommerce/Classes/POS/Presentation/TotalsView.swift [hunk 9]
```diff
@@ -23,15 +23,15 @@ struct TotalsView: View {
                             VStack(spacing: Constants.totalsVerticalSpacing) {
                                 priceFieldView(title: "Subtotal",
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/Presentation/TotalsView.swift]: Non-blocker: Since we're editing this bit, we can make the title for "Subtotal" and "Taxes" `NSLocalizedString`s in an extension

File: WooCommerce/WooCommerceTests/POS/ViewModels/TotalsViewModelTests.swift [hunk 10]
```diff
@@ -43,10 +43,9 @@ final class TotalsViewModelTests: XCTestCase {
 
         await sut.syncOrder(for: [CartItem(id: UUID(), item: item, quantity: 1)], allItems: [item])
         XCTAssertNotNil(sut.order)
-        let order: Order = orderService.order(from: sut.order!)
 
         // When
-        _ = try await cardPresentPaymentService.collectPayment(for: order, using: .bluetooth)
+        _ = try await cardPresentPaymentService.collectPayment(for: sut.order!, using: .bluetooth)
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/POS/ViewModels/TotalsViewModelTests.swift]: In here we could avoid the force-unwrapping by failing the test if the order happens to be `nil`:
```suggestion
        guard let order = sut.order else {
            return XCTFail("Expected order. Got nothing")
        }
        _ = try await cardPresentPaymentService.collectPayment(for: order, using: .bluetooth)
```

Comment (bozidarsevo) [reply WooCommerce/WooCommerceTests/POS/ViewModels/TotalsViewModelTests.swift]: If the order is nil the test will fail in the line above:
`XCTAssertNotNil(sut.order)`

Comment (bozidarsevo) [reply WooCommerce/WooCommerceTests/POS/ViewModels/TotalsViewModelTests.swift]: But I can change it to this

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift [hunk 11]
```diff
@@ -23,16 +22,19 @@ final class TotalsViewModel: ObservableObject {
...
 
     // MARK: - Order total amounts
-
-    @Published private(set) var formattedCartTotalPrice: String?
+    var formattedCartTotalPrice: String? {
+        formattedPrice(totalsCalculator?.itemsTotal.stringValue, currency: order?.currency)
+    }
 
     var formattedOrderTotalPrice: String? {
         formattedPrice(order?.total, currency: order?.currency)
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:40]: Question: Just wondering, in `formattedOrderTotalPrice` and `formattedOrderTotalTaxPrice` should we log if there's an error if the order happens to be `nil`? Eg:
```
    var formattedOrderTotalPrice: String? {
        guard let total = order?.total, let currency = order?.currency else {
            DDLogError("Failed to ... ")
            return nil
        }
        return formattedPrice(total, currency: currency)
    }
```

(I'm not sure how expected are those to be nil while the order stuff happens, so maybe it's an overkill and not necessary 🤔 )

Comment (bozidarsevo) [reply WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:40]: If the order is still nil after syncing/updating then we will probably get one of the errors that we will handle with the unhappy path error views.
And since the order is initally nil we would log this once for sure and maybe have unnecessary error logs..

File: Yosemite/Yosemite/Model/Extensions/User+Roles.swift (hunk 7 above)
Comment (iamgabrielma) [reply Yosemite/Yosemite/Model/Extensions/User+Roles.swift]: > I sometimes put // in files while I debug so I can easily just look at "changed"

I do the same 😁

File: WooCommerce/WooCommerceTests/POS/ViewModels/TotalsViewModelTests.swift (hunk 10 above)
Comment (iamgabrielma) [reply WooCommerce/WooCommerceTests/POS/ViewModels/TotalsViewModelTests.swift]: Whatever you prefer is fine, def not a blocker 👍 , I generally just try to avoid force-unwrapping as while the case might be covered now, if we happen to change it in the future without realizing there's a force-unwrap we might introduce a potential crash.

**Review by staskus — APPROVED** [review]
👍 Thank you for the work of simplyfing the solution and reusing a lot of logic from the previous solution.

**Comment by iamgabrielma** [comment]
> > Is there a reason we don't use `RemoteOrderSynchronizer.createOrderRemotely / updateOrderRemotely` instead of separate `POSOrderService` calls? I see it already calls `sanitizingLocalItems` the same way.
> 
> I am not sure at the moment, there was some reason.. I will try to find it! 👍

Late to the party: I don't have full context but AFAU this was done to keep an additional layer of separation and intent of abstraction between app and POS, so we would directly use as less dependencies as possible and reduce the models required for POS to the simplest form, rather than using the existing models with all their properties and such (eg: there was no need for interactions with the synchronizer in the POS when creating/updating POSOrders).

That said, we've moved some things around since these decisions and if the service or other tools are in Yosemite, there is no reason to not use the existing models/methods.
