### PR TITLE
[Mobile Payments] Receipt Printing Controller is not shown

### LINKED ISSUE #7757: [Mobile Payments] `Print receipt` button does not print / open receipt
**Describe the bug**
When completing a payment with card, the merchant is presented with options to `Print receipt` and to `Save receipt and continue`. All what tapping `Print receipt` does is closing the popup:

https://user-images.githubusercontent.com/73365754/191749442-e92803d8-307e-49c9-9080-d8e1259c4924.MP4

(for the reference, Android app will open the PDF preview)

**To Reproduce**
1. Use a store with Stripe set up
2. Connect to card reader and collect a payment with a card
3. Once payment is completed, tap `Print receipt` ~> the popover will just close.

**Expected behavior**

I'd expect that after tapping `Print receipt` I'd either see the print options for this receipt:

photo_2022-09-22 15 42 34

Or at least see the preview with print button (which is available via `See Receipt` in product details):

photo_2022-09-22 15 42 34

**Mobile Environment**

- Device: iPhone 13 Pro
- iOS version: 16.0
- WooCommerce iOS version: 10.4.0.0 from TestFlight

### PR DESCRIPTION
**Pull request by toupper**
Closes: #7757 

## Description

Currently we do not show the `UIPrintInteractionController` when requested after collecting a payment, because we dismiss the underlying order flow `WooNavigationController` when showing it. As the system tries to present from there, we get this error:

`[Presentation] Attempt to present <UIPrintPanelNavigationController: 0x10c244c00> on <WooCommerce.WooNavigationController: 0x111808e00> (from <WooCommerce.WooNavigationController: 0x111808e00>) whose view is not in the window hierarchy.`

To solve it I make the receipt printing presentation _awaitable_, so we can close the order flow `WooNavigationController` **only** when the printing flow is finished, whatever its end result -success, error, cancel, etc.

## Testing instructions

1. Go to Menu.
2. Go to Payments.
3. Tap on Collect Payment.
4. Follow the flow and collect a payment with a card.
5. When the payment is collected successfully, tap on Print receipt.
6. The receipt printing controller should be presented -before it was not-.
7. Try different printing actions -email, save to notes, cancel, etc.-.
8. When done, it should dismiss the receipt printing flow, and then the order creation controller. (See attached video).

## Screenshots

https://user-images.githubusercontent.com/1864060/213214396-3b1e24e3-1434-494f-bf13-daccaf8404a4.MP4

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift [hunk 1]
```diff
@@ -110,27 +110,6 @@ final class LegacyCollectOrderPaymentUseCaseTests: XCTestCase {
     }
 
     // MARK: Success alert actions
-
-    func test_printing_receipt_from_collectPayment_success_alert_tracks_receiptPrintTapped_event() throws {
```
Comment (toupper) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/LegacyCollectOrderPaymentUseCaseTests.swift:114]: I deleted this test case because we have it already implemented in `ReceiptActionCoordinatorTests`, where it feels more natural.

**Review by joshheald — APPROVED** [review]
Works well. Good spot on removing the duplicated test
🚢
