### PR TITLE
Stats: update Stats v4 Networking/Yosemite layers

### LINKED ISSUE #1156: Stats: update Stats v4 Networking/Yosemite layers after more API testing
There are a few gotchas when using Stats v4 API:
- **(NOTE: will double check, doesn't seem to be a problem anymore. might be a problem with previous `before` and `interval` values)** the forward slash in `path` param now must be escaped, which is not the case in v3 API. With the existing networking client using default encoding, we get the error below:
  - I couldn't really find a straightforward way to change the encoding, as Alamofire followed the recommendation from [RFC 3986 - Section 3.4](https://tools.ietf.org/html/rfc3986#section-3.4) that both the `?` and `/` are not percent escaped in query string parameters
```
{
    "error": "rest_invalid_param",
    "message": "Invalid parameter(s): before, interval"
}
```
- only specifying `before` and `per_page` params isn't enough, `after` is also needed. Otherwise, an unexpected amount of intervals could be returned in the response
- the `interval` param is `hour/day/week/month/year`
- the `after`/`before` values are ISO8601 compliant dates

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1156 

## Changes
- Added `after` field to Stats v4 API request
- Updated raw value of `StatsGranularityV4` enum that represents the interval granularity in Stats v4
- Added `StatsStoreV4` as a store in authenticate state
- Added Storage level alias definition for each Stats v4 model
- Updated `after`/`before` values to ISO8601 compliant dates

## Testing
Unit tests! (no direct app layer changes)

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: Networking/Networking/Remote/OrderStatsRemoteV4.swift [hunk 1]
```diff
@@ -17,10 +17,12 @@ public final class OrderStatsRemoteV4: Remote {
     ///
     public func loadOrderStats(for siteID: Int,
                                unit: StatsGranularityV4,
+                               earliestDateToInclude: String,
```
Comment (mindgraffiti) [inline Networking/Networking/Remote/OrderStatsRemoteV4.swift]: love this. So clear to understand what date is expected.
