### PR TITLE
[Mobile Payments] Display connecting-to-reader failures

### LINKED ISSUE #4923: [Mobile Payments] Inconsistent discovery state when attempting to connect to a powered off reader
**Describe the bug**
When you attempt to connect to a reader and the reader is gone, the app is left in an inconsistent state, and needs to force-quit before it can connect again.

**To Reproduce**
1. Go to Settings > In-Person Payments > Manage Card Reader
2. Tap on Connect Reader
3. When a reader is found, turn off the reader
4. Tap Connect

You end up back and the card reader settings screen, but from now on, every time you try to connect you get an error saying that the SDK is busy with another command

### PR DESCRIPTION
**Pull request by allendav**
Partially addresses #4947 
Closes #4923 

To test:
- Tap on Settings
- Tap on In-Person Payments, then Manage card reader
- When the Connect your card reader view appears, tap on Connect Card Reader
- The “Scanning for reader” modal should appear
- Power on a reader at this point
- (If the reader has previously connected, it will autoconnect. You’ll need to disconnect it and repeat the process)
- When the “Do you want to connect to reader xxx” modal appears, power off the reader by holding its power button down at least 5 seconds
- Tap on “Connect to Reader”
- The “Connecting to reader” modal will display
- After about 10 seconds, the “We couldn’t connect your reader” modal will display
- Tap “Cancel”
- You should be back on the Connect your card reader view now
- Tap on Connect Card Reader
- The Scaning for reader modal should display
- Power on the reader
- The Do you want to connect to reader xxx” modal should appear
- power off the reader by holding its power button down at least 5 seconds
- Tap on “Connect to Reader”
- The “Connecting to reader” modal will display
- After about 10 seconds, the “We couldn’t connect your reader” modal will display
- Tap on “Try Again”
- The “Scanning for reader” modal should return
- Power on your reader
- NOTE: There is a bug here. The reader won’t be found. It looks like it may be a problem with the Stripe SDK: https://github.com/stripe/stripe-terminal-ios/issues/104#issuecomment-916285167 - The workaround follows:

- Cancel the Scanning for reader modal
- Tap on Connect Card Reader
- The Do you want to connect to reader xxx” modal should appear
- Tap on “Connect to Reader”
- The reader should now connect successfully

Screenshots:

Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift [hunk 1]
```diff
@@ -33,6 +33,11 @@ final class CardReaderConnectionController {
         ///
         case connectToReader
 
+        /// A failure occurred while connecting. The search may continue or be canceled. At this time we
+        /// do not present the detailed error from the service.
+        ///
+        case connectingFailed
```
Comment (ctarda) [inline WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: In preparation for the 2.0 SDK it might be a good idea to add either an extra case or make the view model title customizable, or pass the error as an associated value, for when the connection fails and we want to present a custom error message, instead of a standard one. "We couldn't connect, try again"

I have seen two error cases that might be worth treating with a custom error message:
1. The SDK detects a mandatory update, and the reader battery is below 50%. We should notify users that they need to charge their battery (pdfdoF-7i-p2#comment-327)
2. On the first connection to an unknown reader, the user needs to enter in the mobile app a 6 digit number located in the back of the reader. If the user enters the wrong number, the connection fails. I think this one might deserve an specific error as well

Comment (allendav) [reply WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: I agree with presenting more actionable dialogs, but I think extending and testing with these SDK 2 messages should wait for a later PR (it will be hard to test that we got-it-right with SDK 1). How about I open a separate issue for that?

**Comment by allendav** [comment]
The bug where a powered-off-and-on-again reader is not easily re-discovered appears to be in the Stripe Terminal SDK. See this issue: https://github.com/stripe/stripe-terminal-ios/issues/104#issuecomment-916285167

File: WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift (hunk 1 above)
Comment (allendav) [reply WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: On further discussion, I'll add an associated value we can leverage later.

Comment (allendav) [reply WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: Added associated value in https://github.com/woocommerce/woocommerce-ios/pull/4957/commits/0db9ef0b4bc11efbf1857839a089867dc84f323f

**Review by ctarda — APPROVED** [review]
Code looks great. :shipit:

**Review by ghost — APPROVED** [review]

**Comment by koke** [comment]
I'll just note that, while this new modal is showing, the discovery process would still be active. So if you turn on a second reader, the app would present the option to connect to it, even without tapping Try again. Also, I would probably understand Try again as trying to connect to the same reader, not trying to scan for readers again.
