### PR TITLE
Core Data: Attempt recovery when database is corrupted

### LINKED ISSUE #14451: [Crash] Crash with corrupted database from BlazeCampaignDashboardViewModel
Sentry Issue: [WOOCOMMERCE-IOS-1NF3](https://a8c.sentry.io/issues/5882975158/?referrer=github_integration)

```
Error Domain=NSSQLiteErrorDomain Code=11 "(null)" UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/AE242CE1-AA09-4BEA-BD8D-89FB37D28DA0/Documents/WooCommerce.sqlite, NSSQLiteErrorDomain=11}
```

Sample stack trace:
```
AutomatticTracks    0x104be7170  CrashLogging.logError (CrashLogging.swift:204)
  WooCommerce         0x102e68354  WooCrashLoggingStack.logError (WooCrashLoggingStack.swift:57)
  WooCommerce         0x102e68354  WooCrashLoggingStack (<compiler-generated>:56)
  WooCommerce         0x102e68354  BlazeCampaignDashboardViewModel.configureResultsController (BlazeCampaignDashboardViewModel.swift:331)
  WooCommerce         0x1032d549c  BlazeCampaignDashboardViewModel.init (BlazeCampaignDashboardViewModel.swift:125)
  WooCommerce         0x1032d83ac  BlazeCampaignDashboardViewModel.init (ServiceLocator.swift)
  WooCommerce         0x1032d83ac  BlazeCampaignDashboardViewModel.init (<compiler-generated>:112)
  WooCommerce         0x1032d83ac  BlazeCampaignDashboardViewModel.init (<compiler-generated>:112)
  WooCommerce         0x1032d83ac  $s11WooCommerce31BlazeCampaignDashboardViewModelC6siteID6stores14storageManager9analytics23blazeEligibilityCheckerACs5Int64V_8Yosemite06StoresL0_p7Storage0tL4Type_p0A10Foundation9Analytics_pAA0coP8Protocol_ptcfCTf4nnnnen_nAA0coP0C_Tgm5 (BlazeCampaignDashboardViewModel.swift:126)
  WooCommerce         0x1032d83ac  BlazeCampaignDashboardViewModel.__allocating_init (<compiler-generated>:112)
  WooCommerce         0x1032d83ac  DashboardViewModel.init (DashboardViewModel.swift:124)
  WooCommerce         0x1032d8ef0  DashboardViewModel.init (DashboardViewModel.swift)
  WooCommerce         0x1032d8ef0  DashboardViewModel.init (<compiler-generated>:105)
  WooCommerce         0x1032d8ef0  DashboardViewModel.init (<compiler-generated>:105)
```

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #14451 

## Description

We got reports from Sentry about users with corrupted databases and could not recover from the failure unless they reinstalled the app. This PR implements the recovery for this scenario by dropping the database so users can restart the app from scratch.

Note: 
- When the persistent container is destroyed, users are likely to get crashes if they manage to fetch any data before because those objects will no longer be relevant. The app will crash in this case, so instead, I'm forcing the app to crash immediately after dropping the database. The app is already crashing when the `save` operation fails anyway.
- After dropping the database, I'm sending the `StorageManagerDidResetStorage` notification. This is necessary to clear the timestamp of the Performance or Top Performers dashboard cards or the Orders list if any of them finished loading data before. This is to ensure that data can be loaded immediately after relaunching the app.

## Steps to reproduce

It's not straightforward to manually force the database to crash. I tried a few ways to update the database files but Core Data still managed to recover.

The most consistent way is to put a breakpoint at `try context.save()` line in `CoreDataManager.saveStorageIfNeeded` and force the database dropping using command: `e dropDatabaseAndExit(with: NSError(domain: "Test", code: 11))`.

After this, the app will crash. Relaunch the app and confirm that data can be loaded normally.

## Testing information

- Unit test: I added a test for `CoreDataManager` when the database is corrupted.
- Manual test: Confirmed that data in My Stores, Orders, Products, and Menu tab are loaded correctly after dropping the database and relaunching the app.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/235">21.5</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift [hunk 1]
```diff
@@ -120,7 +120,7 @@ extension NSManagedObjectContext: StorageType {
         do {
             return try existingObject(with: objectID) as? T
         } catch {
-            DDLogError("Error loading Object [\(T.entityName)]")
+            DDLogError("Error loading Object [\(T.entityName)]: \(error)")
```
Comment (itsmeichigo) [inline Storage/Storage/Extensions/NSManagedObjectContext+Storage.swift:123]: Updated the log for more useful information.

File: Storage/StorageTests/CoreData/CoreDataManagerTests.swift [hunk 2]
```diff
@@ -309,6 +343,27 @@ private extension CoreDataManagerTests {
...
+            for i in 0..<min(100, data.count) {
+                data[i] = 0xFF // Overwrite with invalid data
+            }
+            // Write the corrupted data back to the file
+            try data.write(to: walURL)
+            print("Database corrupted successfully")
+        } catch {
+            print("Error corrupting database: \(error)")
+        }
+    }
```
Comment (pmusolino) [inline Storage/StorageTests/CoreData/CoreDataManagerTests.swift:366]: Nit: As mentioned also on Slack, what do you think about corrupting also the main .sqlite database and not only the WAL? Doing a quick research, it seems that if SQLite detects that the WAL file is corrupted or inconsistent, it may discarded and recreated (and then, I imagine it will be recreated from the main .sqlite file). In these cases, any corruption introduced into the WAL file may be ignored or repaired by SQLite.
I think this approach can be closer to a real scenario, compared to deleting the main sqlite db.

**Review by pmusolino — APPROVED** [review]
Just a nit, but it looks good to me :shipit:

File: Storage/StorageTests/CoreData/CoreDataManagerTests.swift (hunk 2 above)
Comment (itsmeichigo) [reply Storage/StorageTests/CoreData/CoreDataManagerTests.swift:366]: My assumption of the corrupted database case in real life is when a user interrupts the migration step, which is more likely to happen when Core Data is updating the WAL file. When they try to use the app again, the SQLite file is still fine so the persistent container can still load, but when they trigger fetching/saving, the operation fails since the WAL file is not in sync with the SQLite.

During the work on this test, I tried corrupting the SQLite file at first, but the manager would attempt to recover since the loading of the persistent container fails, and the saving would be successful afterward. 

Let's keep this test for now, we can always revisit it if it no longer works or if we find new clues about the database corruption. WDYT @pmusolino?

Comment (pmusolino) [reply Storage/StorageTests/CoreData/CoreDataManagerTests.swift:366]: Sounds good @itsmeichigo 👍

File: Storage/Storage/CoreData/CoreDataManager.swift [hunk 3]
```diff
@@ -303,6 +302,37 @@ extension CoreDataManager {
...
+// MARK: Helpers
+private extension CoreDataManager {
+
+    func saveStorageIfNeeded(_ storage: StorageType) {
+        let context = storage as! NSManagedObjectContext
+        guard context.hasChanges else {
+            return
+        }
+        do {
+            try context.save()
```
Comment (selanthiraiyan) [inline Storage/Storage/CoreData/CoreDataManager.swift:314]: 👋 @itsmeichigo , Does calling `context.save()` mean we no longer call the `saveIfNeeded()` from `NSManagedObjectContext+Storage` file? We rely on that method to enforce correct context usage for write operations, right? Please correct me if I am missing something.

Comment (itsmeichigo) [reply Storage/Storage/CoreData/CoreDataManager.swift:314]: Hi @selanthiraiyan - since my last change in the Core Data stack, I don't expect anyone to use `saveIfNeeded` directly, but to use `performAndSave` instead - which handles the write operations on the background thread.

`saveIfNeeded` was only kept because we have a lot of unit tests relying on it - I even marked it as deprecated in `MockStorageManager`.

Comment (selanthiraiyan) [reply Storage/Storage/CoreData/CoreDataManager.swift:314]: Thanks, @itsmeichigo!

Sorry, I am trying to understand this. I raised this question because in `performAndSave` method the following [lines 1](https://github.com/woocommerce/woocommerce-ios/pull/14961/files#diff-f43a023c555398d48483bd4415451807f83ae569c2b166696c6bfc8c1fee14e6L114-L115) and [lines 2](https://github.com/woocommerce/woocommerce-ios/pull/14961/files#diff-f43a023c555398d48483bd4415451807f83ae569c2b166696c6bfc8c1fee14e6L141) were using `saveIfNeeded()` before we started calling `saveStorageIfNeeded()` instead. 🤔 

Did we miss replacing those `saveIfNeeded()` calls from `performAndSave` method in the past while planning to deprecate the method?

Comment (itsmeichigo) [reply Storage/Storage/CoreData/CoreDataManager.swift:314]: I wanted to deprecate **direct access** to that method and use `performAndSave` to ensure the correct thread usage. Now that we use the new method to handle saving inside of `performAndSave`, we can remove the method. I added a commit for that here: 122e1c6ae59bb446824701ef6f792327aa2c35c9. Let me know if you have any other questions! @selanthiraiyan

**Review by selanthiraiyan — APPROVED** [review]
Thanks for working on this, Huong!

The code changes LGTM and works as expected. :shipit:
