### PR TITLE
[Woo POS] Improve itemlist state representation and fix glitches

### LINKED ISSUE #14251: [Woo POS] Pagination UI improvement: Update animation on pull-to-refresh
From review on https://github.com/woocommerce/woocommerce-ios/pull/14226#pullrequestreview-2401010336

> during pull-to-refresh, the product list view along with its scroll indicator seems to move around

https://github.com/user-attachments/assets/e3354e15-2e8c-4897-a738-b079799a64f6

This most likely comes from not considering any specific animation when the state changes to `.loading`,  as now we're just performing an easeInOut for `.isInitialLoading` on `PointOfSaleDashboardView`: 

```
.animation(.easeInOut, value: viewModel.isInitialLoading)
```

> The spinner is overlapping with the fading non-simple products notice briefly

Since the banner is temporary and seems to be going away with the new design iteration, let's keep this in the backlog for now.

### LINKED ISSUE #14350: [Woo POS] Improve ItemListState representation of loading/loaded/empty to include previously loaded orders on loading

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #14350
Closes: #14251 

## Description

This PR removes uses of the `items` array and `itemsPublisher` from the `ItemListViewModel`. This is in preparation for architecture changes to move this state to the new Aggregated Model

The only remaining use of the `items` array is from the dashboard, where it's used for creating the order. We'll remove that in a future commit.

Instead, we rely on the ItemListState, which includes items when they should be shown.

As part of this work I've had to change the various pagination/loading/refresh behaviours to use the new source of truth for items, and along the way I've fixed some glitches

- Pull to refresh now leaves the simple products banner in place (arguably the items should remain too, but I've not done that)
- There's no animation glitch on refresh #14251 
- The ghost cell does eventually go away now (though it could still do with one less load cycle)

## Steps to reproduce

1. Launch the app and go to POS
2. Observe that the initial loading state is shown
3. When the items load, observe that they're shown correctly
4. Scroll to the bottom of the list; observe that the next page is loaded
5. Pull to refresh; observe that the list refreshes without glitches

Test with a site that has no simple products; observe that the full-screen empty state is shown.

Test with the products endpoint on a network breakpoint, and abort the request; observe that the error state is shown and can be refreshed correctly.

## Testing information

This refactor should be limited to the display of the itemlist, but it's worth also checking a full checkout including order editing after the first checkout tap, because the `items` array is used for building the order.

I've tested this with the above scenarios on an iPad Air running iOS 17.7

## Screenshots

https://github.com/user-attachments/assets/4b2001c8-c686-4648-902b-fbffd35492a3

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift [hunk 1]
```diff
@@ -14,12 +14,12 @@ struct ItemListView: View {
...
             switch viewModel.state {
-            case .empty, .error:
+            case .initialLoading, .empty, .error:
                 // These cases are handled directly in the dashboard, we do not render
                 // a specific view within the ItemListView to handle them
                 EmptyView()
-            case .initialLoading, .loading, .loaded:
-                listView(viewModel.items)
+            case .loading(let items), .loaded(let items):
+                listView(items)
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/Presentation/ItemListView.swift:22]: Just wondering: Loading an EmptyView for several cases here is something that always felt off and mostly driven by design changes regarding what to show full-screen vs partial-screen. Do you know at this point if this is something we'll be changing with the re-architecture?

File: WooCommerce/Classes/POS/ViewModels/ItemListState.swift [hunk 2]
```diff
@@ -0,0 +1,46 @@
+import protocol Yosemite.POSItem
+
+enum ItemListState: Equatable {
+    case empty
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/ItemListState.swift:4]: Question: Is worth to keep an `.empty` case? Or would `.loaded([])` suffice?

File: WooCommerce/Classes/POS/ViewModels/ItemListState.swift [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    case initialLoading
+    case loading(_ currentItems: [POSItem])
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/ItemListState.swift:6]: Question: I'm not sure to understand why we're passing the items as associated value to the `.loading` state. From this [commit](https://github.com/woocommerce/woocommerce-ios/pull/14362/commits/651b3bf87b61951f7bc7063ccf6dd712f783957d) I understand that it's only temporary and we'll just rely on state instead?

> "Adding the `currentItems` will allow us to avoid keeping the list content separately, and instead build the list based only on this enum."

File: WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift [hunk 4]
```diff
@@ -185,11 +185,11 @@ private extension PointOfSaleDashboardViewModel {
...
-        Publishers.CombineLatest(itemListViewModel.statePublisher, itemListViewModel.itemsPublisher)
-            .sink { [weak self] state, items in
+        itemListViewModel.statePublisher
+            .sink { [weak self] state in
                 guard let self = self else { return }
 
-                self.isInitialLoading = (state == .initialLoading && items.isEmpty)
+                self.isInitialLoading = state == .initialLoading
 
                 switch state {
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift:194]: Not sure if this is in your radar, and not for this PR, but I'm thinking we can improve this and have a more solid state by not relying on Published booleans, and instead have a dashboard state enum?

**Review by iamgabrielma — APPROVED** [review]
LGTM :shipit: 

I couldn't replicate the case for the ghost cell eventually disappearing when we reach the end of the infinite scroll, it always remains there, but I see it working on your recording. Not really part of this PR, but from what I see the state keeps refreshing when we've reached the end of the list, so it keeps switching between setting `isLoadingAfterInitialLoad` to false, and then true, which renders the `GhostItemCardView` indefinitely. I can tackle this separately, just asking in case you've experienced a different behaviour.

Tested on:

- Simulated: iPad Air 11 - iOS 17.5
- iPad Pro 12.9 - iOS 17.6.1

✅ Pull to refresh visual glitch is no longer there
✅ Banner remains if we pull to refresh
❌ The ghost cell does eventually go away
✅ A site that has no simple products; the full-screen empty state is shown.
✅ The error state is shown and can be refreshed correctly.

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/ItemListView.swift:22]: I don't think it's reasonable to avoid it with our current design, but nor is it a big deal that we use an empty view... 

Even if we made the ItemListView responsible for showing the full screen views as well, which would be nice, it would probably need to do them using a separate view modifier that the Dashboard actually presents the contents of (like `posModal`)

File: WooCommerce/Classes/POS/ViewModels/ItemListState.swift (hunk 2 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/ViewModels/ItemListState.swift:4]: I think it's better to keep it. Empty and loaded with items are two different screens, and it's cleaner everywhere if we don't have to check whether the array is empty when we get a loaded state.

File: WooCommerce/Classes/POS/ViewModels/ItemListState.swift (hunk 3 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/ViewModels/ItemListState.swift:6]: No, it's not temporary.

We will just rely on `state`, and remove the `@Published var items`, but to do that we need to keep the `currentItems` in the loading case.

They're used to continue showing items in the list while we show the loading indicator at the same time.

File: WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift (hunk 4 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift:194]: Yes, removing the extra flags is exactly the sort of state cleanup I'd like to make. We need to use single sources of truth where possible.

I think in this case we may just be able to rely directly on the ItemListState from the dashboard, once it's in the aggregate model. A dashboard state might be cleaner, we'll see when we get to it, but it does potentially go against the idea of having a single source of truth for the initialLoading state. We can have convenience wrappers though, so it's not a firm no.

**Comment by joshheald** [comment]
@iamgabrielma thanks for the review.

> I couldn't replicate the case for the ghost cell eventually disappearing when we reach the end of the infinite scroll, it always remains there, but I see it working on your recording. Not really part of this PR, but from what I see the state keeps refreshing when we've reached the end of the list, so it keeps switching between setting `isLoadingAfterInitialLoad` to false, and then true, which renders the `GhostItemCardView` indefinitely. I can tackle this separately, just asking in case you've experienced a different behaviour.

Strange, but yeah I definitely see it disappear eventually. There may be some iOS differences? But mine is on iOS 17.7 so not far away from your versions...
