### PR TITLE
Shipping settings: Comma as decimal separator.

### LINKED ISSUE #6567: Product details: Set up package dimensions with comma as decimal point creates dimensions without decimal point
**Describe the bug**
When a device's region uses commas as decimal points, setting up package dimensions with decimal points ends up with dimensions without decimal points.

**To Reproduce**
0. Change the device's region to a region that uses commas as decimal points.
1. Navigate to the Products tab
2. Select the "+" button and choose the physical product type
3. Fill in basic details for the product: title, price.
4. Select "Add more details" > "Shipping". Enter decimal values for the dimensions and save changes 
5. Save or publish the product. Notice that the dimensions are displayed without decimal points.

**Screenshots**
| Editing | Result |
| ------ | ----- |
|  |  |

**Expected behavior**
The values for the dimensions should be correct with decimal points.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 Pro
- iOS version: iOS 15.4
- WooCommerce iOS version: 8.9

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #6567

### Description
While editing a product in iOS, if we use a comma as a decimal separator for shipping package dimensions, the decimal point is not saved in the backend, upon saving the product. The backend ignores the comma and saves the number.

This PR attempts to solve the issue by,

- Always convert the weight and package dimensions to the device's locale before displaying. 
- The weight and package dimensions are converted back to the US locale before sending the request to API. This ensures that the API saves the decimal point information.

More details about this approach at p2 post - p91TBi-8kO-p2

### Testing instructions
1. Change the device's region to a region that uses commas as decimal points. (Vietnam for example)
1. Navigate to the Products tab.
1. Select the "+" button and choose the physical product type
1. Fill in basic details for the product: title, price.
1. Select "Add more details" > "Shipping". Enter decimal values for the weight and dimensions and save changes.
1. Save or publish the product. Notice that the weight and dimensions are displayed with proper decimal points, using comma as a decimal separator.

### Screenshots
CommaDecimalSeparator

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Extensions/NumberFormatter+Localized.swift [hunk 1]
```diff
@@ -29,4 +29,35 @@ extension NumberFormatter {
...
+    /// - Parameters:
+    ///     - using: The string to be localized.
+    ///     - from: The current `Locale` of the input string.
+    ///     - to: The `Locale` to be used for localizing the input string.
+    ///
+    /// - Returns: The input string localized to the target locale. Returns `nil` if the localization is unsucessful.
+    ///
+    static func localizedString(using string: String,
+                                from sourceLocale: Locale,
+                                to targetLocale: Locale) -> String? {
```
Comment (jaclync) [inline WooCommerce/Classes/Extensions/NumberFormatter+Localized.swift]: non-blocking 💭 : this feels a bit specific to product shipping values, like the assumption of no grouping separator. I was wondering if this function could be just for formatting the product shipping values instead of a generic function, so that we can encapsulate the logic for other assumptions like the API using US locale in `DefaultProductFormTableViewModel` below:

```swift
func localizedNumber(_ string: String) -> String? {
            // API uses US locale for weight and shipping dimensions
            let usLocale = Locale(identifier: "en_US")
            return NumberFormatter.localizedString(using: string, from: usLocale, to: locale)
}
```

Like this function could be `static func localizedShippingValueString(using string: String, to targetLocale: Locale) -> String?` and we can set the US locale in L48 below. Then anywhere we want to show localized shipping values, like in both product form and `ProductShippingSettingsViewModel`, we can use this helper function to do so. WDYT?

Comment (jaclync) [reply WooCommerce/Classes/Extensions/NumberFormatter+Localized.swift]: I saw that later in the PR a reverse conversion is needed in `func formattedForAPI(fromLocale: Locale)`. Maybe the current `static func localizedString` could be kept this way as private, and having two public functions like `static func localizedShippingValueString` and `static func unlocalizedShippingValueString` for conversions in two ways?

Keeping these helper function(s) in a separate struct/class could also be nice to not add too many functionalities to `NumberFormatter` 😄

File: WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModelTests.swift [hunk 2]
```diff
@@ -119,4 +119,40 @@ final class DefaultProductFormTableViewModelTests: XCTestCase {
             XCTFail("Cell not found")
         }
     }
+
+    func test_shipping_settings_row_displays_localized_weight_and_dimensions() {
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModelTests.swift:123]: nice tests!

**Review by jaclync — APPROVED** [review]
Works great and code LGTM! :shipit: Just a non-blocking thought on the localization helper, would just like to hear your thoughts!

File: WooCommerce/Classes/Extensions/NumberFormatter+Localized.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/Extensions/NumberFormatter+Localized.swift]: > Keeping these helper function(s) in a separate struct/class could also be nice to not add too many functionalities to NumberFormatter

💯 

I was trying to think of ways to make this better, but I didn't think about totally moving it outside of `NumberFormatter`. This is a great suggestion. Thank you! 🙇

**Comment by selanthiraiyan** [comment]
@jaclync I have moved the localization code out of `NumberFormatter` and into its own file. Thanks again for your suggestion. 🙏 

The PR is now ready for another look.

**Review by jaclync — APPROVED** [review]
Great work, and it still tests well! :shipit:
