### PR TITLE
[Mobile Payments] Retry when a payment capture fails

### LINKED ISSUE #4210: [Mobile Payments] Try again
The "Try again" button in the error modal does nothing.

See OrderDetailsViewController.collectPaymentForCurrentOrder()

### LINKED ISSUE #4228: [Mobile Payments] Error modal alerts do not show the reason for the error
The error modal alert when a payment capture fails does not show the reason for the error:

### PR DESCRIPTION
**Pull request by ctarda**
Closes #4210 , closes #4228

⚠️ This PR is against the feature branch implementing support for Card Present Payments, not against develop ⚠️

Sorry, this is a long PR, but most of the diff is because I have added unit tests for the view models backing the modal alerts, which were missing. 

Also, the copy of the retry button in the error alert is truncated. We have a ticket for that: #4222 

## Changes
* Add a new view model to back an error modal alert that does not retry.
* Add logic to retry a failed payment capture: 
1. Cancelling the previous payment capture
2. Starting a new payment capture after cancelling the previous one succeeds
3. Cancelling the whole process if cancelling the previous payment fails.
* Touch the error modals to display the error localized description.

There is the potential of entering an endless loop if capturing a payment fails, and a retry fails. I think we should add a "dismiss and do not not do anything"  button to the "error with retry" modal. I logged #4227 for that.

## How to test
Testing requires:

1. Setting up a store for Card Present Payment Testing (also P91TBi-4BH-p2 for more specific instructions)
2. WCPay 2.4.0

* Checkout the branch
* Connect to a reader
* Navigate to an order eligible for CPP.
* Wait a couple of seconds to make sure there are no lingering network requests, otherwise the order details screen will transition to a "no network" error screen, which is fine, but makes testing this PR a bit annoying

* Switch on airplane mode. 
* Tap "Collect payment". An error modal should be presented, because there is no network connection. The button and the error description are 😬 . We have #4222 and #4176 for that.
* Tap "retry", still in airplane mode. There should be a new alert modal. Tapping the button in the new modal should dismiss it.
* Deactivate airplane mode. Tap Collect Payment again. The payment collection should proceed forward and succeed (and the order notes should be updated).

There is one edge case we are not covering:
* Switch on airplane mode. 
* Tap "Collect payment". An error modal should be presented, because there is no network connection. The button and the error description are 😬 . We have #4222 and #4176 for that.
* Deactivate airplane mode while the modal alert is active
* Tap retry.  The payment collection could proceed forward and succeed, but there is a second error alert. After dismissing the second alert, tapping "Collect payment" again should work. We can add a ticket for this if we want to.

Activating airplane mode was the simplest way I could think of to make the payment collection process fail. If you know of another way to make that fail, by all means, try that as well! 

Update release notes:
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift [hunk 1]
```diff
@@ -0,0 +1,61 @@
+import UIKit
+
+/// Modal presented on error
+final class CardPresentModalNonRetryableError: CardPresentPaymentsModalViewModel {
```
Comment (ctarda) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift:4]: This is the new view model that we'd use for an error that can not be retried.

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift [hunk 2]
```diff
@@ -623,6 +623,17 @@ private extension OrderDetailsViewController {
         }
     }
 
+    private func retryCollectPayment() {
+        self.viewModel.cancelPayment { [weak self] result in
```
Comment (ctarda) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift]: We cancel the previous payment and start a new one from scratch. 

If the cancellation of the previous payment fails, we just present a modal error that does not allow a retry. I can't think of a better way to handle this, retrying again is a possibility if users tap the "collect payment" button

File: WooCommerce/WooCommerce.xcodeproj/project.pbxproj [hunk 3]
```diff
@@ -2304,6 +2315,17 @@
 		CEEC9B5F21E79CAA0055EEF0 /* FeatureFlagTests.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = FeatureFlagTests.swift; sourceTree = "<group>"; };
 		CEEC9B6221E79EE00055EEF0 /* AppRatingManager.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppRatingManager.swift; sourceTree = "<group>"; };
 		CEEC9B6521E7C5200055EEF0 /* AppRatingManagerTests.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppRatingManagerTests.swift; sourceTree = "<group>"; };
+		D802541E2655137A001B2CC1 /* CardPresentModalNonRetryableError.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = CardPresentModalNonRetryableError.swift; sourceTree = "<group>"; };
```
Comment (ctarda) [inline WooCommerce/WooCommerce.xcodeproj/project.pbxproj:2318]: From here down, it's just unit tests for all the view models associated with the modal alerts.

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift [hunk 4]
```diff
@@ -623,6 +623,17 @@ private extension OrderDetailsViewController {
         }
     }
 
+    private func retryCollectPayment() {
+        viewModel.cancelPayment { [weak self] result in
+            switch result {
+            case .failure(let error):
+                self?.paymentAlerts.nonRetryableError(from: self, error: error)
```
Comment (ctarda) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/OrderDetailsViewController.swift:630]: This is were the edge case mention in the PR description is: if there is a failure the fist time we attempt to cancel the previous payment attempt, we always transition to the non returnable alert.

If the first attempt to collect the payment failed because there is not a valid internet connection, the attempt to cancel the previous payment fails because we never got to even create a payment intent. 

If the internet connection comes back in between the first error and the time we hit retry, we would not be aware of it at this point, so we can not swallow the second error

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+private extension CardPresentModalNonRetryableError {
+    enum Localization {
+        static let paymentFailed = NSLocalizedString(
+            "Payment failed",
+            comment: "Error message. Presented to users after a collecting a payment fails"
+        )
+
+        static let tryAgain = NSLocalizedString(
+            "Dismiss",
+            comment: "Button to try to dismiss. Presented to users after a collecting a payment fails"
```
Comment (allendav) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift]: tryAgain -> closeLabel or something

to try to -> to

after a collecting -> after collecting

File: WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift [hunk 6]
```diff
@@ -48,6 +48,17 @@ final class OrderDetailsPaymentAlerts {
         modalController?.setViewModel(viewModel)
     }
 
+    func nonRetryableError(from: UIViewController?, error: Error) {
+        let viewModel = nonRetryableErrorViewModel(amount: amount, error: error)
+        let newAlert = CardPresentPaymentsModalViewController(viewModel: viewModel)
+        modalController?.setViewModel(viewModel)
```
Comment (allendav) [inline WooCommerce/Classes/ViewModels/Order Details/OrderDetailsPaymentAlerts.swift]: The next line blows this away kinda. Maybe `guard` on `nil` `modalController` and then call this then `return`? Similar to how `setViewModelAndPresent` works in `CardReaderSettingsAlerts`?

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalConnectingToReaderTests.swift [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+        XCTAssertNil(viewModel.bottomSubtitle)
+    }
+}
+
+
+private extension CardPresentModalConnectingToReaderTests {
+    enum Expectations {
+        static var image = UIImage.cardReaderConnecting
+    }
+}
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalConnectingToReaderTests.swift:55]: Thank you for adding these. I didn't even think to enforce the labels with a unit test. I'll do that next time.

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+
+    func test_bottom_title_is_not_nil() {
+        XCTAssertNotNil(viewModel.bottomTitle)
+    }
+
+    func test_bottom_subTitle_is_not_nil() {
+        XCTAssertNotNil(viewModel.bottomSubtitle)
+    }
+
+    func test_primary_button_dispatched_canel_action() throws {
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift]: canel -> cancel

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+        let storesManager = MockStoresManager(sessionManager: .makeForTesting(authenticated: true))
+        storesManager.reset()
+
+        ServiceLocator.setStores(storesManager)
+
+        assertEmpty(storesManager.receivedActions)
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift:57]: Ooooooh. Nice.

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+        viewModel.didTapPrimaryButton(in: nil)
+
+        XCTAssertEqual(storesManager.receivedActions.count, 1)
+
+        let action = try XCTUnwrap(storesManager.receivedActions.first as? CardPresentPaymentAction)
+        switch action {
+        case .cancelPayment(onCompletion: _):
+            XCTAssertTrue(true)
+        default:
+            XCTFail("Primary button does not dispatch .cancelPayment action")
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalReaderIsReadyTests.swift]: does not -> failed to

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalSuccessTests.swift [hunk 11]
```diff
@@ -0,0 +1,90 @@
...
+            self?.didTapPrint = true
+        }
+    }
+
+    func emailReceipt() -> () -> Void {
+        return { [weak self] in
+            self?.didTapEmail = true
+        }
+    }
+}
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalSuccessTests.swift:89]: Can we test the auxiliary?

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalSuccessTests.swift [hunk 12]
```diff
@@ -0,0 +1,90 @@
...
+        static var amount = "amount"
+        static var image = UIImage.celebrationImage
+    }
+}
+
+
+private final class Closures {
+    var didTapPrint = false
+    var didTapEmail = false
+    var didTapNoThanks = false
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalSuccessTests.swift]: Not used - see below

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalTapCardTests.swift [hunk 13]
```diff
@@ -0,0 +1,80 @@
...
+
+    func test_bottom_title_is_not_nil() {
+        XCTAssertNotNil(viewModel.bottomTitle)
+    }
+
+    func test_bottom_subTitle_is_not_nil() {
+        XCTAssertNotNil(viewModel.bottomSubtitle)
+    }
+
+    func test_primary_button_dispatched_canel_action() throws {
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalTapCardTests.swift]: canel -> cancel

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalTapCardTests.swift [hunk 14]
```diff
@@ -0,0 +1,80 @@
...
+        viewModel.didTapPrimaryButton(in: nil)
+
+        XCTAssertEqual(storesManager.receivedActions.count, 1)
+
+        let action = try XCTUnwrap(storesManager.receivedActions.first as? CardPresentPaymentAction)
+        switch action {
+        case .cancelPayment(onCompletion: _):
+            XCTAssertTrue(true)
+        default:
+            XCTFail("Primary button does not dispatch .cancelPayment action")
```
Comment (allendav) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalTapCardTests.swift]: does not -> failed to

**Review by allendav — APPROVED** [review]
Tests well. Instead of using Airplane mode, I blocked and unblocked my iPad's access to the internet from my router. One recommended fix.

After blocking Internet access for my iPad:




After restoring Internet access for my iPad:

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalSuccessTests.swift (hunk 11 above)
Comment (ctarda) [reply WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CardPresentModalSuccessTests.swift:89]: Not really. It just calls dismiss in the view controller that is passed to it, as far as I know there is no way to test that unless we pass a closure to be assigned to that button via the constructor... and to be honest, at that point I'm not sure it'd worth it.

**Comment by ctarda** [comment]
Blocking access to the network for that device in the router is quite smart, nice!

Notice how we still need to do some work in the way we print the user facing errors: `The operation couldn't be completed` is not great. I logged #4235 

I pushed an update with your feedback, and I'll merge when CI is ✅
