### PR TITLE
Order list: fix truncated payment status label for large font sizes

### LINKED ISSUE #900: Order list: Status label is clipped for large font sizes
The status label is clipped for large font sizes. 

Simulator Screen Shot - iPhone 8 - 2019-04-23 at 08 53 56

### LINKED ISSUE #901: Order List: Switch vertical layout from a "two column" layout to a "two row layout" for large font sizes
Currently, the layout is of the cell describing an order is:

| Customer name | Order total |
| ---------------- | ----------- |
| A name | A price |

That makes customer names difficult to read when the font size is large.

We could consider changing the layout, when a large font is selected, to :

| Single column |
| -------------- |
| Customer name |
| Price |

Simulator Screen Shot - iPhone 8 - 2019-04-23 at 08 53 56

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #900 
Fixes #901 

## Changes (pass 1)
- Allowed any number of lines for payment status label
- After a few trials and errors, this [SO answer](https://stackoverflow.com/a/21267507) fixed the issue. First, with just `label.numberOfLines = 0` more of the text is shown but still truncated at the end. When I updated the `textInsets` to all 0s, the text is fully shown without insets as expected. Reading some other similar SO posts, I think the issue is that with `intrinsicContentSize` it doesn't know where to draw the text. [`textRect(forBounds bounds: CGRect, limitedToNumberOfLines numberOfLines: Int)`](https://developer.apple.com/documentation/uikit/uilabel/1620545-textrect) seems to be the method for that

## Changes (pass 2)
- Since the fix in pass 1 is quite hacky and no official backup, and after checking Apple Wallet and Stocks apps for their Dynamic Type practices with price label, we changed the design from horizontally stacked to vertically stacked over a certain font size

## Testing
- Prerequisites: log in to a store with some orders.

- Go to Orders tab
- Turn on dynamic type (device Settings > General > Accessibility > Larger Text > turn it on) and adjust the device to different font sizes via the slider, and observe the payment status text on the left side of the cell --> The text should not be truncated

## Example screenshots

UPDATED:

smaller font size | larger font size | largest font size
--- | --- | ---
Simulator Screen Shot - iPhone SE - 2019-07-09 at 11 34 57 | Simulator Screen Shot - iPhone SE - 2019-07-09 at 11 35 02 | Simulator Screen Shot - iPhone SE - 2019-07-09 at 11 35 19

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift [hunk 1]
```diff
@@ -87,5 +87,6 @@ private extension OrderTableViewCell {
         titleLabel.applyHeadlineStyle()
         totalLabel.applyBodyStyle()
         paymentStatusLabel.applyFootnoteStyle()
+        paymentStatusLabel.numberOfLines = 0
```
Comment (ctarda) [inline WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift]: My first instinct would be moving this to PaddedLabel itself. But it seems like we use that label in several places, so I am not sure how safe that would be.

File: WooCommerce/Classes/Styles/PaddedLabel.swift [hunk 2]
```diff
@@ -16,11 +16,14 @@ class PaddedLabel: UILabel {
         super.drawText(in: rect.inset(by: textInsets))
     }
 
-    override var intrinsicContentSize: CGSize {
-        var intrinsicSuperViewContentSize = super.intrinsicContentSize
-        intrinsicSuperViewContentSize.height += textInsets.top + textInsets.bottom
-        intrinsicSuperViewContentSize.width += textInsets.left + textInsets.right
-        return intrinsicSuperViewContentSize
+    override func textRect(forBounds bounds: CGRect, limitedToNumberOfLines numberOfLines: Int) -> CGRect {
```
Comment (ctarda) [inline WooCommerce/Classes/Styles/PaddedLabel.swift]: This is a genuine question: my knowledge of the intricacies of the autolayout system is very limited, but my understanding was that when the system relies heavily on intrinsicContentSize. Would it make sense to actually implement both intrinsicContentSize and textRect:forBounds?

@mindgraffiti You know much more than me about this, what do you think?

File: WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift]: good question - I think for labels, sometimes they don't need to be fully shown if the information is not critical and if the vertical space is limited. While for buttons, since users interact with them, it might make more sense to show full text

File: WooCommerce/Classes/Styles/PaddedLabel.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/Classes/Styles/PaddedLabel.swift]: After I first got the full text to show with `textRect:forBounds`, I kept the pre-existing `intrinsicContentSize` override. However, during my testing I noticed there's extra padding both vertically and horizontally.

overriding `textRect:forBounds` and `intrinsicContentSize` | overriding `textRect:forBounds` but not `intrinsicContentSize`
--- | ---
Simulator Screen Shot - iPhone SE - 2019-06-21 at 15 32 44 | Simulator Screen Shot - iPhone SE - 2019-06-21 at 15 26 31

My guess is that both overrides apply the label padding from `textInsets`, and `textRect:forBounds` specifies where the text is drawn. Though I'm not an expert about these methods and would like to learn how they work differently in more depth

Comment (mindgraffiti) [reply WooCommerce/Classes/Styles/PaddedLabel.swift]: So I read the documentation on `textRect:forBounds` and `intrinsicContentSize`, and `UILabel` as well. There were no answers to be found there. I'm still researching this (I still need to read the Draw lifecycle of a UIView), but I have doubts that this is the solution we want to take.

I did read the SO solution, and this implementation is also missing `didSet { invalidateIntrinsicContentSize() }` mentioned [here](https://stackoverflow.com/a/33573850/4150507).

File: WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift (hunk 1 above)
Comment (mindgraffiti) [reply WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift]: For the Order List, I would make the argument that a max fixed font size set in this cell would be a better way to go. 
Why?
1. Since we're limited on vertical space, it breaks the readability if the word breaks to a new line.
2. Since the payment status is also inside the Order Details screen, where it has plenty of vertical and horizontal space, the user has the opportunity to read it comfortably and in an accessible manner.

"Completed" in this context is almost unreadable, because it's unnatural to break a single word into multiple lines: 


But its fully rendered size in Order Details

File: WooCommerce/Classes/Styles/PaddedLabel.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/Classes/Styles/PaddedLabel.swift]: I also found the solution in this PR pretty hacky, I don't feel so confident when I cannot explain why `intrinsicContentSize` doesn't just work (most SO answers suggested just overriding `intrinsicContentSize` as before this PR). Another alternative is to not try adding padding to `UILabel` (since it is not supported natively): just have a `UIView` that contains a `UILabel` subview with insets. I was thinking about using Auto Layout, then checked the Slack discussion where Nate suggested the [WPiOS implementation](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Views/PaddedLabel.swift). I'll try with Auto Layout first, and then the WPiOS implementation

> I did read the SO solution, and this implementation is also missing didSet { invalidateIntrinsicContentSize() } mentioned here. Was there something you noticed that made you decide not to include it?

great catch! I was trying to make minimal changes since I was uncertain about the changes, but yes I believe `didSet { invalidateIntrinsicContentSize() }` is necessary if going with the `textRect:forBounds:` approach

File: WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift]: > For the Order List, I would make the argument that a max fixed font size set in this cell would be a better way to go.

Yea with very large font sizes, the price label dominates the horizontal space. Were you suggesting capping the font size of some of the labels in the Order cell? If so, maybe can use this [`scaledFont(for:maximumPointSize:)`](https://developer.apple.com/documentation/uikit/uifontmetrics/2877383-scaledfont) with `UIFontMetrics`?

Comment (mindgraffiti) [reply WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift]: >Were you suggesting capping the font size of some of the labels in the Order cell?

Yes, exactly. I did ask in Slack p1562017670132500-slack-C02Q9GACF what the other iOS devs have done in this situation before. I don't think this exact situation has occurred before, but something very similar. I agree with @ctarda that we should get @kyleaparker's opinion as well.

**Comment by mindgraffiti** [comment]
Idk why github decided my single comment needed posted 4 times and I can't delete the duplicates 😒

File: WooCommerce/Classes/Styles/PaddedLabel.swift (hunk 2 above)
Comment (mindgraffiti) [reply WooCommerce/Classes/Styles/PaddedLabel.swift]: >Eric suggested the WPiOS implementation. 

>I'll try with Auto Layout first, and then the WPiOS implementation

Thank you! That sounds like a better alternative.

**Comment by jaclync** [comment]
After trying out a `UIView` approach that contains a `UILabel` with insets via Auto Layout constraints, I noticed a few issues:
- this works on some cells but not all, the payment status text is still truncated in the cells that have much longer height with long price text. So far I tried setting content hugging and compression resistance priorities to required, but that still leaves either extra space or truncated text in some cells. I'll have to spend more time looking into all the constraints and their priorities. Dynamic height with Auto Layout in `UITableViewCell` is quite tricky 😓
- it'd be quite an undertaking to replace existing `PaddedLabel: UILabel` usage with the `PaddedLabelView: UIView` approach. For example, the background color and border styles are applied to the `UIView` while text and font styles are applied to the `UILabel` subview.
  - using IB also makes it harder, having to remove the current `PaddedLabel` label from xib and add the new `UIView` label view and the same constraints
  - there are a few different xib's that have `PaddedLabel: UILabel` as a subview - `LargeImageTableViewCell`, `TwoColumnTableViewCell`, `NewOrdersViewController`, `TopPerformersViewController`, `Dashboard.storyboard`,  `SummaryTableViewCell` and `OrderTableViewCell`

I also tried replacing my `PaddedLabelView: UIView` Auto Layout implementation with the frame-based [`PaddedLabel` in WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Views/PaddedLabel.swift). So far the payment status label isn't showing but I haven't got to debug it much.

I'll come back to it next week. In the meantime, @mindgraffiti @ctarda any suggestions tech/design wise are super welcome! (thanks Thuy for starting the discussion on Slack, I'll document more after figuring out a solution we all like)

**Comment by mindgraffiti** [comment]
Thanks for the update @jaclync! Did you try this yet?

>use this scaledFont(for:maximumPointSize:) with UIFontMetrics

If that works for the order status label in Order Details, I would consider this problem solved. In no particular order:
- because it creates the least impact to the code base 
- because you've already put too much effort into this and have suffered enough 😄 
- because a slightly smaller padded label on this screen is acceptable when considering the information hierarchy and the layout limitations of the screen

File: WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift (hunk 1 above)
Comment (ctarda) [reply WooCommerce/Classes/ViewRelated/Orders/Cells/OrderTableViewCell.swift]: Just to add a note to this, you might want to look at `fontForTextStyle(style:weight:maximumPointSize)` in `DefaultStyle`, which should provide what you want

**Comment by jaclync** [comment]
I just checked Apple Wallet and Stocks app, and it looks like both apps give the $ label its own line when the device font size is above a certain threshold ([`extraExtraExtraLarge`](https://developer.apple.com/documentation/uikit/uicontentsizecategory/1623109-extraextraextralarge)):

app | smaller font size | larger font size
--- | --- | ---
Apple Wallet | IMG_6058 | IMG_6059
Apple Stocks | IMG_6060 | IMG_6062

I updated the layout in xib to use stack views, and adjust the axis of the top-level stack view to be vertical above `extraExtraLarge` (since our $ label has a larger font size than the Apple Wallet/Stocks apps) and horizontal otherwise. Example screenshots:

smaller font size | larger font size | largest font size
--- | --- | ---
Simulator Screen Shot - iPhone SE - 2019-07-09 at 11 34 57 | Simulator Screen Shot - iPhone SE - 2019-07-09 at 11 35 02 | Simulator Screen Shot - iPhone SE - 2019-07-09 at 11 35 19

I think this would be a better design rather than letting the price label grow so much that leaves 1-2 characters for the order customer's name and payment status. In [this WWDC 2017 talk](https://developer.apple.com/videos/play/wwdc2017/245/) on Dynamic Type, they also encouraged updating horizontally stacked content to vertically stacked above a certain font size. What do you all think? @kyleaparker @ctarda @mindgraffiti

**Comment by mindgraffiti** [comment]
That's brilliant! I deleted the Stocks app a long time ago. I guess I should keep it around for examples like this. Can you commit what you have so it can be tested?

**Comment by jaclync** [comment]
@mindgraffiti just pushed the changes for testing/CR!

**Comment by mindgraffiti** [comment]
Thank you for putting so much care and effort into this @jaclync! 

This looks amazing! :shipit:

**Comment by jaclync** [comment]
merging after confirming with @kyleaparker in DM :)
