### PR TITLE
[REST API] Fix magic link handling on cold start

### LINKED ISSUE #14470: [REST API] Jetpack Setup: Magic Link flow opens the site picker if the app was closed before clicking it.
During the Jetpack Setup, if we use magic link, the flow will open the site picker instead of continuing the setup if the app was closed before clicking on the link.

To reproduce:

1. Open the app and sign in using site credentials.
2. Start Jetpack Setup.
3. Use Magic Link.
4. When the magic link is sent, force close the app.
5. Click on the magic link in the email.
6. Notice that the app opened the site picker.

##### Identified in https://github.com/woocommerce/woocommerce-ios/pull/14431#pullrequestreview-2441757332

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #14470 

## Description
This PR adds a fix for the case where we receive a magic link to continue the Jetpack setup, and the app is launched from cold, previously this led to launching the site picker, as we fail to get the selected site.

With this PR, we will know wait for the site to be available before trying to handle the URL.

**Note:**
Personally I think this is just a workaround, because ideally we should be caching the site for REST API just like we [do](https://github.com/woocommerce/woocommerce-ios/blob/0f6ad4ba2a24ecbaf55b41cb4caa4950f5249c46/Yosemite/Yosemite/Stores/AccountStore.swift#L106-L108) for WordPress.com, and if we were doing this, then the `defaultSite` could be loaded synchronously during URL launches.
The lack of cache leads to some other issues, if we launch the app and the fetching [failed](https://github.com/woocommerce/woocommerce-ios/blob/0f6ad4ba2a24ecbaf55b41cb4caa4950f5249c46/WooCommerce/Classes/Yosemite/DefaultStoresManager.swift#L680), the app will stay broken until it's force closed.
Adding the local cache and updating the logic will take a significant effort though.

## Steps to reproduce
1. Use a self-hosted site.
2. Sign in to the site using site credentials.
3. Start Jetpack setup.
4. Optionally:
   - Use magic link to sign in to an existing account.
   - Enter a new email to start signup.
5. Close the app.
6. Tap on the magic link.

## Testing information
- The app should be able to handle the magic link even though it was closed.

Tested magic link handling for both login and signup using iPhone 16 Simulator iOS 18.0

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

File: WooCommerce/Classes/AppDelegate.swift [hunk 1]
```diff
@@ -578,6 +577,44 @@ private extension AppDelegate {
...
+    func handleAuthenticationUrlForJetpackSetup(_ url: URL, rootViewController: UIViewController) -> Bool {
+        if let site = ServiceLocator.stores.sessionManager.defaultSite {
+            return handleAuthenticationUrlForJetpackSetup(with: site, url: url, rootViewController: rootViewController)
+        } else {
+            // Wait for the site to be available before handling the magic link
+            ServiceLocator.stores.sessionManager.defaultSitePublisher
+                .timeout(.seconds(30), scheduler: DispatchQueue.main)
+                .first(where: { $0 != nil })
+                .sink { site in
+                    guard let site = site else {
```
Comment (itsmeichigo) [inline WooCommerce/Classes/AppDelegate.swift]: Super nit:

```suggestion
                    guard let site else {
```

File: WooCommerce/Classes/AppDelegate.swift [hunk 2]
```diff
@@ -578,6 +577,44 @@ private extension AppDelegate {
...
+                        return
```
Comment (itsmeichigo) [inline WooCommerce/Classes/AppDelegate.swift:601]: ❓ Should we log an error here to know when handling the deeplink fails due to missing site?

**Review by itsmeichigo — APPROVED** [review]
Tested with simulator iPhone 16 Pro iOS 18.0 and confirmed that magic link handling works for both login and Jetpack setup when the app is cold started ✅

File: WooCommerce/Classes/AppDelegate.swift (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/Classes/AppDelegate.swift:601]: This should never happen due to the `.first(where: { $0 != nil })`, it's just because Swift's compiler can't infer that the value is not nil, do you think it would still be valuable?

Comment (itsmeichigo) [reply WooCommerce/Classes/AppDelegate.swift:601]: Gotcha, `site` should not be optional here since we already filtered the non-nil value in the `first` operator above. Please leave a comment stating that if you don't mind.

File: WooCommerce/Classes/AppDelegate.swift [hunk 3]
```diff
@@ -578,6 +577,44 @@ private extension AppDelegate {
...
+        } else {
+            // Wait for the site to be available before handling the magic link
+            ServiceLocator.stores.sessionManager.defaultSitePublisher
+                .timeout(.seconds(30), scheduler: DispatchQueue.main)
+                .first(where: { $0 != nil })
+                .sink { site in
+                    guard let site else {
+                        return
+                    }
+                    _ = self.handleAuthenticationUrlForJetpackSetup(with: site, url: url, rootViewController: rootViewController)
```
Comment (itsmeichigo) [inline WooCommerce/Classes/AppDelegate.swift]: I missed this line in my previous review. We should be careful about capturing `self` in Combine closures to avoid retain cycles. Please ensure to capture `self` weakly in this case.

Comment (hichamboushaba) [reply WooCommerce/Classes/AppDelegate.swift]: I can update it, but just for my learning here, generally in other platforms I don't care about this part when the parent `self` is a singleton that lives for the whole lifecycle of the app, which is the case of AppDelegate (unless I'm misunderstanding something), in iOS, even in those cases you would explicitly capture self weakly?

File: WooCommerce/Classes/AppDelegate.swift (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/Classes/AppDelegate.swift:601]: Done in 
6b5ec26

File: WooCommerce/Classes/AppDelegate.swift (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/Classes/AppDelegate.swift]: Updated in a425c2f, but I would still love to get an answer about my question 🙂

Comment (itsmeichigo) [reply WooCommerce/Classes/AppDelegate.swift]: You have a good point about the parent being AppDelegate making it redundant to capture `self` weakly. It's just a best practice to be on the safe side in case we forget to do that in other classes that can be deallocated. 

If you intentionally retain `self`, it'd be nice to have a comment explaining why just so we don't overlook it. The comment would be helpful, especially for those who are new to iOS dev reading the code to understand why.

Comment (hichamboushaba) [reply WooCommerce/Classes/AppDelegate.swift]: I see, thank you for the clarifications @itsmeichigo. Since I already added the weak capture logic, I'll keep it now.
