### PR TITLE
Orders tab: fix placeholder cells losing animated content

### LINKED ISSUE #11701: Orders tab: placeholder cells are plain without animated ghost content - a potential regression
**Describe the bug**

In the orders tab, when it's in the loading state, the placeholder cells don't have the animated ghost content anymore like in production.
After testing commits in trunk, it seems to happen after https://github.com/woocommerce/woocommerce-ios/pull/11621 regardless of the `splitViewInOrdersTab` feature flag value.

**To Reproduce**
- Launch the app
- Go to the orders tab --> notice that in the loading state, the cells don't animate with the ghost content

**Screenshots**

production | trunk
-- | --
 | 
 | 

https://github.com/woocommerce/woocommerce-ios/assets/1945542/cf3d4984-eece-4ada-afef-3459fb17ccc9

**Expected behavior**

In the loading state, the cells should animate with ghost content.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 17
- WooCommerce iOS version: 16.9

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #11701
Please review https://github.com/wordpress-mobile/WordPressUI-iOS/pull/138 first with testing steps in this PR

Details about Why and How are in https://github.com/wordpress-mobile/WordPressUI-iOS/pull/138 as this PR just updates the `WordPressUI` library to the PR commit.

## Testing instructions

- [x] @jaclync tests that all screens that conform to `GhostableViewController` look as before

---

Note: for easier testing on the loading state, you can add a filter to the order list that results in no orders. Alternatively, switching to another store also shows the loading state.

- Launch the app
- Go to the orders tab --> in the loading state, the cells should have animated content (redacted content) instead of the whole cell animated

## Screenshots

before | after
-- | --
 | 
 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/WPComLogin/WPComPasswordLoginViewModel.swift [hunk 1]
```diff
@@ -78,7 +78,7 @@ private extension WPComPasswordLoginViewModel {
         return email
             .lowercased()
             .trimmingCharacters(in: .whitespaces)
-            .md5Hash()
+            .sha256Hash()
```
Comment (jaclync) [inline WooCommerce/Classes/Authentication/WPComLogin/WPComPasswordLoginViewModel.swift:81]: this diff is to fix the build failure from updating the WordPressUI library with this improvement https://github.com/wordpress-mobile/WordPressUI-iOS/pull/133.

**Review by bozidarsevo — APPROVED** [review]
Looks good!

Simulator Screenshot - iPhone 15 Pro - 2024-01-29 at 16 40 53

Simulator Screenshot - iPhone 15 Pro - 2024-01-29 at 16 40 26
