### PR TITLE
Use NSFetchedResultsSectionInfo.numberOfObjects Instead of objects.count

### LINKED ISSUE #1543: Invalid Number Of Rows/Sections Crash
**Describe the bug**
Text from one of the crashes:

```Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (8) must be equal to the number of rows contained in that section before the update (7), plus or minus the number of rows inserted or deleted from that section (1 inserted, 7 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).```

Crash report: https://sentry.io/share/issue/63aa8ffcc1634d5da1c7c2c0f8155ac8/

**To Reproduce**
Unsure of how to reproduce.

**Expected behavior**
No crashes when orders list is updated.

### PR DESCRIPTION
**Pull request by shiki**
This is just an attempt in fixing #1543. 

## Findings

We currently use `objects.count` when determining the number of rows in the section. 

https://github.com/woocommerce/woocommerce-ios/blob/9420a214faa675cd5eb5d36de1a4f6ac509f8cfa/Yosemite/Yosemite/Tools/ResultsController.swift#L266-L270

I found from these resources that `objects.count` can sometimes have a different value compared to [`numberOfObjects`](https://developer.apple.com/documentation/coredata/nsfetchedresultssectioninfo/1622289-numberofobjects):

- http://mikeabdullah.net/nsfetchedresultscontroller.html
- https://stackoverflow.com/a/39232007
- https://stackoverflow.com/q/3967895

Sadly, I have not been able to prove that this is the cause of the crash. 😞 

The [official Apple doc](https://developer.apple.com/documentation/coredata/nsfetchedresultscontroller) also shows that `numberOfObjects` should be used.

## Changes

This changes `SectionInfo` to use `numberOfObjects` instead of `objects.count`. I also made it store the `NSFetchedResultsSectionInfo` internally so `SectionInfo` would act more like just a wrapper. 

While we can't really prove if this fixes #1543, this change at least eliminates some _possible_ causes that we should look into. We can now ignore this part and move on.

## Testing

Please do a regression test that this does not affect the table view loading. 

## Reviewing 

Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Yosemite/Yosemite/Tools/ResultsController.swift [hunk 1]
```diff
@@ -256,36 +256,45 @@ public extension ResultsController {
...
-        /// Array of Mutable Objects!
-        ///
-        private let mutableObjects: [T]
+            guard let objects = mutableSectionInfo.objects else {
+                return []
+            }
+            guard let castedObjects = objects as? [T] else {
+                assertionFailure("Failed to cast objects into an array of \(T.self)")
+                return []
+            }
```
Comment (jaclync) [inline Yosemite/Yosemite/Tools/ResultsController.swift:289]: nit: would it also work by combining these 2 guard statements like:

```
private(set) public lazy var objects: [T.ReadOnlyType] = {
        guard let objects = mutableSectionInfo.objects as? [T] else {
            return []
        }
        return objects.map { $0.toReadOnly() }
}()
```
