### PR TITLE
Send receipts after failed payments via the API

### LINKED ISSUE #14163: [TTPReq] Send receipts after succeeded or failed payments
PT: p7bje6-6ob-p2
Test scenarios: p91TBi-csN-p2
API task: https://github.com/woocommerce/woocommerce-ios/issues/14326
Designs & Copy: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2

## Description

Allow customer receipts to be sent after successful and failed payments.

1. Integrate new Woo 9.5 changes to send receipts after failed payment
2. Integrate 'Send Receipt' option within existing APIs
3. Try integrating existing UI to select customers / add new customer details
4. Call a new API https://github.com/woocommerce/woocommerce-ios/issues/14326 to send receipt to updated customer details
5. https://github.com/woocommerce/woocommerce-ios/issues/6358
Do not send a receipt to the same user twice. Test if receipts are always sent after successful or failed payments when the customer is attached. If that's the case, consider showing `Send Receipt` option only when there's no customer attached (See https://github.com/woocommerce/woocommerce-ios/issues/6358 and Android implementation).

## Design

| Image 1 | Image 2 |
| ------- | ------- |
| Image 1 | Image 2 |

#### Email sent message

Image

## User Flow

Image

### PR DESCRIPTION
**Pull request by staskus**
Closes: #14163
Wraps up the work from: 
- https://github.com/woocommerce/woocommerce-ios/pull/14422 
- https://github.com/woocommerce/woocommerce-ios/pull/14446 
- https://github.com/woocommerce/woocommerce-ios/pull/14475

## Description

Allow inputting and sending receipts after failed payments. Equivalent changes to https://github.com/woocommerce/woocommerce-ios/pull/14422 but for failed payments.

I will enable feature flag only when both WooCommerce and WooPayments versions are officially released and additional CFT is performed.

## Solution

1. To be consistent, now we have three types of alerts:
- **EmailSent** (email sent message): CardPresentModalSuccessEmailSent, CardPresentModalErrorEmailSent, CardPresentModalNonRetryableErrorEmailSent
- **WithoutEmail** (no email information) : CardPresentModalSuccessWithoutEmail, CardPresentModalErrorWithoutEmail, CardPresentModalNonRetryableErrorWithoutEmail
- **Default** (with email receipt button): CardPresentModalSuccess, CardPresentModalError, CardPresentModalNonRetryableError

2. Since payment failure alert allows to retry the payment, when `ReceiptEmailViewController` is present, do not automatically dismiss the alert. If email is sent, update the alert to show `Email sent` message created in the previous PR.

## Steps to reproduce

Before testing:
1. Enable `sendReceiptAfterPayment` in `DefaultFeatureFlagService`
2. Use my testing site https://lovely-aware-sturgeon.jurassic.ninja/ details: PdfdoF-5Qj-p2

#### Main scenario: No customer + Failed Payment + Input Email

1. Order
2. [Set a failure amount](https://docs.stripe.com/terminal/references/testing#physical-test-cards)
3. Make Card Reader / TTP payment
4. Confirm Payment failed modal appears with "Email receipt option"
5. Click "Email receipt"
6. Confirm a new modal appears
7. Input a valid email
8. Tap "Email receipt"
9. Confirm email modal is dismissed, payment failure alert is updated with an email sent message
10 Confirm email arrives
11. Tap `Try collecting again'
12. Confirm email sent message is shown

#### 2nd scenario: No customer + Failed Payment + Retry + Input email

1. Repeat steps 1-4 until failure modal appears
2. Tap 'Try collecting again'
3. Confirm 'Email Receipt' and 'Dismiss' options are shown
4. Click "Email receipt", enter valid email, confirm
5. Confirm email modal is dismissed, payment failure alert is updated with an email sent message
6. Confirm email sent message is shown

## Testing information

I additionally tested:
- Feature flag enabled/disabled
- Dismissing receipt email modal via cancel button or dismiss gesture
- Making payments with customer, without customer, retrying payments later, attaching customer later etc...
- iPad and iPhone
- Tap to Pay and Card Reader
- Success

### Card Reader + Failed Payment + Input email

https://github.com/user-attachments/assets/81f5be07-25e7-477c-916a-5b09c2c896ea

### TTP + Failed Payment + Retry + Input email

https://github.com/user-attachments/assets/f9f592ab-bb76-4e06-98ff-23bdb4d6f9ff

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.m

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift [hunk 1]
```diff
@@ -113,5 +120,11 @@ extension CardPresentModalError {
             value: "A receipt has been sent to %1$@",
             comment: "Message informing the user that a receipt has been sent to their email address. %1$@ is the email address"
         )
+
+        static let emailReceipt = NSLocalizedString(
+            "cardPresentPaymentsModal.error.emailReceipt",
+            value: "Email receipt",
+            comment: "Button to email receipts. Presented to users after a payment has been successfully collected"
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift]: super nit: the comment indicates a successful payment, whereas the modal is shown on payment error

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift [hunk 2]
```diff
@@ -38,13 +41,15 @@ final class CardPresentModalError: CardPresentPaymentsModalViewModel {
          transactionType: CardPresentTransactionType,
          image: UIImage = .paymentErrorImage,
          primaryAction: @escaping () -> Void,
+         secondaryAction: @escaping () -> Void,
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalError.swift]: nit: if the secondary button is always to email receipt, how about using a closure name with this clear intention?
```suggestion
         emailReceipt: @escaping () -> Void,
```

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift [hunk 3]
```diff
@@ -484,14 +486,21 @@ private extension CollectOrderPaymentUseCase {
                                                    onCompletion(.failure(error))
                                                })
             )
-        }
+        },
+                                     emailPromptCompletion: { [weak self] in
+            self?.presentRetryByRestartingError(error: error,
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift]: non-blocking❓: since it's calling the same function, could it result in a loop? Or maybe it's intentional to show the retryable error on email prompt completion?

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift [hunk 4]
```diff
@@ -748,14 +775,20 @@ private extension CollectOrderPaymentUseCase {
                 if let email = order.billingAddress?.email, email.isNotEmpty {
                     receiptState = .paymentSuccessEmailSent(email: email)
                 } else {
-                    receiptState = .promptToSendEmailReceipt(emailReceiptAction: {
-                        // TODO
+                    receiptState = .promptToSendEmailReceipt(emailReceiptAction: { [weak self] in
+                        guard let self else { return }
+                        presentSendReceiptAfterPayment { order in
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift]: nit: might we want to weak self in this closure as well?
```suggestion
                        presentSendReceiptAfterPayment { [weak self] order in
```

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift [hunk 5]
```diff
@@ -748,14 +775,20 @@ private extension CollectOrderPaymentUseCase {
...
+                            if let order {
+                                self.order = order
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift:783]: just curious, what parts of the order might be updated after sending an email receipt? like the billing email?

File: WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CollectOrderPaymentUseCaseTests.swift [hunk 6]
```diff
@@ -288,6 +288,40 @@ final class CollectOrderPaymentUseCaseTests: XCTestCase {
                                             error: error)
         receiptEligibilityUseCase.isEligibleSendingReceiptAfterPayment = true
 
+        // When we make a payment thar results in card reader disconnection
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewModels/CardPresentPayments/CollectOrderPaymentUseCaseTests.swift]: super nit:
```suggestion
        // When we make a payment that results in card reader disconnection
```

**Review by jaclync — APPROVED** [review]
Nice work, works as expected! :shipit: At first I didn't have the feature flag enabled, and can verify that the email receipt CTA isn't shown for card reader & TTP payment error modal. I like the UX where a checkmark is shown after the loading state in the CTA on success.

Do you know if the email receipt works in POS as well? Some presentation logic in the error modal is UIKit specific, just wondering if this works for the adapted SwiftUI version in POS.

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift (hunk 3 above)
Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift]: Yes, this is intentional. It is done to update the currently shown alert after the email prompt is closed. 

After we send a new email receipt, an alert is updated and shows "Email has been sent to {email}" message rather than continue showing "Email receipt" button. 

I'll try to think how to make it clearer. It may be possible to move this call one layer up where `presentRetryByRestartingError` is called rather than calling it within itself.

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift (hunk 5 above)
Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift:783]: Yes. The billing email is updated.

**Comment by staskus** [comment]
@jaclync, thanks for the review!

> Do you know if the email receipt works in POS as well? Some presentation logic in the error modal is UIKit specific, just wondering if this works for the adapted SwiftUI version in POS.

This is a great question. A current implementation builds on already existing receipt-related modals. However, as you mention, it implements specific UIKit modals within `CollectOrderPaymentUseCase` which is not ideal.

We discussed it here as well pdfdoF-5RR-p2#comment-6896.

POS receipts functionality is being implemented right now. POS could use `ReceiptState` when building `CardPresentPaymentEventDetails` in `CardPresentPaymentsTransactionAlertsProvider`. This way there could be a shared logic between POS and IPP. However, we discussed this and we are choosing to untangle receipts from payment flow within POS for more flexibility. In a longer term, it could mean that we should remove receipt-related functionality from `CollectOrderPaymentUseCase` for clarity. I have a draft task for this on the project board so I could address it later or plan for the future.
