### PR TITLE
Fixed tracking events opened/closed called multiple times 

### LINKED ISSUE #2440: Application opened event possibly firing too much
Looking at activity of the application_opened event, I'm seeing nearly double the events than Android. Comparing to Apple's usage statistics we should be more in line with Android's counts for active sessions in a day. Take a bit of time to test the application_opened event to make sure it's firing correctly - especially when considering push notifications.

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #2440 

Investigating the issue #2440 seems that the events `application_opened` and `application_closed` are called two times every time they are fired because we start to observe notifications two times if the user has opted in the analytics.
To make sure to not register the notifications two times, I remove all the observers before adding a new one.

## Testing
- Launch the app, and make sure that in the console you are able to see only one `application_opened` event. 
- Send the app in foreground, make sure that the event `application_closed` is fired only one time. (if you relaunch the app, you will notice another `application_opened` event)

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Analytics/WooAnalytics.swift [hunk 1]
```diff
@@ -140,6 +140,7 @@ private extension WooAnalytics {
             return
         }
 
+        stopObservingNotifications()
```
Comment (astralbodies) [inline WooCommerce/Classes/Analytics/WooAnalytics.swift:143]: I believe the better course of action here might be to only call `startObservingNotifications()` once. I understand why we conditionally wrap the calls to loop into the NSNotificationCenter but in the end the `track()` method will ignore those events.

Comment (astralbodies) [reply WooCommerce/Classes/Analytics/WooAnalytics.swift:143]: So that means removing all of the `stopObservingNotifications()`, leave the one `startObservingNotifications()` in the `initialize()` method, and then add a `deinit` to call `stopObservingNotifications()`.

**Review by astralbodies — CHANGES_REQUESTED** [review]

File: WooCommerce/Classes/Analytics/WooAnalytics.swift (hunk 1 above)
Comment (pmusolino) [reply WooCommerce/Classes/Analytics/WooAnalytics.swift]: You are right, I didn't notice that there was a check on the `track()` method. 
Since we target >= iOS 12.0 and we use `addObserver:selector:name:object:`, we don't need to unregister the observer inside the `deinit` method. The system will take care of it. It would have been different if we were using `addObserverForName:object:queue:usingBlock:`. 👍 
Can you take a second look at it?

**Review by astralbodies — APPROVED** [review]
I didn't know about the iOS 12 thing with observing - nice! :shipit:
