### PR TITLE
[Mobile Payments] Bump minimum Stripe extension version to 6.2.0 for IPP

### LINKED ISSUE #6033: [Mobile Payments] Bump minimum Stripe version to 6.2.0 to avoid empty descriptors that block payments
The Stripe extension allows the payment descriptor to be empty. This will cause creation of a payment intent to fail.

This will be fixed in version 6.2.0 of the extension - see https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2303

fyi @ctarda @malinajirka

### PR DESCRIPTION
**Pull request by allendav**
Closes: #6033

### Description
- Although the iOS app no longer requires the null descriptor fix in Stripe extension 6.2.0, [since it will pass a null (instead of an empty string) to payment intent creation](https://github.com/woocommerce/woocommerce-ios/pull/6041), we want to set the first release of IPP for Stripe extension to 6.2.0

### Testing instructions
- Ensure unit tests pass
- Attempt to enter IPP flows with Stripe extension version less than 6.2.0. Ensure you are prompted to update
- Attempt to enter IPP flows with Stripe extension version of 6.2.0 or newer. Ensure you are NOT prompted to update

### Screenshots
N/A

fyi @malinajirka @ctarda 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift [hunk 1]
```diff
@@ -665,7 +665,7 @@ private extension CardPresentPaymentsOnboardingUseCaseTests {
     }
 
     enum StripePluginVersion: String {
-        case minimumSupportedVersion = "6.1.0" // Should match `CardPresentPaymentsOnboardingState` `minimumSupportedPluginVersion`
+        case minimumSupportedVersion = "6.2.0" // Should match `CardPresentPaymentsOnboardingState` `minimumSupportedPluginVersion`
         case unsupportedVersion = "5.8.1"
```
Comment (koke) [inline WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift]: I don't think it's a big deal, but to properly test the change, maybe the unsupported version should now be 6.1

**Review by koke — COMMENTED** [review]
I had some trouble with this. The version check seems fine, but I'm getting an error after upgrading to 6.2

> 2022-02-18 11:33:42.521528+0100 WooCommerce[90552:12275813] ⛔️ Error synchronizing Stripe Account: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "statement_descriptor", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))

6.1|6.2
-|-
Simulator Screen Shot - iPhone 13 - 2022-02-18 at 11 31 52|Simulator Screen Shot - iPhone 13 - 2022-02-18 at 11 32 08

**Comment by koke** [comment]
Noting that the API response contains `"statement_descriptor":null`, but the decoder won't handle nulls for that field:
```
let statementDescriptor = try container.decode(String.self, forKey: .statementDescriptor)
```

**Review by koke — APPROVED** [review]
Approving since the error is not exactly caused by this PR, but we should address it before release

File: WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift (hunk 1 above)
Comment (allendav) [reply WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift]: Fixed in https://github.com/woocommerce/woocommerce-ios/pull/6224/commits/9b03f5fd863483fd81207f037d1fc40c69ffda1f
