### PR TITLE
Reviews: delete stored Product Reviews when syncing Reviews from the first page

### LINKED ISSUE #2335: Reviews: Remotely trashed review remains in app
**Describe the bug**

When a review is trashed remotely (e.g. via the web) it remains in the app, even after pulling to refresh or force-closing the app.

The trashed review wasn't removed from the app until I completely refreshed the Reviews screen, e.g. by switching stores and then switching back.

I'm not sure if this is related to https://github.com/woocommerce/woocommerce-ios/issues/1908 (an issue where reviews trashed from **within** the app remain in the app).

**To Reproduce**

1. View the Reviews list in the app.
2. On the web, trash a review (from the product details screen).
3. In the app, pull to refresh the Reviews screen and notice the review remains.
4. Notice you can open the review in the app, navigate to others and back, and even force-close the app and the review remains there.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4.1
- WooCommerce iOS version: 4.2.0.1 and 4.3.0.0 TestFlight Beta

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #2335 

## Changes
- Moved all the Reviews classes under the folder `Reviews` (before the name of the folder was Notifications).
- Deleted all stored Product Reviews for a given site ID after successfully loading the first page of Reviews from the API and before inserting the data from the API to the storage.
- Added 3 test cases for `ProductReviewStore` for this change.
- Updated the name of all the tests in `ProductReviewStore`.

## Testing
1. View the Reviews list in the app.
2. On the web, trash a review (from the product details screen) or set it as spam.
3. In the app, pull to refresh the Reviews screen and notice the review is correctly removed from the list.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Yosemite/Yosemite/Stores/ProductReviewStore.swift [hunk 1]
```diff
@@ -81,6 +81,10 @@ private extension ProductReviewStore {
                 return
             }
 
+            if pageNumber == 1 {
```
Comment (jaclync) [inline Yosemite/Yosemite/Stores/ProductReviewStore.swift]: nit: we usually compare with `Default.firstPageNumber` like in `ProductCategoryStore`

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 2]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+    ///
+    func test_syncing_product_reviews_on_the_first_page_resets_stored_product_reviews() {
+
+        // Given
+        let reviewID1: Int64 = 1
+        let reviewID2: Int64 = 2
+        let productReviews = [self.sampleProductReview(reviewID: reviewID1), self.sampleProductReview(reviewID: reviewID2)]
+        self.store.upsertStoredProductReviews(readOnlyProductReviews: productReviews,
+                                              in: self.viewStorage,
+                                              siteID: self.sampleSiteID)
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift]: nit: `self` probably not needed?

```suggestion
        store.upsertStoredProductReviews(readOnlyProductReviews: productReviews,
                                          in: viewStorage,
                                          siteID: sampleSiteID)
```

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 3]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+
+                exp.fulfill()
+            }
+            store.onAction(action)
+        }
+    }
+
+    /// Verifies that `ProductReviewAction.synchronizeProductReviews` after the first page does not delete stored Product Reviews for the given
+     /// site ID.
+     ///
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift]: super nit!

```suggestion
    /// site ID.
    ///
```

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 4]
```diff
@@ -206,7 +331,7 @@ final class ProductReviewStoreTests: XCTestCase {
 
     /// Verifies that `ProductReviewAction.retrieveProductReview` returns an error whenever there is an error response from the backend.
     ///
-    func testRetrieveSingleProductReviewReturnsErrorUponReponseError() {
+    func test_retrieve_single_product_review_returns_rrror_upon_reponse_error() {
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift]:
```suggestion
    func test_retrieve_single_product_review_returns_error_upon_reponse_error() {
```

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 5]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+
+                exp.fulfill()
+            }
+            store.onAction(action)
+        }
+    }
+
+    /// Verifies that `ProductReviewAction.synchronizeProductReviews` for the first page does not delete stored Product Reviews if the API call fails.
+    ///
+    func test_syncing_product_reviews_on_the_first_page_doest_not_delete_stored_product_reviews_upon_response_error() {
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift]:
```suggestion
    func test_syncing_product_reviews_on_the_first_page_does_not_delete_stored_product_reviews_upon_response_error() {
```

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 6]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+
+        // Given
+        let reviewID1: Int64 = 1
+        let reviewID2: Int64 = 2
+        let productReviews = [self.sampleProductReview(reviewID: reviewID1), self.sampleProductReview(reviewID: reviewID2)]
+        self.store.upsertStoredProductReviews(readOnlyProductReviews: productReviews,
+                                              in: self.viewStorage,
+                                              siteID: self.sampleSiteID)
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift]: nit: `self` probably not needed?

```suggestion
        let productReviews = [sampleProductReview(reviewID: reviewID1), sampleProductReview(reviewID: reviewID2)]
        store.upsertStoredProductReviews(readOnlyProductReviews: productReviews,
                                              in: viewStorage,
                                              siteID: sampleSiteID)
```

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 7]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+                    siteID: self.sampleSiteID,
+                    reviewID: reviewID1)
+                XCTAssertNotNil(storedProductReview1)
+
+                let storedProductReview2 = self.viewStorage.loadProductReview(
+                    siteID: self.sampleSiteID,
+                    reviewID: reviewID2)
+                XCTAssertNotNil(storedProductReview2)
+
+                XCTAssertGreaterThan(self.viewStorage.countObjects(ofType: Storage.ProductReview.self), 2)
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift:203]: nit: similar to the above comment about moving these to `// Then`!

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 8]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+                // The previously upserted Product Reviews should be deleted.
+                let storedProductReview1 = self.viewStorage.loadProductReview(
+                    siteID: self.sampleSiteID,
+                    reviewID: reviewID1)
+                XCTAssertNil(storedProductReview1)
+
+                let storedProductReview2 = self.viewStorage.loadProductReview(
+                    siteID: self.sampleSiteID,
+                    reviewID: reviewID2)
+                XCTAssertNil(storedProductReview2)
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift:159]: nit: I think the wait for `ProductReviewAction.synchronizeProductReviews` could be moved to the `// When` section, and then these asserts can be under the `// Then` section?

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 9]
```diff
@@ -123,9 +123,134 @@ final class ProductReviewStoreTests: XCTestCase {
...
+                    siteID: self.sampleSiteID,
+                    reviewID: reviewID1)
+                XCTAssertNotNil(storedProductReview1)
+
+                let storedProductReview2 = self.viewStorage.loadProductReview(
+                    siteID: self.sampleSiteID,
+                    reviewID: reviewID2)
+                XCTAssertNotNil(storedProductReview2)
+
+                XCTAssertEqual(self.viewStorage.countObjects(ofType: Storage.ProductReview.self), 2)
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift:245]: nit: similar to the earlier comment about When/Then sections!

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 10]
```diff
@@ -77,7 +77,7 @@ final class ProductReviewStoreTests: XCTestCase {
 
     /// Verifies that ProductReviewAction.synchronizeProductReviews effectively persists any retrieved product reviews.
     ///
-    func testRetrieveProductReviewsEffectivelyPersistsRetrievedProductReviews() {
+    func test_retrieve_product_reviews_effectively_persists_retrieved_product_reviews() {
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift:80]: thanks for updating all the test case names!

**Review by jaclync — COMMENTED** [review]
Thanks for the p2 post discussion in addition to working on this bug!

Code: ✅ (mostly nits)
Testing: I noticed some issues most likely from the `viewWillAppear` sync to `viewDidLoad`:

- When I first launched the app from the PR branch (logged in), the Reviews tab first showed the empty screen (same screenshot as below) while it was actually syncing --> it might be nice to keep the placeholder state as before?
- After switching stores, the Reviews tab is always empty and I cannot pull down to refresh either



Maybe we need to sync again when the site changes, `ProductsViewController` might be a good reference if we want to move the sync from `viewWillAppear` sync to `viewDidLoad`.

**Comment by pmusolino** [comment]
Thank you so much @jaclync for your review and for discovering these issues! Can you take a second look at the PR, considering also two other cases:

- Switching between two stores and going to the reviews tab
- Login into the app and navigate to the reviews tab

Everything should be in place now. I also think that the state machine and the management of data source it's a little bit over-engineered in the reviews. I'd like in the future to refactor the view controller and the data source, and simplify the methods inside `ReviewsViewController` because there are some nested methods, so you risk to call a method two or more times, and you don't know it.

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift [hunk 11]
```diff
@@ -122,7 +123,9 @@ final class ReviewsViewController: UIViewController {
         resetApplicationBadge()
         transitionToResultsUpdatedState()
 
-        syncingCoordinator.synchronizeFirstPage()
+        if isEmpty {
+            transitionToSyncingState(pageNumber: SyncingCoordinator.Defaults.pageFirstIndex)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift:127]: I'm a bit confused by calling the syncing UI manually here, since `transitionToSyncingState` is usually triggered by `SyncingCoordinator`'s delegate callback 🤔 I don't have a store that has empty reviews to test, but I wonder if revisiting the reviews tab without any actual reviews will get stuck at placeholder UI state?

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift [hunk 12]
```diff
@@ -291,7 +294,8 @@ private extension ReviewsViewController {
 
         tableView.setContentOffset(.zero, animated: false)
         tableView.reloadData()
-        transitionToSyncingState()
+
+        transitionToSyncingState(pageNumber: SyncingCoordinator.Defaults.pageFirstIndex)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift]: is this call necessary? since `reloadResultsController` is only called in `defaultSiteWasUpdated` and is followed by `syncingCoordinator.resynchronize()` which triggers syncing the first page, I think it's safe to let the sync callback transition to the expected state after switching sites?

I understand that this call is pre-existing, just thought it might simplify the code a bit by just letting the syncing callback triggers UI state transitions :)

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift [hunk 13]
```diff
@@ -363,7 +367,8 @@ private extension ReviewsViewController {
     ///
     @objc func defaultSiteWasUpdated() {
         reloadResultsController()
-        syncingCoordinator.resetInternalState()
+        syncingCoordinator.resynchronize()
+        tableView.reloadData()
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift]: nit: is this call necessary? I commented this line and it seems to work still

File: Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift [hunk 14]
```diff
@@ -123,9 +123,136 @@ final class ProductReviewStoreTests: XCTestCase {
...
+
+        // When
+        network.simulateResponse(requestUrlSuffix: "products/reviews", filename: "generic_error")
+        XCTAssertEqual(viewStorage.countObjects(ofType: Storage.ProductReview.self), 2)
+
+        waitForExpectation { exp in
+            let action = ProductReviewAction.synchronizeProductReviews(siteID: sampleSiteID,
+                                                                       pageNumber: defaultPageNumber,
+                                                                       pageSize: defaultPageSize) { error in
+        // Then
```
Comment (jaclync) [inline Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift]: nit: indentation 😄

**Review by jaclync — APPROVED** [review]
Thanks for the updates Paolo!

> I also think that the state machine and the management of data source it's a little bit over-engineered in the reviews. I'd like in the future to refactor the view controller and the data source, and simplify the methods inside ReviewsViewController because there are some nested methods, so you risk to call a method two or more times, and you don't know it.

yes I agree! I'm also hoping to make each tab view controller's life cycle tied to a store, so that we don't have to handle when the site changes manually via `NSNotificationCenter` and all the setup can be in `viewDidLoad`: https://github.com/woocommerce/woocommerce-ios/issues/1838

Code: ✅ (just questions about some calls that might not be necessary)
Testing: ✅ (tested logging out, switching stores, pulling down to refresh with a remotely trashed review!)

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift (hunk 11 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift:127]: I think there is a bug in updating the UI only from the `SyncingCoordinator` because some cases are not managed. For example, we don't want to reload all the things when the Reviews screen appears, so it's not useful to resynchronize the SyncingCoordinator in `viewWillAppear`, and without the `transitionToSyncingState` here when the screen is empty, you will see the loading/ghost cells with the data of the old store. It can be caused by the wrong reuse of the cells but should be fixed when we will drop the old `SyncingCoordinator`. I also noticed that we are using `transitionToResultsUpdatedState` here, but in theory, also it should be called only inside the `SyncingCoordinator` delegates methods.

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift (hunk 12 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift]: It make sense, fixed here 1e26382ce06a7391d4cd4f088d4913837f9e5dd4 🙇

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift (hunk 13 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift]: I confirm that it works properly also without this `reloadData()`. Removed here 3ddb199db0e0e2eaf0204e6729e710c3d1159409 🙇

File: WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift (hunk 11 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.swift:127]: I see, yea we can remove the manual UI state transitions after replacing `SyncingCoordinator` 👍 this might also not be necessary once a `ReviewsViewController` is tied to one site ID

**Review by jaclync — APPROVED** [review]
The changes look good!

**Comment by pmusolino** [comment]
Thank you so much @jaclync for your review! <3
