### PR TITLE
[Refunds] Update deleted refunds on web

### LINKED ISSUE #3052: Deleting refunds on web does not reflect in the app
It seems that when you delete a refund on wen, the app is not able to pick up those changes and displays wrong refund information.

### PR DESCRIPTION
**Pull request by Ecarrion**
fix https://github.com/woocommerce/woocommerce-ios/issues/3052

# Why

While testing the refunds creation feature I noticed that deleting a refund on web does not properly reflect in the app.
The issue happens because the app is only upserting new refunds as they come from web but does not handle the scenario of cleaning refunds deleted on web.

# How

To fix that I've added a method on `RefundStore` that deletes stale(web removed) refunds when indicated on `RefundAction.retrieveRefunds - deleteSlateRefunds flag` 

# Screenshots
**WEB**
core

Before | After
---- | ----
before | after

# Testing Steps
- Navigate to a refunded order
- Tap on refunded items and see items being refunded
- On web, go to that order and delete one or more refunds
- On the app, refresh the order detail and see that the previous refund disappears.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Yosemite/Yosemite/Actions/RefundAction.swift [hunk 1]
```diff
@@ -7,7 +7,7 @@ import Networking
 public enum RefundAction: Action {
     case createRefund(siteID: Int64, orderID: Int64, refund: Refund, onCompletion: (Refund?, Error?) -> Void)
     case retrieveRefund(siteID: Int64, orderID: Int64, refundID: Int64, onCompletion: (Refund?, Error?) -> Void)
-    case retrieveRefunds(siteID: Int64, orderID: Int64, refundIDs: [Int64], onCompletion: (Error?) -> Void)
+    case retrieveRefunds(siteID: Int64, orderID: Int64, refundIDs: [Int64], deleteStaleRefunds: Bool, onCompletion: (Error?) -> Void)
```
Comment (jaclync) [inline Yosemite/Yosemite/Actions/RefundAction.swift:10]: I'd think we always want to delete stale refunds, do you know if there are any scenarios when we want to set `deleteStaleRefunds: false`?

File: Yosemite/Yosemite/Stores/RefundStore.swift [hunk 2]
```diff
@@ -36,8 +36,8 @@ public class RefundStore: Store {
             createRefund(siteID: siteID, orderID: orderID, refund: refund, onCompletion: onCompletion)
         case .retrieveRefund(let siteID, let orderID, let refundID, let onCompletion):
             retrieveRefund(siteID: siteID, orderID: orderID, refundID: refundID, onCompletion: onCompletion)
-        case .retrieveRefunds(let siteID, let orderID, let refundIDs, let onCompletion):
-            retrieveRefunds(siteID: siteID, orderID: orderID, refundIDs: refundIDs, onCompletion: onCompletion)
+        case .retrieveRefunds(let siteID, let orderID, let refundIDs, let deleteStaleRefunds, let onCompletion):
+            retrieveRefunds(siteID: siteID, orderID: orderID, refundIDs: refundIDs, deleteStaleRefunds: deleteStaleRefunds, onCompletion: onCompletion)
         case .synchronizeRefunds(let siteID, let orderID, let pageNumber, let pageSize, let onCompletion):
```
Comment (jaclync) [inline Yosemite/Yosemite/Stores/RefundStore.swift:41]: deleting stale refunds made me wonder how we handle deleted refunds in `synchronizeRefunds`, and it looks like it's not even used 🤔

**Review by jaclync — APPROVED** [review]
Good catch on this scenario! Just checking, it makes sense to still show an empty refunded row in the payment section right?

before deleting refund | after deleting refund
-- | --
Simulator Screen Shot - iPhone 11 - 2020-10-23 at 18 08 35 | Simulator Screen Shot - iPhone 11 - 2020-10-23 at 18 09 34

In core, the deleted refund row is also shown as $0:

Screen Shot 2020-10-23 at 6 14 39 PM

Also, an unrelated observation: the refunds under payment don't seem to follow the same order as in the screenshots 🤔

File: Yosemite/Yosemite/Actions/RefundAction.swift (hunk 1 above)
Comment (Ecarrion) [reply Yosemite/Yosemite/Actions/RefundAction.swift:10]: I added the flag because in the action `retrieveRefunds` you can specify which refunds to retrieve. So If a consumer chooses just to refresh a few they may not want to delete the ones they didn't fetch.

File: Yosemite/Yosemite/Stores/RefundStore.swift (hunk 2 above)
Comment (Ecarrion) [reply Yosemite/Yosemite/Stores/RefundStore.swift:41]: Yeah, the only action used `retrieveRefunds` do you think we should delete the rest of them?

**Comment by Ecarrion** [comment]
Thanks for the review @jaclync, regarding your findings I've added a separate issue to continue working on that screen! https://github.com/woocommerce/woocommerce-ios/issues/3055
