### PR TITLE
Coupons: Add new view for enabling analytics

### LINKED ISSUE #6360: Coupon Details: Total discounted amount is unabled to load when WC Analytics is disabled
# Description
When disabling WC Analytics, requests to `wc-analytics/reports/coupons/` return 404 error. In this case, the loading indicator on the Coupon Detail screen will load forever.

# Steps to reproduce
- Make sure your test store enables Coupons and has set up at least one coupon and applied it to at least one order.
- Turn off WC Analytics (WC Settings > Advanced > Features > Enables WooCommerce Analytics).
- On the app, navigate to Menu > Coupons > Select the aforementioned coupon to see its details. Notice that the amount field shows a loading indicator for an infinite time.

# Expectation
Show an error message or hide the amount field in this case.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #6360 

### Description

This PR adds a new screen to provide an explanation and an action button to enable WooCommerce Analytics from within the app. This flow is needed to address the issue with loading the total discounted amount on the coupon details screen since we're using a `wc-analytics` endpoint for this.

A few things to note:
- We have 2 UIKit flows to handle on this screen: navigation to support and displaying notices for successful or failed requests. Both these flows require a view controller to present from; while the enable analytics screen is a modal presented from the coupon detail screen in SwiftUI. The solution is to send the presenting view controller to the `EnableAnalyticsView`, which essentially is the hosting controller of the coupon details screen. This workaround doesn't look very nice, so please feel free to suggest another solution if possible.
- The API request to toggle analytics settings doesn't work very consistently: if the value in the request is different from the current setting value, the request always fails on first try and succeeds on the second time. I'm not sure yet where to file the issue (probably [woocommerce/woocommerce-admin](https://github.com/woocommerce/woocommerce-admin)?) But for now, I've added a workaround by allowing retrying the request once to avoid the false failure.

### Testing instructions

- Please make sure that your test stores has coupons enabled (in WP Admin > WC Settings > General > Enable Coupons), has at least one coupon set up (in WP Admin > Marketing > Coupons) and applied to at least an order.
- Disable WC Analytics in WP Admin > WC Settings > Advanced > Features > Analytics.
- Open the app, navigate to Menu > Coupons > select the coupon that has been applied to at least an order.
- On the coupon details screen, notice that there's an orange (i) icon next to "Amount" after loading the total discounted amount fails. Tapping on that, notice that a new screen for enabling analytics is presented.
- Tap on Contact Support, notice that the support flow is presented properly.
- Tap on Not now, notice that the screen is dismissed.
- Tap on Enable analytics, notice that the screen should be dismissed if the request succeeds. The coupon details screen should reload its Amount field.
- Try again with the internet connection off. Tap on Enable analytics should not dismiss the screen and display a notice about the error instead.

### Screenshots

https://user-images.githubusercontent.com/5533851/158966104-a40efcbd-10be-4592-9f98-b3dac8173a37.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift [hunk 1]
```diff
@@ -166,6 +167,13 @@ struct CouponDetails: View {
             }
             .background(Color(.listBackground))
             .ignoresSafeArea(.container, edges: [.horizontal, .bottom])
+            .sheet(isPresented: $showingEnableAnalytics) {
+                EnableAnalyticsView(viewModel: .init(siteID: viewModel.siteID),
+                                    presentingController: noticePresenter.presentingViewController,
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift:172]: This looks a bit like a hack; we can send the hosting controller to `CouponDetails` and use it here instead, but I'm not sure I like it either.

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetailsViewModel.swift [hunk 2]
```diff
@@ -95,7 +98,7 @@ final class CouponDetailsViewModel: ObservableObject {
         hasErrorLoadingAmount = false
         // Get "ancient" date to fetch all possible reports
         let startDate = Date(timeIntervalSince1970: 1)
-        let action = CouponAction.loadCouponReport(siteID: coupon.siteID, couponID: coupon.couponID, startDate: startDate) { [weak self] result in
+        let action = CouponAction.loadCouponReport(siteID: siteID, couponID: coupon.couponID, startDate: startDate) { [weak self] result in
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetailsViewModel.swift:101]: just curious about this change, is it possible for the coupon site ID to be different from the logged-in site ID?

File: WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+        let font: UIFont = .body
+        let foregroundColor: UIColor = .text
+        let linkColor: UIColor = .textLink
+        let linkContent = Localization.contactSupport
+
+        let paragraphStyle = NSMutableParagraphStyle()
+        paragraphStyle.alignment = .center
+
+        let attributedString = NSMutableAttributedString(
+            string: String(format: "%@ %@", Localization.needSomeHelp, linkContent),
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift]: nit: how about including the link variable in `Localization.needSomeHelp` as a format? like  `static let needSomeHelp = NSLocalizedString("Need some help? #%1$@", comment: "Message format on enable analytics screen for support. The %@ placeholder is a URL with more information.")` in case the order is different in certain languages

File: WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+
+    /// The presenter to display notice when enabling analytics succeeds or fails.
+    private let noticePresenter: DefaultNoticePresenter
+
+    /// Keeping a reference to the presenting controller to present notice and contact support
+    private let presentingController: UIViewController?
+
+    /// The attributed string to display for the contact support button
+    /// Essentially is a message with the Contact Support text highlighted
+    private var contactSupportAttributedString: NSAttributedString {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift:23]: nit: maybe this can be a lazy var since the logic is not trivial?

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+@testable import WooCommerce
+
+final class EnableAnalyticsViewModelTests: XCTestCase {
+
+    func test_enableAnalytics_triggers_onSuccess_if_request_succeeds() {
+        // Given
+        let sampleSiteID: Int64 = 135
+        let stores = MockStoresManager(sessionManager: .makeForTesting())
+        let viewModel = EnableAnalyticsViewModel(siteID: sampleSiteID, stores: stores)
+        var onSuccessTrigged = false
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift]: super nit:
```suggestion
        var onSuccessTriggered = false
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+        XCTAssertTrue(onSuccessTrigged)
+        XCTAssertFalse(onFailureTriggered)
+    }
+
+    func test_enableAnalytics_triggers_onSuccess_if_request_succeeds_on_second_try() {
+        // Given
+        let sampleSiteID: Int64 = 135
+        let stores = MockStoresManager(sessionManager: .makeForTesting())
+        let viewModel = EnableAnalyticsViewModel(siteID: sampleSiteID, stores: stores)
+        var onSuccessTrigged = false
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift]: similar nit:
```suggestion
        var onSuccessTriggered = false
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+        XCTAssertTrue(onSuccessTrigged)
+        XCTAssertFalse(onFailureTriggered)
+    }
+
+    func test_enableAnalytics_triggers_onFailure_if_request_fails_on_both_tries() {
+        // Given
+        let sampleSiteID: Int64 = 135
+        let stores = MockStoresManager(sessionManager: .makeForTesting())
+        let viewModel = EnableAnalyticsViewModel(siteID: sampleSiteID, stores: stores)
+        var onSuccessTrigged = false
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift]: similar nit:

```suggestion
        var onSuccessTriggered = false
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift [hunk 8]
```diff
@@ -0,0 +1,105 @@
+import XCTest
+@testable import enum Yosemite.SettingAction
+@testable import WooCommerce
+
+final class EnableAnalyticsViewModelTests: XCTestCase {
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/EnableAnalyticsViewModelTests.swift:5]: nice having these tests!

**Review by jaclync — APPROVED** [review]
LGTM! :shipit: 

> The API request to toggle analytics settings doesn't work very consistently: if the value in the request is different from the current setting value, the request always fails on first try and succeeds on the second time.

This is unfortunate 😓 I think the WC Admin repo is being merged to core recently, you can file an issue in core (with [1.1k existing issues](https://github.com/woocommerce/woocommerce/issues)) and also ask around in this channel p1595167833001300-slack-CB0GAP5EK

---

While testing the following steps:
* Tap on Contact Support, notice that the support flow is presented properly.
* Tap on Not now, notice that the screen is dismissed.

The "Not now" button somehow isn't tappable after dismissing from Contact Support page. If I scroll the modal a bit, then the button is tappable again so this issue isn't blocking the user. The modal can also be swiped to dismiss. Not sure if it's some weird SwiftUI issue 🤔

File: WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift (hunk 3 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift]: Good idea! Updated in 258d9c129f63d53bea3a4fd35671e9db57bfb38b.

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetailsViewModel.swift (hunk 2 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetailsViewModel.swift:101]: I believe the site IDs have to always match since we're fetching coupons by site ID. The reason why I extracted site ID to a separate property is because I need to access it from the view too 😅

File: WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift (hunk 4 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Coupons/EnableAnalytics/EnableAnalyticsView.swift:23]: I don't think we can use a lazy property since accessing it mutates the struct 🤔 I read [somewhere](https://oleb.net/blog/2015/12/lazy-properties-in-structs-swift/) that there's a workaround for that but I don't think the complication is worth it in this case.

**Comment by itsmeichigo** [comment]
Thank you @jaclync for the review! 

> The "Not now" button somehow isn't tappable after dismissing from Contact Support page. If I scroll the modal a bit, then the button is tappable again so this issue isn't blocking the user. The modal can also be swiped to dismiss. Not sure if it's some weird SwiftUI issue

This seems to be an issue with SwiftUI, I might need to wrap the contact page in a SwiftUI view to present it the SwiftUI way instead. But since it's still possible to dismiss the modal, I'm merging this PR and will fix the issue in the next PR.
