### PR TITLE
Unit tests fail for non-US regions

### LINKED ISSUE #1550: Unit tests fail for non-US regions
There are currently ~25 unit tests failing when the region is changed. 

Steps to reproduce:
1. Set your simulator Settings app to use Chinese (Traditional) and set the region to Hong Kong. 
2. Run the unit tests.

Approximately 25 unit tests are failing because they are using non-localized strings as the expected result.

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #1550 

## Steps to reproduce
0. Check out the `develop` branch.
1. Set your simulator Settings app to use Chinese (Traditional) and set the region to Hong Kong.
2. Run the unit tests locally on Xcode.

## Testing
Do Not rely on CI for this. Tests pass in CI because the Xcode region (probably) defaults to the US.

0. Check out this branch.
1. Set your simulator Settings app to use Chinese (Traditional) and set the region to Hong Kong.
2. Run the unit tests locally on Xcode.

Expectation: 8 unit tests in `DateWooTests` fail. These remaining 8 failing unit tests are expected to pass once the `NSLocalizedString`s have been translated.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift [hunk 1]
```diff
@@ -4,81 +4,108 @@ import XCTest
...
+                                           comment: "A unit test string for time intervals")
+        let almostHourAgo = NSLocalizedString("Updated 59 minutes ago",
+                                              comment: "A unit test string for a plural time interval in minutes")
+        let hourAgo = NSLocalizedString("Updated 1 hour ago",
+                                        comment: "A unit test string for a singular time interval")
+        let nineAgo = NSLocalizedString("Updated 9 hours ago",
+                                        comment: "A unit test string for a plural time interval in hours")
+        let almostDayAgo = NSLocalizedString("Updated 23 hours ago",
+                                             comment: "A unit test string for time interval just under 1 day")
+        let dayAgo = NSLocalizedString("Updated 24 hours ago",
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: I'd suggest using "Updated %ld hours ago" format (and its variants in `Localizable.strings`) and `String.localizedStringWithFormat` to create the expected string. these strings "Updated # minutes/hours ago" have the number hardcoded, and because they don't exist in `Localizable.strings` these strings aren't localizable and will always be in English.

File: WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift [hunk 2]
```diff
@@ -4,81 +4,108 @@ import XCTest
...
-        XCTAssertNotEqual(oneDayAgo.relativelyFormattedUpdateString, "Updated 24 hours ago")
+        XCTAssertNotEqual(oneDayAgo.relativelyFormattedUpdateString, dayAgo)
     }
 
     func testUpdateStringWorksForIntervalsOverOneDay() {
 
         // Skip verifying the time part of the resulting string because of TZ madness
 
+        // Create and translate the exact phrase for the expected result
+        let updatedOct = NSLocalizedString("Updated on Oct 10, 2018",
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: similar to the comment above, this string isn't in `Localizable.strings` and thus not localizable. you can use `NSLocalizedString("Updated on %@", ...)` and `String.localizedStringWithFormat` to create the expected string

File: WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift [hunk 3]
```diff
@@ -4,81 +4,108 @@ import XCTest
...
+                                           comment: "A unit test string that checks the string date formatter works properly." +
+            "Please translate this using your language's medium-length date abbreviation (if you have one).")
+        let updatedFeb = NSLocalizedString("Updated on Feb 2, 2016",
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: same comment as above!

File: WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift (hunk 1 above)
Comment (mindgraffiti) [reply WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: The current expectation is that these 8 unit tests in DateWooTests will fail. They will pass once the NSLocalizedStrings have been translated. They will exist in `Localizable.strings` once this PR is merged and a build is created. Part of the build process is to run the script and find new strings that need localized and set them up for translation.

The point of creating the localized strings with the times hardcoded is to have a fully translated string that was not formatted or modified by the `relativelyFormattedString` method. That way, a "hardcoded string" for the expected result is compared to the actual result from the `relativelyFormattedString` method. If I create a `NSLocalizedString` that added an argument for the minutes and hours, it would be incorrect because it doesn't account for pluralizations. If I further modified the `NSLocalizedString` to account for the pluralization, then all I am doing is re-creating the `relativelyFormattedUpdateString` method, when what I really want is to compare the actual output to the expected output.

Does that make sense?

**Comment by mindgraffiti** [comment]
Deleted the unit test that wasn't good and replaced with a couple of new ones. Ready for a second review!

File: WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: I feel it's a bit odd to have new localizable strings from the unit tests in general (there might be exceptions), I'm not sure if we want to put the (community) effort localizing strings just for internal unit tests. This also creates a dependency for our unit tests on the external translation - what if the hard-coded strings are translated to a different string from the localized format + value? If we use the existing localizable strings in unit tests, even if some strings haven't been translated yet they will at least match and pass in tests.

Looking at this test class, it seems to me that it's trying to test the "Updated ... ago" string with different units and unit plural formats given different timestamps. I feel like testing with the localized format + value would achieve the goals of this test case.

@pmusolino what do you think?

Comment (mindgraffiti) [reply WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: I think these unit tests have the same problem as [this one](https://github.com/woocommerce/woocommerce-ios/pull/1552/commits/af6fc028c0389a07b489fd2452392e252b3f152e). Would it be better to remove these altogether? 

> (community) effort

As an aside, our translations are done by a professional service. I would consider it money well spent if the unit tests are alerting us to a format that has been altered and doesn't suit multiple languages. (That is, if these unit tests are useful in the first place.)

Comment (pmusolino) [reply WooCommerce/WooCommerceTests/Extensions/DateWooTests.swift]: In doing so, is there not a risk that the work of the translators will affect the test result?

**Comment by mindgraffiti** [comment]
Updated unit tests to use existing localizations. Please run unit tests in your region? I tested it in English / `en_US` and Chinese (Hong Kong) `zh-HK`

@jaclync @pmusolino
