### PR TITLE
REST API: Clear login error notification after successful login with site credentials

### LINKED ISSUE #8786: REST API: Scheduled notification for failed logins not cleared after logged in
As reported in pe5sF9-15E-p2#comment-1636 - we are still displaying local notification 24hrs after a failed login even though the user logs in successfully with site credentials afterward.

The problem is that we cleared scheduled notifications after successful logins with WPCom, but not with site credentials only.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #8786 

## Description

This PR adds a fix to clear any scheduled login error notifications after site credential login succeeds. This was handled for WPCom login but missed for this new case.

## Testing instructions

- Update the [duration](https://github.com/woocommerce/woocommerce-ios/blob/d6122655050ef973c1281307ae3cc86481ef6447/WooCommerce/Classes/Authentication/AuthenticationManager.swift#L611) for scheduled login error notifications for testing purpose.
- Set `enableSiteAddressLoginOnly` in `AuthenticationManager` to `true`
- Reinstall the app to clear any previous notifications permission state if needed
- Skip the onboarding if needed
- Tap either CTA
- If choosing to log in with a site address, enter an invalid site address
- Enter an invalid WP.com email to trigger a local notification scheduling with an event in the console `login_local_notification_scheduled`
- Enter the valid address a self-hosted site of after the error
- Quickly continue to enter the correct credentials to log in, then put the app to the background since we don't support local notifications in the foreground --> a local notification should **not** be shown after the duration you set in `AuthenticationManager`

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/AuthenticationManager.swift [hunk 1]
```diff
@@ -777,6 +777,11 @@ private extension AuthenticationManager {
         }
         let checker = PostSiteCredentialLoginChecker(applicationPasswordUseCase: useCase)
         checker.checkEligibility(for: siteURL, from: navigationController) { [weak self] in
+            // clear scheduled local notifications
+            if ServiceLocator.featureFlagService.isFeatureFlagEnabled(.loginErrorNotifications) {
```
Comment (jaclync) [inline WooCommerce/Classes/Authentication/AuthenticationManager.swift]: super nit: can we use the `self.featureFlagService`?

**Review by jaclync — APPROVED** [review]
LGTM 🚢

File: WooCommerce/Classes/Authentication/AuthenticationManager.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/Authentication/AuthenticationManager.swift]: Yes - updated in 25f9f14da99e349add2b7306c48eeb4c8901c7d1.
