### PR TITLE
[Woo POS] Product list: implement infinite scroll with threshold based trigger

### LINKED ISSUE #14735: [Woo POS] Pulling to refresh when the current items page height is shorter than view height triggers API request twice
**Describe the bug**

Pulling to refresh should only one API request, but it's currently triggering 2 when the items are not filling the view height due to trigger of infinite scroll in addition to pull-to-refresh.

**To Reproduce**

- Switch to a store eligible for POS, and only has purchasable simple/variable products < 1 page like 1-2
- Go to Menu > Point of Sale mode
- After the initial items are loaded, pull to refresh --> check the network requests, notice that 2 requests are triggered from the pull-to-refresh

**Screenshots**

https://github.com/user-attachments/assets/1d9cd8cf-b9f0-4238-af3e-7d0c42d6f516

**Expected behavior**

Only one API request should be made from any pull-to-refresh.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Pro 11in
- iOS version: iOS 18.0
- WooCommerce iOS version: 21.3

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #14735 

## Description

This PR implements a new infinite scroll mechanism, to trigger loading the next page by detecting scroll positions past 70% of the scrollable height. The trigger is emitted once per content height for a successful load. Please feel free to suggest any improvements or alternative approaches to make it more robust and easier to read/use!

There are 3 key parameters for the infinite scroll trigger:
- `scrollViewHeight`: scroll view height
- `contentHeight`: scroll view content height, could be shorter or taller than the scroll view height
- Scroll position. Currently, we use the scroll view content's background maxY to determine the scroll offset. I found it easier to visualize by defining `scrollPosition` as `contentHeight - maxY`. At the top without any scrolling, `scrollPosition` is `0`. At the end of the scroll, `scrollPosition` is the scrollable height `contentHeight - scrollViewHeight`.
  - `maxY` also needs to be measured relative to the scroll view frame instead of the global view hierarchy. This is achieved by specifying a namespace in GeometryReader proxy's frame getter.

Therefore, infinite scroll can be triggered at 70% of the scrollable height for example. This is implemented in `ThresholdInfiniteScrollTriggerDeterminer`, behind a protocol. Some details:

- In order not to trigger `loadMore` more than once per content state, the implementation keeps track of the content height of the last trigger. If `loadMore` fails, this state is reset. In order to catch the failure case, `loadNextItems` is updated to be throwable.
- If the content height is shorter than the scroll view height, infinite scroll is never triggered. If we want to handle this edge case, which is unlikely to happen if we don't do client-side filtering with page size more than 10 (tested on the tallest 13in iPad Pro portrait mode with the smallest font size), we might want to keep loading the next page until the scroll view is filled at initial load. At the team meeting yesterday, we decided not to do this and will use a page size that fills the scroll view given a full page of data.

### Infinite Scroll Functionality:

Infinite scroll is only implemented in the root item list at the moment.

* Added `InfiniteScrollTriggerDeterminable` protocol and `ThresholdInfiniteScrollTriggerDeterminer` class to determine when to trigger infinite scroll based on scroll metrics. (`WooCommerce/Classes/POS/Presentation/Infinite Scroll/InfiniteScrollTriggerDeterminable.swift`)
* Introduced `InfiniteScrollView` struct to support infinite scrolling by triggering a load more action when the user scrolls near the bottom. (`WooCommerce/Classes/POS/Presentation/Infinite Scroll/InfiniteScrollView.swift`)
* Added a view modifier to measure the height of a view and call a callback with the height value. (`WooCommerce/Classes/View Modifiers/View+Measurements.swift`)

### Error Handling Improvements:

* Modified `PointOfSaleItemsControllerProtocol` and `PointOfSaleAggregateModelProtocol` to make `loadNextItems` method throwable, so that the infinite scroll trigger determiner can reset its states if needed. (`WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift`, `WooCommerce/Classes/POS/Models/PointOfSaleAggregateModel.swift`) [[1]](diffhunk://#diff-b34ef3931ae78bf4b51520edbe9c11abd6bf36d31dfce4882f3b621c5a7e2af9L11-R11) [[2]](diffhunk://#diff-b9d72a7102bb1a5778e338bc3b2046cd3490aa8dc893fc3a05f18cb655ce698cL27-R27)
* Updated `PointOfSaleItemsController` to throw an error when loading next items fails. (`WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift`)

### Partial first page

- Switch to a store eligible for POS, and only has purchasable simple/variable products < 1 page like 1-2
- Go to Menu > Point of Sale mode
- After the initial items are loaded, pull to refresh --> check the network requests to make sure only 1 products network request is made

### Multi-page products

🗒️ An easier to test infinite scroll is by reducing the page size from 100 to 25 [here](https://github.com/woocommerce/woocommerce-ios/blob/efe8572e3c69a04a66bc76d2e41b855bb5ff02aa/Networking/Networking/Remote/ProductsRemote.swift#L651). I will save this change on the page size to a separate PR along with removing local filtering.

- Switch to a store eligible for POS, and has multiple pages of purchasable simple/variable products
- Go to Menu > Point of Sale mode
- Scroll near 70% of the scrollable height --> the next page of data should be loaded
- Try scrolling up and down to ensure the next page load is at the right timing
- Try pulling to refresh --> the first page of data should be reloaded

## Testing information

- [x] @jaclync tests that variations work as before (no pagination support)

### Partial first page

https://github.com/user-attachments/assets/2b303c21-1cb9-4d20-a2f5-660980664ffd

### Multi-page products

https://github.com/user-attachments/assets/c0007d77-926d-42a1-a288-e88d3527fcf9

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleItemsControllerTests.swift [hunk 1]
```diff
@@ -198,7 +198,7 @@ final class PointOfSaleItemsControllerTests {
                                                   buttonText: "Retry")
 
         // When
-        await sut.loadNextItems()
+        try? await sut.loadNextItems()
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleItemsControllerTests.swift]: Question: I'm not sure to understand why making the `try` optional actually makes the test pass. Shouldn't we'll be falling into the catch block in the following bit?
```
catch {
  itemsViewState = .init(containerState: .error(PointOfSaleErrorState.errorOnLoadingProducts()),
                                   itemsStack: ItemsStackState(root: .loaded(currentItems),
                                                               itemStates: currentItemStates))
            throw error
}
```
Which should set the state, then throw the error, and we would catch it in a test via:
```
        do {
            try await sut.loadNextItems()
        } catch {
            #expect(itemsViewState.containerState == .error(expectedError))
        }
``` 

I've tried this and it ofc it doesn't work: We do not fall into the catch block in the test target, so the expectation for error is never checked, I just don't understand why 😁  

Shouldn't the optional make it fail silently? Or that's precisely what happens? It fails silently but the `containerState` is already set to `PointOfSaleErrorState` so we just care about the state, not if we're throwing ?

**Review by iamgabrielma — APPROVED** [review]
Thanks for working on this Jaclyn, it works great. Extracting the trigger determination to somewhere else and make it testable is 💯 

Just left a small question regarding some tests.

🚢

File: WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleItemsControllerTests.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleItemsControllerTests.swift]: I believe the optional try worked because `loadNextItems` triggers the container state to the error state synchronously, so we don't have to wait for the error to be thrown for the assertion. Moving it to do/catch as you suggested should also work, it passed for me locally and if I changed the assertion condition it failed so it was executed. do/catch looks nicer, less confusing, and Swift Testing doesn't require the XCTest extension workaround. I updated it in https://github.com/woocommerce/woocommerce-ios/pull/14833/commits/7849bbba5a8ce7e8c5c3e46e66d7d6ab4a792560.

**Comment by jaclync** [comment]
@joshheald this might have some conflicts with your work on variations pagination support, I will wait for your input on the order of merge (and if you'd like to review this PR) if you have other work in progress.

**Comment by joshheald** [comment]
@jaclync Thanks. Sorry the review request didn't go through to you, I was sure I'd pressed the button but it seems Github lied to me about sending it.

I've not looked at the code yet, but based on the description I think we've got duplicative PRs here, using different approaches. I'll review this today then we can decide which to go ahead with.

**Review by joshheald — COMMENTED** [review]
@jaclync it works well, but does add quite a lot of complexity, I think.

What do you think about going with the approach in #14827 instead? 

- The list state includes whether there are more pages or not for a given list.
- The list shows the loading cell if it's loading, or if there are more pages left. 
- When that loading cell is scrolled in to view, it triggers the next page using `onAppear`.

This avoids any use of geometry readers or thresholds for the scroll, and seems much easier to understand, IMO.

If you agree, we can close this PR and merge #14827 instead. Sorry that I didn't say I was working on this already; I started on the variations pagination and it just seemed the right time to fix the bugs we'd seen in scrolling, and I thought I'd requested a review from you when I finished it last night, it just turns out I didn't...

**Comment by jaclync** [comment]
> it works well, but does add quite a lot of complexity, I think.
> 
> What do you think about going with the approach in #14827 instead?

IMO we can merge https://github.com/woocommerce/woocommerce-ios/pull/14827 first and have this PR replace the infinite scroll behavior there. The complexity is encapsulated in the `InfiniteScrollView` itself with the trigger logic unit testing coverage, and we can swap out the view if we decide not to go with this approach. While being a simple solution, the infinite scroll trigger in https://github.com/woocommerce/woocommerce-ios/pull/14827 is when the bottom of the list is shown, instead of "near the bottom of the list," which implies the merchant would see the loading state and wait for the next page longer almost most of the time if they cannot find the item in what's already loaded. There are still other improvements in https://github.com/woocommerce/woocommerce-ios/pull/14827 like the LazyVStack and the addition of `hasMoreItems` in the state that we should go with, and we can still use `hasMoreItems` in the loaded state to check whether to load the next page in this PR.

In iOS 18, there is a better API to [observe scroll view metrics with `onScrollGeometryChange`](https://developer.apple.com/documentation/swiftui/view/onscrollgeometrychange(for:of:action:)) to replace the use of GeometryReader.

Please let me know if you have concerns about this PR, I'm fine closing this too.

> If you agree, we can close this PR and merge #14827 instead. Sorry that I didn't say I was working on this already; I started on the variations pagination and it just seemed the right time to fix the bugs we'd seen in scrolling, and I thought I'd requested a review from you when I finished it last night, it just turns out I didn't...

Sorry I didn't notice the draft PR earlier, as I mainly rely on [GitHub notifications](https://github.com/notifications) in daily work. GitHub did have some issues in my morning yesterday as I failed to submit an issue and the GitHub status page indicated some services having downtime.

**Comment by joshheald** [comment]
> IMO we can merge #14827 first and have this PR replace the infinite scroll behavior there. The complexity is encapsulated in the `InfiniteScrollView` itself with the trigger logic unit testing coverage, and we can swap out the view if we decide not to go with this approach. While being a simple solution, the infinite scroll trigger in #14827 is when the bottom of the list is shown, instead of "near the bottom of the list," which implies the merchant would see the loading state and wait for the next page longer almost most of the time if they cannot find the item in what's already loaded. There are still other improvements in #14827 like the LazyVStack and the addition of `hasMoreItems` in the state that we should go with, and we can still use `hasMoreItems` in the loaded state to check whether to load the next page in this PR.

OK, I'll wrangle that today 👍 

> Sorry I didn't notice the draft PR earlier, as I mainly rely on [GitHub notifications](https://github.com/notifications) in daily work. GitHub did have some issues in my morning yesterday as I failed to submit an issue and the GitHub status page indicated some services having downtime.

No need to apologise, it's my fault, with a little potential blame on Github

**Comment by joshheald** [comment]
OK, I've updated that to work after #14827 was merged.

I simplified `InfiniteScrollView` to just take content and a load more function – it wasn't giving any benefit to pass the loading view separately anyway, and this way the caller can decide whether to use a LazyVStack or a VStack. It also avoids some duplication of padding modifiers, etc, since everything is in the one stack.

**Comment by jaclync** [comment]
Thanks for updating the PR Josh! I was going to do it today after your PR is merged 😃
