### PR TITLE
[Store onboarding] Reload task list on task completed

### LINKED ISSUE #9172: Store onboarding: reload tasks after dismissing a modal from an onboarding action
Steps to reproduce:

- Log in to a store with pending onboarding tasks that present a modal (e.g. Launch store, Get paid, Customize domain tasks)
- In the My store tab, tap on a pending task that presents a modal
- Complete the task in the modal
- Dismiss the modal

What happened: the onboarding tasks aren't refreshed so that the task is still shown as incomplete until we pull down to refresh or go to another tab then back
Expected: the onboarding tasks should be refreshed after dismissing a modal from an onboarding action

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #9172

## Description

Reload the onboarding task list upon completing tasks by adding a callback. 

## Testing instructions

Prerequisite: Create a new WPCOM WooCommerce site 

- Launch and log in using a WPCOM site
- Ensure that you see the onboarding list in dashboard
- Tap "Launch your store" and finish the task.
- When you see the "Dashboard" screen, notice that the task list is already reloaded and the "Launch your store" task is marked as completed. 
- Validate the same for "Add your first product" and "Customize your domain" tasks

**Known issues**
- We cannot detect when the "Get paid" task gets completed as that is a web view. So the task list won't be reloaded automatically for that.
- For the "Customize your domain" task, the backend doesn't mark it as completed immediately after purchasing a domain. So, reloading the task list doesn't update the task. Waiting for confirmation - p1679456923870899-slack-C045CUK1Y3U

## Screenshots
LaunchStore

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift [hunk 1]
```diff
@@ -14,10 +14,14 @@ final class StoreOnboardingCoordinator: Coordinator {
     private var paymentsSetupCoordinator: StoreOnboardingPaymentsSetupCoordinator?
 
     private let site: Site
+    private let onTaskCompleted: (() -> Void)?
 
-    init(navigationController: UINavigationController, site: Site) {
+    init(navigationController: UINavigationController,
+         site: Site,
+         onTaskCompleted: (() -> Void)? = nil) {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift]: nit: does it make sense to make this non-optional since it seems always implemented? it can also be helpful for analytics.

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift [hunk 2]
```diff
@@ -8,6 +8,8 @@ final class StoreOnboardingLaunchStoreCoordinator: Coordinator {
     private let site: Site
     private let isLaunched: Bool
 
+    var onStoreLaunched: (() -> Void)? = nil
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift]: nit: can this be passed in the initializer so that it can't be changed externally? similar to `StoreOnboardingCoordinator`

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift [hunk 3]
```diff
@@ -19,6 +19,8 @@ final class DomainSettingsCoordinator: Coordinator {
     private let source: Source
     private let analytics: Analytics
 
+    var onDomainPurchased: (() -> Void)? = nil
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift]: nit: similar to the previous comment, can this be passed in the initializer so that it can't be changed externally?

**Review by jaclync — APPROVED** [review]
I meant to approve the PR earlier, just noticed that it wasn't sent

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingCoordinator.swift]: Done in https://github.com/woocommerce/woocommerce-ios/pull/9249/commits/4e1f2f1080743280c11d770433d20e4ac6e5cd63

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift (hunk 2 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingLaunchStoreCoordinator.swift]: Done in f3fa739e243d9596d5bb9aff0b8764496d7436e4

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift (hunk 3 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/Domains/DomainSettingsCoordinator.swift]: Done in a2bc8540d11161bd9b385da3ee7d5492e5de4754
