### PR TITLE
Subscriptions: Update logic for Report Subscription Issue button

### LINKED ISSUE #13564: Subscriptions: "Report Subscription Issue" button not working
Identified in an iOS quality walkthrough - Internal - p91TBi-bPj-p2

#### Issue
Subscriptions: The “Report Subscription Issue” button is unresponsive when tapped. (Only visible for Jetpack-connected stores.)

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #13564

## Description

On Jetpack-connected stores, when going to Hub menu > Subscriptions, the "Report Subscription Issue" button was not working.

This happened because the code that initialized the button handling was set in the `SubscriptionView`'s hosting controller, and there was [a recent Hack Week work](https://github.com/woocommerce/woocommerce-ios/pull/12283) that updated the Hub menu's navigation logic from using the hosting controller, to directly using the View. As such, the logic to set the button handling wasn't being run.

As the button is meant to open support form, this PR updates the logic so that the button handling is added directly inside the View, thus restoring the functionality. This is the same logic as used in other places such as `BlazeCampaignCreationForm` or `UnavailableAnalyticsView`.

The `SubscriptionsHostingController` itself is not deleted because it is still used in other places.

## Steps to reproduce

1. Login to a Jetpack-connected store,
2. Go to Hub Menu > Subscriptions,
3. Tap Report Subscription Issue,
4. Ensure that the support form is opened.

https://github.com/user-attachments/assets/d543e181-e294-41f9-9cdc-05ba9cd22f50

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsView.swift [hunk 1]
```diff
@@ -71,6 +64,26 @@ struct SubscriptionsView: View {
...
+                        viewModel: SupportFormViewModel())
+            .toolbar {
+                ToolbarItem(placement: .confirmationAction) {
+                    Button(Localization.done) {
+                        isShowingSupport = false
+                    }
+                }
+            }
+        }
+        .navigationViewStyle(.stack)
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsView.swift]: Nit: Please replace the deprecated `NavigationView` with `NavigationStack`.

**Review by itsmeichigo — APPROVED** [review]
Thanks for the fix! I left a nitpicking regarding the deprecate `NavigationView`.

Also - this issue should happen to WPCom sites, not JCP sites as mentioned in the PR description and the GH issue. The subscription screen is only available for WPCom sites.

File: WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsView.swift (hunk 1 above)
Comment (hafizrahman) [reply WooCommerce/Classes/ViewRelated/Upgrades/SubscriptionsView.swift]: Thanks, I updated SubscriptionsView and UpgradesView on https://github.com/woocommerce/woocommerce-ios/pull/13577/commits/89765130d79a35b6d102687a4106d41f4dcc3c1d

There are still other usages of the combination of `NavigationView` and `.navigationViewStyle(.stack)` in the app, but I didn't have time to smoke test all of them so I'm keeping them unchanged for now.
