### PR TITLE
[Woo POS] Specialize item list empty and error cases 

### LINKED ISSUE #12846: [Woo POS] M2 handle unhappy path: Fail to fetch products for POS
Ref: p1716432162915869-slack-C070SJRA8DP

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #12846

## Description
This PR specializes further the different cases the `ItemList` can be at, by passing associated values and modelling the data we'll display in the view when we land on each case.

| Loading | Loaded | 
|--------|--------|
| simulator_screenshot_28B15C8C-1A0C-46EC-BFC0-A175491876A9 | Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-07-11 at 11 20 37 |   

| Empty | Error |
|--------|--------|
| Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-07-11 at 11 20 41 | Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-07-11 at 11 21 54 |

## Changes
`ItemListState` cases now have associated values: `empty(EmptyModel)`, `loaded([POSItem])`, and `error(ErrorModel)` which will be passed down to the views as needed. These hold either the list of items that have been loaded or the different data to be displayed.

#### Case 1: Loading/Loaded
* Run the POS normally, observe that products are loading, then loaded, and re-loaded on pull-to-refresh

#### Case 2: Empty
* Update the `reload()` method to return a list of empty products:
```diff
    @MainActor
    func reload() async {
        do {
            state = .loading
-           let newItems = try await itemProvider.providePointOfSaleItems()
+           var newItems = try await itemProvider.providePointOfSaleItems()
+           newItems = []
            if newItems.count == 0 {
```
* Run the POS normally, observe that products are loaded and the `empty view` is shown on pull-to-refresh

#### Case 3: Error
* Update the `reload()` method to throw an error:
```diff
    @MainActor
    func reload() async {
        do {
            state = .loading
            let newItems = try await itemProvider.providePointOfSaleItems()
+          throw NSError(domain: "", code: 0)
            if newItems.count == 0 {
```
* Run the POS normally, observe that products are loaded and the `error view` is shown on pull-to-refresh

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift [hunk 1]
```diff
@@ -42,25 +27,135 @@ final class ItemListViewModel: ObservableObject {
...
+                                      buttonText: Constants.failedToLoadButtonTitle)
+            state = .error(itemListError)
         }
     }
 
     @MainActor
     func reload() async {
         do {
+            // TODO:
+            // Resolve duplication with populatePointOfSaleItems()
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:52]: I'll resolve this duplication separately, since requires a bit more testing around updating products via the web/app and confirming that the reload works as expected.

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift [hunk 2]
```diff
@@ -42,25 +27,135 @@ final class ItemListViewModel: ObservableObject {
...
             state = .loading
             let newItems = try await itemProvider.providePointOfSaleItems()
-            // Only clears in-memory items if the `do` block continues, otherwise we keep them in memory.
-            items.removeAll()
-            items = newItems
-            state = .loaded
+            if newItems.count == 0 {
+                let itemListEmpty = EmptyModel(title: Constants.emptyProductsTitle,
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:56]: Should we create these directly inside of the struct? Sort of
```
func copy() -> EmptyModel { .. }
```

Would help to clean-up the method, despite being pretty simple right now 🤔

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift [hunk 3]
```diff
@@ -42,25 +27,135 @@ final class ItemListViewModel: ObservableObject {
...
+    struct EmptyModel: Equatable {
+        // TODO:
+        // Differentiate between empty with no products vs empty with no eligible products
+        // https://github.com/woocommerce/woocommerce-ios/issues/12815
+        // https://github.com/woocommerce/woocommerce-ios/issues/12816
+        let title: String
+        let subtitle: String
+        let hint: String
+        let buttonText: String
+    }
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:120]: Those seem extremely similar, I'm thinking we could use a single model for both since there's no need to pass something like `Error` to the UI and we may use only strings and images. Thoughts?

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 1 above)
Comment (staskus) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:52]: No problem. Out of curiosity, why removing one of `reload()` or `populatePointOfSaleItems()` could cause problems? They look to be doing the same thing or am I missing something?

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 2 above)
Comment (staskus) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:56]: > Would help to clean-up the method, despite being pretty simple right now 🤔

True. Yes, for example, we could have something like `static var noProducts: EmptyModel` within `EmptyModel`, so it could be passed as `.empty`, maybe it would simplify tests as well. 

However, I think it's also fine to clean it up and organize when we work specifically on empty states since we will also need to add additional cases and actions 👍  So see what makes sense the most to you.

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 3 above)
Comment (staskus) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:120]: Good point 🤔. Are they extremely similar or are they the same thing? If business logic and UI-wise we differentiate between error (cannot fetch), and empty (no eligible product) states, I think it's fine not to over-optimize and allow them to be described by different structs. 

However, if they are exactly the same, and we only send different image names, titles, and subtitles to view, then we could have a single struct.

If we don't know yet we can keep two separate ones, and optimize later.

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift [hunk 4]
```diff
@@ -4,21 +4,6 @@ import protocol Yosemite.POSItem
...
-        // Differentiate between loaded with products vs with no products vs with no eligible products
-        // https://github.com/woocommerce/woocommerce-ios/issues/12815
-        // https://github.com/woocommerce/woocommerce-ios/issues/12816
-        case loaded
-        // TODO:
-        // https://github.com/woocommerce/woocommerce-ios/issues/12846
-        case error
-    }
 
     @Published private(set) var items: [POSItem] = []
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:8]: Not needed anymore

File: WooCommerce/WooCommerceTests/POS/ViewModels/ItemListViewModelTests.swift [hunk 5]
```diff
@@ -49,54 +49,82 @@ final class ItemListViewModelTests: XCTestCase {
...
+        // Then
+        XCTAssertEqual(sut.state, .loaded([expectedItem]))
+    }
+
+    func test_itemListViewModel_when_populatePointOfSaleItems_has_no_items_then_state_is_loaded_empty() async {
+        // Given
+        let itemProvider = MockPOSItemProvider()
+        itemProvider.shouldReturnZeroItems = true
+        let sut = ItemListViewModel(itemProvider: itemProvider)
+        let expectedResult = ItemListViewModel.EmptyModel(title: "No products",
```
Comment (staskus) [inline WooCommerce/WooCommerceTests/POS/ViewModels/ItemListViewModelTests.swift:68]: If as you said you move these static model descriptions to `EmptyModel`, you could use it here as well instead of retyping all these strings.

**Review by staskus — APPROVED** [review]
👍 Looks good, works well. I left a few non-blocking comments. 

Feel free to address some of them here or in a different PR. If you make more larger changes to this PR - re-request review to check them out. Thanks!

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 1 above)
Comment (bozidarsevo) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:52]: I suppose we could switch to using just one of those since `populatePointOfSaleItems()` is called before the view appears, and the only difference is that `reload()` "clears" the in-memory items if it the `providePointOfSaleItems` finishes without throwing, and if it throws in `populatePointOfSaleItems()` the `items` were already empty.
Maybe we can have 1 method that has a parameter like `initialLoad: Bool`:
`func loadItems(initialLoad: Bool)`

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:56]: > However, I think it's also fine to clean it up and organize when we work specifically on empty states since we will also need to add additional cases and actions

Yeah, I'd say let's refactoring it later when we actually need it 👍

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:120]: > If business logic and UI-wise we differentiate between error (cannot fetch), and empty (no eligible product) states, I think it's fine not to over-optimize and allow them to be described by different structs.

That's a good thought, while what we present in the UI might be similar, these cover different cases and will have different business logic in the CTAs, so for now let's keep them separate.

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:52]: > Out of curiosity, why removing one of reload() or populatePointOfSaleItems() could cause problems? They look to be doing the same thing or am I missing something?

Good question, I had to rethink this again 🤔 Right now the only difference is that we clear the loaded items on `reload()`, and we do not do it on `populatePointOfSaleItems()`  because it's only called once on model initialization, so it doesn't need clearing. 

I think this difference was more important previously, when we were fetching products from storage rather than from the network as we do now, since could be discrepancies between what was stored and what was fetched, however, now there shouldn't be much difference since in both cases we would have a new fresh list of the latest 100 simple products from the remote. 

> Maybe we can have 1 method that has a parameter like initialLoad: Bool:
func loadItems(initialLoad: Bool)

Yes, right now the only difference would be UI wise, as the "loading" state would be the same for the first time we enter in the POS mode, as well as each time we reload, and we want these to be different.

I'll keep it for a different PR just so we don't mix changes on this one and can improve the tests as well, but I'd say that right now they're doing effectively the same thing, we should just handle the loading state differently, and this can be done when we tackle the different views.

Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:52]: Logged here: https://github.com/woocommerce/woocommerce-ios/issues/13307

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/213">19.5</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift (hunk 4 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:8]: Are you referring to `@Published private(set) var items: [POSItem] = []`? There's a reference to this property from the dashboard when we sync the order, so I can't remove it 😅  :

```
private extension PointOfSaleDashboardViewModel {
    func startSyncingOrder(cartItems: [CartItem]) {
        totalsViewModel.startSyncingOrder(with: cartItems,
                                          allItems: itemListViewModel.items)
    }
}
```
I'm not quite sure to understand why we need to pass all products when synchronizing, I think could be just because we're reusing `app` logic for the moment that needs those. Maybe @bozidarsevo has more context here.

Comment (staskus) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:8]: Got it, I haven't seen that it was used this way. Ideally, we would rely on the state since it also contains items. 

We could have something like:

```
var items: [POSItem] {
   switch state {
        case let .success(items)
            return items
         default
             return []
   }
}

Comment (bozidarsevo) [reply WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:8]: > all products

yep, we need to have list of all products for the order syncing logic
