### PR TITLE
[Woo POS] Analytics: Fix clear cart event called incorrectly

### LINKED ISSUE #15194: [Woo POS] Clear cart event is tracked when we tap `New Order`
## Description
`pos_clear_cart_tapped` is tracked when tapping `New order` after a payment, along with `pos_create_new_order_tapped`. I think only the latter should be tracked.

## Repro
While debugging in Xcode, view the analytics logs

1. Open POS and make an order
2. Take payment for the order
3. Tap `New order`
4. Observe that both analytics events are logged.

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #15194 

## Description
This PR fixes the problem with the `pos_clear_cart_tapped` event discovered during testing, where this event would also be wrongly tracked when the merchant starts a new order from the success view.

This is a side-effect of calling the event in the `removeAllItemsFromCart()` function within the aggregate model, as this function is also used for other logic, like emptying the existing cart before proceeding to start a new order.

I've moved the track event closer to where it actually happens, which is in the view when the button is tapped.

## Testing
1. In POS, add `pos_clear_cart_tapped` to the console's search
2. Add some items to the cart, tap "Clear", and observe the event is tracked:
```
🔵 Tracked pos_clear_cart_tapped, properties: [store_id: c5bd46cc-1804-4f7b-badb-bb98c449127f, was_ecommerce_trial: false, site_url: https://indiemelon.mystagingwebsite.com, is_wpcom_store: false, blog_id: -1, plan: ]
```
3. Go through the payment flow, and on the success view tap on "new order"
4. Observe the event is no longer tracked.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/238">21.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Presentation/CartView.swift [hunk 1]
```diff
@@ -47,6 +47,7 @@ struct CartView: View {
 
                     Button {
                         posModel.removeAllItemsFromCart()
+                        ServiceLocator.analytics.track(.pointOfSaleClearCartTapped)
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CartView.swift:50]: I don't love that we use `ServiceLocator` within the view (not just here). Of course, if/until we decide to decouple POS from the main application that wouldn't change anything. I guess that wouldn't be a hard refactoring, we would need to inject dependencies through the environment.

**Review by staskus — APPROVED** [review]
Nice, I agree with moving the event as close to the source as possible 👍

File: WooCommerce/Classes/POS/Presentation/CartView.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CartView.swift:50]: Yeah, I don't like to see the ServiceLocator being called on those neither, but as you mention the potential refactor would be minimal. 

There are several views that are only driven by the aggregate model, so one of my thoughts around this was if was worth to expose either the analytics dependency in the aggregate model (make it just `private(set)`) or have some `track(Event)` function in the aggregate where we pass all of those and handle events there through the internal dependency. One of the reasons I didn't is we don't solve anything regarding unit testing in most cases, but might be alternatives indeed. Knowing for sure if we're going to decouple from the app or not would have definitely helped in a lot of these decisions 😅
