### PR TITLE
Coupons: add coupon discard alert

### LINKED ISSUE #6836: [Coupons] - No discard alert when swiping down to cancel editing a coupon
**Describe the bug**
When a user uses swipe-down gesture to close the edit coupon screen after making some changes, there are no alerts about discarding the changes. On some screens on the app, this action would trigger an alert (e.g. Shipping Address screen on Orders)

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon > Edit Coupon
3. Make some changes on the coupon and swipe down to cancel
4. There's no alert warning about discarding the changes

**Expected behavior**
When changes have been made, it would be better if there is a warning about discarding it when the swipe down gesture is used as the swipe down could be accidental from the user.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: AppCenter build pr6809-84ae456

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #6836 by defining a discard dialog before the merchant dismisses the Edit coupon view from a swipe-down gesture. This is made possible through wrapping the `AddEditCoupon` SwiftUI view in a `UIHostingController`, where we can implement the `UIAdaptivePresentationControllerDelegate` protocol and register the hosting controller as a presentation controller, making it possible to handle the gesture from in an UIKit manner, since SwiftUI doesn't offer us a reliable way to do so.

Screenshots
==========

https://user-images.githubusercontent.com/5920403/169617487-ed581954-c418-4a2e-bf2c-03c704d19bfe.mov

How to Test
==========
1. Make sure the Coupons experimental toggle is active
2. Go to the Coupons section and in the Coupon list, select an editable one
3. Once inside the select Coupon details, click the action menu button and select `Edit Coupon`
4. Make any changes to the coupon and try to do a swipe-down to dismiss in the edit view
5. Verify if the discard warning is displayed
6. Remove all changes done and try the swipe-down again, verify that now the dismiss happens without issues

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
@itsmeichigo, before raising this discussion to more people, I decided to ping you on this draft PR here so you can check out everything I've done so far related to detecting the swipe down gesture as we discussed previously on slack. 

So far, every attempt that tries to display the `AddEditCoupon` Hosting Controller in a modal way fails to detect the swipe down. The dismiss detection only works if the view is fully presented. As you can check in the `attempt 1` implementation, the idea you had on calling the view on top of the Coupon details hosting controller visually works, but so far, it fails to detect the swipe down too, so I'm not sure what I'm missing here 😅 .

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 1]
```diff
@@ -1,9 +1,92 @@
...
+    }
+
+    required dynamic init?(coder aDecoder: NSCoder) {
+        fatalError("init(coder:) has not been implemented")
+    }
+
+    override func viewDidLoad() {
+        super.viewDidLoad()
+
+        handleSwipeBackGesture()
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: We will not need this since the `AddEditCoupon` view is presented modally. We only need to check for the swipe back gesture if it's pushed into a navigation stack (using `navigationController.push()`).

Instead, we should intercept the swipe gesture when the view is presented by setting a delegate to its presentation controller here:

```suggestion
        presentationController?.delegate = self
```

Since you have implemented the conformance to `UIAdaptivePresentationControllerDelegate` below, this should be sufficient for detecting the swipe gesture.

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 2]
```diff
@@ -1,9 +1,92 @@
...
+            })
+            return false
+        }
+        return true
+    }
+
+    override func shouldPopOnSwipeBack() -> Bool {
+        return shouldPopOnBackButton()
+    }
+}
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: This part should be removed since we're not pushing the `AddEditCoupon` view into the navigation stack.

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 3]
```diff
@@ -1,9 +1,92 @@
...
+
+extension AddEditCouponHostingController: UIAdaptivePresentationControllerDelegate {
+    func presentationControllerShouldDismiss(_ presentationController: UIPresentationController) -> Bool {
+        return !viewModel.hasChangesMade
+    }
+
+    func presentationControllerDidAttemptToDismiss(_ presentationController: UIPresentationController) {
+        presentDiscardChangesActionSheet(onDiscard: { [weak self] in
+            self?.discardAndDismiss()
+        })
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: We can simplify this to trigger the alert and discard changes directly here since there's only one type of navigation to support for this view:

```suggestion
        UIAlertController.presentDiscardChangesActionSheet(viewController: self, onDiscard: { [weak self] in
            self?.dismiss(animated: true)
        })
```

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 4]
```diff
@@ -1,9 +1,92 @@
...
+    }
+
+    func discardAndDismiss() {
+        dismiss(animated: true)
+    }
+
+    func discardAndPop() {
+        navigationController?.popViewController(animated: true)
+    }
+}
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: This part can be removed since we've simplified the call to present the discard alert in the above suggestion 😄

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift [hunk 5]
```diff
@@ -202,8 +225,12 @@ struct CouponDetails: View {
...
             }
-            .sheet(isPresented: $viewModel.showingEditCoupon) {
-                AddEditCoupon(addEditCouponViewModel)
+            .sheet(isPresented: $viewModel.showingEditCoupon, onDismiss: {
+                // this is just a test to compare calling the AddEditCoupon view from a callback
+                // and from the UIViewControllerRepresentable bridge implementation below
+                onEditCoupon(addEditCouponViewModel)
+            }) {
+                AddEditCouponHostingControllerBridge(viewModel: addEditCouponViewModel)
             }
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift]: Since we want to present the `AddEditCoupon` view the UIKit way, we should remove this and instead call the `onEditCoupon` closure when we need to show the view. So instead of this:

https://github.com/woocommerce/woocommerce-ios/blob/91acf263d2ffbbc52c7e36abc4c0e307df86b04d/WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift#L83-L88

We should trigger the closure like so:

```Swift
buttons.append(contentsOf: [ 
     .default(Text(Localization.editCoupon), action: { 
         ServiceLocator.analytics.track(.couponDetails, withProperties: ["action": "tapped_edit"]) 
         onEditCoupon(addEditCouponViewModel)
     }) 
 ])
```

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 6]
```diff
@@ -1,9 +1,92 @@
...
+    let viewModel: AddEditCouponViewModel
+
+    func makeUIViewController(context: Context) -> AddEditCouponHostingController {
+        AddEditCouponHostingController(viewModel: viewModel)
+    }
+
+    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
+    }
+}
+
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: This is redundant since we won't need to present the view in the SwiftUI way.

**Review by itsmeichigo — COMMENTED** [review]
Thank you for trying to hack this 🎉 

Looking through the code and the explanations, attempt 3 makes the best sense to me. Since we want to intercept the swipe gesture using `UIAdaptivePresentationControllerDelegate`, we should present the view in the UIKit way by triggering the closure as you did in this attempt.

I left a few comments on the way the AddEditCoupon view is presented and how the swipe gesture is detected. Let me know if you need clarification on any of them 😄

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift (hunk 1 above)
Comment (ThomazFB) [reply WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: I can't believe I forgot to register the delegate 🤦, this was the missing part to make attempt 3 work. Thank you so much for catching this 🙇🙇🙇 It's fixed now!

**Comment by ThomazFB** [comment]
@itsmeichigo thank you so much for your inputs and help, I applied all your suggestions, and now we have a much better strategy for the `UIHostingController` to intercept the swipe down gesture. Can't thank you enough 🙇. 

As we discussed yesterday, there is still some stuff we need to adjust in the `AddEditCoupon` view and ViewModel for the discarding action to work properly. E.g. I've noticed that even dismissing the view confirming the discard, some changes get submitted to the coupon anyway. So I'm still leaving this PR as a draft to address the remaining adjustments.

With that said, do you think that with the solution we have here right now it's safe to move forward with the discard implementation? At least to me, looks like we've done something pretty close to what we have in the `NewOrder` implementation.

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift (hunk 5 above)
Comment (ThomazFB) [reply WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift]: Oh, makes perfect sense! I did that in the first place, but since I was comparing each of the three implementations, I decided to call everything at once so I could compare how each one was behaving! The callback is now linked within the button action! Commit: https://github.com/woocommerce/woocommerce-ios/pull/6889/commits/cc7a93d051768e3431e0810edf95ba1f34c49fc1

**Comment by itsmeichigo** [comment]
Hi @ThomazFB - so sorry I missed the mention above 😅 

> there is still some stuff we need to adjust in the AddEditCoupon view and ViewModel for the discarding action to work properly. E.g. I've noticed that even dismissing the view confirming the discard, some changes get submitted to the coupon anyway.

This was fixed in #6857 - but since I missed the train to 9.2, I merged it to the release branch and we'll have to wait until after this sprint for it to be merged back to trunk. I can also create another PR to merge it to trunk early if you think that's better?

> do you think that with the solution we have here right now it's safe to move forward with the discard implementation?

Yes, I think it looks pretty solid and should be alright to proceed, so please feel free to mark this PR as ready for review. As discussed earlier, I think it's worth it to notice the team as a workaround for SwiftUI. We have a page for the workarounds (P91TBi-7F9-p2), so this should probably be mentioned or linked there. WDYT?

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 7]
```diff
@@ -1,9 +1,55 @@
...
+        rootView.dismissHandler = { [weak self] in
+            guard let self = self else { return }
+            if viewModel.hasChangesMade {
+                UIAlertController.presentDiscardChangesActionSheet(viewController: self) { [weak self] in
+                    self?.dismiss(animated: true)
+                }
+            } else {
+                self.dismiss(animated: true)
+            }
+        }
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: I think we should probably dismiss the view instantly here since we had a discussion about the close button earlier with the Eagle team (p1649409321754619/1649383906.341789-slack-C6H8C3G23), and the discard alert should only be presented on swipe gesture to make sure that the user didn't accidentally close the modal.

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 8]
```diff
@@ -254,7 +300,7 @@ struct AddEditCoupon: View {
             .toolbar {
                 ToolbarItem(placement: .cancellationAction) {
                     Button(Localization.cancelButton, action: {
-                        presentation.wrappedValue.dismiss()
+                        dismissHandler()
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift:304]: Since we no longer dismiss the view with `presentation`, we should probably remove the declaration for this property above?

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift [hunk 9]
```diff
@@ -7,12 +7,21 @@ final class CouponDetailsHostingController: UIHostingController<CouponDetails> {
...
 
         // Set presenting view controller to show the notice presenter here
         rootView.noticePresenter.presentingViewController = self
+
+        // Set manually the edit coupon button click event to present
+        // the AddEditCoupon view on top of the Coupon details
+        rootView.onEditCoupon = { [weak self] addEditCouponViewModel in
+            guard let self = self else { return }
+            let addEditHostingController = AddEditCouponHostingController(viewModel: addEditCouponViewModel)
+            self.navigationController?.present(addEditHostingController, animated: true)
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift]: We don't really need to present the view on top of the navigation controller unless there's a clear reason for that. In this case, I believe we can simply present it from the current controller:
```suggestion
            self.present(addEditHostingController, animated: true)
```

**Review by itsmeichigo — COMMENTED** [review]
Great work @ThomazFB! I tested and the discard alert works as expected! 💯 

I notice in Xcode console that there's some constraint warning about the navigation item. I belive this can be fixed by applying `.navigationViewStyle(.stack)` to the `NavigationView` of `AddEditCoupon`. This is a weird behavior when presenting a navigation view from UIKit.

I also left a few other comments below.

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift (hunk 8 above)
Comment (ThomazFB) [reply WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift:304]: Indeed! Fixed here: https://github.com/woocommerce/woocommerce-ios/pull/6889/commits/8399f66cb79ff9e74e9e2729a150a35ed2027f4b

File: WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift (hunk 9 above)
Comment (ThomazFB) [reply WooCommerce/Classes/ViewRelated/Coupons/CouponDetails/CouponDetails.swift]: Oh, that makes sense! Now it's fixed! https://github.com/woocommerce/woocommerce-ios/pull/6889/commits/610110df70a7cd8dd178d2b8b9fb874b18b20c36

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift (hunk 7 above)
Comment (ThomazFB) [reply WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift]: Thanks for giving me this context! I've fixed it here: https://github.com/woocommerce/woocommerce-ios/pull/6889/commits/a159a30df8fe55f99852337a903bd57d99663ad0

**Comment by ThomazFB** [comment]
Thanks, @itsmeichigo for all your effort reviewing all the changes going on here 🙇 

> This was fixed in https://github.com/woocommerce/woocommerce-ios/pull/6857 - but since I missed the train to 9.2, I merged it to the release branch and we'll have to wait until after this sprint for it to be merged back to trunk. I can also create another PR to merge it to trunk early if you think that's better?

I see! Do you believe there's a conflict risk in these changes you mentioned when they're merged back to trunk by the end of the sprint? If there's not, maybe we could move forward with this PR and merge it, and if there's a conflict, we can jump to solve it before the release. WDYT?

>Yes, I think it looks pretty solid and should be alright to proceed, so please feel free to mark this PR as ready for review. As discussed earlier, I think it's worth it to notice the team as a workaround for SwiftUI. We have a page for the workarounds (P91TBi-7F9-p2), so this should probably be mentioned or linked there. WDYT?

Sounds great! The workaround page is updated now with this PR solution, and I'll raise to the team what we did here by Monday, since right now everyone is out for the weekend.

>I notice in Xcode console that there's some constraint warning about the navigation item. I belive this can be fixed by applying .navigationViewStyle(.stack) to the NavigationView of AddEditCoupon. This is a weird behavior when presenting a navigation view from UIKit.

Thanks for letting me know! I added the navigation view style right here: https://github.com/woocommerce/woocommerce-ios/pull/6889/commits/9015935a08b7c22bd2258c8e9382f9f7b0550794

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift [hunk 10]
```diff
@@ -263,6 +308,10 @@ struct AddEditCoupon: View {
             .navigationBarTitleDisplayMode(.large)
             .wooNavigationBarStyle()
         }
+        .navigationViewStyle(.stack)
+        .onDisappear {
+            onDisappear()
+        }
```
Comment (ThomazFB) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift:316]: @itsmeichigo I noticed after merging this branch with trunk that a `onDisappear` behavior was added to the `AddEditCoupon` creation, since this view ended up getting wrapped by the `UIHostingController`, the only solution I found to keep this behavior was to also connect the event through a closure callback. WDYT?

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCouponViewModel.swift [hunk 11]
```diff
@@ -241,6 +241,7 @@ final class AddEditCouponViewModel: ObservableObject {
             case .success(_):
                 ServiceLocator.analytics.track(.couponUpdateSuccess)
                 self.onCompletion(result)
+                onUpdateFinished()
```
Comment (ThomazFB) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCouponViewModel.swift:244]: I added this closure parameter here to allow us to dismiss the `EditAddCoupon` view after the update ends, since we removed the sheet observing the `showingEditCoupon` property state. WDYT?

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift (hunk 10 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCoupon.swift:316]: This looks good to me 💯

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCouponViewModel.swift (hunk 11 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/AddEditCouponViewModel.swift:244]: This makes sense too! 👍

**Review by itsmeichigo — APPROVED** [review]
The new changes look good and work as expected. Great work @ThomazFB 🎉 🏅 

> Do you believe there's a conflict risk in these changes you mentioned when they're merged back to trunk by the end of the sprint? If there's not, maybe we could move forward with this PR and merge it, and if there's a conflict, we can jump to solve it before the release.

I believe that our release engineer has merged my PR back to trunk in 08f3f29e880c09a9fde7174adba1efd0e5a695b8. You have also fixed the issue with `onDisappear` (which was added in that PR) - so we should be good to go now! :shipit:
