### PR TITLE
[Media Library] Update parameter key for number of items to fetch to be `per_page`

### LINKED ISSUE #14432: Missing images in media library
**Describe the bug**
Some images are not showing up in the media library when the user attempts to update a product image. I have been able to replicate the issue on my site. It seems to be related to the application password login as all images show up when I login using WordPress.com account, however, some images are missing when I login using application passwords. This issue is NOT reproducible in the Android app so there seems to be some inconsistency between the platforms.

**To Reproduce**
1. Login with application password flow
2. Try to upload a new image for one of the products
3. Select WP Media Library
4. Notice some images that are accessible in wpadmin do not appear in the app at all.

**Expected behavior**
All images available in the wp media library should be available in the mobile app.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 17.6.1
- WooCommerce iOS version: 9.4

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #14432

## Description

When logging in with application password, the Media Library only fetches 10 images regardless. From investigating and comparing with Android, the API request in iOS uses `number` parameter.

According to the API doc, `number` parameter does not exist and instead `per_page` is needed: https://developer.wordpress.org/rest-api/reference/media/#arguments

Android also uses `per_page` and thus do not see this issue:

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/cc17141a0e910d5b808ba6bbfb4b7d393d3517a0/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/media/BaseWPV2MediaRestClient.kt#L231

This PR updates the parameter to the correct one.

The above should also apply the same for Jetpack CP site.

For full Jetpack site, the parameter `number` should still be used, and this PR differentiates between the two usage.

Reference:
1. .org API https://developer.wordpress.org/rest-api/reference/media/#arguments
2. .com API https://developer.wordpress.com/docs/api/1.2/get/sites/%24site/media/

## Steps to reproduce

**a. No Jetpack case (Application Password)**
1. Have a .org site with no Jetpack, 
3. Upload more than 25 images in wp-admin Media > Library,
4. In the app, login to site with application password,
5. Go to Products > Add Product > Add Product Image > WordPress Media Library
6. Ensure all the images are loaded, not just 10.

**b. Jetpack CP site case**
1. Have a .org site with no Jetpack but with a plugin with Jetpack CP (I use "Blaze Ads"), 
2. Setup the Jetpack CP plugin and connect it to your WordPress.com account,
3. Upload more than 25 images in wp-admin Media > Library,
4. In the app, login to site with WordPress.com account,
5. Go to Products > Add Product > Add Product Image > WordPress Media Library
7. Ensure all the images are loaded, not just 10.

**c. WordPress.com / full Jetpack site case**
1. Have a .org site with Jetpack plugin, 
2. Setup the Jetpack plugin and connect it to your WordPress.com account,
3. Upload more than 25 images in wp-admin Media > Library,
4. In the app, login to site with WordPress.com account,
5. Go to Products > Add Product > Add Product Image > WordPress Media Library
6. Ensure all the images are loaded, not just 10.

**New: "media_type" fix test**
1. Have a .org site with no Jetpack, 
3. Upload some images and at least one video to media library,
5. In the app, login to site with application password,
6. Go to Products > Add Product > Add Product Image > WordPress Media Library
7. Ensure all the images are loaded, but the video is not shown

## Testing information

I tested this on three type of sites above, on iPhone simulator with iOS 18.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Networking/Networking/Remote/MediaRemote.swift [hunk 1]
```diff
@@ -294,7 +294,7 @@ public extension MediaRemote {
 
     private enum ParameterKey {
         static let pageNumber: String = "page"
-        static let pageSize: String   = "number"
+        static let pageSize: String   = "per_page"
```
Comment (selanthiraiyan) [inline Networking/Networking/Remote/MediaRemote.swift]: Thanks for working on this, @hafizrahman! I will wait for @hichamboushaba to review this.

---

I am jumping in as this parameter key change will affect both `loadMediaLibrary` and `loadMediaLibraryFromWordPressSite` methods in this `MediaRemote` file. 

The `number` parameter key is from the following documentation. https://developer.wordpress.com/docs/api/1.2/get/sites/%24site/media/

Please make sure to test the following login cases and update the PR testing instructions accordingly.

1. Jetpack
2. JCP
3. No Jetpack. (Application password)

I am afraid that one of the above cases could be broken/affected by this change. 

---
Nice to have: It would be nice to add a unit test to ensure that the parameter key is correct.

Comment (hafizrahman) [reply Networking/Networking/Remote/MediaRemote.swift]: Oh good catch, I tested in WordPress.com console and indeed it wants `number`. Let me refactor this.

Comment (hafizrahman) [reply Networking/Networking/Remote/MediaRemote.swift]: Updated in https://github.com/woocommerce/woocommerce-ios/pull/14444/commits/7215568fbe05f767eebc8710a371eceb86007256

Good for another review.

**Comment by hichamboushaba** [comment]
@hafizrahman just sharing this [bug](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3109#discussion_r1844958555) that I identified in Android last week, it's similar to this one, we use the `mime_type` parameter for all implementations, while it should be `media_type` for `loadMediaLibraryFromWordPressSite`, do you think it makes sense to fix it on the same PR?

**Comment by hafizrahman** [comment]
@hichamboushaba thanks for the ping! I'll have it added here.

**Comment by hafizrahman** [comment]
Added `media_type` fix on https://github.com/woocommerce/woocommerce-ios/pull/14444/commits/02bd74d9967b94e677b427694b36851bb6f8011a and updated test instruction at the top with this scenario.

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for the updates, Hafiz!

> b. Jetpack CP site case

Unfortunately, the above case doesn't work. I used Blaze Ads plugin to connect my WPCOM account with the JN site. 

While trying to load images from the media library, I end up seeing the following error alert. 



To debug this,

I looked into proxyman, and I see that I do receive a success response from the store for the following request. 

`https://public-api.wordpress.com/wp/v2/sites/1234/media?_fields=id%2Cdate_gmt%2Cslug%2Cmime_type%2Csource_url%2Calt_text%2Cmedia_details%2Ctitle&media_type=image&page=1&per_page=25`

I looked into Xcode logs, and I see the following decoding error.

```
<> Mapping Error: typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [_CodingKey(stringValue: "Index 6", intValue: 6), CodingKeys(stringValue: "media_details", intValue: nil), CodingKeys(stringValue: "sizes", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Any> but found an array instead.", underlyingError: nil))
```

**Comment by hichamboushaba** [comment]
> I looked into Xcode logs, and I see the following decoding error.
>
> ```
> <> Mapping Error: typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [_CodingKey(stringValue: "Index 6", intValue: 6), CodingKeys(stringValue: "media_details", intValue: nil), CodingKeys(stringValue: "sizes", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Any> but found an array instead.", underlyingError: nil))
> ```

This looks like the `media_details.sizes` property is returning a dictionary instead of the expected object, I had this happen in my tests when I worked on this in Android, but it was only for non-image types, which was happening because we weren't passing the correct argument `media_type` and we were using the `mime_type` one.
(This issue shouldn't be because of the PR's changes, and should happen also on trunk I think)

I tried to replicate this, but I couldn't on a test site that I have right now. It's the EOD for me, but I'll try to take a look at this if needed tomorrow, if it's an issue then it would impact Android as well.

**Comment by selanthiraiyan** [comment]
Thanks for taking a look, @hichamboushaba! 

> I tried to replicate this, but I couldn't on a test site that I have right now.

I have sent invites to my JN store to both you and @hafizrahman. (To your A8C emails)

**Comment by hichamboushaba** [comment]
Using your site @selanthiraiyan, I can see that an image item has the sizes property empty, and when using the WPCom endpoint, this item is returned as an array instead of an empty object (I think this is something that happens a lot with WordPress, in FluxC we have an old [class](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/JsonObjectOrEmptyArrayDeserializer.java) just to handle similar cases).

So, my assumption that `sizes` won't be empty for images is wrong, we need to fix this in both platforms then, we should:
1. Either gracefully handle the switch to empty array (this is what I'll do in Android).
2. Remove the property from the Networking model, this is an easier solution if we don't use the `sizes` property in the app.

**Comment by hichamboushaba** [comment]
An update on why this is happening on your site @selanthiraiyan, one of the images in your site is pretty small (4x2 pixels...), when an image is small, WordPress [skips](https://github.com/WordPress/WordPress/blob/261373653c190d4c77a677f9df75f40a89c4648e/wp-admin/includes/image.php#L79C4-L79C68) generating any other alternative sizes (as they are generally smaller than the original one), so this leads to the empty object.

**Review by selanthiraiyan — APPROVED** [review]
👋  @hafizrahman I am approving this PR as Hicham's explanation makes sense to me. 

Could you please clone this https://github.com/woocommerce/woocommerce-android/issues/12989 for iOS and merge this PR? Thanks!

**Comment by hafizrahman** [comment]
> Could you please clone this https://github.com/woocommerce/woocommerce-android/issues/12989 for iOS and merge this PR? Thanks!

Sure: #14516

**Comment by selanthiraiyan** [comment]
@hafizrahman The release note for this PR is mentioned under version `21.2`. The PR is targeting `21.3`, though.

**Comment by hafizrahman** [comment]
@selanthiraiyan good catch, thanks, fixing in https://github.com/woocommerce/woocommerce-ios/pull/14521/
