### PR TITLE
Auth Role Checks: Part 4 - Implement user-facing flow changes

### LINKED ISSUE #3963: Error synchronizing: "Unable to load content" and "Unable to refresh list" when logged in to a Jetpack site as a user with the Editor role
To prepare:

<sup>TL;DR have a Jetpack site with one Administrator Jetpack-connected account and one Editor Jetpack-connected account.</sup>

* Set up a WooCommerce store hosted somewhere other than WordPress.com.
* Install, activate, and connect Jetpack using a WordPress.com account.
* Go to WP Admin > Users and create an Editor account using a different WordPress.com account email.
* Log out of both WordPress.com and WP Admin.
* Log back in to WP Admin as the user you just created.
* Go to WP Admin > Jetpack Dashboard > Account connection and click the "Link to WordPress.com" link.
* Connect to the WordPress.com with the email address of the Editor account in WP Admin.
* You should end up with something that looks similar to [this screenshot](https://user-images.githubusercontent.com/1119271/114798908-b6d21600-9d53-11eb-936b-3604021753f3.png).

To test: 

1. Log in to the WooCommerce app as a Jetpack-connected user with an Editor role.
1. Browse around in the app.

**Result:** if I log in to the WooCommerce app with a user that is Jetpack-connected but has an Editor role, the app will show "Unable to load content" and "Unable to refresh list" and the app log says "Error synchronizing" multiple times.  ([1m33s](https://cloudup.com/c0NWSqCI4Xw))

```
2021/04/14 19:58:42:104  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:104  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
```

<details>
<summary>Full app logs for the timestamp matching the video</summary>

```
2021/04/14 19:58:01:812  ðŸ”µ Tracked unified_login_interaction, properties: [AnyHashable("click"): "submit", AnyHashable("source"): "default", AnyHashable("flow"): "wordpress_com", AnyHashable("step"): "start"]
2021/04/14 19:58:02:630  ðŸ”µ Tracked unified_login_step, properties: [AnyHashable("source"): "default", AnyHashable("step"): "start", AnyHashable("flow"): "login_password"]
2021/04/14 19:58:10:565  Received OAuth2 response: {
    "access_token" = "*** REDACTED ***";
    "blog_id" = 0;
    "blog_url" = "<null>";
    scope = global;
    "token_type" = bearer;
}
2021/04/14 19:58:10:609  ðŸ”µ Tracked unified_login_step, properties: [AnyHashable("flow"): "login_password", AnyHashable("step"): "success", AnyHashable("source"): "default"]
2021/04/14 19:58:10:795  ðŸ“± Unregistering For Remote Notifications...
2021/04/14 19:58:10:795  â˜Žï¸ [Zendesk] Unregistering for Notifications...
2021/04/14 19:58:10:963  ðŸ”µ Tracked unified_login_step, properties: [AnyHashable("flow"): "login_password", AnyHashable("step"): "success", AnyHashable("source"): "default"]
2021/04/14 19:58:12:291  TracksService sendQueuedEvents completed. Sent 4 events.
2021/04/14 19:58:23:415  âš ï¸ Cannot check WC version on default store â€” default siteID is nil or 0.
2021/04/14 19:58:23:416  checkAppleIDCredentialState: No Apple ID found.
2021/04/14 19:58:39:419  ðŸ“± Registering for Remote Notifications...
2021/04/14 19:58:39:460  â™»ï¸ Requesting dashboard data be reloaded...
2021/04/14 19:58:39:501  ðŸ“± Device Token Received: [*** REDACTED ***]
2021/04/14 19:58:39:597  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:597  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:629  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:629  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:878  ðŸ“± Successfully registered Device ID 41285461 for Push Notifications
2021/04/14 19:58:42:104  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:104  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:162  â›”ï¸ Site settings sync had 2 error(s) for siteID 191940058: [Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources., Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.]
2021/04/14 19:58:42:238  â›”ï¸ Could not successfully fetch order statuses for siteID 191940058: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:369  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:370  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:377  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:377  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:388  â›”ï¸ Failed to sync payment gateways for siteID: 191940058. Error: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:406  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:406  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:412  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:413  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:432  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:432  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:584  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:584  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:667  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:667  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:674  â›”ï¸ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:49:846  checkAppleIDCredentialState: No Apple ID found.
2021/04/14 19:58:51:886  â›”ï¸ Order List â€” Error synchronizing order statuses: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:52:090  â›”ï¸ Error synchronizing orders: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:57:259  â›”ï¸ Error synchronizing products: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:09:934  â™»ï¸ Requesting dashboard data be reloaded...
2021/04/14 19:59:10:060  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:060  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:061  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:061  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:062  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:063  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:063  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:063  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:11:293  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:294  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:294  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:294  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:310  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:310  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:351  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:351  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:357  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:357  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:377  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:377  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:379  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:379  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:468  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:468  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:472  â›”ï¸ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:48:602  â™»ï¸ Requesting dashboard data be reloaded...
2021/04/14 19:59:48:730  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:731  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:731  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:731  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:735  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:735  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:768  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:768  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:50:509  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:510  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:534  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:534  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:820  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:820  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:876  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:877  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:901  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:902  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:921  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:922  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:952  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:952  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:995  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:995  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:51:002  â›”ï¸ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 20:00:00:080  checkAppleIDCredentialState: No Apple ID found.
2021/04/14 20:03:31:860  checkAppleIDCredentialState: No Apple ID found.
```
</details>

Unable to load content Unable to refresh list No products yet
<sup>Tested with WCAndroid 6.4.0.0 (TestFlight beta) on iPhone 11 iOS 14.4.2 on favourite-saki.jurassic.ninja (WP 5.7.1-RC1 JP 9.6.1 WC 5.2.1) logged in as testuser031821 (which is a WordPress.com account username used to connect to the account with the same name on the Jetpack site and that has an Editor role there).</sup>

**Potential solutions:** 

1. Update the minimum requirements for the app to mention the account in WP Admin must be connected to Jetpack and must either be an Administrator or Shop Manager role. 
1. Add error handling for `Sorry, you cannot list resources` to let the user know the role requirements and how to update that in WP Admin (make sure to note that an Administrator must make the change).

### PR DESCRIPTION
**Pull request by dvdchr**
Resolves #3963 
Depends on #4492 and #4665

## Summary

This is the **final** part out of 4 parts that make up the changes related to role authentication (for more details, refer to #3963). This PR introduces **user-facing changes** as it modifies the application flow. Here's a summary of this change: 

### 1. Check role eligibility after selecting a store

With this change, a blocking role eligibility check is performed after user taps "Continue" in Store Picker. If the role eligibility check fails, the user will be presented with a role error page. To see how the error page looks, refer to #4478.

At this moment, there are 3 ways to present a Store Picker: from the Authentication flow, from app launch, or from the Settings page. Here's how the role error page behaves on each of the behaviors:
- **From the authentication flow** 🔒 : The role error page will be directly pushed onto the navigation stack. This is possible because the authentication flow directly pushes Store Picker onto the navigation controller.
- **From app launch** 🚀 : The role error page will be directly pushed onto the _top-most_ navigation controller. In this flow, the Store Picker is wrapped in a navigation controller and then modally presented from a navigation controller. This is why we need to find the top-most navigation controller, and present it from there.
- **From the Settings page** ⚙️ : Same as previous, the role error page will be directly pushed onto the top-most navigation controller. The Store Picker is also presented modally, but the difference is that the Settings page presents it using default presentation style (i.e. it can be dismissed).

In all of the cases, the role eligibility check is performed _before_ the selected `storeID` is updated, therefore user can freely go back from the error page to the Store Picker page to (for example) try accessing a different store. 

Additionally, in the case where the user selected a store and were presented with the role error page, if they restart the app, they would enter the Store Picker again (through the app launch 🚀  flow) – giving them a chance to select a different store.

### 2. Check role eligibility on every app launch

This change also introduces a non-blocking role eligibility check during app launch. The result of the check is stored in `GeneralAppSettings`, and will be consumed by `AppCoordinator` on the next launch, should the result differ from the current state.

The role check is only performed for users that have **authenticated AND selected a store**. The purpose of doing this on every app launch is to detect when the user's roles are updated _after_ they gained access to the store (in the WooCommerce app).

Different from the Store Picker behavior, the error page presented from the app launch flow ⚠️ **may block the user** ⚠️. This can only happen under these conditions:
- User is authenticated,
- Has selected a store,
- User was previously eligible, but the latest role eligibility check failed.

In cases where the API request fails (i.e. we don't know if user is eligible or not), the implementation similarly follows the [implementation on Android](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2002#issuecomment-843736770):

- **If user is previously NOT eligible** and the API call fails, the app will assume that the user is still not eligible. User can retry the eligibility check from the error screen, and if it succeeded, they will be directed to the store.
- **If the user is previously eligible** and the API call fails, the app will assume that the user is still eligible. Although it's not ideal, we don't know if the user is eligible or not because the API call failed. If they turned out to be NOT eligible, they'll get failing API requests on the store due to insufficient permissions.

## Related PRs
- #4473 
- #4478 
- #4619
- #4620 (integration branch)
- #4492
- #4665 

## To Test

Since this involves role modifications, my recommendation is to add a user that you can easily modify in your store. Having a WP-Admin dashboard opened and ready is also handy to quickly apply role changes.

### Store Picker: Authentication Flow 🔒 
Make sure the app is in logged out state.

- Login, and enter the Store Picker.
- Select the store where your role is ineligible, and tap "Continue". 
- Verify that the role error page is shown.
- Tap on the "Retry" button. Verify that a notice is shown.
- Tap back. Verify that you are now back at the Store Picker page.
- Enter the Role error page again, and tap Help. Verify that the help form is shown.
- Tap Login with Another Account. Verify that the authentication flow is restarted.
- Go through the authentication process again until you've entered the role error page.
- From the WP Admin, update your role to be eligible.
- Tapping Retry should bring you into the store.

### Store Picker: App Launch Flow 🚀 
Make sure the app is in authenticated state, but has no default store yet.
- Select the store where your role is ineligible, and tap "Continue". 
- Verify that the role error page is shown.
- Tap on the "Retry" button. Verify that a notice is shown.
- Tap back. Verify that you are now back at the Store Picker page.
- Enter the Role error page again, and tap Help. Verify that the help form is shown.
- From the WP Admin, update your role to be eligible.
- Tapping Retry should bring you into the store.

### Store Picker: Settings Flow ⚙️ 
Make sure the app is in authenticated state, and has a default store selected. Also make sure that the user has access to >1 stores.
- Go to Settings and select Switch Store.
- Select the store where the user has ineligible roles, and verify that the role error page is shown.
- Tap on Login With Another Account, verify that the authentication flow is restarted.
- Go to the Store Picker again from Settings, and enter the role error page.
- From the WP Admin, update your role to be eligible.
- Tapping Retry should bring you into the store.

#### Scenario 1: Not Eligible -> Eligible state
Make sure the app is in authenticated state, has a default store selected, and the user is NOT eligible to access.

- Close the app.
- Update the user role to be eligible.
- Open the app.
- Verify that the error page is shown.
- Tap on the Retry button.
- Verify that the main UI is shown.

#### Scenario 2: Eligible -> Not Eligible state
Make sure the app is in authenticated state, has a default store selected, and the user is eligible to access.

- Close the app.
- Update the user role to be NOT eligible.
- Open the app.
- Verify that the error page is shown, not long after the main UI is shown.

#### Scenario 3: Eligible -> Eligible state
Make sure the app is in authenticated state, has a default store selected, and the user is eligible to access.

- Close the app.
- Update the user role to something else, but still an eligible role.
- Open the app.
- Verify that the main UI is shown, and there are no disruptions in the user flow.

#### Scenario 4: NOT Eligible -> NOT Eligible state
Make sure the app is in authenticated state, has a default store selected, and the user is NOT eligible to access.

- Close the app.
- Update the user role to something else, but still an ineligible role.
- Open the app.
- Verify that the role error page is shown.

### Unit tests

- Make sure all the tests are 🟢 .

## Author Checklist

- [x] I have added unit tests where necessary.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift [hunk 1]
```diff
@@ -45,17 +49,19 @@ final class StorePickerCoordinator: Coordinator {
...
-            if self?.selectedConfiguration == .login {
-                MainTabBarController.switchToMyStoreTab(animated: true)
+        roleEligibilityUseCase.checkEligibility(for: storeID) { [weak self] error in
+            guard let self = self else { return }
+
+            guard let error = error else {
+                // if user is eligible, then switch to the desired store.
+                self.roleEligibilityUseCase.reset()
+                self.switchStore(with: storeID, onCompletion: onCompletion)
+                return
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: ⚠️  I think it looks a bit strange to handle the `success` case in a `guard let`.
What do you think about returning a `Result` from `roleEligibilityUseCase.checkEligibility` and handle these paths in a switch?

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift [hunk 2]
```diff
@@ -85,4 +91,43 @@ private extension StorePickerCoordinator {
         }
     }
 
+    func switchStore(with storeID: Int64, onCompletion: @escaping SelectStoreClosure) {
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift:97]: nit: Some documentation here will also be nice!

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift [hunk 3]
```diff
@@ -85,4 +91,43 @@ private extension StorePickerCoordinator {
...
+            self.restartAuthentication()
+        }
+
+        // find the top-most navigation controller by checking if there's a navigationController being presented.
+        // this takes care of the different variation of presentation, based on configurations.
+        var topNavigationController = navigationController
+        while let presented = topNavigationController.presentedViewController as? UINavigationController {
+            topNavigationController = presented
+        }
+        topNavigationController.pushViewController(errorViewController, animated: true)
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: nit: 
```suggestion
        topNavigationController.show(errorViewController, sender: self)
```

File: WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift [hunk 4]
```diff
@@ -14,6 +17,10 @@ final class RoleErrorViewModel {
         .incorrectRoleError
     }
 
+    var onSuccess: (() -> Void)?
+
+    var onDeauthenticationRequest: (() -> Void)?
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift]: Since this is an API meant to be consumed It would be good to add some docs too!

File: WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift [hunk 5]
```diff
@@ -38,17 +45,37 @@ final class RoleErrorViewModel {
...
+
+            if case let RoleEligibilityError.insufficientRole(errorInfo) = error {
+                self.titleText = errorInfo.name
+                self.subtitleText = errorInfo.humanizedRoles
+                self.output?.refreshTitleLabels()
+                self.output?.displayNotice(message: .insufficientRolesErrorMessage)
+                return
+            }
+
+            self.output?.displayNotice(message: .retrieveErrorMessage)
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift]: Same comment as above!

File: WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift [hunk 6]
```diff
@@ -35,8 +35,11 @@ final class RoleEligibilityUseCase {
 
     /// The last eligibility error info encountered by the user.
     private var lastErrorInfo: EligibilityErrorInfo? {
-        didSet {
-            defaults.setValue(lastErrorInfo?.toDictionary(), forKey: Constants.eligibilityErrorInfoKey)
+        get {
+            loadLastErrorInfo()
+        }
+        set {
+            defaults.setValue(newValue?.toDictionary(), forKey: Constants.eligibilityErrorInfoKey)
```
Comment (Ecarrion) [inline WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift]: ⚠️  We try to not save more things to user defaults. For settings like these, we have `GeneralAppSettings` which is accessible through a `Yosemite` store.

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift [hunk 7]
```diff
@@ -66,6 +69,14 @@ private extension AppCoordinator {
     /// Displays logged in tab bar UI.
     ///
     func displayLoggedInUI() {
+        // if the previous role check indicates that the user is ineligible, then we want to show the error message.
+        // Eligibility status is stored locally in user defaults, and updated asynchronously upon app launch.
+        if let errorInfo = roleEligibilityUseCase.lastEligibilityErrorInfo(),
```
Comment (Ecarrion) [inline WooCommerce/Classes/ViewRelated/AppCoordinator.swift]: ⚠️  I think this is a bit missleading. A use case is supposed to serve a single purpose, but this use-case already has two. `checkEligibility` and `lastEligibilityErrorInfo`. What do you think about moving `lastEligibilityErrorInfo()` to `AppSettingsStore`?

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift [hunk 8]
```diff
@@ -90,6 +101,25 @@ private extension AppCoordinator {
...
+        errorViewModel.onSuccess = {
+            self.displayLoggedInUI()
+        }
+
+        errorViewModel.onDeauthenticationRequest = {
+            self.stores.deauthenticate()
+        }
+
+        // this needs to be wrapped within a navigation controller to properly show the right bar button for Help.
+        setWindowRootViewControllerAndAnimateIfNeeded(UINavigationController(rootViewController: errorViewController))
```
Comment (Ecarrion) [inline WooCommerce/Classes/ViewRelated/AppCoordinator.swift]: ⚠️  I think we should use `WooNavigationController` to be safe with any future global customization.

**Review by Ecarrion — CHANGES_REQUESTED** [review]
Hi @dvdchr! Thanks for tackling this. I left some concerns marked with ⚠️ 

----

I'm not sure if this is already on your radar but we are missing some accessibility support. See how the feature looks when using big fonts:

Portrait | Landscape
---- | ----
problem-big-fonts | problem-big-fonts-2

----

Also I think it would be a great improvement to always do the async check when the app launches and act immediately, not wait until the next app launch or until the user taps retry. 


https://user-images.githubusercontent.com/562080/124191734-d8f14f80-da89-11eb-8bdb-377b9ad7e9fc.mov

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift (hunk 1 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: Thanks for the suggestion! I've received [similar review in Part 3](https://github.com/woocommerce/woocommerce-ios/pull/4492#discussion_r662318120), and I'll be changing this to a `Result<Void, Error>` soon! 🙂

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift (hunk 2 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift:97]: Will do! 👍

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift (hunk 3 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: Good catch! Will adjust this soon.

File: WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift (hunk 4 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/Navigation Exceptions/RoleErrorViewModel.swift]: Noted, will add some docs soon! 👍

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift (hunk 7 above)
Comment (dvdchr) [reply WooCommerce/Classes/ViewRelated/AppCoordinator.swift]: > A use case is supposed to serve a single purpose,

Ah, I didn't know that we are supposed to have only one public method per use case. I thought it's more of being responsible for a single context or object, but still allowing more than one method. I'll try to separate the responsibility to another object, then 👍 

> moving lastEligibilityErrorInfo() to AppSettingsStore?

Good idea! Will do this soon. 👍

File: WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift (hunk 6 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift]: Noted. Will look into this and move the implementation to `GeneralAppSettings` instead. 👍

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift (hunk 8 above)
Comment (dvdchr) [reply WooCommerce/Classes/ViewRelated/AppCoordinator.swift]: Ah, right! About this, I tried using `WooNavigationController` but it was [overriding the status bar style](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/System/WooNavigationController.swift#L25-L30) to `.lightContent` regardless of the current color scheme. 

I'll follow your suggestion on using `WooNavigationController` for now, and will probably raise this as a separate issue later. Thanks! 👍

**Comment by dvdchr** [comment]
> we are missing some accessibility support

Thanks for noticing this. I missed testing large font sizes. Since UI is addressed in Part 2, I'll address this in a different PR!

> it would be a great improvement to always do the async check when the app launches and act immediately

I see, thanks for the suggestion 👍 . Previously, the consideration for delaying the error page to next launch was to not disrupt the user abruptly – but if their roles are ineligible, the app would not be working correctly for them and it would confuse them anyways. To make this work, I'll probably hook into the `AppCoordinator` and use `CombineLatest3` to listen to eligibility state. When the state changes, it can be immediately acted upon.

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift (hunk 7 above)
Comment (dvdchr) [reply WooCommerce/Classes/ViewRelated/AppCoordinator.swift:74]: Update: comment addressed in #4492, particularly in [this commit](https://github.com/woocommerce/woocommerce-ios/pull/4492/commits/f2e1cccf92c216a97dcf4ab30806c9024fd2330e)! 🙂

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift (hunk 1 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: Update: comment addressed in #4492, particularly in [this commit](https://github.com/woocommerce/woocommerce-ios/pull/4492/commits/f2e1cccf92c216a97dcf4ab30806c9024fd2330e)! 🙂

**Comment by dvdchr** [comment]
> we are missing some accessibility support. 

This will be resolved in #4619!

**Comment by shiki** [comment]
Hi, @dvdchr and @Ecarrion! Would you mind marking the conversations that have been resolved as "Resolved"? Just so we have some idea on what else is pending and how we can help each other get this PR merged. 🙂 

Is this ready for another round of review? 🙂

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift (hunk 7 above)
Comment (dvdchr) [reply WooCommerce/Classes/ViewRelated/AppCoordinator.swift]: This is addressed in #4665!

File: WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift (hunk 6 above)
Comment (dvdchr) [reply WooCommerce/Classes/Authentication/RoleEligibilityUseCase.swift]: Addressed in #4665 !

**Comment by dvdchr** [comment]
Hey there @shiki! Thanks for checking in. 🙂 

> Is this ready for another round of review? 

While this PR is still dependent on pending PRs, it is now at a working state. Here's an update based on the latest major review comments from @Ecarrion :

- Missing some accessibility support: addressed in #4619 ✅ 
- Always do the async check when the app launches and act immediately: addressed in https://github.com/woocommerce/woocommerce-ios/pull/4493/commits/9b0cae812786f56d5e16659f794ab261c339ba88 ✅ 
- Move `EligibilityErrorInfo` model to `Storage`, and expose it through `AppSettingsStore`: addressed in #4665 (⏳ pending review)
- All the other minor review comments are addressed here (marked as resolved). ✅ 

---
Here's a chronological list on which PR should be reviewed first:

- #4620. This is an integration branch, so it is safe to merge to `develop`.
- #4665. Since this targets [Part 3](https://github.com/woocommerce/woocommerce-ios/pull/4492), this should be reviewed first.
- #4492 
- And finally this PR!

**Review by Ecarrion — APPROVED** [review]
Thanks for the changes @dvdchr!
Code and tests look good to me! 👏
