### PR TITLE
Site picker fix for inadvertent logout

### LINKED ISSUE #693: Killing the app when fully logged in causes a forced log out
**Describe the bug**
After fully logging in, killing the app and relaunching it causes the user to see the login screen. This probably related to the featured introduced in PR #685. (Sorry I didn't catch this sooner @ctarda!)

**To Reproduce**
0. Delete the existing app from your sim or device
1. Pull from develop and reinstall the app
2. Log in all the way (to Dashboard or choose any tab)
3. Kill the app
4. Relaunch the app

**Screenshots**
N/A

**Expected behavior**
If a user is fully logged in and kills the app, their session should be restored upon relaunching the app. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: 12.x
- WooCommerce iOS version: 3.5

**WordPress Environment**
N/A

### PR DESCRIPTION
**Pull request by bummytime**
This is a quick fix for the inadvertent logout issue we were seeing in #693. 

The problem here was that `StorePickerViewController.applicationTerminating()` was firing even after the user moved past the auth/picking-a-store flow because `StorePickerViewController` was not fully dealloc'ed yet and the `applicationTerminating` [handler was executing](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift#L186-L197) thus logging out the user. This issue only occurs while the StorePicker VC is in memory. 

To fix it I added a call to`removeObserver(self)` in `StorePickerViewController.viewDidDisappear()` insteading of waiting until it's normally called in `deinit()`

Fixes #693 

Ref: #466 and #505 

## Testing

For these scenarios, make sure you begin logged out of the app.

### Scenario 1 — User is deauth'ed if a store isn't selected on store picker screen
1. Log into the app
2. On the store picker screen, kill the app
3. Restart the app 
- [x] Verify the user is at the top of the login flow (aka not authenticated)

### Scenario 2 — User is **NOT** deauth'ed post store picker screen
1. Log into the app
2. On the store picker screen, select a store and tap "Continue"
3. Restart the app
- [x] Verify the dashboard appears and the user is still logged in

@mindgraffiti Could you take a 👀 at this for me?

----
Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift [hunk 1]
```diff
@@ -116,6 +116,14 @@ class StorePickerViewController: UIViewController {
         super.viewWillDisappear(animated)
         onDismiss?()
     }
+
+    override func viewDidDisappear(_ animated: Bool) {
+        super.viewDidDisappear(animated)
+
+        // This should be called here to address this issue:
+        // https://github.com/woocommerce/woocommerce-ios/issues/693
+        stopListeningToNotifications()
```
Comment (mindgraffiti) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift]: If this is here, should the `deinit` method be deleted? 

I can't remember if it's remove observer called twice or add observer called twice that can cause crashes.

Comment (bummytime) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift]: Yeah, this for me — I'll remove it.

**Comment by bummytime** [comment]
Thank you for the review @mindgraffiti !
