### PR TITLE
Issue: Keep the minus sign when deleting negative numbers on the product inventory quantity

### LINKED ISSUE #3710: Cannot Delete “-0” Product Inventory Value
## Describe the Bug

When deleting a negative inventory value like “-10”, the deletion stops at “-0” and I cannot delete the whole value anymore. I have to tap near the negative sign itself to remove it to set it back to zero.

Negative inventory values can happen if products are back-ordered. This behavior makes it a bit cumbersome to update the inventory levels.

## To Reproduce

Please see this video:

https://user-images.githubusercontent.com/198826/108557970-88394100-72b6-11eb-8860-8d3053b345ef.mp4

## Expected Behavior

I would expect that when deleting from the rightmost part of the “-0” text, the “0” would disappear. Pressing delete again would remove “-”. 

## Mobile Environment

- Device: iPhone 11 Simulator
- iOS version: 14.4
- WooCommerce iOS version: c0ea580

### PR DESCRIPTION
**Pull request by toupper**
Closes: #3710 

### Description
With this Pull Request, we fix the issue specified [here](https://github.com/woocommerce/woocommerce-ios/issues/3710), where the user couldn't delete a "-0" quantity reached after deleting a negative quantity (e.g -12) in the Product Inventory Detail Screen (Negative inventory values can happen if products are back-ordered). Because of this behavior, the user had to tap right between "-" and "0" to be able to delete the minus sign if the user wanted to add a positive quantity, which is suboptimal:

https://user-images.githubusercontent.com/198826/108557970-88394100-72b6-11eb-8860-8d3053b345ef.mp4

### Fix
With the fix introduced by this Pull Request, the user can further delete the last number of a negative quantity (e.g "1" of "-1"), thus reaching a point where only "-" appears in the text field. At this point, the user can further delete the "-" if they want to add a positive value or start typing if they want a negative value with the already present "-" sign.

https://user-images.githubusercontent.com/1864060/159524072-73f13911-c38f-4e8d-898e-26d30b028479.mov

### Code Changes
- Return "-" in `IntegerInputFormatter` `format` function when the input is "-" so it can be further edited.
- Update the unit tests matching this logic.
- Update the test functions naming to match the latest convention.

#### Negative Quantity on a Product Inventory
- Set a negative quantity for a product inventory in your testing site wp-admin
- Open the app. Go to products and select the product with that negative quantity. Open the products detail screen and go to inventory.
- Tap on the right side of the negative quantity and start deleting by pressing the delete button.

##### Test Cases

- Before when reaching only the "-", the value was converted automatically to "-0" and it couldn't be deleted. Now you can delete forward until "-", and start typing again.
- If you only the "-" character and delete it, the text field automatically shows the default value ("0").
- If you only the "-" character and press the navigation bar "Done" button, the value is converted to the default value ("0") and so is shown on the product detail page.
---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### Notes
For the stock quantity we use a `numberPad` that only allows input from 0 to 9 (not negative values). This goes counter to the wp-admin logic, where we could add negative values. We might want to fix this so we can also enter negative values on the iOS app.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift [hunk 1]
```diff
@@ -7,69 +7,69 @@ final class IntegerInputFormatterTests: XCTestCase {
 
     // MARK: test cases for `isValid(input:)`
 
-    func testEmptyInputIsValid() {
+    func test_isValid_with_empty_input_then_returns_true() {
```
Comment (pmusolino) [inline WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]: Thanks for updating the methods name using the new format! 

nit: I just say to not explicit the return type `then_returns_true`. It's not useful to know the return type. Some example below

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift [hunk 2]
```diff
@@ -7,69 +7,69 @@ final class IntegerInputFormatterTests: XCTestCase {
...
         let input = ""
         XCTAssertTrue(formatter.isValid(input: input))
     }
 
-    func testAlphanumericInputIsNotValid() {
+    func test_isValid_with_alphanumeric_input_then_returns_false() {
```
Comment (pmusolino) [inline WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]: nit: `test_alphanumeric_input_is_not_valid` is more understandable to me.

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift [hunk 3]
```diff
@@ -7,69 +7,69 @@ final class IntegerInputFormatterTests: XCTestCase {
...
         let input = "06two"
         XCTAssertFalse(formatter.isValid(input: input))
     }
 
-    func testDecimalInputIsNotValid() {
+    func test_isValid_with_decimal_input_then_returns_false() {
```
Comment (pmusolino) [inline WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]:
```suggestion
    func test_decimal_input_is_not_valid() {
```

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift [hunk 4]
```diff
@@ -7,69 +7,69 @@ final class IntegerInputFormatterTests: XCTestCase {
...
         let input = "9990.52"
         XCTAssertFalse(formatter.isValid(input: input))
     }
 
-    func testTrailingPointInputIsValid() {
+    func test_isValid_with_trailing_point_input_then_returns_false() {
```
Comment (pmusolino) [inline WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]: and so on...

**Review by pmusolino — APPROVED** [review]
Thanks for fixing it César, and congrats for opening your first PR as a member of the team 🥳 

Looks good to me, just some nits on the test methods name.

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift (hunk 1 above)
Comment (toupper) [reply WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]: Indeed, refactored in https://github.com/woocommerce/woocommerce-ios/pull/6480/commits/cae78448b59a54bf647ffabe060be3b15eefa86f

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift (hunk 2 above)
Comment (toupper) [reply WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]: yep, see https://github.com/woocommerce/woocommerce-ios/pull/6480/commits/cae78448b59a54bf647ffabe060be3b15eefa86f

File: WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift (hunk 4 above)
Comment (toupper) [reply WooCommerce/WooCommerceTests/Tools/IntegerInputFormatterTests.swift]: As for the rest, fixed in Indeed, refactored in https://github.com/woocommerce/woocommerce-ios/pull/6480/commits/cae78448b59a54bf647ffabe060be3b15eefa86f :)

**Comment by shiki** [comment]
@toupper Thank you very much for fixing this! I've been annoyed at this for a long time. 🤣 Negative values are common if the site supports backorders. And my test site usually has negative values.

**Comment by toupper** [comment]
@shiki You're welcome! 
Unfortunately, the [UIKeyboardTypeNumberPad](https://developer.apple.com/documentation/uikit/uikeyboardtype/uikeyboardtypenumberpad?language=objc) does not allow minus sign, so we can only enter a negative value on the iOS app if there were before already a negative value for that product inventory (probably set in the wp-admin). If we had a positive value we cannot set a negative one, which is weird.
We could add a +/- button as explained [here](https://stackoverflow.com/questions/27272121/is-there-a-uitextfield-keyboard-type-that-like-a-number-pad-but-allows-negative) so we fix this inconsistency.

**Comment by shiki** [comment]
We could build our own keyboard. 🤣 Maybe a HACK Week project! ¯\\\_(ツ)\_/¯

But this is good enough for me. I don't see a need to add negative values, only to delete them.
