### PR TITLE
[REST API] Alamofire network retry and adapt network requests

### LINKED ISSUE #8482: [REST API] Introduce retrier and adaptor for `AlamofireNetwork`
In order to generate application password when a REST API request fails due to authentication error, we should use `Alamofire` framework's `SessionManager` properties `retrier` and `adapter` for authentication and retrying requests.

1. Existing WPCOM Jetpack tunnel requests should be authenticated using token. 
   1. There will be no retry step for Jetpack requests.
1. WPOrg REST API requests should be authenticated using application password. 
   1. If there is an authentication failure, we should generate application password and retry the REST API request.

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #8482

## Description
As part of the REST API project we need the capability to retry a request in case of authentication failure. 

The flow for a REST API request is described below,
1. Send a request
2. If an error occurs due to authentication failure for a REST request. 
3. Regenerate a new application password.
4. Retry the REST API request again.

The request adapt and retry implementation is followed from https://github.com/wordpress-mobile/WordPressKit-iOS/blob/trunk/WordPressKit/Authenticator.swift

There are no changes to how a Jetpack or WPCOM request is handled. They will be authenticated using the new `RequestAuthenticator`. But there will be no retrying. 

### UI tests
As the network started validating the requests using Alamofire's `validate` method [like this](https://github.com/woocommerce/woocommerce-ios/pull/8483/files#diff-e5de4f95ce59918843a27539494c0fe4cb56643666b6ba692a8598eadbb1a35cR60), the UI tests started failing for mocks without `headers` section. 

The UI tests were failing due to incorrect `Content-Type` in the response.  The `headers` section takes care of adding the `Content-Type` to the mock response. 

To fix this, I added the headers part for all missing mock JSON files. 

## Testing instructions
- Login into the app using WPCOM credentials. (Both Email and Store Address flows)
- Do smoke testing to ensure that everything works as before.
- We don't have any REST API requests migrated. So there is no testing required. Coupons endpoints will be migrated in a future PR. 

## Screenshots
NA

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jaclync — COMMENTED** [review]
Hi @selanthiraiyan 👋  Sorry for some preliminary questions before diving into deeper code review, since I don't know much about this project. Trying to clarify a few things:

- What does the user provide when signing in with the application password for the REST API feature?
- From the issue description:
> WPOrg REST API requests should be authenticated using application password. If there is an authentication failure, we should generate application password and retry the REST API request.

What can trigger the original application password to fail/change, is it a common scenario? Just trying to understand why we need to handle this API failure case only for this new authentication method.

- What does the adapter do? I'm not very familiar with the technical requirements, just wanted to get a full understanding of the changes

If there's a p2 or reference that explains the answers to my questions above, feel free to just drop the link here 🙂

**Comment by selanthiraiyan** [comment]
Thank you, @jaclync, for reviewing the PR. 

Those are great questions. Sorry I couldn't provide enough context in the PR description. 🙏 

> What does the user provide when signing in with the application password for the REST API feature?

The users will provide the site URL, wp-admin username and password.

https://github.com/woocommerce/woocommerce-ios/pull/8459 This PR has an entry point for that flow which you can enable by returning `true` for `applicationPasswordAuthenticationForSiteCredentialLogin` feature flag. Since we don't have any endpoints migrated to REST API yet, you can't really test any features in the app yet. 

> What can trigger the original application password to fail/change, is it a common scenario? Just trying to understand why we need to handle this API failure case only for this new authentication method.

- The scenario that we try to cover here is when the user manually revokes the application password from the `wp-admin` page. 
- There is the other case in which the application password itself would have been disabled in the site using a plugin like Word Fence. We won't be retrying (after regenerating the application password) for that case.

> What does the adapter do? I'm not very familiar with the technical requirements, just wanted to get a full understanding of the changes

- The `RequestAdapter` authenticates the URL request by adding authorization related headers and etc.
- The `RequestRetrier` retries the request if applicable. i.e. For a REST request if the error is `401` the request will be retried after regenerating the application password.

> If there's a p2 or reference that explains the answers to my questions above, feel free to just drop the link here

@hichamboushaba  has written a few P2 posts which discuss the application password authentication. I think the following P2 might be helpful.
pe5sF9-U3-p2

**Comment by jaclync** [comment]
> > What can trigger the original application password to fail/change, is it a common scenario? Just trying to understand why we need to handle this API failure case only for this new authentication method.
> 
> * The scenario that we try to cover here is when the user manually revokes the application password from the `wp-admin` page.

If the user manually revokes the application password from wp-admin, does this mean they intentionally want to disable this authentication method in the app? I'm not sure what the revocation UI looks like in wp-admin, just wondering if it makes more sense to log the user out instead of retrying in this case.

> > What does the adapter do? I'm not very familiar with the technical requirements, just wanted to get a full understanding of the changes
> 
> * The `RequestAdapter` authenticates the URL request by adding authorization related headers and etc.

For authenticating a URL request with auth headers, the pre-existing implementation uses `AuthenticatedRequest` and adds auth headers based on the credentials in `asURLRequest`. Why not do the same for REST requests in `RESTRequest.asURLRequest` or `AuthenticatedRequest.asURLRequest` with a new `Credentials` enum case with an application password instead of using an adapter?

File: Networking/Networking/Network/AlamofireNetwork.swift [hunk 1]
```diff
@@ -48,17 +55,12 @@ public class AlamofireNetwork: Network {
...
-        requestAuthenticator.authenticateRequest(request) { result in
-            switch result {
-            case .success(let request):
-                Alamofire.request(request)
-                    .responseData { response in
-                        completion(response.value, response.networkingError)
-                    }
-            case .failure(let error):
-                completion(nil, error)
+        let request = requestConverter.convert(request)
```
Comment (jaclync) [inline Networking/Networking/Network/AlamofireNetwork.swift:58]: (same for 3 other similar calls) how about including this conversion inside the adapter, since this feels like part of the adapter? then all the auth/conversion details are within the adapter `RequestProcessor`.

File: Networking/Networking/Extensions/String+URL.swift [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import Foundation
+
+extension String {
+    /// Trims front slash
```
Comment (jaclync) [inline Networking/Networking/Extensions/String+URL.swift]: super nit: the implementation looks like it also trims the back slash?

File: Networking/NetworkingTests/Extensions/String+URLTests.swift [hunk 3]
```diff
@@ -0,0 +1,20 @@
+import XCTest
+@testable import Networking
+
+final class String_URLTests: XCTestCase {
```
Comment (jaclync) [inline Networking/NetworkingTests/Extensions/String+URLTests.swift:4]: thanks for adding these tests!

File: Networking/Networking/Requests/RESTRequest.swift [hunk 4]
```diff
@@ -33,7 +33,6 @@ struct RESTRequest: URLRequestConvertible {
     ///     - parameters: Collection of String parameters to be passed over to our target endpoint.
     ///      This can be encoded to the URL request query if the HTTP method is `.get`.
     ///     - headers: Headers to be added to the request.
```
Comment (jaclync) [inline Networking/Networking/Requests/RESTRequest.swift]: nit: this parameter doesn't seem to exist either, maybe it can be removed from the comment as well?

**Comment by selanthiraiyan** [comment]
@jaclync 

> If the user manually revokes the application password from wp-admin, does this mean they intentionally want to disable this authentication method in the app? I'm not sure what the revocation UI looks like in wp-admin, just wondering if it makes more sense to log the user out instead of retrying in this case.

- The mobile app will revoke/delete the password upon logout/switching store.
- There will be a unique name used for application passwords. So, if the user tries to switch to a different device we will be generating a new password.

I think there might be more other scenarios that I didn't cover here. But, Hicham thought through all the scenarios and created a Figma diagram which describes the flow to be followed here. 

XeKDpQTUkwK6FCQmWpb0to-fi-0%3A1&t=QA9ugH57tK2e2jql-1

---- 

> I'm not sure what the revocation UI looks like in wp-admin

https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/ has the details and screenshot about how the UI looks in wp-admin.

---- 

> For authenticating a URL request with auth headers, the pre-existing implementation uses AuthenticatedRequest and adds auth headers based on the credentials in asURLRequest. Why not do the same for REST requests in RESTRequest.asURLRequest or AuthenticatedRequest.asURLRequest with a new Credentials enum case with an application password instead of using an adapter?

I am not sure I understand this question well. I will try to share a couple of points down below. Please let me know if it doesn't clarify.

1. Moving the authentication to the `RequestProcessor` makes the retry process straightforward. i.e. When a request fails, the `RequestRetrier` will generate a new password and schedule that REST request for retrying. When the request is retried, the `RequestAdapter` will take care of authenticating it with the latest credentials. 
1. The `RequestAdapter` and `RequestRetrier` work with `URLRequest` type directly, so I had to make changes to `AuthenticatedRequest` and `UnauthenticatedRequest` to make them work with `URLRequest` instead of `URLRequestConvertible`
1. We previously had the adding headers login in `RESTReqest` file [here](https://github.com/woocommerce/woocommerce-ios/pull/8483/files#diff-8f57060b8a6718867c4871f6e591743c49edc263d90c3e2cd85f87e97ae6f3f2L61-L79). I moved it into `RequestProcessor` which will take care of identifying REST requests [here](https://github.com/woocommerce/woocommerce-ios/pull/8483/files#diff-e2b63cf38f66c7a410720d0644c041faf8dbbca67d1e011e7ce325bd698a596dR66-R74) and scheduling retry if needed.

File: WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc/me/users_me.json [hunk 5]
```diff
@@ -25,6 +25,10 @@
           "administrator"
         ]
       }
+    },
+    "headers": {
+        "Content-Type": "application/json",
+        "Connection": "keep-alive"
```
Comment (jaclync) [inline WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc/me/users_me.json]: I read in the PR description that these headers are now required because of the `validate` call. Is it possible to only validate REST requests in the adapter so that WPCOM/Jetpack requests aren't affected? I'd think the `validate` call takes in and returns a request.

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+    ///
+    init(credentials: Credentials?, applicationPasswordUseCase: ApplicationPasswordUseCase? = nil) {
+        self.credentials = credentials
+        let useCase: ApplicationPasswordUseCase? = {
+            if let applicationPasswordUseCase {
+                return applicationPasswordUseCase
+            } else if case let .wporg(username, password, siteAddress) = credentials {
+                return try? DefaultApplicationPasswordUseCase(username: username,
+                                                              password: password,
+                                                              siteAddress: siteAddress)
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestAuthenticator.swift:28]: Not directly related to this PR: I took a look at what might cause the use case to throw an error, and it looks like it could be from an invalid site address `ApplicationPasswordUseCaseError.invalidSiteAddress`. Can we validate the site address when the user signs in with site credentials so that the use case can be non-nil here?

File: Networking/Networking/ApplicationPassword/RequestProcessor.swift [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+                isAuthenticating = false
+                completeRequests(false)
+            }
+        }
+    }
+
+    func shouldRetry(_ request: Alamofire.Request) -> Bool {
+        guard case let .wporg(_, _, siteAddress) = requestAuthenticator.credentials,
+              let url = request.request?.url,
+              url.absoluteString.hasPrefix(siteAddress + "/" + RESTRequest.Settings.basePath) else {
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestProcessor.swift]: these lines seem to be exactly the same as in `RequestAuthenticator.authenticate`, can this check be moved to `RequestAuthenticator` and called here?

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+        let password = applicationPassword.password.secretValue
+        let loginString = "\(username):\(password)"
+        guard let loginData = loginString.data(using: .utf8) else {
+            return request
+        }
+        let base64LoginString = loginData.base64EncodedString()
+        request.setValue("Basic \(base64LoginString)", forHTTPHeaderField: "Authorization")
+
+        // Cookies from `CookieNonceAuthenticator` should be skipped
+        request.httpShouldHandleCookies = false
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestAuthenticator.swift]: does it make sense to move these auth logic for a REST request to `RESTRequest.asURLRequest`, so that it's similar to `authenticateUsingWPCOMTokenIfPossible` and can be tested separately?

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift [hunk 9]
```diff
@@ -0,0 +1,91 @@
...
+}
+
+private extension RequestAuthenticator {
+    /// Attempts creating a request with WPCOM token if possible.
+    ///
+    func authenticateUsingWPCOMTokenIfPossible(_ urlRequest: URLRequest) throws -> URLRequest {
+        if let credentials, case .wpcom = credentials {
+            return try AuthenticatedRequest(credentials: credentials, request: urlRequest).asURLRequest()
+        }
+        return UnauthenticatedRequest(request: urlRequest).asURLRequest()
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestAuthenticator.swift]: nit: it feels like this can be refactored at its call site to be like

```swift
if let credentials {
  switch credentials {
    case .wpcom:
        return try AuthenticatedRequest(credentials: credentials, request: urlRequest).asURLRequest()
    case .wporg(...):
        return ...
  }
} else {
  return UnauthenticatedRequest(request: urlRequest).asURLRequest()
}
```

**Review by jaclync — COMMENTED** [review]
I left some initial comments from the first pass!

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 9 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift]: Authentication should be done after checking the contents of the `URLRequest` and not by checking the type of `Credentials`. But, I have improved this in commit 5965160b490ecd85069e2d39ab9f9c88f6cb96fa

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 8 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift]: Good point. Done in 5965160b490ecd85069e2d39ab9f9c88f6cb96fa

File: Networking/Networking/ApplicationPassword/RequestProcessor.swift (hunk 7 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestProcessor.swift]: Good idea. Done in https://github.com/woocommerce/woocommerce-ios/pull/8483/commits/4f932ef0417660e204de65e11d82bb37ebb840f5

File: WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc/me/users_me.json (hunk 5 above)
Comment (selanthiraiyan) [reply WooCommerce/WooCommerceUITests/Mocks/mappings/jetpack-blogs/wc/me/users_me.json]: I agree. Done in https://github.com/woocommerce/woocommerce-ios/pull/8483/commits/f890c439905020a4efa5730f4269820555c13b18

I have also reverted the commits which made changes to the mock JSON files.

File: Networking/Networking/Requests/RESTRequest.swift (hunk 4 above)
Comment (selanthiraiyan) [reply Networking/Networking/Requests/RESTRequest.swift]: Done in https://github.com/woocommerce/woocommerce-ios/pull/8483/commits/d0cc935f2dfb90ea9a9824c86ab7ca634f7d3251

File: Networking/Networking/Extensions/String+URL.swift (hunk 2 above)
Comment (selanthiraiyan) [reply Networking/Networking/Extensions/String+URL.swift]: Done in https://github.com/woocommerce/woocommerce-ios/pull/8483/commits/00c84fb6e8094e1ffc5596d661aa60e97f9d629b

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 6 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift:28]: The `DefaultApplicationPasswordUseCase` initialization can throw an error when we are not able to construct login/admin URL using the site address, [here](https://github.com/woocommerce/woocommerce-ios/pull/8483/files#diff-6f412183a8c153584c372b45458f65ddc92da5bdd69e8d90d63463af4298d5c1R77-R78)

I have renamed the error in this commit to explain the scenario better. ae5b15c9df4d4810bcf37786d7efc6c82b80c444

> Can we validate the site address when the user signs in with site credentials so that the use case can be non-nil here?

Sorry I don't understand this. Could you kindly explain how we can improve it? Thank you!

File: Networking/Networking/Network/AlamofireNetwork.swift (hunk 1 above)
Comment (selanthiraiyan) [reply Networking/Networking/Network/AlamofireNetwork.swift:58]: `RequestAdapter` doesn't have access to `URLRequestConvertible`. It only has access to `URLRequest`, so we won't be able to do the conversion from `RequestProcessor`. Kindly let me know if you have other ideas to handle this.

**Comment by selanthiraiyan** [comment]
Thanks for the review, @jaclync!

I have addressed your comments. The PR is ready for the second pass of review. 🙏

**Comment by jaclync** [comment]
> https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/ has the details and screenshot about how the UI looks in wp-admin.

From the wp-admin UI here, it looks like it shows the name of the app with a CTA to revoke. If the user chooses to revoke the application password here, it feels like they intentionally want to remove access from the app? If that's the case, then it feels a bit intrusive how the app just creates another password. I'm sure this has been thought out before, just sharing my observations from the review.

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 6 above)
Comment (jaclync) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift:28]: During the login flow where the user signs in with site credentials, do we check if the login and admin URLs are valid? If so, maybe we don't need to check again so that the initialization always succeeds. I assume the API requests here are after the login flow, please correct me if this isn't the case.

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+    func authenticate(_ urlRequest: URLRequest) throws -> URLRequest {
+        if isRestAPIRequest(urlRequest) {
+            return try authenticateUsingApplicationPasswordIfPossible(urlRequest)
+        } else {
+            return try authenticateUsingWPCOMTokenIfPossible(urlRequest)
+        }
+    }
+
+    func generateApplicationPassword() async throws {
+        guard let applicationPasswordUseCase = applicationPasswordUseCase else {
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestAuthenticator.swift]: nit: might look nicer
```suggestion
        guard let applicationPasswordUseCase else {
```

File: Networking/Networking/Requests/RESTRequest.swift [hunk 11]
```diff
@@ -58,38 +55,7 @@ struct RESTRequest: URLRequestConvertible {
 }
 
 extension RESTRequest {
```
Comment (jaclync) [inline Networking/Networking/Requests/RESTRequest.swift:57]: nit: do you think we can add `RESTRequest` to the [documentation on `URLRequestConvertible`](https://github.com/woocommerce/woocommerce-ios/blob/148b0a955a8390c5d3218bfd8e7c19de709c6c07/docs/NETWORKING.md#urlrequestconvertible)?

File: Networking/Networking/ApplicationPassword/RequestConverter.swift [hunk 12]
```diff
@@ -0,0 +1,17 @@
+import Alamofire
+
+/// Converter to convert Jetpack tunnel requests into REST API requests if needed
+///
+struct RequestConverter {
+    let credentials: Credentials?
+
+    func convert(_ request: URLRequestConvertible) -> URLRequestConvertible {
+        guard let jetpackRequest = request as? JetpackRequest,
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: just wondering, do we only do the conversation from `JetpackRequest`? How about `DotcomRequest` and `WordPressOrgRequest`?

File: Networking/Networking/Requests/AuthenticatedRequest.swift [hunk 13]
```diff
@@ -8,29 +8,43 @@ enum AuthenticatedRequestError: Error {
...
+        let loginString = "\(username):\(password)"
+
+        if let loginData = loginString.data(using: .utf8) {
+            let base64LoginString = loginData.base64EncodedString()
+            authenticated.setValue("Basic \(base64LoginString)", forHTTPHeaderField: "Authorization")
+        }
+
+        // Cookies from `CookieNonceAuthenticator` should be skipped
+        authenticated.httpShouldHandleCookies = false
+        self.request = authenticated
```
Comment (jaclync) [inline Networking/Networking/Requests/AuthenticatedRequest.swift]: After understanding the code a bit more, it looks like the REST request-related logic is in two `URLRequestConvertible` places - `AuthenticatedRequest` (authenticating a REST request) and `RESTRequest` (generating a URL for a REST request). Since these two have to go hand in hand, I'm afraid at some point we're going to mistakenly use `AuthenticatedRequest`'s WPCOM authentication with a `RESTRequest` or vice versa. How about separating `AuthenticatedRequest` into `AuthenticatedDotcomRequest` and `AuthenticatedRESTRequest` so that it's clear which one to use with each type of request?

File: Networking/Networking/Network/AlamofireNetwork.swift (hunk 1 above)
Comment (jaclync) [reply Networking/Networking/Network/AlamofireNetwork.swift:58]: I see, now I understand why it has to be converted here - `URLRequestConvertible` is only available here and not after `sessionManager.request(request)` where the retry takes place, and the conversion requires the site URL from the credentials so it's not possible at the `JetpackRequest` call sites. I can't think of other solutions given these constraints, the only thought I had is to move the authentication step to the `URLRequestConvertible` level but I'm not sure if that works with the retry and what's the best practice.

File: Networking/Networking/ApplicationPassword/RequestProcessor.swift [hunk 14]
```diff
@@ -0,0 +1,87 @@
...
+    func shouldRetry(_ error: Error) -> Bool {
+        // Need to generate application password
+        if .applicationPasswordNotAvailable == error as? RequestAuthenticatorError {
+            return true
+        }
+
+        // Failed authorization
+        if case .responseValidationFailed(reason: .unacceptableStatusCode(code: 401)) = error as? AFError {
+            return true
+        }
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestProcessor.swift:76]: might this trigger a retry for non-REST requests? in the issue description https://github.com/woocommerce/woocommerce-ios/issues/8482, it mentions there's no retry for WPCOM/Jetpack-tunneled requests so just making sure.

File: Networking/Networking/ApplicationPassword/RequestProcessor.swift [hunk 15]
```diff
@@ -0,0 +1,87 @@
...
+            isAuthenticating = true
+
+            do {
+                let _ = try await requestAuthenticator.generateApplicationPassword()
+                isAuthenticating = false
+                completeRequests(true)
+            } catch {
+                isAuthenticating = false
+                completeRequests(false)
+            }
```
Comment (jaclync) [inline Networking/Networking/ApplicationPassword/RequestProcessor.swift:63]: just to clarify: on completion, it would trigger `adapt(_:)` again with an application password if `retry == true` right?

**Comment by jaclync** [comment]
I think I have more understanding of the PR now 😄 thanks for the updates and explanations, I took another pass with some questions/suggestions.

**Review by jaclync — COMMENTED** [review]
I think I have more understanding of the PR now 😄 thanks for the updates and explanations, I took another pass with some questions/suggestions.

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 10 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift]: Done in a3e21d8a6e7422a2fc1489974d61d0a8c7d71ab7

File: Networking/Networking/Requests/RESTRequest.swift (hunk 11 above)
Comment (selanthiraiyan) [reply Networking/Networking/Requests/RESTRequest.swift:57]: Update docs in f1511f824cb5fd9c5746d807f70ccca6bfeb531e and e30bfd550c4f612e268335e043dd356ea436153a

File: Networking/Networking/Requests/AuthenticatedRequest.swift (hunk 13 above)
Comment (selanthiraiyan) [reply Networking/Networking/Requests/AuthenticatedRequest.swift]: Done in e30bfd550c4f612e268335e043dd356ea436153a

File: Networking/Networking/ApplicationPassword/RequestProcessor.swift (hunk 15 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestProcessor.swift:63]: Yes, the `adapt(_:)` method will be called for the retried requests. (which will authenticate the requests)

`completeRequests` [method](https://github.com/woocommerce/woocommerce-ios/pull/8483/files#diff-e2b63cf38f66c7a410720d0644c041faf8dbbca67d1e011e7ce325bd698a596dR81-R86) will retry all the requests from the `requestsToRetry` array if the application password generation is successful.

File: Networking/Networking/ApplicationPassword/RequestProcessor.swift (hunk 14 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestProcessor.swift:76]: [This](https://github.com/woocommerce/woocommerce-ios/pull/8483/files#diff-e2b63cf38f66c7a410720d0644c041faf8dbbca67d1e011e7ce325bd698a596dR36) will take care of filtering REST requests.

File: Networking/Networking/ApplicationPassword/RequestConverter.swift (hunk 12 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: 1. `DotcomRequest` are sent to WordPress.com servers, and it needs WPCOM authentication token. We cannot talk to WPCOM servers using the application password. 
1. `WordPressOrgRequest` will be sent through `WordPressOrgNetwork` instead of `AlamofireNetwork`. 
     - `WordPressOrgNetwork` solely handles `WordPressOrgRequest`, and it doesn't use `RequestConverter`.

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 6 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift:28]: We validate `loginURL` and `adminURL` only while sending `WordPressOrgNetwork`, which currently happens during Jetpack setup [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/Authentication/Jetpack%20Setup/Site%20Credential%20Login/SiteCredentialLoginViewModel.swift#L81-L86). This validation doesn't happen during site address login step. So we need to validate the  `loginURL` and `adminURL` here again.

File: Networking/Networking/Network/AlamofireNetwork.swift (hunk 1 above)
Comment (selanthiraiyan) [reply Networking/Networking/Network/AlamofireNetwork.swift:58]: > the only thought I had is to move the authentication step to the `URLRequestConvertible` level but I'm not sure if that works with the retry and what's the best practice.

Sorry, I don't understand. Do you mean moving the "request conversion step" to `URLRequestConvertible`? 

As the authentication step is already inside the `RequestProcessor`, I don't understand why/how we should move that to `URLRequestConvertible`.

**Comment by selanthiraiyan** [comment]
> From the wp-admin UI here, it looks like it shows the name of the app with a CTA to revoke. If the user chooses to revoke the application password here, it feels like they intentionally want to remove access from the app? If that's the case, then it feels a bit intrusive how the app just creates another password. I'm sure this has been thought out before, just sharing my observations from the review.

I started an internal discussion about this, and we will update this if we decide to follow a different flow. p1672283352691059-slack-C046HDZL87J

**Comment by selanthiraiyan** [comment]
Thanks, @jaclync. I addressed your comments. Kindly take another look when you can. 🙏

File: Networking/Networking/ApplicationPassword/RequestConverter.swift (hunk 12 above)
Comment (jaclync) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: TIL, thanks for the explanation. Now I have another question 😅 what are the differences between `WordPressOrgRequest` and `RESTRequest`? from the `asURLRequest` implementation in both structs, the way it sets the URL feels pretty similar 🤔

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 6 above)
Comment (jaclync) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift:28]: does it make sense to validate these two URLs during the login step so that we don't have to handle this error scenario here? If the URLs are invalid from the beginning, the app doesn't seem usable since it can never generate an application password.

File: docs/architecture-overview.md [hunk 16]
```diff
@@ -169,12 +169,22 @@ of performing this task for us:
         Analog to DotcomRequest, this structure represents a Jetpack Endpoint request. Capable of building a ready-to-use
         URLRequest for a "Jetpack Tunneled" endpoint.
 
-3.  **AuthenticatedRequest**
+3.  **RESTRequest**
+
+        Represents a REST API request which will be used to contact to the site directly. (Skipping Jetpack tunnel) 
+        These requests are authenticated using application passwords.
```
Comment (jaclync) [inline docs/architecture-overview.md]: nit: maybe can mention `AuthenticatedRESTRequest` here?
```suggestion
        These requests are then authenticated using an application password using `AuthenticatedRESTRequest`.
```

File: docs/architecture-overview.md [hunk 17]
```diff
@@ -169,12 +169,22 @@ of performing this task for us:
...
+4.  **AuthenticatedDotcomRequest**
 
         Injects a set of Credentials and a custom user-agent header into anything that conforms to the URLConvertible protocol. Usually wraps up
         a DotcomRequest (OR) JetpackRequest.
 
-4. **UnauthenticatedRequest**
+5.  **AuthenticatedRESTRequest**
+
+        Injects application password and a custom user-agent header into anything that conforms to the URLConvertible protocol. Usually wraps up
+        a RESTRequest.
```
Comment (jaclync) [inline docs/architecture-overview.md]: nit: "anything that conforms to the URLConvertible protocol" might not hold anymore?
```suggestion
        Injects application password and a custom user-agent header into anything that conforms to the URLConvertible protocol and can be authenticated with an application password. For example, a RESTRequest.
```

File: Networking/NetworkingTests/Network/RequestConverterTests.swift [hunk 18]
```diff
@@ -0,0 +1,69 @@
+import XCTest
+import Alamofire
+@testable import Networking
+
+final class RequestConvertorTests: XCTestCase {
+    func test_jetpack_request_is_returned_when_credentials_not_available() {
+        // Given
+        let converter = RequestConverter(credentials: nil)
+        let jetpackRequest = JetpackRequest(wooApiVersion: .mark1, method: .get, siteID: 123, path: "test", availableAsRESTRequest: false)
```
Comment (jaclync) [inline Networking/NetworkingTests/Network/RequestConverterTests.swift]: nit: does it make sense to set `availableAsRESTRequest` to `true` to enable this conversion in any case?

File: Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift [hunk 19]
```diff
@@ -4,35 +4,34 @@ import Alamofire
...
+        let converter = RequestConverter(credentials: nil)
+        let jetpackRequest = JetpackRequest(wooApiVersion: .mark1, method: .get, siteID: 123, path: "test", availableAsRESTRequest: false)
 
         // When
-        var updatedRequest: URLRequestConvertible?
-        authenticator.authenticateRequest(request) { result in
-            updatedRequest = try? result.get()
-        }
+        let request = try converter.convert(jetpackRequest).asURLRequest()
+        let updatedRequest = try authenticator.authenticate(request)
```
Comment (jaclync) [inline Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift]: nit: is the conversion necessary since `availableAsRESTRequest` is `false` already and `RequestConverter` has been tested separately?

File: Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift [hunk 20]
```diff
@@ -4,35 +4,34 @@ import Alamofire
...
 
         // Then
-        XCTAssertTrue(updatedRequest is UnauthenticatedRequest)
```
Comment (jaclync) [inline Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift:19]: nit: does it make sense to recover this assertion? or has the type of request changed?

File: Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift [hunk 21]
```diff
@@ -4,35 +4,34 @@ import Alamofire
...
-        let request = JetpackRequest(wooApiVersion: .mark1, method: .get, siteID: 123, path: "test", availableAsRESTRequest: false)
+        let converter = RequestConverter(credentials: credentials)
+        let jetpackRequest = JetpackRequest(wooApiVersion: .mark1, method: .get, siteID: 123, path: "test", availableAsRESTRequest: false)
 
         // When
-        var updatedRequest: URLRequestConvertible?
-        authenticator.authenticateRequest(request) { result in
-            updatedRequest = try? result.get()
-        }
+        let request = try converter.convert(jetpackRequest).asURLRequest()
```
Comment (jaclync) [inline Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift]: nit: similar to before, the request can be passed directly (`JetpackRequest` or `RESTRequest`) without the converter so that this is testing just one thing (`RequestAuthenticator`)

Same for other test cases in this file.

File: Networking/NetworkingTests/Requests/AuthenticatedDotcomRequestTests.swift [hunk 22]
```diff
@@ -0,0 +1,94 @@
...
+    ///
+    func test_bearer_token_is_injected_as_request_header_when_authenticated_using_WPCOM_token() {
+        // Given
+        XCTAssertEqual(unauthenticatedRequest.allHTTPHeaderFields, [:])
+
+        guard case let .wpcom(_, authToken, _) = credentials else {
+            XCTFail("Missing credentials.")
+            return
+        }
+
```
Comment (jaclync) [inline Networking/NetworkingTests/Requests/AuthenticatedDotcomRequestTests.swift]: nit: do we still need `Credentials`? it looks like we can just pass an auth token string to the next line directly.

Same for other test cases in this file.

**Review by jaclync — APPROVED** [review]
Thanks for all the updates and clarifications, LGTM now 👍 sorry it took a while, since the changes are now 1000+ 😆 

One non-blocking suggestion is to unit test `RequestProcessor` on the retry and adaption behavior. given the current PR size, feel free to consider it for the future.

File: Networking/Networking/ApplicationPassword/RequestConverter.swift (hunk 12 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: - `WordPressOrgRequest` talks to WordPress in general. https://developer.wordpress.org/rest-api/
- `RESTRequest` talks to WooCommerce plugin. https://woocommerce.com/document/woocommerce-rest-api/

File: Networking/Networking/ApplicationPassword/RequestAuthenticator.swift (hunk 6 above)
Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestAuthenticator.swift:28]: > does it make sense to validate these two URLs during the login step so that we don't have to handle this error scenario here?

I agree. Created an issue https://github.com/woocommerce/woocommerce-ios/issues/8506

File: Networking/NetworkingTests/Requests/AuthenticatedDotcomRequestTests.swift (hunk 22 above)
Comment (selanthiraiyan) [reply Networking/NetworkingTests/Requests/AuthenticatedDotcomRequestTests.swift]: Done in c66416dffcf5c28760675b5d4abae33a1b4d24d5

File: Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift (hunk 21 above)
Comment (selanthiraiyan) [reply Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift]: Great point. Done in 7ccf5a4faf00dd6f80d372a4cbda1ce906599b13

File: Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift (hunk 19 above)
Comment (selanthiraiyan) [reply Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift]: Done in 7ccf5a4faf00dd6f80d372a4cbda1ce906599b13

File: Networking/NetworkingTests/Network/RequestConverterTests.swift (hunk 18 above)
Comment (selanthiraiyan) [reply Networking/NetworkingTests/Network/RequestConverterTests.swift]: Done in d0b7993f98e050bcb1e775ef844f7cf78219b30b

File: docs/architecture-overview.md (hunk 17 above)
Comment (selanthiraiyan) [reply docs/architecture-overview.md]: Done in 9464bd1d997a45c3edebe30d2dd4bc21d821131f

File: docs/architecture-overview.md (hunk 16 above)
Comment (selanthiraiyan) [reply docs/architecture-overview.md]: Done in 9464bd1d997a45c3edebe30d2dd4bc21d821131f

File: Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift (hunk 20 above)
Comment (selanthiraiyan) [reply Networking/NetworkingTests/Network/RequestAuthenticatorTests.swift:19]: We will be working with `URLRequest` here. So I had to remove the type checking the assertion and check the header fields directly instead.

**Comment by selanthiraiyan** [comment]
Thank you for your patience and the detailed review, Jaclyn! ❤️ 🙇 
I have addressed your recent comments, and I will go ahead and merge this now. Kindly take another look if you get the time. 🙏 

> One non-blocking suggestion is to unit test RequestProcessor on the retry and adaption behavior. given the current PR size, feel free to consider it for the future.

I created an issue for this. https://github.com/woocommerce/woocommerce-ios/issues/8507

File: Networking/Networking/ApplicationPassword/RequestConverter.swift (hunk 12 above)
Comment (itsmeichigo) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: > 

    WordPressOrgRequest talks to WordPress in general. https://developer.wordpress.org/rest-api/
    RESTRequest talks to WooCommerce plugin. https://woocommerce.com/document/woocommerce-rest-api/

Just chiming in to clarify: I believe `RESTRequest` can be used to handle requests to all WordPress org and Woo requests. The difference between these two types is the way authentication is handled:
- `WordPressOrgRequest` uses cookie authentication.
- `RESTRequest` uses application password.
We should probably come up with better naming for these and update the documentation for clearer explanations.

Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: Thanks for the details, Huong!

`RESTRequest` has this extra parameter/value `let wooApiVersion: WooAPIVersion` when compared to `WordPressOrgRequest`.
I thought the `wooApiVersion` parameter makes it clear that we should use `RESTRequest` for the WooCommerce plugin's REST API-related requests. I looked again now and noticed that `WooAPIVersion` has a case `none` which is an empty string. 

> We should probably come up with better naming for these and update the documentation for clearer explanations.

Maybe we could have a single `struct` instead of two and use the `WooAPIVersion.none` case. What do you think? 

I will create an issue after we finish discussing it here.

Comment (itsmeichigo) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: > Maybe we could have a single struct instead of two and use the WooAPIVersion.none case. What do you think?

This makes sense to me! A few things I notice:
- We're using `WordPressApiValidator` in `WordPressOrgRequest` but this is not necessary. Since `WordPressOrgRequest` is required to conform to `Request`, we can use `PlaceholderDataValidator` instead.
- `WordPressOrgRequest` is not using JSON encoding for `POST` and `PUT` requests like `RESTRequest` does, so unifying them with `RESTRequest` implementation will fix this too.

Let's use `RESTRequest` for both then.

Comment (selanthiraiyan) [reply Networking/Networking/ApplicationPassword/RequestConverter.swift:9]: Created an issue here https://github.com/woocommerce/woocommerce-ios/issues/8512
