### PR TITLE
[Woo POS] Throw error when fetch request fails

### LINKED ISSUE #13565: [Woo POS] Handle simulated product list network error in `POSProductProvider`
From https://github.com/woocommerce/woocommerce-ios/pull/13532#issuecomment-2283197623

If fetching products from the remote in Yosemite fails, we'll get an empty list of products rather than an error. This seems to be due to the initial handling of `func providePointOfSaleItems() async throws -> [POSItem]` , where no errors are thrown, but only an empty array is returned:

```
        } catch {
            DDLogError("No POS items")
            return []
        }
```

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #13565 

## Description
Up until now, if the remote failed to return products within `providePointOfSaleItems()` in Yosemite, we were just retuning an empty array rather of products, rather than handling the error. This would cause that a merchant see the "Empty products" screen rather than the "Error" screen if the fetch request fails at this point. 

This PR addresses this by throwing, rather than returning an empty array, if this happens.

## Changes
* `POSProductProvider` throws `POSError.requestFailed` if the request fails
* Updated unit tests to cover empty and error cases

## Testing
Via proxyman/network tool, or by updating the `POSProductProvider.providePointOfSaleItems()` method, return an empty array and an error, and observe the correct screens appear when running the POS:

* Empty case: 
```diff
    public func providePointOfSaleItems() async throws -> [POSItem] {
        do {
            var products = try await productsRemote.loadAllSimpleProductsForPointOfSale(for: siteID)
+          products = []
```

Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-08-13 at 09 34 16

* Error case:
```diff
    public func providePointOfSaleItems() async throws -> [POSItem] {
        do {
            var products = try await productsRemote.loadAllSimpleProductsForPointOfSale(for: siteID)
+          throw NSError(domain: "", code: 0)
```

Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-08-13 at 09 32 54

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Yosemite/Yosemite/PointOfSale/POSProductProvider.swift [hunk 1]
```diff
@@ -39,17 +39,15 @@ public final class POSProductProvider: POSItemProvider {
...
-            DDLogError("No POS items")
-            return []
+            DDLogError("Failed to retrieve products. Error: \(error)")
+            throw POSError.requestFailed
         }
     }
 
+    enum POSError: Error {
+        case requestFailed
+    }
```
Comment (iamgabrielma) [inline Yosemite/Yosemite/PointOfSale/POSProductProvider.swift]: I went ahead with a simple structure for the error and a single case, but perhaps we want to define these further and use a common POSError everywhere? We could also pass the error messages as an associated value. All of this feels more MVP, but something to take into account.

**Comment by iamgabrielma** [comment]
👋  Only one review is necessary!

File: Yosemite/Yosemite/PointOfSale/POSProductProvider.swift (hunk 1 above)
Comment (staskus) [reply Yosemite/Yosemite/PointOfSale/POSProductProvider.swift]: Good question. I don't know if we want to or can have a single `POSError`, especially given most of the errors come from payment-related code.

My suggestion would be to have:

a) `POSProductProviderError`

```
enum POSProductProviderError: Error {
        case requestFailed
    }
```

b) Propagate errors from `productsRemote` for now, especially since we don't handle them in any special way

```
    public func providePointOfSaleItems() async throws -> [POSItem] {
        let products = try await productsRemote.loadAllSimpleProductsForPointOfSale(for: siteID)

        let eligibilityCriteria: [(Product) -> Bool] = [
            isNotVirtual,
            isNotDownloadable,
            hasPrice
        ]
        let filteredProducts = filterProducts(products: products, using: eligibilityCriteria)

        return mapProductsToPOSItems(products: filteredProducts)
    }
```

**Review by staskus — APPROVED** [review]
Left a suggestion, leaving for you do decide 👍

File: Yosemite/Yosemite/PointOfSale/POSProductProvider.swift (hunk 1 above)
Comment (iamgabrielma) [reply Yosemite/Yosemite/PointOfSale/POSProductProvider.swift]: Thanks! I'm inclined to go with `a` at the moment, so we're more explicit about the type of error. Updated the naming on https://github.com/woocommerce/woocommerce-ios/pull/13586/commits/2fef97ca97056bf1e7ae29909be5796ad6f305c0
