### PR TITLE
Shipping Labels: open Apple Maps or Call the Customer if an error occurs in the address validation form

### LINKED ISSUE #2973: Shipping Labels M2: add option to validate shipping label address details
Once the [shipping label addresses are displayed](https://github.com/woocommerce/woocommerce-ios/issues/2972), we would need to:
- [x] parse the origin address of the store from the site settings.
- [x] for populating the origin address with the correct first and last name of the store owner, we need to explicitly ask for `first_name,last_name` parameters in `loadAccountSettings` method and add the new properties to `AccountSettings` entity.
- [x] call API to validate the origin address. If the address is not valid, the next steps in the creation flow should be greyed out.
- [x] If the origin address is valid, call API to validate the destination address. If the destination address is not valid, the next steps in the creation flow should be greyed out.
- [x] When the **Continue** button is clicked on the origin address section, we need to redirect to the edit address screen.  
- [x] If the validation fails, we need to display an error warning banner at the top of the screen.
- [x] Provide option to use the address as it is.
- [x] If the API response returns a suggested address, we need to display the suggested response and allow the users to select the suggested address.
- [x] Open Apple Maps tapping the error banner on top, if there is an address that can't be validated.
- [x] Add loader during address validation API request.
- [x] Show errors when the name, the company or other essential fields like the address are empty.
- [x] Top Banner autolayout issues

Screenshot 2020-10-14 at 10 43 38 AM
Screenshot 2020-10-14 at 10 43 54 AM
Screenshot 2020-10-14 at 10 44 03 AM

### PR DESCRIPTION
**Pull request by pmusolino**
Closes #2973

## Description
The last part of the address validation form in Shipping Labels is to show the actions for opening the address in Apple Maps if not found to call the customer.
In this PR, I added the two actions in the top banner view, and I implemented two extensions for opening Apple Maps or for calling the user.

## Testing
Note: _It would be preferable to test on the device, as it will not be possible to call the customer's phone number from the simulator._
1. Launch the app in debug mode (because of the feature flag).
2. Open an order detail.
3. Press the button "Create Shipping Label".
4. Press the button "Continue" in Create Shipping Label form, under the **Ship From** cell.
5. Go to the editing address screen and make sure the address is not valid remotely. -> You should see the top banner view with two buttons "Open Map" and "Contact Customer".
6. Tapping "Open Map" you should see that Apple Maps will be opened. If the address is not found on Apple Maps, you should see an error notice.
7. Tapping "Contact Customer" you should be able to call it. If the phone is not valid or the device doesn't support phone calls, you should see an error notice.

## Screenshots

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Tools/MapsHelper.swift [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+    /// The method accept a string of the address info you already have, and open Apple Maps on that address if found.
+    ///
+    static func openAppleMaps(address: String?, completion: @escaping (Result<Void, MapsHelperError>) -> Void) {
+        guard let address = address else {
+            completion(.failure(.locationNotFound))
+            return
+        }
+        CLGeocoder().geocodeAddressString(address) { (placemarksOptional, error) -> Void in
+              if let placemarks = placemarksOptional {
```
Comment (ctarda) [inline WooCommerce/Classes/Tools/MapsHelper.swift]: This is a personal preference, but I tend to find nested if/elses difficult to read. Maybe separating the first if as a `guard let placemarks = placemarksOptional else { completion(.failure(.locationNotFound)) }` could help remove one else later on, kind of flatten things one level?

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift [hunk 2]
```diff
@@ -18,7 +18,21 @@ final class ShippingLabelAddressFormViewController: UIViewController {
...
+            MapsHelper.openAppleMaps(address: self?.viewModel.address?.formattedPostalAddress) { [weak self] (result) in
+                switch result {
+                case .success:
+                    break
+                case .failure:
+                    self?.displayAppleMapsErrorNotice()
+                }
+            }
+        } contactCustomerPressed: { [weak self] in
+            if !PhoneHelper.callPhoneNumber(phone: self?.viewModel.address?.phone) {
```
Comment (ctarda) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift]: This seems to be failing for empty phone numbers

**Review by ctarda — APPROVED** [review]
There seems to be one issue with the phone number validation. In my case, the phone number is empty, but that allows tapping the "contact customer" button and presents an alert with an empty phone number:


Other than that, it works fine. There is an error notice presented on non-valid addresses:


And:
 

 :shipit: . The validation of empty phone numbers could be fixed before merging or deferred to a separate ticket.

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift (hunk 2 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Orders/Order Details/Shipping Labels/Create Shipping Label Form/Shipping Address Validation/ShippingLabelAddressFormViewController.swift]: Good catch, fixed here 991e3160aa4d8368fcb9f6b0b14e84a7a11fee5b
