### PR TITLE
Orders: Support searching for orders with # prefix

### LINKED ISSUE #2506: Orders: Searching for order number doesn't work with # as a prefix in the search
**Describe the bug**

Searching orders for an order number only works if you search for the plain order number (e.g. `123`). The search doesn't work — it returns all the orders in the search results — if you prefix the order number with a `#` symbol (e.g. `#123`).

**To Reproduce**

1. Open the Orders tab.
2. Tap the search icon to start a search.
3. Search for an existing order number, such as `123`.
4. Verify the search results show that order.
5. Search for the same order number with the `#` symbol included in the search, such as `#123`.
6. Notice that the search results now show all orders, instead of returning the same results as before.

**Screenshots**

Search with correct results (no `#`)|Search with incorrect results (with `#`)
-|-
IMG_3672|IMG_3671

**Expected behavior**
Since we show the order numbers in the Orders list with the `#` symbol as a prefix, we should also be able to handle searching for orders with the `#` as a prefix.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.5.1
- WooCommerce iOS version: 4.6.0.2

Source: Original report from a public beta tester, reproduced internally

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #2506

## Description

On the Orders tab, we have the option to search orders by order number. The REST API only supports searching for orders with a plain order number (e.g. `123`); prefixing the order with a `#` (e.g. `#123`) does not return results.

This removes the `#` before performing the search, so that searching e.g. `123` and `#123` returns the same results.

## Changes

* Adds a `sanitizeKeyword(_:)` method to the `SearchUICommand` protocol, along with a default implementation.
* Sanitizes the keyword in `SearchViewController` before performing the remote search and fetching the results from Storage.
* Adds a `sanitizeKeyword(_:)` implementation to `OrderSearchUICommand` to remove the `#` from the search keyword.

Note: I considered using `searchBar(_:shouldChangeTextIn:replacementText:)` (part of the `UISearchBarDelegate` in `SearchViewController`) to validate and sanitize the search input as it's entered, so that `#` couldn't be entered at all in order searches. However, I think the approach used in this PR works better for cases like this where we know that certain characters need to be stripped for the search to work correctly but there isn't a logical reason to prevent them from being entered in the search field.

## Testing

1. Open the Orders tab.
2. Tap the search icon to start a search.
3. Search for an existing order number on your store, such as `123`.
4. Verify the search results show that order.
5. Search for the same order number with the # symbol included in the search, such as `#123`.
6. Confirm the same search results appear, including that order.

## Screenshots

https://user-images.githubusercontent.com/8658164/161769453-52a3d651-c23b-4255-8722-66b2aba4b8b5.mp4

## Submitter Checklist

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift [hunk 1]
```diff
@@ -362,14 +362,14 @@ extension SearchViewController: SyncingCoordinatorDelegate {
...
+        let keyword = searchUICommand.sanitizeKeyword(self.keyword)
         searchUICommand.synchronizeModels(siteID: storeID,
                                           keyword: keyword,
                                           pageNumber: pageNumber,
                                           pageSize: pageSize,
-                                        onCompletion: { [weak self] isCompleted in
+                                          onCompletion: { [weak self] isCompleted in
                                             // Disregard OPs that don't really match the latest keyword
-                                            if keyword == self?.keyword {
+                                            if keyword == self?.searchUICommand.sanitizeKeyword(self?.keyword ?? String()) {
```
Comment (Ecarrion) [inline WooCommerce/Classes/ViewRelated/Search/SearchViewController.swift]: It may be good to do a `guard let self = self else { return }` to avoid so many optional chaining

**Review by Ecarrion — APPROVED** [review]
Looks good!
