### PR TITLE
[Woo POS] Workaround for refreshable task being canceled by redraw

### LINKED ISSUE #14853: [Woo POS] Pulling to refresh while the next page is being loaded results in fullscreen error
Investigation: whenever the item view state is set (e.g. from loading the next page completes) while the refresh control async task is still in progress, the task is canceled and results in an `explicitlyCancelled` error from the networking call. This is because the view is redrawn from the state change, and cancels the refresh control task. Previous discussion: https://github.com/woocommerce/woocommerce-ios/pull/14728#discussion_r1892286471

## Steps to repro

🗒️ If the page size for products is still 100, it's much easier to reproduce this issue by reducing the page size from 100 to 15 for products [here](https://github.com/woocommerce/woocommerce-ios/blob/efe8572e3c69a04a66bc76d2e41b855bb5ff02aa/Networking/Networking/Remote/ProductsRemote.swift#L651).

- Switch to a store eligible for POS, with more than one page of products in POS
- Go to Menu > Point of Sale
- Scroll toward the bottom of the list to trigger the next page load
- Quickly scroll to the top and pull to refresh --> notice a fullscreen error appears

## Expected behavior

The refresh control should ideally cancel the next page load, or at least override the resulting state without an error.

## Example screencast

https://github.com/user-attachments/assets/05823fcf-d389-46eb-be85-4c7a0dba20f9

### LINKED ISSUE #14860: [Woo POS] Retrying products and variations from error UI does not transition to loading state right away
As we removed the initial loading state in https://github.com/woocommerce/woocommerce-ios/pull/14852#discussion_r1912833004 to prevent the PTR error from refresh task being canceled due to redraw, there is a side effect that results in a UX issue. Ideally, we can resolve the root issue to only redraw views whose state changes that would also fix https://github.com/woocommerce/woocommerce-ios/issues/14853.

## Steps to repro

- Switch to a store eligible for POS, with at least one variable product
- Go to Menu > Point of Sale
- Simulate a network error by going offline, or using a proxy tool to abort the request
- Pull to refresh
- Simulate a success response for the products request
- Tap `Retry` --> notice that the UI stays on the error state instead of the loading state
- Do the same steps above for a variation item list

## Expected behavior

Loading UI should be shown right after tapping `Retry`.

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #14853 
Closes: #14860

## Description

There is a known issue initially from Previous discussion in https://github.com/woocommerce/woocommerce-ios/pull/14728#discussion_r1892286471, where the refreshable async task (triggered by pull-to-refresh, abbreviated PTR) gets canceled when the view is redrawn from POS aggregate model's state change. For example, when we set the initial loading state before the remote request. The initial state was removed to prevent redraws to fix the PTR error in the loaded state, but this results in issue #14860 where the Retry action has no loading UI.

Before we can refactor POS aggregate model to provide more granular updates for the SwiftUI views (created an issue in the backlog https://github.com/woocommerce/woocommerce-ios/issues/14869), we want to explore workarounds for the linked issues at the top. Moving `refreshable` task to a detached Task was one option, but the changes looked quite complicated and hard to test. Alternatively, from [this SO answer](https://stackoverflow.com/a/74977961) > Option 1, we can use `task` associated with a unique ID set in `refreshable` to preserve the async task. The UI/UX tradeoff is that the refresh control does not stay visible until the async task is complete. I haven't found a way to programmatically display the refresh control in SwiftUI, we might have to implement a custom refreshable view if we want to ensure the refresh control staying visible when awaiting the async task for these workarounds.

### Set initial loading state in `loadItems`:

* [`WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift`](diffhunk://#diff-b34ef3931ae78bf4b51520edbe9c11abd6bf36d31dfce4882f3b621c5a7e2af9R45-R50): Updated `loadRootItems` and `loadChildItems` methods to set the loading state while preserving existing items. [[1]](diffhunk://#diff-b34ef3931ae78bf4b51520edbe9c11abd6bf36d31dfce4882f3b621c5a7e2af9R45-R50) [[2]](diffhunk://#diff-b34ef3931ae78bf4b51520edbe9c11abd6bf36d31dfce4882f3b621c5a7e2af9R97-R98)

### View updates to use `task` instead of `refreshable` for the async `loadItems`:

* [`WooCommerce/Classes/POS/Presentation/Item Selector/ChildItemList.swift`](diffhunk://#diff-e00b9006e8350a3bbba23158a3c7109cda5523bf7eb46287e08588f69439227bR11-R14): Added a workaround for refresh control issues by introducing a `refreshControlTaskID` state and ensuring only one refresh task is allowed at a time. [[1]](diffhunk://#diff-e00b9006e8350a3bbba23158a3c7109cda5523bf7eb46287e08588f69439227bR11-R14) [[2]](diffhunk://#diff-e00b9006e8350a3bbba23158a3c7109cda5523bf7eb46287e08588f69439227bR38-R49)
* [`WooCommerce/Classes/POS/Presentation/ItemListView.swift`](diffhunk://#diff-7348f0411ea3b05ba08687e582f83a4e93265bb61ff7c7302f398953dd954071R18-R21): Similar to `ChildItemList`, added a `refreshControlTaskID` state to handle refresh control issues and ensure only one refresh task is allowed at a time. [[1]](diffhunk://#diff-7348f0411ea3b05ba08687e582f83a4e93265bb61ff7c7302f398953dd954071R18-R21) [[2]](diffhunk://#diff-7348f0411ea3b05ba08687e582f83a4e93265bb61ff7c7302f398953dd954071R42-R53)

### New test cases:

* [`WooCommerce/WooCommerceTests/POS/Controllers/PointOfSaleItemsControllerTests.swift`](diffhunk://#diff-035efdb132bc0f5bf81f75e3cf647335bf2e4532162bc08f16ead4095da998e4R333-R413): Added new test cases to verify that the loading state is correctly set for root and child items while preserving existing items.

### Issue 1: PTR while the next page is being loaded

🗒️ If the page size for products is still 100, it's much easier to reproduce this issue by reducing the page size from 100 to 15 or 25 for products [here](https://github.com/woocommerce/woocommerce-ios/blob/efe8572e3c69a04a66bc76d2e41b855bb5ff02aa/Networking/Networking/Remote/ProductsRemote.swift#L651).

- Switch to a store eligible for POS, with more than one page of products and variations in POS
- Go to Menu > Point of Sale
- Scroll toward the bottom of the list to trigger the next page load
- Quickly scroll to the top and pull to refresh --> no fullscreen error should appear
- Repeat the above steps for variations of a variable product

### Issue 2: Retry UX

- Switch to a store eligible for POS, with at least one variable product
- Go to Menu > Point of Sale --> items should be loaded
- Simulate a network error by going offline, or using a proxy tool to abort the request
- Pull to refresh --> error UI should be shown
- Simulate a success response for the products request
- Tap Retry --> the loading UI should be shown, and then the loaded state
- Repeat the above steps above for variation item list

## Screenshots

https://github.com/user-attachments/assets/020daa65-c734-42bf-953b-23a629ab941b

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift [hunk 1]
```diff
@@ -35,7 +39,18 @@ struct ItemListView: View {
...
+                return
+            }
+            refreshControlTaskID = .init()
+        }
+        .task(id: refreshControlTaskID) {
+            guard refreshControlTaskID != nil else {
+                return
+            }
             await posModel.loadItems(base: .root)
+            refreshControlTaskID = nil
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/ItemListView.swift]: Would such an approach work? Or does it end up having similar problems as a detached task?
```suggestion
            await Task {
                 await posModel.loadItems(base: .root)
             }.value
```

**Review by staskus — APPROVED** [review]
It's a tricky issue that goes right in the center of SwiftUI state management. 

Would refactoring of the aggregate model make a difference in this case? The view observes `itemsViewState` which changes before and after making the request, which results in a view reload. Or does ability to provide more granular updates would result in only part of `ItemListView` updating while leaving the refresh control not affected? 

I wonder if we should restructure `PointOfSaleItemsController` so it would disptach item loading tasks synchronously and wouldn't allow making all these requests all at once. Especially given every single task can update `itemsViewState`.

Either way, I recognize it's tricky. I gave one suggestion but you may have already considered it.

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/ItemListView.swift]: This does work, at least from a quick test. Perhaps it's a better workaround for now since it leaves the UI as we'd expect it?

There is some suggestion on Stack Overflow that it could cause hard to diagnose issues, because the refresh won't get cancelled when the view's lifetime ends. I tried to break it, and couldn't, and I think the risk of that with a refresh control is quite low.

**Comment by joshheald** [comment]
> Would refactoring of the aggregate model make a difference in this case? The view observes `itemsViewState` which changes before and after making the request, which results in a view reload. Or does ability to provide more granular updates would result in only part of `ItemListView` updating while leaving the refresh control not affected?

This is my expectation – the refresh control is on `ItemListView`'s navigation stack, which contains views that depend on the `posModel.itemsViewState.itemsStack.root` state. The refresh control is above the dependant views in the heirarchy, so as I understand it, the refresh control shouldn't be redrawn when we change that state to `loading`.

If the container state changed (used up the heirarchy in the `PointOfSaleDashboardView`, and part of the same struct), then the `refreshable` would be redrawn, and cancel, but that's what we'd want to happen because that would indicate a different change in state, such that the root list shouldn't show any more.

I'm going to try adopting observation to see if it helps.

In the meantime, I think @jaclync, if you're happy with @staskus' suggested workaround, we should go with that one for now.

File: WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift [hunk 2]
```diff
@@ -42,6 +42,12 @@ class PointOfSaleItemsController: PointOfSaleItemsControllerProtocol {
 
     @MainActor
     private func loadRootItems() async {
+        let items = itemsViewState.itemsStack.root.items
+        let containerState: ItemsContainerState = items.isEmpty ? .loading : .content
+        itemsViewState = .init(containerState: containerState,
+                               itemsStack: ItemsStackState(root: .loading(items),
+                                                           itemStates: [:]))
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift]: Do we definitely want to delete the sublists here, by setting `itemStates` to the empty dictionary? I don't think we should do that until the PTR completes, if possible.

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/POS/Presentation/ItemListView.swift]: Thanks for suggesting this @staskus! I tested it and it worked on my end, it's a better workaround because the refresh control is shown while awaiting the async task and the changes are simpler. The lack of cancellation when the view lifetime ends is a downside, but given the impact this tradeoff seems small.

Comment (jaclync) [reply WooCommerce/Classes/POS/Presentation/ItemListView.swift]: Updated in https://github.com/woocommerce/woocommerce-ios/pull/14870/commits/0e52b0f810da499be07e74622f8ea8839cbe7de3.

File: WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift (hunk 2 above)
Comment (jaclync) [reply WooCommerce/Classes/POS/Controllers/PointOfSaleItemsController.swift]: Great catch! I updated it with a test case with some mock provider refactoring to provide any items in https://github.com/woocommerce/woocommerce-ios/pull/14870/commits/1db7a63f51c24497229161ec99d477ac1a81e791.

**Comment by jaclync** [comment]
> It's a tricky issue that goes right in the center of SwiftUI state management.
> 
> Would refactoring of the aggregate model make a difference in this case? The view observes `itemsViewState` which changes before and after making the request, which results in a view reload. Or does ability to provide more granular updates would result in only part of `ItemListView` updating while leaving the refresh control not affected?
> 
> I wonder if we should restructure `PointOfSaleItemsController` so it would disptach item loading tasks synchronously and wouldn't allow making all these requests all at once. Especially given every single task can update `itemsViewState`.
> 
> Either way, I recognize it's tricky. I gave one suggestion but you may have already considered it.

@joshheald described it well why granular updates should not trigger redraws at the refresh control level in https://github.com/woocommerce/woocommerce-ios/pull/14870#issuecomment-2593247234. Right now, `PointOfSaleDashboardView`'s `posModel` is changed every time the aggregate model's state changes, which probably triggers a redraw of all subviews that depend on `posModel` including `ItemListView`. I tried updating `ItemListView` to remove the direct dependency on the aggregate model and only take in a state enum & reload closure, but it still didn't work because Self changed.

**Comment by jaclync** [comment]
I've updated the PR with Povilas' suggested workaround if anyone would like to test again! If not I'll merge it in a few hours.

**Review by staskus — APPROVED** [review]
I retested again, this time not on simulator but on iPad Air M2 18.2 dvice and couldn't break it. 👍

**Comment by joshheald** [comment]
> This is my expectation – the refresh control is on `ItemListView`'s navigation stack, which contains views that depend on the `posModel.itemsViewState.itemsStack.root` state. The refresh control is above the dependant views in the heirarchy, so as I understand it, the refresh control shouldn't be redrawn when we change that state to `loading`.
> 
> If the container state changed (used up the heirarchy in the `PointOfSaleDashboardView`, and part of the same struct), then the `refreshable` would be redrawn, and cancel, but that's what we'd want to happen because that would indicate a different change in state, such that the root list shouldn't show any more.
> 
> I'm going to try adopting observation to see if it helps.

[I hacked `Observation` in here](https://github.com/woocommerce/woocommerce-ios/compare/trunk...experiment/observable-pos-model-2). I had to comment a bit of stuff out to do it but most of the POS works fine; enough for testing this, at least.

I added the code back to set the `loading` state for new calls to `loadRootItems`, and made some changes to the view hierarchy to make sure that the refreshable isn't redrawn when the root state reloads – see the last commit note for full details.

In short; Observation does seem to fix this problem. I'm going to see whether it also makes animation easier, then look at doing a proper implementation. I'll try to write this up more clearly tomorrow, run out of time today.

**Comment by jaclync** [comment]
> [I hacked `Observation` in here](https://github.com/woocommerce/woocommerce-ios/compare/trunk...experiment/observable-pos-model-2). I had to comment a bit of stuff out to do it but most of the POS works fine; enough for testing this, at least.

Great news! Let's remove the workaround in the refreshable after implementing the Observation framework. It's interesting how we can just use properties now from a look at the branch. It simplifies some of the Combine logic.

Merging this PR now in case the Observation framework changes might take longer as the scope of changes is bigger.
