### PR TITLE
Fix Custom Fields Handling in Storage for both Orders and Products

### LINKED ISSUE #14106: Orders are not loaded
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
We got a few tickets reporting that order are not loading since last update

### PR DESCRIPTION
**Pull request by pmusolino**
Closes #14106

## Description
It has been reported that for some users orders does not load peaMlT-Wz. It seems that this can happen when a store has a lot of custom fields for products, so upserting custom fields creates a deadlock on the writer context, delaying the syncing of orders for around 2 minutes.
This update optimizes the handling of custom fields in both `OrdersUpsertUseCase` and `ProductStore`. The changes improve performance by streamlining the logic for managing custom fields, introducing batch processing, and eliminating redundant operations.

## Summary of changes
- **OrdersUpsertUseCase**
  - Removed checks for the existence of custom fields in `storageOrder` that are not present in `readOnlyOrder`, directly removing them to simplify the logic.
  - Converted the creation of new custom fields from a loop with appends to a map for efficiency.
  - Implemented batch writing for new custom fields to reduce database calls.

- **ProductStore**
  - Improved readability and indentation for better code maintenance.
  - Simplified the logic for removing custom fields that are not in `readOnlyProduct` by directly using a set lookup.
  - Removed redundant operations for managing custom fields.
  - Introduced batch processing for adding new custom fields, thereby optimizing database interactions.

## Steps to reproduce
1. Login to a store with a lot of products and orders, with a lot of custom fields for each one (more than 100).
2. Notice that Order List is not loading, if not after a lot of time.
3. Make sure that in the product detail, the list of custom fields will be loaded correctly (cc @hafizrahman).

## Testing information
Tested that in a store with a lot of custom fields for products and orders, and everything loads properly.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/225">20.6 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift [hunk 1]
```diff
@@ -304,25 +304,25 @@ struct OrdersUpsertUseCase {
...
-                let newStorageMetaData = storage.insertNewObject(ofType: Storage.MetaData.self)
-                newStorageMetaData.update(with: readOnlyCustomField)
-                storageOrder.addToCustomFields(newStorageMetaData)
-            }
-        }
+        // Create a set of metadata IDs from the read-only order for quick lookup
+        let readOnlyMetadataIDs = Set(readOnlyOrder.customFields.map { $0.metadataID })
 
-        // Now, remove any objects that exist in `storageOrder.customFields` but not in `readOnlyOrder.customFields`
+        // Remove any objects that exist in `storageOrder.customFields` but not in `readOnlyOrder.customFields`
```
Comment (itsmeichigo) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: I'll let someone else review this as I also contributed a bit to it, but this comment (and the one for products) should be updated. We are removing all custom fields for the order right?

Comment (pmusolino) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: Fixed here 9d34b5c8b8214eb7147ba806b809da1222700c96

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift [hunk 2]
```diff
@@ -304,25 +304,25 @@ struct OrdersUpsertUseCase {
...
-                                                                       metadataID: readOnlyCustomField.metadataID) {
-                existingStorageMetaData.update(with: readOnlyCustomField)
-            } else {
-                let newStorageMetaData = storage.insertNewObject(ofType: Storage.MetaData.self)
-                newStorageMetaData.update(with: readOnlyCustomField)
-                storageOrder.addToCustomFields(newStorageMetaData)
-            }
-        }
+        // Create a set of metadata IDs from the read-only order for quick lookup
+        let readOnlyMetadataIDs = Set(readOnlyOrder.customFields.map { $0.metadataID })
```
Comment (selanthiraiyan) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: I think this isn't used anywhere.

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift [hunk 3]
```diff
@@ -304,25 +304,25 @@ struct OrdersUpsertUseCase {
...
+        }
+
+        // Create `customFields` objects from the `readOnlyOrder`
+        let newStorageMetaDataArray = readOnlyOrder.customFields.map { readOnlyCustomField in
+            let newStorageMetaData = storage.insertNewObject(ofType: Storage.MetaData.self)
+            newStorageMetaData.update(with: readOnlyCustomField)
+            return newStorageMetaData
+        }
+
+        // Batch writing process of multiple custom fields
```
Comment (selanthiraiyan) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: Nice. 👍

File: Yosemite/Yosemite/Stores/ProductStore.swift [hunk 4]
```diff
@@ -1162,25 +1162,25 @@ extension ProductStore {
...
-                                                                         metadataID: readOnlyCustomField.metadataID) {
-                existingStorageMetaData.update(with: readOnlyCustomField)
-            } else {
-                let newStorageMetaData = storage.insertNewObject(ofType: Storage.MetaData.self)
-                newStorageMetaData.update(with: readOnlyCustomField)
-                storageProduct.addToCustomFields(newStorageMetaData)
-            }
-        }
+        // Create a set of metadata IDs from the read-only product for quick lookup
+        let readOnlyMetadataIDs = Set(readOnlyProduct.customFields.map { $0.metadataID })
```
Comment (selanthiraiyan) [inline Yosemite/Yosemite/Stores/ProductStore.swift]: I think this isn't used anywhere.

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift [hunk 5]
```diff
@@ -304,25 +304,25 @@ struct OrdersUpsertUseCase {
...
         storageOrder.customFields?.forEach { storageCustomField in
-            if readOnlyOrder.customFields.first(where: { $0.metadataID == storageCustomField.metadataID } ) == nil {
-                storageOrder.removeFromCustomFields(storageCustomField)
-                storage.deleteObject(storageCustomField)
-            }
+            storageOrder.removeFromCustomFields(storageCustomField)
+            storage.deleteObject(storageCustomField)
+        }
+
+        // Create `customFields` objects from the `readOnlyOrder`
```
Comment (selanthiraiyan) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: I think we should unit tests to `OrdersUpsertUseCaseTests` to validate that it can handle a large number of `MetaData` items. Right now, I see only tests that add/remove 1 custom field. What do you think?

File: Yosemite/Yosemite/Stores/ProductStore.swift [hunk 6]
```diff
@@ -1162,25 +1162,25 @@ extension ProductStore {
...
         storageProduct.customFields?.forEach { storageCustomField in
-            if readOnlyProduct.customFields.first(where: { $0.metadataID == storageCustomField.metadataID } ) == nil {
-                storageProduct.removeFromCustomFields(storageCustomField)
-                storage.deleteObject(storageCustomField)
-            }
+            storageProduct.removeFromCustomFields(storageCustomField)
+            storage.deleteObject(storageCustomField)
+        }
+
+        // Create `customFields` objects from the `readOnlyProduct`
```
Comment (selanthiraiyan) [inline Yosemite/Yosemite/Stores/ProductStore.swift]: Similar to the other comment. I think we should unit tests to validate that it can handle a large number of MetaData items.

**Review by selanthiraiyan — COMMENTED** [review]
Thanks for working on this, Paolo!

I tested this on a store with a large number of custom fields and I validated that orders are loaded as expected. ✅ 

I will wait for @hafizrahman to test that custom fields are displayed without issues.

**Comment by hafizrahman** [comment]
> Make sure that in the product detail, the list of custom fields will be loaded correctly (cc @hafizrahman).

At this point in this branch, the Product Details is not able to actually show custom fields yet (only shows entry point), with the logic to show them is in a different branch in #14068

However, I was able to test this by putting a breakpoint inside `ProductFormViewController`. For each time I'm entering a Product Detail, I can confirm that `p viewModel.productModel` shows the content of the product and it includes its `customFields` property properly. Since it is what's used to display the content, I'm fairly confident there's no issue here.

Update: additionally, loading the product list screen itself also works fine. This is tested in both iPad and iPhone in iOS 17.5 Simulator with a site with many orders and products, where the products have many custom fields.

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift (hunk 2 above)
Comment (pmusolino) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: Fixed here d51ee596fb1c3c0533cacb338e2eb755c3c3bb8e 👍

File: Yosemite/Yosemite/Stores/ProductStore.swift (hunk 4 above)
Comment (pmusolino) [reply Yosemite/Yosemite/Stores/ProductStore.swift]: d51ee596fb1c3c0533cacb338e2eb755c3c3bb8e

**Comment by selanthiraiyan** [comment]
@pmusolino Please update the PR description to close the issue #14106

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift (hunk 5 above)
Comment (pmusolino) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: Implemented here dd9ca2356ceb1927721114c57c770a18409939ed

File: Yosemite/Yosemite/Stores/ProductStore.swift (hunk 6 above)
Comment (pmusolino) [reply Yosemite/Yosemite/Stores/ProductStore.swift]: The test implemented here dd9ca2356ceb1927721114c57c770a18409939ed should work also for Products

**Comment by pmusolino** [comment]
@selanthiraiyan ready for another check

File: Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift [hunk 7]
```diff
@@ -304,25 +304,23 @@ struct OrdersUpsertUseCase {
...
+        let newStorageMetaDataArray = readOnlyOrder.customFields.map { readOnlyCustomField in
+            let newStorageMetaData = storage.insertNewObject(ofType: Storage.MetaData.self)
+            newStorageMetaData.update(with: readOnlyCustomField)
+            return newStorageMetaData
+        }
+
+        // Batch writing process of multiple custom fields
+        if !newStorageMetaDataArray.isEmpty {
+            storageOrder.addToCustomFields(NSSet(array: newStorageMetaDataArray))
```
Comment (jaclync) [inline Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: @pmusolino Just sharing an observation from some debugging - this line caused the upsert to be triggered twice, with `newStorageMetaDataArray` containing a different custom field object (different Core Data object ID) each time. It's the expected result of the updated approach in this PR, with pre-existing custom fields being deleted and new custom fields re-added.

Comment (selanthiraiyan) [reply Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift]: Thanks, Jaclyn!

From the comment of [the failing unit test](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Yosemite/YosemiteTests/Stores/OrderStoreTests.swift#L971) I wonder whether the updated approach of deleting all the stored custom fields before adding new custom fields will cause any reload or UI issues in screens where we use `EntityListener` to listen to changes to product or order entities. 🤔

**Review by selanthiraiyan — COMMENTED** [review]
Thanks a lot for working on this @pmusolino and @itsmeichigo! I appreciate the efforts. 🙇 

With the new approach of deleting all the `MetaData` items from Storage we are not doing the "upsert" operation of orders and products. i.e. We are not following the "upsert" behaviour, which is to check the existing items from core data and update them. Instead, we delete all the `MetaData` items and add them again regardless of whether something changed. 

I think we should look for a different solution for the following reasons. 


1. [The existing method names and comments](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Yosemite/Yosemite/Stores/Order/OrdersUpsertUseCase.swift#L19-L25) expect an upsert operation instead of deleting everything. This is misleading. 
2. Core data will consider that the entity is changed even if we write the same order or product into the storage again. (which triggers callbacks and UI reloads) This is not expected from an "upsert" process. 

Unfortunately, I don't have any suggestions currently.

**Comment by pmusolino** [comment]
@selanthiraiyan I have pushed new changes here: 3cc83fdf4435a910761b0ebae87ec27c8c667f36. In this update, `MetaData` items will not be deleted; instead, there will be just the usual upsert. As a result, the previous unit test in `OrderStoreTests` will no longer fail. These new changes offer blazing fast performance compared to the previous approach while obtaining the same result. It's just an improvement on how metadata are handled in the main cycle. With these changes, I am no longer able to replicate the issue, and the unit test implemented in this PR still works as expected.
Please take a second look 🙌

File: Yosemite/YosemiteTests/Stores/Order/OrdersUpsertUseCaseTests.swift [hunk 8]
```diff
@@ -262,6 +261,30 @@ final class OrdersUpsertUseCaseTests: XCTestCase {
...
+        let orderUseCase = OrdersUpsertUseCase(storage: backgroundContext)
+        let dispatcher = Dispatcher()
+        let network = MockNetwork()
+        let productStore = ProductStore(dispatcher: dispatcher, storageManager: storageManager, network: network)
+
+        // When
+        DispatchQueue.global(qos: .background).async {
+            orderUseCase.upsert([order])
+            productStore.upsertStoredProducts(readOnlyProducts: [product], in: backgroundContext)
+        backgroundContext.saveIfNeeded()
```
Comment (selanthiraiyan) [inline Yosemite/YosemiteTests/Stores/Order/OrdersUpsertUseCaseTests.swift]: nit: Indentation update needed.

**Review by selanthiraiyan — APPROVED** [review]
This looks great! 👏 

I tested it using the store with issues, and the orders load as expected.

File: Yosemite/YosemiteTests/Stores/Order/OrdersUpsertUseCaseTests.swift (hunk 8 above)
Comment (pmusolino) [reply Yosemite/YosemiteTests/Stores/Order/OrdersUpsertUseCaseTests.swift]: 161f7cd5ba6decc8c5a91f26a3b00ac5f78cffd5
