### PR TITLE
Dynamic Dashboard: Error state for dashboard cards

### LINKED ISSUE #12546: Error state view for cards when failed to load

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12546 

## Description

This PR handles the error state for dashboard cards. The same layout is applied for every card, and there are two actions available: contact support and retry.

## Testing instructions

- Turn off the internet connection on your device and build the app (assuming you are already logged in to a test store).
- Confirm that all cards show the loading state. 
- After all requests time out, confirm that all cards display the error state.
- Tap on "contact support" on any of the error state views, confirm that the support form is displayed.
- Tap on Retry button of any of the error state views, confirm that only the corresponding card is reloaded.
- Confirm that the old error banner is no longer displayed on the Dashboard screen when the Performance card fails to load data. 

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/5533851/abcabdff-a2da-46bf-8a38-3b89f3bbda63

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/200">18.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardView.swift [hunk 1]
```diff
@@ -115,6 +125,8 @@ struct BlazeCampaignDashboardView: View {
             createCampaignButton
                 .padding(.horizontal, Layout.padding)
                 .redacted(reason: viewModel.shouldRedactView ? .placeholder : [])
+                .shimmering(active: viewModel.shouldRedactView)
+                .renderedIf(viewModel.state != .empty)
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardView.swift]: Suggestion: For consistency, consider creating a new property `shouldShowShowCreateCampaignButton` just like `shouldShowShowAllCampaignsButton`. Just like the new `shouldShowSubtitle`.

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardCardErrorView.swift [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+        )
+        static let retry = NSLocalizedString(
+            "dashboardCardErrorView.retry",
+            value: "Retry",
+            comment: "Button to reload the Performance card on the Dashboard screen"
+        )
+        static let done = NSLocalizedString(
+            "dashboardCardErrorView.dismissSupport",
+            value: "Done",
+            comment: "Button to dismiss the support form from the Dashboard stats error screen."
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/DashboardCardErrorView.swift]:
```suggestion
            comment: "Button to dismiss the support form from the Dashboard generic error card."
```

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardCardErrorView.swift [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+        )
+        static let contactSupport = NSLocalizedString(
+            "dashboardCardErrorView.contactSupport",
+            value: "contact support",
+            comment: "Link to open the support form. Should be lowercased."
+        )
+        static let retry = NSLocalizedString(
+            "dashboardCardErrorView.retry",
+            value: "Retry",
+            comment: "Button to reload the Performance card on the Dashboard screen"
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/DashboardCardErrorView.swift]:
```suggestion
            comment: "Button to reload the dashboard card on the Dashboard screen"
```

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardCardErrorView.swift [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+private extension DashboardCardErrorView {
+    enum Layout {
+        static let padding: CGFloat = 16
+    }
+
+    enum Localization {
+        static let errorTitle = NSLocalizedString(
+            "dashboardCardErrorView.errorTitle",
+            value: "Unable to load data",
+            comment: "The title of the error view when failed to load store statistics on the Dashboard screen"
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/DashboardCardErrorView.swift]:
```suggestion
            comment: "The title of the error view when failed to load a Dashboard card"
```

File: WooCommerce/Classes/Extensions/NSMutableAttributedString+Helpers.swift [hunk 5]
```diff
@@ -58,4 +58,15 @@ extension NSMutableAttributedString {
         }
 
     }
+
+    /// Highlight the given substring (case insensitive). It does nothing if the given substring cannot be found in the original string.
+    ///
+    func highlightSubstring(textToFind: String, with color: UIColor = .accent) {
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/Extensions/NSMutableAttributedString+Helpers.swift:64]: Nice addition.

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift [hunk 6]
```diff
@@ -142,32 +142,42 @@ struct StoreOnboardingView: View {
...
-                // Task list
-                VStack(alignment: .leading, spacing: 0) {
-                    ForEach(viewModel.tasksForDisplay) { taskViewModel in
-                        let isLastTask = taskViewModel == viewModel.tasksForDisplay.last
-
-                        StoreOnboardingTaskView(viewModel: taskViewModel,
-                                                showDivider: !isLastTask,
-                                                isRedacted: viewModel.isRedacted) { task in
-                            taskTapped?(task)
+                if viewModel.failedToLoadTasks && !viewModel.isExpanded {
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift:150]: nit: Could you please add a comment to explain why we are checking for `!viewModel.isExpanded` condition? I hope it is to avoid showing the error card on the full screen mode of the onboarding view.

**Review by selanthiraiyan — APPROVED** [review]
This works great, Huong! 🚀 

I left a few non-blocking nits and questions.

File: WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardView.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardView.swift]: Good point! Added in 40cf0623c40678124c085b21f0d7cb822896f845.

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift (hunk 6 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingView.swift:150]: Yup that's my intention. Added a comment for that in 12de8f8395bdc1696f65b03b366ceb5f4d917603.

**Comment by itsmeichigo** [comment]
Thanks @selanthiraiyan for the reviews! I'm enabling auto-merge to unblock the tracking PR 🙇
