### PR TITLE
Analytics Hub: Fix range generation structure

### LINKED ISSUE #8615: Analytics Hub: Inconsistency with My Store stats
Summary
==========
For stores with a vast order flow and numbers, it's possible to easily detect an inconsistency between the stats presented in the My Store section and those inside the Analytics Hub. This is due to a difference in how the My Store section builds the data request date range.

Screen Capture
==========
https://user-images.githubusercontent.com/5920403/211960994-a7caec68-d0e3-4c68-9dcd-8a2efa5f2fdf.mp4

Steps to Reproduce
==========
1. Navigate between the My Store four tabs and the respective Analytics Hub screen and verify the difference of the numbers.

PS: The `Flying Origami` store is highly recommended for reproducing this test scenario.

### PR DESCRIPTION
**Pull request by ThomazFB**
Closes: #8615 

Why
==========
For stores with a vast order flow and numbers, it's possible to easily detect an inconsistency between the stats presented in the My Store section and those inside the Analytics Hub. This is due to a difference in how the My Store section builds the data request date range.

### My Store date range generation

Today: Jan 11, 2023
Time zone: GMT -3
Time: 11 AM GMT -3 or 14h UTC

    - Today
        - Start: 2023-01-11 03:00:00 UTC	
        - End: 2023-01-12 02:59:59 UTC	

    - This Week (named Week to Date in Analytics Hub)
        - Start: 2023-01-08 03:00:00 UTC	
        - End: 2023-01-15 02:59:59 UTC	

    - This Month (named Month to Date in Analytics Hub)
        - Start: 2023-01-01 03:00:00 UTC	
        - End: 2023-02-01 02:59:59 UTC	

    - This Year ((named Year to Date in Analytics Hub))
        - Start: 2023-01-01 03:00:00 UTC	
        - End: 2024-01-01 02:59:59 UTC	

### Current Analytics Hub date range generation
Today: Jan 11, 2023
Time zone: GMT -3
Time: 11 AM GMT -3 or 14h UTC

    - Today
        - Start: 2023-01-11 03:00:00 UTC
        - End: 2023-01-11 14:00:00 UTC

    - Week to Date
        - Start: 2023-01-08 03:00:00 UTC
        - End: 2023-01-11 14:00:00 UTC

    - Month to Date
        - Start: 2023-01-01 03:00:00 UTC 
        - End: 2023-01-11 14:00:00 UTC

    - Year to Date
        - Start: 2023-01-01 03:00:00 UTC
        - End: 2023-01-11 14:00:00 UTC

The My Store section creates the end date far in the future for each tab instead of using the current time. This covers any time zone gap between the app and the store, always fetching as much data in “the future” as possible.

But inside the Analytics Hub, the `to Date` selections will use the end date of the range as the exact instant where the data was requested. This difference between the My Store and the Analytics Hub date range end is the issue source since the Time zone difference between the app and the store will cause the Hub not to fetch everything, while the My Store will.

How
==========
Adjust the internal range generation classes inside the Analytics Hub to follow the same My Store date range generation rule while keeping the expected description. To achieve this, it was necessary to generate the formatted string of each range now range inside each data class, making the request data the same as the `My Store` one for the `Today`, `Week to Date`, `Month to Date`, `Quarter to Date` and `Year to Date`, while keeping the UI description of the ranges the same.

Capture
==========
### Before
https://user-images.githubusercontent.com/5920403/211960994-a7caec68-d0e3-4c68-9dcd-8a2efa5f2fdf.mp4

### After
https://user-images.githubusercontent.com/5920403/211962894-66e4fd99-1429-43b0-8529-71aa63e22dd9.mp4

How to Test
==========
1. Navigate between the My Store four tabs and the respective Analytics Hub screen and verify there's no difference in the numbers between both screens.

PS: The Flying Origami store is highly recommended for reproducing this test scenario.

### CODE REVIEW

File: WooCommerce/Classes/Extensions/Date+Woo.swift [hunk 1]
```diff
@@ -57,6 +57,46 @@ extension Date {
...
+    /// other: 2022-01-01
+    /// returns: Jan 1, 2021 - Jan 1, 2022
+    ///
+    /// receiver: 2022-01-1
+    /// other: nil
+    /// returns: Jan 1, 2022
+    ///
+    func formatAsRange(with other: Date? = nil, timezone: TimeZone, calendar: Calendar) -> String {
+        guard let other = other else {
+            return DateFormatter.Stats.createAnalyticsHubDayMonthYearFormatter(timezone: timezone).string(from: self)
```
Comment (rachelmcr) [inline WooCommerce/Classes/Extensions/Date+Woo.swift]: If we're moving this method into `Date+Woo` as a more general `Date` extension for formatting date ranges, should we also rename the formatters used in the method to something more general (e.g. `createAnalyticsHubDayMonthYearFormatter` renamed to `createDayMonthYearFormatter`) to indicate that they may be relevant for other contexts?

File: WooCommerce/Classes/Extensions/Date+Woo.swift [hunk 2]
```diff
@@ -57,6 +57,46 @@ extension Date {
...
+    /// receiver: 2021-01-01
+    /// other: 2022-01-01
+    /// returns: Jan 1, 2021 - Jan 1, 2022
+    ///
+    /// receiver: 2022-01-1
+    /// other: nil
+    /// returns: Jan 1, 2022
+    ///
+    func formatAsRange(with other: Date? = nil, timezone: TimeZone, calendar: Calendar) -> String {
+        guard let other = other else {
```
Comment (rachelmcr) [inline WooCommerce/Classes/Extensions/Date+Woo.swift]: nit: This can be simplified to `guard let other else {`

File: WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubMonthToDateRangeData.swift [hunk 3]
```diff
@@ -11,14 +11,20 @@ import Foundation
...
     let currentDateEnd: Date?
+    let formattedCurrentRange: String?
+
     let previousDateStart: Date?
     let previousDateEnd: Date?
+    let formattedPreviousRange: String?
 
     init(referenceDate: Date, timezone: TimeZone, calendar: Calendar) {
-        self.currentDateEnd = referenceDate
+        self.currentDateEnd = referenceDate.endOfMonth(timezone: timezone)
```
Comment (rachelmcr) [inline WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubMonthToDateRangeData.swift:32]: Could we add documentation here to explain why we're setting `currentDateEnd` to the end of the month? (Similar documentation in the other "to Date" ranges would also be helpful, for future reference.)

**Review by rachelmcr — APPROVED** [review]
This works as expected to resolve the discrepancies between My Store and Analytics Hub for now. 👍

Before merging this, though, I think it'd help to add documentation to explain why the current date end is being set this way for each of the "to Date" ranges. The changes in this PR are clear with the context provided here, but that documentation will be important later on to understand why it's being set this way.

File: WooCommerce/Classes/Extensions/Date+Woo.swift (hunk 2 above)
Comment (ThomazFB) [reply WooCommerce/Classes/Extensions/Date+Woo.swift]: Oh, good to know! Thanks for the suggestion, fixed here: https://github.com/woocommerce/woocommerce-ios/pull/8613/commits/2db4f0109eeca1523c87c7a8115fd39d2f1b7764

File: WooCommerce/Classes/Extensions/Date+Woo.swift (hunk 1 above)
Comment (ThomazFB) [reply WooCommerce/Classes/Extensions/Date+Woo.swift]: Indeed! Makes sense 😄 Fixed here: https://github.com/woocommerce/woocommerce-ios/pull/8613/commits/2db4f0109eeca1523c87c7a8115fd39d2f1b7764

File: WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubMonthToDateRangeData.swift (hunk 3 above)
Comment (ThomazFB) [reply WooCommerce/Classes/ViewRelated/Dashboard/Analytics Hub/Time Range/Range Data Generation/AnalyticsHubMonthToDateRangeData.swift:32]: Good catch. We should make that clear for all those ranges. Fixed here: https://github.com/woocommerce/woocommerce-ios/pull/8613/commits/57766ae6f19b63013636162155e39365f854430d

**Comment by ThomazFB** [comment]
@rachelmcr thank you so much for your review! I addressed all your suggestions!

**Comment by rachelmcr** [comment]
Thanks, these updates look good to me; I think we can merge this! 👍 

As an aside, I just noticed that the localization for the formatted date ranges is kind of awkward. (For example, in Spanish it shows `ene 1-13, 2023` instead of `1-13 ene 2023` because our formatters don't localize the format.) Maybe as a future improvement we could consider using `DateIntervalFormatter` to create the formatted ranges, but that could be done in a separate PR.

**Comment by ThomazFB** [comment]
Good point @rachelmcr! Thanks for noticing that! I opened an issue to track your suggestion right here: https://github.com/woocommerce/woocommerce-ios/issues/8629. Let me know if the description is clear enough around the suggestion!
