### PR TITLE
Fix ghost layers in the shipping class selector

### LINKED ISSUE #1645: Fix ghost layers in the shipping class selector
The layers seem a bit off in the placeholder state of paginated shipping class list selector screen:

Simulator Screen Shot - iPhone 8 - 2019-12-18 at 21 14 45

perhaps an estimated cell height has to be specified?

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1645

## Cause of issue

After some debugging, the ghost layer doesn't look as expected (see screenshots in #1645) because the cell `BasicTableViewCell`'s layout is frame-based instead of Auto Layout based and thus the ghost layer does not adjust to its superview's frame properly. This PR updated the use of `BasicTableViewCell` to `WooBasicTableViewCell`, an Auto Layout version of `BasicTableViewCell`, with its top margin constraint configurable for other existing usage.

## Changes

- Updated `WooBasicTableViewCell` xib: replaced bottom margin constraint with vertically center constraint, and added an outlet for the top margin constraint with 0 by default to make the vertical constraint configurable.
- Extracted `WooBasicTableViewCell` styling to 3 extension helpers:
  - Plain text style (e.g. used in Order Details > View Billing Information)
  - Actionable style (e.g. used in Product Details > view product link)
  - List selector style, used in the shipping class list selector cells

## Testing

Prerequisite: have a store without shipping classes, or hard code to always show the syncing state

- Launch the app
- Go to Products tab
- Tap on a Product
- Tap "Edit"
- Tap on the shipping settings row
- Tap the Shipping class row --> the ghost layer shouldn't look weird and should be flashing

## Example screenshots

Syncing | List selector | Order Details (plain text style) | Product Details (actionable style)
-- | -- | -- | --
Simulator Screen Shot - iPhone 11 - 2019-12-26 at 14 41 37 | Simulator Screen Shot - iPhone 11 - 2019-12-26 at 14 42 34 | Simulator Screen Shot - iPhone 11 - 2019-12-26 at 14 42 53 | Simulator Screen Shot - iPhone 11 - 2019-12-26 at 14 54 14

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Extensions/WooBasicTableViewCell+Styling.swift [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import UIKit
+
+extension WooBasicTableViewCell {
```
Comment (pmusolino) [inline WooCommerce/Classes/Extensions/WooBasicTableViewCell+Styling.swift]: Nit: Since this is applicable only to a WooBasicTableViewCell, maybe make sense to add the extension at the end of `WooBasicTableViewCell.swift`. So we will remember these methods more easily and conform to the other cells' structure.
