### PR TITLE
Recover from date decoding failures when a fallback or optional date can be used

### LINKED ISSUE #11486: [Products] Resolve decoding errors for `Product` lists
`Product` can fail to decode if it includes an image with a `date_created_gmt` field that can’t be decoded as a `Date`. We could use a try optional when decoding the `Date` fields, so it returns `nil` instead of failing. (We can then use the fallback to `Date()`, which we already have in place).

Sample response with data that can't be decoded:

```
"images": [
        {
          "id": 10000053070,
          "date_created": "-0001-11-30T00:00:00",
          "date_created_gmt": "-0001-11-30T00:00:00",
          "date_modified": "-0001-11-30T00:00:00",
          "date_modified_gmt": "-0001-11-30T00:00:00",
          "src": "https://example.com/woo.jpg",
          "name": "",
          "alt": ""
        }
      ]
```

Discussion: pe5pgL-4bk-p2

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #11486

## Why
A number of networking entities can fail to decode if they have a date field that can't be decoded as a `Date`.

This caused ~3,500 JSON decoding errors so far this month, mostly with these date fields:

* `date_created_gmt`
* `date_modified_gmt`

## How

This fix allows entities to recover from these date decoding failures by allowing a `nil` date (for optional properties) or using a fallback if the date can't be decoded. In many cases the fallback already existed but was only used if the date field was missing, not if the decoding failed.

The fix is applied to the following entities:

* Coupon
* Media
* WordPressMedia
* Order
* OrderNote
* Product
* ProductImage
* ProductReview
* ProductVariation
* Refund

Note: This fix doesn't extend to all date properties, even in these entities. Using fallbacks for some dates that can be updated from the app (e.g. sale dates for `Product`) could overwrite remote data that affects the store in unexpected and potentially negative ways.

## Testing instructions

Optional testing:

1. Prerequisite: Use a tool like Charles Proxy to modify the responses with an unexpected date format (any unexpected format should be fine; see example for images in the `products` response in the original issue: https://github.com/woocommerce/woocommerce-ios/issues/11486).
2. Build and run the app.
3. Open the order tab and confirm the order list loads.
4. Select an order and confirm order notes and refunds load.
5. Open the products tab and confirm the product list loads.
6. Select a product and confirm the product images, reviews, and any variation details load.
7. Open the menu tab > Coupons and confirm the coupon list loads.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/Networking/Model/Order.swift [hunk 1]
```diff
@@ -162,8 +162,8 @@ public struct Order: Decodable, GeneratedCopiable, GeneratedFakeable {
         let currencySymbol = try container.decode(String.self, forKey: .currencySymbol)
         let customerNote = try container.decode(String.self, forKey: .customerNote)
 
-        let dateCreated = try container.decodeIfPresent(Date.self, forKey: .dateCreated) ?? Date()
-        let dateModified = try container.decodeIfPresent(Date.self, forKey: .dateModified) ?? Date()
+        let dateCreated = (try? container.decodeIfPresent(Date.self, forKey: .dateCreated)) ?? Date()
+        let dateModified = (try? container.decodeIfPresent(Date.self, forKey: .dateModified)) ?? Date()
```
Comment (Ecarrion) [inline Networking/Networking/Model/Order.swift:166]: I know that these already had a nill fallback but I wonder if it is ideal to list orders with a different order than the intended one, and how could this affect merchant workflows 🤔

**Review by Ecarrion — APPROVED** [review]

File: Networking/Networking/Model/Order.swift (hunk 1 above)
Comment (rachelmcr) [reply Networking/Networking/Model/Order.swift:166]: Yeah, this was the one fallback I was most skeptical about. But given that the other order data is the same (including status), the orders could still be processed in the same way — just, as you mentioned, maybe a different order. I think that is still better than failing to decode the order list entirely. We can watch out for any feedback about it, though, and a future improvement would still be to show some kind of message in the UI if we have an issue with the decoding.
