### PR TITLE
Fix crash when uploading product images after logging in

### LINKED ISSUE #2337: Crash selecting some images from the device photo library
While I was recording a video while I was reporting another issue on Product Images, I encountered a crash while I was selecting some images from the device photo library.

The attached gif shows the whole process and the crash.

## Environment
- Device: iPhone 11 Pro (simulator)
- iOS version: 13.4
- WooCommerce iOS version: 4.3

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #2337 

## Reason for crash

From the stack trace and crash reason (`Task created in a session that has been invalidated`), it seems related to the background session `backgroundSessionManager: Alamofire.SessionManager` in `AlamofireNetwork`. Since we initialize a background session manager on every login, and each login request [triggers the `AuthenticatedState` init](https://github.com/woocommerce/woocommerce-ios/blob/84b1a8cfd99043c410e7c24fc345637328fe130d/WooCommerce/Classes/Yosemite/DefaultStoresManager.swift#L90) twice, and we are assigning the same identifier to the session, the session gets invalidated and results in a crash when it's trying to make a network request on the invalidated background session.

I'm not super sure why each login action triggers `AuthenticatedState` init twice, there are probably some reasons behind it. Since this is a hotfix, I kept the changes only to address the crash.

## Changes

This PR added a UUID to the background session identifier, so that a new session manager of a different identifier is created when `AuthenticatedState`/`AlamofireNetwork` is reinitialized (e.g. when the user logs in) and the original background session isn't invalidated.

### The app is logged out on launch

- Log out of the app if the app is not already logged out
- Relaunch the app
- Log in to a store
- In Settings > Experimental Features, turn on the Products switch if it was off before
- Go to the Products tab
- Tap on a simple product
- Tap on the "+" cell in the images header
- Tap "Add Photos"
- Choose a photo or take one with camera --> the app used to crash before this PR, and now it should not crash and go back to the product details screen when the image is being uploaded
- Tap "Update" on the product details --> after the update completes, make sure the image is uploaded on web

### The app is logged in on launch

- Launch the app in logged in state
- In Settings > Experimental Features, turn on the Products switch if it was off before
- Go to the Products tab
- Tap on a simple product
- Tap on the "+" cell in the images header
- Tap "Add Photos"
- Choose a photo or take one with camera
- Tap "Update" on the product details --> after the update completes, make sure the image is uploaded on web

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
@oguzkocer since this PR is addressing a crash from one of the release features found during internal testing, this PR is targeting `release/4.3` branch. Please let me know if you have other thoughts!

**Comment by oguzkocer** [comment]
@jaclync That sounds good to me, thank you for the heads up!

File: Networking/Networking/Network/AlamofireNetwork.swift [hunk 1]
```diff
@@ -19,7 +19,8 @@ public class AlamofireNetwork: Network {
     ///
     public required init(credentials: Credentials) {
         self.credentials = credentials
-        let configuration = URLSessionConfiguration.background(withIdentifier: "com.automattic.woocommerce.backgroundsession")
+        let uniqueID = UUID().uuidString
+        let configuration = URLSessionConfiguration.background(withIdentifier: "com.automattic.woocommerce.backgroundsession.\(uniqueID)")
```
Comment (pmusolino) [inline Networking/Networking/Network/AlamofireNetwork.swift:23]: What do you think about adding here a small comment describing why we are using the uniqueID? I think it can be useful for the future

Comment (jaclync) [reply Networking/Networking/Network/AlamofireNetwork.swift:26]: yup! added in: https://github.com/woocommerce/woocommerce-ios/pull/2342/commits/5c012d0ab829219e7f5a08526b65fc74001a44de

**Comment by jaclync** [comment]
Thanks for testing & reviewing @pmusolino! merging now, cc @oguzkocer
