### PR TITLE
Set default values for Blaze Ad Preview when fetching AI suggestions fail

### LINKED ISSUE #14616: Set default values for Blaze ad preview when fetching suggestions fail
##### Android counterpart https://github.com/woocommerce/woocommerce-android/issues/13075

When Blaze API fails to load the suggestion we should avoid showing the ad preview empty and instead set some default values using the selected product data. 

- Use product name for ad title
- Use product short description if available or Description for ad description. 

The idea is to avoid this empty preview:

### PR DESCRIPTION
**Pull request by pmusolino**
Closes: #14616

## Description
In this PR, I updated the logic in the Blaze Campaign Creation form to improve the scenario where AI suggestions fail, preventing an empty and buggy preview from being displayed.

## Changes
- Updated `BlazeCampaignCreationFormViewModel` to enhance the AI suggestion logic by checking if the tagline, description, and ctaText are empty in case of failure, and then populating them with product information.
- Added a test `test_onLoad_does_not_fetch_AI_suggestions_again` to ensure AI suggestions are not fetched again if the tagline, description, and ctaText have already been populated.

## Testing information
1) Start the process to create a new Blaze campaign.
2) Before opening the product, enable the Network Link Conditioner or disable the internet connection.
3) Open the product.
4) Notice that after the alert, which mentions that it is unable to fetch AI data, the preview is populated with product information.
5) Try to continue by opening another view, then return to the Blaze Creation Form.
6) Notice that the information populated with product data is still there.

## Screenshots
| Before            |  After |
:-------------------------:|:-------------------------:
Before | After

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift [hunk 1]
```diff
@@ -323,7 +323,8 @@ final class BlazeCampaignCreationFormViewModel: ObservableObject {
 
     func onLoad() async {
         await withTaskGroup(of: Void.self) { group in
-            if suggestions.isEmpty {
+            // Make sure AI Suggestions are called just if suggestions are empty, and we didn't already populated tagline, description and ctaText.
+            if suggestions.isEmpty && tagline.isEmpty && description.isEmpty && ctaText.isEmpty {
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift:328]: I don't quite understand this part, could you explain why we need the change? From what I understand, `onLoad` is triggered with `task`, i.e. when the creation form appears. There's no other trigger to be prevented.

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift [hunk 2]
```diff
@@ -355,6 +356,11 @@ final class BlazeCampaignCreationFormViewModel: ObservableObject {
                 ctaText = firstSuggestion.ctaText
             }
         } catch {
+            if let name = product?.name, let shortDescription = product?.shortDescription {
+                tagline = name
+                description = shortDescription
+                ctaText = Localization.shopNow
+            }
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: Should this be the other way around? I have a product without short description and the pre-populated tagline makes it look odd:

Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: Do you mean having description = product title and tagline = shortDescription?
From the original issue instructions we have: 
```
Use product name for ad title
Use product short description if available or Description for ad description.
```
then I assume the description it's the tagline here (which appear on top of the "title").

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift (hunk 1 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift:328]: Now, those fields are populated even if the API call fails. Previously, if the API call failed and you navigated to another screen, like moving forward in the navigation, the `loadAISuggestions` would be called again because `suggestions` was empty. However, we now want to avoid calling AI suggestions again if the ad was pre-populated with product information. This prevents unnecessary UI updates, which can be confusing for the user. If the network request initially fails and we populate it with product info, the user might not notice that the ad information was updated with AI suggestions the second time.

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift (hunk 2 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: Thanks for the explanation. Maybe @JorgeMucientes can confirm the requirements?
Either way, I think we should display the description when short description is not available.

Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: I just checked the "Edit Ad" screen, and I think it should remain this way. In fact, the `tagline` has a limited number of characters, which is fewer than the number of characters allowed in the `description`.
I agree on displaying the description, if short description is not available: 38e93e148e6423131fe252495b2c4247664d15e4

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift:328]: Gotcha, so this can be triggered again if tapping Confirm Details and then navigating back 👍

**Comment by itsmeichigo** [comment]
Another thing: should we hide or update the "Suggested by AI" text and the arrow buttons in the Edit Ad screen when we use the pre-populated content? Should we replace these with the option to retry fetching AI recommendations?

**Comment by dangermattic** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: SIGHUP
```
 #  from Dangerfile:6
 #  -------------------------------------------
 #  # `files: []` forces rubocop to scan all files, not just the ones modified in the PR
 >  rubocop.lint(files: [], force_exclusion: true, inline_comment: true, fail_on_inline_comment: true, include_cop_names: true)
 #  
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pmusolino** [comment]
Thanks, @itsmeichigo, for raising the point about suggestions by AI in the Edit Screen. I applied the changes in commit 7dd227c46327dcd70b48dd024965aff95c475ba7, and now the "suggested by AI" section will be hidden if the suggestions don't come from AI. Please feel free to take another look.

**Review by itsmeichigo — APPROVED** [review]
Tested again and confirmed that the Edit ad screen is no longer displaying the "Suggested by AI" text 👍
