### PR TITLE
Reviews: Fix unreliable logic for review age

### LINKED ISSUE #12194: Reviews: Review age is incorrect
A lot of PRs have been failing today due to the unit tests `testAgeCalculationsReturnLast7DaysAgeForAlmostSevenFullDays` and `testAgeCalculationsReturnLastOlderForMoreThanSevenFullDays`. The reason is not due to the flaky tests, but the incorrect [implementation](https://github.com/woocommerce/woocommerce-ios/blob/1cc04aca84d327db6234b57374adf324d481ed44/WooCommerce/Classes/Model/ReviewAge.swift#L27-L55) that checks for month/week differences by calendar instead of day count.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12194 

## Description

This PR fixes the logic for calculating review age. The previous logic checks for calendar month/week/day difference, which is unreliable since we want to display only the difference in hours or days.

Consider the edge case: when the time difference is within 7 days but in calendar it's 1 month difference, the old logic will still return more than 7 days ago.

This PR fixes this by checking for difference in seconds rather than using calendar.

## Testing instructions

- All unit tests should pass.
- It's tricky to test the edge case in action, but if you have a review created last Tuesday, the time on the review detail should says "Last 7 days" instead of "Older than 7 days"

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Model/ReviewAge.swift [hunk 1]
```diff
@@ -25,31 +25,15 @@ extension ReviewAge {
     /// Returns the Age entity that best describes a given timespan.
     ///
     static func from(startDate: Date, toDate: Date) -> ReviewAge {
-        let components = [.day, .weekOfYear, .month] as Set<Calendar.Component>
-        let dateComponents = Calendar.current.dateComponents(components, from: startDate, to: toDate)
+        let timeDifference = toDate.timeIntervalSince(startDate)
+        let oneDayInSeconds: TimeInterval = 86_400
```
Comment (iamgabrielma) [inline WooCommerce/Classes/Model/ReviewAge.swift:29]: By declaring 86400 seconds as one day explicitly, I see we might be using the wrong numbers in the tests? I might be mistaken, but, for example:

- The comment states _"We are going to assume that days are 84400 milliseconds"_. Should be 86400.
- `testAgeCalculationsReturnLast24HoursAgeFor24HoursAnd1Second` should use 86400 + 1 second, uses 84461 instead.
- If `testAgeCalculationsReturnLast24HoursAgeFor23Hours` calculated 1 second before a day, should be 86400 - 1, but uses 84399 instead
- `testAgeCalculationsReturnLast24HoursAgeFor12Hours` uses 43200 correctly.
- `testAgeCalculationsReturnLast7DaysAgeForAlmostSevenFullDays` calculates 7 days as 604760, should be 604800 instead

Side note: Perhaps re-declaring these as 'let numberOfDays` and then, in the tests, passing `numberOfDays * oneDayInSeconds` would be more descriptive?

Comment (itsmeichigo) [reply WooCommerce/Classes/Model/ReviewAge.swift:29]: Good point! I updated the tests in 8e2844edd290c8e28ca7282e983a72f593acf24b. I removed `testAgeCalculationsReturnLast24HoursAgeFor24HoursAnd1Second` because this case will now return "Last 7 days" - I don't see the point of updating the implementation to support this case. LMK what you think.

**Review by iamgabrielma — APPROVED** [review]
LGTM, thanks for taking care of this!
