### PR TITLE
Coupons: Hide limit usage to X Items when discount type is fixed cart

### LINKED ISSUE #6863: Coupons: Should hide "Limit usage to X items" field for fixed cart discount type
While searching for some logic in Core, I found that there's a missing piece of logic that we're not handling on the iOS app. On the WP Admin page, they're hiding the "Limit usage to X items" field on the edit/creation form for coupons of fixed cart discount type:

https://github.com/woocommerce/woocommerce/blob/f0dc99efcd74276341a986ef9059493985ed52b9/plugins/woocommerce/legacy/js/admin/meta-boxes-coupon.js#L34-L38

We should do the same on the iOS app - we should hide this field on both the add/edit coupon form AND the coupon details screen:

| Coupon Details | Usage Restriction |
| ----- | ----- |
|  |

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #6863 by setting a rule inside the `CouponRestriction` view and viewModel to only display the `limit usage to X items` row when the Coupon discount type is different from `fixed cart`.

Screenshots
==========
### Before
https://user-images.githubusercontent.com/5920403/170117633-d1a45346-2f4d-4230-9df8-b984ac7d49ce.mp4

### After
https://user-images.githubusercontent.com/5920403/170117670-c85a7417-645d-4db7-a535-36299fd63068.mp4

How to Test
==========
### Scenario 1
1. Make sure the Coupons experimental toggle is activated
2. Go to the Coupon list, select a Coupon configured with the fixed cart discount type
3. Inside the Coupon details, select the Edit coupon in the action menu
4. Inside the Edit Coupon view, select the `usage restrictions` option
5. Verify that the `limit usage to X items` is **NOT** displayed

### Scenario 2
1. Make sure the Coupons experimental toggle is activated
2. Go to the Coupon list, select a Coupon configured with **any discount type different from fixed cart**
3. Inside the Coupon details, select the Edit coupon in the action menu
4. Inside the Edit Coupon view, select the `usage restrictions` option
5. Verify that the `limit usage to X items` is displayed

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/UsageDetails/CouponRestrictionsViewModel.swift [hunk 1]
```diff
@@ -9,6 +9,8 @@ final class CouponRestrictionsViewModel: ObservableObject {
 
     let currencySymbol: String
 
+    let shouldDisplayLimitUsageToXItemsRow: Bool
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Coupons/Add and Edit Coupons/UsageDetails/CouponRestrictionsViewModel.swift]: I think this property should be a computed variable based on `discountType`. This will be important since I'm adding the option to update the discount type in #6935 - so this property will no longer be constant. Using a computed variable makes sure that `shouldDisplayLimitUsageToXItemsRow` will always be updated when the discount type is updated.

```suggestion
    var shouldDisplayLimitUsageToXItemsRow: Bool {
        discountType != .fixedCart
    }
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 2]
```diff
@@ -68,4 +68,20 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+        XCTAssertFalse(viewModel.shouldDisplayLimitUsageToXItemsRow)
+    }
+
+    func test_shouldDisplayLimitUsageToXItemsRow_is_true_when_fixed_cart_discount_type_is_NOT_set() {
+        let sampleCoupon = Coupon.fake().copy(discountType: .percent)
+        let viewModel = CouponRestrictionsViewModel(coupon: sampleCoupon)
+
+        // Then
+        XCTAssertTrue(viewModel.shouldDisplayLimitUsageToXItemsRow)
+    }
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift]: Thanks for adding these tests!

**Review by itsmeichigo — COMMENTED** [review]
Thanks, Thomaz for the fix! This is working for the current implementation of the Edit Coupon screen 👍 

But a new update is coming with the addition of the option to update discount type in #6935, so we will need to update the visibility of "Limit usage to X Items" accordingly (more details in the comment below).

Another problem I found is that if we set a value to this field when a coupon is of another discount type, and then update the discount type to fixed cart, the field is still visible on the Coupon Details screen. We should probably check to hide this field on this screen also:

**Comment by ThomazFB** [comment]
Thanks @itsmeichigo for your great review! And nice catch with the Coupon details part! I'll fix it later today 🙇 

I have just one question regarding changing the `shouldDisplayLimitUsageToXItemsRow` to computed value property and the issue we're trying to avoid: 

I see that the `CouponRestrictionsViewModel` is stored inside the `AddEditCouponViewModel`, and when we update the discount type in the `AddEditCoupon` view, this change should be reflected inside the `CouponRestrictionsViewModel` too, but looking how it is right now, the `existingCoupon` is only passed there when we initialize the ViewModel, and that ViewModel doesn't store the Coupon, only extracts some specific data. 

So, correct me if I'm wrong, but it looks like the `CouponRestrictionsViewModel` currently doesn't have a way to get this updated discount type that we can use to allow evaluating `shouldDisplayLimitUsageToXItemsRow` any time as a computed value. Maybe we should update this ViewModel inside the `AddEditCoupon` whenever we call the `CouponRestrictions` view?

**Comment by itsmeichigo** [comment]
> but it looks like the `CouponRestrictionsViewModel` currently doesn't have a way to get this updated discount type that we can use to allow evaluating `shouldDisplayLimitUsageToXItemsRow` any time as a computed value.

Great question @ThomazFB! I admit that my suggestion wasn't correct earlier 😅 I was thinking that `shouldDisplayLimitUsageToXItemsRow` was created in `AddEditCouponViewModel` and didn't realize it was in `CouponRestrictionsViewModel`, hence the suggestion.

> Maybe we should update this ViewModel inside the AddEditCoupon whenever we call the CouponRestrictions view?

I'm thinking of something close to this: let's add a property observer to `AddEditCouponViewModel`'s discount type (using `didSet`). So whenever the discount type is updated, we update `shouldDisplayLimitUsageToXItemsRow` on the `CouponRestrictionsViewModel` from the `AddEditCouponViewModel` accordingly. This should be doable since the `AddEditCouponViewModel` keeps a reference to the accompanying `CouponRestrictionsViewModel`. 

How does that sound?

**Comment by ThomazFB** [comment]
@itsmeichigo thanks for the suggestions and discussion! I've addressed the points we discussed and both Coupon details and the Coupon Restrictions are now updated to be aware of discount type changes. I modified the discountType inside the `AddEditCouponViewModel` following your changes in https://github.com/woocommerce/woocommerce-ios/pull/6935 to avoid a complicated merge between both this PR and yours and applied the `didSet` idea. Let me know what you think!

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 3]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
         let expectedTitle = String.localizedStringWithFormat(NSLocalizedString("Exclude Product Categories (%1$d)", comment: ""), 2)
         XCTAssertEqual(viewModel.excludeCategoriesButtonTitle, expectedTitle)
     }
+
+    func test_shouldDisplayLimitUsageToXItemsRow_is_false_when_fixed_cart_discount_type_is_set() {
+        let sampleCoupon = Coupon.fake().copy(discountType: .fixedCart)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:74]: Nit: We should add clear comments for the condition and expectation of each test following Given/When/Then pattern.
```suggestion
        // Given
        let sampleCoupon = Coupon.fake().copy(discountType: .fixedCart)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 4]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+        let viewModel = CouponRestrictionsViewModel(coupon: sampleCoupon)
+
+        // Then
+        XCTAssertFalse(viewModel.shouldDisplayLimitUsageToXItemsRow)
+    }
+
+    func test_shouldDisplayLimitUsageToXItemsRow_is_true_when_fixed_cart_discount_type_is_NOT_set() {
+        let sampleCoupon = Coupon.fake().copy(discountType: .percent)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:83]: Nit: Same comment as above about the missing comment.
```suggestion
        // Given
        let sampleCoupon = Coupon.fake().copy(discountType: .percent)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 5]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+        let viewModel = CouponRestrictionsViewModel(coupon: sampleCoupon)
+
+        // Then
+        XCTAssertTrue(viewModel.shouldDisplayLimitUsageToXItemsRow)
+    }
+
+    func test_shouldDisplayLimitUsageToXItemsRow_is_false_when_discount_type_is_changed_to_fixed_cart() {
+        let sampleCoupon = Coupon.fake().copy(discountType: .percent)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:92]: Nit:
```suggestion
        // Given
        let sampleCoupon = Coupon.fake().copy(discountType: .percent)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 6]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+        let viewModel = CouponRestrictionsViewModel(coupon: sampleCoupon)
+
+        // Then
+        XCTAssertTrue(viewModel.shouldDisplayLimitUsageToXItemsRow)
+
+        viewModel.onDiscountTypeChanged(discountType: .fixedCart)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:99]: Nit:
```suggestion
        // When
        viewModel.onDiscountTypeChanged(discountType: .fixedCart)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 7]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+
+        XCTAssertFalse(viewModel.shouldDisplayLimitUsageToXItemsRow)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:102]: Nit:
```suggestion
        // Then
        XCTAssertFalse(viewModel.shouldDisplayLimitUsageToXItemsRow)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 8]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+    }
+
+    func test_shouldDisplayLimitUsageToXItemsRow_is_true_when_discount_type_is_changed_from_fixed_cart() {
+        let sampleCoupon = Coupon.fake().copy(discountType: .fixedCart)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:107]: Nit:
```suggestion
        // Given
        let sampleCoupon = Coupon.fake().copy(discountType: .fixedCart)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 9]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+        let viewModel = CouponRestrictionsViewModel(coupon: sampleCoupon)
+
+        // Then
+        XCTAssertFalse(viewModel.shouldDisplayLimitUsageToXItemsRow)
+
+        viewModel.onDiscountTypeChanged(discountType: .percent)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:114]: Nit:
```suggestion
        // When
        viewModel.onDiscountTypeChanged(discountType: .percent)
```

File: WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift [hunk 10]
```diff
@@ -68,4 +68,44 @@ final class CouponRestrictionsViewModelTests: XCTestCase {
...
+
+        XCTAssertTrue(viewModel.shouldDisplayLimitUsageToXItemsRow)
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Coupons/CouponRestrictionsViewModelTests.swift:117]: Nit: 
```suggestion
        // Then
        XCTAssertTrue(viewModel.shouldDisplayLimitUsageToXItemsRow)
```

**Review by itsmeichigo — APPROVED** [review]
This works perfectly now 🎉 

I left a few nitpicking comments regarding the unit tests, please feel free to merge this afterward if you fix those issues. Thanks!
