### PR TITLE
Product Price Settings: fixed regular and sale price with thousand separators

### LINKED ISSUE #1794: Product Price Settings: wrong input on regular/sale price with large numbers
I discovered a strange bug that happens in the Product Price Settings when we have multiple large numbers (with thousand separators) in regular and sale price fields. 

1) The first thing is that after inputting the price and pressing done, reopening it shows all the numbers with thousand separators. And if you try to edit it, all the thousand separators will be a comma or a point (it depends on the Currency decimal separator) and you can't delete more than the first number.
2) if you save the number with thousand separators, when you re-open the price settings screen, you will see the price truncated.

This is a GIF of the problem:
pricing bug

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #1794

## Description
This PR fixes a bug that happens when a regular or sale price has one or more thousand separators: the two price text fields became no longer editable, and when you save the price with thousand separators when you re-open the price settings screen, you will see the price truncated.

This is a GIF of the bug:
pricing bug

## Testing
1) Tap Products tab
2) Navigate to a product detail
3) Tap price settings
4) Add a big price number, like `32934567890.45`. Press the done button.
5) Make sure that the product detail now shows the new price as `39,394,567,890.45` followed by the currency symbol of your website (like $). Tap update.
6) Reopen the edit price settings screen. Make sure you see the new price `32934567890.45` and make sure you can edit it.

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by shiki** [comment]
@pmusolino Is this still a WIP? I was wondering if I should review this or not. 😄

**Comment by pmusolino** [comment]
@shiki I think that when a PR is ready for review (since this was a draft) you will receive a notification. Let me know if you received the notification now 👍

File: WooCommerce/Classes/Tools/UnitInputFormatter/PriceInputFormatter.swift [hunk 1]
```diff
@@ -37,14 +37,16 @@ struct PriceInputFormatter: UnitInputFormatter {
...
-
-        // Remove any initial zero number in the string. Es. 00224.30 will be 2224.30
-        formattedText = formattedText.replacingOccurrences(of: "^0+([1-9]+)", with: "$1", options: .regularExpression)
+        let formattedText = text
+            // Replace any characters not in the set of 0-9 with the current decimal separator configured on website
+            .replacingOccurrences(of: "[^0-9]", with: CurrencySettings.shared.decimalSeparator, options: .regularExpression)
+            // Remove any initial zero number in the string. Es. 00224.30 will be 2224.30
+            .replacingOccurrences(of: "^0+([1-9]+)", with: "$1", options: .regularExpression)
+            // Replace all the occurrences of regex plus all the points or comma (but not the last `.` or `,`) like thousand separators
+            .replacingOccurrences(of: "(?:[.,](?=.*[.,])|)+", with: "$1", options: .regularExpression)
```
Comment (shiki) [inline WooCommerce/Classes/Tools/UnitInputFormatter/PriceInputFormatter.swift]: Thank you for writing the comments. Regex is great but it's like reading Assembly code. 😄

**Review by shiki — APPROVED** [review]
Great work! :shipit:
