### PR TITLE
Reload product when review notification received

### LINKED ISSUE #7823: [Products] Product details can show "no ratings" for product even after receiving a review
**Describe the bug**

As reported by @malinajirka:

> When I open product detail, it says there are No Ratings even though there is one rating already in the local db.

Internal ref (including screencast): p5T066-3CP-p2#comment-13654

### PR DESCRIPTION
**Pull request by ealeksandrov**
Fixes: https://github.com/woocommerce/woocommerce-ios/issues/7823

## Description
This PR adds product refresh when new product review push notification is received.
It provides correct review information when product details is opened.

## How

`ProductAction` is dispatched with a product ID from push notification. `ProductsViewController` picks up updated data automatically through `ResultsController<StorageProduct>`.

## Testing

1. Test on device with enabled push notifications.
2. Open products list.
3. Go to the web and publish a new review.
4. Open product details and confirm that the number of reviews is correct.

## Screenshots

before|after
--|--
IMG_2536|IMG_2538

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift [hunk 1]
```diff
@@ -454,6 +454,11 @@ private extension PushNotificationsManager {
             incrementNotificationCount(siteID: notificationSiteID, type: type, incrementCount: 1) { [weak self] in
```
Comment (rachelmcr) [inline WooCommerce/Classes/Notifications/PushNotificationsManager.swift:454]: nit: There's a comment `// Badge: Update` in L449 that confused me because now we're updating the related product in the same block of code. Maybe we could move that comment to just above this line, so it's clear that two different things are being handled here?

**Review by rachelmcr — APPROVED** [review]
Looks great! 🚀

File: WooCommerce/Classes/Notifications/PushNotificationsManager.swift (hunk 1 above)
Comment (ealeksandrov) [reply WooCommerce/Classes/Notifications/PushNotificationsManager.swift:454]: Updated in d186c93
