### PR TITLE
HACK Week: Update media picker to support types other than images for downloadable products

### LINKED ISSUE #5064: Digital/Downloadable products can only be images
Reported on 4327111-zen , related to https://github.com/woocommerce/woocommerce-ios/issues/5063

**Describe the bug**

When we try to attach a digital file to a Digital/Downloadable product via the app, the only available selectable option seems to be images (not other filetypes like .txt, .pdf, etc, .. )

**To Reproduce**
1. Edit a Digital/Downloadable product from the app. If you need to create one, this needs to be done via the browser ( #5063 )
2. Tap on "+ Add more details"
3. Tap on "Downloadable files"
4. Try to attach any non-image file from your device, media library, or URL. These are filtered down and do not show.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #5064 

## What

This PR updates the fetching for WP media library to add an option to remove the image-only filter. This makes it possible to select document files from the media library for downloadable products.

## How
- Updated `MediaRemote` to add a new param `imagesOnly` to decide whether to apply the mime-type filter for the fetch requests.
- Updated `MediaAction` and `MediaStore` to add `imagesOnly` param.
- Renamed and updated `WordPressMediaLibraryPickerViewController` and `WordPressMediaLibraryPickerCoordinator` to add an option to not filter only images.
- Updated `ProductDownloadListViewController` to not apply the image filter when fetching data from the media library for downloadable products.
- Updated `MediaPickingCoordinator` to apply the image filter to work with images only.
- Updated `WordPressMediaLibraryPickerDataSource` to add `imagesOnly` param for filtering contents if needed.
- Updated `Media+WPMediaAsset` to support loading video files.

## Testing instructions

- Log in to a store and switch to the Products tab.
- Select and existing simple product or create a new one.
- In the product form, select the button to add a new photo.
- When the action sheet for photo source is displayed, select WP media library. Notice that only images are displayed in the list.
- Navigate back and select Downloadable Files (enable downloadable in ellipsis menu > Product Settings > Enable downloadable option if the option is not available).
- Select Add File > From WP Media library. Notice that all file types are displayed including document types, audios, videos, etc. Select any file, a new screen should be displayed to edit the file name and URL.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/5533851/f6b7b45d-b077-4fcc-922c-22c3e9311d81

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/Downloadable Files/File List/ProductDownloadListViewController.swift [hunk 1]
```diff
@@ -39,7 +40,7 @@ final class ProductDownloadListViewController: UIViewController {
     private let localFileUploader: LocalFileUploader
 
     private var onDeviceMediaLibraryPickerCompletion: DeviceMediaLibraryPicker.Completion?
-    private var onWPMediaPickerCompletion: WordPressMediaLibraryImagePickerViewController.Completion?
+    private var onWPMediaPickerCompletion: WordPressMediaLibraryPickerViewController.Completion?
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/Downloadable Files/File List/ProductDownloadListViewController.swift]: I know this was here before, but since we're renaming it, I wonder if is there any reason to keep the "WP" reference and coupling it with `WordPressMediaLibraryPickerViewController`? Or a more generic naming and a explicit signature would work?
```
private var onMediaPickerCompletion: (([Media]) -> Void)?
```

I find this confusing since we do have two different types `Media` and `WordPressMedia`, and it seems this difference should only be clear in the networking layer.

**Comment by itsmeichigo** [comment]
@iamgabrielma I didn't know you were already reviewing this - just wanna let you know that I just pushed a change cfd4d16a4e131b04b89456ff390b88973d39d190 to improve the experience as [commented](https://github.com/woocommerce/woocommerce-ios/pull/11353#issuecomment-1842750120) by Sharma in a previous PR. The buttons on the top right should be disabled in the loading state now:


https://github.com/woocommerce/woocommerce-ios/assets/5533851/45e1e370-8353-461f-b904-c29779830ef0

File: WooCommerce/Classes/ViewRelated/Products/Media/Media+WPMediaAsset.swift [hunk 2]
```diff
@@ -31,15 +31,17 @@ extension CancellableMedia: WPMediaAsset {
     }
 
     public func videoAsset(completionHandler: @escaping WPMediaAssetBlock) -> WPMediaRequestID {
-        fatalError("Video is not supported")
+        DDLogWarn("⚠️ Video is not supported for viewing")
+        return 0
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Products/Media/Media+WPMediaAsset.swift:35]: Good change! 💯  I cannot see a reason why we would prefer to crash here.

File: WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryPickerCoordinator.swift [hunk 3]
```diff
@@ -4,27 +4,30 @@ import struct Yosemite.Media
 
 /// Coordinates navigation for picking media from the site's WordPress media library.
 /// `NSObject` is required for `UIAdaptivePresentationControllerDelegate` conformance.
-final class WordPressMediaLibraryImagePickerCoordinator: NSObject {
-    typealias Completion = WordPressMediaLibraryImagePickerViewController.Completion
+final class WordPressMediaLibraryPickerCoordinator: NSObject {
+    typealias Completion = WordPressMediaLibraryPickerViewController.Completion
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryPickerCoordinator.swift:8]: Same as above, do we need this type-alias?  Or being explicit about the return type clarifies the callback intent?
```
  private let onCompletion: ([Media]) -> Void
  
  init(siteID: Int64, imagesOnly: Bool, allowsMultipleSelections: Bool, onCompletion: @escaping ([Media]) -> Void)
```

**Review by iamgabrielma — APPROVED** [review]
Thanks for working on this, works great! 

I've added a couple of comments, but these are more related to the pre-existing code than to the new changes. I have a question though, since you have more context: 

When retrieving media, I see we might call either `loadMediaLibrary` or `loadMediaLibraryFromWordPressSite` depending on logged status/JCP connection. Depending which remote is called, we'll get either a`Media` or a  `WordPressMedia` object in the networking layer, and [we'll convert the latter](https://github.com/woocommerce/woocommerce-ios/blob/4d53caba861ef20a46c8f41401738a1cc8b383da/Yosemite/Yosemite/Stores/MediaStore.swift#L82) to `Media` before passing it to the business logic. Is there any concern when we convert from `WordPressMedia` to `Media` with these changes?

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/Downloadable Files/File List/ProductDownloadListViewController.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/Downloadable Files/File List/ProductDownloadListViewController.swift]: > I find this confusing since we do have two different types Media and WordPressMedia, and it seems this difference should only be clear in the networking layer.

Exactly, that's why we should not interpret this property as returning type `WordPressMedia`, but as returning media from the WP library. I've renamed the property to `onWPLibraryPickerCompletion` to clarify the intention in 831cc34ed11085b5a04eea5953bb11ab525dcb2b.

I'd prefer keeping the completion type of `WordPressMediaLibraryPickerViewController` though. It might not be as readable as keeping the raw type, but it gives the context about where the closure is returned from. Does that make sense?

File: WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryPickerCoordinator.swift (hunk 3 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Media/WordPressMediaLibraryPickerCoordinator.swift:8]: I'll keep this with the same explanation as the above response:

> It might not be as readable as keeping the raw type, but it gives the context about where the closure is returned from

**Comment by itsmeichigo** [comment]
Thanks @iamgabrielma for the reviews!

> When retrieving media, I see we might call either loadMediaLibrary or loadMediaLibraryFromWordPressSite depending on logged status/JCP connection. Depending which remote is called, we'll get either aMedia or a  WordPressMedia object in the networking layer, and [we'll convert the latter](https://github.com/woocommerce/woocommerce-ios/blob/4d53caba861ef20a46c8f41401738a1cc8b383da/Yosemite/Yosemite/Stores/MediaStore.swift#L82) to Media before passing it to the business logic. Is there any concern when we convert from WordPressMedia to Media with these changes?

Good thinking! I just realized that I missed an issue with the `WordPressMedia` decoding for non-image media. This causes failures to load WP Library for users authenticated without Jetpack. I just pushed changes to the decoding and added tests to fix it. This PR is ready for another look when you can.

**Review by iamgabrielma — APPROVED** [review]
Works as expected, good one! 🚢
