### PR TITLE
Use system status endpoint to check Jetpack plugin status

### LINKED ISSUE #11030: [REST API] Incorrect endpoint used for checking Jetpack installation status
WooCommerce 7.9+ added /jetpack/v4/connection/data/ endpoint as part of the Jetpack Connection Package effort. This has a undesired side-effects, since the Android app uses this endpoint to determine whether Jetpack is installed on the side. The app expects 404 code to be returned when Jetpack is not installed, however, the endpoint on Woo 7.9+ returns an answer.

The iOS uses /wp/v2/plugins/jetpack/jetpack endpoint to determine if Jetpack is installed.

For the moment, there's an existing workaround on the backend side which returns 404 for mobile requests when full Jetpack plugin is NOT installed. Ideally, we’d remove this workaround after we update the Android app.

More context in peaMlT-7P-p2

We should align between the two platforms to work together on a fix. More context here: pe5sF9-29D-p2#comment-2999

Issue on Android: https://github.com/woocommerce/woocommerce-android/issues/9397

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #11030 

####  What? 
Starts using the system status endpoint to check the Jetpack plugin installation status. 

####  Why? 

We previously used the `/jetpack/v4/connection/data` endpoint to determine Jetpack installation status. 

The endpoint above is added by the Jetpack Connection Package, so sites that have JCP are detected as having Jetpack the plugin installed which is incorrect. 

We decided to use the `/wc/v3/system_status` endpoint to check the Jetpack installation and activation status. 

Internal - pe5sF9-2aR-p2

####  How? 
- Send a request to the `/wc/v3/system_status` endpoint to determine the Jetpack plugin installation status.
- Continue using `/jetpack/v4/connection/data` endpoint to fetch the Jetpack user email if available.

## Testing instructions
1. Prepare a self-hosted site with WooCommerce but without Jetpack
2. Log in
3. Tap on the Jetpack promotion banner
4. Notice the next screen prompts you to install Jetpack
5. Go back to the main screen
6. Install & activate Jetpack on the site, but don't connect
7. Tap on the Jetpack banner
8. Notice the next screen prompts you to connect an email address to Jetpack
9. From the wp-admin page, setup Jetpack and connect a WPCOM email
10. Tap on the Jetpack banner
11. Notice that the email is prefilled and you are asked to login

## Screenshots
| No Jetpack | Jetpack installed | Jetpack connected |
|--------|--------|--------|
| Simulator Screen Recording - iPhone 14 Pro - 2023-11-01 at 10 29 11 | Simulator Screen Recording - iPhone 14 Pro - 2023-11-01 at 10 31 23 | Simulator Screen Recording - iPhone 14 Pro - 2023-11-01 at 10 36 41 | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift [hunk 1]
```diff
@@ -125,25 +124,21 @@ private extension JetpackSetupCoordinator {
...
     ///
-    func saveJetpackConnectionStateIfPossible(_ result: Result<JetpackUser, Error>) throws {
-        switch result {
-        case .success(let user):
-            requiresConnectionOnly = true
+    func checkJetpackConnectionState() async throws {
+        requiresConnectionOnly = await isJetpackInstalledAndActive()
+        do {
+            let user = try await fetchJetpackUser()
             jetpackConnectedEmail = user.wpcomUser?.email
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift]: 💡 If we want to follow Hicham's suggestion [p1698767013497509/1698766164.511719-slack-C03L1NF1EA3], we can check Jetpack status after checking the fetched user:

  ```suggestion
        do {
            let user = try await fetchJetpackUser()
            jetpackConnectedEmail = user.wpcomUser?.email
            // confirms Jetpack plugin status by checking with the system plugin list.
            // this is to avoid the edge case when Jetpack user is returned even though Jetpack plugin is not installed.
            requiresConnectionOnly = await isJetpackInstalledAndActive()
```

WDYT?

File: WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift [hunk 2]
```diff
@@ -297,20 +291,40 @@ private extension JetpackSetupCoordinator {
...
+                case let .success(plugins):
+                    if let plugin = plugins.first(where: { $0.name.lowercased() == Constants.jetpackPluginName.lowercased() }),
+                       plugin.active {
+                        continuation.resume(returning: true)
+                    } else {
+                        continuation.resume(returning: false)
+                    }
+                case let .failure(error):
+                    DDLogError("⛔️ Failed to sync system plugins. Error: \(error)")
+                    continuation.resume(returning: false)
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift]: ❓ Should we display an alert for the error and block the user from proceeding?

**Review by itsmeichigo — APPROVED** [review]
This works well for me 👍  I left some unblocking comments, let me know what you think.

File: WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift (hunk 2 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift]: Done in https://github.com/woocommerce/woocommerce-ios/pull/11057/commits/0f15ea35c5b571a2835cb6dd4301f9a427818c32

File: WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift]: Good point. 

To follow Hicham's suggestion, I made this change https://github.com/woocommerce/woocommerce-ios/pull/11057/commits/f72f9cc6c3a2f1d6719bf268b9e449a38447de19 due to the following reasons. 
- To avoid doing the error handling for Jetpack installation case. (i.e. To avoid catching 404 and 403 errors of Jetpack installation check request)
- To perform Jetpack installation in all other cases, including error cases except the 404 case.

What do you think?

Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift]: > To avoid doing the error handling for Jetpack installation case. (i.e. To avoid catching 404 and 403 errors of Jetpack installation check request)

This I agree 👍 

> To perform Jetpack installation in all other cases, including error cases except the 404 case.

Regarding this, I believe the code will not be executed in error cases because the method ends when we throw any error. Instead, it will only be triggered when `fetchJetpackUser` succeeds. But it makes sense to keep this call separated for the reason you mentioned above. So this looks good to me.

Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/JetpackSetup/JetpackSetupCoordinator.swift]: > Regarding this, I believe the code will not be executed in error cases because the method ends when we throw any error.

Oh, right. That makes sense. 👍
