### PR TITLE
[Variable Product] - Variation name input should start with uppercase

### LINKED ISSUE #8692: [Variable Product] - Variation name input starts with lowercase instead of uppercase
**Describe the bug**
When adding a new variation attribute name, the first letter is not capitalized, the merchant would need to do an extra tap to make it uppercase. This only happens on the add variation screen. 

**To Reproduce**
1. Go to Product > Add new product > Variable product > Add variation
2. Click on Add Attributes
3. Add a new attribute name
4. See that the first letter of the attribute name is in lowercase instead of uppercase

**Screenshots**

https://user-images.githubusercontent.com/17252150/213347348-9786c3ea-7257-4112-bf52-76bee4b83fca.MP4

**Expected behavior**
The keyboard should start with uppercase when typing the first letter of the attribute.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.7.2
- WooCommerce iOS version: v11.8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by reginabally**
Closes: #8692 

## Description
The first letter is not capitalized when adding a new variation attribute name. The merchant would need to do an extra tap to make it uppercase. This only happens on the add variation screen.

Since `AddAttributeViewController` uses `TextFieldTableViewCell` to initialize the text fields, I added `UITextAutocapitalizationType` option to auto-capitalized the attribute name in the Add Variation Screen.

## Testing instructions

1. Go to Product > Add new product > Variable product > Add variation
2. Click on Add Attributes
3. Add a new attribute name
4. See that the first letter of the attribute name is in uppercase

## Screenshots

https://user-images.githubusercontent.com/40906847/215433722-d52a88db-5561-4dfb-9475-f7e599d6537f.mp4

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by reginabally** [comment]
Hi @ealeksandrov 👋  I can't find a way to create a unit test for this scenario because it requires user input. If this change requires a unit test, can you please point me in the right direction to get it done? A sample from one of the previous PRs would do. Thank you!

File: WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift [hunk 1]
```diff
@@ -4,14 +4,29 @@ import UIKit
 ///
 final class TextFieldTableViewCell: UITableViewCell {
     struct ViewModel {
+        internal init(text: String? = nil, placeholder: String? = nil, onTextChange: ((String?) -> Void)? = nil,
```
Comment (ealeksandrov) [inline WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift]: nit: `internal` is default access level, so we can remove it.
```suggestion
        init(text: String? = nil, placeholder: String? = nil, onTextChange: ((String?) -> Void)? = nil,
```

File: WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift [hunk 2]
```diff
@@ -4,14 +4,29 @@ import UIKit
...
+                      onTextDidBeginEditing: (() -> Void)? = nil, onTextDidReturn: ((String?) -> Void)? = nil,
+                      inputFormatter: UnitInputFormatter? = nil, keyboardType: UIKeyboardType,
+                      returnKeyType: UIReturnKeyType = .default, autocapitalizationType: UITextAutocapitalizationType = .none) {
```
Comment (ealeksandrov) [inline WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift]: nit: for improved readability when you need to wrap list of arguments - place each argument on a new line.

File: WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift [hunk 3]
```diff
@@ -41,6 +56,7 @@ final class TextFieldTableViewCell: UITableViewCell {
         textField.returnKeyType = viewModel.returnKeyType
         textField.addTarget(self, action: #selector(textFieldDidChange(textField:)), for: .editingChanged)
         textField.addTarget(self, action: #selector(textFieldDidBegin(textField:)), for: .editingDidBegin)
+        textField.autocapitalizationType = viewModel.autocapitalizationType
```
Comment (ealeksandrov) [inline WooCommerce/Classes/ViewRelated/ReusableViews/TextFieldTableViewCell.swift]: very nit: I would move `autocapitalizationType` before `addTarget(...)` calls, so lines are grouped logically - styling textfield first, then adding actions.

**Review by ealeksandrov — APPROVED** [review]
Great work! Added only minor style nits :shipit:

> If this change requires a unit test, can you please point me in the right direction to get it done?

We don't usually add unit tests for UIKit-related code. If the PR adds some logic on viewmodel - we can test isolated viewmodel, but here it's used just to store the state, we can't test much. We could test initializing it without providing any arguments and then testing for default values, but I think it's overkill.
```swift
let viewModel = TitleAndTextFieldTableViewCell.ViewModel()

XCTAssertEqual(viewModel.autocapitalizationType, .none)
```

**Comment by reginabally** [comment]
Thank you so much for reviewing the PR, @ealeksandrov!
