### PR TITLE
Fix Vertical Alignment of Empty State

### LINKED ISSUE #2252: Orders Empty States are not vertically aligned
## To Reproduce

1. Use the #2245 branch
2. Navigate to Orders → Search
3. Make sure the keyboard is shown if you're using the simulator. 
4. Pick a filter that is empty.

This seems to be related to the `KeyboardFrameObserver` usage in `EmptyStateViewController`. 

---

More reproducible steps from Garance at p5T066-2p9-p2#comment-8783: 

1. Navigate to Products 
2. Tap on plus button. 
3. Pick Variable product. 
4. Enter a text in the title. Make sure the keyboard is present if you're using the simulator.
5. Abort everything and go back to the Products list. 
6. Tap on plus button again. 
7. Pick Variable product.
4. Tap on Add variations row. This is the result:
    
 
## Expectations

The content should be vertically centered.

### PR DESCRIPTION
**Pull request by shiki**
Fixes #2252. The incorrectly aligned empty state content has been reported almost on every release. The most recent is p5T066-2yX-p2#comment-9591. I started fixing this [more than a year ago](https://github.com/woocommerce/woocommerce-ios/issues/2252#issuecomment-625330625) and didn't get around to it until now. I'm glad @designsimply never stopped reporting these. 😅 

## UI Changes

Before | After 
--------|-------
        |       
  | 
 | 

Large Font Size Scrolling (Before) | After 
--------|-------
|

## Trials and Tribulations

There were two problems here. 

### Non-Zero Keyboard Frame

First, `EmptyStateViewController` [relies on `KeyboardFrameObserver`](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift#L90-L93) to correctly align the content. However, `KeyboardFrameObserver` [can sometimes (or often) return a non-zero `frame`](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift#L50-L52) even if the keyboard is not visible. This causes the [layout calculations in `EmptyStateViewController` ](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift#L208-L229) to incorrectly assume that there is a keyboard present even though there's not. That's why you'll see that the content is aligned at the top. The calculation expected a keyboard to be at the bottom. 🤦 

I fixed that by adding a check in `KeyboardFrameObserver` to always make sure that the `frame` is zero if the keyboard is not supposed to be visible (f94eab89bd728f391cf7fdd0bcca1fa155658cb0).

### Delayed Keyboard Visibility State

I expected the above to be enough to fix the problems. Of course, I have forgotten that life hates me. 🍋 😄 When navigating from Orders Search to an empty filter page, the `KeyboardFrameObserver` still [assumed that the keyboard was present](https://user-images.githubusercontent.com/198826/131189312-34b8ed2f-82a3-4aef-81a0-c58d19e10b0a.png). (╯°□°)╯︵ ┻━┻

What I found was that [`currentState.isVisible` was returning `true`](https://github.com/woocommerce/woocommerce-ios/blob/issue/2252-fix-empty-state-alignment/WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift#L54) even though the keyboard was being dismissed by the time the empty state was shown. And the culprit was `KeyboardStateProvider`, the object that we rely on to give us the keyboard state. It has a delay when [updating the `KeyboardState`](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift#L55-L60). The layout finishes first before `KeyboardStateProvider` gets a chance to change the `isVisible` state to `false`. 

The reason for the delay was `KeyboardFrameObserver` observes [`willShow` and `willHide` notifications](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ViewRelated/Keyboard/KeyboardFrameObserver.swift#L40-L48) while `KeyboardStateProvider` observes [`didShow` and `didHide` notifications](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift#L46-L52). Naturally, `KeyboardFrameObserver`'s notification handlers are executed first with incorrect `isVisible` values. 🤦 

I fixed this by changing `KeyboardStateProvider` to use the `willShow` and `willHide` notifications (5ce160fc7d7e0863eb703301490be370bac38fbd). Since `KeyboardStateProvider` [is initialized in the `ServiceLocator`](https://github.com/woocommerce/woocommerce-ios/blob/0d869cadc0016194e459dd366655a6173edc03f3/WooCommerce/Classes/ServiceLocator/ServiceLocator.swift#L162-L167), we are guaranteed that it will update the `isVisible` value first before `KeyboardFrameObserver` instances.

All of these were obviously my mistakes. 😆 

## Known Problems

There's an issue with how the error banners (https://github.com/woocommerce/woocommerce-ios/pull/4407) interact with the rest of the empty state content. For example, the content does not automatically resize or expand if the banner content is expanded. 

Default (Looks Fine) | Expanded ([Sad Trombone](https://www.youtube.com/watch?v=yJxCdh1Ps48))
--------|-------
 | 

The fix for this can be done separately. I have no idea where to start. ¯\\\_(ツ)\_/¯

## Testing

Please consider running these steps in `develop` first so you'll get a feel of what's being fixed. 🙂 

1. Navigate to Orders → Search. If you're using the simulator, make sure that the keyboard is visible (CMD+K).
2. Tap on an Order Status that has zero orders. 
3. Confirm that the “We're sorry, we couldn't find any .... orders” content is vertically centered. 
4. Navigate to Products. 
5. Tap + to add a product. Pick the Variable product option.
6. Tap on the Add Variations cell. 
7. Confirm that the “Create your first variation...” content is vertically centered.

### Regression Tests

If you can, please do a regression test of the banners by following the steps in #4407.  

## Reviewing 

Only 1 reviewer is needed but anyone can review.

## Author Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] Create an issue for the error banner layout problem: https://github.com/woocommerce/woocommerce-ios/issues/4900

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift [hunk 1]
```diff
@@ -8,7 +8,17 @@ struct KeyboardState: Equatable {
     let isVisible: Bool
     /// The frame of the keyboard when it is fully shown or hidden.
```
Comment (ealeksandrov) [inline WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift:10]: nit: a single newline before comment block can improve readability

**Review by ealeksandrov — APPROVED** [review]
Empty orders view looks good ✅
Empty variations view looks good ✅
Expanded error banner on orders list doesn't interfere with empty state ✅ (but empty state alignment is not perfect as described)

Code LGTM :shipit:
Great work! Special thanks for comments and detailed PR description 👏

File: WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift (hunk 1 above)
Comment (shiki) [reply WooCommerce/Classes/ViewRelated/Keyboard/KeyboardStateProvider.swift:10]: Thanks. I'm never sure about the spacing of these properties. 😅 Added a newline in 9a01ed36bcb8147a9dd066ccfa0f980b7e6286c0.

**Review by shiki — COMMENTED** [review]
Thank you very much for reviewing and testing this thoroughly, @ealeksandrov! 🙏
