### PR TITLE
[Crash] Attempt to fix crash with magic link login

### LINKED ISSUE #3865: Fatal error > WordPressAuthenticator/LoginViewController.swift
CUW: peaMlT-hY-p2

Sentry Issue: [WOOCOMMERCE-IOS-1CQR](https://sentry.io/organizations/a8c/issues/2201838137/?referrer=github_integration)

```
EXC_BREAKPOINT: Fatal error > WordPressAuthenticator/LoginViewController.swift
  File "LoginViewController.swift", in LoginViewController.showLoginEpilogue
  File "LoginViewController.swift", line 238, in LoginViewController.presentEpilogue
  File "LoginViewController.swift", line 264, in LoginViewController.syncWPComAndPresentEpilogue
  File "LoginViewController.swift", line 275, in LoginViewController.syncWPCom
  File "<compiler-generated>", in LoginViewController.syncWPCom
...
(15 additional frame(s) were not displayed)
```

Created by @shiki

---

As of Mar 24: 62 events, 61 users.

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #3865

## Why
As discussed in peaMlT-hY-p2, there is a long-running crash during login that seems to be limited to certain magic link logins. We haven't been able to reproduce the exact scenario seen in crash reports but I have a theory about the root cause and this PR attempts to fix it.

### Cause

There are a few common factors in the crash reports:

* It only happens when logging in with a magic link.
* It seems to happen when users are switching to a new device. This can be seen in their Tracks history, which shows the events leading up to the crash coming from a different device than previous events. 
* The user seems to be in an unexpected authentication state: They are not logged in but they do have a default store set (`ServiceLocator.stores.isAuthenticated` is `false` and `ServiceLocator.stores.needsDefaultStore` is `false`). This can be seen in the app logs, which show an unexpected mix of login flow actions and background updates that should only happen while logged in (e.g. attempting to dispatch logged-in actions, or syncing dashboard data).

I believe the point where the user gets into this auth state is when `DefaultStoresManager` is initialized, if the credentials can't be retrieved:

https://github.com/woocommerce/woocommerce-ios/blob/e5b29b6a8243f477c6c0a5cd6a8ec5e2437192e1/WooCommerce/Classes/Yosemite/DefaultStoresManager.swift#L125

This sets `isAuthenticated` to `false` but doesn't reset the `sessionManager` (including the default store) so `needsDefaultStore` remains `false`. Normally `needsDefaultStore` would be set to `true` when a user is deauthenticated.

### How it happens

Unfortunately I haven't been able to consistently reproduce this crash, but here's what I think is happening:

1. They are probably migrating their data to the new device, but their keychain isn't migrated so they aren't fully authenticated. This gets them into the unexpected auth state.
2. They are taken to the login flow. They choose magic link login, so as soon as they open the magic link they are fully authenticated (logged in with a default store).
3. The magic link login flow handles the link in `WordPressAuthenticator` and presents a `LoginNavigationController`, which eventually tries to show the login epilogue (store picker - where we expect the default store to be set). Note: Presenting the login epilogue requires a navigation controller.
4. At the same time, as soon as they are fully authenticated, `AppCoordinator.start()` treats them as logged in. It checks their user role and then replaces `LoginNavigationController` with `MainTabBarController` as the root view controller.
5. Because the login epilogue requires a navigation controller, it then crashes when it tries to present the epilogue in `LoginViewController.showLoginEpilogue(for:)`.

I believe this wasn't a problem when `AppCoordinator.start()` immediately displayed the logged in UI to fully authenticated users, interrupting the login flow. However, in release 7.2 we delayed that (by checking the user role first) which allows the magic link login flow to proceed long enough to create this race condition.

However, I can't be 100% sure because even in testing I can't figure out the exact conditions/steps to reproduce this (even when testing setting up a new device as I suspect is happening here).

## Fix

This changes how we handle this auth state in two places:

1. `DefaultStoresManager` now fully deauthenticates the user if it's initialized in the unexpected auth state (logged out but with a default store set).
2. `AppCoordinator.start()` now handles this auth state differently from the expected fully logged-out state. It fully deauthenticates the user before starting the login flow, to ensure login can proceed as expected. (Hopefully users won't be able to get into this state anymore, since we're also fixing the root cause in `DefaultStoresManager`.)

This should ensure that users are fully deauthenticated when starting the login flow, so that when they get to the step where they open the magic link it proceeds as expected to the store picker.

Let me know if you have any doubts or concerns about the cause or fix here.

## Testing instructions

Because I don't have steps to reproduce this crash, please build and run the app and confirm that you see the expected state and the app behaves as expected while authenticated or deauthenticated.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/AppCoordinatorTests.swift [hunk 1]
```diff
@@ -568,6 +568,25 @@ final class AppCoordinatorTests: XCTestCase {
         }
         XCTAssertNil(loginNavigationController.presentedViewController)
     }
+
+    func test_appCoordinator_start_resets_default_store_and_proceeds_to_login_when_isAuthenticated_and_needsDefaultStore_are_false() {
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/AppCoordinatorTests.swift:572]: nice with a test case 👍

File: WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift [hunk 2]
```diff
@@ -468,6 +468,18 @@ final class StoresManagerTests: XCTestCase {
...
     }
+
+    /// Verifies that default store is reset when initialized in an unexpected state: deauthenticated state with default store set.
+    ///
+    func test_it_resets_default_store_when_initialized_with_deauthenticated_state_and_default_store_set() {
+        // Given
+        let sessionManager = SessionManager.makeForTesting(defaultSite: Site.fake().copy(siteID: 123))
+        let manager = DefaultStoresManager(sessionManager: sessionManager)
+
+        // Assert
```
Comment (jaclync) [inline WooCommerce/WooCommerceTests/Yosemite/StoresManagerTests.swift]: super nit: just to follow the Given/When/Then pattern
```suggestion
        // Then
```

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift [hunk 3]
```diff
@@ -79,7 +79,13 @@ final class AppCoordinator {
 
                 // More details about the UI states: https://github.com/woocommerce/woocommerce-ios/pull/3498
                 switch (isLoggedIn, needsDefaultStore) {
-                case (false, true), (false, false):
+                case (false, true):
+                    self.displayAuthenticatorWithOnboardingIfNeeded()
+                case (false, false):
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/AppCoordinator.swift:84]: nit: what do you think about adding logging here like `DDLogError` or `DDLogWarn` just in case the crash persists and we can confirm that it isn't from this unexpected auth state?

**Review by jaclync — APPROVED** [review]
Thanks for the very detailed analysis and finding the common patterns on Tracks! Your theory sounds very plausible, and the changes LGTM  🚀 

Just an unrelated question, were you able to log in with a magic link from your testing? When tapping on the link, it kept deep linking to the Jetpack app. I wonder if it might be just an issue on my end, or it could be from the domain change to woo.com.

File: WooCommerce/Classes/ViewRelated/AppCoordinator.swift (hunk 3 above)
Comment (rachelmcr) [reply WooCommerce/Classes/ViewRelated/AppCoordinator.swift:84]: Good idea! Added logging in 21a55b3.

**Comment by rachelmcr** [comment]
> were you able to log in with a magic link from your testing?

Yeah, I don't have any problems logging in with a magic link, even with the Jetpack app installed. Not sure what's going on with the deep linking for you. 🤔 Those magic links should still use the `woocommerce://` scheme and direct to the app.
