### PR TITLE
5320 Show card reader connection postal code error

### LINKED ISSUE #5320: [Mobile Payments] Reader will fail to connect if store postal code does not conform to postal codes for their country
The Stripe API will reject location API requests where the supplied postal code doesn't make sense for the supplied country.

An appropriate error message should be displayed that leads the merchant to correct their store's address

Not sure if this is a likely case, however, so I am prioritizing this initially as low

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #5320 

Merge #5552 before this

### Description

This adds a specific error state for when the Postal Code is rejected by Stripe. Unfortunately, we don't get an adminUrl back in this case, so there's no straightforward signposting to the user with a button to go directly to the WP-Admin page.

### Testing instructions

1. With a store set up for In-Person Payments, go to `WP-Admin > WooCommerce > Settings` and change the contents of `Postcode/ZIP` to a non-US format, or delete.
2. In the app, go to `⚙️ > In-Person Payments > Manage Card Reader`
3. Search for and connect to a reader (or simulated reader)
4. Observe that the error message is shown telling the merchant to update their address.
5. Update the address in WP-Admin to include the correct `Postcode/ZIP` again
6. Tap retry, and connect to the reader again.

### Screenshots

https://user-images.githubusercontent.com/2472348/144096589-ac5add73-cd71-48b8-b1e2-a477720f908a.mp4

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift [hunk 1]
```diff
@@ -0,0 +1,71 @@
+import UIKit
```
Comment (allendav) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift:1]: Instead of adding a modal for each error, since the only thing changing is the title, could we do something with `CardPresentModalRetryableError` instead? (Same comment basically for the incomplete address error PR.)

**Comment by allendav** [comment]
This PR depends a lot on the answers to the review feedback in #5515 - I'll circle back to this PR after we connect on that first.

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift:1]: Thanks, I didn't see that one. 

We can't use `CardPresentModalRetryableError` for the incomplete address error, because of #5552 – the behaviour needed is more than just to retry, before you retry it opens up a web view or takes you to Safari to fix the issue.

Really it would be nice if we could do the same thing for this error, but we don't get the URL from the API in that case. Because we don't have the URL, there's a bit more signposting here using the `bottomTitle` to tell the user what to do. We could use the `CardPresentModalRetryableError` in this case, but it's set up as a simple generic retryable error, so we'd need to make it more configurable. I'll add a convenience init so that we can use the existing class that way.

Comment (joshheald) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift:1]: > We could use the CardPresentModalRetryableError in this case, but it's set up as a simple generic retryable error, so we'd need to make it more configurable. I'll add a convenience init so that we can use the existing class that way.

[I've done that here](https://github.com/woocommerce/woocommerce-ios/compare/issue/5320-show-postcode-error-on-card-reader-connection...issue/5320-use-retryable-error-for-postcode-issues)... but I'm not sure that it's much of an improvement so have kept it on a separate branch. Let me know what you think.

**Comment by allendav** [comment]
> Unfortunately, we don't get an adminUrl back in this case, so there's no straightforward signposting to the user with a button to go directly to the WP-Admin page.

At first I thought perhaps core WooCommerce might have this through an endpoint, so I checked but it looks like `wp-json/wc/v3/system_status` doesn't return any wp-admin URLs either. Might be a good idea for core to add that URL to that endpoint.

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift (hunk 1 above)
Comment (allendav) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift:1]: I think it's awesome, since it will be one fewer modal to maintain, but I leave it up to you to decide if you'd like to do that.

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+        cancelSearchAction()
+    }
+
+    func didTapAuxiliaryButton(in viewController: UIViewController?) { }
+}
+
+private extension CardPresentModalConnectingFailedUpdatePostalCode {
+    enum Localization {
+        static let title = NSLocalizedString(
+            "Please update your postal code",
```
Comment (allendav) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift]: Suggestion: "Please correct your store's postcode/ZIP"

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+            comment: "Title of the alert presented when the user tries to connect to a specific card reader and it fails " +
+            "due to postal code problems"
+        )
+
+        static let subtitle = NSLocalizedString(
+            "You can set it in your site's admin pages on the web",
```
Comment (allendav) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift]: Suggestion: "You can set your store's postcode/ZIP in wp-admin > WooCommerce > Settings (General)."

**Review by allendav — APPROVED** [review]
Tests fine. Some wording suggestions to make finding the setting in wp-admin easier and to match WooCommerce core terminology. :shipit: 

IMG_0266

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalConnectingFailedUpdatePostalCode.swift:1]: We agreed on a call that due to future plans, it would be clearer not to merge these.

**Comment by joshheald** [comment]
> Tests fine. Some wording suggestions to make finding the setting in wp-admin easier and to match WooCommerce core terminology. :shipit:

Wording suggestions done, thanks for those 😊 
I've also added this to #5591 as we discussed, to check this during onboarding, not just wait for card reader connection.
