### PR TITLE
[Mobile Payments] Speculative implementation of non-retryable refund error

### LINKED ISSUE #6658: [Mobile Payments] Show non-retryable error alert on Interac refund failure if an error is not retryable
Android have this implemented already, it's done in the app. [Stripe have a bit of guidance](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)processRefund)...

> When processRefund fails, the SDK returns an error that either includes the failed [SCPRefund](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPRefund.html) or the [SCPRefundParameters](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPRefundParameters.html) that led to a failure. Your app should inspect the [SCPProcessRefundError](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPProcessRefundError.html) to decide how to proceed.
> 
> If the refund property is nil, the request to Stripe’s servers timed out and the refund’s status is unknown. We recommend that you retry processRefund with the original [SCPRefundParameters](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPRefundParameters.html).
> 
> If the [SCPProcessRefundError](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPProcessRefundError.html) has a failure_reason, the refund was declined. We recommend that you take action based on the decline code you received.

... but it's not exactly definite about which ones are retryable!

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/6654#discussion_r851166397_

[From Android](https://github.com/woocommerce/woocommerce-android/blob/45ce7d3a565c7e9d2da3b84a4af7057853f0038f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/payment/CardReaderPaymentViewState.kt#L208), I've found that the following errors are mapped as non-retryable. Strings are [Stripe Decline Codes](https://stripe.com/docs/declines/codes)

```
object AmountTooSmall : Declined(R.string.card_reader_payment_failed_amount_too_small), NonRetryableError
"amount_too_small"

object Fraud : Declined(R.string.card_reader_interac_refund_refund_failed_fraud), NonRetryableError
"call_issuer",
"card_velocity_exceeded",
"do_not_honor",
"do_not_try_again",
"fraudulent",
"lost_card",
"merchant_blacklist",
"pickup_card",
"restricted_card",
"revocation_of_all_authorizations",
"revocation_of_authorization",
"security_violation",
"stolen_card",
"stop_payment_order"

object InvalidAccount : Declined(R.string.card_reader_payment_failed_invalid_account), NonRetryableError
"invalid_account",
"new_account_information_available"

object CurrencyNotSupported : Declined(R.string.card_reader_payment_failed_currency_not_supported), NonRetryableError
"currency_not_supported"

object DuplicateTransaction : Declined(R.string.card_reader_interac_refund_refund_failed_duplicate_transaction), NonRetryableError
"duplicate_transaction"

object IncorrectPostalCode : Declined(R.string.card_reader_payment_failed_incorrect_postal_code), NonRetryableError
"incorrect_zip"

object InvalidAmount : Declined(R.string.card_reader_interac_refund_refund_failed_invalid_amount), NonRetryableError
"invalid_amount"
```

We'll implement these same codes as non-retryable from Interac refund failures.

### PR DESCRIPTION
**Pull request by joshheald**
Relates to: #6658

### Description

I've not been able to test this at all, because the test amounts from Stripe don't return what we need. I've tried with amounts ending in .01, .05, .55, .65, .75, and all of them have a `refund`, but none have a `failureReason`. This means that all the failures go down the non-retryable path at the moment.

This matches the [logic which Stripe suggest](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)processRefund), combined with the decline reasons that Android’s implementation mark as non-retryable. I have also added some other decline reasons to our non-retryable list, because they did not appear to make sense for retries. Namely:
`.cardNotSupported`
`.expiredCard`

`Amount too small` is not available in our enum, so not covered here.

### Screenshots

N.B. the non-retryable error is not refund specific yet:
non retryable refund error

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by joshheald** [comment]
@jaclync ... I'd hoped to get this done today, but if it's helpful for you, it's here. Sorry to hand it over half-finished!

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift [hunk 1]
```diff
@@ -291,15 +291,21 @@ private extension RefundSubmissionUseCase {
...
-                // Regardless of whether the refund could be cancelled (e.g. it completed but failed), retry the refund.
-                self?.attemptCardPresentRefund(refundAmount: refundAmount, charge: charge, onCompletion: onCompletion)
-            }
-        }, dismissCompletion: {
-            onCompletion(.failure(error))
-        })
+        if let cardReaderError = error as? CardReaderServiceError,
+           case .refundPayment(_, let shouldRetry) = cardReaderError,
+           shouldRetry == false {
+            alerts.nonRetryableError(from: self.rootViewController, error: error)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift]: I think we'd want to call `onCompletion` after dismissing the alert on this code path, which requires some changes to `CardPresentModalNonRetryableError`

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 2]
```diff
@@ -516,29 +517,41 @@ extension StripeCardReaderService {
...
-                    promise(.failure(CardReaderServiceError.refundPayment(underlyingError: UnderlyingError(with: error))))
+                    promise(.failure(CardReaderServiceError.refundPayment(
+                        underlyingError: UnderlyingError(with: error),
+                        shouldRetry: true
+                    )))
                 } else {
                     // Process refund
-                    Terminal.shared.processRefund { processedRefund, processError in
-                        self?.refundCancellable = nil
+                    Terminal.shared.processRefund { [weak self] processedRefund, processError in
```
Comment (jaclync) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift:527]: good catch on using weak self in the completion block 👍

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 3]
```diff
@@ -547,6 +560,52 @@ extension StripeCardReaderService {
...
+    /// Implements refund retry logic as recommended by Stripe
+    /// https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)processRefund
+    /// > When `processRefund` fails, the SDK returns an error that either includes the failed `SCPRefund` or the `SCPRefundParameters` that led to a failure.
+    /// > Your app should inspect the `SCPProcessRefundError` to decide how to proceed.
+    /// >
+    /// > If the `refund` property is nil, the request to Stripe’s servers timed out and the refund’s status is unknown.
+    /// > We recommend that you retry processRefund with the original `SCPRefundParameters`.
+    /// >
+    /// > If the `SCPProcessRefundError` has a `failure_reason`, the refund was declined.
+    /// > We recommend that you take action based on the decline code you received.
```
Comment (jaclync) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift:570]: nice context for future readers!

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift [hunk 4]
```diff
@@ -547,6 +560,52 @@ extension StripeCardReaderService {
...
+        guard let failureReason = failureReason else {
+            return false
+        }
+        switch DeclineReason(with: failureReason) {
+        case .fraud,
+                .invalidAccount,
+                .currencyNotSupported,
+                .cardNotSupported,
+                .duplicateTransaction,
+                .expiredCard,
```
Comment (jaclync) [inline Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift]: this decline reason is considered as retryable [in Android](https://github.com/woocommerce/woocommerce-android/blob/567742faae9786e774f419e02f48d171bdaba97c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/payment/CardReaderPaymentViewState.kt#L138) (also confirmed again with Android in p1650533500277319/1650028971.895919-slack-C025A8VV728), do we want to follow? I think it makes sense for this to be retryable, because the customer can try using a different card (this happened to me once when I used to still keep the expired card 😅 )

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift [hunk 5]
```diff
@@ -291,15 +291,21 @@ private extension RefundSubmissionUseCase {
         DDLogError("Failed to refund: \(error.localizedDescription)")
         // Informs about the error.
         //TODO: Check which refund errors can't be retried, and use that to call nonRetryableError(from: self.rootViewController, error: cancelError)
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift]: nit: maybe we can remove this TODO in this PR?

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift (hunk 1 above)
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift]: nit:

```suggestion
            alerts.nonRetryableError(from: rootViewController, error: error)
```

**Review by jaclync — COMMENTED** [review]
Nice work @joshheald! I also wasn't able to see the failure reason from the Stripe refund, and `SCPProcessRefundError.requestError` isn't helpful either. I'm not sure if it's because our Stripe account is in test mode, so far I don't see a conclusion in this conversation p1647343856332389-slack-C01G168NFC2.

I mostly had a request for the completion path in `alerts.nonRetryableError`, other than that just minor comments! Some unit tests might also be nice 🙂

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift (hunk 1 above)
Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift]: Great 👍 I implemented that on https://github.com/woocommerce/woocommerce-ios/pull/6659/commits/3375d971a29263eceb7f19bb1ddfe087e8157a29 and https://github.com/woocommerce/woocommerce-ios/pull/6659/commits/280429b4b850d88c152f99eafe2fe9abba106e96

Please also notice that I modified CollectOrderPaymentUseCase.swift [here](https://github.com/woocommerce/woocommerce-ios/blob/280429b4b850d88c152f99eafe2fe9abba106e96/WooCommerce/Classes/ViewRelated/Orders/Collect%20Payments/CollectOrderPaymentUseCase.swift#L291) to call completion when the alert is dismissed, please let me know if this is not correct. :)

File: WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift (hunk 5 above)
Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Orders/Refund/RefundSubmissionUseCase.swift]: Yeah, removed ✅

File: Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift (hunk 4 above)
Comment (toupper) [reply Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift]: Ah yes, that's true, I moved that case to the "retryable" ones, and also .`cardNotSupported ` for the same reasons. See more about it here pdfdoF-GB-p2

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift [hunk 6]
```diff
@@ -40,13 +43,15 @@ final class CardPresentModalNonRetryableError: CardPresentPaymentsModalViewModel
         return topTitle + bottomTitle
     }
 
-    init(amount: String, error: Error) {
+    init(amount: String, error: Error, onDismission: @escaping () -> Void) {
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift]: nit: maybe `onDismiss` to be consistent with other simialr cases in the codebase?
```suggestion
    init(amount: String, error: Error, onDismiss: @escaping () -> Void) {
```

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift [hunk 7]
```diff
@@ -40,13 +43,15 @@ final class CardPresentModalNonRetryableError: CardPresentPaymentsModalViewModel
...
         self.amount = amount
         self.error = error
+        self.onDismission = onDismission
     }
 
     func didTapPrimaryButton(in viewController: UIViewController?) {
         viewController?.dismiss(animated: true)
+        onDismission()
```
Comment (jaclync) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift]: nit: maybe this can be called after `viewController?.dismiss` completes in the completion block (default to be `nil`)?

**Review by jaclync — APPROVED** [review]
LGTM 🚢 Just very minor non-blocking nits for your consideration!

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift (hunk 6 above)
Comment (toupper) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift]: Great point! changed in https://github.com/woocommerce/woocommerce-ios/pull/6659/commits/d19046d5684dc3f783a1f83854a62d513cb4992d :)

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift (hunk 7 above)
Comment (toupper) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalNonRetryableError.swift]: That makes more sense indeed, changed in https://github.com/woocommerce/woocommerce-ios/pull/6659/commits/79c975d9df2f7896a4880575d1cabc53e1a19c3b 🚀

**Review by jaclync — APPROVED** [review]
Thanks for the updates! LGTM :shipit:
