### PR TITLE
Attempt mitigate tablet crash when `highlightSelectedRowIfNeeded`

### LINKED ISSUE #12374: EXC_BAD_ACCESS: Exception 1, Code 2, Subcode 6095503072 >
Sentry Issue: [WOOCOMMERCE-IOS-1MFX](https://a8c.sentry.io/issues/4970844566/?referrer=github_integration)

```
EXC_BAD_ACCESS: Exception 1, Code 2, Subcode 6095503072 >
Stack overflow in (null)
  File "NSOrderedSet+Array.swift", line 5, in NSOrderedSet.toArray<T>
  File "Order+ReadOnlyConvertible.swift", line 166, in Order.orderItemsArray.getter
  File "Order+ReadOnlyConvertible.swift", line 74, in Order.toReadOnly
  File "<compiler-generated>", in Order
  File "FetchResultSnapshotsProvider.swift", line 175, in FetchResultSnapshotsProvider.object
...
(103 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #12374

## Description

This PR attempts to mitigate a crash we've seen on tablets and described on peaMlT-vd-p2. When tapping in Orders, there seems to be a crash in some instances when the system attempts to highlight the appropriate row for the selected order.

> An initial look seems to be from converting Storage.Order (NSManagedObject)’s items: NSOrderedSet of type Storage.OrderItem to a Swift array. Something went wrong in the conversion from NSOrderedSet‘s Objective-C element to the read-only Swift version.

Since I couldn't replicate it, my initial approach to this is to be more strict around the type conversion, and to move the `highlightSelectedRowIfNeeded` method to be called only when needed. Any input or feedback is welcome.

## Changes:
1. Moved `highlightSelectedRowIfNeeded()` from `willDisplay` to `viewDidAppear`

While this delegate allows us to customize the cell before it is displayed and highlight if its needed, we're calling this method multiple times when is not necessary (eg: when scrolling). We only need one check when the view is loaded, and further checks will happen when the different rows are selected. 

Additionally, internally `highlightSelectedRowIfNeeded` is reaching to storage to calculate the index path each time this delegate was called, which could be causing concurrency issues if we're accessing to the NSOrderedSet from multiple threads or there's some sort of index path miss-match since cells should've been reorganized.

```
EXC_BAD_ACCESS: Exception 1, Code 2, Subcode 6095503072 >
Stack overflow in (null)
  File "NSOrderedSet+Array.swift", line 5, in NSOrderedSet.toArray<T>
  File "Order+ReadOnlyConvertible.swift", line 166, in Order.orderItemsArray.getter
  File "Order+ReadOnlyConvertible.swift", line 74, in Order.toReadOnly
  File "<compiler-generated>", in Order
  File "FetchResultSnapshotsProvider.swift", line 175, in FetchResultSnapshotsProvider.object
...
(103 additional frame(s) were not displayed)
```

2. Added a `toTypeCheckedArray` method

Despite using optional casting during type conversion, we've seen some logs pointing to force casting and bridging issues between types. Eg:
```
Array._unconditionallyBridgeFromObjectiveC, 
_arrayForceCast<T>
```

This is a copy of `.toArray()` with additional safeguards by being stricter catching type-cast errors, since we're checking each element rather than the entire array level, and provides feedback about why the cast failed via the `assert`. If any of the elements cannot be casted we'll just return an empty array in production.

3. Updates `orderItemsArray` nil-coalescing fallback type to be explicit

When the read-only convertible implementation fails to convert  to a Swift array, we fallback to an empty array `[]` which will be type-inferred automatically. There shouldn't be any difference between being explicit or not, but since we've seen from the logs that there might be errors when casting/converting between types, we can be explicit here and just tell the compiler and the next person that we're expecting an empty `[Storage.OrderItem]`

## Testing instructions
I wasn't able to replicate the issue on peaMlT-vd-p2 . My attempts to load a site with a large number of orders that hasn’t been synchronised for a while seems to just make the selected row to jump "out of the view" when the rest of cells are updated, but there's no crash.

Run the app on tablet, go to Orders, and test that the selected row works as expected on selection, deselection, moving between views and playing with the split view configuration.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift [hunk 1]
```diff
@@ -8,3 +8,20 @@ extension NSOrderedSet {
         return array
     }
 }
+
+/// Explicitely checks the type for each generic element that will be converted from NSOrderedSet to a Swift array.
+/// Crash and log the error in debug builds if there's a miss-match
```
Comment (jaclync) [inline Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift]: super nit:
```suggestion
/// Explicitly checks the type for each generic element that will be converted from NSOrderedSet to a Swift array.
/// Crash and log the error in debug builds if there's a mismatch
```

File: Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift [hunk 2]
```diff
@@ -8,3 +8,20 @@ extension NSOrderedSet {
...
+extension NSOrderedSet {
+    func toTypeCheckedArray<T>() -> [T] {
+        var typeCheckedArray = [T]()
+
+        for element in self {
+            guard let typeCheckedElement = element as? T else {
+                assert(false, "Failed conversion. \(element) is not of type \(T.self)")
```
Comment (jaclync) [inline Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift]: For crashing in debug builds on a developer error, I think `assertionFailure` is used more widely in the code base

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift [hunk 3]
```diff
@@ -823,9 +829,6 @@ extension OrderListViewController: UITableViewDelegate {
         }
 
         syncingCoordinator.ensureNextPageIsSynchronized(lastVisibleIndex: itemIndex)
-        if indexPath == selectedIndexPath {
-            highlightSelectedRowIfNeeded()
-        }
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift:828]: this move makes sense to me. Just to make sure there are no other reasons for the highlight logic here, double checking with @joshheald.

**Review by jaclync — APPROVED** [review]
Tested well on my end, let's give it a try! :shipit:

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift (hunk 3 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift:828]: The highlighting code is pretty patchy and complicated now, so I can't say for sure. I was poking at it a bit yesterday while investigating another crash.

This particular call is one of the older ones, and predates our tablet work. I don't know the reason it was added, but it came from [this commit](https://github.com/woocommerce/woocommerce-ios/commit/cb8c5b2), and looks like an effort in the HACK week to simplify the highlighting. We have since had to add other calls back to this elsewhere, so perhaps this one isn't needed any more.

If it were the only call, I can see that it might have made sense to do the highlighting right before the cell was displayed... but it's probably fine to remove now.

Did anyone check the deeplink highlighting behaviour?

Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift:828]: > Did anyone check the deeplink highlighting behaviour?

I did test those with both on-screen and out-of-screen order deeplinks and the rows are highlighted correctly (out-of-screen still doesn't scroll automatically as https://github.com/woocommerce/woocommerce-ios/issues/11789)

File: Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift (hunk 1 above)
Comment (iamgabrielma) [reply Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift]: Thanks! https://github.com/woocommerce/woocommerce-ios/pull/12587/commits/18ce47b61af7cc35541aa2330649d3d5b743e1d0

File: Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift (hunk 2 above)
Comment (iamgabrielma) [reply Yosemite/Yosemite/Internal/NSOrderedSet+Array.swift]: It seems the only difference is the interface offering a boolean option, or having `false` baked-in. But sounds good since the naming is more explicit. Updated on https://github.com/woocommerce/woocommerce-ios/pull/12587/commits/51a36b9302b9ea3a5271962723bc820434c6140e
