### PR TITLE
[Payments] Do not display error modal when merchant cancels reader connection

### LINKED ISSUE #11209: [Payments] Suppress error modal when cancelling from reader discovery or connection
From review: https://github.com/woocommerce/woocommerce-ios/pull/11080#issuecomment-1814109340
>  Cancelling from discovery shows a "System unexpectedly cancelled" error – this should be suppressed.

After further testing, this currently happens in trunk as well. Both when cancelling discovering readers, as well as after discovery, when we cancel the flow after we successfully found -but not connected yet- to a reader.

This seem to happen due `CardReaderConnectionController` state switch after cancelling, the error is captured during the flow since the completion passed to `searchAndConnect` will be called with a `failure` result, which triggers the `onDiscoveryFailed` state, this then will present the modal with the error message.

https://github.com/woocommerce/woocommerce-ios/assets/2472348/d351ccbb-24a8-4dbf-9465-b0760097be7d

### PR DESCRIPTION
**Pull request by iamgabrielma**
Merge after #11080 
Closes: #11209

## Description
This PR suppresses "System unexpectedly cancelled" error presented via a modal view to a merchant, when the card reader discovery or connection process is manually cancelled by taping the "cancel" button.

The "System unexpectedly cancelled" modal view would appear because the `ControllerState` state would change to be `.cancel` state after a merchant taps the cancel button. This would trigger an error within reader search, which is intercepted in the `onError` completion handler. This switched the `ControllerState` to `discoveryFailed(_)` immediately, which triggers `CardReaderConnectionController.onDiscoveryFailed` that presents the error in a modal to the merchant.

## Changes
We add additional logic when an error during reader search is captured, if there's an error but we're in the `.cancel` state:
* Track a `card_reader_connection_failed` error, rather than `card_reader_discovery_failed`, since discovery either has not completed when cancelled, or was completed but ultimately not connected the candidate reader.
* Pass and track `.connectionError` as the `CancellationSource`. While we're already in the `.cancel` state at this point, the error captured is unknown, so we declare it explicitly.

## Testing instructions
1. With a disconnected reader
2. Go to Menu > Payments > Manage card reader > Tap Connect Card Reader > Tap cancel before the discovery finishes
3. Observe no "System unexpectedly cancelled" error are shown
4. Repeat the discovery until a candidate reader is found, you'll see the "Do you want to connect to reader XYZ" screen
5. Tap the cancel button
6. Observe no "System unexpectedly cancelled" error are shown

2023-11-21 at 12 47 12 supress cancel error

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift [hunk 1]
```diff
@@ -376,8 +376,13 @@ private extension CardReaderConnectionController {
             onError: { [weak self] error in
                 guard let self = self else { return }
 
-                self.analyticsTracker.discoveryFailed(error: error)
-                self.state = .discoveryFailed(error)
+                if case .cancel = self.state {
+                    self.analyticsTracker.connectionFailed(error: error, cardReaderModel: self.candidateReader?.readerType.model)
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: I don't understand why we track `connectionFailed` here – it hasn't failed, the user cancelled it.

When connecting in the payments flow, we also track `card_present_collect_payment_canceled`, which is currently being tracked twice for a cancellation (I'm sure that's unrelated to this change. That's not tracked in the `Manage Card Reader` flow though.

**Review by joshheald — COMMENTED** [review]
This works.... but I don't think it's the right fix neccesarily.

Previous to the 3.0 SDK, cancelling discovery returned a `nil` error, and we used a guard to avoid sending an error out of the StripeCardReaderService. [They documented a change for 3.0 saying they would end with an "error" for cancellation](https://stripe.com/docs/terminal/references/sdk-migration-guide#update-your-discoverreaders-and-connectreader-usage)

You can see it at the breakpoint in this image, [which shows part of StripeCardReaderService](https://github.com/woocommerce/woocommerce-ios/blob/50e1091dc6a7e82244311790e088123b6cb83d9f/Hardware/Hardware/CardReader/StripeCardReader/StripeCardReaderService.swift#L173):
CleanShot 2023-11-22 at 10 22 39@2x

I suspect a better fix would be to fall into the guard for `SCPErrorCanceled` as well as nil errors, and updating the comment. That would have the advantage of applying the fix to anything which uses the `cancelCardReaderDiscovery` action and `StripeCardReaderService`. Right now, that is _really_ only the `CardReaderConnectionController`, but it makes the interface of the card reader service more... sensible. We shouldn't really propagate errors for cancellation, unless we failed to cancel, in my view. (`BuiltInCardReaderConnectionController` has it too, but I think it's copy-pasta and not actually called...) 

WDYT?

File: WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: I added the `connectionFailed` event it seemed the closest fit from existing track events to the manual disconnection:
```
Tracked when connecting to a card reader fails
```
 Up until now was being tracked as `discoveryFailed`, which doesn't seem to fit either. Would you say we should add a new event to track the cancellation tap, or it's not worth it? We do in some other places, like `cardReaderSoftwareUpdateCancelTapped`

**Comment by iamgabrielma** [comment]
> I suspect a better fix would be to fall into the guard for SCPErrorCanceled as well as nil errors, and updating the comment. That would have the advantage of applying the fix to anything which uses the cancelCardReaderDiscovery action and StripeCardReaderService. Right now, that is really only the CardReaderConnectionController, but it makes the interface of the card reader service more... sensible. We shouldn't really propagate errors for cancellation, unless we failed to cancel, in my view. (BuiltInCardReaderConnectionController has it too, but I think it's copy-pasta and not actually called...)

I'm not quite sure what do you mean 😅, could you confirm if this is what you meant?

From the comment, I understand that while the callback of `Terminal.shared.discoverReaders` continues to be of type `Error?`, we don't expect a `nil` value when this is cancelled by the user, as now it will return a proper error. That said, we still have to account for possible `nil` so we guard against both. Also the error handling would remain in the service, and wouldn't require that we re-implement or remember to do things on a certain way in each concrete implementation (`CardReaderConnectionController`, ... )

I changed the implementation to the following (not committed yet) and works as expected, however I'm not sure if we should also capture the `nil` value with some sort of NSError, since with this, we wouldn't. What do you think?

```
        discoveryCancellable = Terminal.shared.discoverReaders(config, delegate: self, completion: { [weak self] receivedError in
            guard receivedError == nil else {
                self?.switchStatusToIdle()
                return
            }

            guard let error = receivedError else {
                self?.switchStatusToIdle()
                return
            }

            self?.switchStatusToFault(error: error)
        })
```

There's also some inconsistency on Stripe docs, or I'm miss-reading it. I believe the second one is outdated.
* In https://stripe.com/docs/terminal/references/sdk-migration-guide#update-your-discoverreaders-and-connectreader-usage
> Canceling discoverReaders now calls the completion block with an error with code SCPErrorCanceled, just like all other cancellable methods.
* In https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)discoverReaders:delegate:completion:
> If discoverReaders is canceled, the completion block will be called with nil (rather than an SCPErrorCanceled error).

File: WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift]: Reverted with https://github.com/woocommerce/woocommerce-ios/pull/11230/commits/9c5fbcb1135ddf2a50d7006a2e7f828135bb681c, since we're leaving this class as was initially.

**Comment by iamgabrielma** [comment]
> I suspect a better fix would be to fall into the guard for SCPErrorCanceled as well as nil errors, and updating the comment. That would have the advantage of applying the fix to anything which uses the cancelCardReaderDiscovery action and StripeCardReaderService

Updated on https://github.com/woocommerce/woocommerce-ios/pull/11230/commits/9c5fbcb1135ddf2a50d7006a2e7f828135bb681c, this is ready for re-review when you have the chance 🙇

**Comment by joshheald** [comment]
> I'm not quite sure what do you mean 😅, could you confirm if this is what you meant?

Sorry, both for lack of clarity and for not noticing this comment! Happy to elaborate.

> From the comment, I understand that while the callback of `Terminal.shared.discoverReaders` continues to be of type `Error?`, we don't expect a `nil` value when this is cancelled by the user, as now it will return a proper error. That said, we still have to account for possible `nil` so we guard against both. Also the error handling would remain in the service, and wouldn't require that we re-implement or remember to do things on a certain way in each concrete implementation (`CardReaderConnectionController`, ... )

Yes, that's what I was trying to get across 😊 

> I changed the implementation to the following (not committed yet) and works as expected, [...]

> ```
>         discoveryCancellable = Terminal.shared.discoverReaders(config, delegate: self, completion: { [weak self] receivedError in
>             guard receivedError == nil else {
>                 self?.switchStatusToIdle()
>                 return
>             }
> 
>             guard let error = receivedError else {
>                 self?.switchStatusToIdle()
>                 return
>             }
> 
>             self?.switchStatusToFault(error: error)
>         })
> ```

Not quite what I meant – I meant that you should make the previous `guard` statement fail (i.e. call its `else` block) for both `nil` and `SCPErrorCanceled` errors, i.e. 

```
        discoveryCancellable = Terminal.shared.discoverReaders(config, delegate: self, completion: { [weak self] receivedError in
            guard let error = receivedError else {
                self?.switchStatusToIdle()
                return
            }

            let nsError = error as NSError
            guard nsError.code != ErrorCode.Code.canceled.rawValue else {
                self?.switchStatusToIdle()
                return
            }

            self?.switchStatusToFault(error: error)
```

I had thought it would be possible to do this in one guard, but it's not, because you need to make it an `NSError` to check the code. That might be acceptable, but it would need testing. Casting from Error to NSError always succeeds, but there might be some effects in the caller if it starts getting NSError versions of Swift errors for some reason? I think that's very unlikely though.

> [...] however I'm not sure if we should also capture the `nil` value with some sort of NSError, since with this, we wouldn't. What do you think?

I think that's a good suggestion and would be worth doing; `nil` doesn't mean `cancel` any more, so it should be sent up to the caller as an error to display to the user and track. Doing that definitely requires two guards, as the else blocks will be different anyway


> There's also some inconsistency on Stripe docs, or I'm miss-reading it. I believe the second one is outdated.
> 
> * In https://stripe.com/docs/terminal/references/sdk-migration-guide#update-your-discoverreaders-and-connectreader-usage
> 
> > Canceling discoverReaders now calls the completion block with an error with code SCPErrorCanceled, just like all other cancellable methods.
> 
> * In https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)discoverReaders:delegate:completion:
> 
> > If discoverReaders is canceled, the completion block will be called with nil (rather than an SCPErrorCanceled error).

Yeah, I agree there's inconsistency and the second one is outdated. Perhaps you could let Stripe know?


Hope that helps, give me a shout if you want to pair on it or anything.

**Comment by iamgabrielma** [comment]
Thanks for your help with this @joshheald , as we saw during the pairing session the changes proposed with the https://github.com/woocommerce/woocommerce-ios/pull/11230/commits/05a0e0dfd15f92e6c430fc34777750394c1ce829 makes the user experience better, as well as the code slightly more readable. 

I haven't changed anything additional since our call, so feel free to approve it as it is when you have the chance 🙇

**Review by joshheald — APPROVED** [review]
