### PR TITLE
Remove `defaultStoreURL` from `SessionManager`

### LINKED ISSUE #11076: Session Manager: `defaultStoreURL` is incorrect
Previously we added `defaultStoreURL` to `SessionManager` as part of the effort to support REST API. `defaultStoreURL` is [retrieved](https://github.com/woocommerce/woocommerce-ios/blob/c3918db86165e96ca63e78b15daa5570371413d6/WooCommerce/Classes/System/SessionManager.swift#L100-L107) from credentials, which is valid for users authenticated without WPCom, but incorrect otherwise, especially when they have multiple stores.

We should update `defaultStoreURL` to reflect the URL in [defaultSite](https://github.com/woocommerce/woocommerce-ios/blob/c3918db86165e96ca63e78b15daa5570371413d6/WooCommerce/Classes/System/SessionManager.swift#L151) instead (at least when the logged-in credentials is WPCom).

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #11076 

## What

This PR removes the redundant and misleading `defaultStoreURL` from `SessionManager`.

## Why
This property is only used when restoring session for users logging in without WPCom. It can be replaced with a simple check with the credentials. This check doesn't work if the logged in credentials are WPCom because multiple sites are supported and the credentials are not updated when the default site is switched.

## How
- Removed `defaultStoreURL` from `SessionManagerProtocol` and `SessionManager`.
- Replaced the use of `defaultStoreURL` (because #11074 has yet to be merge back to trunk).
- Replace the use of `defaultStoreURL` in `DefaultStoresManager` by checking directly with credentials.

## Testing instructions

- Log in with a self-hosted site without Jetpack.
- Confirm that all logged-in features are still working properly.

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hafizrahman — APPROVED** [review]
Looks good to me! Works fine in my test as well.

File: Yosemite/Yosemite/Base/SessionManagerProtocol.swift [hunk 1]
```diff
@@ -23,10 +23,6 @@ public protocol SessionManagerProtocol {
     ///
     var defaultStoreID: Int64? { get set }
 
-    /// URL of default store
-    ///
-    var defaultStoreURL: String? { get }
```
Comment (selanthiraiyan) [inline Yosemite/Yosemite/Base/SessionManagerProtocol.swift:28]: I think we can also remove [this](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Settings/Credentials.swift#L43C17-L43C42) `Credentials.hasPlaceholderSiteAddress()` method, which isn't used anywhere now.

Comment (itsmeichigo) [reply Yosemite/Yosemite/Base/SessionManagerProtocol.swift:28]: Good point - removed in 97d8cd3d78aa9357ae22f64470794e4564974238.
