### PR TITLE
Fix Notice View when navigating to a view without tab bar

### LINKED ISSUE #8224: [Payments] - Order Completed toast moves to the top of screen when user move to a different screen
**Describe the bug**
After completing a simple payment, the Order Created toast is displayed briefly on the bottom of the screen, but if the user navigates to a different screen when it's displayed, the toast moves top the top blocking the back button on the new screen.

**To Reproduce**
1. Go to Payments
2. Complete a simple payment
3. Return to In-Person Payments screen
4. When the `Order Completed` toast is displayed, click on `Manage card reader`
5. See that toast is not at the top of the screen

**Screenshots**

https://user-images.githubusercontent.com/17252150/203953891-431551aa-e2bf-4d5c-9967-b0beda56ecd4.MP4

**Expected behavior**
Toast should be displayed on the bottom of the screen

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.7.1
- WooCommerce iOS version: 11.2 and 11.3

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by toupper**
Closes: #8224 

### Description

Here we fix a misplacement of the notice (the one that shows the _Order Created!_ message) when navigating to a view without the tab bar. The reason behind this is that we **constrain the notice container's bottom to the tab bar's top**. Because of this, when we the **tab bar is removed**, the notice loses its bottom anchor, resulting in the view moving to the top of the screen.

In the scenario described in this issue, we navigate to the Manage Card Readers view with the notice on the screen, the tab bar is then removed, and the notice -without a bottom constraint to follow- is moved to the upper part of the screen, hiding the back button.

To fix it I consider a few approaches:
* Leave the tab bar in the Manage Card Readers screen. Discarded because it was a design reason to remove it.
* Add the notice to the selected controller of the tab bar. I discarded this option because the notice disappears if we change tabs.
* Instead of constraining to the tab bar, **constrain to the view's bottom, with the tab bar height as padding**. This makes it independent of the tab bar, without moving to the top when the tab bar disappears. ~~**This is my final choice**~~. I discarded it because it required updating the constraints when the device orientation changes, which is not safe as the views might not have common ancestors, thus crashing as @joshheald  explained [here](https://github.com/woocommerce/woocommerce-ios/pull/8263#issuecomment-1332424133)
* Listen to the tab bar visibility via KVO and update the constraints of the notice view. I discarded it because, as the tab bar is removed or recreated internally in the UITabBarController, we might try to add constraints to views without a common ancestor, thus crashing.
* Listen for the tab bar visibility via KVO and hide the container if the tab bar is hidden. This is not optimal UI-wise, as the notice will be moved on top for a while until the navigation animation stops and the tab bar is hidden. I opted for this however as:
      * It's safe (no messing with constraints, no crash)
      * It hides the notice asap, thus uncovering the back button
      * The root issue is complex and might require a major refactor of this class. The UI issue we have is an edge case and it's not worthy of further analysis.
In this case, we don't unhide the notice if the tab bar is unhidden because it would still show the notice on top.

### Testing instructions

1. Go to Payments
2. Create a Simple Payment with whatever payment method. The notice with _Order Created!_ should appear. You should be navigated back to the Payments Menu.
3. Go to Manage Card Reader. The notice goes up for a while but soon disappears.

### Before
https://user-images.githubusercontent.com/17252150/203953891-431551aa-e2bf-4d5c-9967-b0beda56ecd4.MP4

### After

Uploading Simulator Screen Recording - iPhone 14 - 2022-12-01 at 13.24.21.mp4…

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by joshheald** [comment]
I like your approach and broadly it works well. Thanks for looking at it so soon after it was raised!

I've not approved because I got this crash when testing:

```
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-11-30 16:14:40.706156+0000 WooCommerce[37605:15151793] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x282b324c0 "_TtC11WooCommerceP33_FFA5D4594163A533C445FD7D6757038419NoticeContainerView:0x10cc67310.bottom"> and <NSLayoutYAxisAnchor:0x282b08200 "UILayoutContainerView:0x10b77d220.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'
*** First throw call stack:
(0x1da732248 0x1d3af7a68 0x1f6c00cf0 0x1032770b8 0x103276b24 0x10327b1b9 0x1032771e5 0x10327b2f1 0x102f12cc5 0x102f12e15 0x1e495e2d1)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x282b324c0 "_TtC11WooCommerceP33_FFA5D4594163A533C445FD7D6757038419NoticeContainerView:0x10cc67310.bottom"> and <NSLayoutYAxisAnchor:0x282b08200 "UILayoutContainerView:0x10b77d220.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x282b324c0 "_TtC11WooCommerceP33_FFA5D4594163A533C445FD7D6757038419NoticeContainerView:0x10cc67310.bottom"> and <NSLayoutYAxisAnchor:0x282b08200 "UILayoutContainerView:0x10b77d220.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'
terminating with uncaught exception of type NSException
```

Repro:

1. Launch the app and go to the Manage card reader screen
2. On your computer, place an order on the store
3. Wait for the notice to show up on the app
4. Rotate the device several times (it seems to need to be more than once.)
5. The app will crash due to a constraint issue

This is pretty edge-casey, but it may also be possible to get this crash in other ways, so I think it's probably worth investigating.

Also, did you consider/investigate updating the constant when the tab bar is removed or added? It looks like we present the notice with that padding even when it's shown on a screen with no tab bar, which seems a little strange too. Not a big deal, I'm just wondering...

**Comment by jostnes** [comment]
I noticed a couple of things on the build:
1. After getting an order, I navigated to a few screens and left it on `Manage Card Reader` for a while. When I returned to it, the screen was frozen. When that happens, the user can't do anything on the screen (I had to kill the app to restart it) and this is seen on the logs (the logs look similar to what @joshheald reported above):
```
2022-12-01 13:35:59.088554+0800 WooCommerce[668:24123] 🔵 Tracked payments_hub_manage_card_readers_tapped, properties: [AnyHashable("blog_id"): 212435671, AnyHashable("is_wpcom_store"): true]
2022-12-01 13:35:59.845048+0800 WooCommerce[668:24549] <> Mapping Error: Dotcom Invalid REST Route
2022-12-01 13:35:59.846278+0800 WooCommerce[668:24334] ⛔️ Error synchronizing Stripe Account: Dotcom Invalid REST Route
2022-12-01 13:36:02.115768+0800 WooCommerce[668:23840] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x28082eb00 "_TtC11WooCommerceP33_FFA5D4594163A533C445FD7D6757038419NoticeContainerView:0x10d437e30.bottom"> and <NSLayoutYAxisAnchor:0x2808c6f40 "UILayoutContainerView:0x10b57c260.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'
*** First throw call stack:
(0x19aff91ec 0x1b3d2e744 0x1b402a8c8 0x104d2ee30 0x104d2e89c 0x104d32f31 0x104d2ef5d 0x104d33069 0x1049caa3d 0x1049cab8d 0x21c613081)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x28082eb00 "_TtC11WooCommerceP33_FFA5D4594163A533C445FD7D6757038419NoticeContainerView:0x10d437e30.bottom"> and <NSLayoutYAxisAnchor:0x2808c6f40 "UILayoutContainerView:0x10b57c260.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'
terminating with uncaught exception of type NSException
```
2. So based on the PR description, not having the tab bar on `Manage Card Reader` screen was a design decision. When a card reader is connected and the toast appears, I noticed that it looks like it's "floating" in the middle, unlike on other screens:

https://user-images.githubusercontent.com/17252150/204979038-a7d20d8c-0914-465f-bf72-947568e8596f.MP4

Is it okay that the toast position is like that in this particular case?

**Comment by toupper** [comment]
@joshheald @jostnes many thanks for your comments and suggestions. I found another approach based on them and described it in the description. Please take a look and let me know what you think. Thanks a lot!

File: WooCommerce/Classes/Tools/Notices/DefaultNoticePresenter.swift [hunk 1]
```diff
@@ -191,6 +193,7 @@ private extension DefaultNoticePresenter {
     func dismiss() {
         noticeOnScreen = nil
         keyboardFrameObserver = nil
+        kvoToken = nil
```
Comment (joshheald) [inline WooCommerce/Classes/Tools/Notices/DefaultNoticePresenter.swift:196]: Is this sufficient for removing the KVO subscription? It's been a long time since I've done it but I remember having to remove it at `dealloc` (in the old days) as well, perhaps adding it to `deinit` is also required?

Not sure. I can see it getting called even when the notice gets hidden, so perhaps it's fine.

**Review by joshheald — APPROVED** [review]
@toupper Thanks, this works and I can't make it crash any more. One question about ending the KVO observation.

This seems better than having the notice obscuring the back button, and I agree that it's pretty edge-casey so it's not worth spending a huge amount of time on.

I did notice this as well though: if you get a notice on a no-tab-bar screen, then go back to the tab bar, you still see the notice but obscured by the tab bar. Any thoughts on whether this is (efficiently) addressable?

https://user-images.githubusercontent.com/2472348/205096562-16a96c00-1916-462e-b1aa-d15da356fd1b.mp4

File: WooCommerce/Classes/Tools/Notices/DefaultNoticePresenter.swift (hunk 1 above)
Comment (toupper) [reply WooCommerce/Classes/Tools/Notices/DefaultNoticePresenter.swift:196]: Good question, from iOS 11 onwards we do not need to do that, as there's no penalty for letting the observer die before the observed or vice-versa. See [this doc](https://developer.apple.com/library/archive/releasenotes/Foundation/RN-Foundation/index.html) under Relaxed Key-Value Observing Unregistration Requirements for further details, or this [interesting discussion about it](https://stackoverflow.com/questions/46591637/in-swift-4-how-do-i-remove-a-block-based-kvo-observer).

**Comment by toupper** [comment]
> I did notice this as well though: if you get a notice on a no-tab-bar screen, then go back to the tab bar, you still see the notice but obscured by the tab bar. Any thoughts on whether this is (efficiently) addressable?

Nice point, I tried for a while to fix it but it is not an easy one due to the unpredictability of the tab bar behavior. The more I try the more convinced I am that we should rely on the tab bar neither for adding constraints nor for hiding/showing it. I will go and merge it now but I will keep it in mind to find a better solution. Thanks for your review!
