### PR TITLE
Set payment method and payment method title for Cash Orders

### LINKED ISSUE #12347: Cash Orders with empty Payment Method
**Describe the bug**
The mobile apps leave the `payment_method` and `payment_method_title` fields empty when the payment is collected in cash.

I checked the code, and the app updates only the status of the order to Completed, leaving the `payment_method` and `payment_method_title` fields empty.

**To Reproduce**
1. Create an order in the app
2. Open detail of the order
3. Tap on 'Collect Payment'
4. Select Cash
5. Confirm
6. Notice the order is marked as completed, but the payment_method and payment_method_title are empty (not visible on the UI in the app

**Screenshots**

**Expected behavior**

**Proposal**
When the user selects Cash on the Payment Selection screen, the apps should update:

- `status` to `completed`
- `payment_method` to `cod`
- `payment_method_title` to `Pay in Person` (This could get tricky, since this title is customizable – .../wp-admin/admin.php?page=wc-settings&tab=checkout&section=cod. However, AFAICT the end-customers won’t see this value. I believe setting it to Pay in Person should be a good enough MVP.)

### PR DESCRIPTION
**Pull request by staskus**
Closes: #12347
More context: pdfdoF-5ai-p2

## Description

When collecting cash payments through the app, the order status is marked as `complete` without setting the `payment_method` and `payment_method_title` as its done on the web.

Cash payment logic is initiated by `PaymentMethodViewModel` through `markOrderAsPaidByCash` method. At the moment, all it does to the order is update its status to completed.

### Solution

1. Use `updateOrder` instead of `updateOrderStatus` action that allows us to set modified `Order` object, and pass an array of fields that should be updated on the backend.
2. Use `PaymentGateway.Constants.cashOnDeliveryGatewayID` (`cod`) as `paymentMethodID`
3. Fetch Cash on Delivery (COD) payment gateway through `viewStorage.loadPaymentGateway`. If it doesn't exist, set a default "Pay in Person" title

## Testing information

1. Create an order in the app
6. Open detail of the order
7. Tap on 'Collect Payment'
8. Select Cash
9. Confirm
10. Confirm the order is marked as completed, and payment_method and payment_method_title are set. Payment method title can be visible in order details or receipts.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/4062343/1a4e01df-c8ae-4a53-93ab-1580429a36e5

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by staskus** [comment]
@iamgabrielma I still need to update UI test mocks to get the UI test to succeed. However, if you have time on Monday morning you can review the code and give some feedback, if not, we can do it once everything is completed, thanks! I'll also ask for further review from someone who worked on this part of the code.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by staskus** [comment]
@toupper I've seen you have made the last larger improvements to cash payments (https://github.com/woocommerce/woocommerce-ios/pull/11365). Let me know if you would have time to take a look at the solution, at least from a high-level. Thanks!

File: WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift [hunk 1]
```diff
@@ -338,13 +338,33 @@ private extension PaymentMethodsViewModel {
...
-                guard let error else {
-                    return continuation.resume(returning: ())
+        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
+            guard let order = ordersResultController.fetchedObjects.first else {
+                DDLogError("⛔️ Order not found, can't mark order as paid.")
+                continuation.resume(throwing: PaymentMethodsError.orderNotFound)
+                return
+            }
+
+            let cashOnDeliveryID = PaymentGateway.Constants.cashOnDeliveryGatewayID
```
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift:349]: I have my concerns hardcoding these title and payment gateway here. After all, this method is just marking the order as paid (complete); it doesn't have to be necessarily cash on delivery. I would change the function name to make it more explicit (e.g. `markOrderCompleteWithCashOnDelivery`), or pass the method id and title as parameters :)

Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift:349]: Good point. This method is only used for Cash Payments (Order -> Collect Payment -> Cash) flow, and is only called by a larger `markOrderAsPaidByCash` method. So I agree the naming is too broad and misleading. 👍

Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift:349]: Something like `completeCashPayment` or `completeCashOnDeliveryPayment` could reflect the functionality in a most appropriate way.

File: WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift [hunk 2]
```diff
@@ -338,13 +338,33 @@ private extension PaymentMethodsViewModel {
     ///
     @MainActor
     func markOrderAsPaid() async throws {
-        try await withCheckedThrowingContinuation { continuation in
-            stores.dispatch(OrderAction.updateOrderStatus(siteID: siteID, orderID: orderID, status: .completed) { error in
-                guard let error else {
-                    return continuation.resume(returning: ())
+        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
+            guard let order = ordersResultController.fetchedObjects.first else {
+                DDLogError("⛔️ Order not found, can't mark order as paid.")
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModel.swift]: Just for easier debugging, we could interpolate the orderID here:
```suggestion
                DDLogError("⛔️ Order \(orderID) not found, can't mark order as paid.")
```

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift [hunk 3]
```diff
@@ -135,18 +141,60 @@ final class PaymentMethodsViewModelTests: XCTestCase {
         await viewModel.markOrderAsPaidByCash(with: nil)
     }
 
+    func test_mark_order_as_paid_by_cash_then_order_status_and_payment_method_fields_updated() async {
+        // Given
+        let stores = MockStoresManager(sessionManager: .testingInstance)
+        let storage = MockStorageManager()
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift]: Not necessarily for this PR, but since we have 20+ instances of `MockStorageManager()`, `siteID`, and others, we could make some `setUp` and `tearDown` in this test suite so each unit test is clearer 👍

File: Networking/NetworkingTests/Remote/OrdersRemoteTests.swift [hunk 4]
```diff
@@ -462,6 +462,21 @@ final class OrdersRemoteTests: XCTestCase {
         assertEqual(received, expected)
     }
 
+    func test_update_order_when_payment_method_id_and_title_passed_then_request_parameters_set() throws {
```
Comment (iamgabrielma) [inline Networking/NetworkingTests/Remote/OrdersRemoteTests.swift:465]: Thanks for covering the `OrdersRemoteTests` accounting for the new properties! 💯

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift [hunk 5]
```diff
@@ -135,18 +141,60 @@ final class PaymentMethodsViewModelTests: XCTestCase {
...
+        let siteID: Int64 = 10
+        let orderID: Int64 = 123
+        let order = Order.fake().copy(siteID: siteID, orderID: orderID)
+        storage.insertSampleOrder(readOnlyOrder: order)
+        let paymentGateway = PaymentGateway.defaultPayInPersonGateway(siteID: siteID).copy(title: "Pay in Person")
+        storage.insertSamplePaymentGateway(readOnlyGateway: paymentGateway)
+        let dependencies = Dependencies(stores: stores, storage: storage)
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift:159]: I thought we wouldn't need to inject an instance of storage into the gateway dependencies for some cases, but that doesn't seem to be the case, if we do not specifically call `storage.insertSampleOrder(readOnlyOrder: .fake())` we'll see crashes in tests.

My understanding is this comes from the change from using `auto-draft` orders to `pending` orders, where auto-drafts are temporary and not meant to be stored, while pending orders are actual orders already started to be processed and should be stored. Does that sounds right?

If that's the case I think makes total sense for cash orders, but we should keep an eye to see if we've changed behaviour unintendedly where auto-drafts are used 👍

**Review by iamgabrielma — APPROVED** [review]
Works nicely! I've dropped a couple of comments and a question but nothing blocking, feel free to address them if you feel it's necessary or skip them 🙇 

LGTM! 🚢

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift (hunk 5 above)
Comment (staskus) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift:159]: We need to insert a sample order because we take an order from storage to pass to mody and then pass to `updateOrder` action. When we were using `updateOrderStatus`, we only needed orderID, so no order had to exist in the storage.

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift (hunk 3 above)
Comment (staskus) [reply WooCommerce/WooCommerceTests/ViewRelated/Orders/Payment Methods/PaymentMethodsViewModelTests.swift]: Good observation 👍 . Init and deinit of `MockStoresManager` and `MockStorageManage` can both be moved to setUp and tearDown. It's tougher with other parts of the tests since they differ slightly from one another.
