### PR TITLE
Shipping Labels: Handle error and empty states for carrier package screen

### LINKED ISSUE #14881: Load predefined packages fails
When loading the predefined packages in the purchase shipping label flow, we should display an error if the request fails.

Image

https://teameaglep2.wordpress.com/2025/01/15/revamp-shipping-labels-recovering-from-errors/

### LINKED ISSUE #15155: Empty predefined packages
When the list of predefined packages is empty, we should display an empty status

Image

### Design

[Figma](https://www.figma.com/design/bsLNrhmi2xQZB4C0TzjmHB/Shipping-Labels-Purchase-Flow?node-id=3155-3063&t=XTbYGXIFqOzOCoDE-0)

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #14881 
Also closes #15155 

## Description

This PR adds error and empty states for the carrier package screen. 

Additionally, packages are now loaded when the Add package screen is displayed instead of initially when the label creation form is displayed. This helps make catching errors easier.

## Steps to reproduce

Pre-requisite: add a breakpoint in Proxyman for responses of GET requests with `path=/wcshipping/v1/packages`.
- Log out of the app to clear cached data.
- Log back in to a store with Woo Shipping set up.
- Navigate to the Orders tab and select a completed order with a physical product.
- Select Create shipping label > Select a Package.
- When the Proxyman breakpoint pauses, update the response error code to be 400. Confirm that the error state is displayed in the Carrier tab.
- Tap Retry and update the response body to return an empty list of packages when the breakpoint pauses again.
- Confirm that the empty state is displayed in the Carrier tab.
- Select Create a custom package and confirm that the screen is switched to Custom tab.
- Quit proxyman or disable the breakpoint and open the package screen again.
- Confirm that the package list is displayed on the Carrier tab.

## Testing information

Tested on simulator iPhone 16 Pro iOS 18.2 and confirmed all the above test cases.

## Screenshots

Screen | Light mode | Dark mode
--- | --- | ---
Loading state |  | 
Error state |  | 
Empty state |  | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/239">21.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Yosemite/Yosemite/Stores/WooShippingStore.swift [hunk 1]
```diff
@@ -511,12 +511,3 @@ public enum WooShippingLabelPurchaseError: Error {
...
 }
-
-public enum WooShippingLoadPackagesError: Error, Equatable {
-    case loadingInProgress
-    case loadingFailed(error: Error)
-
-    public static func ==(lhs: WooShippingLoadPackagesError, rhs: WooShippingLoadPackagesError) -> Bool {
-        return lhs.localizedDescription == rhs.localizedDescription
-    }
-}
```
Comment (itsmeichigo) [inline Yosemite/Yosemite/Stores/WooShippingStore.swift:522]: Removed this as it seems redundant. `loadingInProgress` is irrelevant to the store.

**Review by selanthiraiyan — APPROVED** [review]
This looks great and works as described. 🚀
