### PR TITLE
Remove ghost animations when refreshing products, reviews and plugins

### LINKED ISSUE #2909: Product skeleton visible with pull to refresh
**Describe the bug**
When you pull to refresh on the products screen, the skeleton placeholder appears briefly until the data reloads.

**To Reproduce**
1. Switch to a store with at least one product.
2. Tap on the Products tab.
3. After they load, pull to refresh.
4. Notice the UI switches to the loading skeleton, then hops back to the loaded list.

**Screenshots**
RPReplay_Final1601580616 (1)

**Expected behavior**
I believe the skeleton is only supposed to show if loading/reloading from an empty table state.

**Mobile Environment**
Please include:
- Device: iPhone 11 Pro 
- iOS version: 14.0.1
- WooCommerce iOS version: 5.1

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #2909

### Description

It is expected that ghost animations are present only when first loading lists. Currently, we're showing this animation in product, review, and plugin lists even when refreshing content.

This PR cleans this up by removing the redundant animations on those screens.

### Testing instructions

Refresh product, reviews, and plugin lists after loading their contents. Notice that ghost animations are no longer present.

### Screenshots

Product list:
https://user-images.githubusercontent.com/5533851/156491620-c27e8acb-7906-4cfd-aff5-94a3af270728.mp4

Review list:
https://user-images.githubusercontent.com/5533851/156491664-86d9f296-2cdb-45c9-b226-d1340c1b1703.mp4

Plugin list:
https://user-images.githubusercontent.com/5533851/156491706-1baae17b-9911-415f-9a25-1e539f670268.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 1]
```diff
@@ -949,13 +949,13 @@ private extension ProductsViewController {
         case .noResultsPlaceholder:
             displayNoResultsOverlay()
         case .syncing(let pageNumber):
-            if pageNumber == SyncingCoordinator.Defaults.pageFirstIndex {
-                displayPlaceholderProducts()
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: I think we might want to keep showing this `displayPlaceholderProducts` when syncing the first page? otherwise, if there are no results before (like switching to a different store and going to the products tab) the products tab appears empty:

**Review by jaclync — APPROVED** [review]
LGTM, just a question about syncing the first page of the products tab!

Side note: now that the placeholder state isn't shown after pull-to-refresh on the products tab and because `ProductStore` deletes all products when syncing the first page, the empty state is briefly shown before the results. For example, the empty state appears for a split second toward the end of the [example screencast](https://user-images.githubusercontent.com/5533851/156491620-c27e8acb-7906-4cfd-aff5-94a3af270728.mp4). I think we can fix this by deleting all products in the same Core Data transaction as the upsert.

**Comment by itsmeichigo** [comment]
Thanks for the review @jaclync! I've added 2 commits to fix the issue with showing the placeholder when syncing products without previously fetched data and make sure that deletion and upsertion happen in the same context for products. This PR is ready for another review!

File: Yosemite/Yosemite/Stores/ProductStore.swift [hunk 2]
```diff
@@ -351,20 +348,18 @@ extension ProductStore {
...
-    /// Updates (OR Inserts) the specified ReadOnly Product Entities *in a background thread*. onCompletion will be called
-    /// on the main thread!
-    ///
-    func upsertStoredProductsInBackground(readOnlyProducts: [Networking.Product], onCompletion: @escaping () -> Void) {
+    func upsertStoredProductsInBackground(readOnlyProducts: [Networking.Product],
+                                          shouldDeleteExistingProducts: Bool = false,
+                                          onCompletion: @escaping () -> Void) {
         let derivedStorage = sharedDerivedStorage
         derivedStorage.perform {
+            if shouldDeleteExistingProducts, let id = readOnlyProducts.first?.siteID {
```
Comment (jaclync) [inline Yosemite/Yosemite/Stores/ProductStore.swift]: nit: maybe we can DI the site ID to the function?

**Review by jaclync — APPROVED** [review]
Works great!! thanks for the updates :shipit:

File: Yosemite/Yosemite/Stores/ProductStore.swift (hunk 2 above)
Comment (itsmeichigo) [reply Yosemite/Yosemite/Stores/ProductStore.swift]: Updated in e41ed55e66e4b175a3c736195205db84835b9413 👍
