### PR TITLE
[Product sharing] Unit test share sheet presentation behaviour.

### LINKED ISSUE #9882: Product sharing: Share sheet is not displayed properly on the celebratory screen on iPad
**Describe the bug**
When tapping the share product button on the celebratory screen on iPad in portrait mode, the share sheet is clipped off at the bottom.

**To Reproduce**
1. Create a new JN site, build and run the app on an iPad.
2. Create the first product.
3. Publish the product. Notice that the celebratory screen is presented after that.
4. Tap the Share Product button. Notice that the share sheet is not displayed properly.

**Screenshots**
Simulator Screenshot - iPad (10th generation) - 2023-06-07 at 10 18 40

**Expected behavior**
The share sheet is not clipped off. It would be nice to show it from the share button.

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #9882 

## Description

Concludes work from - https://github.com/woocommerce/woocommerce-ios/pull/9901

Adds unit tests to `ProductSharingMessageGenerationViewModel` to test 
- share sheet or popover visibility in iPad vs Phone
- share sheet activity items

## Testing instructions
CI passing is sufficient. 

## Screenshots
NA

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift [hunk 1]
```diff
@@ -89,4 +89,97 @@ final class ProductSharingMessageGenerationViewModelTests: XCTestCase {
...
+            switch action {
+            case let .generateProductSharingMessage(_, _, _, completion):
+                completion(.success(expectedString))
+            default:
+                return
+            }
+        }
+
+        // When
+        await viewModel.generateShareMessage()
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift:113]: I don't think we need to generate share message to test the share sheet right? It looks to me that `shareSheet` is a computed variable.

**Review by itsmeichigo — APPROVED** [review]

File: WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/WooCommerceTests/ViewRelated/Products/AI/ProductSharingMessageGenerationViewModelTests.swift:113]: `shareSheet` uses `messageContent` to compute its value. And the `messageContent` will be an empty string if we don't generate a share message.
