### PR TITLE
My Store Analytics: Fix missing stats for custom range

### LINKED ISSUE #12142: Missing stats for custom date ranges
## Problem
When I select a time range for a custom range tab, the start date of the stats is one day later. As in the screencast below, I picked Feb 1-8 - but I got only stats for Feb 2-8:

https://github.com/woocommerce/woocommerce-ios/assets/5533851/0beafb12-352e-469e-be1d-b6596ee89bba

## Expectation
For a custom date range, we want to consider all the stats included from the start date to the end date.

## Potential causes:
In `OrderStatsRemoteV4`, we are setting the start date to the `after` param in the fetching request:

https://github.com/woocommerce/woocommerce-ios/blob/a28476adf90c7792dad289408be0b3d61285cd3d/Networking/Networking/Remote/OrderStatsRemoteV4.swift#L31-L43

This causes the API to return only results for the days after the start date. 

## Potential solution: 

- Adjust `earliestDateToInclude` to one day before
- Update the `quantity` param to be the difference between the start date and end date, plus one extra day to include both dates in the stats.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12142 

## Description

Previously we were calculating manually the difference in hours/days/months/years to determine the `per_page` param to be sent to the endpoint `GET wc-analytics/reports/revenue/stats`.

This calculation is error-prone and can cause missing stats. This PR fixes this by simply returning the maximum number of items allowed for pagination (defined [here](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/)), and the backend will [determine](https://github.com/woocommerce/woocommerce/blob/b471e51734a09eadd5ff80d6eda268a5627b5f3d/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/DataStore.php#L384) the maximum values it can return based on the provided granularity.

Internal discussion: p1709207657326339-slack-C03L1NF1EA3.

Also: 
- Updated the displayed selected date to consider granularity rather than specific range.
- Fixed failed requests to refresh stats with `force_cache_refresh` being false (400 error code).
- Fixed failed unit tests for stats granularity.

## Testing instructions

- Log in to a test store with revenue history.
- Add a custom range or edit an existing one.
- Try a range of 2-7 days. Confirm that the stats include both start and end dates.
- Try a range of 1 day. Confirm that the stats include the time from start date 12 AM to end date 12 am.
- Try a large range in months or years. The stats will only include the possible range for the respective granularity. E.g. if the selected range is from Oct 1 2023 to Feb 7 2024, we can only see stats from Oct 2023 to Feb 7.

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/5533851/44b5def1-ad86-4fee-abcf-545761efba9e

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/188">17.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift [hunk 1]
```diff
@@ -316,9 +316,33 @@ final class StatsStoreV4Tests: XCTestCase {
...
+                                                     latestDateToInclude: .init(),
+                                                     quantity: 1,
+                                                     forceRefresh: true) { _ in
+                promise(())
+            }
+            store.onAction(action)
+        }
+
+        // Then
+        XCTAssertEqual(network.queryParametersDictionary?["force_cache_refresh"] as? Bool, true)
```
Comment (iamgabrielma) [inline Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift]: To make the test more readable, would you consider to declare the assertion at the beginning of the test? Sort of:

```diff
+ let containsExpectedQueryParameter = network.queryParametersDictionary?["force_cache_refresh"] as? Bool
...
- XCTAssertEqual(network.queryParametersDictionary?["force_cache_refresh"] as? Bool, true)
+ XCTAssertEqual(containsExpectedQueryParameter, true)
```

The same for `test_retrieveStats_makes_network_request_without_force_cache_rerefresh_parameter_if_forceRefresh_is_false` down below.

**Review by iamgabrielma — APPROVED** [review]
Works well! 🚢

File: Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift (hunk 1 above)
Comment (itsmeichigo) [reply Yosemite/YosemiteTests/Stores/StatsStoreV4Tests.swift]: Done in a160e3c6cd7673dbe9066592bb5b24bd83b730fd
