### PR TITLE
Order Creation: Add order items to order creation API request

### LINKED ISSUE #5410: Order Creation: API support for existing products when creating an order
The products added to the order (product ID and quantity) need to be added to the request sent to the order creation endpoint (`POST /wc/v3/orders`) when the order is created.

### Tasks

Feel free to divide these into separate subtasks:

- [ ] Add Networking support for sending products (product ID and quantity) to the order creation endpoint
- [ ] Add Yosemite support for sending products (product ID and quantity) to the order creation endpoint
- [ ] Add UI integration for including the products (product ID and quantity) when the order is created on the New Order screen

Sample request:

```
{
  "line_items": [
    {
      "product_id": 196,
      "quantity": 2
    },
    {
      "product_id": 206,
      "quantity": 3
    }
  ]
}
```

### LINKED ISSUE #5682: Order Creation: Create order button is not tappable after adding product to order
During order creation, I noticed that the Create button works as expected when you change the order status. It continues to work if you open the Add Product modal and dismiss it without selecting a product. But it stops working once you add a product to the order.

To reproduce:

1. Build and run the app in debug mode (to ensure the feature flag is enabled).
2. Make sure Order Creation is enabled under Settings > Experimental Features.
3. Go to the Orders tab and tap the + button. (If Simple Payments is also enabled, tap "Create order" in the bottom sheet that appears.)
4. On the New Order screen, tap the "Add product" button.
5. On the Add Product screen, tap to select a product.
6. Notice that the Create button appears, but nothing happens when you tap it.

https://user-images.githubusercontent.com/8658164/146260062-eb6e59c4-78fa-4ce3-8d2f-8411b6c4bc79.mp4

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #5410, Closes: #5682

## Description

This adds support for mapping order items in the remote API request for order creation.

It also fixes a couple issues with order creation for products in the UI layer:
* The `Create` button wasn't tappable after adding products to the order.
* Product quantity changes could be lost when the list of items in the order changed. (This was not visually apparent on the new order screen but caused the quantity to be reset to 1, which could be seen after creating the order.)

## Changes

API support:
* Adds `items` case to `CreateOrderField`.
* Adds `items` field handling on Networking layer. This maps the `productID` and `quantity` for each item in the order.
* Adds unit test for mapping the new `items` field.

UI layer fixes:
* Adds `navigationButtonID` in the `NewOrder` view and `ProductsSection` view, to fix the Create button issue.
* Adds a `quantity` parameter to `ProductRowViewModel`, to set a quantity other than 1 for a product row. (That way, when the product rows are updated for the `NewOrder` view, any previous quantity changes are retained.)
* Updates the unit test for product quantity changes to check that the quantity change is retained when the order items change.

## Testing

1. Build and run the app in debug mode (to ensure the feature flag is enabled).
2. Make sure Order Creation is enabled under Settings > Experimental Features.
3. Go to the Orders tab and tap the + button. Tap "Create order" in the bottom sheet.
4. Tap "Add product" and select a product to add it to the order. Change its quantity.
5. Add at least one more product to the order.
6. Tap the "Create" button that appeared in the navigation bar.
7. Confirm Order Details shows the correct products and quantities.

## Screenshots

https://user-images.githubusercontent.com/8658164/146838284-a02200e6-d72f-45e7-877a-bf56f4692562.mp4

## Submitter Checklist

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/NewOrderViewModelTests.swift [hunk 1]
```diff
@@ -155,9 +155,13 @@ class NewOrderViewModelTests: XCTestCase {
         viewModel.addProductViewModel.selectProduct(product.productID)
         viewModel.productRows[0].incrementQuantity()
 
+        // And when another product is added to the order (to confirm the first product's quantity change is retained)
+        viewModel.addProductViewModel.selectProduct(product.productID)
```
Comment (ealeksandrov) [inline WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Creation/NewOrderViewModelTests.swift:158]: 👍

File: Networking/Networking/Model/OrderItem.swift [hunk 2]
```diff
@@ -113,7 +113,7 @@ public struct OrderItem: Decodable, Equatable, Hashable, GeneratedFakeable, Gene
 
 /// Defines all of the OrderItem's CodingKeys.
 ///
-private extension OrderItem {
+internal extension OrderItem {
```
Comment (ealeksandrov) [inline Networking/Networking/Model/OrderItem.swift]: nit: since `internal` is default access level, do we need to declare it explicitly?

**Review by ealeksandrov — APPROVED** [review]
LGTM! Excited to see most important part of order flow fully working! :shipit:
