### PR TITLE
Fix: Users Unable to Upload Product Images if the store is private

### LINKED ISSUE #12646: Users Unable to Upload Product Images on iOS App if the store is private
**Problem**

We have been alerted to an issue where users are experiencing difficulties when attempting to upload product images through the Android app. On the Android side, the issue was identified as a problem with private sites blocking image uploads (see peaMlT-zw) even with the correct bearer token. Users were not informed of this limitation, leading to confusion and frustration. This happens just on WP.com sites, since on self-hosted store it's not possible to put a store in the "private" state.

**Impact**

Reports have surfaced both in app reviews and comments on GitHub for Android, highlighting the problem:

- "Great app overall, but image uploading from the device isn't working. Please address this. Even after the recent update, the issue persists, and notifications are also non-functional despite Jetpack being configured correctly." - App Review
- "Image uploads from the device still aren't possible on the app. Kindly resolve this." - App Review
- Several comments on GitHub Issue https://github.com/woocommerce/woocommerce-android/issues/10329 also mention similar problems.

**Next Step**

Given the parallel issue that was identified and resolved on the Android platform, I investigated this, and the iOS app faces a similar problem. We need to apply a fix similar to the one applied on Android here https://github.com/woocommerce/woocommerce-android/pull/11383

### PR DESCRIPTION
**Pull request by pmusolino**
Closes: #12646

## Description
The PR adds a notice in Product detail when a WP.com site is in Private mode since this makes the images not accessible.
This happens just on WP.com sites, since on self-hosted store it's not possible to put a store in the "private" state.
This has been already fixed here https://github.com/woocommerce/woocommerce-android/pull/11383 and here https://github.com/woocommerce/woocommerce-android/pull/11493 on Android.

## Detail implementation
I decided to use a custom table view cell inside the image section instead of showing it as a banner, because it can happen to have another banner already displayed while the user is editing a product (or it can appear later). In this way, this notice in product images is always displayed when the store is private.

### Test 1
1. Log in to a *WP.com site* that is `Public`
2. Go to Products -> Tap on some product
3. Verify the images are available (either existing images or button to add one)
4. In `wp-admin` set the site to `Private` mode in Settings ([more info here](https://wordpress.com/support/privacy-settings/))
5. In the app, switch to a different site and switch back (or re-login, or close and reopen the app)
6. Go to Products -> Tap on some product
7. Verify a notice is displayed instead of an image gallery
8. Tap on the notice
9. Verify the privacy settings page is opened
10. Go back
11. In `wp-admin` set the site to `Coming soon` mode in the Settings
12. In the app, switch to a different site and switch back (or re-login, or close and reopen the app)
13. Go to Products -> Tap on some product
14. Verify the images are available (either existing images or button to add one)

### Test 2
1. Create a self-hosted site with WooCommerce but without installing Jetpack or connecting a WP.com user using JCP
2. Log in to the app
3. Start creating a product
4. Verify the image uploading is available

## Screenshots
| Light mode             |  Dark mode |
:-------------------------:|:-------------------------:
Simulator Screenshot - iPhone 15 Pro Max - 2024-05-23 at 18 34 58 | Simulator Screenshot - iPhone 15 Pro Max - 2024-05-23 at 18 35 11

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/Networking/Model/Site.swift [hunk 1]
```diff
@@ -284,6 +284,11 @@ public extension Site {
         return TimeZone(secondsFromGMT: secondsFromGMT) ?? .current
     }
 
+    /// Returns true only if the site is hosted on WP.com and is private.
+    ///
+    var isPrivateWPCOMSite: Bool {
+        return isWordPressComStore && !isPublic
```
Comment (itsmeichigo) [inline Networking/Networking/Model/Site.swift]: This logic includes only public sites. Is it possible to access images for sites with Coming soon status?

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift [hunk 2]
```diff
@@ -107,9 +112,36 @@ private extension ProductFormTableViewDataSource {
...
+                text: Localization.wpComStoreNotPublicText,
+                    textTintColor: .textLink,
+                    image: .infoOutlineImage,
+                    imageTintColor: .text,
+                    numberOfLinesForTitle: 0,
+                    numberOfLinesForText: 0,
+                    isActionable: true,
+                    showsDisclosureIndicator: false,
+                    showsSeparator: true
+                )
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormTableViewDataSource.swift]: Nit: can you update the indenting here please?

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/Cells/ImageAndTitleAndTextTableViewCell.swift [hunk 3]
```diff
@@ -36,6 +37,7 @@ final class ImageAndTitleAndTextTableViewCell: UITableViewCell {
 
         init(title: String?,
              titleFontStyle: FontStyle = .body,
+             titleTintColor: UIColor? = nil,
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/Cells/ImageAndTitleAndTextTableViewCell.swift:40]: Nit: to avoid updating other cells, you might want to set the default  value to a common one (e.g. `.text`).

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift [hunk 4]
```diff
@@ -33,14 +35,16 @@ struct DefaultProductFormTableViewModel: ProductFormTableViewModel {
...
+         featureFlagService: FeatureFlagService = ServiceLocator.featureFlagService,
+         stores: StoresManager = ServiceLocator.stores) {
         self.currency = currency
         self.currencyFormatter = currencyFormatter
         self.shippingValueLocalizer = shippingValueLocalizer
         self.weightUnit = weightUnit
         self.dimensionUnit = dimensionUnit
         self.isDescriptionAIEnabled = isDescriptionAIEnabled
         self.featureFlagService = featureFlagService
+        self.stores = stores
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift]: Nit: I don't see `stores` being used, should we remove it?

**Review by itsmeichigo — COMMENTED** [review]
Thanks for the fix @pmusolino! This test didn't pass for me: 

> In wp-admin set the site to Coming soon mode in the Settings
In the app, switch to a different site and switch back (or re-login, or close and reopen the app)
Go to Products -> Tap on some product
Verify the images are available (either existing images or button to add one)

File: Networking/Networking/Model/Site.swift (hunk 1 above)
Comment (pmusolino) [reply Networking/Networking/Model/Site.swift]: This is not expected, unfortunately. As you can see here C06NC969ZF0/p1715793466695389?thread_ts=1715193928.110329&cid=C06NC969ZF0 I was expecting that parsing `blog_public` limiting it to Atomic websites return `private = true` only if the store is `private` and not `coming soon` or `public`.

It seems btw that the app parse `isPublic` alias `blog_public` as a boolean, while it's an integer. From my tests, the values should be `private = -1`,  `coming soon = 0`, `public = 1`. When it's `-1`, it's automatically `false`, that's why it works as expected. When it's coming soon, it's also false (0), and that's why you see the banner.

I'm going to address this

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/Cells/ImageAndTitleAndTextTableViewCell.swift (hunk 3 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/Cells/ImageAndTitleAndTextTableViewCell.swift:40]: There was just one point where `titleTintColor` was needed, and it was `DownloadableFileBottomSheetListSelectorCommon`. To match the behavior of `textTintColor` I preferred to set it to `nil` 👍

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift (hunk 4 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/DefaultProductFormTableViewModel.swift]: Good catch c2255b7178dfbc96033cf41c1dc73eacd6f5b04e

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Networking/Networking/Model/Site.swift (hunk 1 above)
Comment (pmusolino) [reply Networking/Networking/Model/Site.swift]: @itsmeichigo this is ready for another review! 
Here are all the changes: a91a6fce415516a6518a972055d4abb2700fe5be

Below is the list of changes:
- I removed the `isPublic` property from the `Site` model, which has been replaced with `visibility`, a property of type `SiteVisibility`. `SiteVisibility` is an enum that contains the values `private = -1`, `coming soon = 0`, `public = 1`.
- Following the above change, I created a new Core Data model (version 112). As there is a data migration involved from the old Boolean value to the new Int64 in the database, there is also a new mapping model that converts the old Boolean value from model version 111 to the new Int64 in model version 112.
- I updated all the code to use the new `visibility` property.

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift [hunk 5]
```diff
@@ -49,7 +49,7 @@ final class OrderListViewModel {
         }
 
         /// Enabled if site is launched, has published at least 1 product and set up payments.
-        return site.isPublic && hasAnyPaymentGateways && hasAnyPublishedProducts
+        return (site.visibility == .publicSite) && hasAnyPaymentGateways && hasAnyPublishedProducts
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift:52]: This fails for self-hosted sites because you were setting the default visibility for them as `.comingSoon`. I pushed a change in 44036af6c49a5da87fe9bfe5c304069aa4798dc4 to make them public by default.

**Review by itsmeichigo — COMMENTED** [review]
I found issues with self-hosted sites when checking their visibility to display the Share option for products and Test order on the Orders tab, so I pushed a commit to fix that.

Although this works as described now, I'm not confident I didn't miss any edge cases. There aren't any migration tests for the migration from Core Data model version V111 to 112, and it's quite close to the code freeze, it's safer to delay the merge until the next version.

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift (hunk 5 above)
Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift:52]: This is likely an error that existed previously since the WordPressSite had the `isPublic` property set to `false`, which was equivalent to `comingSoon`. Therefore, with the configuration I had in place, there should not have been any difference in behavior.

**Comment by pmusolino** [comment]
Added the test for the migration from Core Data model version V111 to 112 408181ad0e9ca04df3018f5518dec67a9c540558

**Review by itsmeichigo — APPROVED** [review]
Thanks for adding the migration test Paolo!
