### PR TITLE
[Blaze] Validate campaign image dimensions

### LINKED ISSUE #12463: [Blaze] Inform/Validate expected image size
Currently, Blaze Ads supports images of 500 x 500px. If the image is larger, the backend will center-crop it to make it 500x500px. But if the image is smaller, then apparently, we get an error.

Error response
```
Error creating Blaze campaign: Sorry, there was an issue with the server. Please try again later. (Error code: 422). Response: {"message":"Validation failed","details":{"main_image":{"message":"Insufficient image size for cropping"}}}
```

Internal - p1712592228577439-slack-C6H8C3G23

### PR DESCRIPTION
**Pull request by selanthiraiyan**
Closes: #12463

## Description

Blaze backend expects the campaign image size to be greater than or equal to 500*500.

To inform users about this requirement, we are validating the selected campaign image dimensions and showing a local error alert about the expected image dimensions. 

Internal discussion in which we decided to follow the above approach - p1712745183124909/1712674079.063239-slack-C03L1NF1EA3

## Testing instructions

Prerequisites
- Woo Store eligible for Blaze
- A published product with an image with dimensions less than 500*500. 
- An image with dimensions less than 500*500 in your device/simulator library.

Steps
- Login into a Woo store eligible for Blaze.
- Navigate to the Products tab and tap on the product with the image with dimensions less than 500*500. 
- You should see the "Promote with Blaze" button.
- Tap "Promote with Blaze" -> "Confirm Details". 
- You should see an error alert asking you to select an image with minimum dimensions of 500*500.
- Tap "Edit ad" and navigate to the edit screen.
- Tap "Change image" and choose an image with dimensions less than 500*500. 
- You should see an error alert asking you to select an image with minimum dimensions of 500*500.

#### Creation form - When a product image does not have 500 * 500

https://github.com/woocommerce/woocommerce-ios/assets/524475/6fa001b9-3719-48d8-b3e3-c12e239be92e

#### Edit image form - When selected image 500 * 500

https://github.com/woocommerce/woocommerce-ios/assets/524475/18ebacb4-68e6-4a2e-ac36-c26f7771ec1a

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/194">18.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift [hunk 1]
```diff
@@ -252,6 +255,16 @@ private extension BlazeEditAdView {
                 value: "Change image",
                 comment: "Change image button title in the Blaze Edit Ad screen."
             )
+            static let imageSizeError = NSLocalizedString(
+                "blazeEditAdView.image.imageSizeError",
+                value: "Please select an image with minimum dimensions of 500 * 500.",
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift]: Nit: we should specify the unit for the image size for clarity.

```suggestion
                value: "Please select an image with minimum dimensions of 500 × 500 px.",
```

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdViewModel.swift [hunk 2]
```diff
@@ -154,6 +160,10 @@ final class BlazeEditAdViewModel: ObservableObject {
             guard let image = await onAddImage(source) else {
                 return imageState = previousState
             }
+            guard image.image.size.width >= minImageSize.width || image.image.size.height >= minImageSize.height else {
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdViewModel.swift]: I'm not sure if checking the size is enough. I have an image of size 1722*501 but it still got rejected when creating a new campaign. In order to test this, you can open any image in Preview app > Tools > Adjust Size > then set either of the dimensions to 500 or 501. I haven't checked with slightly larger sizes, it'd be great if we can confirm the logic with backend folks.

File: WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift [hunk 3]
```diff
@@ -297,10 +298,14 @@ final class BlazeCampaignCreationFormViewModel: ObservableObject {
     }
 
     func didTapConfirmDetails() {
-        guard image != nil else {
+        guard let image else {
             return isShowingMissingImageErrorAlert = true
         }
 
+        guard image.image.size.width >= editAdViewModel.minImageSize.width || image.image.size.height >= editAdViewModel.minImageSize.height else {
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift]: Same comment as above about the check.

**Review by itsmeichigo — COMMENTED** [review]
Thanks for the fix! I wasn't able to submit a campaign with an image of size 1722 × 501 - I'm not sure if our check matches with backend's check - I think we should verify with them. In the meanwhile, should we display a message when the image size is insufficient? We might want to catch this error:

> ⛔️ Error creating Blaze campaign: Sorry, there was an issue with the server. Please try again later. (Error code: 422). Response: {"message":"Validation failed","details":{"main_image":{"message":"Insufficient image size for cropping"}}}

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdViewModel.swift (hunk 2 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdViewModel.swift]: I have updated the expected size as `600 * 600`. But we are still talking with the backend team as the campaign creation fails for image size `1722 * 601`. p1712848101999269/1712831053.533739-slack-C069RG07W6S

Meanwhile, since we started showing the exact error reason to the user, https://github.com/woocommerce/woocommerce-ios/pull/12470#issuecomment-2050215178 I think we can merge this PR for now and update the image size validation again.

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift]: Updated in https://github.com/woocommerce/woocommerce-ios/pull/12470/commits/e0806346a0b0b918b91ec22e4d559076dc49cb41

**Comment by selanthiraiyan** [comment]
> In the meanwhile, should we display a message when the image size is insufficient? We might want to catch this error:

Great point. I have started handling this error in https://github.com/woocommerce/woocommerce-ios/pull/12470/commits/73268afefd5c29fa30773f1dca36acc2674e49ee

#### When the insufficient error happens
| Before | After |
|--------|--------|
| Before | After |

**Comment by selanthiraiyan** [comment]
Thank you for the review, @itsmeichigo! 🙇 The PR is ready for another look. 

As discussed in p1712739200004669-slack-C03L1NF1EA3, I have added the change of resetting the My Store Blaze section after campaign creation in https://github.com/woocommerce/woocommerce-ios/pull/12470/commits/e4560e7e7a74305b31e5249c8b621e0333162583. 

I have addressed your comments. We still aren't sure about the expected image dimensions, but we have started showing a better error message. I think we can merge this PR as a temporary fix and update the image size later.

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift [hunk 4]
```diff
@@ -252,6 +255,16 @@ private extension BlazeEditAdView {
                 value: "Change image",
                 comment: "Change image button title in the Blaze Edit Ad screen."
             )
+            static let imageSizeError = NSLocalizedString(
+                "blazeEditAdView.image.imageSizeError",
+                value: "Please select an image with minimum dimensions of 600 * 600 px.",
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift]: We should use "× " instead of "*" for user-facing copy (the same symbol is used on mac).

```suggestion
                value: "Please select an image with minimum dimensions of 600 × 600 px.",
```

**Review by itsmeichigo — APPROVED** [review]
I tested again with an image of size 2062 × 600 and successfully created a campaign 🎉  Resetting Blaze section visibility works too. 🚢

File: WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift (hunk 4 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift]: I'll merge the change above and enable automerge for the code freeze.

Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Blaze/BlazeEditAd/BlazeEditAdView.swift]: Thank you! ❤️
