### PR TITLE
[IAP] Ignore renewal errors, not all product purchase errors

### LINKED ISSUE #10075: [IAP] New purchases which receive a 422 error when submitted are shown as successful, but not upgraded
## Description

With 🍍 we're adding the ability to buy Woo Express plans using IAP.

We initially only support upgrading a single site. Upgrading multiple sites is prevented by checking whether the merchant has already got an entitlement to an In-App Purchase, and showing the `Maximum sites upgraded` error at the start of the Upgrade flow if they have.

Unfortunately, if the MobilePay server and Apple are out of sync, it's possible to make an In-App Purchase to upgrade a second site which will succeed with Apple (i.e. taking the merchants money), fail with MobilePay, but be announced as success in the app. The IAP `Transaction` will be marked as `finished`, (i.e. we're telling Apple that we've furnished the merchant with the upgrade they paid for) and the site will remain on the trial. We won't ever show the merchant an error.

This isn't readily reproducible without forcing the two systems to be out of sync, but it's high enough impact that we should have some mitigation.

## To Reproduce

1. Using a sandbox App Store account, and a Woo Express free trial store,
2. Launch the app, and tap Upgrade Now
3. Upgrade the site and wait until the IAP expires (usually 1hr for sandbox users)
4. Edit the WC order in the backing store, change the status from `cancelled` to `completed`.
5. Launch the app and make a new free trial store
6. Upgrade the new store with IAP – observe that you can complete the payment
7. Observe that the `Completed` celebration screen is shown, saying the store is upgraded
8. Check wp-admin for the store on the web: observe that it still on a free trial

## Expected behaviour

We should not show the `Completed` screen, and should instead show the `Post Purchase Error` advising the merchant to contact support.

## Underlying issue and proposed fix:

422 errors are common in our implementation, as we get lots of `renewal` transactions which we have to handle on app start up – when we send these to the API, MobilePay already knows about them because of the server to server notifications from the App Store Connect API, so sends us a 422. We mark the transaction as finished and ignore the error, which is correct in this case.

Unfortunately, we can't distinguish between these and new purchases, [because the `reasonStringRepresentation` which Apple documents](https://developer.apple.com/documentation/storekit/transaction/4193540-reasonstringrepresentation)... doesn't seem to exist. Perhaps we can use the new `reason` property once iOS 17 reaches wider adoption.

Initially, we'll mitigate this by treating user-initiated purchases differently, while we're still in the upgrade flow – we'll stop ignoring 422s for just those transactions, and show them to the user.

It will still be possible to trigger this error, by completing the IAP and quickly closing the app. The next time we come in to the app, it'll restart, but will treat it as a renewal again and this issue will still happen. We can improve that in future by keeping a log of new transaction IDs in the app, but that's out of scope for now.

CC. @iamgabrielma @hannahtinkler @lmischner

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #10075 
Merge after #10093

~⛔️ Do not merge until **D114571** on MobilePay is landed~ ✅ 

## Description

Initially, our IAP plan purchases only support upgrading a single site. Upgrading multiple sites is prevented by checking whether the merchant has already got an active entitlement to an In-App Purchase, and showing the Maximum sites upgraded error at the start of the Upgrade flow if they have.

Unfortunately, if the MobilePay server and Apple are out of sync, it's possible to make an In-App Purchase to upgrade a second site which will succeed with Apple (i.e. taking the merchants money), fail with MobilePay, but be announced as success in the app. The IAP Transaction will be marked as finished, (i.e. we're telling Apple that we've furnished the merchant with the upgrade they paid for) and the site will remain on the trial. We won't ever show the merchant an error.

Originally, we ignored all `productPurchased` errors because they were _usually_ renewals that had been processed on the server already, via server-to-server notifications.

This meant that we missed edge case errors where the merchant already had a live upgrade we knew about it, so we stopped ignoring these errors in the purchase flow – however, we still ignored them in the purchase recovery flow.

MobilePay now returns a distinct error message for renewals and other “unsupported” transactions that we submit. This means we can always ignore renewals, and avoid ever ignoring `productPurchased` errors, which can hide some rare edge cases.

### Sandbox the API changes

If D114571 is not landed yet, on your WPCom sandbox apply that patch and sandbox `public-api.wordpress.com`, routing your device's traffic to it using Proxyman and your hosts file.

### Purchase flow

1. Using a sandbox App Store account, and a Woo Express free trial store,
2. Launch the app, and tap Upgrade Now
3. Upgrade the site and wait until the IAP expires (usually 1hr for sandbox users)
4. Edit the WC order in the backing store, change the status from `cancelled` to `completed`.
5. Launch the app and make a new free trial store
6. Upgrade the new store with IAP – observe that you can complete the payment
7. Observe that the `Error Activating Plan` screen is shown, saying that they should contact support.

### Renewal flow

Using a sandbox App Store account, and a Woo Express free trial store,
Launch the app, and tap Upgrade Now
Upgrade the site
Background the app and then open it again.
Wait for the renewals to come in
Observe that the `"Unsupported transaction recieved: \(transaction.id) on site \(siteID), ignoring.` message is logged to the console

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Yosemite/Yosemite/Stores/InAppPurchaseStore.swift [hunk 1]
```diff
@@ -236,11 +231,12 @@ private extension InAppPurchaseStore {
...
-                throw Errors.transactionAlreadyAssociatedWithAnUpgrade
-            }
-            // Ignore errors for existing purchase
-            logInfo("Existing order found for transaction \(transaction.id) on site \(siteID), ignoring")
+            throw Errors.transactionAlreadyAssociatedWithAnUpgrade
+        } catch WordPressApiError.transactionReasonInvalid(let reasonMessage) {
+            /// We ignore transactionReasonInvalid errors, usually these are renewals that
+            /// MobilePay has already handled via Apple's server to server notifications
+            /// [See #10075 for details](https://github.com/woocommerce/woocommerce-ios/issues/10075)
+            logInfo("Unsupported transaction recieved: \(transaction.id) on site \(siteID), ignoring. \(reasonMessage)")
```
Comment (iamgabrielma) [inline Yosemite/Yosemite/Stores/InAppPurchaseStore.swift]:
```suggestion
            logInfo("Unsupported transaction received: \(transaction.id) on site \(siteID), ignoring. \(reasonMessage)")
```

File: Networking/Networking/Model/WordPressApiError.swift [hunk 2]
```diff
@@ -61,6 +68,13 @@ extension WordPressApiError: CustomStringConvertible {
             return NSLocalizedString(
                 "An order aready exists for this receipt",
```
Comment (iamgabrielma) [inline Networking/Networking/Model/WordPressApiError.swift]:
```suggestion
                "An order already exists for this receipt",
```

**Review by iamgabrielma — APPROVED** [review]
Tests well for both purchase and renewal flows! 🚢 
```
2023-06-28 19:36:25.414317+0700 WooCommerce[7155:3396471] [💰IAP Store] Unsupported transaction recieved: 2000000358829283 on site 220619290, ignoring. Invalid transaction reason: RENEWAL.
```
