### PR TITLE
[Order Creation] Ensure correct variation list is opened for selected variation

### LINKED ISSUE #7026: [Order Creation] Selecting a variable product from the product list opens wrong variation list
**Describe the bug**

Selecting a variable product from the product list can open the wrong variation list. This seems most consistently reproducible when searching for a product first, and then selecting a variable product.

Reported in testing: pdfdoF-QC-p2#comment-1736

**To Reproduce**
1. Go to the Orders tab and create a new order.
2. Select "Add product" to open the product list.
3. Do a search that returns multiple variable products.
4. Select a variable product from the list and notice the wrong list of variations (variations for a different product) are loaded.

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #7026

## Description

This fixes a bug in the `ProductSelector` (used for displaying the product list in Order Creation and in the Coupons feature) where selecting a variable product from the product list could open the wrong list of product variations.

## Changes

The problem was caused by using an `isActive` state property in the `LazyNavigationLink` within the `ForEach` loop (the product list). This activated all of the navigation links in the list, instead of just the link for the selected variable product.

This PR moves the `LazyNavigationLink` outside the `ForEach` loop so there's only a single navigation link in the view. To make that work, there's a new state property `variationListViewModel`: it is set when a variable product is tapped and is used in the `LazyNavigationLink` to set the selected variation list view model. (The `productID` in that view model is also now publicly accessible so it can be used in the `LazyNavigationLink` in the `onMultipleSelections` closure.)

## Testing

1. Go to the Orders tab and create a new order.
2. Select "Add Product" to open the product list.
3. Select several different variable products and confirm that each time, the expected variation list is opened.
4. You can also search the product list for variable products. Then, select one of the variable products in the search results and confirm the expected variation list is opened.

Bonus: Enable the experimental Coupons feature and confirm the product selector works as expected there:

1. Go to Menu > Settings > Experimental Features > Enable Coupon Management.
2. On the Menu tab, select Coupons.
3. Select a coupon from the list.
4. Tap the ellipsis menu in the top right and select "Edit Coupon."
5. Under "Apply This Coupon To" select "All Products."
6. Confirm you can select all or some of the variations for a variable product in the product list there.

## Screenshots

Before:

https://user-images.githubusercontent.com/8658164/172176978-4dc023d6-d2e3-4096-be63-48eb24b3ce34.mp4

After:

https://user-images.githubusercontent.com/8658164/172176992-aea260f8-8bdb-4c53-8596-e235dcfb2c36.mp4

## Submitter Checklist

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift [hunk 1]
```diff
@@ -14,6 +14,10 @@ struct ProductSelector: View {
     ///
     @State var isShowingVariationList: Bool = false
 
+    /// View model to use for the variation list, when it is shown.
+    ///
+    @State var variationListViewModel: ProductVariationSelectorViewModel?
```
Comment (Ecarrion) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift:19]: Do you think we can provide a custom binding of `isShowingVariationList` in order to nil the `variationListViewModel` once it has been dismissed / closed / navigated away?

Comment (rachelmcr) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift:19]: I thought about this a bit and felt divided about it:

On one hand, it isn't strictly necessary to nil `variationListViewModel` since it is updated with the newly selected view model any time `isShowingVariationList` is set to `true`. (Any previous value is ignored until it's updated again when a new variable product is selected in the list.)

On the other hand, it seems reasonable to make the connection between these properties more explicit. Rather than a custom binding, if we want to do this I think we could use `.onChange(of:perform:)` to nil `variationListViewModel` as an explicit side effect of `isShowingVariationList` being changed.

However, after trying that out I don't think it's worth doing this. If we nil `variationListViewModel` every time we navigate back, the `LazyNavigationLink` isn't kept in the view hierarchy (because of the nil check `if let variationListViewModel = variationListViewModel`). If it isn't already in the view hierarchy, there isn't any animation when going from the product list to the variation list. The solution for that would be to accept an optional view model in `ProductVariationSelector` and I think that creates unnecessary complexity there.

What do you think? It's possible to do, but I'm not sure it's worth it in this case.

Comment (Ecarrion) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift:19]: Well, if It's causing animation problems maybe it's ok to leave it as it is?
I'm not sure I totally understand why the navigation link has to exists conditionally tho 😅

**Review by Ecarrion — APPROVED** [review]

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift (hunk 1 above)
Comment (rachelmcr) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelector.swift:19]: > I'm not sure I totally understand why the navigation link has to exists conditionally tho 😅

It exists conditionally so we can pass `variationListViewModel` as a non-optional to the `ProductVariationSelector` initializer (as the `LazyNavigationLink` destination). Every other solution I tried, to avoid having to do that, ended up with issues like the missing animation or sometimes navigating to an empty view (e.g. when I tried to use a `@ViewBuilder` to create the destination view for the navigation link, with `EmptyView` as a fallback).

I'll go ahead and merge it as-is but I'll keep an eye out for better solutions I haven't tried yet.
