### PR TITLE
Background image upload: Update error handling

### LINKED ISSUE #15065: Failed uploads screen and retry cta
Follow Android to display an action button on the notice when image upload fails. Tapping on this button should display a new screen with a list of images that are failed to upload and buttons to retry to uploads.

Image
Image

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #15065 

## Description

Previously our error handling for image uploads was pretty minimal - with only generic error alerts in the product form and error notices outside of the screen. As an improvement, we were suggested to use a separate screen for all image uploads similar to Android.

However, while working on the improvements, I realized that it's better to show more details on errors right on the product form for better relevance. This PR updates the error handling by keeping the failed uploads in the image list and enabling users to retry uploads on the product form.

Changes include:
- `ProductImageStatus`: Add a separate status for failed uploads
- `ProductImageActionHandler`: Remove the error from the `OnAllStatusesUpdate` callback and return statuses directly instead.
- `ProductImageUploader`: 
  - Removed the unused `productImageStatuses` from `ProductImageUploadErrorInfo`.
  - Updated the error observation by listening to updates from the asset upload results.
- Added a new cell type `FailedProductImageCollectionViewCell` for failed uploads.
- Updated the product form and product image list to:
  - display the failed uploads as separate cells
  - allow tapping on the cell to see error details, and retry or discard the uploads.
- Updated relevant unit tests. 

Apologies for the large number of changes, the updates are related to each other so it was not possible to split into smaller PRs.

### Testing error handling when image uploading fails on the product form

1. Open an existing product or create a new one.
2. Disconnect the Internet connection before uploading one or more images or add a debug point for the image upload endpoint to mock the response later using Proxyman / Charles.
3. When the uploads fail, confirm that an alert is displayed with the error details and two CTAs: Retry and Discard the upload. The uploading cell is updated to show a circle arrow instead.
4. Tap Retry and confirm that the upload is in progress again. Confirm that `product_image_upload_retry_button_tapped` is tracked.
5. When the upload fails again, select Discard on the alert. Confirm that the upload is removed from the image list of the product form.

https://github.com/user-attachments/assets/bf1a3672-3b5a-4400-935b-1ba204671280

https://github.com/user-attachments/assets/7079c206-9287-46fd-8b81-046c2ebba453

### Testing error handling when reopening the product form after uploading fails

1. Open an existing product or create a new one.
2. Disconnect the Internet connection before uploading one or more images or add a debug point for the image upload endpoint to mock the response later using Proxyman / Charles.
3. Navigate back to the product list and wait for the uploads.
4. Confirm that an error notice is presented with a CTA to the product form.
5. Navigate to the product details again and confirm that the failed uploads are displayed both on the product form and the image list screen.
6. On both screens, try tapping on the failed upload cells.
7. Confirm that on both screens, an alert is displayed with the error details of the failed upload and two CTAs to retry or discard the upload.
8. Test the two CTAs and confirm that they work similarly to the first test case. Confirm that `product_image_upload_retry_button_tapped` is tracked when tapping the Retry button.

https://github.com/user-attachments/assets/2da95b1f-65a6-430b-836b-008b61cadd03

## Testing information

Tested on simulator iPhone 16 Pro iOS 18.2 and confirmed that:
- Error alert is displayed with error details and CTAs when an upload fails while on the product form.
- Both CTAs work as expected.
- When viewing a product form with failed image uploads in the background, failed uploads are displayed on both the product form and the image list.
- Tapping on failed upload cells shows the same alert as when the upload fails on the product form.
- The error notice is displayed properly when image upload fails in the background.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/FailedProductImageCollectionViewCell.swift [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        imageView.clipsToBounds = Settings.clipToBounds
+    }
+
+    func configureBlurView() {
+        let blurEffect = UIBlurEffect(style: .extraLight)
+        effectView.effect = blurEffect
+    }
+
+    func configureErrorImageView() {
+        errorImageView.image = UIImage(systemName: "arrow.counterclockwise")
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/FailedProductImageCollectionViewCell.swift:36]: nit: Do you think we should consider using a different image here to clearly indicate an error occurred? The current "Refresh" image might convey that a product image didn't load from the remote.

File: WooCommerce/Classes/ServiceLocator/ProductImageUploader.swift [hunk 2]
```diff
@@ -276,16 +277,24 @@ private extension ProductImageUploader {
...
-                removeProductFromActiveUploads(key: key)
-                errorsSubject.send(.init(siteID: key.siteID,
-                                         productOrVariationID: key.productOrVariationID,
-                                         productImageStatuses: productImageStatuses,
-                                         error: .failedUploadingImage(error: error)))
+    func observeImageUploads(key: Key, actionHandler: ProductImageActionHandler) {
+        let observationToken = actionHandler.addAssetUploadObserver(self) { [weak self] asset, result in
+            guard let self else { return }
+
+            if case .failure(let error) = result {
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ServiceLocator/ProductImageUploader.swift:288]: Super nit: Consider using guard for early exit to increase readability.

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift [hunk 3]
```diff
@@ -1037,6 +1040,25 @@ private extension ProductFormViewController {
...
+                                      preferredStyle: .alert)
+        let discard = UIAlertAction(title: Localization.ImageUploadError.discard, style: .destructive, handler: { [weak self] _ in
+            self?.productImageActionHandler.discardUpload(asset: asset)
+        })
+        alert.addAction(discard)
+
+        let retry = UIAlertAction(title: Localization.ImageUploadError.retry, style: .default, handler: { [weak self] _ in
+            ServiceLocator.analytics.track(.productImageUploadRetryButtonTapped)
+            self?.productImageActionHandler.discardUpload(asset: asset)
+            self?.productImageActionHandler.uploadMediaAssetToSiteMediaLibrary(asset: asset)
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift:1056]: Opinion: Consider adding a comment explaining that we discard the upload and start a new one.

**Review by selanthiraiyan — APPROVED** [review]
Nice work, Huong! 👏 

The code LGTM and tests as described. I left couple of non-blocking nits.

---

I noticed that the failed image is set as the cover image upon successful retry. Please feel free to log a separate issue for this.  

https://github.com/user-attachments/assets/c5f34de3-3931-40ae-affd-0a26b3845d32

--- 

Not related to this PR. 

When a notice appears in the product detail screen tapping on it to view error info opens another product detail screen in a modal screen. 



https://github.com/user-attachments/assets/75da17ed-890f-4f7f-8b93-c3c8c9775405

File: WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/FailedProductImageCollectionViewCell.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/FailedProductImageCollectionViewCell.swift:36]: There's a thread about this here: p1739186718310849-slack-C03L1NF1EA3. TL;dr: the circular arrow makes it clearer that the image can be tapped to retry. Anyway, we'll likely update this when we get design involved in the project, so I'm keeping this for now.

File: WooCommerce/Classes/ServiceLocator/ProductImageUploader.swift (hunk 2 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ServiceLocator/ProductImageUploader.swift:288]: I prefer to keep the `if` check as this logic is inside the observation closure. A guard check would make more sense when it's in a separate method dedicated to error handling only. I'm keeping this for now.

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift (hunk 3 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift:1056]: Done in cd3b745d3d287ca547c6a6c172c5611af7239339.

**Comment by itsmeichigo** [comment]
Thanks Sharma for the reviews!

> I noticed that the failed image is set as the cover image upon successful retry. Please feel free to log a separate issue for this.

This is the current behavior on iOS that the last image to be uploaded would become the cover photo. Are you suggesting displaying the cover tag on the image next to the uploading image until the upload is completed?

> When a notice appears in the product detail screen tapping on it to view error info opens another product detail screen in a modal screen.

Nice catch! I filed a separate issue for this in #15170.

**Comment by selanthiraiyan** [comment]
> This is the current behavior on iOS that the last image to be uploaded would become the cover photo. Are you suggesting displaying the cover tag on the image next to the uploading image until the upload is completed?

Thanks, @itsmeichigo! I didn't know that this is current behaviour. I thought that making the last uploaded image as the cover photo might cause inconvenience to the user. Would you happen to know how we handle this in Android? I think it is OK to leave it as is if the behaviour aligns between platforms and there are no user complaints. What do you think?

File: WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/FailedProductImageCollectionViewCell.swift (hunk 1 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Products/Cells/Product Images/Collection View Cells/FailedProductImageCollectionViewCell.swift:36]: Thanks for sharing this discussion! It makes sense to me. 👍

**Comment by itsmeichigo** [comment]
> I thought that making the last uploaded image as the cover photo might cause inconvenience to the user. Would you happen to know how we handle this in Android? I think it is OK to leave it as is if the behaviour aligns between platforms and there are no user complaints. What do you think?

@selanthiraiyan On Android they are not setting the latest photo as the cover, I think the last photo would be at the end of the list if I'm not mistaken. This is not a good experience either as the last photo would be hard to discover after uploading completes, as pointed out by Paolo in his last beta review p1738925705150139-slack-C03L1NF1EA3. 

I'll note this down as something to review with design when they join.
