### PR TITLE
[IAP] Show correct purchase upgrade errors

### LINKED ISSUE #9886: [IAP] Error handling when upgrading
There's several methods in `UpgradesViewModel` which could return an error, as are implementations from their async throws `InAppPurchasesForWPComPlansManager` counterparts, for example:

1. `loadUserEntitlements`: Iterates through all available WPCom plans and checks whether the merchant is entitled to purchase them via IAP
2. `fetchPlans`: Retrieves all In-App Purchases WPCom plans

These two run when we tap on "Upgrade Now":

| While loading | Finish loading |
|--------|--------|
| Screenshot 2023-06-15 at 19 23 15 | Screenshot 2023-06-15 at 19 23 34 |

During this process, we could fail to either load the user entitlements, or fetch the products. Currently we do nothing when these fail, we just log the error in the system: `DDLogError("fetchPlans \(error)")`.

3. `purchaseProduct`: This will be called when we perform the purchase by tapping "purchase xxxx plan". The flow involves calling StoreKit -> Verifying with AppleID -> Waiting for the site to be set and ready -> Additional delay until we see everything updated in the app.

| Call StoreKit | Purchase verification | All Set |  Updated data |
|--------|--------|--------|--------|
| Screenshot 2023-06-15 at 19 26 47 | Screenshot 2023-06-15 at 19 28 09 | Screenshot 2023-06-15 at 19 29 06 | Screenshot 2023-06-15 at 19 29 25 | 

As before, errors here are not handled UI-wise, we only log these internally: `DDLogError("purchasePlan \(error)")`. Apart from the error, we could inform to the merchants that the process is ongoing and needs some time (they do not need to wait in the same screen until this process completed).

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #9886 (follows from #10044 which should be merged first)

## Description

We have added the ability to purchase plans using IAP. When this fails after the IAP, we show errors which can only really be resolved by talking to support.

This PR adds the error code to those screens, and shows the appropriate screen based on the error raised by the InAppPurchaseStore.

## Testing instructions

Hardcode the `InAppPurchaseStore` to show the error you want to test, by adding `throw Errors.transactionMissingAppAccountToken` or similar to the [first line of the do block in `purchaseProduct`](https://github.com/woocommerce/woocommerce-ios/blob/f8dfa09c44c59dad5d573fb6668099650be0e7bf/Yosemite/Yosemite/Stores/InAppPurchaseStore.swift#L83).

1. Start the app and select a Woo express store with a free trial active
2. Tap `Upgrade now`
3. Wait for the load to finish
4. Tap `Purchase Debug Essential Monthly`
5. Observe that the expected error screen shows, and includes the error code if recognised.

#### Plan Activation Error
- `transactionMissingAppAccountToken`
- `appAccountTokenMissingSiteIdentifier`
- `storefrontUnknown`

#### Purchase Failed Error
- `unverifiedTransaction`
- `inAppPurchasesNotSupported`
- `transactionProductUnknown`

#### Unknown
`NSError(domain: "iap-example", code: 123)`

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/542a989a-03cc-4bb7-bad6-d4e48edf1a3f

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift [hunk 1]
```diff
@@ -30,8 +30,9 @@ enum PrePurchaseError: Error {
 }
 
 enum PurchaseUpgradeError {
-    case inAppPurchaseFailed(WooWPComPlan)
-    case planActivationFailed
+    case inAppPurchaseFailed(WooWPComPlan, InAppPurchaseStore.Errors)
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift:33]: TIL we can pass more than one associated type 💯  

Not now, but I'm wondering if we should think of refactoring the different enums here in some sort of Result type like: `InAppPurchaseResult<WooWPComPlan, InAppPurchaseStore.Error>`, then update the `UpgradeViewState` based on the result case we get back.

**Review by iamgabrielma — APPROVED** [review]
LGTM! :shipit:

File: WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift:33]: Maybe? We won't always have a "result" per se though. The view state declares all the... states the view can be in. 

Not all of those states would fit well in a `Result`, since several are intermediate states. Having all the view states in a single enum means we can switch over it in one place and be sure that we're covering all the cases, without any confusion over shared state.

Comment (joshheald) [reply WooCommerce/Classes/ViewModels/InAppPurchases/UpgradesViewModel.swift:33]: In this case, we need both the `WooWPComPlan` and the error, and a result would only give you one of them.
