### PR TITLE
Make reviewer_avatar_urls optional

### LINKED ISSUE #1917: Reviews sometimes fails to load
## Describe the bug

The app sometimes cannot load reviews. 

## To Reproduce

Refs 2736767-zen, C6H8C3G23/p1582797389043700-slack. 

Reproduction steps are currently unknown. We only have this log:

```
2020/02/24 07:23:56:181 <> Mapping Error: keyNotFound(CodingKeys(stringValue: "reviewer_avatar_urls", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "Cannot get KeyedDecodingContainer<CodingKeys> -- no value found for key CodingKeys(stringValue: \"reviewer_avatar_urls\", intValue: nil) (\"reviewer_avatar_urls\")", underlyingError: nil))
2020/02/24 07:23:56:181 :no_entry:️ Error synchronizing reviews: keyNotFound(CodingKeys(stringValue: "reviewer_avatar_urls", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "Cannot get KeyedDecodingContainer<CodingKeys> -- no value found for key CodingKeys(stringValue: \"reviewer_avatar_urls\", intValue: nil) (\"reviewer_avatar_urls\")", underlyingError: nil))
2020/02/24 07:23:56:193 :large_blue_circle: Tracked reviews_load_failed, properties: [AnyHashable("is_wpcom_store"): false, AnyHashable("error_code"): "4865", AnyHashable("error_domain"): "NSCocoaErrorDomain", AnyHashable("error_description"): "Error Domain=NSCocoaErrorDomain Code=4865 \"Cannot get KeyedDecodingContainer<CodingKeys> -- no value found for key CodingKeys(stringValue: \"reviewer_avatar_urls\", intValue: nil) (\"reviewer_avatar_urls\")\" UserInfo={NSDebugDescription=Cannot get KeyedDecodingContainer<CodingKeys> -- no value found for key CodingKeys(stringValue: \"reviewer_avatar_urls\", intValue: nil) (\"reviewer_avatar_urls\"), NSCodingPath=(\n \"CodingKeys(stringValue: \\\"data\\\", intValue: nil)\",\n \"_JSONKey(stringValue: \\\"Index 0\\\", intValue: 0)\"\n)}", AnyHashable("blog_id"): 173129846]
```

## Expected behavior

Reviews should load.

## Isolating the problem (mark completed items with an [x]):
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

## Mobile Environment
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

## WordPress Environment
<details>
```
### WordPress Environment ###

WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14-6+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.28-31-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wp_
Total Database Size: 472.29MB
Database Data Size: 284.53MB
Database Index Size: 187.76MB
wp_woocommerce_sessions: Data: 9.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 51.56MB + Index: 23.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 7.13MB + Index: 11.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 5.11MB + Index: 5.08MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aepc_custom_audiences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aepc_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_bwf_actions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_bwf_action_claim: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bwf_contact: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_bwf_wc_customers: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 4.52MB + Index: 2.80MB + Engine InnoDB
wp_comments: Data: 25.55MB + Index: 18.84MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.47MB + Index: 0.83MB + Engine InnoDB
wp_followup_customer_carts: Data: 3.20MB + Index: 0.44MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_followup_email_orders: Data: 8.52MB + Index: 0.59MB + Engine InnoDB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
wp_followup_order_items: Data: 1.52MB + Index: 4.48MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ks_giveaways_contestant: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_ks_giveaways_entry: Data: 0.14MB + Index: 0.41MB + Engine InnoDB
wp_ks_giveaways_winner: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_login_redirects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.36MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 108.64MB + Index: 88.09MB + Engine InnoDB
wp_posts: Data: 18.52MB + Index: 12.72MB + Engine InnoDB
wp_posts_backup: Data: 0.31MB + Index: 0.09MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.08MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 11.52MB + Index: 10.03MB + Engine InnoDB
wp_users: Data: 0.41MB + Index: 0.42MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.16MB + Index: 0.39MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_meta: Data: 11.39MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 2
acf-field: 3
acf-field-group: 2
attachment: 660
authnet_credit_card: 200
customize_changeset: 5
custom_css: 1
feedback: 1
follow_up_email: 3
ks_giveaway: 2
nav_menu_item: 44
oembed_cache: 2
page: 36
post: 77
product: 154
product_variation: 582
revision: 21
shop_coupon: 105
shop_order: 17832
shop_order_refund: 40
shop_subscription: 360
vc4_templates: 2
was: 1
wc_order_email: 1
wc_order_status: 7
wfob_bump: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

Advanced Custom Fields: by Elliot Condon – 5.8.7
Akismet Anti-Spam: by Automattic – 4.1.3
API KEY for Google Maps: by GeoDirectory – 1.2.0
Appmaker – Convert WooCommerce to Android & iOS Native Mobile Apps: by Appmaker – 1.21.0 – Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Easy Social Share Buttons for WordPress: by CreoApps – 6.2.9
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Smash Balloon Instagram Feed: by Smash Balloon – 2.1.5
Interact Quiz Embed: by The Quiz Collective Inc. – 3.0.7
Jetpack by WordPress.com: by Automattic – 8.2.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
KingSumo Giveaways: by KingSumo – 1.8.2
LiveChat WooCommerce: by LiveChat – 1.5.1 – Not tested with the active version of WooCommerce
Mailchimp for WooCommerce: by Mailchimp – 2.3.1 – Not tested with the active version of WooCommerce
Maintenance Switch: by Fugu – 1.5.2
Peter's Login Redirect: by Peter Keung – 2.9.4
Slider Revolution: by ThemePunch – 6.1.7
Compress JPEG & PNG images: by TinyPNG – 3.2.1
User Switching: by John Blackbourn & contributors – 1.5.3
WEBDOGS Support: by WEBDOGS Support Team – 1.3.6
Wisepops: by Wisepops – 1.2.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.1 – Not tested with the active version of WooCommerce
Product Feed PRO for WooCommerce: by AdTribes.io – 7.2.8 – Not tested with the active version of WooCommerce
WooCommerce Address Validation: by SkyVerge – 2.6.2
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.13 – Not tested with the active version of WooCommerce
WooCommerce Cart Notices: by SkyVerge – 1.11.1
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.2 – 1.7.4 is available
Follow-Up Emails: by WooCommerce – 4.8.22 – 4.8.25 is available
WooCommerce Free Gift Coupons: by Kathy Darling – 2.4.2 – Not tested with the active version of WooCommerce
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.1.3 – 3.2.1 is available
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.8
WooCommerce Header Category Image: by Get Bowtied – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by SkyVerge – 1.11.2 – 1.11.3 is available
WooCommerce Product Reviews Pro: by SkyVerge – 1.15.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.31 – 4.1.32 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions - Preserve Billing Schedule: by Prospress Inc. – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by WooCommerce – 3.0.1
WooCommerce: by Automattic – 3.9.1 – 3.9.2 is available
OrderBumps: WooCommerce Checkout Offers: by WooFunnels – 1.8.0 – Not tested with the active version of WooCommerce
WooSwipe: by Thrive Website Design – 1.1.6.8
Yoast SEO: by Team Yoast – 12.9.1
WP Rocket: by WP Media – 3.4.4
Yoast SEO: WooCommerce: by Team Yoast – 12.4.1

### Inactive Plugins (0) ###


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php
object-cache.php: Memcached Redux

### Must Use Plugins (4) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
WP Engine Seamless Login Plugin: by WP Engine – 1.5.1
WP Engine Security Auditor: by wpengine – 1.0.8
WP Engine System: by WP Engine – 3.2.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #18 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: houseofcoffee Child Theme
Version: 1.1
Author URL: http:%20//www.none.com/
Child Theme: ✔
Parent Theme Name: houseofcoffee
Parent Theme Version: 1.3.3
Parent Theme Author URL: http://www.none.com/
WooCommerce Support: ✔

### Templates ###

Overrides: houseofcoffee-child/woocommerce/archive-product.php
houseofcoffee-child/woocommerce/cart/cart-empty.php
houseofcoffee-child/woocommerce/cart/cart-totals.php
houseofcoffee-child/woocommerce/cart/cart.php
houseofcoffee-child/woocommerce/cart/cross-sells.php
houseofcoffee-child/woocommerce/checkout/form-checkout.php
houseofcoffee-child/woocommerce/checkout/form-coupon.php
houseofcoffee-child/woocommerce/content-product.php
houseofcoffee-child/woocommerce/content-single-product.php
houseofcoffee-child/woocommerce/emails/admin-new-order.php
houseofcoffee-child/woocommerce/global/breadcrumb.php
houseofcoffee-child/woocommerce/global/sidebar.php
houseofcoffee-child/woocommerce/global/wrapper-end.php
houseofcoffee-child/woocommerce/global/wrapper-start.php
houseofcoffee-child/woocommerce/loop/loop-end.php
houseofcoffee-child/woocommerce/loop/loop-start.php
houseofcoffee-child/woocommerce/loop/no-products-found.php
houseofcoffee-child/woocommerce/loop/orderby.php
houseofcoffee-child/woocommerce/myaccount/form-edit-account.php
houseofcoffee-child/woocommerce/myaccount/form-login.php
houseofcoffee-child/woocommerce/myaccount/form-lost-password.php
houseofcoffee-child/woocommerce/myaccount/my-address.php
houseofcoffee-child/woocommerce/myaccount/my-orders.php
houseofcoffee-child/woocommerce/order/form-tracking.php
houseofcoffee-child/woocommerce/order/order-details.php
houseofcoffee-child/woocommerce/single-product/add-to-cart/external.php
houseofcoffee-child/woocommerce/single-product/meta.php
houseofcoffee-child/woocommerce/single-product/related.php
houseofcoffee-child/woocommerce/single-product/review.php
houseofcoffee-child/woocommerce/single-product/short-description.php
houseofcoffee-child/woocommerce/single-product/tabs/additional-information.php
houseofcoffee-child/woocommerce/single-product/tabs/description.php
houseofcoffee-child/woocommerce/single-product/tabs/tabs.php
houseofcoffee-child/woocommerce/single-product/title.php
houseofcoffee-child/woocommerce/single-product/up-sells.php
houseofcoffee-child/woocommerce/single-product-reviews.php
houseofcoffee-child/woocommerce/single-product.php


### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://henryshouseofcoffee.com
Subscriptions Template Theme Overrides: houseofcoffee-child/woocommerce/checkout/recurring-totals.phpversion 2.0 is out of date. The core version is 2.6.0
houseofcoffee-child/woocommerce/myaccount/subscription-details.phpversion 2.2.19 is out of date. The core version is 2.6.5						❌ Learn how to update

Subscription Statuses: wc-active: 92
wc-expired: 183
wc-pending-cancel: 2
wc-pending: 6
wc-on-hold: 24
wc-cancelled: 53

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: wc-active: 1
wc-expired: 1
wc-cancelled: 8
wc-expired: 61
wc-on-hold: 6
wc-pending: 4

Authorize.Net Credit Card: wc-active: 3
wc-cancelled: 29
wc-expired: 86
wc-on-hold: 10

Stripe: wc-active: 82
wc-cancelled: 15
wc-expired: 34
wc-on-hold: 8
wc-pending: 2
wc-pending-cancel: 2


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

Authorize.Net Credit Card: products
card_types
payment_form
inline
lightbox
tokenization
token_editor
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
apple_pay
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin

PayPal: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log
Webhooks Enabled: ❌
						No signature key configured

### Address Validation ###

Active Provider: Loqate
Configured: ✔
Validate international addresses: No
Debug Mode: No
Geocode Addresses: No
Classify Addresses: No
Force Customer to look-up address via Postcode: No

### Action Scheduler ###

Canceled: 60
Oldest: 2020-02-01 02:06:07 -0800
Newest: 2021-01-01 03:00:00 -0800

Complete: 5,985
Oldest: 2020-01-22 09:58:47 -0800
Newest: 2020-02-22 13:34:00 -0800

Failed: 7
Oldest: 2018-11-01 03:00:00 -0700
Newest: 2019-01-01 03:00:00 -0800

Pending: 235
Oldest: 2020-02-22 22:31:24 -0800
Newest: 2021-02-19 11:00:00 -0800
```
</details>

### PR DESCRIPTION
**Pull request by shiki**
Fixes #1917

### How

As described in #1917, we could not find the cause of why `reviewer_avatar_urls` is `null` in the JSON response. We will fix it by making `Networking.ProductReview.reviewerAvatarURLs` for now. 

### Storage <> Networking

Luckily, the Core Data `ProductReviews.reviewerAvatarURL` is **Optional** so we don't need to do any migration. This was odd too, because Networking's `reviewerAvatarURL` **is not** optional while Storage's `reviewerAvatarURL` **is** optional. ¯\\\_(ツ)\_/¯

## Solution

The main change is utilizing `decodeIfPresent` so that the avatar URLs object will not be parsed if the key is not there or if it's `null`. 

https://github.com/woocommerce/woocommerce-ios/blob/b30443f70eca4dcc1e310b46e25506063ea63f65/Networking/Networking/Model/Product/ProductReview.swift#L68

### Fetching

I then added a test that proves that if the response has no `reviewer_avatar_urls` or its value is `null`, the app will still parse the object. 

https://github.com/woocommerce/woocommerce-ios/blob/b30443f70eca4dcc1e310b46e25506063ea63f65/Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift#L85-L111

If you follow the commits, this test was failing before I fixed it. TDD FTW! 

### Saving in Core Data

I then added a test that this `ProductReview` can be saved in Core Data:

https://github.com/woocommerce/woocommerce-ios/blob/b30443f70eca4dcc1e310b46e25506063ea63f65/Yosemite/YosemiteTests/Stores/ProductReviewStoreTests.swift#L125-L153

## Testing

This is tricky to test so I propose the following.

### Test for Regression

1. Navigate to Reviews
2. Tap on any review. 
3. Confirm that the Gravatar URL is still shown.

### Test Dummy Scenario

Edit this part so that `gravatarURL` is always `nil`:

https://github.com/woocommerce/woocommerce-ios/blob/b30443f70eca4dcc1e310b46e25506063ea63f65/WooCommerce/Classes/ViewRelated/Notifications/ReviewDetailsViewController.swift#L348-L353

1. Navigate to Reviews
2. Tap on any review. 
3. Confirm that a placeholder image is shown.

### Unit Test

Scrutinize the unit test. Am I testing the correct scenarios? 

## Reviewing 

Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift [hunk 1]
```diff
@@ -8,57 +8,107 @@ final class ProductReviewsRemoteTests: XCTestCase {
...
-            XCTAssertNotNil(error)
+            result = (reviews, error)
             expectation.fulfill()
         }
 
         wait(for: [expectation], timeout: Constants.expectationTimeout)
+
+        // Then
+        XCTAssertNil(result.reviews)
+        XCTAssertNotNil(result.error)
```
Comment (shiki) [inline Networking/NetworkingTests/Remote/ProductReviewsRemoteTests.swift]: I accidentally modified this to use Given/When/Then when I really wanted to modify `testLoadAllProductReviewsProperlyReturnsParsedProductReviews` (above). I kept it anyway. ¯\\\_(ツ)\_/¯

**Comment by shiki** [comment]
Thanks, @pmusolino!
