### PR TITLE
[Mobile Payments] Only show IPP announcement if it's supported in the store's country

### LINKED ISSUE #7768: [Mobile Payments] Feature is promoted in orders even for countries where it's not available
**Describe the bug**

The new "Accept payments easily" banner in the orders list is visible even if the store isn't in a supported country

**To Reproduce**
1. Using a fresh install of the app, log in to a store in a country that doesn't support IPP (e.g. Spain)
2. Go to orders
3. See the banner promoting the IPP feature (I think it's only visible if there is at least one order)
4. Tapping on Purchase Card Reader sends you to a form to register interest

**Screenshots**

**Expected behavior**
The banner should only appear for stores in a country that supports IPP

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 15.5 (also seen on 16)
- WooCommerce iOS version: 10.4.0.2

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by koke**
Closes: #7768 

### Description

Previously, we were showing the promotion for In-Person Payments on top of the orders list, even if the store was in a country where we don't support In-Person Payments. With this PR, this banner should only appear in stores from US and Canada.

### Testing instructions

Go to orders list:
- If the store is in the US or Canada, there should be a banner promoting In-Person Payments (as long as you haven't dismissed it before)
- If the store is in any other country, there should be no In-Person Payments banner

### Screenshots

Before|After
-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-09-27 at 10 28 33|Simulator Screen Shot - iPhone 14 Pro - 2022-09-27 at 10 29 34

---

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift [hunk 1]
```diff
@@ -293,18 +293,21 @@ extension OrderListViewModel {
...
         Publishers.CombineLatest3(errorState, $hideOrdersBanners, upsellCardReadersAnnouncementViewModel.$shouldBeVisible)
             .map { hasError, hasDismissedOrdersBanners, upsellCardReadersBannerShouldBeVisible  -> TopBanner in
 
-                guard !hasError else {
+                if hasError {
                     return .error
                 }
 
-                guard !upsellCardReadersBannerShouldBeVisible else {
+                if upsellCardReadersBannerShouldBeVisible && isSupportedCountryForCPP {
```
Comment (toupper) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift]: Non a blocker; `upsellCardReadersBannerShouldBeVisible` naming seems a bit confusing now that we added the new condition (the country is supported for CPP), as this is also part of whether the banner should be visible or not. Something like `upsellCardReadersBannerWasDismissed` is more meaningful in my opinion:

`let upsellCardReadersBannerShouldBeVisible = !upsellCardReadersBannerWasDismissed && isSupportedCountryForCPP`

**Review by toupper — APPROVED** [review]

**Comment by toupper** [comment]
Nice addition! Code is good and tests well, I just added a small suggestion :shipit:

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift (hunk 1 above)
Comment (koke) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift]: I don't think I can turn the meaning around to `wasDismissed` since it comes from the generic `FeatureAnnouncementCardViewModel`. I guess I could do `upsellCardReadersAnnouncementViewModel.$shouldBeVisible.map(!)` but it doesn't seem very readable 😅 

What do you think about `upsellCardReadersBannerAvailable`?

Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift]: > I don't think I can turn the meaning around to wasDismissed since it comes from the generic FeatureAnnouncementCardViewModel. I guess I could do upsellCardReadersAnnouncementViewModel.$shouldBeVisible.map(!) but it doesn't seem very readable 😅

Yeah, that's a good point :) Now that you mention it, perhaps the CPP country availability check should be included in the `FeatureAnnouncementCardViewModel`, or do we want to only check it for orders and not other places such as the Payment Methods Screen? Otherwise `upsellCardReadersBannerAvailable` is a good option 😃

Comment (koke) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift]: Oh I hadn't realized we were showing the upsell in more than one place. In that case, we might want to move the check to `FeatureAnnouncementCardViewModel`. But maybe this is a good start and we can revisit that in another PR 🤷🏽‍♂️

Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift]: Sure 👍
