### PR TITLE
Order Creation: Disable selection for bookable products

### LINKED ISSUE #12318: Bookable products available via in-app order creation but treated as simple products
**Describe the bug**
When a bookable product created via [WooCommerce Bookings](https://woo.com/products/woocommerce-bookings/?aff=10486&cid=1131038) is available for purchase, the in-app order creation allows the mobile user to add this product to an order.

However, when this type of product is added to an order in-app, all of the important details (e.g., resource, date, time) are not available options to choose from. It can still be added to the order, but:
- It will be added at the lowest possible value.
- Any specific details are not available.
- No booking is created and associated with the order.

As a result, a bookable product is treated like a simple product if it is added to an order in-app.

**To Reproduce**
1. Install and activate [WooCommerce Bookings](https://woo.com/products/woocommerce-bookings/?aff=10486&cid=1131038).
2. Create a new product.
3. Use the "Hair Salon" template available in Bookings.
4. Publish the product.
5. Create a new order in the Woo Mobile App.
6. Add the product published in step 4.
7. You will not be prompted for any additional details.
8. Proceed through the purchase flow via any payment method (e.g., cash).
9. Complete the order.
10. Navigate to the edit order page for the order placed in step 9.
11. The order will be placed, but it is not associated with a booking.
12. Navigate to **wp-admin > Bookings > All Bookings**.
13. Note that there is no booking associated with the order placed in step 9.

**Screenshots**
CleanShot 2024-03-19 at 17 46 45@2x

CleanShot 2024-03-19 at 17 47 57@2x

IMG_8799BE1F999E-1

CleanShot 2024-03-19 at 17 49 11@2x

CleanShot 2024-03-19 at 17 49 36@2x

**Expected behavior**
WooCommerce Bookings is not currently compatible with in-app order creation. As a result, the expectation is either: 
1. Bookable products remain incompatible and they should not be able to be added to an order in-app.
2. Bookable products become compatible and adding one to an order will prompt the user for additional information (e.g., resources, persons, etc.) and create the booking in wp-admin.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 Mini
- iOS version: 17.3.1
- WooCommerce iOS version: 8.7.0.11

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://testingwoopayments.com
Site address (URL): https://testingwoopayments.com
WC Version: 8.7.0.11
REST API Version: ✔ 8.7.0.11
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.16
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.6.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0.20
WC Database Prefix: wp_
Total Database Size: 136.34MB
Database Data Size: 76.52MB
Database Index Size: 59.82MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.34MB + Index: 0.39MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.30MB + Index: 0.22MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.27MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 16.55MB + Index: 20.06MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.77MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.45MB + Index: 0.41MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.30MB + Index: 0.39MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_contacts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_customfields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_externalsources: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tags_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 2.02MB + Index: 0.61MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 1.30MB + Index: 0.42MB + Engine InnoDB
__wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_commentmeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.45MB + Index: 0.38MB + Engine InnoDB
__wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
__wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 3.05MB + Index: 1.08MB + Engine InnoDB
__wp_postmeta: Data: 15.34MB + Index: 18.98MB + Engine InnoDB
__wp_posts: Data: 2.47MB + Index: 0.67MB + Engine InnoDB
__wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
__wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
__wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_orders: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
__wp_wc_orders_meta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
__wp_wc_order_addresses: Data: 0.13MB + Index: 0.22MB + Engine InnoDB
__wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_operational_data: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.41MB + Index: 0.34MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wpml_mails: Data: 5.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2429
bookable_resource: 4
customize_changeset: 70
custom_css: 1
elementor_library: 1
jetpack_migration: 2
nav_menu_item: 6
page: 10
post: 2
product: 958
product_variation: 15
revision: 56
shop_coupon: 3
shop_order: 715
shop_order_refund: 32
shop_subscription: 39
wp_global_styles: 15
wp_navigation: 1
wp_template: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Jetpack: by Automattic – 13.3-a.5
WooCommerce: by Automattic – 8.7.0.11
WooCommerce Bookings: by WooCommerce – 2.1.0
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 7.3.0

### Inactive Plugins (6) ###

Code Snippets: by Code Snippets Pro – 3.6.4
Jetpack Beta Tester: by Automattic – 4.0.0
WooCommerce Canada Post Shipping: by WooCommerce – 2.9.1
WooCommerce Shipping & Tax: by WooCommerce – 2.5.1 (update to version 2.5.3 is available)
Woo Subscriptions: by WooCommerce – 6.0.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 6 MB

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: #355 - /posts/

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.3.0
Connected to WPCOM: Yes
WPCOM Blog ID: 210545187
Account ID: acct_1LhhVSFk5Ng3VVfB
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card,klarna,afterpay_clearpay
WooPay: Enabled (checkout,product,cart)
WooPay Incompatible Extensions: Yes
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: advanced
Enabled Fraud Filters: AVS Verification
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-20 22:44:19 -05:00
Options: ✔
Notes: 170
Onboarding: completed

### Action Scheduler ###

Complete: 107
Oldest: 2024-02-17 20:13:37 -0600
Newest: 2024-03-19 17:48:56 -0500

Pending: 3
Oldest: 2024-03-19 17:52:17 -0500
Newest: 2024-04-18 17:32:57 -0500

Failed: 871
Oldest: 2022-11-23 19:01:59 -0600
Newest: 2024-02-13 16:59:50 -0600

Canceled: 1
Oldest: 2024-03-05 14:15:27 -0600
Newest: 2024-03-05 14:15:27 -0600


### Status report information ###

Generated at: 2024-03-19 17:52:01 -05:00
`
```
</details>

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #12318 

## Description

Currently, we haven't yet supported bookable products on Woo iOS. However, those products are still selectable from order creation, and orders created with them are not associated with any booking like they should be.

This PR fixes this by disabling bookable products on the product selector for order creation.

Changes include:
- Added new product type `booking` and display it as "Bookable product" following Woo Core.
- Moved `ProductSelector.Source` to a separate enum `ProductSelectorSource` and inject it to `ProductSelectorViewModel`. All calls to `ProductSelectorView` and its view model were updated accordingly.
- Updated selected state for `ProductRow` for bookable products in order form to be `unsupported` and inject unsupported reason to `ProductRowViewModel`.
- Updated the UI for `ProductRow` with `unsupported` state and reason.
- Also: updated the item detail in Order Edit form for bookable products to display order item price instead of product price since the bookable product price usually include more costs depending on the associated bookings.

## Steps to reproduce

- Install and activate [WooCommerce Bookings](https://woo.com/products/woocommerce-bookings/?aff=10486&cid=1131038).
- Create a new product.
- Use the "Hair Salon" template available in Bookings.
- Publish the product.
- Build and run the app.
- Navigate to the Orders tab and tap "+" to add a new order.
- Select Add product and find the new bookable product.
- Confirm that the product cannot be selected for order creation.
- Test other flows with the product selector: order filter / Blaze / coupons. Confirm that bookable products are still selectable in these flows.
- Create a booking on the web. Check the order on the app and tap Edit. Confirm that the order item displays the correct price.

## Screenshots

Light mode | Dark mode | Edit Order
--- | --- | ---
 |  | 

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift [hunk 1]
```diff
@@ -261,6 +270,9 @@ final class ProductRowViewModel: ObservableObject, Identifiable {
     ///
     @Published var quantity: Decimal
 
+    /// Text explaining why the product is not supported for order creation if that's the case.
+    private let unsupportedReason: String?
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift]: Instead of storing it here, is it possible to make this in an associate value in the `unsupported` case of `ProductRow.SelectedState` enum? 

We could also add helper computed properties to `ProductRow.SelectedState` for further calculations.

**Review by selanthiraiyan — APPROVED** [review]
Nice work, Huong! This works great. 🎉 I left a non-blocking suggestion about the code.

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift (hunk 1 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift]: That's a good idea! I added the changes as you suggested in a33de2035e9f2f4451dcb9cb855bd7e22de19441, please feel free to take another look when you can 🙇

Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift]: Thanks for the updates, Huong! The changes look good to me. 🚀

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/210">19.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
