### PR TITLE
[Tablet Orders] Fix deeplink to Order Details when SplitViewOrders is enabled

### LINKED ISSUE #11674: [Tablet Orders] Fix deeplink to Order Details when SplitViewOrders is enabled
When the `splitViewInOrdersTab` feature flag is enabled, Universal URLs such as `https://woo.com/mobile/orders/details?blog_id={id}&order_id={id}` only navigate to the Orders tab, but don't open the specific order.

This also affects order notifications, both displayed as a Notice in the app, or as a system notification when backgrounded.

The routing in MainTabViewController needs to be updated to take account of the WooTabContainerController use for the split view, rather than expecting a navigation controller as the container. See #11673 for context.

## Subtasks

- [x] Handle universal links in `OrdersSplitViewWrapperController` https://github.com/woocommerce/woocommerce-ios/pull/11718

### Split view specific issues

The following issues only happen when the split view is shown (two panes).

- [ ] Fix an issue where deep deep-linked order is overridden by the auto-selected order in `OrderListViewController.checkSelectedItem` in `viewWillAppear`

Repro steps:

- Prepare an order link in a separate app
- Switch to a different store from the store ID in the link
- Tap on an order universal link --> notice that the first order of the store is shown instead of the order ID in the link

https://github.com/woocommerce/woocommerce-ios/assets/1945542/7fecc721-3e80-470e-b0e7-abe1b945058e

- [x] Fix the order not appearing as selected in the primary view (order list) https://github.com/woocommerce/woocommerce-ios/pull/11729

Notice that the order ID in the two views do not match.

### PR DESCRIPTION
**Pull request by jaclync**
Part of #11674 

⚠️ Please notice there are two related known issues in https://github.com/woocommerce/woocommerce-ios/issues/11674

## Why

Based on the description in #11674:

> When the `splitViewInOrdersTab` feature flag is enabled, Universal URLs such as `https://woo.com/mobile/orders/details?blog_id={id}&order_id={id}` only navigate to the Orders tab, but don't open the specific order. This also affects order notifications, both displayed as a Notice in the app, or as a system notification when backgrounded.

This is because the orders tab's root view controller is now `TabContainerController` and not `UINavigationController` (with `OrdersRootViewController` as the top view controller) anymore with the split view support. When receiving the order universal link in `OrderDetailsRoute.perform`, it calls `MainTabBarController.navigateToOrderDetails` to:
1. Switch to the target store if it's different from the current store
2. Switch to the orders tab: this logic previously assumes the orders tab's root view controller to be `UINavigationController` instead of `TabContainerController`
3. Present the order details: this logic previously assumes the orders tab's root view controller to be `OrdersSplitViewWrapperController` instead of `TabContainerController`

## How

To fix the issue from the outdated assumption of the view controller type:

- Switch to the orders tab: this logic was updated in `MainTabBarController.navigateToTabWithNavigationController` (renamed to `navigateToTabWithNavigationController`) to call the completion block not only for `UINavigationController` tab root view controller but also any `UIViewController`. It now returns `UIViewController` in the completion block. This requires updating `DashboardViewController.startAddProductFlowFromProductDescriptionAIModal` to cast the view controller to `UINavigationController` because `AddProductCoordinator` expects the source view controller to be `UINavigationController` and it takes many diffs to fix this assumption. We can tackle this when we implement split view support for the products tab
- Present the order details: this logic was updated in `MainTabBarController.presentDetails` to get `OrdersSplitViewWrapperController` (which can present the order details) from the root `TabContainerController`. The same change was applied to the order notification tap handling. I tried adding some test cases for it to ensure the order universal link behavior, though the static usage makes it quite tricky. Lemme know if the test cases are too hacky 😬 

## Testing instructions

- [x] @jaclync tests that order deep links work as before when `splitViewInOrdersTab` feature flag is off
- [x] @jaclync tests that adding product from the AI modal works as before
- [x] @jaclync tests that tapping on a new order push notification opens the app, switches to the store, and opens the order

Hand-testing is optional, as I can reproduce the issue before and it's straightforward to verify.

- In code, update `splitViewInOrdersTab` feature flag to return `true` in `DefaultFeatureFlagService`
- In another app, paste an order URL that can deep link to the app (`https://woo.com/mobile/orders/details?blog_id={id}&order_id={id}`)
- In the app, switch to a different store from the store in the URL in the previous step
- Background the app
- Tap on the order URL --> it should deep link to the app, switch to the store in the URL, then open the order details for the order ID in the URL

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/181">17.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bozidarsevo** [comment]
> * Tap on the order URL --> it should deep link to the app, switch to the store in the URL, then open the order details for the order ID in the URL

I tested it and it opens a correct order but the one selected on the left is wrong (first in the list), since you will be AFK few days, I can take a look?

Simulator Screenshot - iPad Pro (11-inch) (4th generation) - 2024-01-18 at 12 05 56

**Comment by jaclync** [comment]
> I tested it and it opens a correct order but the one selected on the left is wrong (first in the list), since you will be AFK few days, I can take a look?

Yup, this is the second known issue in the "Split view specific issues" in https://github.com/woocommerce/woocommerce-ios/issues/11674. The linked order ID might not exist in the order list yet (not all orders are fetched at once as they're paginated), I think we can simply unselect the order on the left side (the order list) so that it doesn't look inconsistent.

**Review by joshheald — APPROVED** [review]
Works well, and thanks for flagging the known issues.

This PR covers a lot of the use cases for deep links, but we likely do need to fix the first known issue you raised before we ship: 
- "issue where deep deep-linked order is overridden by the auto-selected order in OrderListViewController.checkSelectedItem in viewWillAppear"

The second is less urgent, but also probably easier to fix.

Thanks for the improvement here!

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift [hunk 1]
```diff
@@ -487,8 +487,12 @@ private extension DashboardViewController {
 
     /// Starts the Add Product flow to showcase the product description AI feature.
     private func startAddProductFlowFromProductDescriptionAIModal() {
-        AppDelegate.shared.tabBarController?.navigateToTabWithNavigationController(.products, animated: true) { [weak self] navigationController in
+        AppDelegate.shared.tabBarController?.navigateToTabWithViewController(.products, animated: true) { [weak self] tabViewController in
             guard let self else { return }
+            guard let navigationController = tabViewController as? UINavigationController else {
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift:492]: Nice guard rails and reminder for a future engineer 👍

File: WooCommerce/Classes/ViewRelated/MainTabBarController.swift [hunk 2]
```diff
@@ -444,12 +450,20 @@ extension MainTabBarController {
 
     private static func presentDetails(for orderID: Int64, siteID: Int64) {
         if ServiceLocator.featureFlagService.isFeatureFlagEnabled(.splitViewInOrdersTab) {
-            (childViewController() as? OrdersSplitViewWrapperController)?.presentDetails(for: orderID, siteID: siteID)
+            ordersTabSplitViewWrapper()?.presentDetails(for: orderID, siteID: siteID)
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/MainTabBarController.swift:453]: As part of a fix for one/both of the known issues, we could have `OrdersSplitViewWrapperController.presentDetails(for:[, siteID:])` delegate to the corresponding method on `OrdersRootViewController`. 

That way, we:
1. remove some duplication
2. can co-ordinate changes to the list and the presented order simultaneously.

**Comment by joshheald** [comment]
> > * Tap on the order URL --> it should deep link to the app, switch to the store in the URL, then open the order details for the order ID in the URL
> 
> I tested it and it opens a correct order but the one selected on the left is wrong (first in the list), since you will be AFK few days, I can take a look?

@bozidarsevo can we merge this PR and if you're continuing to work on the selection do that on a new branch? I don't want to mess up your workflow, so just checking.

**Comment by bozidarsevo** [comment]
> > > * Tap on the order URL --> it should deep link to the app, switch to the store in the URL, then open the order details for the order ID in the URL
> > 
> > 
> > I tested it and it opens a correct order but the one selected on the left is wrong (first in the list), since you will be AFK few days, I can take a look?
> 
> @bozidarsevo can we merge this PR and if you're continuing to work on the selection do that on a new branch? I don't want to mess up your workflow, so just checking.

Sure!
