### PR TITLE
Fixes issue where products filter bar dissapears

### LINKED ISSUE #2720: [IAFeedback] Dismissing Product Banner also dismisses the Product filters
To reproduce:

1. Delete the app from the device.
2. Run and navigate to Products.
3. Tap on Give Feedback. 
4. Dismiss the survey URL.
5. Notice that the product filters are no longer visible. Only the list is visible.

### PR DESCRIPTION
**Pull request by Ecarrion**
fixes #2720 

# Why 

While trying to [dismiss the product banner](https://github.com/woocommerce/woocommerce-ios/pull/2686#issuecomment-678276742) I introduced a bug that hides the products filter bar as well 😇 

# How

- Do not `nil` the table header view when trying to dismiss the top banner
- Adjust the spacing of the outer container stack view(that serves as the header view for the table view) to be `0` when it does not have any top banner presented, to remove an unwanted separator space.

# Gif
Before | After
---- | ----
 | 

# Testing Steps
- Delete the app from the device.
- Run and navigate to Products.
- Tap on Give Feedback. 
- Dismiss the survey URL.
- Make sure that the products filter bar is still visible

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 1]
```diff
@@ -388,22 +388,28 @@ private extension ProductsViewController {
...
         topBannerView?.removeFromSuperview()
         topBannerView = nil
-        tableView.tableHeaderView = nil
+        updateTableHeaderView()
+    }
+
+    /// Updates table header view with the correct spacing / edges depending if `topBannerContainerView` is empty or not.
+    ///
+    func updateTableHeaderView() {
+        topStackView.spacing = topBannerContainerView.subviews.isNotEmpty ? 8 : 0
```
Comment (shiki) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Where do these magic numbers come from? I guess this is from this declaration right? 

https://github.com/woocommerce/woocommerce-ios/blob/1c0bb1cfbb3d99a4f42efc7aaadab1ab1d9f8d2a/WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift#L42

If so, should we consider moving `8` to a constant (enum)?

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift [hunk 2]
```diff
@@ -388,22 +388,28 @@ private extension ProductsViewController {
...
     func hideTopBannerView() {
         topBannerView?.removeFromSuperview()
         topBannerView = nil
-        tableView.tableHeaderView = nil
+        updateTableHeaderView()
+    }
+
+    /// Updates table header view with the correct spacing / edges depending if `topBannerContainerView` is empty or not.
+    ///
+    func updateTableHeaderView() {
```
Comment (shiki) [inline WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: Do you think `updateTableHeaderViewHeight` would be less ambiguous? 

```suggestion
    func updateTableHeaderViewHeight() {
```

**Review by shiki — APPROVED** [review]
LGTM! Thanks for fixing this. 

I just have a couple of nitpicks. 🙃

File: WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift (hunk 2 above)
Comment (Ecarrion) [reply WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: I had it like that, but since it does a little bit more than updating just the height I left it as `updateTableHeaderView()` I also had it as `updateTableHeaderViewHeightAndSpacing()` 🤔

Comment (shiki) [reply WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift]: I guess we can consider changing the spacing as changing the "height" too. 🤣 Anyway, up to you!
