### PR TITLE
Coupons: Fix incorrect expiry date check 

### LINKED ISSUE #6254: Coupons: Incorrect expiry date check due to timezone difference
### Description
The current expiry date check is incorrect at some specific hours of the day in GMT++ timezones.

### Steps to reproduce
- Make sure the timezone on your computer is ahead of GMT so that setting the next day as the coupon expiry date results in the same day in GMT time. E.g: 6 pm Feb 21 GMT+7. 
- Create a coupon for your test store (in WP Admin > Marketing > Coupons). Set the expiry date to the next day.
- Open the app and load the coupon list (Menu > Coupons). Notice that the created coupon is marked as Expired.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #6254 

### Description

This PR fixes an edge case when setting the expiry date to the next day in a timezone that is ahead of GMT.
To be more specific: in my case, I'm in GMT+7 timezone, so when I set the next day (Feb 22nd) as the expiry date, I get Feb 21st 17:00 as the expiry date in GMT time. When I test the coupon list in my PM (at 17:00 for example), my current date is also Feb 21st in GMT time, so the old expiry date check finds that I'm on the same day as the expiry date and decides that the coupon has expired.

The solution is to set the granularity of the check to `hour` instead of `day` as before. This makes sure that the check is always correct regardless of the timezone I'm in.

### Testing instructions

- Make sure the timezone on your computer is ahead of GMT so that setting the next day as the coupon expiry date results in the same day in GMT time. E.g: 6 pm Feb 21 GMT+7. 
- Create a coupon for your test store (in WP Admin > Marketing > Coupons). Set the expiry date to the next day.
- Open the app and load the coupon list (Menu > Coupons). Notice that the created coupon is still marked as Active.

### Screenshots

Before: 

https://user-images.githubusercontent.com/5533851/154949124-66061b8c-ba4e-43a8-b133-d3578c5c297c.mp4

After:

https://user-images.githubusercontent.com/5533851/154949179-7a18b41a-5f10-4d92-a6b7-45588f565526.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Model/Coupon+Woo.swift [hunk 1]
```diff
@@ -42,7 +42,8 @@ extension Coupon {
         var calendar = Calendar.current
         calendar.timeZone = gmtTimeZone
 
-        let result = calendar.compare(expiryDate, to: now, toGranularity: .day)
+        // Compare the dates by hour to get around edge cases of timezone differences.
+        let result = calendar.compare(expiryDate, to: now, toGranularity: .hour)
```
Comment (pmusolino) [inline WooCommerce/Classes/Model/Coupon+Woo.swift]: I believe that to include all the cases, we should compare by `minute` granularity because there are some time zones where there is also the half-hour or 45 minutes. For example, in India, the India Standard Time is +5:30, or in New Zealand, the time is UTC +12:45 / +13:45. WDYT?

Comment (itsmeichigo) [reply WooCommerce/Classes/Model/Coupon+Woo.swift]: Good point! TIL about the timezones with half hour 😅 Updated in ae0bf2d8091879aaf57227707e4f40edf9476f40

**Review by pmusolino — APPROVED** [review]
:shipit:
