### PR TITLE
[Backend Receipts] Analytics

### LINKED ISSUE #11856: [Backend Receipts] Analytics
Ref: pfoUAQ-cg-p2

- Update `receipt_*` events with `source: backend | local`
- For the cases when downloading/creating/sharing a receipt fails, use the same `receipt_email_failed` error with `error_description: error_type` props
- We need to track cases when fetching a receipt URL from the backend fails: `receipt_url_fetching_fails` with appropriate `error_description: error_type` that comes from the backend as an error

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes #11856
Its better if we review/merge https://github.com/woocommerce/woocommerce-ios/issues/11829 first, but not a blocker.

## Description
This PR updates analytics for receipt-related events. Now they'll track an additional property `source: local | backend` depending if is generated locally or from the backend.

## Changes:
* Adds "source" property to receipt events. This property will mark the event source as `local` if we're dealing with a legacy receipt, or `backend` if is a backend-generated receipt.
* Updates some of the existing properties to be optional, since we may have no `CountryCode` or when a receipt is generated via a non-card present method.

## Testing instructions
There's no need to test all cases, since some flows might require a bit of setup (eg: The print button is only enabled if you use the printer simulator from Xcode additional tools, but sharing is enabled by default), just go through the receipts flow, attempt to print/share, and observe that `source: local | backend` is logged. 

Examples of some flows that can be checked:
- With the feature flag on, print or share cash receipt.
```
Tracked receipt_print_success, properties: [AnyHashable("country"): "US", AnyHashable("is_wpcom_store"): false, AnyHashable("was_ecommerce_trial"): false, AnyHashable("source"): "local", AnyHashable("plan"): "jetpack_free", AnyHashable("blog_id"): 229034549, AnyHashable("store_id"): "59682e4b-5967-4a66-b8dc-831526e293b3", AnyHashable("site_url"): "https://loudly-silly-kid.jurassic.ninja"]
```
- With the feature flag on, share card present receipt.
```
Tracked receipt_email_success, properties: [AnyHashable("site_url"): "https://loudly-silly-kid.jurassic.ninja", AnyHashable("source"): "backend", AnyHashable("blog_id"): 229034549, AnyHashable("store_id"): "59682e4b-5967-4a66-b8dc-831526e293b3", AnyHashable("was_ecommerce_trial"): false, AnyHashable("plan"): "jetpack_free", AnyHashable("is_wpcom_store"): false]
```
- Cancelling printing tracks the event.
```
Tracked receipt_print_canceled, properties: [AnyHashable("was_ecommerce_trial"): false, AnyHashable("source"): "local", AnyHashable("plan"): "jetpack_free", AnyHashable("is_wpcom_store"): false, AnyHashable("blog_id"): 229034549, AnyHashable("country"): "US", AnyHashable("store_id"): "59682e4b-5967-4a66-b8dc-831526e293b3", AnyHashable("site_url"): "https://loudly-silly-kid.jurassic.ninja"]
```
- Forcing an error logs the error:
```
Tracked receipt_print_failed, properties: [AnyHashable("plan"): "jetpack_free", AnyHashable("is_wpcom_store"): false, AnyHashable("store_id"): "59682e4b-5967-4a66-b8dc-831526e293b3", AnyHashable("error_description"): "Error Domain= Code=0 \"(null)\"", AnyHashable("error_domain"): "", AnyHashable("was_ecommerce_trial"): false, AnyHashable("site_url"): "https://loudly-silly-kid.jurassic.ninja", AnyHashable("error_code"): "0", AnyHashable("source"): "backend", AnyHashable("blog_id"): 229034549]
```

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptViewController.swift [hunk 1]
```diff
@@ -51,15 +51,33 @@ final class ReceiptViewController: UIViewController {
...
+                ServiceLocator.analytics.track(event: .InPersonPayments.receiptEmailFailed(error: error, source: .backend))
+                DDLogError("Failed to share receipt for orderID \(String(describing: self?.viewModel.orderID)). Error: \(error)")
+            }
+            switch success {
+            case true:
+                ServiceLocator.analytics.track(event: .InPersonPayments.receiptEmailSuccess(countryCode: nil, cardReaderModel: nil, source: .backend))
+            case false:
+                ServiceLocator.analytics.track(event: .InPersonPayments.receiptEmailCanceled(countryCode: nil, cardReaderModel: nil, source: .backend))
+            }
+        }
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptViewController.swift:94]: When we track errors both in share and print actions, we'll also log the `success` or `completion` event. This is done on purpose to understand "recoverability": If an event failed, but then we tracked success on completion, the merchant could recover. If we track fail + !success then they couldn't.

File: WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift [hunk 2]
```diff
@@ -1385,6 +1385,7 @@ extension WooAnalyticsEvent {
             static let millisecondsSinceCardCollectPaymentFlow = "milliseconds_since_card_collect_payment_flow"
             static let siteID = "site_id"
             static let connectionType = "connection_type"
+            static let receiptSource = "source"
```
Comment (bozidarsevo) [inline WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift:1388]: regarding all the event names, parameter names, etc., is there a place where we keep documentation of all of it?

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptViewController.swift [hunk 3]
```diff
@@ -51,15 +51,33 @@ final class ReceiptViewController: UIViewController {
     }
 
     @objc private func shareReceipt() {
+        ServiceLocator.analytics.track(event: .InPersonPayments.receiptEmailTapped(countryCode: nil,
```
Comment (bozidarsevo) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptViewController.swift:75]: I see this is event that was here from before, but would maybe "receiptShareTapped" be a better name? Since we trigger share sheet and users can share it various ways/apps?

File: WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift:1388]: There was an spreadsheet, but this has been deprecated since was too much manual work and prone to error. At the moment we just see them under MC > Tracks > Events. There if you look for `woocommerceios_` you'll see all registered events and their properties.

Some context: p91TBi-aNE-p2

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptViewController.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptViewController.swift:75]: I agree with you, the name could be better. The reason we're using `receiptEmailTapped` here is because we're tracking the same `WooAnalyticsStat.receiptEmailTapped = "receipt_email_tapped"` case when tapping sharing or printing. Since we do this, we cannot create another case with a different name, since the raw value would still have to be "receipt_email_tapped", and the compiler doesn't allow it since the enum case is not unique.

**Review by bozidarsevo — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/185">17.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
