### PR TITLE
Use a Separate Ghost VC for TopPerformerDataViewController

### LINKED ISSUE #1711: Ghost-related crash in TopPerformerDataViewController → EXC_BREAKPOINT: crash in TopPerformerDataViewController
Sentry Issue: [WOOCOMMERCE-IOS-10](https://sentry.io/organizations/a8c/issues/1424905202/?referrer=github_integration)

```
EXC_BREAKPOINT: Exception 6, Code 15841252, Subcode 8
  File "TopPerformerDataViewController.swift", line 122, in TopPerformerDataViewController.displayGhostContent
  File "<compiler-generated>", in _ArrayBuffer._nativeTypeChecked.getter
  File "<compiler-generated>", in Array._getElement
  File "WooCommerce", in Array.subscript.getter
  File "TopPerformersViewController.swift", line 19, in TopPerformersViewController.visibleChildViewController.getter
...
(32 additional frame(s) were not displayed)
```

First seen: Jan 8, 2020
Release: 3.2.1.0

### PR DESCRIPTION
**Pull request by shiki**
Hopefully fixes #1711.

Looking at the crash events of #1711, I'm betting that it is because we're using Ghost on the same `UITableView` used for showing real data in `TopPerformerDataViewController`. We've discovered a few months ago that this can cause race conditions (https://github.com/wordpress-mobile/WordPress-iOS/pull/12974) and crash the app. 

This PR adds a new [`GhostTableViewController`](https://github.com/woocommerce/woocommerce-ios/blob/d24dd81ee131cdc7331c6a1d29f56f32ca9903ec/WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift#L322) that serves as the ghost view of `TopPerformerDataViewController`. It is added and removed as a child ViewController:

https://github.com/woocommerce/woocommerce-ios/blob/d24dd81ee131cdc7331c6a1d29f56f32ca9903ec/WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift#L125-L135

I could not reproduce the crash, unfortunately. 😐 

## Testing

1. Comment this out or add a delay:

    https://github.com/woocommerce/woocommerce-ios/blob/d24dd81ee131cdc7331c6a1d29f56f32ca9903ec/WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformersViewController.swift#L101-L102

2. Run the app
3. Confirm that you see the placeholder:

    <kbd></kbd>

## Reviewing 

Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [ ] Mark Sentry issue as fixed

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift [hunk 1]
```diff
@@ -311,12 +384,16 @@ private extension TopPerformerDataViewController {
         static let sectionRightColumn = NSLocalizedString("Total Spend", comment: "Description for Top Performers right column header")
     }
 
+    enum TableViewStyle {
```
Comment (pmusolino) [inline WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift:387]: 👍

File: WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift [hunk 2]
```diff
@@ -158,7 +175,12 @@ private extension TopPerformerDataViewController {
         resultsController.onDidResetContent = { [weak self] in
             self?.tableView.reloadData()
         }
-        try? resultsController.performFetch()
+
+        do {
+            try resultsController.performFetch()
+        } catch {
+            CrashLogging.logError(error)
```
Comment (pmusolino) [inline WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift:182]: Good idea!

**Comment by shiki** [comment]
Thanks, Paolo!
