### PR TITLE
Dynamic Dashboard: Add tracking for dashboard card data loading

### LINKED ISSUE #13152: EXC_BREAKPOINT: calling into SwiftUI on a non-main thread is not supported > Fatal error > SwiftUI/ThreadUtils.swift
Sentry Issue: [WOOCOMMERCE-IOS-1MXD](https://a8c.sentry.io/issues/5530106026/?referrer=github_integration)

```
EXC_BREAKPOINT: calling into SwiftUI on a non-main thread is not supported > Fatal error > SwiftUI/ThreadUtils.swift
  File "<compiler-generated>", in ReviewsDashboardCardViewModel.syncingError.setter
  File "ReviewsDashboardCardViewModel.swift", line 253, in closure in ReviewsDashboardCardViewModel.synchronizeReviews
...
(90 additional frame(s) were not displayed)
```

### LINKED ISSUE #13156: Dynamic Dashboard: Add missing events for dashboard card performance
Event list:

Event | Trigger | Properties
-- | -- | --
*_dynamic_dashboard_card_data_loading_started | When a dashboard card starts loading data. | `type`: card type name
*_dynamic_dashboard_card_data_loading_completed | When a dashboard card completes loading data without error | `type`: card type name
*_dynamic_dashboard_card_data_loading_failed | When a dashboard card fails to load data | `type`: card type name, `error`: error details

Internal discussion: pe5sF9-2PV-p2#comment-3718

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13156 

## Description

This PR adds more tracking for dashboard cards data loading. Changes include:
- New events for when card loading starts, completes or fails.
- Updated tracking for all card types: performance, top performers, blaze, onboarding, last orders, most active coupons, stock, reviews, inbox.
- Some improvements:
  - Updated logs to not show type `AnyHashable` for property keys to make it more readable.
  - Track the correct error type and domain if the error is AFError with NSError as the underlying error.
  - Dashboard: fixed redundant requests for default cards by observing dashboard cards after fetching saved cards from storage. Otherwise, the default cards' data will always be loaded when the dashboard first loads.
  - Blaze card: separate logic to check card availability and reload data. This fixes duplicated requests on the dashboard.
  - Fixed rethrow error logic for performance, stock, and review cards to avoid mutating the task group in an async context.
  - Updated the review card to rethrow any errors while retrieving products. This also fixes #13152.

## Steps to reproduce

- Test each card on the dashboard by disabling all the other cards to make it easier to read the logs.
- Confirm that for each card:
  - `dynamic_dashboard_card_data_loading_started` is tracked with the correct card type when it first loads. No other card type should be loaded.
  - After loading completes, `dynamic_dashboard_card_data_loading_completed` is tracked with the correct card type.
  - Disable the internet connection and reload the dashboard. Confirm that `dynamic_dashboard_card_data_loading_failed` is tracked with the correct card type and error properties.
- Also confirm that all cards still load correctly. 

## Screenshots

N/A

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/211">19.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Dashboard/ProductStock/ProductStockDashboardCardViewModel.swift [hunk 1]
```diff
@@ -161,11 +164,10 @@ private extension ProductStockDashboardCardViewModel {
...
 
-            while !group.isEmpty {
-                // gather the results and re-throw any failure.
-                if let items = try await group.next() {
-                    allReports.append(contentsOf: items)
-                }
+            // rethrow any failure.
+            for try await items in group {
+                // gather the results
+                allReports.append(contentsOf: items)
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Dashboard/ProductStock/ProductStockDashboardCardViewModel.swift:170]: Calling `group.next()` mutates `group`, which will be an error when strict concurrency is enabled. Using `for` loop iterates through the group so it's thread-safe.

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift [hunk 2]
```diff
@@ -106,16 +106,31 @@ class StoreOnboardingViewModel: ObservableObject {
             return
         }
 
+        analytics.track(event: .DynamicDashboard.cardLoadingStarted(type: .onboarding))
         await update(state: .loading)
-        if let tasks = try? await loadTasks(),
-           tasks.isNotEmpty {
+
+        var tasks: [StoreOnboardingTaskViewModel] = []
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift]: Super nit: To prevent `tasks` being written into more than once, I would use a `let` here and set it as an empty array after catching an error.

File: WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift [hunk 3]
```diff
@@ -87,9 +88,12 @@ final class MostActiveCouponsCardViewModel: ObservableObject {
                     }
                 }
             }
+
+            analytics.track(event: .DynamicDashboard.cardLoadingCompleted(type: .coupons))
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift:92]: nit: This will be tracked before `synchronizeCoupons` is completed during the "Refresh coupons in background" case. I hope this is OK.

File: WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift [hunk 4]
```diff
@@ -290,6 +316,13 @@ private extension BlazeCampaignDashboardViewModel {
             }
             .store(in: &subscriptions)
     }
+    func trackingSyncingResult() {
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift]: nit: Would renaming into `trackSyncingResult` make sense? 

nit: New line needed above.

File: WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift [hunk 5]
```diff
@@ -118,25 +120,39 @@ final class BlazeCampaignDashboardViewModel: ObservableObject {
...
     @MainActor
     func reload() async {
+        syncingError = nil
         update(state: .loading)
-        isSiteEligibleForBlaze = await blazeEligibilityChecker.isSiteEligible()
+
+        analytics.track(event: .DynamicDashboard.cardLoadingStarted(type: .blaze))
 
         guard isSiteEligibleForBlaze else {
             update(state: .empty)
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift:140]: `isSiteEligibleForBlaze` has default value set as `false`. If we call reload without calling `checkAvailability` we will end up not checking site eligibility. 

One solution I can think of is to make `isSiteEligibleForBlaze` optional and check site eligibility from `reload` if `isSiteEligibleForBlaze` is nil. 

What do you think?

**Review by selanthiraiyan — APPROVED** [review]
Nice work, Huong. This works as expected. 🎉 

I left a few non-blocking nits and questions.

File: WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift (hunk 2 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Onboarding/StoreOnboardingViewModel.swift]: Good point! Updated in 0411458253fca975c197d354ce40a9a048bf96ef.

File: WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift (hunk 3 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift:92]: @selanthiraiyan Do you think it's ok to let `synchronizeCoupons` fail silently? If not, we would need to wait for its response instead of calling it in the background.

File: WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift (hunk 4 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift]: Updated in 3c2a878004db0504ceea99840c8cf3af259b8705 👍

File: WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift (hunk 5 above)
Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Blaze/BlazeCampaignDashboardViewModel.swift:140]: For simplicity, I added a check for site eligibility at the beginning of `reloadData` in a0f2237bc6adabd3d29363272cdb8836377a323e. Keeping `isSiteEligibleForBlaze` optional would make it difficult to work with in other methods.

File: WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift (hunk 3 above)
Comment (selanthiraiyan) [reply WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift:92]: I think it is OK unless we want to measure the network loading time of each card using the `started` and `completed` events. (I don't know whether this is possible)

Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Dashboard/Coupons/MostActiveCouponsCardViewModel.swift:92]: Since we're not measuring network loading time, I'll keep this change as-is for now. We can always revisit the logic and update when the need arises.

**Comment by itsmeichigo** [comment]
I'll merge this PR for now, thank you @selanthiraiyan for the review!
