### PR TITLE
Fix unnecessary stats API requests after switching stores

### LINKED ISSUE #6855: Dashboard: remove unnecessary API requests for the original store when switching stores
**Describe the bug**

When switching stores, the app not only makes API requests to fetch the latest stats for the new store but also the previous store. There's no immediate use of the stats for the previous store, and even if the user switches back to the original store later we want to fetch the latest stats.

**To Reproduce**

Prerequisite: the account is connected to at least two stores
- Log in to a store if needed
- Go to the Menu tab and tap "Switch store"
- Select a different store and continue --> you can use proxy tool (e.g. Charles) or Wormholy to see that the app was still fetching the latest stats for the previously selected store

**Expected behavior**

The app should only make stats API requests for the newly selected store.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 9.1

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #6855 

### Description

When switching stores, there are stats API requests (store stats, visitor stats, top performers) for the previous store in addition to the newly selected store and these data aren't used in the new store. The reason for this bug is because `DashboardViewController` observes `StoresManager.site` (since the `Site` object is fetched or loaded asynchronously after `siteID` is set) and when the store changes the view controller of the previous store also receives the site update and triggers API requests to refresh data.

To fix this, `DashboardViewController` now checks that the `Site` from `StoresManager.site` observable matches its site ID before making any updates based on the site changes. `DashboardViewController` of the previous store is deallocated shortly after being replaced by a new view controller.

### Testing instructions

Prerequisite: the account is connected to at least two stores
- Log in to a store if needed
- Go to the Menu tab and tap "Switch store"
- Select a different store and continue --> you can use proxy tool (e.g. Charles) or Wormholy to see that the app is only fetching stats data for the new site ID

### Screenshots

before | after
-- | --
Screen Shot 2022-05-16 at 1 26 56 PM | Screen Shot 2022-05-16 at 1 27 49 PM

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift [hunk 1]
```diff
@@ -277,8 +277,9 @@ private extension DashboardViewController {
         spacerView.isHidden = true
     }
 
-    func updateUI(site: Site?) {
-        guard let siteName = site?.name, siteName.isEmpty == false else {
+    func updateUI(site: Site) {
+        let siteName = site.name
+        guard siteName.isEmpty == false else {
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift]: Super nit: We could also use the extension property `isNotEmpty` for simplicity here.
```suggestion
        guard siteName.isNotEmpty else {
```

**Review by itsmeichigo — APPROVED** [review]
This looks good and tests well for me ✅ :shipit: 

My understanding is that the previous dashboard controller hasn't been released yet when switching stores? It's good to know that the redundant requests are only triggered for the immediately previous store, as this means the old dashboard controller is released soon after that.

File: WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift (hunk 1 above)
Comment (jaclync) [reply WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift]: This looks nicer! Updated in https://github.com/woocommerce/woocommerce-ios/pull/6864/commits/edf5ac27f368a72e0b010cd890917269434f3f72
