### PR TITLE
REST API: Update title and URL and hide Switch store button on Hub menu

### LINKED ISSUE #8511: [REST API] Invalid store address in `My Store`
## Steps to reproduce 
1. Turn on the `applicationPasswordAuthenticationForSiteCredentialLogin` feature flag.
1. Login into the app using .org site credentials.
1. Navigate to the `Menu` tab.
1. Notice that the site URL is not right.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #8511 

## Description

This PR updates the logic on Hub menu to observe the logged-in site to update its title and URL accordingly.

Also: a new boolean was added to hide the Switch store button when the user is logged in with site credentials only.

## Testing instructions

Prerequisite: Make sure that application password is enabled on your test site.
- Enable the feature flag `applicationPasswordAuthenticationForSiteCredentialLogin` and build the app.
- Log out of the app if needed.
- On the prologue screen, select "Enter your site address". If this option is not available, [disable simplified login](https://github.com/woocommerce/woocommerce-ios/blob/8d471f969911067311412d72f58de6ae2c966c6a/WooCommerce/Classes/Authentication/AuthenticationManager.swift#L61) and build the app again.
- Enter your test store address and select "Sign in with site credentials".
- Enter correct credentials and select "Continue". The app should navigate to the home screen after that.
- Navigate to the Menu tab. Notice that the site title and URL are updated correctly. The Switch store button should be hidden.

Please feel free to test again by logging in with a WPCom account. The menu should work as before.
## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift [hunk 1]
```diff
@@ -271,6 +271,42 @@ final class HubMenuViewModelTests: XCTestCase {
         XCTAssertNotNil(viewModel.woocommerceAdminURL)
         XCTAssertEqual(viewModel.woocommerceAdminURL, try URL(string: expectedAdminURL)?.asURL())
     }
+
+    func test_switchStoreEnabled_returns_true_when_logged_in_with_wpcom() {
```
Comment (selanthiraiyan) [inline WooCommerce/WooCommerceTests/ViewRelated/HubMenu/HubMenuViewModelTests.swift:275]: Thanks for adding tests. ❤️

**Review by selanthiraiyan — APPROVED** [review]
This works as expected. 🚢
