### PR TITLE
Send receipts after successful payments via the API

### LINKED ISSUE #14163: [TTPReq] Send receipts after succeeded or failed payments
PT: p7bje6-6ob-p2
Test scenarios: p91TBi-csN-p2
API task: https://github.com/woocommerce/woocommerce-ios/issues/14326
Designs & Copy: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2

## Description

Allow customer receipts to be sent after successful and failed payments.

1. Integrate new Woo 9.5 changes to send receipts after failed payment
2. Integrate 'Send Receipt' option within existing APIs
3. Try integrating existing UI to select customers / add new customer details
4. Call a new API https://github.com/woocommerce/woocommerce-ios/issues/14326 to send receipt to updated customer details
5. https://github.com/woocommerce/woocommerce-ios/issues/6358
Do not send a receipt to the same user twice. Test if receipts are always sent after successful or failed payments when the customer is attached. If that's the case, consider showing `Send Receipt` option only when there's no customer attached (See https://github.com/woocommerce/woocommerce-ios/issues/6358 and Android implementation).

## Design

| Image 1 | Image 2 |
| ------- | ------- |
| Image 1 | Image 2 |

#### Email sent message

Image

## User Flow

Image

### PR DESCRIPTION
**Pull request by staskus**
Resolves: #14163

I'll address failed payments in the next tasks.

## Description

This PR implements sending receipts after successful payments with a new API. Until now, it was only possible to send a receipt after payment using the email client.

However, after https://github.com/woocommerce/woocommerce-ios/pull/14368 was implemented and with Woo 9.5, it's possible to trigger sending receipts via API.

Note: There's an issue with this functionality on the WooCommerce trunk (p91TBi-csN-p2#comment-13579) therefore I'm not implementing an eligibility handler. I recommend doing testing on my provided site.

## Solution

1. Created `ReceiptEmailView` and `ReceiptEmailViewViewModel` for displaying a view with a single email address field and processing the "Email Receipt" action. It emulates the UI of the existing Customer Billing Information screens and reuses existing fields and buttons.
2. Presenting this view within `CollectOrderPaymentUseCase` when users select "Email Receipt" option.

#### Before testing
1. Edit project to return `true` from `isEligibleSendingReceiptAfterPayment` 
2. Use my testing site https://lovely-aware-sturgeon.jurassic.ninja/ details: PdfdoF-5Qj-p2

#### Main scenario: Successful payment + No customer

1. Order
2. Add custom amount / product
3. Make Card Reader / TTP payment
4. Confirm Payment successful modal appears with three options: "Print receipt", "Email receipt", "Save receipt and continue"
5. Click "Email receipt"
6. Confirm a new modal appears
7. Confirm "Email Receipt" button only enables when the valid email is added
8. Input a valid email
9. Tap "Email receipt"
10. Confirm modals are dismissed
11. Confirm email arrives

## Testing information

I tested additional scenarios:
- Successful payments with email attached
- Failed payments with and without email attached

Regression cases where `isEligibleSendingReceiptAfterPayment` returns false:
- Successful and failed payments with native iOS mail client and without it

## Screenshots

| Payment Successful | Email Receipt to Customer |
|-------------------|----------------------------|
| Simulator Screenshot - iPhone 16 - 2024-11-14 at 17 00 51 | Simulator Screenshot - iPhone 16 - 2024-11-14 at 17 00 19 |

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailView.swift [hunk 1]
```diff
@@ -0,0 +1,116 @@
+import SwiftUI
+import Yosemite
+
+struct ReceiptEmailView: View {
```
Comment (staskus) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailView.swift:4]: Any feedback is welcome on this view as well. I tried to keep it simple, maybe it's too simple.

Another option I considered is reusing 'customer form view', with the email field focused. However, I thought it may distract the user in this flow and left only the email field.

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift [hunk 2]
```diff
@@ -42,6 +43,11 @@ final class ReceiptEligibilityUseCase: ReceiptEligibilityUseCaseProtocol {
         }
         stores.dispatch(action)
     }
+
+    func isEligibleSendingReceiptAfterPayment(onCompletion: @escaping (Bool) -> Void) {
+        // TODO: WooCommerce 9.5.0
+        onCompletion(false)
```
Comment (staskus) [inline WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: Note: There's an issue with this functionality on the WooCommerce trunk (p91TBi-csN-p2#comment-13579) therefore I'm not implementing an eligibility handler. I recommend doing testing on my provided site.

Testing site https://lovely-aware-sturgeon.jurassic.ninja/ details: PdfdoF-5Qj-p2.

It means that the current changes should not affect production in any way.

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift [hunk 3]
```diff
@@ -565,11 +565,28 @@ private extension CollectOrderPaymentUseCase {
                 }
             })
         }
-        // Presents receipt alert
-        alertsPresenter.present(viewModel: paymentAlerts.success(printReceipt: receiptPresentationCompletionAction,
-                                                                 emailReceipt: receiptPresentationCompletionAction,
-                                                                 noReceiptAction: { onCompleted() },
-                                                                 email: order.billingAddress?.email))
+            // Sends receipt via API
```
Comment (staskus) [inline WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift:568]: It's the first time I have made some additions to the use case. Let me know if it's preferred that `ReceiptEmailView` would be a dumb view and email sending would happen within the PaymentOrchestrator rather than within `ReceiptEmailViewModel`.

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailViewModel.swift [hunk 4]
```diff
@@ -0,0 +1,57 @@
+import Foundation
+import class WordPressShared.EmailFormatValidator
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailViewModel.swift:2]: TIL `WordPressShared.EmailFormatValidator`

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEmailViewModelTests.swift [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+@testable import WooCommerce
+
+@MainActor
+struct ReceiptEmailViewModelTests {
+    private let stores: MockStoresManager
+    private let order: Order
+    private let noticesPresenter: MockNoticePresenter
+    private let sut: ReceiptEmailViewModel
+
+    init() {
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEmailViewModelTests.swift:13]: Oh, I just realized since SwiftTesting uses structs we do not need setup/teardown anymore, this should recreate a new instance for each test 💯

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEmailViewModelTests.swift [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+        noticesPresenter = MockNoticePresenter()
+        sut = ReceiptEmailViewModel(
+            order: order,
+            stores: stores,
+            noticesPresenter: noticesPresenter
+        )
+    }
+
+    @Test func sendReceipt_when_action_succeeds() async {
+        // Given send receipt action suceeds
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEmailViewModelTests.swift]:
```suggestion
        // Given send receipt action succeeds
```

File: WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEmailViewModelTests.swift [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+                continuation.resume(returning: $0)
+            }
+            sut.sendReceipt()
+        }
+
+        // Then
+        #expect(completionResult.title != nil)
+    }
+
+    @Test(arguments: [true, false])
```
Comment (iamgabrielma) [inline WooCommerce/WooCommerceTests/ViewModels/Receipts/ReceiptEmailViewModelTests.swift:75]: 💯

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailView.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailView.swift:4]: I think is perfectly fine for our current use case, and we can iterate on the future depending on, for example:
- Are we going to be able to select an email from existing customers, rather than writing it?
- Are going to be able to "resend" to the same address (eg: retry button, reusing the already-entered email) and/or different addresses prompted from the order view?

Something I've missed is some sort of UI feedback between sending was completed and all the modals were dismissed, something like what we do when creating a coupon (a big animated checkmark before calling for dismiss)

File: WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift (hunk 2 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewModels/Order Details/Receipts/ReceiptEligibilityUseCase.swift]: I think we should pass a feature flag here for now rather than passing `false` directly, just to be safe, then we can also modify it to perform a version check when 9.5 is available.

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTransactionAlertEmailReceiptAction.swift [hunk 8]
```diff
@@ -0,0 +1,16 @@
+import Foundation
+import MessageUI
+
+enum CardReaderTransactionAlertEmailReceiptAction {
+    case emailSent(String)
+    case sendEmail(() -> Void)
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTransactionAlertEmailReceiptAction.swift]: What do you think if we add descriptors to the associated values? I wasn't sure at first glance what the String type was until I checked the context where it was called. Sort of:

```suggestion
    case emailSent(_ emailAddress: String)
    case sendEmail(_ onSendAction: () -> Void)
```

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift [hunk 9]
```diff
@@ -42,20 +42,19 @@ final class BuiltInCardReaderPaymentAlertsProvider: CardReaderTransactionAlertsP
...
+                 noReceiptAction: @escaping () -> Void) -> CardPresentPaymentsModalViewModel {
+        switch emailReceipt {
+        case let .emailSent(email):
+            return CardPresentModalSuccessEmailSent(printReceipt: printReceipt,
+                                                    noReceiptAction: noReceiptAction,
+                                                    email: email)
+        case let .sendEmail(emailReceipt):
+            return CardPresentModalSuccess(printReceipt: printReceipt,
+                                           emailReceipt: emailReceipt,
+                                           noReceiptAction: noReceiptAction)
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift]: I found these two hard to read when they're together as are very similar. How about changing the `emailReceipt` property to something like `emailReceiptAction` for consistency with `noReceiptAction`, and rename both `.emailSent` and `.sendEmail` cases to something more descriptive with what they'll be presenting? like promptToSendEmailReceipt, paymentSuccessEmailSent, or similar 🤔

File: WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Orders/Collect Payments/CollectOrderPaymentUseCase.swift:568]: I have no specific input here, I think I've never touched those files either (or I did slightly), my 0.02: 

I think it's fine where it is now, as within `CollectOrderPaymentUseCase` we're handling the entire lifecycle from connection to payment, alerts, receipts, and analytics until is entirely completed. However, at some point we should move this out of here to some service/provider in Yosemite outside of this PR.

A related item is that currently the `CollectOrderPaymentUseCase` may be handling too much responsibility, and some of this should be extracted out (eg: alerts, hardware references, ... ).  The Orchestrator seems to be mixing some of these responsibilities as well, as is handling capture, but also receipts, which I think comes from when we were generating these entirely in the client, rather than backend-generated.

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailView.swift [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+                VStack(spacing: 0) {
+                    Divider()
+                    TitleAndTextFieldRow(title: Localization.emailField,
+                                         placeholder: Localization.emailHint,
+                                         text: $viewModel.email,
+                                         symbol: nil,
+                                         fieldAlignment: .leading,
+                                         keyboardType: .emailAddress)
+                    .autocapitalization(.none)
+                    .autocorrectionDisabled()
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Receipts/ReceiptEmail/ReceiptEmailView.swift:19]: Nice touch, those 3 make the experience much better 💯

**Review by iamgabrielma — APPROVED** [review]
LGTM 🚀 

Left a couple of comments but nothing is a blocker. (PD: Aren't yes/no switched [here](https://private-user-images.githubusercontent.com/4062343/384932854-f1809292-bb9e-469a-8c1d-11c4582ef011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzM2MTEsIm5iZiI6MTczMTYzMzMxMSwicGF0aCI6Ii80MDYyMzQzLzM4NDkzMjg1NC1mMTgwOTI5Mi1iYjllLTQ2OWEtOGMxZC0xMWM0NTgyZWYwMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDExNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTllNTNlZTNlMDFjOWU0YzIyMWFiOGIyYjUyNTdhNDUxMDdlM2M4ZGNkM2QzYWFmMmE5NjNjZjg4NDU3OWYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EDBR60-8FOKrciR2mE48absor-sGW7KHTWX0s739fL8)?)

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTransactionAlertEmailReceiptAction.swift (hunk 8 above)
Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/CardReaderTransactionAlertEmailReceiptAction.swift]: Sounds good!

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift (hunk 9 above)
Comment (staskus) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/BuiltInCardReaderPaymentAlertsProvider.swift]: Good idea. I went back-and-forth with various versions of these. The goal of it all is clarity and if it's not clear it needs to be improved.

**Comment by staskus** [comment]
> Are we going to be able to select an email from existing customers, rather than writing it?

Good question. I opted for simplicity now, but I imagine a scenario where we would have a button that opens Customer search and allows them to pick one instead.

> Are going to be able to "resend" to the same address (eg: retry button, reusing the already-entered email) and/or different addresses prompted from the order view?

Not in the scope of this feature. But all of that is supported by a new API.

> Something I've missed is some sort of UI feedback between sending was completed and all the modals were dismissed, something like what we do when creating a coupon (a big animated checkmark before calling for dismiss)

Good point. I'll check what is done in the coupon view and try to implement it as well. 👍
