### PR TITLE
[Order Creation] Fix Collect Payment from Order Form when Split View enabled

### LINKED ISSUE #11676: [Tablet Orders] Fix `Collect Payment` button from order creation when SplitViewOrders is enabled
With the `splitViewInOrdersTab` feature flag set to true, if you tap `Collect Payment` on the Create Order screen (not Order Details), the order is created but the presentation of the payment screen silently fails.

This is probably due to an issue picking the correct view controller to present the flow from; I suspect we're presenting from the OrderForm, but not until it's off screen, which would fail.

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11676

## Description

The `Collect Payment` button on the Order Form was broken with the Orders Split View feature flag set to `true`.

This was due to the different view lifecycle, when the Order Form is presented from a `UISplitViewController`. The previous implementation relied on the Order Details becoming visible before the sheet was presented by the OrderForm (and frankly, I'm surprised it ever worked!)

This PR delegates the presentation of the Payment Method screen to the `OrdersRootViewController`, which handles the transition and can wait until the Order Details screen is shown, before telling it to present the payment screen.

The same approach is used with the feature flag on and off, but that's required a change to the code with the feature flag set to `false` as well. Both should be tested.

## Testing instructions

1. Set the feature flag to your test variant
2. Launch the app
3. Tap the Orders tab
4. Tap +
5. Add a product to the order
6. Tap `Collect Payment`
7. Observe that the form is dismissed, Order Details are shown, and then the Payment Methods screen is presented on top.
8. Complete a payment flow.

- [ ] Feature flag `true`, iPad full-screen (split view visible)
- [ ] Feature flag `true`, iPad with app in slide-over (split view collapsed)
- [ ] Feature flag `true`, iPhone in portrait
- [ ] Feature flag `false`, iPad full-screen (split view visible)
- [ ] Feature flag `false`, iPad with app in slide-over (split view collapsed)
- [ ] Feature flag `false`, iPhone in portrait

### iPad: feature flag on

https://github.com/woocommerce/woocommerce-ios/assets/2472348/6479a279-6cd5-4aa7-94e9-80b2afa81c55

### iPad: feature flag off

https://github.com/woocommerce/woocommerce-ios/assets/2472348/9a9664a3-1400-4df0-a61b-1c63b7712aec

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by joshheald** [comment]
Only one review required, tagging @jaclync @bozidarsevo for visibility (but your reviews are of course welcome!)

File: WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift [hunk 1]
```diff
@@ -188,6 +188,20 @@ final class OrdersRootViewController: UIViewController {
...
+                        return
+                    }
+                    let paymentMethodsViewController = PaymentMethodsHostingController(viewModel: paymentMethodsViewModel)
+                    paymentMethodsViewController.parentController = orderDetailsViewController
+                    orderDetailsViewController.present(paymentMethodsViewController, animated: true)
+                }
+            }
+        }
+
         if ServiceLocator.featureFlagService.isFeatureFlagEnabled(.splitViewInOrdersTab) {
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift:205]: Not from this PR, but just noticed that we're calling the `ServiceLocator` instance of feature flag in this line.

**Comment by iamgabrielma** [comment]
Tests well! 🚢  

|| flag `true` | flag `false` |
|--|--------|--------|
|iPad full-screen (split view visible)| ✅  | ✅ |
| iPad with app in slide-over (split view collapsed)| ✅  | ✅ |
| iPhone in portrait | ✅  | ✅  |

**Review by iamgabrielma — APPROVED** [review]

File: WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Orders/OrdersRootViewController.swift:205]: It'll be deleted before long, but thanks for pointing it out
