### PR TITLE
[Mobile Payments] Use a single object for token and location, update its context as siteID, gateway change

### LINKED ISSUE #5912: [Mobile Payments] Can't connect to reader after switching stores - terminal SDK incorrectly asks old store for token
When testing #5868 I noticed the Terminal SDK asking the wrong store for reader tokens and location after switching stores.

**To Reproduce**
1. Add a breakpoint to the token fetch and location fetch, or `print` the siteID in those functions
2. Connect to a card reader
3. Disconnect the reader
4. As the same user, and without exiting the app, switch to a different store also set up for WCPay
5. Connect to the card reader
6. Observe the siteID the request is posted to

**Screenshots**
N/A

**Expected behavior**
The siteID fetched from should be changing as the store selected changes.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by allendav**
Closes: #5912

### Description
- Currently we pass a token provider to the `start` method of the `CardReaderService`
- That token provider is passed to the Terminal SDK so that it can request a token when attempting to connect a reader
- Unfortunately, the Terminal SDK will continue to call that object once set
- So, we instead have CardPresentPaymentStore instantiate an object that can accept changes to the siteID and backend and update it each time we start discovery. That way when Stripe calls into it, it has the correct context.

### Testing instructions
- Enable the Stripe IPP experiment if you haven't already
- Connect to a card reader for a store using WCPay as its payments backend
- Switch to a store using Stripe as its payments backend
- Ensure you can connect to a card reader there too

### Screenshots
N/A

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/Networking/Remote/CardReaderCapableRemote.swift [hunk 1]
```diff
@@ -0,0 +1,6 @@
+public protocol CardReaderCapableRemote {
```
Comment (ctarda) [inline Networking/Networking/Remote/CardReaderCapableRemote.swift]: Can this declaration been moved to the context of CardPresentPaymentsStore? Declaring this protocol in Networking as public seems unnecessary.

If this could be declared in the same file as the store, conformance also could be declared in the same file as: `extension StripeRemote: CardReaderCapableRemote {}`

**Review by ctarda — APPROVED** [review]
Works well. 

I would suggest trying to move the declaration of the protocol out of Networking. 

:shipit:

File: Networking/Networking/Remote/CardReaderCapableRemote.swift (hunk 1 above)
Comment (allendav) [reply Networking/Networking/Remote/CardReaderCapableRemote.swift]: > If this could be declared in the same file as the store, conformance also could be declared in the same file as: extension StripeRemote: CardReaderCapableRemote {}

OMG that's a good idea. I keep forgetting Swift allows that sort of thing

Comment (allendav) [reply Networking/Networking/Remote/CardReaderCapableRemote.swift]: Fixed in https://github.com/woocommerce/woocommerce-ios/pull/5922/commits/21297284bab6e6798ad448e49c02dc29fc2816de
