### PR TITLE
Store picker updates

### LINKED ISSUE #678: Settings > Switch Store > Site Picker can trap a user in the flow
**Describe the bug**
[Background](https://github.com/woocommerce/woocommerce-ios/pull/660#issuecomment-462388240)
If the user goes to Settings > Switch Store and switches to airplane mode, they can become trapped by the UX. There is no Cancel or Back button to take them out of the site switching flow.

Internal ref for uxtrap.patch p1549923119041400-slack-C6H8C3G23

**To Reproduce**
1. Settings > Switch Stores
2. Wait for the Site Picker to appear
3. Turn off data by switching to airplane mode and turning off wifi
4. An error pops up stating "Unable to connect to store" and there is no way to back out of the flow.

**Screenshots**

**Expected behavior**
There are multiple ways to fix this flow. The issue is not changing the UI, but rather the tightly coupled actions and network calls happening in the background.

The UI is the easy part:
- add a nav bar with the Back button (and move Help to the nav bar)
- add a Cancel button on the left (and leave the Help button on the right)
- make an exception for this error message and change the "Retry" button to "Go back"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. **- N/A**
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). **- N/A**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: (all)
- iOS version: (all) 
- WooCommerce iOS version: 1.2

### PR DESCRIPTION
**Pull request by bummytime**
The primary reason this PR exists is to address #678 — allowing a user to navigate back out of the store picker screen when switching stores:

before-after

Consider the UI here a "v1". Ideally we might move the continue button to the upper right corner of the nav bar, when in store switching mode but that would require a lot more refactoring and thus not included in this PR.

## Discussion

The store picker is actually called from 3 different spots in the app:
1. The main login flow
2. In `AppDelegate` when the app launches and a default store is not selected (a little bit of an edge case but we need to account for it)
3. Switching stores

In each of these cases the store picker has to present, look, and behave differently. So instead of tightly coupling the `StorePickerVC` to each spot that instantiates it, I decided to run with the classic `Coordinator` pattern:

storecoordinator

Each caller passes `StorePickerCoordinator` a `StorePickerConfiguration` value which is then used to set the picker up appropriately as well as determine when certain events occur (e.g. when switching stores don't log out the user until they press "Continue"). Additionally, I tried to make `StorePickerVC` "dumber" by removing a lot of app-level store management and into `StorePickerCoordinator`.

Fixes #678 

## Testing

review the codez and let me know what y'all think. Additionally, let's make sure we test this pretty well, because there is a lot of fundamental changes happening here. Here are some scenarios to consider:

### Login flow
* Logging into the app as a multi-store user
* Logging into the app as a single-store user
* Logging into the app as a user with no stores
* In the login flow, if I kill the app while on the picker screen, and then restart it, am I at the beginning of the login flow?
* Does the help button still work?

### Store switching
* After I tap the back navbar button in the store picker, is everything still working?
* When first opening the store picker, is my current store pre-selected?
* In the store picker, if I tap the same store I am already logged into, is it effectively a no-op?
* When switching stores, do I see the notice that @ctarda did in #735 ?
* What happens when I switch tabs when the store switcher is on screen? Is this expected? 
* We now nav back to the settings screen after selecting a new store (WooAndroid parity) — is this screen updated with the new store information?
* After switching stores in the app, do the other screens show the correct data?

@ctarda and @mindgraffiti if you could give this a thorough test,that would be swell! 😄 

----
Update release notes:

- [X] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift [hunk 1]
```diff
@@ -5,42 +5,56 @@ import WordPressUI
 import Yosemite
 
 
+typealias SelectStoreClosure = () -> Void
 
-/// Allows the user to pick which WordPress.com (OR) Jetpack-Connected-Store we should set up as the Main Store.
+/// StorePickerViewControllerDelegate: the interface with operations related to the store picker
 ///
-class StorePickerViewController: UIViewController {
+protocol StorePickerViewControllerDelegate: class {
```
Comment (ctarda) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift]: This is totally nitpick, but it seems like the Kool kids now declare class only protocols with `AnyObject`:
https://useyourloaf.com/blog/class-only-protocols-in-swift-4/

Even though it does make sense to me, I haven't found any direct link to any Apple doc suggesting doing so 🤷‍♂️

**Comment by ctarda** [comment]
The code looks great, as you would expect. 

I am still seeing the picker being presented modally instead of embedded in a navigation controller when logging in, either as a user with a single store or as a user with multiple stores. 

Once logged in, as a user with multiple stores, the picker is embedded into a navigation controller, as expected.

##Store switching

✅ After I tap the back navbar button in the store picker, is everything still working? 
✅ When first opening the store picker, is my current store pre-selected?
✅ In the store picker, if I tap the same store I am already logged into, is it effectively a no-op?
✅ When switching stores, do I see the notice added in #735 ?
✅ What happens when I switch tabs when the store switcher is on screen? Is this expected?
🤔 We now nav back to the settings screen after selecting a new store (WooAndroid parity) — is this screen updated with the new store information? _I am not sure about what's expected here. The back button should not commit, in my opinion, the selection. At the moment, it seems like it is not committing it, so I would say it works as expected_
✅ After switching stores in the app, do the other screens show the correct data?

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+
+    func showStorePicker() {
+        if selectedConfiguration == .standard {
+            navigationController.present(storePicker, animated: true)
+        } else {
+            navigationController.pushViewController(storePicker, animated: true)
+        }
+    }
+
+    func presentStoreSwitchedNotice() {
```
Comment (ctarda) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: I am starting to wonder if we should try to abstract out presenting Notices. We have code very similar to this in several places across the app (i.e. code that configures and presents a Notice), that is tightly coupled with the fact that we are using `Notice`. I am just thinking out loud here, but would it make sense to explore some kind of abstraction (let's call it `NoticeProducer`) modelled as a protocol, with an extension that implements presentation of Notices for view controllers (`extension NoticeProducer where self = UIViewController`) and provides "domain methods" to present user-facing alerts (for example `presentAlertWithTitle` `presentAlertWithTitle:retryClosure:`...)

My concern, even though it is a minor one, would be that if we wanted to use a different library, or we needed to change the way Notices are initialised, or we needed to make any change in general, we'd need to touch a lot of different classes / files

**Comment by bummytime** [comment]
Thank you @ctarda!

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift (hunk 2 above)
Comment (bummytime) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: This is a good point @ctarda — we do have Notice code scattered throughout the app! Would you mind writing up a new issue for this so we can track it?

Comment (mindgraffiti) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerCoordinator.swift]: ++ excellent observation

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift [hunk 3]
```diff
@@ -456,7 +523,7 @@ extension StorePickerViewController: UITableViewDelegate {
     func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
 
         // Preserve the Cell Height
-        // Why: Because Autosizing Cells, upon reload, will need to be laid yout yet again. This might cause
+        // Why: Because Autosizing Cells, upon reload, will need to be laid you yet again. This might cause
```
Comment (mindgraffiti) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift]: `out` instead of `you`

File: WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift [hunk 4]
```diff
@@ -29,6 +29,20 @@ class OrderLoaderViewController: UIViewController {
...
 
+    /// ResultsController: Handles all things order status
+    ///
+    private lazy var statusResultsController: ResultsController<StorageOrderStatus> = {
+        let storageManager = AppDelegate.shared.storageManager
+        let predicate = NSPredicate(format: "siteID == %lld", siteID)
+        let descriptor = NSSortDescriptor(key: "slug", ascending: true)
+        return ResultsController<StorageOrderStatus>(storageManager: storageManager, matching: predicate, sortedBy: [descriptor])
+    }()
+
```
Comment (mindgraffiti) [inline WooCommerce/Classes/ViewRelated/Orders/OrderLoaderViewController.swift]: Nice catch. Thank you for including this fix!

File: WooCommerce/Classes/AppDelegate.swift [hunk 5]
```diff
@@ -343,17 +347,15 @@ extension AppDelegate {
...
-    }
-
-    /// Displays the Woo Store Picker.
-    ///
-    func displayStorePicker() {
-        let pickerViewController = StorePickerViewController()
-        let navigationController = UINavigationController(rootViewController: pickerViewController)
-
-        window?.rootViewController?.present(navigationController, animated: true, completion: nil)
+        DDLogInfo("💬 Authenticated user does not have default store — launching store picker.")
```
[the remark this answers is not in the document]
Comment (bummytime) [reply WooCommerce/Classes/AppDelegate.swift]: I shall update!

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift (hunk 3 above)
Comment (bummytime) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift]: gah! 🤣

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift (hunk 1 above)
Comment (bummytime) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift]: Thanks for the heads up @ctarda — I will update!

**Comment by bummytime** [comment]
Thank you for the 👀 @ctarda and @mindgraffiti !

**Comment by kyleaparker** [comment]
I like the inclusion of the back button here, but I think this should come in as an overlay from the bottom as it doesn't seem like you should still be able to navigate to the other tabs (My store, Orders, Notifications) from this screen.

**Comment by bummytime** [comment]
@kyleaparker I will make an issue to track this ^^
