### PR TITLE
Fix Top banner view autolayout warnings

### LINKED ISSUE #1549: "Unable to simultaneously satisfy constraints" in Product List
Opening Product List on iPhone 11 Pro (simulator), the console prints a lot of errors about auto layout. They seem related to `TopBannerView`.

Simulator Screen Shot - iPhone 11 Pro - 2019-12-03 at 17 25 54

```[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002cf27b0 UIView:0x7fb8dc75d590.leading == UIStackView:0x7fb8dc75d400.leading - 16   (active)>",
    "<NSLayoutConstraint:0x600002cf1720 H:[UIStackView:0x7fb8dc75d400]-(10)-|   (active, names: '|':UIView:0x7fb8dc75d590 )>",
    "<NSLayoutConstraint:0x600002cf1270 WooCommerce.TopBannerView:0x7fb8dc75c570.leading == UIStackView:0x7fb8dc75d870.leading   (active)>",
    "<NSLayoutConstraint:0x600002cf0b90 H:[UIStackView:0x7fb8dc75d870]-(0)-|   (active, names: '|':WooCommerce.TopBannerView:0x7fb8dc75c570 )>",
    "<NSLayoutConstraint:0x600002cf1d10 UIView:0x7fb8dc7510c0.leading == WooCommerce.TopBannerView:0x7fb8dc75c570.leading   (active)>",
    "<NSLayoutConstraint:0x600002cf10e0 H:[WooCommerce.TopBannerView:0x7fb8dc75c570]-(0)-|   (active, names: '|':UIView:0x7fb8dc7510c0 )>",
    "<NSLayoutConstraint:0x600002cdaee0 'UISV-canvas-connection' UIStackView:0x7fb8dc75ca30.leading == UILabel:0x7fb8dc75bec0'Work in progress!'.leading   (active)>",
    "<NSLayoutConstraint:0x600002cdad50 'UISV-canvas-connection' H:[UILabel:0x7fb8dc75bec0'Work in progress!']-(0)-|   (active, names: '|':UIStackView:0x7fb8dc75ca30 )>",
    "<NSLayoutConstraint:0x600002cda5d0 'UISV-canvas-connection' UIStackView:0x7fb8dc75d400.leading == UIImageView:0x7fb8dc75ccd0.leading   (active)>",
    "<NSLayoutConstraint:0x600002cdb070 'UISV-canvas-connection' H:[UIButton:0x7fb8dc75d150]-(0)-|   (active, names: '|':UIStackView:0x7fb8dc75d400 )>",
    "<NSLayoutConstraint:0x600002cd43c0 'UISV-canvas-connection' UIStackView:0x7fb8dc75d870.leading == UIView:0x7fb8dc75d590.leading   (active)>",
    "<NSLayoutConstraint:0x600002cd72a0 'UISV-canvas-connection' H:[UIView:0x7fb8dc75d590]-(0)-|   (active, names: '|':UIStackView:0x7fb8dc75d870 )>",
    "<NSLayoutConstraint:0x600002cdba20 'UISV-spacing' H:[UIImageView:0x7fb8dc75ccd0]-(10)-[UIStackView:0x7fb8dc75ca30]   (active)>",
    "<NSLayoutConstraint:0x600002cd6080 'UISV-spacing' H:[UIStackView:0x7fb8dc75ca30]-(10)-[UIButton:0x7fb8dc75d150]   (active)>",
    "<NSLayoutConstraint:0x600002cd6990 'UIView-Encapsulated-Layout-Width' UIView:0x7fb8dc7510c0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002cdaee0 'UISV-canvas-connection' UIStackView:0x7fb8dc75ca30.leading == UILabel:0x7fb8dc75bec0'Work in progress!'.leading   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2019-12-03 17:23:17.777694+0100 WooCommerce[56465:5905172] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002cf27b0 UIView:0x7fb8dc75d590.leading == UIStackView:0x7fb8dc75d400.leading - 16   (active)>",
    "<NSLayoutConstraint:0x600002cf1720 H:[UIStackView:0x7fb8dc75d400]-(10)-|   (active, names: '|':UIView:0x7fb8dc75d590 )>",
    "<NSLayoutConstraint:0x600002cf1270 WooCommerce.TopBannerView:0x7fb8dc75c570.leading == UIStackView:0x7fb8dc75d870.leading   (active)>",
    "<NSLayoutConstraint:0x600002cf0b90 H:[UIStackView:0x7fb8dc75d870]-(0)-|   (active, names: '|':WooCommerce.TopBannerView:0x7fb8dc75c570 )>",
    "<NSLayoutConstraint:0x600002cf1d10 UIView:0x7fb8dc7510c0.leading == WooCommerce.TopBannerView:0x7fb8dc75c570.leading   (active)>",
    "<NSLayoutConstraint:0x600002cf10e0 H:[WooCommerce.TopBannerView:0x7fb8dc75c570]-(0)-|   (active, names: '|':UIView:0x7fb8dc7510c0 )>",
    "<NSLayoutConstraint:0x600002cda5d0 'UISV-canvas-connection' UIStackView:0x7fb8dc75d400.leading == UIImageView:0x7fb8dc75ccd0.leading   (active)>",
    "<NSLayoutConstraint:0x600002cdb070 'UISV-canvas-connection' H:[UIButton:0x7fb8dc75d150]-(0)-|   (active, names: '|':UIStackView:0x7fb8dc75d400 )>",
    "<NSLayoutConstraint:0x600002cd43c0 'UISV-canvas-connection' UIStackView:0x7fb8dc75d870.leading == UIView:0x7fb8dc75d590.leading   (active)>",
    "<NSLayoutConstraint:0x600002cd72a0 'UISV-canvas-connection' H:[UIView:0x7fb8dc75d590]-(0)-|   (active, names: '|':UIStackView:0x7fb8dc75d870 )>",
    "<NSLayoutConstraint:0x600002cdba20 'UISV-spacing' H:[UIImageView:0x7fb8dc75ccd0]-(10)-[UIStackView:0x7fb8dc75ca30]   (active)>",
    "<NSLayoutConstraint:0x600002cd6080 'UISV-spacing' H:[UIStackView:0x7fb8dc75ca30]-(10)-[UIButton:0x7fb8dc75d150]   (active)>",
    "<NSLayoutConstraint:0x600002cd6990 'UIView-Encapsulated-Layout-Width' UIView:0x7fb8dc7510c0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002cd6080 'UISV-spacing' H:[UIStackView:0x7fb8dc75ca30]-(10)-[UIButton:0x7fb8dc75d150]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2019-12-03 17:23:17.778461+0100 WooCommerce[56465:5905172] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002cf27b0 UIView:0x7fb8dc75d590.leading == UIStackView:0x7fb8dc75d400.leading - 16   (active)>",
    "<NSLayoutConstraint:0x600002cf1720 H:[UIStackView:0x7fb8dc75d400]-(10)-|   (active, names: '|':UIView:0x7fb8dc75d590 )>",
    "<NSLayoutConstraint:0x600002cf1270 WooCommerce.TopBannerView:0x7fb8dc75c570.leading == UIStackView:0x7fb8dc75d870.leading   (active)>",
    "<NSLayoutConstraint:0x600002cf0b90 H:[UIStackView:0x7fb8dc75d870]-(0)-|   (active, names: '|':WooCommerce.TopBannerView:0x7fb8dc75c570 )>",
    "<NSLayoutConstraint:0x600002cf1d10 UIView:0x7fb8dc7510c0.leading == WooCommerce.TopBannerView:0x7fb8dc75c570.leading   (active)>",
    "<NSLayoutConstraint:0x600002cf10e0 H:[WooCommerce.TopBannerView:0x7fb8dc75c570]-(0)-|   (active, names: '|':UIView:0x7fb8dc7510c0 )>",
    "<NSLayoutConstraint:0x600002cd43c0 'UISV-canvas-connection' UIStackView:0x7fb8dc75d870.leading == UIView:0x7fb8dc75d590.leading   (active)>",
    "<NSLayoutConstraint:0x600002cd72a0 'UISV-canvas-connection' H:[UIView:0x7fb8dc75d590]-(0)-|   (active, names: '|':UIStackView:0x7fb8dc75d870 )>",
    "<NSLayoutConstraint:0x600002cd6990 'UIView-Encapsulated-Layout-Width' UIView:0x7fb8dc7510c0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002cf27b0 UIView:0x7fb8dc75d590.leading == UIStackView:0x7fb8dc75d400.leading - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

### PR DESCRIPTION
**Pull request by toupper**
Closes: #1549

### Description

As the linked issue describes, we had warnings on Xcode console because of some conflicting constraints related to the `TopBannerView` in orders and products. With this PR we address this problem.

The reason behind the conflicting constraints was that when we add the banner view to the table view header when the view is loaded, the tableView and its header have still a width of 0. That conflicts with the inner constraints of the `TopBannerView`, such as having a spacing of 16.

To fix it we follow the approach used in other places in the app and load the view controllers with the help of a nib file. This ensures that the table view has the proper frame and size when we try to add the top banner view.

#### Orders
Ensure that there is banner to be shown (at the moment it is shown for me). If none is shown when testing it, you can tweak it by modifying the code here in `OrderListViewController`:
```
/// Update the top banner when needed
        viewModel.$topBanner
            .sink { [weak self] topBannerType in
                guard let self = self else { return }
                switch topBannerType {
                case .none:
                    self.hideTopBannerView() <----- show banner to test
                case .error:
                    self.setErrorTopBanner()
                case .orderCreation:
                    self.setOrderCreationTopBanner()
                }
            }
```

1. Open the app
2. Go to Orders
3. Banner is shown, no conflicting constraints warnings appear on the Xcode console

#### Products
Ensure that a banner is shown by changing the code in `func showTopBannerViewIfNeeded()`

1. Open the app
2. Go to Products
3. Banner is shown, no conflicting constraints warnings appear on the Xcode console

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by pmusolino — COMMENTED** [review]
I'm still able to see some warnings 🤔 and they probably depend also on the device where I'm running the app, right now it's an iPhone 13 Pro Max with iOS 15.2. 

This is the current screen 



```2022-04-06 11:06:53.427108+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000337c6e0 h=--& v=--& UITableViewCellContentView:0x111a0f750.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000337ee40 h=--& v=--& UITableViewCellContentView:0x111a0f750.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x6000033051d0 UITableViewCellContentView:0x111a0f750.top == UIStackView:0x111a0f5c0.top - 16   (active)>",
    "<NSLayoutConstraint:0x600003305450 V:[UIStackView:0x111a0f5c0]-(16)-|   (active, names: '|':UITableViewCellContentView:0x111a0f750 )>",
    "<NSLayoutConstraint:0x60000337eb70 UIImageView:0x111a0f3e0.width == 0.1*UITableViewCellContentView:0x111a0f750.width   (active)>",
    "<NSLayoutConstraint:0x60000337e710 UIImageView:0x111a0f3e0.width == UIImageView:0x111a0f3e0.height   (active)>",
    "<NSLayoutConstraint:0x60000337dd60 'UISV-canvas-connection' UIStackView:0x111a0f5c0.top == UIImageView:0x111a0f3e0.top   (active)>",
    "<NSLayoutConstraint:0x60000337d860 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002f86490'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x111a0f5c0 )>",
    "<NSLayoutConstraint:0x60000337d9f0 'UISV-spanning-boundary' _UILayoutSpacer:0x600002f86490'UISV-alignment-spanner'.bottom >= UIImageView:0x111a0f3e0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000337e710 UIImageView:0x111a0f3e0.width == UIImageView:0x111a0f3e0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.434968+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000336ae90 h=--& v=--& UITableViewCellContentView:0x111a185b0.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000336b200 h=--& v=--& UITableViewCellContentView:0x111a185b0.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x60000337e940 UITableViewCellContentView:0x111a185b0.top == UIStackView:0x111a18420.top - 16   (active)>",
    "<NSLayoutConstraint:0x60000337dd10 V:[UIStackView:0x111a18420]-(16)-|   (active, names: '|':UITableViewCellContentView:0x111a185b0 )>",
    "<NSLayoutConstraint:0x60000337f340 UIImageView:0x111a177d0.width == 0.1*UITableViewCellContentView:0x111a185b0.width   (active)>",
    "<NSLayoutConstraint:0x60000337ff20 UIImageView:0x111a177d0.width == UIImageView:0x111a177d0.height   (active)>",
    "<NSLayoutConstraint:0x600003368460 'UISV-canvas-connection' UIStackView:0x111a18420.top == UIImageView:0x111a177d0.top   (active)>",
    "<NSLayoutConstraint:0x60000336b0c0 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002f86670'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x111a18420 )>",
    "<NSLayoutConstraint:0x60000336a170 'UISV-spanning-boundary' _UILayoutSpacer:0x600002f86670'UISV-alignment-spanner'.bottom >= UIImageView:0x111a177d0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000337ff20 UIImageView:0x111a177d0.width == UIImageView:0x111a177d0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.469016+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600003379630 h=--& v=--& UITableViewCellContentView:0x106521040.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x600003379d10 h=--& v=--& UITableViewCellContentView:0x106521040.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x600003379040 UITableViewCellContentView:0x106521040.top == UIStackView:0x10651c2b0.top - 16   (active)>",
    "<NSLayoutConstraint:0x600003379090 V:[UIStackView:0x10651c2b0]-(16)-|   (active, names: '|':UITableViewCellContentView:0x106521040 )>",
    "<NSLayoutConstraint:0x6000033780f0 UIImageView:0x1065243e0.width == 0.1*UITableViewCellContentView:0x106521040.width   (active)>",
    "<NSLayoutConstraint:0x6000033785f0 UIImageView:0x1065243e0.width == UIImageView:0x1065243e0.height   (active)>",
    "<NSLayoutConstraint:0x60000337a580 'UISV-canvas-connection' UIStackView:0x10651c2b0.top == UIImageView:0x1065243e0.top   (active)>",
    "<NSLayoutConstraint:0x60000337a300 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002fac690'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x10651c2b0 )>",
    "<NSLayoutConstraint:0x60000337a440 'UISV-spanning-boundary' _UILayoutSpacer:0x600002fac690'UISV-alignment-spanner'.bottom >= UIImageView:0x1065243e0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000033785f0 UIImageView:0x1065243e0.width == UIImageView:0x1065243e0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.474022+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600003360dc0 h=--& v=--& UITableViewCellContentView:0x126db0d80.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x600003361090 h=--& v=--& UITableViewCellContentView:0x126db0d80.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x6000033727b0 UITableViewCellContentView:0x126db0d80.top == UIStackView:0x126da36d0.top - 16   (active)>",
    "<NSLayoutConstraint:0x600003372bc0 V:[UIStackView:0x126da36d0]-(16)-|   (active, names: '|':UITableViewCellContentView:0x126db0d80 )>",
    "<NSLayoutConstraint:0x600003371810 UIImageView:0x126dae9d0.width == 0.1*UITableViewCellContentView:0x126db0d80.width   (active)>",
    "<NSLayoutConstraint:0x600003371fe0 UIImageView:0x126dae9d0.width == UIImageView:0x126dae9d0.height   (active)>",
    "<NSLayoutConstraint:0x6000033605f0 'UISV-canvas-connection' UIStackView:0x126da36d0.top == UIImageView:0x126dae9d0.top   (active)>",
    "<NSLayoutConstraint:0x600003360870 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002fb7390'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x126da36d0 )>",
    "<NSLayoutConstraint:0x600003360730 'UISV-spanning-boundary' _UILayoutSpacer:0x600002fb7390'UISV-alignment-spanner'.bottom >= UIImageView:0x126dae9d0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003371fe0 UIImageView:0x126dae9d0.width == UIImageView:0x126dae9d0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.477270+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600003364e10 h=--& v=--& UITableViewCellContentView:0x126e7c640.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x6000033650e0 h=--& v=--& UITableViewCellContentView:0x126e7c640.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x600003313750 UITableViewCellContentView:0x126e7c640.top == UIStackView:0x126e7c4b0.top - 16   (active)>",
    "<NSLayoutConstraint:0x600003310a00 V:[UIStackView:0x126e7c4b0]-(16)-|   (active, names: '|':UITableViewCellContentView:0x126e7c640 )>",
    "<NSLayoutConstraint:0x600003364000 UIImageView:0x126e7c2d0.width == 0.1*UITableViewCellContentView:0x126e7c640.width   (active)>",
    "<NSLayoutConstraint:0x600003364050 UIImageView:0x126e7c2d0.width == UIImageView:0x126e7c2d0.height   (active)>",
    "<NSLayoutConstraint:0x600003364640 'UISV-canvas-connection' UIStackView:0x126e7c4b0.top == UIImageView:0x126e7c2d0.top   (active)>",
    "<NSLayoutConstraint:0x6000033648c0 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002fb3660'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x126e7c4b0 )>",
    "<NSLayoutConstraint:0x600003364780 'UISV-spanning-boundary' _UILayoutSpacer:0x600002fb3660'UISV-alignment-spanner'.bottom >= UIImageView:0x126e7c2d0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003364050 UIImageView:0x126e7c2d0.width == UIImageView:0x126e7c2d0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.481318+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000336d8b0 h=--& v=--& UITableViewCellContentView:0x111a23b10.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000336db80 h=--& v=--& UITableViewCellContentView:0x111a23b10.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x60000336c5f0 UITableViewCellContentView:0x111a23b10.top == UIStackView:0x111a23980.top - 16   (active)>",
    "<NSLayoutConstraint:0x60000336c640 V:[UIStackView:0x111a23980]-(16)-|   (active, names: '|':UITableViewCellContentView:0x111a23b10 )>",
    "<NSLayoutConstraint:0x60000336cb90 UIImageView:0x111a237a0.width == 0.1*UITableViewCellContentView:0x111a23b10.width   (active)>",
    "<NSLayoutConstraint:0x60000336cbe0 UIImageView:0x111a237a0.width == UIImageView:0x111a237a0.height   (active)>",
    "<NSLayoutConstraint:0x60000336d0e0 'UISV-canvas-connection' UIStackView:0x111a23980.top == UIImageView:0x111a237a0.top   (active)>",
    "<NSLayoutConstraint:0x60000336d360 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002f86760'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x111a23980 )>",
    "<NSLayoutConstraint:0x60000336d220 'UISV-spanning-boundary' _UILayoutSpacer:0x600002f86760'UISV-alignment-spanner'.bottom >= UIImageView:0x111a237a0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000336cbe0 UIImageView:0x111a237a0.width == UIImageView:0x111a237a0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.485385+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000336f6b0 h=--& v=--& UITableViewCellContentView:0x111a29200.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000336f980 h=--& v=--& UITableViewCellContentView:0x111a29200.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x60000336de50 UITableViewCellContentView:0x111a29200.top == UIStackView:0x111a29070.top - 16   (active)>",
    "<NSLayoutConstraint:0x60000336dea0 V:[UIStackView:0x111a29070]-(16)-|   (active, names: '|':UITableViewCellContentView:0x111a29200 )>",
    "<NSLayoutConstraint:0x60000336e3f0 UIImageView:0x111a28e90.width == 0.1*UITableViewCellContentView:0x111a29200.width   (active)>",
    "<NSLayoutConstraint:0x60000336e440 UIImageView:0x111a28e90.width == UIImageView:0x111a28e90.height   (active)>",
    "<NSLayoutConstraint:0x60000336ee90 'UISV-canvas-connection' UIStackView:0x111a29070.top == UIImageView:0x111a28e90.top   (active)>",
    "<NSLayoutConstraint:0x60000336f110 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002f86940'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x111a29070 )>",
    "<NSLayoutConstraint:0x60000336efd0 'UISV-spanning-boundary' _UILayoutSpacer:0x600002f86940'UISV-alignment-spanner'.bottom >= UIImageView:0x111a28e90.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000336e440 UIImageView:0x111a28e90.width == UIImageView:0x111a28e90.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-04-06 11:06:53.489825+0200 WooCommerce[70201:1453811] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000335a080 h=--& v=--& UITableViewCellContentView:0x111a30fc0.width == 428   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000335a350 h=--& v=--& UITableViewCellContentView:0x111a30fc0.height == 74.6667   (active)>",
    "<NSLayoutConstraint:0x60000336fca0 UITableViewCellContentView:0x111a30fc0.top == UIStackView:0x111a30e30.top - 16   (active)>",
    "<NSLayoutConstraint:0x60000336fd40 V:[UIStackView:0x111a30e30]-(16)-|   (active, names: '|':UITableViewCellContentView:0x111a30fc0 )>",
    "<NSLayoutConstraint:0x600003358320 UIImageView:0x111a30c50.width == 0.1*UITableViewCellContentView:0x111a30fc0.width   (active)>",
    "<NSLayoutConstraint:0x600003358370 UIImageView:0x111a30c50.width == UIImageView:0x111a30c50.height   (active)>",
    "<NSLayoutConstraint:0x6000033598b0 'UISV-canvas-connection' UIStackView:0x111a30e30.top == UIImageView:0x111a30c50.top   (active)>",
    "<NSLayoutConstraint:0x600003359b30 'UISV-canvas-connection' V:[_UILayoutSpacer:0x600002f86a30'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x111a30e30 )>",
    "<NSLayoutConstraint:0x6000033599f0 'UISV-spanning-boundary' _UILayoutSpacer:0x600002f86a30'UISV-alignment-spanner'.bottom >= UIImageView:0x111a30c50.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003358370 UIImageView:0x111a30c50.width == UIImageView:0x111a30c50.height   (active)>```

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift [hunk 1]
```diff
@@ -35,11 +35,7 @@ final class OrderListViewController: UIViewController, GhostableViewController {
 
     /// Main TableView.
     ///
-    private lazy var tableView: UITableView = {
-        let tableView = UITableView(frame: .zero, style: .grouped)
-        tableView.accessibilityIdentifier = "orders-table-view"
```
Comment (pmusolino) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift:40]: nit: we tend to declare all the things related to a specific view inside the code, and not on in the `xib` or `storyboard` files. I saw that you added the  `accessibilityIdentifier` in the xib file, and it's easy to miss it or declare it a second time.

**Review by pmusolino — APPROVED** [review]
LGTM, I'm not able to see any auto layout warning related the Top Banner view. :shipit: 

Just a small nit 👍

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift (hunk 1 above)
Comment (toupper) [reply WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift:40]: Thanks for letting me know :) I changed it accordingly
