### PR TITLE
Top Performers: mapping error causes "Unable to load content" error message

### LINKED ISSUE #949: Top Performers: mapping error causes "Unable to load content" error message
**Describe the bug**

Ref: 2009108-zen

Some users do not name their products, which causes a `null` to appear in the `name` field in an API response. 

**Example:**

```
{
    "date": "2019",
    "unit": "year",
    "limit": "3",
    "data": [
        {
            "ID": 11111,
            "name": null,
            "total": 220,
            "quantity": 1,
            "price": 0,
            "image": "",
            "currency": "USD"
        },
        {
            "ID": 22222,
            "name": null,
            "total": 150,
            "quantity": 1,
            "price": 0,
            "image": "",
            "currency": "USD"
        }
    ]
}
```

On iOS, we have created the product mapper to enforce all fields as non-null, so an error is getting thrown and the error bubbles up to the user as an "Unable to load content" snackbar message. 

**Console error message:**

```
2019/05/05 08:18:15:631  ⛔️ Error loading dashboard: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
```

Originally this bug was reported under #932, because the error messages always appeared together for the mapping error and the Stats module being disabled. Some of the `-zen` references in issue #932 may belong here, instead.

**To Reproduce**
1. Go to My Store > Top Performers > This Year
2. Find a product listed there, that has a name.
3. Go to your Store's website > WooCommerce. Find that specific product.
4. Erase the product name and Save.
5. Return to the app, pull-to-refresh. 
6. See snackbar-style error message "Unable to load content" appear under the "This Year" tab. (It also makes the tab show an empty content view.)

**Screenshots**

**Expected behavior**
The mapping accounts for the `null` value in the `name` field. The content loads under the Top Performers tabs.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: all
- iOS version: all
- WooCommerce iOS version: 1.8 and below

**WordPress Environment**
N/A

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #949.

This PR contains a bug fix where the "Unable to load content" error message would appear for some users, due to Top Performers being unable to load content.

Some users do not name their products, which causes a `null` to appear in the `name` field in an API response. 

**Example:**

```
{
    "date": "2019",
    "unit": "year",
    "limit": "3",
    "data": [
        {
            "ID": 11111,
            "name": null,
            "total": 220,
            "quantity": 1,
            "price": 0,
            "image": "",
            "currency": "USD"
        },
        {
            "ID": 22222,
            "name": null,
            "total": 150,
            "quantity": 1,
            "price": 0,
            "image": "",
            "currency": "USD"
        }
    ]
}
```

On iOS, we have created the product mapper to enforce all fields as non-null, so an error is getting thrown and the error bubbles up to the user as an "Unable to load content" snackbar message. 

**Console error message:**

```
2019/05/05 08:18:15:631  ⛔️ Error loading dashboard: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
```

**To Reproduce**
1. Go to My Store > Top Performers > This Year
2. Find a product listed there, that has a name.
3. Go to your Store's website > WooCommerce. Find that specific product.
4. Erase the product name and Save.
5. Return to the app, pull-to-refresh. 
6. See snackbar-style error message "Unable to load content" appear under the "This Year" tab. (It also makes the tab show an empty content view.)

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mindgraffiti** [comment]
@astralbodies I would also like to make this a patch for build 1.8 if that's okay? This bug was trending in ZD and was also reported separately by @ctarda, @jkmassel, and me.

**Comment by astralbodies** [comment]
That's great @mindgraffiti we have enough time to get a 1.8.1 out and a week of user testing on it. 😄

File: Networking/Networking/Model/Stats/TopEarnerStatsItem.swift [hunk 1]
```diff
@@ -36,9 +36,9 @@ public struct TopEarnerStatsItem: Decodable {
 
     /// Designated Initializer.
     ///
-    public init(productID: Int, productName: String, quantity: Int, price: Double, total: Double, currency: String, imageUrl: String?) {
+    public init(productID: Int, productName: String?, quantity: Int, price: Double, total: Double, currency: String, imageUrl: String?) {
         self.productID = productID
-        self.productName = productName
+        self.productName = productName ?? String()
```
Comment (astralbodies) [inline Networking/Networking/Model/Stats/TopEarnerStatsItem.swift]: For brevity just make it `?? ""` 😄

**Review by astralbodies — APPROVED** [review]

**Comment by mindgraffiti** [comment]
Thank you @astralbodies!
