### PR TITLE
Coupon: Fix issue encoding coupons

### LINKED ISSUE #7114: Coupons: "Individual use" and "Excludes sale items" are not saved when editing coupon
**Describe the bug**
When changing the values to the fields "Individual use" and "Excludes sale items" and then save the changes, the changes are not actually persisted. The cause seems to be that [these fields are currently not encoded](https://github.com/woocommerce/woocommerce-ios/blob/e8ae4c31a5d6e4d6235d62e9bb528fe6186dadd6/Networking/Networking/Model/Coupon.swift#L171-L200) so requests to edit or create coupon will not include these fields.

**To Reproduce**
1. Go to Menu > Coupons > Select a coupon
2. Select the ellipsis button and choose Edit Coupon
3. Select Usage Restrictions and toggle the values for "Individual use" and "Excludes sale items" and then save the changes.
4. Open the coupon details again, notice that the old value are kept.

**Screenshots**

https://user-images.githubusercontent.com/5533851/174736699-721c25f4-d4b6-4f63-921a-751ed3e75a02.mp4

**Expected behavior**
These fields should be updated.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #7114

### Description

This PR fixes the encoder of coupons by adding the missing fields `individualUse` and `excludeSaleItems`. Unit test has also been added for extra confidence.

### Testing instructions

1. Go to Menu > Coupons > Select a coupon
2. Select the ellipsis button and choose Edit Coupon
3. Select Usage Restrictions and toggle the values for "Individual use" and "Excludes sale items" and then save the changes.
4. Open the coupon details again, notice that the new values are displayed on the coupon details screen and the edit form displays the correct values..

### Screenshots

https://user-images.githubusercontent.com/5533851/174758295-821299f7-637b-44de-97de-366e422a4220.mp4

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/NetworkingTests/Encoder/CouponEncoderTests.swift [hunk 1]
```diff
@@ -0,0 +1,65 @@
+import XCTest
+@testable import Networking
+
+final class CouponEncoderTests: XCTestCase {
+
+    func test_coupon_encoder_encodes_necessary_fields_correctly() throws {
```
Comment (selanthiraiyan) [inline Networking/NetworkingTests/Encoder/CouponEncoderTests.swift:6]: Nice tests. ❤️

**Review by selanthiraiyan — APPROVED** [review]
The changes test well and LGTM. 🎉 
:shipit:
