### PR TITLE
[Mobile Payments] Pass empty statement descriptors as nil to Stripe

### LINKED ISSUE #6040: [Mobile Payments] Pass nil for statement descriptor to intent creation when account endpoint gives empty string
This will make it more likely to succeed for older versions of the Stripe plugin. When the merchant fails to set a descriptor for their account, we get an empty string from the account endpoint.

If we pass that empty string to intent creation, it fails, but if nil is passed, it will succeed and a default credit card statement of STRIPE will be visible on the buyer's statement.

See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2303#discussion_r796885593

### PR DESCRIPTION
**Pull request by allendav**
Closes: #6040

@ctarda @joshheald - just one review is needed but either of y'all (or both) are welcome

fyi @brianyu28 

Related: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2303#discussion_r796885593

### Description
- If the plugin passes us an empty statement_descriptor in the account endpoint, pass that as nil to Stripe to avoid payment intent creation failure

### Testing instructions
- With Stripe extension version 6.1.0, make sure you have no statement descriptor set in the plugin settings

no-descriptor

- Check Wormholy to ensure an empty string is passed in the response body for the account request when you connect the reader:

Screen Shot 2022-02-01 at 11 15 16 AM

- Proceed to orders and collect in-person payment for a cash on delivery order
- Ensure that payment collection (and therefore intent creation) succeeds
- For Stripe extension powered sites, you will see "Stripe" as the descriptor for that payment if a descriptor has not been configured in the Stripe dashboard for the account. Otherwise you will see whatever has been configured in the Stripe dashboard for that account.
- Also ensure new unit test passes

### Screenshots

statement-descriptor-stripe

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Hardware/Hardware/CardReader/StripeCardReader/PaymentIntentParameters+Stripe.swift [hunk 1]
```diff
@@ -17,7 +17,15 @@ extension Hardware.PaymentIntentParameters {
...
-        returnValue.statementDescriptor = self.statementDescription
+
+        /// Stripe allows the credit card statement descriptor to be nil, but not an empty string
+        /// https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html#/c:objc(cs)SCPPaymentIntentParameters(py)statementDescriptor
+        returnValue.statementDescriptor = nil
+        let descriptor = self.statementDescription ?? ""
+        if !descriptor.isEmpty {
+            returnValue.statementDescriptor = descriptor
+        }
+
```
Comment (joshheald) [inline Hardware/Hardware/CardReader/StripeCardReader/PaymentIntentParameters+Stripe.swift]: I've made a refactor suggestion in #6047

**Review by joshheald — APPROVED** [review]
Tested well following the instructions. Unfortunately I wasn't able to test the case where the descriptor is set to something in the settings, as the API currently seems to ignore that? Or at least it did for my test site.

Would you be able to check whether you see the same thing? I set a descriptor, and the API still returns `""`, and then I set the `add order number` toggle to change the descriptor, and still the API gives `""`.
Stripe gateway settings with statement descriptors set

I'm not really sure where to raise that, but it'd be good to get confirmation that it's not just me first anyway.

**Comment by allendav** [comment]
> Would you be able to check whether you see the same thing? I set a descriptor, and the API still returns "", and then I set the add order number toggle to change the descriptor, and still the API gives ""

I should have mentioned that. 6.2.0 is going to fix that. In the mean time, you have to either set it in the Stripe dashboard for that account or hack the plugin account controller response

**Comment by joshheald** [comment]
> 6.2.0 is going to fix that. In the mean time, you have to either set it in the Stripe dashboard for that account or hack the plugin account controller response

Nice! No need to log a bug, and another way to test it. I'll give it a whirl 😊

**Comment by joshheald** [comment]
Looks good with a statement descriptor set too 👍

File: Hardware/Hardware/CardReader/StripeCardReader/PaymentIntentParameters+Stripe.swift (hunk 1 above)
Comment (allendav) [reply Hardware/Hardware/CardReader/StripeCardReader/PaymentIntentParameters+Stripe.swift]: I do think we should clean up the unneeded selfs (and will do so here), but I find the flatMap computed property a little more of a mind warp for the next person maintaining this, so if it is ok, I think I will decline?
