### PR TITLE
[Issue Refund] Add Analytics

### LINKED ISSUE #2793: [Issue Refunds] Add Tracking for Refunding by Items
### `refund_create`

Triggered when a refund API request is submitted to the API. 

Parameters:

- `order_id` 
- `is_full`. Boolean. True if the refund amount is equal to the total order amount. This will probably be `false` all the time for now. 
- `method`. Enum. This is the refund type. Values are `ITEMS`, or `AMOUNT`. 
- `gateway`. String. The payment method of the order. Example: `"PayPal"`, `"Stripe"`. 
- `amount`. Decimal. The total refunded amount. 

### `refund_create_failed`

Triggered when the API request (`refund_create` event) failed. 

Parameters:

- `order_id`
- `error_context`. String. This is the `Exception.simpleName` in Android. I think we're free to use whatever we want here. 
- `error_description`. String. The error that is presented to the user. If available, we should probably use the error message from the API. That's assuming that it's descriptive enough. 
- `error_type`. String. In Android, this is `API_ERROR`, `GENERIC_ERROR`, or `TIMEOUT`. We can use what's similar in iOS. We don't need to follow the actual values used by Android. 

###  `refund_create_success`

Triggered when the API request (`refund_create` event) succeeded. 

Parameters:

- `order_id`
- `id`. The local `ID` of the Order. This is the same as `order_id` in the case of iOS. So it's probably not necessary to track this. 

### `create_order_refund_select_all_items_button_tapped`

Triggered when the “Select All” / “Select None” button is tapped. 

Parameters:

- `order_id`

### `create_order_refund_item_quantity_dialog_opened`

Triggered when the quantity dialog is shown.

Parameters:

- `order_id`

There are no other events triggered when interacting with the dialog. 

### `create_order_refund_next_button_tapped`

Triggered when the “Next” button is tapped.

Parameters:

- `order_id`

### `create_order_refund_summary_refund_button_tapped`

Triggered when the “Refund” button on the summary page is tapped. 

Parameters:

- `order_id`

## References

https://github.com/woocommerce/woocommerce-android/pull/1635
https://github.com/woocommerce/woocommerce-android/pull/1410

### `create_order_refund_shipping_option_tapped`

Triggered when the Refund Shipping checkbox/switch is tapped. 

Parameters:

- `order_id`
- `action`: Enum. Either “on” or ”off”.

### PR DESCRIPTION
**Pull request by Ecarrion**
closes #2793

# Why 

To complete the "Issue Refund" feature we need to match the tracking that is already implemented in Android.
Specifically, the following events are added:

- refund_create
- refund_create_failed
- refund_create_success
- create_order_refund_select_all_items_button_tapped
- create_order_refund_shipping_option_tapped
- create_order_refund_item_quantity_dialog_opened
- create_order_refund_summary_refund_button_tapped
- create_order_refund_next_button_tapped
- create_order_refund_shipping_option_tapped 

# How
- Added track identifiers enum cases to `WooAnalyticsStat`
- Added track events methods to `WooAnalyticsEvents`
- Fire methods from `IssueRefundViewModel` and `RefundConfirmationViewModel`
- Add test cases

# Testing Steps
- Confirm the analytics are being tracked correctly and printed in the console while issuing a refund

**or**

- Trust the unit tests 😅 

Update release notes:
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift [hunk 1]
```diff
@@ -87,3 +87,64 @@ extension WooAnalyticsEvent {
...
 }
+
+
+// MARK: - Issue Refund
+//
+extension WooAnalyticsEvent {
+    // Namespace
+    enum IssueRefund {
+        /// The state of the "refund shipping" button
+        public enum ShippingSwitchState: String {
```
Comment (jaclync) [inline WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift]: nit: `public` might not be necessary?
```suggestion
        enum ShippingSwitchState: String {
```

File: WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift [hunk 2]
```diff
@@ -87,3 +87,64 @@ extension WooAnalyticsEvent {
...
+            case on
+            case off
+        }
+
+        // The method used for the refund
+        public enum RefundMethod: String {
```
Comment (jaclync) [inline WooCommerce/Classes/Analytics/WooAnalyticsEvent.swift]:
```suggestion
        enum RefundMethod: String {
```

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift [hunk 3]
```diff
@@ -141,9 +145,40 @@ extension IssueRefundViewModel {
...
             state.refundQuantityStore.update(quantity: refundable.quantity, for: refundable.item)
         }
+
+        trackSelectAllButtonTapped()
     }
 }
 
+// MARK: Analytics
+extension IssueRefundViewModel {
+    /// Tracks when the shipping swtich state changes
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift]: nit:
```suggestion
    /// Tracks when the shipping switch state changes
```

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift [hunk 4]
```diff
@@ -141,9 +145,40 @@ extension IssueRefundViewModel {
...
+        analytics.track(event: WooAnalyticsEvent.IssueRefund.shippingSwitchTapped(orderID: state.order.orderID, state: action))
+    }
+
+    /// Tracks when the user taps the "next" button
+    ///
+    func trackNextButtonTapped() {
+        analytics.track(event: WooAnalyticsEvent.IssueRefund.nextButtonTapped(orderID: state.order.orderID))
+    }
+
+    /// Tracks when the user taps the "next" button
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift]: nit: the comment could be updated?

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift [hunk 5]
```diff
@@ -141,9 +145,40 @@ extension IssueRefundViewModel {
...
+    ///
+    func trackQuantityButtonTapped() {
+        analytics.track(event: WooAnalyticsEvent.IssueRefund.nextButtonTapped(orderID: state.order.orderID))
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift]: I think this event is meant to be `.quantityDialogOpened`? when I tapped on the quantity accessory view to open the quantity selector, it logged `create_order_refund_next_button_tapped` instead of `create_order_refund_item_quantity_dialog_opened`

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/RefundConfirmationViewModel.swift [hunk 6]
```diff
@@ -139,6 +150,37 @@ private extension RefundConfirmationViewModel {
...
+    }
+
+    /// Tracks when the create refund request is made.
+    ///
+    private func trackCreateRefundRequest() {
+        analytics.track(event: WooAnalyticsEvent.IssueRefund.createRefund(orderID: details.order.orderID,
+                                                                          fullyRefunded: details.amount == details.order.total,
+                                                                          method: .items,
+                                                                          gateway: details.order.paymentMethodID,
+                                                                          ammount: details.amount))
```
Comment (jaclync) [inline WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/RefundConfirmationViewModel.swift]: nit:

```suggestion
                                                                          amount: details.amount))
```

**Review by jaclync — APPROVED** [review]
Nice tests! 💯 

I also tested manually and just a question on `trackQuantityButtonTapped`!

File: WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift (hunk 5 above)
Comment (Ecarrion) [reply WooCommerce/Classes/ViewRelated/Orders/Order Details/Issue Refunds/IssueRefundViewModel.swift]: 🤦

**Comment by Ecarrion** [comment]
Thanks, @jaclync for the review and for catching that quantity bug 🙇
