### PR TITLE
[Woo POS] Add missing transitions: Unhappy payment path 

### LINKED ISSUE #13735: [Woo POS] Add missing transitions: Unhappy payment path
Parent task: #13700

p91TBi-bHy-p2

#### Payment
- [x] ‘Couldn’t load totals’ fade in [4:10]
- [x] ‘Error checking orders’ fade in and totals move down [4:32]
- [x] ‘Reader not connected’ fades in and totals move down [5:12]
- [x] ‘Processing payment’ -> ‘Payment Failed’ transition [5:51]
- [x] ‘’Payment Failed’ -> ‘’Tap, swipe, or insert card’ transition [6:44]

### PR DESCRIPTION
**Pull request by staskus**
Closes: #13735

## Description

Implemented transitions for unhappy payment path:

- Couldn't load totals
- Error checking orders
- Reader not connected
- Transitions between payment states

## Solution

To support non-payment transitions I needed to make slight adjustments to `TotalsView` to support animations during a wider range of state changes. I found it problematic to smoothly animate `Error checking orders` state due to a static height `filledSpacer` I introduced previously. If looked carefully, you can still see a gap animating differently than the main view. For now, I couldn't come up for a good solution.

### Payment States

The best solution I found is to extensively use `matchedGeometryEffect` and synchronize different parts of all message views. This means sharing a single `namespace` and different transitionIds for `icon`, `title`, and `message`. I was happy with the result. No matter which state transition happens, different messages transition smoothly between each other.

Note: this PR involves changes in a lot of files but mainly for two reasons:
- Making `PointOfSaleCardPresentPaymentMessageType` `Equatable` so it could be used to trigger animations
- Setting `matchedGeometryEffect` on all the payment message views

### Couldn't load totals

1. Open POS
2. Add an item
3. Turn off internet connection
4. Check out
5. Confirm fade in animation when the error appears
6. Turn on internet connection
7. Retry
8. Confirm fade animation when the error disappears

### Reader disconnected

1. Open POS
2. Add an item
3. Do not connect the reader
4. Check out
5. Confirm totals load, moves down, reader not connected view fades in

### Error checking order

1. Open POS
2. Add an item with less than $0.5 price
3. Connect the reader
4. Check out
5. Confirm loading appears
6. Confirm loading view transitions smoothly into 'Error checking order' state

### Payment error

1. Open POS
2. Add an item that produces a payment error (e.g $1.05)
3. Confirm all the tap/swipe -> payment processing -> payment failed transition happen smoothly
4. Tap 'Try another payment method'
5. Confirm it transitions smoothly to tap/swipe state as well

## Testing information

I tested the scenarios described in `Steps to reproduce`, tried triggering different types of payment states with different totals, and lost internet connection. Let me know if you think transitions could be done differently. 

#### Unit Tests

None added since the changes are purely user-facing.

### Couldn't load totals

https://github.com/user-attachments/assets/55622d6d-567b-443d-b4fb-f38fc732b54f

### All the other

https://github.com/user-attachments/assets/d45495b6-84ab-41e1-8285-cfbe46c39f5c

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Utils/View+WithoutAnimation.swift [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import SwiftUI
+
+extension View {
+    func withoutAnimation() -> some View {
+        return self.animation(nil, value: UUID())
+    }
+}
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/Utils/View+WithoutAnimation.swift]: Is this extension still needed? It was added to handle this case https://github.com/woocommerce/woocommerce-ios/pull/13741/commits/575f372356596d7fb757987380dc404a535a450b but then removed in a later commit https://github.com/woocommerce/woocommerce-ios/pull/13741/commits/3dca4cd9550aebfec4d6c8bf786914e5200c3f2a

File: WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import Foundation
 
-struct CardPresentPaymentsModalButtonViewModel: Identifiable {
+struct CardPresentPaymentsModalButtonViewModel: Identifiable, Equatable {
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift]: I think this case doesn't need the `Equatable` conformance?

```suggestion
struct CardPresentPaymentsModalButtonViewModel: Identifiable {
```

**Review by iamgabrielma — APPROVED** [review]
Works great! Also TIL `matchedGeometry` exists. With this and the shadows I have plenty of learning to go through in detail next 💯 

On an unrelated note to this PR, the "No internet connection" feels very flaky at times, since generally doesn't detect re-connection  properly most of times. 

Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-08-27 at 10 07 18

I've logged a quick issue here with an idea to improve it (not for M2 thought!): https://github.com/woocommerce/woocommerce-ios/issues/13743

File: WooCommerce/Classes/POS/Utils/View+WithoutAnimation.swift (hunk 1 above)
Comment (staskus) [reply WooCommerce/Classes/POS/Utils/View+WithoutAnimation.swift]: Good observation can be deleted. 👍 Transitions required many iterations to get about right 😀

File: WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift (hunk 2 above)
Comment (staskus) [reply WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift]: Good observation. Would make sense that `Identifiable` is also `Equatable`. I'll check 👍

Comment (staskus) [reply WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift]: Yes, not needed 👍

**Comment by staskus** [comment]
@iamgabrielma, thanks for the review. Made the suggested fixes!

Also, checklist is left:

> Reviewer (or Author, in the case of optional code reviews)

File: WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift (hunk 2 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Card Present Payments/CardPresentPaymentsModalButtonViewModel.swift]: I think `Hashable` is `Equatable` (it inheirits from it, I believe)

`Identifiable` just means you know that this a specific instance, it doesn't let you determine whether one instance equals another.

Similar to pointer comparison vs equality in C-based languages.

**Comment by joshheald** [comment]
One thing I noticed from the video @staskus:

Screengrab from video showing gap in background during transition


There's a gap in the background during the transition from processing to error. Perhaps changing the background of the processing view during the transition as well would fix this? It's not super important, but it is noticable so we should at least add an issue for MVP.

File: WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel.swift [hunk 3]
```diff
@@ -23,6 +24,10 @@ final class PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel: Observabl
     func onAppear() {
         showsInfoSheet = true
     }
+
+    static func == (lhs: PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel, rhs: PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel) -> Bool {
+        lhs.id == rhs.id
+    }
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel.swift:30]: We should implement equatable fully here – identity comparison can lead to issues in future when testing, as we assume that the return would change if any of the underlying properties changed.

I know it's not possible for them to change or differ between instances at the moment, but this implementation isn't resillient to changes in the view model.

As a minimum, we could add a test counting the number of properties (see other view models e.g. `CardPresentPaymentsModalButtonViewModelTests`) to remind ourselves to update the == function if the number of properties changes... but it would be better to also include the other properties, in case they are changed to `var`, or can be passed in with different values through the `init`.

Comment (staskus) [reply WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel.swift:30]: > As a minimum, we could add a test counting the number of properties (see other view models e.g. CardPresentPaymentsModalButtonViewModelTests)

`XCTAssertPropertyCount` is super clever. I have never used it myself! 👍  

I'll add these updates in a next PR.

Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/Card Present Payments/Reader Messages/PointOfSaleCardPresentPaymentCaptureErrorMessageViewModel.swift:30]: > I have never used it myself! 👍
I only added it last week :)
