### PR TITLE
[My Store] Use stored site summary stats for visitors and conversion rate

### LINKED ISSUE #8173: Stats: Adding all visitors from SiteVisitStats can create inaccurate total visitor count
**Describe the bug**

Right now, we're computing a site's total visitor count in the `SiteVisitStats` model by adding together the visitor count for each of the intervals within a given period:

https://github.com/woocommerce/woocommerce-ios/blob/835f9c6abad4cddc848835c8ebee668e83111af8/Networking/Networking/Model/Stats/SiteVisitStats.swift#L43-L48

However, calculating the total visitors this way can be inaccurate. As outlined in [this support doc](https://wordpress.com/support/stats/#views-and-visitors):

> - A view is counted when a visitor loads or reloads a page.
> - A visitor is counted when we see a user or browser for the first time in a selected time frame.

In other words:

If I’m viewing my stats for today, I might see that I’ve had 3 visitors today. I might have 3 visitors every day for a week. However, my total visitors for a week **won’t** necessarily be a sum of the visitors I had for each day of that week (3 + 3 + 3 + 3 + 3 + 3 + 3 = 21 visitors). If I had 3 visitors every day, but they were the _same_ 3 visitors, my total visitor count for the week should be 3 (instead of 21); this is the total we would get if we retrieved the total visitor count with the `week` granularity.

See also this internal discussion: pe5pgL-1eR-p2#comment-1286, pe5pgL-1p6-p2

### PR DESCRIPTION
**Pull request by rachelmcr**
Closes: #8173
⚠️ Depends on #8424 ⚠️ 

## Description

This PR updates the My Store dashboard to use site summary stats (`SiteSummaryStats`) for the "Visitors" and "Conversion" stats for the selected period.

Why we need this:

- Right now, we're computing a site's total visitor count for the entire period by adding together the visitor count for each of the intervals within the period (from `SiteVisitStats` data).
- What we should do in the dashboard — and we're doing already in Analytics Hub — is get the total visitor count for the entire period from `SiteSummaryStats` data. We should continue to get the visitor count for specific intervals from `SiteVisitStats`, to show when an interval is selected in the stats chart.

Note: We should remove the inaccurate `totalVisitors` computed property from `SiteVisitStats`. However, while making these changes I discovered we're also using this property in the store info widget. I've opened #8426 to track that.

### Changes

* Updates the `StatsDataTextFormatter` to have separate methods for getting the visitor count text using `SiteVisitStats` (for a single interval) or using `SiteSummaryStats` (for the entire period). Also removes an unused method.
* Updates `StoreStatsPeriodViewModel` to fetch the `SiteSummaryStats` from storage for the selected time period, and to use those stats for the visitor and conversion text unless a specific interval is selected.
* Updates and adds relevant unit tests.

## Testing instructions

1. Build and run the app.
2. Confirm the "Visitors" and "Conversion" stats load on the My Store dashboard.
3. Confirm you can select a specific interval in the stats chart and the "Visitors" and "Conversion" stats update to reflect the selected interval.
4. Select a different period (Today, This Week, This Month, This Year) and confirm the "Visitors" and "Conversion" stats load as expected for that period.
5. Tap "See more" and confirm the "Conversion" stat on My Store matches the "Conversion Rate" stats in the Sessions card in Analytics.

## Screenshots

/|Dashboard|Analytics
-|-|-
Before|before-dashboard|before-analytics
After|after-dashboard|after-analytics

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
There's a failing unit test that is passing for me locally. I'll take a closer look to get that fixed!

File: WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift [hunk 1]
```diff
@@ -100,7 +100,7 @@ struct StatsDataTextFormatter {
 
     // MARK: Views and Visitors Stats
 
-    /// Creates the text to display for the visitor count.
+    /// Creates the text to display for the visitor count based on SiteVisitStats data and a given interval.
     ///
     static func createVisitorCountText(siteStats: SiteVisitStats?, selectedIntervalIndex: Int?) -> String {
```
Comment (ealeksandrov) [inline WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift]: Can we make `selectedIntervalIndex` non-optional here?
```suggestion
    static func createVisitorCountText(siteStats: SiteVisitStats?, selectedIntervalIndex: Int) -> String {
```

File: WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift [hunk 2]
```diff
@@ -130,7 +132,7 @@ struct StatsDataTextFormatter {
 
     // MARK: Conversion Stats
 
-    /// Creates the text to display for the conversion rate.
+    /// Creates the text to display for the conversion rate based on SiteVisitStats data and a given interval.
     ///
     static func createConversionRateText(orderStats: OrderStatsV4?, siteStats: SiteVisitStats?, selectedIntervalIndex: Int?) -> String {
```
Comment (ealeksandrov) [inline WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift]: Same suggestion as above
```suggestion
    static func createConversionRateText(orderStats: OrderStatsV4?, siteStats: SiteVisitStats?, selectedIntervalIndex: Int) -> String {
```

File: WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsPeriodViewModelTests.swift [hunk 3]
```diff
@@ -632,10 +681,13 @@ final class StoreStatsPeriodViewModelTests: XCTestCase {
 }
 
 private extension StoreStatsPeriodViewModelTests {
-    func createViewModel(timeRange: StatsTimeRangeV4) -> StoreStatsPeriodViewModel {
+    static private let defaultDate = Date(timeIntervalSince1970: 1671123600) // Dec 15, 2022, 5:00:00 PM GMT
```
Comment (ealeksandrov) [inline WooCommerce/WooCommerceTests/ViewRelated/Dashboard/Stats V4/StoreStatsPeriodViewModelTests.swift]: nit: extension is already private
```suggestion
    static let defaultDate = Date(timeIntervalSince1970: 1671123600) // Dec 15, 2022, 5:00:00 PM GMT
```

**Review by ealeksandrov — APPROVED** [review]
Thanks for fixing visitors logic on the dashboard! :shipit:

File: WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift (hunk 1 above)
Comment (rachelmcr) [reply WooCommerce/Classes/ViewRelated/Dashboard/Factories/StatsDataTextFormatter.swift]: Yes, I overlooked that we could do that now! 👍
