### PR TITLE
Dashboard: fix a crash from unexpected number of order stats intervals

### LINKED ISSUE #6333: StoreStatsV4PeriodViewController stringForValue → EXC_BREAKPOINT: Exception 6, Code 21127904, Subcode 8
Sentry Issue: [WOOCOMMERCE-IOS-1DAB](https://sentry.io/organizations/a8c/issues/3047186432/?referrer=github_integration)

```
EXC_BREAKPOINT: Exception 6, Code 21127904, Subcode 8
  File "StoreStatsV4PeriodViewController.swift", in range
  File "<compiler-generated>", in _ArrayBuffer._checkInoutAndNativeTypeCheckedBounds
  File "<compiler-generated>", in Array._checkSubscript
  File "<compiler-generated>", in Array.subscript.getter
  File "StoreStatsV4PeriodViewController.swift", line 467, in StoreStatsV4PeriodViewController.stringForValue
...
(58 additional frame(s) were not displayed)
```

### LINKED ISSUE #7703: StoreStatsV4PeriodViewController EXC_BREAKPOINT: Exception 6, Code 80695708, Subcode 8
Sentry Issue: [WOOCOMMERCE-IOS-1DJV](https://sentry.io/organizations/a8c/issues/3558985660/?referrer=github_integration)

```
EXC_BREAKPOINT: Exception 6, Code 80695708, Subcode 8
  File "<compiler-generated>", in _ArrayBuffer._checkInoutAndNativeTypeCheckedBounds
  File "<compiler-generated>", in Array._checkSubscript
  File "<compiler-generated>", in Array.subscript.getter
  File "<compiler-generated>", in StoreStatsV4PeriodViewController.stringForValue
  File "<compiler-generated>", in StoreStatsV4PeriodViewController.stringForValue
...
(69 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #7703 
Most likely also fixes #6333

### Description

For a long time, we've been haunted by a crash from a delegate method from the Charts framework to generate the string value for an x-axis value (index of the line chart). The crash occurs on and off, often surging around days with the daylight saving time (DST) change in certain regions in the world. This time, fortunately, I was able to reproduce it on one iOS 15.4 device (I cannot reproduce it on the other iOS 15.6 test device).

### Root cause

In `StoreStatsPeriodViewController`, we currently assume the given `value` corresponds to the index of the data values on the x-axis (the index of order stats intervals):

https://github.com/woocommerce/woocommerce-ios/blob/63a3e846101740eff109068ee1807e8bd60b2e72/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StoreStatsV4PeriodViewController.swift#L493-L498

On days with DST change, there was only 1 order stats interval returned from the API (which is unexpected with reason below). In this case where there is only one interval, Charts library has [this logic](https://github.com/danielgindi/Charts/blob/2c77b2b8a4ccb82a36260b44b2c794683cc6f17b/Source/Charts/Components/AxisBase.swift#L345-L353) to set the x-axis's `entries` to `[-1, 0, 1]` and then calls `StoreStatsV4PeriodViewController: AxisValueFormatter`'s `stringForValue(:axis:)` to get the value for each x-axis entry. The app crashes when the x-axis entry is `-1` (and I'm sure it will crash for value `1` as well because it's out of bound). When there is more than one order stats interval, the x-axis `entries` is set properly for each interval index.

The reason why there is only 1 order stats interval fetched/returned is because of how the end of today is calculated in `Date.endOfDay(timezone:)`. Before this PR, the end of a date is calculated by adding 1 day minus 1 second to the start of the given date:

https://github.com/woocommerce/woocommerce-ios/blob/63a3e846101740eff109068ee1807e8bd60b2e72/WooCommerce/Classes/Extensions/Date%2BStartAndEnd.swift#L13-L19

On the day with daily saving time, 0-1 AM is non-existent at least in Chile (each region might be different) and thus the start of today is actually 1 AM instead of 12 AM. After adding 1 day minus 1 second, the end of today becomes the next day at 12:59:59 AM instead of 11:59:59 PM of the same day. In the order stats API request, we then calculate the "start of today" using the "end of today", therefore only 1 interval is fetched (12-1 AM the next day). In order to fix it, the logic is updated to 1 second minus the **start of the next day**.

### Target release

I decided to target the frozen 10.3 because at least Iran and New Zealand might expect a DST change at the end of September from the [DST Wiki](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country). Release 10.4 has code freeze on September 16, and might be too late for the next DST change in Iran on September 20/21.

### Testing instructions

Prerequisite: in device settings > General, set the Date & Time to September 11, 2022, in Santiago, Chile. Also, set the region in Language & Region to Chile. Somehow I cannot reproduce this on an iOS 15.6 device, probably because DST was [recently removed by the Chile government](https://www.ghacks.net/2022/09/07/windows-users-in-chile-could-run-into-issues-because-of-daylight-savings-time/) and not every device receives the updates. You can also test this in a simulator, but updating the Mac time might be more problematic (some websites might stop working). Make sure to revert the device time to be automatic after testing, I couldn't use mobile payment services when buying lunch due to this time hack 😅 .

- Launch the app in the logged-in state --> the app might crash on `trunk`, and does not crash anymore with the PR branch

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jaclync** [comment]
cc @oguzkocer I'm targeting this crash fix to release 10.3 as a hotfix, since there could be a surge for the next daylight saving time change in some countries near the end of September (Iran and New Zealand). Please let me know if you think it makes more sense to target `trunk` instead!

**Review by itsmeichigo — APPROVED** [review]
Thank you for the detailed explanations!

I could not reproduce the crash on either my device (iOS 14) or the simulator, but I'm approving since the logic makes sense to me.

@selanthiraiyan please feel free to test and verify this PR if you can, thanks!

**Comment by selanthiraiyan** [comment]
I couldn't reproduce the crash on my iOS 15.6 device. 

Thanks to the detailed PR description, the changes look good to me. 👍

File: WooCommerce/Classes/Extensions/Date+StartAndEnd.swift [hunk 1]
```diff
@@ -12,10 +12,25 @@ extension Date {
...
-        var components = DateComponents()
-        components.day = 1
-        components.second = -1
-        return calendar.date(byAdding: components, to: startOfDay(timezone: timezone))!
+
+        let startOfNextDay: Date = {
+            var components = DateComponents()
+            components.day = 1
+            guard let nextDay = calendar.date(byAdding: components, to: startOfDay(timezone: timezone)) else {
+                fatalError("The next day cannot be calculated for \(self) with time zone \(timezone)")
```
Comment (Ecarrion) [inline WooCommerce/Classes/Extensions/Date+StartAndEnd.swift]: Do you think we should use `logErrorAndExit` so we can monitor the occurrence of these?

Comment (jaclync) [reply WooCommerce/Classes/Extensions/Date+StartAndEnd.swift]: Great point, I forgot that the error message in `fatalError` isn't logged in Sentry. Updated in https://github.com/woocommerce/woocommerce-ios/pull/7704/commits/f921d01c11e4268295b63b94b1017ea4af0f1764

**Comment by jaclync** [comment]
Thanks for testing @itsmeichigo @selanthiraiyan and the suggestion @Ecarrion! Merging now to release 10.3 (cc @oguzkocer)
