### PR TITLE
Changes OrderItem.quantity from Int to Decimal

### LINKED ISSUE #662: API: Account for non-integer quantities when syncing orders
**Describe the bug**
When an order contains a non-integer quantity, the app cannot sync orders.

**To Reproduce**
1. Install a plugin that allows you to use non-integer quantities or edit the data.
2. Add an order with a line item quantity of something like 1.5.
3. Try syncing orders.
4. See error similar to:

```
2019-02-05 19:37:34.167538-0600 WooCommerce[18821:393260] ⛔️ Error synchronizing orders: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "line_items", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "quantity", intValue: nil)], debugDescription: "Parsed JSON number <1.5> does not fit in Int.", underlyingError: nil))
```

**Screenshots**
simulator screen shot - iphone xr - 2019-02-05 at 19 37 35

**Expected behavior**
I guess I'm not sure what's expected. We could nil out the quantity and show some placeholder maybe? Not sure what to do here.

Whatever change we make lets coordinate with Android too so we're consistent. 😄 

**Mobile Environment**
Please include:
- Device: Simulator
- iOS version: 12
- WooCommerce iOS version: develop (1.2)

1758607-zen

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #662, #125

Adds a new data model for OrderItem.quantity to move to a Decimal data type to support extensions that change it from Integer. This is useful for stores that sell partial quantities (like by weight in 1.5 pounds).

I added `IterativeStoreMigrator` that is based off of the ALIterativeMigrator used in the WordPress app. This is an entirely new Swift file and probably needs some attention to code style and Swift-ness. I tried to do as good as I could but I'm a tad rusty and could really use your help.

There are two unit tests that cover the iterative migrator. This ensures that Model 1 to Model 10 fails without using the iterative migrator, and then succeeds when it is used.

# Testing
1. Switch back to develop. Clean, rebuild, and launch.
2. Sign in, make sure to fetch orders.
3. Kill the app.
4. Close Xcode, switch to this branch.
5. Reload Xcode, clean, rebuild, and launch.
6. Switch to orders tab - orders should already be present.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: Storage/Storage/CoreData/CoreDataManager.swift [hunk 1]
```diff
@@ -120,10 +122,50 @@ public class CoreDataManager: StorageManagerType {
...
+
+        guard managedModel.isConfiguration(withName: nil, compatibleWithStoreMetadata: metadata) == false else {
+            // Configuration is compatible, no migration necessary.
+            return
+        }
+
+        DDLogWarn("⚠️ [CoreDataManager] Migration required for persistent store")
+
+        // Extract model names
+        let versionPath = modelURL.appendingPathComponent("VersionInfo.plist").path
```
Comment (mindgraffiti) [inline Storage/Storage/CoreData/CoreDataManager.swift]: Nitpicky - one of the standards we follow is to find all the strings and add them to a `Constants` struct at the end of the file so they are easier to find and edit down the road. So this could be `modelURL.appendingPathComponent(Constants.versionInfo).path`.

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift [hunk 2]
```diff
@@ -0,0 +1,220 @@
...
+            try files.forEach { (file) in
+                if file.hasPrefix(tempDestinationURL.lastPathComponent) {
+                    let fullPath = tempDestinationURL.deletingLastPathComponent().appendingPathComponent(file).path
+                    let toPath = url.deletingLastPathComponent().appendingPathComponent(file).path
+                    try? fileManager.removeItem(atPath: toPath)
+                    try fileManager.moveItem(atPath: fullPath, toPath: toPath)
+                }
+            }
+        } catch {
+            DDLogError("Error while copying migrated over the original files: \(error)")
```
[the remark this answers is not in the document]
Comment (bummytime) [reply Storage/Storage/CoreData/IterativeStoreMigrator.swift]: Agree! It's just a little something we do to make errors stick out more in the console.

File: RELEASE-NOTES.txt [hunk 3]
```diff
@@ -1,3 +1,7 @@
+Release 1.3
```
Comment (bummytime) [inline RELEASE-NOTES.txt]: You'll want to merge in the latest release notes from `develop` (which is currently empty). Also, I am (pretty) sure you don't have to create labels like this because the Platform gang clears this file with every release — just adding a single bullet item is sufficient.

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift [hunk 4]
```diff
@@ -0,0 +1,220 @@
+import Foundation
+import CoreData
+
+/// CoreDataIterativeMigrator: Migrates through a series of models to allow for users to skip app versions without risk.
+/// This was derived from ALIterativeMigrator originally used in the WordPress app.
+///
+public struct CoreDataIterativeMigrator {
```
Comment (bummytime) [inline Storage/Storage/CoreData/IterativeStoreMigrator.swift]: Love the inline docs here!

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift [hunk 5]
```diff
@@ -0,0 +1,220 @@
...
+            }
+        }
+
+        // Ensure that the source model is at the start of the list.
+        if reverse {
+            modelsToMigrate = modelsToMigrate.reversed()
+        }
+
+        // Migrate through the list
+        for index in 0...(modelsToMigrate.count - 2) {
```
Comment (bummytime) [inline Storage/Storage/CoreData/IterativeStoreMigrator.swift]: Tiny nit: As a note to our future selves it might be worthwhile to expound on this comment to explain what is happening here (e.g. why `count - 2`).

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift [hunk 6]
```diff
@@ -0,0 +1,220 @@
...
+        // and store the resulting data at the temporary path.
+        let migrator = NSMigrationManager(sourceModel: fromModel, destinationModel: toModel)
+        do {
+            try migrator.migrateStore(from: url, sourceType: storeType, options: nil, with: mappingModel, toDestinationURL: tempDestinationURL, destinationType: storeType, destinationOptions: nil)
+        } catch {
+            return false
+        }
+
+        // Move the original source store to a backup location.
+        let backupURL = url.deletingLastPathComponent().appendingPathComponent("backup")
```
Comment (bummytime) [inline Storage/Storage/CoreData/IterativeStoreMigrator.swift]: Nit: To make the `migrateStore()` func a little more manageable, perhaps we could refactor this `Move original source store to a backup location.` logic into a separate func?

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift [hunk 7]
```diff
@@ -0,0 +1,220 @@
...
+                    try fileManager.moveItem(atPath: fullPath, toPath: toPath)
+                }
+            }
+        } catch {
+            DDLogError("Error while moving original source store to a backup location: \(error)")
+
+            return false
+        }
+
+        // Copy migrated over the original files
```
Comment (bummytime) [inline Storage/Storage/CoreData/IterativeStoreMigrator.swift]: Similar to my previous comment, perhaps we could move this `Copy migrated over the original files` logic into a separate func?

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift [hunk 8]
```diff
@@ -0,0 +1,220 @@
...
+            guard migrateStore(at: sourceStore, storeType: storeType, fromModel: modelFrom, toModel: modelTo, with: migrateWithModel) == true else {
+                return false
+            }
+        }
+
+        return true
+    }
+}
+
+extension CoreDataIterativeMigrator {
```
Comment (bummytime) [inline Storage/Storage/CoreData/IterativeStoreMigrator.swift]: Style nit: since it appears all of the funcs within this extension are `private`, we could just make the extension itself private and then remove all of the `private` declarations from each function.

File: RELEASE-NOTES.txt (hunk 3 above)
Comment (astralbodies) [reply RELEASE-NOTES.txt]: Ahha - I thought it was a running list. 👍

**Comment by bummytime** [comment]
Housekeeping note this PR also fixes #125 :-)

File: Storage/Storage/CoreData/IterativeStoreMigrator.swift (hunk 2 above)
[the remark this answers is not in the document]
Comment (astralbodies) [reply Storage/Storage/CoreData/IterativeStoreMigrator.swift]: I should really create our own custom logger to add these based on the logging level

[the remark this answers is not in the document]
Comment (bummytime) [reply Storage/Storage/CoreData/IterativeStoreMigrator.swift]: @astralbodies that is a great idear — ⛔️ for errors and ⚠️ for warnings. What we do now just evolved over time of course ;-)

File: Storage/Storage/CoreData/CoreDataManager.swift [hunk 9]
```diff
@@ -120,10 +122,50 @@ public class CoreDataManager: StorageManagerType {
...
+            let objectModel = NSManagedObjectModel(contentsOf: modelURL) else {
+            return
+        }
+
+        let sortedKeys = allKeys.sorted { (string1, string2) -> Bool in
+            return string1.compare(string2, options: [String.CompareOptions.numeric], range: nil, locale: nil) == ComparisonResult.orderedAscending
+        }
+
+        do {
+            let migrateResult = try CoreDataIterativeMigrator.iterativeMigrate(sourceStore: storeURL, storeType: NSSQLiteStoreType, to: objectModel, using: sortedKeys)
```
[the remark this answers is not in the document]
Comment (astralbodies) [reply Storage/Storage/CoreData/CoreDataManager.swift]: There are some cases where the function may not throw any errors but still return `false` so I wanted to make sure some logging happened here. As I was "converting" ALIterativeMigrator over to our project I realized the code was kind of crap...

**Comment by astralbodies** [comment]
@bummytime @mindgraffiti This is ready for another review!

**Comment by mindgraffiti** [comment]
+1 on the unit tests and nice documentation on the `count - 2` 

```(you can't migrate the last model to nothingness)```
😀 

Looks good to me.
