### PR TITLE
Fix regression issue in error parsing

### LINKED ISSUE #11192: My Store: Error banner is always displayed for free trial sites
## Description
Reported by @pmusolino:

> when I create a new store I’m always getting the banner on top We couldn't load your data :thinking_face: any idea why it happens?

Internal discussion: p1699998751668909-slack-C03L1NF1EA3.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #11192 

## What

This PR fixes a regression test in the way we parse errors that contain response data.

## Why
We have recently added new changes to how errors are parsed to catch responses from REST API requests. We are currently mapping [only](https://github.com/woocommerce/woocommerce-ios/blob/f2fadd1cba3a36dab415697339c01692f06b687d/Networking/Networking/Remote/Remote.swift#L304) `unacceptableStatusCode` errors, while there are other cases of `NetworkError` that contain response data.

## How
- Added an extension for `NetworkError` to get the accompanied response data if available.
- Updated `mapNetworkError` to get response from `NetworkError` and attempt mapping with the validator if possible.

## Testing instructions

- Create a new free trial site on the app.
- When the store creation is done, notice that the banner `We couldn't load your data` is not displayed on the My Store screen even though requests to the `stats/` endpoints fail with 404 error (message "This blog does not have the Stats module enabled"). 

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: Networking/Networking/Remote/Remote.swift [hunk 1]
```diff
@@ -301,8 +301,7 @@ private extension Remote {
         /// We will to attempt to validate the response using `ResponseDataValidator`
         /// if the error status code is unacceptable
```
Comment (selanthiraiyan) [inline Networking/Networking/Remote/Remote.swift]: I think we should update this comment.

File: Networking/Networking/Network/NetworkError.swift [hunk 2]
```diff
@@ -21,6 +21,19 @@ public enum NetworkError: Error, Equatable {
 
     /// Error for REST API requests with invalid cookie nonce
     case invalidCookieNonce
+
+    var response: Data? {
```
Comment (selanthiraiyan) [inline Networking/Networking/Network/NetworkError.swift:26]: Kindly consider adding a comment to explain this property.

**Review by selanthiraiyan — APPROVED** [review]
Thanks for fixing this, Huong! 👏 

Nice tests. ❤️

File: Networking/Networking/Remote/Remote.swift (hunk 1 above)
Comment (itsmeichigo) [reply Networking/Networking/Remote/Remote.swift]: Done in d2de940cb552fb2102c003ef68d052e69d15cfaa.

File: Networking/Networking/Network/NetworkError.swift (hunk 2 above)
Comment (itsmeichigo) [reply Networking/Networking/Network/NetworkError.swift:26]: Also done in d2de940cb552fb2102c003ef68d052e69d15cfaa.
