### PR TITLE
No discard confirmation when exiting product details

### LINKED ISSUE #13571: [Products] No discard confirmation when exiting product details
**Describe the bug**

There is no discard confirmation if I exit the product details with unsaved changes. My changes are just discarded with no warning. (Tested on device.)

**To Reproduce**

1. Go to the Products tab.
2. Create a new product or select an existing product.
3. Add or change product details.
4. Tap the back button to exit the product details and notice there is no confirmation before the changes are discarded.

**Screenshots**

https://github.com/user-attachments/assets/04f28108-1802-47af-90c7-079dd352326e

**Expected behavior**

I expect a discard confirmation dialog if there are unsaved changes to the product.

### PR DESCRIPTION
**Pull request by bozidarsevo**
Closes: #13571

## Description

There was no discard confirmation if I exit the product details with unsaved changes. The changes were just discarded with no warning.

Changes are explained in the files changed but basically some delegate calls are changed and navigation checks.

One thing that is still problematic is the swipe back gesture when in first screen of product details, that looks to be broken in general, here is a ticket I created for it: #13651

https://github.com/user-attachments/assets/51aefbdd-4339-4d63-92e5-41aa590a92ce

## Testing information

1. Go to the **Products** tab.
2. **Create** a new product or **select** an existing product.
3. **Add** or **change** product details. Do it on the initial product screen and detailed screens like product price
4. Tap the back button to exit the product details and notice there is confirmation sheet to discard changes or cancel.

## Screenshots

Simulator Screen Recording - iPhone 15 Pro - 2024-08-19 at 11 35 03

Simulator Screen Recording - iPad za test - 2024-08-19 at 11 36 36

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/Extensions/UINavigationController+Woo.swift [hunk 1]
```diff
@@ -57,30 +57,20 @@ extension UIViewController: UINavigationBarBackButtonHandler {
...
         if let vc = topViewController {
             shouldPop = vc.shouldPopOnBackButton()
         }
 
-        if shouldPop {
-            DispatchQueue.main.async {
-                self.popViewController(animated: true)
-            }
-        }
-        return false
```
Comment (bozidarsevo) [inline WooCommerce/Classes/Extensions/UINavigationController+Woo.swift:83]: Since the delegate method checks if bar should pop I figured it is best to just return if it should pop or not and let the system do the popping itself.

File: WooCommerce/Classes/Extensions/UINavigationController+Woo.swift [hunk 2]
```diff
@@ -57,30 +57,20 @@ extension UIViewController: UINavigationBarBackButtonHandler {
...
+        return shouldPop
+    }
+
+    // This delegate method is not called on the simulator or device running iOS 13.4 from Xcode.
+    // You need to use a release build.
+    public func navigationBar(_ navigationBar: UINavigationBar, shouldPop item: UINavigationItem) -> Bool {
+        return checkIfNavigationBarShouldPop(navigationBar, item: item)
     }
```
Comment (bozidarsevo) [inline WooCommerce/Classes/Extensions/UINavigationController+Woo.swift]: I left the delegate method as it was and created a separate `checkIfNavigationBarShouldPop` method that is called from here and from `WooNavigationController`

File: WooCommerce/Classes/System/WooNavigationController.swift [hunk 3]
```diff
@@ -30,6 +30,19 @@ class WooNavigationController: UINavigationController {
...
+            return vc.shouldPopOnBackButton()
+        }
+        return shouldPopOnBackButton()
+    }
+}
+
+extension WooNavigationController {
+    public override func navigationBar(_ navigationBar: UINavigationBar, shouldPop item: UINavigationItem) -> Bool {
+        self.checkIfNavigationBarShouldPop(navigationBar, item: item)
+    }
```
Comment (bozidarsevo) [inline WooCommerce/Classes/System/WooNavigationController.swift]: Overriding it in an extension of `WooNavigationController` because when it was just for `UINavigationController` it was not being called.

File: WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift [hunk 4]
```diff
@@ -1295,7 +1295,7 @@ private extension ProductFormViewController {
 private extension ProductFormViewController {
     func presentBackNavigationActionSheet(onDiscard: @escaping () -> Void = {}, onCancel: @escaping () -> Void = {}) {
         let exitForm: () -> Void = {
-            presentationStyle.createExitForm(viewController: self, completion: onDiscard)
+            presentationStyle.createExitForm(viewController: navigationController ?? self, completion: onDiscard)
```
Comment (bozidarsevo) [inline WooCommerce/Classes/ViewRelated/Products/Edit Product/ProductFormViewController.swift:1298]: `ProductFormViewController` on iPhones is in a bit different view controller navigation hierarchy.
Here you get this:

```
(lldb) po self
<_TtGC11WooCommerce25ProductFormViewControllerCS_20ProductFormViewModel_: 0x120082800>
(lldb) po self.navigationController
▿ Optional<UINavigationController>
  ▿ some : <WooCommerce.WooNavigationController: 0x10d104600>
(lldb) po self.navigationController?.viewControllers
▿ Optional<Array<UIViewController>>
  ▿ some : 1 element
    ▿ 0 : <_TtGC11WooCommerce25ProductFormViewControllerCS_20ProductFormViewModel_: 0x120082800>
```

```
(lldb) po self.navigationController?.navigationController
▿ Optional<UINavigationController>
  - some : <WooCommerce.WooTabNavigationController: 0x10d095200>
(lldb) po self.navigationController?.navigationController?.viewControllers
▿ Optional<Array<UIViewController>>
  ▿ some : 2 elements
    ▿ 0 : <WooCommerce.ProductsViewController: 0x10d105c00>
    ▿ 1 : <WooCommerce.WooNavigationController: 0x10d104600>
```

So the `ProductFormViewController` is the only view controller in its own navigation controller, so we need to go 1 level up in the navigation hierarchy.

File: WooCommerce/Classes/Extensions/UINavigationController+Woo.swift [hunk 5]
```diff
@@ -46,7 +46,7 @@ protocol UINavigationBarBackButtonHandler {
     /// Should block the 'Back' button action
     ///
     /// - Returns: true - don't block，false - block
-    func  shouldPopOnBackButton() -> Bool
+    func shouldPopOnBackButton() -> Bool
```
Comment (bozidarsevo) [inline WooCommerce/Classes/Extensions/UINavigationController+Woo.swift:49]: Just removed an extra whitespace

File: WooCommerce/Classes/Extensions/UINavigationController+Woo.swift [hunk 6]
```diff
@@ -57,30 +57,20 @@ extension UIViewController: UINavigationBarBackButtonHandler {
...
-    // This delegate method is not called on the simulator or device running iOS 13.4 from Xcode.
-    // You need to use a release build.
-    public func navigationBar(_ navigationBar: UINavigationBar, shouldPop item: UINavigationItem) -> Bool {
-        guard let items = navigationBar.items else {
-            return false
-        }
-
-        if viewControllers.count < items.count {
-            return true
-        }
```
Comment (bozidarsevo) [inline WooCommerce/Classes/Extensions/UINavigationController+Woo.swift]: I removed this check because the check did not make sense to me since there could be many items and this way we would always return `true` and would not call `shouldPopOnBackButton()`

Comment (rachelmcr) [reply WooCommerce/Classes/Extensions/UINavigationController+Woo.swift]: Agreed, I tried to make sense of this check and don't understand why it would be needed here. I also found examples of where it leads to the wrong result, so removing it makes sense to me.

That said, since the only thing we're now checking is essentially `topViewController.shouldPopOnBackButton()` should we add a check to make sure the navigation item we're popping corresponds to the top view controller? Something like:

```
guard let vc = topViewController, vc.navigationItem == item else {
    return true
}
```

File: WooCommerce/Classes/Extensions/UINavigationController+Woo.swift [hunk 7]
```diff
@@ -57,30 +57,20 @@ extension UIViewController: UINavigationBarBackButtonHandler {
...
-
+    public func checkIfNavigationBarShouldPop(_ navigationBar: UINavigationBar, item: UINavigationItem) -> Bool {
```
Comment (rachelmcr) [inline WooCommerce/Classes/Extensions/UINavigationController+Woo.swift]: nit: Could we simplify this method since we aren't using its parameters (assuming we don't add any additional checks here)?

```suggestion
    public func checkIfNavigationBarShouldPop() -> Bool {
```

File: WooCommerce/Classes/Extensions/UINavigationController+Woo.swift [hunk 8]
```diff
@@ -57,30 +57,20 @@ extension UIViewController: UINavigationBarBackButtonHandler {
...
-            DispatchQueue.main.async {
-                self.popViewController(animated: true)
-            }
-        }
-        return false
+        return shouldPop
+    }
+
+    // This delegate method is not called on the simulator or device running iOS 13.4 from Xcode.
+    // You need to use a release build.
```
Comment (rachelmcr) [inline WooCommerce/Classes/Extensions/UINavigationController+Woo.swift]: nit: Since it's working in a simulator now, how about updating this documentation (and/or adding documenting to the `WooNavigationController` extension) to explain that?

File: WooCommerce/Classes/System/WooNavigationController.swift (hunk 3 above)
Comment (rachelmcr) [reply WooCommerce/Classes/System/WooNavigationController.swift]: Nice!

File: WooCommerce/Classes/System/WooNavigationController.swift [hunk 9]
```diff
@@ -30,6 +30,19 @@ class WooNavigationController: UINavigationController {
     override var preferredStatusBarStyle: UIStatusBarStyle {
         return StyleManager.statusBarLight
     }
+
+    override func shouldPopOnBackButton() -> Bool {
+        if let vc = topViewController {
+            return vc.shouldPopOnBackButton()
+        }
+        return shouldPopOnBackButton()
```
Comment (rachelmcr) [inline WooCommerce/Classes/System/WooNavigationController.swift]: Should this include `super`?

```suggestion
        return super.shouldPopOnBackButton()
```

**Review by rachelmcr — COMMENTED** [review]
Tests well! These changes are clear and it's so nice that everything works as expected in the simulator, too ❤️ 

I just have a couple questions to make sure we're covering all of our bases if the navigation doesn't go as expected. (And a couple nits, but those aren't blockers.)

**Review by rachelmcr — APPROVED** [review]
Looks great! :shipit:
