### PR TITLE
[Orders with Coupons] Calculate price with discount when multiple items

### LINKED ISSUE #11015: [Orders with Coupons] `Price after discount` shows incorrectly if we have multiple items of the same type
Adding a discount to a product row with 1+ items will show `Price after discount` incorrectly, since this is only shown as "price of the product - discount"

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #11015 

## Description
This PR addresses a bug in the Order Creation screen when we have an item with a discount applied to it but the `Order Count` is more than 1. The `Price after discount` row currently only shows the price after discount for 1 item, rather than multiple items, causing confusion.

| Before | After |
|--------|--------|
|  | Simulator Screenshot - iPhone 15 - 2023-10-26 at 11 34 52 | 

## Testing instructions
- Go to `Orders` > `+` > Add a Product to your order
- Tap on the chevron to expand the product row, tap on `+Add discount`
- Enter a value, and `Add` (please note that there are known bugs with discounts, like being able to add discounts higher than the value of the item).
- Observe that now in Order Creation, if the quantity of the product is increased or decreased via `+` and `-` buttons, we have the correct `Price after discount` being displayed, since takes into account how many products are there, but applies an unique discount to the product row.

| 1 item | More than 1 item |
|--------|--------|
|Simulator Screenshot - iPhone 15 - 2023-10-26 at 11 34 29|Simulator Screenshot - iPhone 15 - 2023-10-26 at 11 34 52|

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift [hunk 1]
```diff
@@ -140,6 +140,24 @@ final class ProductRowViewModel: ObservableObject, Identifiable {
...
+        }
+        guard let priceDecimal = currencyFormatter.convertToDecimal(price) else {
+            return nil
+        }
+        let quantityDecimal = NSDecimalNumber(decimal: quantity)
+        let subtotalDecimal = priceDecimal.multiplying(by: quantityDecimal)
+        let totalPriceAfterDiscount = subtotalDecimal.subtracting((discount ?? Decimal.zero) as NSDecimalNumber)
+
+        return currencyFormatter.formatAmount(totalPriceAfterDiscount) ?? ""
+
```
Comment (joshheald) [inline WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift]:
```suggestion
        guard let price = price,
              let priceDecimal = currencyFormatter.convertToDecimal(price) else {
            return nil
        }
        let subtotalDecimal = priceDecimal.multiplying(by: quantity as NSDecimalNumber)
        let totalPriceAfterDiscount = subtotalDecimal.subtracting((discount ?? Decimal.zero) as NSDecimalNumber)

        return currencyFormatter.formatAmount(totalPriceAfterDiscount)
```

Optional, just tightens it up a little. Changes: 
- A single guard statement as the `else` is identical.
- Uses the cast to NSDecimalNumber for `quantity`, rather than making a new variable.
- Avoids returning an empty string given the optional signature.

**Review by joshheald — APPROVED** [review]
Works as described, but I think there's still more to do on this one. In the Add Discount screen, it shows the price after discount based on price alone, even though it shows the line total in the minimal product card too:

price-after-discount-in-discount-screen

That said... this begs a further question: "Is this a discount on the price, or the line total?" 

If it's a discount on the price, not the line total, the `Add discount` screen is pretty much right, but the product card and line total on the `Order Details` screen are wrong – they should have the discount multiplied by the quantity as well. That's suggested by the un-discounted state of the `Add discount` screen.

price-after-discount-on-unpopulated-add-discount-screen

I think the correct answer is probably dictated by what the API does, i.e. when we add a discount it's a discount to the line total, not the item price, so we should change the `Add discount` screen to make it clear that the line total is being discounted, not the item price.

I've also made a minor suggestion for tightening up the `totalPriceAfterDiscountLabel` method.

File: WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductRowViewModel.swift]: Thanks for the tips, changed here: https://github.com/woocommerce/woocommerce-ios/pull/11016/commits/6c7c559611624e7cfbdb2fcadf808b2f5c1e369a

**Comment by iamgabrielma** [comment]
Thanks for the review!

> Is this a discount on the price, or the line total?
> when we add a discount it's a discount to the line total, not the item price, so we should change the Add discount screen to make it clear that the line total is being discounted, not the item price.

That's a good point, and also an indicative of why I didn't notice this bug initially. I agree that it's important to discern "product discount" from "line total discount" here and can cause confusion to merchants down the road.

I'll check with design folks to see if there's any preferred way to iterate through this 👍
