### PR TITLE
[Woo POS] Present full-screen views when item list is empty or returns an error

### LINKED ISSUE #12815: [Woo POS] M2 Empty: Product list
Ref: p1716432162915869-slack-C070SJRA8DP

Design screenshot of empty product list

### LINKED ISSUE #13360: [Woo POS] M2: Use full-screen on product list error/empty load
When product list fails to load or errors out, we should hide other view components that are permanently shown, for example the `CartView` or the `HeaderBanner`: 

Image
Screenshot 2024-07-17 at 13 23 57

### LINKED ISSUE #13480: [Woo POS] M2 Error: Loading products
Image

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #13360
Closes: #12815
Closes: #13480

## Description
Previously, if an error happened when loading products, we displayed it within the `ItemList` view, but the cart and the rest of the components could also be seen on screen. 

This PR changes this to show a full-screen error view instead, both for the cases when the item list fails by throwing an error, or when the item list loads with zero products. 

In each case we display a different view. The UI for both screens still needs some adjustments and tweaking to fit the latest designs, but this can be tackled separately.

## Testing
- Load POS
- Intercept the call to`ItemListViewModel.populatePointOfSaleItems()` and throw an error
- Observe that the error view is shown.
- Tap the Retry button
- Do not intercept it, observe that the dashboard is loaded normally.
- Repeat by changing `ItemListViewModel.populatePointOfSaleItems()` to return an empty list of items
```diff
- items = try await itemProvider.providePointOfSaleItems()
+ items = []
```
- Observe the empty view is shown.

| Error view | Empty view |
|--------|--------|
| Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-08-09 at 11 32 10 | Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-08-09 at 11 33 21 |

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift [hunk 1]
```diff
@@ -31,6 +31,8 @@ final class PointOfSaleDashboardViewModel: ObservableObject {
     /// This boolean is used to determine if the whole totals/payments view is occupying the full screen (cart is not showed)
     @Published var isTotalsViewFullScreen: Bool = false
     @Published var isInitialLoading: Bool = false
+    @Published var isError: Bool = false
+    @Published var isEmpty: Bool = false
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift:29]: I think we can simplify this bit by either moving the isInitialLoading state to `ItemListState`, or creating a new DashboardState with several cases (isInitialLoading, isLoaded, isError, isEmpty). By having these booleans we need to be sure to switch them accordingly when observing state, otherwise we could land on unexpected/wrong state. 

It would also simplify loading the views, since we can use a switch, and the `observeItemListState` method.

Thoughts? @staskus I'm leaning towards the dashboard state option, since we no longer need to show any empty or error cases within the ItemList view, as these are full screen now.

File: WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift [hunk 2]
```diff
@@ -121,44 +126,13 @@ extension ItemListViewModel {
         let buttonText: String
     }
 
-    struct EmptyModel: Equatable {
-        // TODO:
-        // Differentiate between empty with no products vs empty with no eligible products
-        // https://github.com/woocommerce/woocommerce-ios/issues/12815
-        // https://github.com/woocommerce/woocommerce-ios/issues/12816
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/ViewModels/ItemListViewModel.swift:133]: We no longer make this distinction, so we can simplify the .empty case.

File: WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift (hunk 1 above)
Comment (staskus) [reply WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift:29]: Yes, I think we can remove `ItemListState` for the view model, and have a similar functionality for the dashboard. `ItemList` no longer has error or loading states, we're showing everything in `PointOfSaleDashboardView`.

Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewModels/PointOfSaleDashboardViewModel.swift:29]: Great! I started to refactor it but as shared I think we want to do this separately so we're sure to test it properly on its own PR. I've opened a follow-up here: https://github.com/woocommerce/woocommerce-ios/issues/13543

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift [hunk 3]
```diff
@@ -14,15 +14,15 @@ struct ItemListView: View {
         VStack {
             headerView
             switch viewModel.state {
-            case .empty(let emptyModel):
-                emptyView(emptyModel)
+            case .empty, .error:
+                // These cases are handled directly in the dashboard, we do not render
+                // a specific view within the ItemListView to handle them
+                EmptyView()
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Presentation/ItemListView.swift:20]: Bit of a drive-by as I'm also looking at errors...

What's the benefit of handling the empty and error states in the Dashboard? 

I would expect that it was a cleaner separation of concerns for the ItemListView to show its own empty/error views.

I think it's because they are full screen, but you could delegate the fullscreen logic to the Dashboard view, while implementing the error/empty states here still.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+        self.viewModel = viewModel
+    }
+
+    var errorContents: ItemListViewModel.ErrorModel {
+        guard let errorContents = viewModel.state.hasError else {
+            return ItemListViewModel.ErrorModel(title: "Unknown error",
+                                                subtitle: "Unknown error",
+                                                buttonText: "Retry")
+        }
+        return errorContents
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Depending on the view model for another view seems like a bit of a code smell. I know they're related, but you could potentially simplify this view by having it depend on `errorContents` and a reload action closure.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+            value: "Products",
+            comment: "Title for the Point of Sale screen"
+        )
+    }
+    enum Constants {
+        static let headerPadding: CGFloat = 8
+        static let headerSpacing: CGFloat = 16
+        static let titleFont: Font = .system(size: 40, weight: .bold, design: .default)
+        static let buttonPadding: CGFloat = 240
+    }
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: We're going to have a few errors with shared style – perhaps move these out to a shared Layout object as we've done in `PointOfSaleCardPresentPaymentLayout`?

**Review by joshheald — COMMENTED** [review]
Just some thoughts... it would be good to avoid overloading DashboardView with too many concerns...

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift (hunk 3 above)
Comment (staskus) [reply WooCommerce/Classes/POS/Presentation/ItemListView.swift:20]: I started this trend with putting `PointOfSaleLoadingView()` on top of `PointOfSaleDashboardView`. 

I initially started by implementing it in ItemList but I found it hard to work with, since we expect this loading to appear above all the content, it was especially problematic UI-wise because of a previous version of a toolbar. However, maybe now it would be possible to implement it in `ItemListView` as well.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+struct PointOfSaleItemListEmptyView: View {
+    var body: some View {
+        VStack(alignment: .center, spacing: Constants.headerSpacing) {
+            Text(Localization.productTitle)
+                .frame(maxWidth: .infinity, alignment: .leading)
+                .padding(.vertical, Constants.headerPadding)
+                .font(Constants.titleFont)
+                .foregroundColor(Color.posPrimaryTexti3)
+            Spacer()
+            Image(uiImage: .searchImage)
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift]: nitpick; 

we could use `Image(systemImage: "plus.magnifyingglass")` or similar SF Symbol and use a grey tint as in designs.

File: WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift [hunk 7]
```diff
@@ -29,6 +29,12 @@ struct PointOfSaleDashboardView: View {
             if viewModel.isInitialLoading {
                 PointOfSaleLoadingView()
                     .transition(.opacity)
+            } else if viewModel.isError {
+                PointOfSaleItemListErrorView(viewModel: viewModel.itemListViewModel)
+                POSFloatingControlView(viewModel: viewModel)
+            } else if viewModel.isEmpty {
+                PointOfSaleItemListEmptyView()
+                POSFloatingControlView(viewModel: viewModel)
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift]: Notice that with this approach we lose padding and other settings (such as shadows) that are set in POSFloatingControlView in other places)

Consider always having a single `POSFloatingControlView(viewModel: viewModel)` and using something like `redactedIf(viewModel.isInitialLoading`).

image

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+
+    var body: some View {
+        VStack(alignment: .center, spacing: Constants.headerSpacing) {
+            Text(Localization.productTitle)
+                .frame(maxWidth: .infinity, alignment: .leading)
+                .padding(.vertical, Constants.headerPadding)
+                .font(Constants.titleFont)
+                .foregroundColor(Color.posPrimaryTexti3)
+            Spacer()
+            POSErrorExclamationMark()
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift:20]: Oh, I didn't know we have this, I'll replace in my pr as well!

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+            Text(errorContents.title)
+                .foregroundStyle(Color.posPrimaryTexti3)
+                .font(.posTitle)
+                .bold()
+            Divider()
+                .padding([.leading, .trailing], Constants.buttonPadding)
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Might not be necessary. I don't see divider in designs.

TfaZ4LUkEwEGrxfnEFzvJj-fi-2530_16232

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift [hunk 10]
```diff
@@ -0,0 +1,58 @@
+import SwiftUI
+
+struct PointOfSaleItemListEmptyView: View {
+    var body: some View {
+        VStack(alignment: .center, spacing: Constants.headerSpacing) {
+            Text(Localization.productTitle)
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift:6]: Same as with FloatingButton, it lacks respect for side margins.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+            "pos.pointOfSaleItemListErrorView.productTitle",
+            value: "Products",
+            comment: "Title for the Point of Sale screen"
+        )
+    }
+    enum Constants {
+        static let headerPadding: CGFloat = 8
+        static let headerSpacing: CGFloat = 16
+        static let titleFont: Font = .system(size: 40, weight: .bold, design: .default)
+        static let buttonPadding: CGFloat = 240
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Nitpick;

Technically it's true, that we have a 240-point margin. However, usually when we have such a big margin the element sizing follows a different logic. For example, the min width of a button is half of the screen-size width.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift [hunk 12]
```diff
@@ -0,0 +1,66 @@
...
+        static let productTitle = NSLocalizedString(
+            "pos.pointOfSaleItemListErrorView.productTitle",
+            value: "Products",
+            comment: "Title for the Point of Sale screen"
+        )
+    }
+    enum Constants {
+        static let headerPadding: CGFloat = 8
+        static let headerSpacing: CGFloat = 16
+        static let titleFont: Font = .system(size: 40, weight: .bold, design: .default)
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Let's use `Font.posTitle` here, and avoid using `.system(size)` going forward, unless we explicitly want a static non-dynamic font.

**Review by staskus — COMMENTED** [review]
I left a couple of design-related comments.

I'm not yet 100% sure how and where to better handle all the state logic. As @joshheald mentioned, technically it would make the most sense for `ItemsList` to handle product loading-related logic and UI presentation. I knew I had some problems with it before but maybe it wouldn't be problematic anymore. I don't want to block you on this for too much, we can discuss or pair to find a good solution on Monday.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift (hunk 10 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift:6]: Yeah! I'll address this one as smaller PR separately, mainly because currently the main rendering is done inside the `headerTextView`, declared in the ItemList, and I want to extract this into a separate component we can reuse across all screens. It also seems to change colour in cases like "empty list of products", so these can be tackled together 👍 

Logged here: https://github.com/woocommerce/woocommerce-ios/issues/13559

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift (hunk 4 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: That makes sense. I've updated this on 0655f09a1b64fe467326062ce16afed3e09f1c39 by passing the error model only and a closure. I've also moved the "unknown error" to the creation of the ErrorModel. I don't see a case where this could happen ("_there was an error retrieving the error"_), so we could just keep retuning `nil` and remove this default.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift (hunk 5 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Sounds good. Done in 7a60ec8de32cc7f0771c8f5110a767eb4b2ce629

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift (hunk 6 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift]: Definitely. I've given it another twist on ee0e617fc9942122481ed1d3e4939634631d6dc5 , so its closer to the proposal. Still not 10/10 like the designs as seems the icons used in Figma might not be the ones available as SF symbols?
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-08-12 at 10 25 34

File: WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift (hunk 7 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift]: For some reason I missed this one while I was working on the rest of changes on the screen 🤦, updated on 8900932b443b3bfdc8ff4b20996c162e5a6d5f82

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift (hunk 9 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Oh, true! The screenshot I took [here](https://github.com/woocommerce/woocommerce-ios/issues/13360) does have it, it may have changed later 😅  Removed divider on 0bce21ae38028ffe5d912f2dedcaa323ac366e57

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift (hunk 11 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Right! I updated this on 2ce4c6fe3c54dd34e66835cb9d1a7cfbe8d1a659 by setting a specific width for the button. My attempts using minWidth were defaulting to `.infinity` for some reason, despite setting a max too 🤔 

Another option that works is setting it specifically via `.frame(width: UIScreen.main.bounds.width / 2)` but I'm not quite sure if that's a good approach if we're purely using SwiftUI? Thoughts?

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift (hunk 12 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: Done! 72fdfd4043f71fc184cff25daf6d1b4c5c5329c6

File: WooCommerce/Classes/POS/Presentation/ItemListView.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/ItemListView.swift:20]: > I think it's because they are full screen, but you could delegate the fullscreen logic to the Dashboard view, while implementing the error/empty states here still

That's a good point, as you mention my initial idea to move these to the dashboard was because of the full-screen error messages, but at the same time it makes more sense to keep them on the Item list as is where are generated and not mix responsibilities. 

I'll keep the issue open on https://github.com/woocommerce/woocommerce-ios/issues/13543 and we can dig deeper if needed once we've tackled other priorities.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift (hunk 6 above)
Comment (staskus) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListEmptyView.swift]: Most icons I encountered were available on SF Symbols but not all. It's worth discussing it with design later.

File: WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift (hunk 11 above)
Comment (staskus) [reply WooCommerce/Classes/POS/Presentation/CardReaderConnection/UI States/PointOfSaleItemListErrorView.swift]: I think the best is to use `Geometry` to set the proportional width. However, I think had some issues myself with that so chose to stick with `(UIScreen.main.bounds.width / 2)`.

**Comment by staskus** [comment]
I tested simulating network errors but I got an empty state instead of an error state. I think it happens because we return an empty array if fetching products fail. We need to fix that as well, here or in another PR:

image

**Review by staskus — APPROVED** [review]
Thanks for the fixes!

Approving but lets address two other issues separately:
- Dashboard and ItemList states
- itemProvider.providePointOfSaleItems() not throwing errors

**Comment by iamgabrielma** [comment]
> I got an empty state instead of an error state. I think it happens because we return an empty array if fetching products fail.

Thanks for the review! Good catch, we can also remove the references to when there was a difference between "no products all all" vs "some products, but none eligible" 👍 

Logged: https://github.com/woocommerce/woocommerce-ios/issues/13565

Merging this for the moment!
