### PR TITLE
[Mobile Payments] Fix Set up Tap to Pay connectivity handling

### LINKED ISSUE #9136: [Mobile Payments] Tap to Pay set up connectivity issues
Not sure how much of this is known / will be addressed in a future PR, but wanted to make sure I didn't make assumptions!

My findings:
- If app loses connection while actively going through setup (such as at the 'preparing reader' screen), it feels odd that the error message would say that the payment can't be processed:

- If app doesn't have connectivity from the get-go, the purple Set up Tap to Pay on iPhone button in the Set up Tap to Pay on iPhone screen is unresponsive, so the user doesn't know what the issue is.

_Originally posted by @lmischner in https://github.com/woocommerce/woocommerce-ios/issues/9015#issuecomment-1456796754_

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #9136

## Description

In the new Tap to Pay on iPhone set up screen, we didn't have any handling for no network connectivity, and if connectivity was lost after the set up reader connection) process began, we would show an error which mentions a failed payment, out of context.

This PR adds a banner when the user is not online, and disables the Set up button. If the network connection is lost during the set up process, we now show an error message which does not mention a payment:

> Sorry, we could not start Tap to Pay on iPhone. Please check your connection and try again.

## Testing instructions

Using an iPhone XS or newer on a US store

1. Open the app and navigate to `Menu > Payments > Set up Tap to Pay on iPhone` (known issue: wait until the spinner stops before you tap this!)
2. Turn on Airplane Mode, and disable wifi if required
3. Observe that the Offline mode banner is displayed, and the set up button is disabled.
4. Turn off Airplane Mode, and/or enable wifi if required
5. Observe that the banner is cleared and the set up button is enabled
6. Tap `Set up Tap to Pay on iPhone`
7. Observe that the connection proceeds – quickly enable Airplane Mode again
8. Observe that the error displayed does not mention payments.
9. Disable Airplane Mode and tap retry
10. Observe that the retried connection continues and succeeds (blank screen shows)

## Screenshots

https://user-images.githubusercontent.com/2472348/225100639-ce31b9fc-8f7c-49e8-8de1-2198d5de38aa.mp4

---
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowPresentingViewController.swift [hunk 1]
```diff
@@ -54,6 +54,10 @@ final class PaymentSettingsFlowPresentingViewController: UIViewController {
         view.pinSubviewToAllEdges(childViewController.view)
         childViewController.didMove(toParent: self)
     }
+
+    override var shouldShowOfflineBanner: Bool {
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/PaymentSettingsFlowPresentingViewController.swift:58]: 💯

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift [hunk 2]
```diff
@@ -55,6 +61,20 @@ final class SetUpTapToPayInformationViewModel: PaymentSettingsFlowPresentedViewM
         stores.dispatch(connectedAction)
     }
 
+    private func beginConnectivityObservation() {
+        connectivityObserver.statusPublisher.sink { [weak self] status in
+            guard let self = self else { return }
+            switch (status, self.enableSetup) {
+            case (.notReachable, true),
+                (.reachable, false):
+                self.enableSetup.toggle()
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift:70]: TIL we can build a switch like this.

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift [hunk 3]
```diff
@@ -2,16 +2,19 @@ import Foundation
...
 
-final class SetUpTapToPayInformationViewModel: PaymentSettingsFlowPresentedViewModel {
+final class SetUpTapToPayInformationViewModel: PaymentSettingsFlowPresentedViewModel, ObservableObject {
     private(set) var shouldShow: CardReaderSettingsTriState = .isUnknown
     var didChangeShouldShow: ((CardReaderSettingsTriState) -> Void)?
     var didUpdate: (() -> Void)?
     let learnMoreURL: URL
     private let stores: StoresManager
 
+    @Published var enableSetup: Bool = true
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift:12]: Not a blocker: Should we limit access control for this variable?

```suggestion
    @Published private(set) var enableSetup: Bool = true
```

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInConnectingFailed.swift [hunk 4]
```diff
@@ -55,6 +55,20 @@ final class CardPresentModalBuiltInConnectingFailed: CardPresentPaymentsModalVie
...
+        case .internalServiceError:
+            return NSLocalizedString(
+                "Sorry, we could not start Tap to Pay on iPhone. Please check your connection and try again.",
+                comment: "Error message when the built-in reader connection experiences an unexpected internal service error."
+            )
+        default:
+            return underlyingError.errorDescription
+        }
+    }
+}
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInConnectingFailed.swift:70]: Not a blocker: I see we're repeating the same implementation in `CardPresentModalBuiltInConnectingFailed` and `CardPresentModalBuiltInConnectingFailedNonRetryable`, perhaps we can provide a default implementation directly in the protocol?

**Review by iamgabrielma — APPROVED** [review]
LGTM

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift (hunk 3 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift:12]: Good spot. I'll do that in a following PR as I've already based another one on this.

File: WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInConnectingFailed.swift (hunk 4 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewModels/CardPresentPayments/CardPresentModalBuiltInConnectingFailed.swift:70]: I chose not to do that in this case, because I want to allow different alerts to conform to that protocol but provide differently specified messages, based on their own context. I.e. a `CardPresentModalBuiltInPaymentFailed` modal could conform to it and provide payment-specific error language.

File: WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift (hunk 2 above)
Comment (joshheald) [reply WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2/SetUpTapToPayInformationViewModel.swift:70]: @iamgabrielma Yep, tuples in switches can be super helpful! You can also ignore one or other side of the tuple in a pattern match, e.g.

```suggestion
            case (.notReachable, true),
                (.reachable, false),
                (.unknown, _):
                self.enableSetup.toggle()
```

Which would toggle the `enableSetup` whether the current state was true or false if the reachability state is unknown. Not something we would actually do here!
