### PR TITLE
Fix a failing Currency Settings unit test

### LINKED ISSUE #1398: Unit Tests: `CurrencySettingTests` fail on first run
**Describe the bug**
The `testInitWithIndividualParameters` unit test in `CurrencySettingsTests` fails on the first run only. Any subsequent runs are fine. 

**To Reproduce**
This happens most often when I switch to a branch that's not mine, I have to run `bundle install`, followed by `bundle exec pod install`. After I install pods, I use Cmd + B to build, and then I run the unit tests. Getting Xcode in this specific state has been difficult to reproduce.

**Steps to reproduce the behavior:**
Unknown. Whatever requirement causes `bundle install` to be needed, sets the environment in the state that causes the unit test to fail. Deleting derived data doesn't seem to be enough. Cleaning the project doesn't trigger the unit test to fail either.

**Screenshots**

**Expected behavior**
I _think_ this is happening because `CurrencySettings` is a singleton, and the setUp() and teardDown() methods aren't impelmented.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #1398.

I'm unable to create exact Steps To Reproduce, but this PR seems to fix the problem. The problem happens where you: switch to a branch you do not own, build the app, and run unit tests. The `testInitWithIndividualParameters()` unit test always fails on first run. After the first run, it usually shows the test as passing. Whatever the issue is, CI does not seem to catch the problem. It only happens when running unit tests locally.

~My theory is that the CurrencySettings class is not getting initialized and de-init'ed properly. So I changed the `moneyFormat` and `siteSettings` from local constants within each function to variables that have `setUp()` and `tearDown()`  implemented as needed. (Actually, I think I could delete `setUp()` since the variables are initialized upon declaration, but I wasn't sure what's good practice, since I do use `tearDown()`.)~

I believe @jaclync found the root problem. Updated code and ready for another review.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ctarda** [comment]
Funnily enough, `testAgeCalculationsReturnLastOlderForMoreThanSevenFullDays` has started failing, on CI only, a few days ago (maybe as recently as Friday). 

I will merge develop into this branch, as I pushed an update to that one failing test yesterday as part of the reviews pagination

File: WooCommerce/WooCommerceTests/Tools/CurrencySettingsTests.swift [hunk 1]
```diff
@@ -5,9 +5,22 @@ import Yosemite
 /// CurrencySettings Tests
 ///
 class CurrencySettingsTests: XCTestCase {
-    func testInitDefault() {
-        let moneyFormat = CurrencySettings()
 
+    var moneyFormat = CurrencySettings()
+    var siteSettings = [SiteSetting]()
+
+    override func setUp() {
```
Comment (ctarda) [inline WooCommerce/WooCommerceTests/Tools/CurrencySettingsTests.swift]: In theory, moneyFormat and siteSettings should be initialised in setup and nullified in tearDown.

But because almost all tests use a different moneyFormat, maybe it makes sense to just initialise siteSettings in setup(), and initialise moneyFormat as a local variable for each test?

**Review by ctarda — COMMENTED** [review]
Tests seem to pass locally for me after switching to this branch right after checking it out, but I think it might be worth exploring a different way to initialise the subjects. Let me know what you think!

**Comment by jaclync** [comment]
One source of flakiness of the `CurrentSettings` test is the [use of singleton site ID in the predicate](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Tools/Currency/CurrencySettings.swift#L525):
```swift
private func refreshResultsPredicate() {
        let sitePredicate = NSPredicate(format: "siteID == %lld", ServiceLocator.stores.sessionManager.defaultStoreID ?? Int.min)
        let settingTypePredicate = NSPredicate(format: "settingGroupKey ==[c] %@", SiteSettingGroup.general.rawValue)
        resultsController.predicate = NSCompoundPredicate(andPredicateWithSubpredicates: [sitePredicate, settingTypePredicate])
        try? resultsController.performFetch()
        resultsController.fetchedObjects.forEach {
            updateCurrencyOptions(with: $0)
        }
}
```

in unit tests, `ServiceLocator.stores.sessionManager.defaultStoreID` could be nil if the device/simulator never launched the app before, or could be the last site it launched. Thus it's not always in the same state. What do you think about:

- In case of nil site ID, we early return in `refreshResultsPredicate` in https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Tools/Currency/CurrencySettings.swift#L525
- Reset the default site in unit tests `setup` so that the tests aren't dependent on the last site ID on the simulator, by calling `sessionManager.deauthenticate()`

**Comment by ctarda** [comment]
Nice catch @jaclync I'll try resetting the state for each tests.

**Review by ctarda — APPROVED** [review]
I can not reproduce the issue anymore after the last update and the code looks 💯 

:shipit:
