### PR TITLE
[Free Trial] Upgrades View - Error Handling

### LINKED ISSUE #9246: [Free Trial] Handle errors loading plans
The plan could fail to load, we should provide a way to inform the user that an error occurred.

### PR DESCRIPTION
**Pull request by Ecarrion**
Closes: #9246  

# Why

This PR makes sure that the upgrades views handle the scenario of not being able to fetch the plan details. Additionally it shows a notice allowing the merchant to retry loading the plan details.

# Demo

https://user-images.githubusercontent.com/562080/226799047-9572526f-5d39-4ed7-8cd2-0a90bee5c98b.mov

# Testing Steps

- Launch the app on a WPCom site
- Turn off wifi
- Go to the upgrades view
- See the error notice appear
- Turn on wifi
- Tap the retry button on the notice
- See the plan details load successfully.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift [hunk 1]
```diff
@@ -87,6 +90,15 @@ private extension UpgradesViewModel {
         planName = Self.getPlanName(from: plan)
         planInfo = Self.getPlanInfo(from: plan)
         shouldShowUpgradeButton = Self.getUpgradeNowButtonVisibility(from: plan)
+        errorNotice = nil
+    }
+
+    func updateViewProperties(from error: Error) {
+        DDLogError("⛔️ Unable to fetch site's plan: \(error)")
+        planName = ""
```
Comment (rachelmcr) [inline WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift:98]: Right now, when there's an error we just show "Current:" with nothing after it, because the plan name is empty. Would it make sense to have a specific string to show for the plan in that case, rather than an empty string, so it says for example "Current: Unknown"?

**Review by rachelmcr — APPROVED** [review]
Works great!

File: WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift (hunk 1 above)
Comment (Ecarrion) [reply WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift:98]: I was playing yesterday with that, trying a ` - ` or an `error` but nothing was appealing to my eye :-/

Comment (rachelmcr) [reply WooCommerce/Classes/ViewRelated/Upgrades/UpgradesViewModel.swift:98]: No worries, let's skip it then! The error notice is clear enough to explain what's happening, I think.
