### PR TITLE
Stats/Storage/Yosemite: add `timeRange` to `OrderStatsV4` and update decimal properties in `OrderStatsV4Interval`

### LINKED ISSUE #1162: Stats/Storage/Yosemite: add `timeRange` attribute to `OrderStatsV4` entity and update decimal properties in `OrderStatsV4Interval`
Prerequisite for #1067 

Why: for Stats Improvement using v4 API, stats granularity is not unique anymore. Both "this week" and "this month" have granularity/unit/interval of a day. In order to identify stats data for each tab ("today"/"this week"/"this month"/"this year"), `timeRange: String` attribute is added to `OrderStatsV4` for each time range tab.

In addition, fix the exception when setting value to `Decimal` fields in `OrderStatsV4Interval`.

### PR DESCRIPTION
**Pull request by jaclync**
Fixes #1162 

## Changes
- Schema update: added `timeRange` to `OrderStatsV4`
- Created `StatsTimeRangeV4` enum for time range of `OrderStatsV4`
- Updated `StatsStoreV4` and `StatsActionV4` to use time range instead of stats granularity which is not unique in the V4 UI anymore
- Updated `Decimal` properties in `OrderStatsV4Totals` to `NSDecimalNumber`
  - this is what Core Data editor generates in code, and if not using this type the app terminates on setting such property
- Updated unit tests to reflect the subtotals data in json response

## Testing
CI as there are no direct app-level changes

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: Yosemite/Yosemite/Model/Storage/OrderStatsV4Totals+ReadOnlyConvertible.swift [hunk 1]
```diff
@@ -11,27 +11,27 @@ extension Storage.OrderStatsV4Totals: ReadOnlyConvertible {
     public func update(with statsTotals: Yosemite.OrderStatsV4Totals) {
         totalOrders = Int64(statsTotals.totalOrders)
         totalItemsSold = Int64(statsTotals.totalItemsSold)
-        grossRevenue = statsTotals.grossRevenue
-        couponDiscount = statsTotals.couponDiscount
+        grossRevenue = NSDecimalNumber(decimal: statsTotals.grossRevenue)
```
Comment (mindgraffiti) [inline Yosemite/Yosemite/Model/Storage/OrderStatsV4Totals+ReadOnlyConvertible.swift]: **I think it's time we all decide on a "home" for type transformations.** In general we've been defining the Network Model classes to use `NSDecimalNumber` as well, then do any type transformations in the ViewModel, not in the `ReadOnlyConvertible` extension.

The reason being: a lot of numbers often get transformed from integers / doubles / etc. into strings anyway, so we keep most of the transformations there. Same for strings - they often get converted into usable dates. (Conversions to Int64 are about the only exception to the rule.)

It makes perfect sense to me that we'd do some of our conversions here. And if we're going to use this option, let's define the cases and commit to keeping it consistent everywhere.

Comment (jaclync) [reply Yosemite/Yosemite/Model/Storage/OrderStatsV4Totals+ReadOnlyConvertible.swift]: `NSDecimalNumber` might be an edge case in Core Data, normally `NSDecimalNumber` in Objective-C is bridged to `Decimal` in Swift. [This SO post](https://stackoverflow.com/questions/41148782/swift-3-decimal-nsdecimal-and-nsdecimalnumber) quoted a swift-users forum answer:

> Objective-C APIs which use `NSDecimalNumber` should be bridged to `Decimal`, just as `NSString` is bridged to `String`. That bridging may not work for category methods, though

that's probably why `NSDecimalNumber` has to be used for Core Data properties for `Decimal` (otherwise it crashes because it does not recognize the `Decimal` setter).

I'm always pro consistency, a p2 on our conversion convention sounds great!
