### PR TITLE
[Woo POS] Always create a new order when checking out

### LINKED ISSUE #15426: [Woo POS] Coupons: Product Changes & Invalid Coupon in Order update request changes the remote Order despite API error
https://github.com/user-attachments/assets/70410c78-bf19-4a59-8df0-4c39dc66d3bf

1. Add 2 products
2. Check out so the order would be created
3. Come back
4. Remove one of the producs
5. Add one invalid coupon
6. Check out
7. Get error
8. Come back
9. Remove an invalid coupon (the Cart should contain only one product now)
11. Continue
12. API Fails with `"Order item ID provided is not associated with order.

Request:
```
  "coupon_lines": [],
  "line_items": [
    {
      "id": 7588,
      "product_id": 22,
      "quantity": 0,
      "subtotal": "0",
      "total": "0"
    },
    {
      "id": 0,
      "product_id": 22,
      "quantity": 1
    }
  ]
}
```

Response:
```
{
  "code": "woocommerce_rest_invalid_item_id",
  "data": {
    "status": 400
  },
  "message": "Order item ID provided is not associated with the order."
}
```

## Investigation

When we remove a product from the cart, we make a request to an API with an order item with quantity 0. When we do this, the API removes the order item from the Order and returns an updated Order.

When we remove a product from the cart AND add an invalid coupon, during the Checkout an API request fails without returning an Order. However, in the remote, order item gets deleted. When we repeat a request with removed coupon, our request still contains an order item with quantity 0. However, this item no longer exists on the backend and the request fails with `Order item ID provided is not associated with the order.`.

## Solution

We may need to create rather than update the order during Checkout.

Discussion p1742989043210589-slack-C070SJRA8DP

### PR DESCRIPTION
**Pull request by staskus**
Closes: #15426
Discussion: https://github.com/woocommerce/woocommerce-android/issues/12385

## Description

Always create a new order when checking out. This matches the Android solution. Updating the order requires additional diffing logic on the mobile side and sometimes it [introduces issues when remote and local orders become out-of-sync](https://github.com/woocommerce/woocommerce-ios/issues/15426).

`auto-draft` orders [are removed by WordPress once 7 days.](https://github.com/WordPress/WordPress/blob/a645d169b2491a17d07efbf063c830c2b0e31c36/wp-includes/post.php#L8063). 

We could consider creating `checkout-draft` orders, that are [removed once a day by a cron job.](https://woocommerce.com/document/managing-orders/order-statuses/#draft-order-cleanup)

### The original issue I was addressing 

Prerequisites: Enable `enableCouponsInPointOfSale` feature flag in `DefaultFeatureFlagService`

1. Add 2 products
3. Check out so the order would be created
4. Come back
5. Remove one of the producs
6. Add one invalid coupon
7. Check out
8. Get error
9. Come back
10. Remove an invalid coupon (the Cart should contain only one product now)
11. Check out again
12. Confirm order is created successfully

### Regression

The changes affect the checkout flow, which could be triggered in two ways:
1. Tapping Check Out
2. Tapping 'Try Again' if order creation fails

Test with various types of products:
1. Select products -> Check out -> Come back -> Make Changes -> Card Payment
2. Select products -> Check out -> Order creation failure (e.g. no network connection) -> Address Issue (Enable network) -> Try Again -> Card Payment
3. Select products -> Check out -> Come back -> Checkout -> Order is not loading since it remains unchanged

## Testing information

I tested various scenarios with different types of products, variations, and coupons. Also, cash payment and emails. 

The order creation logic is not changed, I use the same method for adding order items to the order. Order editing works as order creation now. 

## Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshheald** [comment]
The repro steps don't always work. When I come back at step 11, it sometimes still shows the invalid coupons error. Is that expected at this point, and unrelated to the PR? 

I'm guessing that removing the coupon isn't noticed as a change to the cart, so the order isn't recalculated... but it has worked sometimes. Adding a coupon to the cart is reliably noticed as a change, but not removing it.


https://github.com/user-attachments/assets/58cfebbd-6722-4fa0-846e-40403744eb3c


Edit: I guess that the `coupon.matches(order)` check would return true after the coupon is removed – the API removes the coupon from the order itself, right?

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift [hunk 1]
```diff
@@ -66,73 +60,17 @@ public final class POSOrderService: POSOrderServiceProtocol {
...
-        let itemsToAdd = cart.items.createGroupedOrderSyncProductInputs().values
-        let itemsToSync = itemsToRemove + itemsToAdd
-
-        var order = ProductInputTransformer.updateMultipleItems(with: itemsToSync, on: order, shouldUpdateOrDeleteZeroQuantities: .update)
-        order = updateCoupons(cart.coupons, on: order)
-
-        return order
+private extension Order {
+    func addItems(_ cartItems: [POSCartItem]) -> Order {
+        let itemsToAdd = Array(cartItems.createGroupedOrderSyncProductInputs().values)
```
Comment (joshheald) [inline Yosemite/Yosemite/Tools/POS/POSOrderService.swift:65]: Do we need to call `sanitizingLocalItems` on these, or is that only relevant for updates?

**Review by joshheald — APPROVED** [review]
Thanks for this – It's a nice simplification of the logic. Other than the issue mentioned about not reliably recognising invalid coupon removal, I found it worked well in my testing...

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift (hunk 1 above)
Comment (staskus) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift:65]: 😨 I missed it.

Great observation. We do need it. As the comment in the `sanitizingLocalItems` says, not applying it breaks the calculations if `prices_include_tax` is `true`.

**Comment by staskus** [comment]
> The repro steps don't always work. When I come back at step 11, it sometimes still shows the invalid coupons error. Is that expected at this point, and unrelated to the PR?

> I'm guessing that removing the coupon isn't noticed as a change to the cart, so the order isn't recalculated... but it has worked sometimes. Adding a coupon to the cart is reliably noticed as a change, but not removing it.

Good catch. Why it happens:

1. Create and persist order (Add Product -> Check out -> Sync -> Come Back).
2. Add invalid coupon, API returns error, order doesn't change (Add Invalid Coupon -> Check out -> Sync -> Error -> Come Back).
3. Remove invalid coupon, cart state is equal to order state, sync is not initialized (Remove Coupon -> Check out -> Error).

The way to get around this cleanly is to always sync the next time after an error is returned from the API.

File: Yosemite/Yosemite/Tools/POS/POSOrderService.swift (hunk 1 above)
Comment (joshheald) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift:65]: Ah, glad I spotted it then! I wasn't sure because it could have been something only required on update... though, our products are all added as an update, aren't they? Rather than in the initial POST request?

Comment (staskus) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift:65]: > though, our products are all added as an update, aren't they? Rather than in the initial POST request?

No. We add them as initial request when creating an order. `createGroupedOrderSyncProductInputs` turns products into order items. `sanitize` makes sure totals and subtotals are cleared and don't influence backend calculations.

Comment (joshheald) [reply Yosemite/Yosemite/Tools/POS/POSOrderService.swift:65]: Ah, makes sense! Yeah, I'm all for just sending up an ID and a quantity as our input. Factors in to the line/cart-level discount/taxes discussion as well.

Ideally, if we ever allow merchants to add line-level discounts like they can in IPP, we could make a change in the API that lets us specify a discount directly, and whether that's before or after tax.
