### PR TITLE
Fix Crash on Image Drag & Drop during upload in Product Images

### LINKED ISSUE #11341: Crash: When product images are reordered (ProductImagesCollectionViewController)
Sentry Issue: [WOOCOMMERCE-IOS-1Y](https://a8c.sentry.io/issues/1523523535/?referrer=github_integration)

```
NSInternalInconsistencyException: <_UIDragSnappingFeedbackGenerator: 0x28058ecb0> is already being interacted with
  File "main.swift", line 7, in main
...
(16 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes: #11341 

## Description
This PR addresses a crash that occurs when a user attempts to drag and drop images during an image upload process in the Product Images section. The issue arises due to an inconsistency exception: `UIDragSnappingFeedbackGenerator is already being interacted with.`. This is definitively in the top 5 unresolved crashes on iOS. More details: peaMlT-hQ

## Steps to reproduce the crash:
1. Open a product.
2. Tap on images.
3. Upload 3 or more images (suggested for users with a fast connection).
4. While the images are uploading, open the list of images.
5. Start the drag and drop of an image, and keep it while the images are uploading. Release it at the end.
6. After the upload finishes, re-try to drag & drop some images.
7. Crash 💥 

## Resolution
With this fix, the app should no longer crash when the user attempts to drag and drop images during the upload process. Instead, the drag and drop functionality will be disabled until the upload process is complete to ensure the app remains stable and the user experience is not disrupted. A notice will be presented if an image is still uploading.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift [hunk 1]
```diff
@@ -159,6 +165,15 @@ extension ProductImagesCollectionViewController {
 ///
 extension ProductImagesCollectionViewController: UICollectionViewDragDelegate, UICollectionViewDropDelegate {
     func collectionView(_ collectionView: UICollectionView, itemsForBeginning session: UIDragSession, at indexPath: IndexPath) -> [UIDragItem] {
+
+        // If any image is currently being uploaded, display a message to the user and prevent drag & drop operations.
+        guard !productImageStatuses.contains(where: { if case .uploading = $0 { return true }; return false }) else {
```
Comment (hafizrahman) [inline WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift:170]: 💡 this `if case` syntax stumped me for a little bit (it makes sense but got me thinking "why are this written this way?"). Luckily [this helps me understand](https://stackoverflow.com/a/37888514).

**Review by hafizrahman — APPROVED** [review]
Good solution to the issue! Tested it and it work as described, the code also makes sense to me.

At first I had a little problem replicating the crash, but here's a video demonstrating the issue in case it helps for future reference:

https://github.com/woocommerce/woocommerce-ios/assets/266376/be4cb711-3210-4d4a-90b9-3920e0ae2f2c

File: WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift [hunk 2]
```diff
@@ -267,3 +282,12 @@ private extension ProductImagesCollectionViewController {
...
     }
 }
+
+/// Private data structures
+/// 
+private extension ProductImagesCollectionViewController {
+    enum Localization {
+        static let dragAndDropMessageWhileUploading = NSLocalizedString("Please wait until all uploads are finished before reordering images.",
+                   comment: "Alert message to inform the user that they must wait for all image uploads to complete before they can reorder the images.")
+    }
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift]: Nit: Please follow the new convention to use reverse-DNS keys for localized strings (p91TBi-aJl-p2)

Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift]: Good catch! Fixed here: 54396e1c564a8b4edcbffd299d29e861f231206f

**Comment by pmusolino** [comment]
Thank you both @hafizrahman @itsmeichigo  🙌

File: WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift (hunk 2 above)
Comment (hafizrahman) [reply WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift]: Ah I always forgot this 💯

Comment (hafizrahman) [reply WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift]: Wonder if we can add this into code checking rule.

Comment (itsmeichigo) [reply WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift]: Good idea! I think someone suggested that too but it will require updating all the localized strings in the app at once, which is not a trivial task for both us devs and translators 😅

**Comment by candyofficial** [comment]
Is this to make iOS app for my woo store?On 12/5/23 at 4:02 AM, Huong Do wrote:
                
            
            
                
                    From: "Huong Do" ***@***.***>Date: December 5, 2023To: "woocommerce/woocommerce-ios" ***@***.***>Cc: "Subscribed" ***@***.***>Subject: Re: [woocommerce/woocommerce-ios] Fix Crash on Image Drag & Drop during upload in Product Images (PR #11350)
                
                
@itsmeichigo commented on this pull request.



In WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesCollectionViewController.swift:
> +        static let dragAndDropMessageWhileUploading = NSLocalizedString("Please wait until all uploads are finished before reordering images.",
+                   comment: "Alert message to inform the user that they must wait for all image uploads to complete before they can reorder the images.")
+    }

Good idea! I think someone suggested that too but it will require updating all the localized strings in the app at once, which is not a trivial task for both us devs and translators 😅
