### PR TITLE
[Order List] Fix iphone crash when Orders Split View flag is enabled

### LINKED ISSUE #11649: [Tablet Orders] Fix crash on iPhone when Split Screen orders is enabled

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #11649 

## Description

The app would crash when the `splitViewInOrdersTab` was enabled, and the orders were used in a horizontally compact view (i.e. on iPhone, or in some split view/slide over presentations on iPad.)

The original crash was trivial to reproduce:

> 1. Go to Orders
> 2. Tap on any order from the list
> 3. Crash
– #10815 

The crash was non-trivial to trace, and you can see from the commit history of this PR that there were a few parts to it.

On iOS 16, it was sufficient to update the various split view function calls to use the modern column-based API, which is not enforced by Apple: f15eb12

However, when built from Xcode 15 on Xcode 17, the crash returned. In this case, it was due to our `UISplitViewController` being wrapped in a `UINavigationController`, as all our root tabs were. Nav controllers live inside split view controllers, and not (ideally) the other way around.

To resolve this without substantially changing how the `MainTabViewController` works, I've added a `WooTabContainerController`, which can be used to wrap view controllers at the root of a tab which should not be presented in a nav controller.

### Other changes
- We only auto-select the first order when the splitview is uncollapsed. Without this, we would sometimes see the phone skip over the Order List and go straight to the Order Details.
- The Order List is always responsible for auto-selection (not the OrdersRoot or OrdersSplitViewWrapper.) 

## Testing instructions

The main thing with this PR is to test on a wide array of devices and with the feature flag `splitViewInOrdersTab` both true and false. 

When the flag's set to false, _everything_ should work. When it's true, there are some known issues with the split view, which are not relevant to this PR – the main thing is that it shouldn't crash!

Devices:
iPad on iOS 15
iPad on iOS 16
iPad on iOS 17 
(include OS-based split view multitasking for smaller size classes)

iPhone on iOS 15
iPhone on iOS 16
iPhone on iOS 17
(if possible, test Plus/Pro Max phone sizes in landscape for horizontally regular size classes)

Here are some scenarios to cover:

### Navigating to an order

1. Launch the app
2. Tap `Orders`
3. Verify that you can view the order details
4. Tap `<` (if available)
5. Select another order
6. Verify that you can view the second order

### Navigating to an order after switching store

1. Launch the app
2. Tap `Orders`
3. Verify that you can view the order details
4. Switch to another store
5. Tap `Orders`, and navigate to an order
6. Verify that you can view the second store's orders

## Screenshots

https://github.com/woocommerce/woocommerce-ios/assets/2472348/be449c2a-cead-40f8-9b36-d23fbfa18cff

https://github.com/woocommerce/woocommerce-ios/assets/2472348/32000e8b-abe0-4d52-8ca4-592beb515cee

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/180">16.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/180">16.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iamgabrielma** [comment]
I tested the following simulators and everything works nicely: 

| Feature flag `true` | Feature flag `false` |
|--------|--------|
| ✅ iPhone on iOS 15 | ✅ iPhone on iOS 15 |
| ✅ iPhone on iOS 16 | ✅ iPhone on iOS 16 |
| ✅ iPhone on iOS 17 | ✅ iPhone on iOS 17 |
| ✅ iPad on iOS 15 | ✅ iPad on iOS 15 |
| ✅ iPad on iOS 16 | ✅ iPad on iOS 16 |
| ✅ iPad on iOS 17 | ✅ iPad on iOS 17 |

I found a recurrent crash running `iPhone 15 Pro Max - iOS 17.0`, but looks unrelated since the app crashes on init when trying to access the stores and setup analytics.

I'll review the code now

File: WooCommerce/Classes/System/WooTabContainerController.swift [hunk 1]
```diff
@@ -0,0 +1,35 @@
+import UIKit
+
+/// Container for a Woo tab, shown as the root view controller of one of the tabs.
+/// Provided as an alternative to `WooTabNavigationController`, for root controllers which should not be in a nav view
+/// For example, a Split View, which will not work correctly on iPhone when wrapped in a navigation view.
+/// This wraps a controller which can be replaced when the selected site changes.
+class WooTabContainerController: UIViewController {
```
Comment (iamgabrielma) [inline WooCommerce/Classes/System/WooTabContainerController.swift]:
```suggestion
final class TabContainerController: UIViewController {
```

Do we want to allow subclassing for this one? Otherwise we can mark it as final. 

Question: Do you think we should remove the `Woo` part from the class name? Since is not really a wrapper for a WooTab  or other concrete implementations, but for any `UIViewController`. On the contrary, `WooTabNavigationController` inherits from `WooNavigationController` so the name goes along.

File: WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift [hunk 2]
```diff
@@ -198,6 +196,13 @@ final class OrderListViewController: UIViewController, GhostableViewController {
         //
         // We can remove this once we've replaced XLPagerTabStrip.
         tableView.reloadData()
+
+        // Select the first order if we're showing in an open split view (i.e. on iPad in some size classes)
+        guard let splitViewController,
```
Comment (iamgabrielma) [inline WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift:201]: TIL `splitViewController` property could be accessed like this. Much easier to deal with certain logic.

**Review by iamgabrielma — APPROVED** [review]
Works great! Thanks for working on this 💯 

🚢

File: WooCommerce/Classes/System/WooTabContainerController.swift (hunk 1 above)
Comment (joshheald) [reply WooCommerce/Classes/System/WooTabContainerController.swift]: Yeah, that makes sense since the WooNavigationController is so named because it adds Woo styling (among other things.)

**Comment by joshheald** [comment]
> I found a recurrent crash running `iPhone 15 Pro Max - iOS 17.0`, but looks unrelated since the app crashes on init when trying to access the stores and setup analytics.

Interesting... I did most of my testing on an iPhone 15 Pro Max with iOS 17.1.2. Do you have any more details about that crash? I wonder whether it's related to Xcode 15 builds...

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/180">16.9</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/180">16.9</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iamgabrielma** [comment]
> > I found a recurrent crash running `iPhone 15 Pro Max - iOS 17.0`, but looks unrelated since the app crashes on init when trying to access the stores and setup analytics.
> 
> Interesting... I did most of my testing on an iPhone 15 Pro Max with iOS 17.1.2. Do you have any more details about that crash? I wonder whether it's related to Xcode 15 builds...

Not much. It does crash with the feature flag enabled/disabled and only seems to happen with this specific simulator. The stack trace indicates unsafe memory access when trying to access the Servicelocator, perhaps because is not fully initialized yet, most likely a related case to this one: p91TBi-axt-p2 . What puzzles me is that only happens with that specific simulated device, so is perfectly possible that is some Xcode oddness.

<details><summary>Stack trace, for reference:</summary>
<code>
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1077723f4)
    frame #0: 0x00000001077723f4 libdispatch.dylib`_dispatch_once_wait.cold.1 + 28
    frame #1: 0x000000010773a318 libdispatch.dylib`_dispatch_once_wait + 184
    frame #2: 0x0000000100e1e2a0 WooCommerce`ServiceLocator._stores.unsafeMutableAddressor at ServiceLocator.swift:22:24
    frame #3: 0x0000000100e1f558 WooCommerce`static ServiceLocator.stores.getter(self=WooCommerce.ServiceLocator) at ServiceLocator.swift:132:16
    frame #4: 0x0000000101d11d34 WooCommerce`DefaultStoresManager.deauthenticate(self=0x00006000033048c0) at DefaultStoresManager.swift:240:24
    frame #5: 0x0000000101d11c50 WooCommerce`DefaultStoresManager.fullyDeauthenticateIfNeeded(self=0x00006000033048c0) at DefaultStoresManager.swift:230:9
    frame #6: 0x0000000101d0faec WooCommerce`DefaultStoresManager.init(sessionManager=0x000000012b008fa0, notificationCenter=0x00006000000100a0, defaults=0x0000600000c5b810, self=0x00006000033048c0) at DefaultStoresManager.swift:131:9
    frame #7: 0x0000000101d0f6f0 WooCommerce`DefaultStoresManager.__allocating_init(sessionManager:notificationCenter:defaults:) at DefaultStoresManager.swift:0
    frame #8: 0x0000000100e1e220 WooCommerce`one-time initialization function for _stores at ServiceLocator.swift:22:49
    frame #9: 0x000000010773993c libdispatch.dylib`_dispatch_client_callout + 16
    frame #10: 0x000000010773b3dc libdispatch.dylib`_dispatch_once_callout + 84
    frame #11: 0x0000000100e1e2a0 WooCommerce`ServiceLocator._stores.unsafeMutableAddressor at ServiceLocator.swift:22:24
    frame #12: 0x0000000100e1f558 WooCommerce`static ServiceLocator.stores.getter(self=WooCommerce.ServiceLocator) at ServiceLocator.swift:132:16
    frame #13: 0x0000000101d86d08 WooCommerce`WooAnalytics.refreshUserData(self=0x000060000212bbb0) at WooAnalytics.swift:67:27
    frame #14: 0x0000000101d868c4 WooCommerce`WooAnalytics.initialize(self=0x000060000212bbb0) at WooAnalytics.swift:53:9
    frame #15: 0x0000000101d86894 WooCommerce`protocol witness for Analytics.initialize() in conformance WooAnalytics at <compiler-generated>:0
    frame #16: 0x0000000101263f3c WooCommerce`AppDelegate.setupAnalytics(self=0x00006000030083f0) at AppDelegate.swift:293:34
    frame #17: 0x0000000101263d94 WooCommerce`AppDelegate.application(application=0x000000012b0072b0, launchOptions=nil, self=0x00006000030083f0) at AppDelegate.swift:61:9
    frame #18: 0x0000000101265b28 WooCommerce`@objc AppDelegate.application(_:willFinishLaunchingWithOptions:) at <compiler-generated>:0
    frame #19: 0x0000000118d0c958 UIKitCore`-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 192
    frame #20: 0x0000000118d0de30 UIKitCore`-[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 2788
    frame #21: 0x0000000118d12974 UIKitCore`-[UIApplication _runWithMainScene:transitionContext:completion:] + 856
    frame #22: 0x00000001183cee08 UIKitCore`-[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 104
    frame #23: 0x00000001188de79c UIKitCore`_UIScenePerformActionsWithLifecycleActionMask + 96
    frame #24: 0x00000001183cf708 UIKitCore`__101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 188
    frame #25: 0x00000001183cf27c UIKitCore`-[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 212
    frame #26: 0x00000001183cf560 UIKitCore`-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 576
    frame #27: 0x00000001183cef64 UIKitCore`-[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 244
    frame #28: 0x00000001183d85f8 UIKitCore`__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 140
    frame #29: 0x00000001187e1170 UIKitCore`+[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 656
    frame #30: 0x00000001188f4950 UIKitCore`_UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 196
    frame #31: 0x00000001183d8304 UIKitCore`-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 288
    frame #32: 0x000000011823a1c4 UIKitCore`__64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.198 + 608
    frame #33: 0x0000000118238f74 UIKitCore`-[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 208
    frame #34: 0x0000000118239e48 UIKitCore`-[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 220
    frame #35: 0x0000000118d116a4 UIKitCore`-[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 484
    frame #36: 0x0000000118808704 UIKitCore`-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 260
    frame #37: 0x000000018544d014 FrontBoardServices`-[FBSScene _callOutQueue_didCreateWithTransitionContext:completion:] + 296
    frame #38: 0x0000000185475acc FrontBoardServices`__92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke.82 + 224
    frame #39: 0x0000000185459bb4 FrontBoardServices`-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 160
    frame #40: 0x0000000185475844 FrontBoardServices`__92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke + 284
    frame #41: 0x000000010773993c libdispatch.dylib`_dispatch_client_callout + 16
    frame #42: 0x000000010773d534 libdispatch.dylib`_dispatch_block_invoke_direct + 392
    frame #43: 0x0000000185498fa0 FrontBoardServices`__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 44
    frame #44: 0x0000000185498e7c FrontBoardServices`-[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 196
    frame #45: 0x0000000185498fd4 FrontBoardServices`-[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 24
    frame #46: 0x00000001803c669c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
    frame #47: 0x00000001803c65e4 CoreFoundation`__CFRunLoopDoSource0 + 172
    frame #48: 0x00000001803c5d54 CoreFoundation`__CFRunLoopDoSources0 + 232
    frame #49: 0x00000001803c043c CoreFoundation`__CFRunLoopRun + 768
    frame #50: 0x00000001803bfd28 CoreFoundation`CFRunLoopRunSpecific + 572
    frame #51: 0x000000018986ebc0 GraphicsServices`GSEventRunModal + 160
    frame #52: 0x0000000118d0ffdc UIKitCore`-[UIApplication _run] + 868
    frame #53: 0x0000000118d13c54 UIKitCore`UIApplicationMain + 124
    frame #54: 0x000000010153e224 WooCommerce`main at main.swift:7:1
    frame #55: 0x00000001059a9558 dyld_sim`start_sim + 20
    frame #56: 0x0000000105a3a058 dyld`start + 2224
</code>
</summary>
