### PR TITLE
[Woo POS] [Cash & Receipts] Fix for number formatting when using grouping separators

### LINKED ISSUE #14909: [Woo POS] [Cash & Receipts] Address cash validation issues when grouping separators
Ref: pdfdoF-6dp#comment-7332-p2

### PR DESCRIPTION
**Pull request by iamgabrielma**
Closes: #14909

## Description
This PR addresses an issue with cash validation found during testing ( pdfdoF-6dp#comment-7332-p2 ), where the values returned are incorrect depending on the store settings and if the amount has both `.` and `,` as grouping separators. 

Screenshot 2025-01-20 at 10 01 29

This is a pre-existing issue with our own `CurrencyFormatter` implementation that we've attempted to mitigate several times ( eg: https://github.com/woocommerce/woocommerce-ios/pull/13854 and https://github.com/woocommerce/woocommerce-ios/pull/13979) and derives from using `convertToDecimal` when operating with values, which doesn't take into account different locale configurations and converts the values incorrectly. Eg:

```
1,000.50 becomes 1.000.50, and NSDecimalNumber ignores everything from the second . to leave us with th number 1.
```

This fix is a bandaid, as shared in the other PRs I believe there are further improvements we can do, but these are out of scope in the context of this PR as would touch many parts. There's also some iteration we can do in the POS side, for example [PointOfSaleOrderTotals](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/POS/Models/PointOfSaleOrderTotals.swift) passes the totals already formatted and could be improved.

## Changes
- Remove usage of `CurrencyFormatter.convertToDecimal`, in favour of `Decimal(string:)`. This is the same approach as on https://github.com/woocommerce/woocommerce-ios/pull/13854, with this we also update the return types to use `Decimal` as well.
- When parsing amounts to calculate change due or "not enough amount" we sanitize, remove the currency and make the built-in formatter take as many store configuration details as possible, otherwise it fails often and returns nil or the incorrect amount, which caused the original issue.
- Added some debug logs if fails to parse, which returns more info that could be useful to understand the merchant's store details: 
```
Number Style: NSNumberFormatterStyle(rawValue: 1)
Grouping Separator: ,
Decimal Separator: .
Minimum Fraction Digits: 2
Maximum Fraction Digits: 2
Locale: en_ES
Rounding Mode: NSNumberFormatterRoundingMode(rawValue: 4)
Uses Grouping Separator: true In: 1
```

## Testing information
- Enable `.acceptCashForPointOfSale` feature flag
- Add products to your cart for a value exceeding $1000 or create a product with that value for testing, by default you should see the price formatted with both thousand and decimal grouping indicators, like `$1,000.00`. For reference, here are my store settings:
Screenshot 2025-01-20 at 09 52 22

- Observe that adding an input amount below the total, will return `Amount must be more or equal to total.`
- Observe that adding an input equal to total, will process the transaction normally.
- Observe that adding an input higher to total, will show the `change due`, and process the transaction normally.

Simulator Screenshot - iPad Air 11 - iOS 17 5 M2 - 2025-01-20 at 09 01 03

### CODE REVIEW

File: WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift [hunk 1]
```diff
@@ -27,18 +29,39 @@ final class CollectCashViewHelper {
...
+        if inputDecimal < orderDecimal {
             onError(Localization.cashPaymentAmountNotEnough)
             return false
         }
         return true
     }
 
-    private func parseCurrency(_ amountString: String) -> NSDecimalNumber? {
-        currencyFormatter.convertToDecimal(amountString, locale: .current)
+    private func parseCurrency(_ amountString: String) -> Decimal? {
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift:52]: Could we avoid writing another parsing method if we pass `Order.total`, rather than formatted order total to this helper? We need to avoid these double formatting as much as possible. I missed the fact in the initial review that we're receiving a formatter rather than a raw total. 

Our input field limits what we can enter already. Maybe this way we would keep the solution simpler and limit the number of failures.

I remember fixing something like this with cash payments on https://github.com/woocommerce/woocommerce-ios/pull/13979, maybe it could be an inspiration.

------

As I understood from your comments, it would require updating `PointOfSaleOrderTotals` but I think that's the way to go. 

This is a quick experimentation from my side:

https://github.com/woocommerce/woocommerce-ios/compare/fix/experiment-with-cash?expand=1

Do you think this would solve the issue without introducing another set of formatting logic? Or do you see some other solution?

**Review by staskus — COMMENTED** [review]
> There's also some iteration we can do in the POS side, for example [PointOfSaleOrderTotals](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/POS/Models/PointOfSaleOrderTotals.swift) passes the totals already formatted and could be improved.

I would love this iteration!

We can improve animations, styles, and accessibility how much we want to, but if the calculations are not solid we're not going to have a good product.

It's a tough issue, I spent some time on it today and we can discuss it tomorrow as well.

File: WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift:52]: > Could we avoid writing another parsing method if we pass Order.total, rather than formatted order total to this helper? 

I don't think we can, can we? At least not without more extensive changes. We still need to calculate the _change due_ which will continue forcing us to parse Strings to Decimals taking into account the grouping separators, make the operation, and then parse it back to string adding the currency formatting, in which case we're only removing the bits here:

```
// Removes currency symbol
let symbol = currencySettings.symbol(from: currencySettings.currencyCode)
let stringWithoutSymbol = sanitized.replacingOccurrences(of: symbol, with: "")
```

But the rest should remain the same or very similar (maybe the character trimming could also be removed).

I agree that in general we should make this change and move the formatter to `PointOfSaleOrderTotals` instead, but I don't think we should make it as part of this PR, as we're touching how prices are being displayed in different places (maybe just in the totals view, I'm not 100% sure) and feels a bit risky when it can be tackled separately on an isolated context and tested with multiple currencies.

If you strongly think that we should make the change here I'm happy to tackle it and re-submit, otherwise I'd prefer to keep it as it is and handle it separately 🙇

Comment (staskus) [reply WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift:52]: > I don't think we can, can we? At least not without more extensive changes. We still need to calculate the change due which will continue forcing us to parse Strings to Decimal

Yes, we do need to do calculations. The idea is to use unformatted total rather than formatted total for this purpose. 
This way we can use existing formatters. The same was done for an IPP cash view. 

I think it's fundamentally flawed that we have to pass a formatted total to POS cash view to use for calculations. We shouldn't be surprised it causes problems.

> I don't think we can, can we? At least not without more extensive changes.

I'm not sure. Requires more testing. This https://github.com/woocommerce/woocommerce-ios/compare/fix/experiment-with-cash?expand=1 was only a quick experiment. 

> If you strongly think that we should make the change here I'm happy to tackle it and re-submit, otherwise I'd prefer to keep it as it is and handle it separately 🙇

Well... I'm just very concerned about introducing another set of parsing logic. Makes things less predictable, maybe introduces even more corner cases. If we deliver cash payments functionality that breaks under pressure - that's super bad.

File: WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift [hunk 2]
```diff
@@ -1,18 +1,20 @@
 import Foundation
-import class WooFoundation.CurrencyFormatter
+import SwiftUI
+import WooFoundation
 
 final class CollectCashViewHelper {
     private let currencyFormatter: CurrencyFormatter = WooFoundation.CurrencyFormatter(currencySettings: ServiceLocator.currencySettings)
+    private let currencySettings: CurrencySettings = ServiceLocator.currencySettings
 
     func updatechangeDueMessage(orderTotal: String,
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift:22]:
```suggestion
    func updateChangeDueMessage(orderTotal: String,
```

File: WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift [hunk 3]
```diff
@@ -27,18 +29,39 @@ final class CollectCashViewHelper {
...
+    private func parseCurrency(_ amountString: String) -> Decimal? {
+        // Removes all leading/trailing whitespace, if any
+        let sanitized = amountString.trimmingCharacters(in: .whitespacesAndNewlines)
+
+        // Removes currency symbol
+        let symbol = currencySettings.symbol(from: currencySettings.currencyCode)
+        let stringWithoutSymbol = sanitized.replacingOccurrences(of: symbol, with: "")
+
+        // Configures the formatter as close as possible to use the Store's settings
+        let formatter = NumberFormatter()
```
Comment (staskus) [inline WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift]: nit;

We could move it to a `var` so it wouldn't be created every time we call `parseCurrency`.

**Review by staskus — APPROVED** [review]
I retested many cases I could think of and it does the job 👍 

We can leave refactoring of `PointOfSaleOrderTotals` for the future. I still agree with he comment there that total should be unformatted there.

File: WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift (hunk 3 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/ViewHelpers/CollectCashViewHelper.swift]: Good point!
