### PR TITLE
Hotfix: Chart Crash on Negative Values on Dynamic Dashboard

### LINKED ISSUE #12661: EXC_BREAKPOINT: Exception 6, Code 1, Subcode 9004625504 >
Sentry Issue: [WOOCOMMERCE-IOS-1MQ3](https://a8c.sentry.io/issues/5309256520/?referrer=github_integration)
CUW: peaMlT-Cp-p2

```
EXC_BREAKPOINT: Exception 6, Code 1, Subcode 9004625504 >
Stack overflow in (null)
  ?, in _Charts_getAxisMarkWitnessTable
  ?, in _Charts_getAxisMarkWitnessTable
  ?, in _Charts_getAxisMarkWitnessTable
  ?, in _Charts_getAxisMarkWitnessTable
  ?, in _Charts_getAxisMarkWitnessTable
...
(95 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by pmusolino**
Closes #12661

#### Problem
This pull request addresses a crash in the `yAxisStride` calculation within the `StoreStatsChartViewModel`. Previously, the stride calculation did not properly account for negative values, which could occur in datasets that included refunds or other negative revenue amounts. This led to a crash when the chart attempted to render with an incorrect stride value. The issue is traced to the `NumberBins.init(size:range:)` method within the framework, causing a crash a few seconds after app launch when viewing stats in the Dynamic Dashboard.

#### Steps to Reproduce
1. Log into the specific store with negative revenue data.
2. Select a date range that includes the negative values.
3. Observe the crash after the stats are fetched and displayed.

#### Solution
- The stride calculation has been updated to correctly handle the full range of data, including negative values. The new calculation determines the stride based on the actual range between the minimum and maximum revenue values.
- The stride is now guaranteed to be a positive value, which prevents the charting library from encountering errors when rendering the y-axis.

#### Changes Made
The stride calculation now uses the absolute values of the minimum and maximum to ensure that the stride is always a positive number.

#### Impact
This hotfix resolves the app crash related to the `Charts` framework and allows users to view their stats without interruption, even with negative data points.

#### Release
This is a critical hotfix, and we are proceeding with an immediate release of version 18.4.1 to address this issue.

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/205">18.4.1</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by selanthiraiyan — APPROVED** [review]
This works as expected. 🚀

**Review by joshheald — APPROVED** [review]
Works as expected and displays negative revenue days correctly
IMG_1354

**Comment by pmusolino** [comment]
Merging it now

File: WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StoreStats/StoreStatsChartViewModelTests.swift [hunk 1]
```diff
@@ -150,6 +150,22 @@ final class StoreStatsChartViewModelTests: XCTestCase {
...
+            StoreStatsChartData(date: currentDate.adding(days: 1)!, revenue: -10),
+            StoreStatsChartData(date: currentDate.adding(days: 2)!, revenue: 130),
+        ]
+
+        // When
+        let viewModel = StoreStatsChartViewModel(intervals: intervals, timeRange: .thisWeek)
+
+        // Then
+        XCTAssertEqual(viewModel.yAxisStride, 70)
+    }
```
Comment (itsmeichigo) [inline WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StoreStats/StoreStatsChartViewModelTests.swift:167]: @selanthiraiyan this test could be improved a bit:
- The crash was due to really small negative revenues.
- The test should check that `yAxisStride` is larger than 0 because that was what crashed the Charts library.

Comment (selanthiraiyan) [reply WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StoreStats/StoreStatsChartViewModelTests.swift:167]: Thanks, @itsmeichigo!

> The crash was due to really small negative revenues.

When I tested, the store had revenues in the range of -39, -88, -19.5. Do you think we should use decimal values? 

> The test should check that yAxisStride is larger than 0 because that was what crashed the Charts library.

Good point. I will update this in one of my future PRs.

Comment (itsmeichigo) [reply WooCommerce/WooCommerceTests/ViewRelated/Dashboard/StoreStats/StoreStatsChartViewModelTests.swift:167]: For the app to crash, the smallest negative revenue has to have a larger absolute value than the largest positive value for the `yAxisStride` to be negative. So the test case above should be:

```suggestion
    func test_yAxisStride_can_handle_negative_revenue_values() {
        // Given
        let currentDate = Date()
        let intervals = [
            StoreStatsChartData(date: currentDate, revenue: 100),
            StoreStatsChartData(date: currentDate.adding(days: 1)!, revenue: 10),
            StoreStatsChartData(date: currentDate.adding(days: 2)!, revenue: -130),
        ]

        // When
        let viewModel = StoreStatsChartViewModel(intervals: intervals, timeRange: .thisWeek)

        // Then
        XCTAssertTrue(viewModel.yAxisStride > 0)
    }
```
