### PR TITLE
[Woo POS] Present `posModal` from root view to ensure full screen coverage

### LINKED ISSUE #13234: [Woo POS] M2 Error: Improve UI/UX after failing to check Order after a Payment Capture error
- Design request: p1719952222271239/1719867296.442819-slack-C0354HSNUJH
- Latest implementation: https://github.com/woocommerce/woocommerce-ios/pull/13215

## Context

From the previous PR description https://github.com/woocommerce/woocommerce-ios/pull/13215:
> If WooPayments captures the payment (charges the customer) but the request fails due to server issues or poor network conditions, we don't know whether the order has been paid for or not. In this case, the app first refreshes the order remotely again, and transitions to the success UI if the order is paid indeed. However, if the order refresh request fails like from poor network connections, we want to better inform the merchant about this error clearly so that the merchant does not end up undercharging or overcharging the customer.

## Further improvements

After the initial implementation, there are a few further improvements:

- Allow exiting POS mode (ref https://github.com/woocommerce/woocommerce-ios/pull/13215#pullrequestreview-2156088128)
- `Retry payment` triggers a retry directly, instead of the current behavior where the error message UI is gone on tap, and the merchant needs to tap `Collect Payment` again (this might require some non-trivial changes to trigger closure from `Collect Payment` in the `Retry payment` closure in `CardPresentPaymentsAlertPresenterAdaptor` https://github.com/woocommerce/woocommerce-ios/pull/13215/files#diff-9241914a004dc7903b66fc9a786752c7515d87c7e61d6ebbce6d788c81342d6aR25-R28)
- UI/UX design updates based on Joe's latest error design, and potential additional design input in p1719952222271239/1719867296.442819-slack-C0354HSNUJH

### PR DESCRIPTION
**Pull request by joshheald**
Closes: #13234
Merge after: #13704 

## Description

This is the final PR in the series handling the improved UI of the payment capture error.

This error has a modal, displayed over an error, fairly far into the POS stack.

In #13642, I noted that there was some remaining work:

> Modal overlay curtain should extend to screen bounds – this will be on a new PR so that the modal content can be passed up for display at the top level.

This PR ensures that a posModal presented from anywhere in POS will extend to the screen bounds, regardless of the size of the view that the `posModal` modifier is specified on.

We do this by doing the presentation through `posRootModal`, which is applied to the Dashboard view and contains the styling, as well as a reference to the `POSModalManager`, an environment object with the presentation logic and view builder.

Then we have two versions of the `posModal` view modifier which can be used to show the modal. Following platform conventions, one uses an `isPresented` Bool, and the other an `Item?` binding.

The `Item` binding was required so that the changes to the underlying view model would be reflected in a view update – unfortunately, I couldn't make that work with `isPresented`. This is noted in doc comments. I thought about removing the `isPresented` option, but where the modals are simple and don't get updated externally to the modal (other than the presentation value), it's very convenient.

Note that if we used the `isPresented` variant for the card reader connection view, it would show the `Scanning for readers` screen indefinitely, even though the reader would actually connect (if known to the iPad.)

## Steps to reproduce

1. Set up Proxyman or Charles to intercept traffic for your test device
2. Launch the app using a store eligible for IPP
3. Navigate to `Menu > Point of Sale mode`
4. Add an item to your basket and tap `Checkout`
5. Enable breakpoints in your proxy for the response of `POST` requests to `https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/*/rest-api/` and the requests to `GET` `https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/*/rest-api/?json=true&path=/wc/v3/orders/*`
6. Tap your card on the reader
7. Abort the `capture_terminal_payment` response and `order` requests when the breakpoints are hit (equivalent to poor network conditions meaning it was lost.) --> an inline error message UI should be shown in the totals view, with a modal presented that shows more details about the error
8. Observe that the blurred "curtain" behind the modal extends right to the bounds of the screen.

Also test the other posModals, that you can open them, perform all the actions, and close them.

- [x] Connect your reader
- [x] Tap the `Simple Products only` banner or info button on Products
- [x] Tap `Exit POS` in the ellipsis menu

## Testing information

I've tested this on an iPad running iOS 16, and a simulator running iOS 17, with all the above scenarios. I've also tested the error cases for card reader connections, and connecting the reader from the `Reader not connected` error screen.

No unit tests, as this is view logic only.

## Screenshots

https://github.com/user-attachments/assets/e84d114d-f8d8-4a6c-af5f-eda04da25df2

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift [hunk 1]
```diff
@@ -62,18 +62,8 @@ struct PointOfSaleDashboardView: View {
...
-            if let alertType = totalsViewModel.cardPresentPaymentAlertViewModel {
-                PointOfSaleCardPresentPaymentAlert(alertType: alertType)
-            } else {
-                switch totalsViewModel.cardPresentPaymentEvent {
-                case .idle,
-                        .show, // handled above
-                        .showOnboarding:
-                    Text(totalsViewModel.cardPresentPaymentEvent.temporaryEventDescription)
-                }
-            }
```
Comment (joshheald) [inline WooCommerce/Classes/POS/Presentation/PointOfSaleDashboardView.swift:76]: Removed this, as it's just old test code anyway.

File: WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift [hunk 2]
```diff
@@ -22,7 +22,7 @@ final class TotalsViewModel: ObservableObject, TotalsViewModelProtocol {
 
     @Published var showsCardReaderSheet: Bool = false
     @Published private(set) var cardPresentPaymentEvent: CardPresentPaymentEvent = .idle
-    @Published private(set) var cardPresentPaymentAlertViewModel: PointOfSaleCardPresentPaymentAlertType?
+    @Published var cardPresentPaymentAlertViewModel: PointOfSaleCardPresentPaymentAlertType?
```
Comment (joshheald) [inline WooCommerce/Classes/POS/ViewModels/TotalsViewModel.swift:25]: In order to bind to it, set and get need to be accessible.

File: WooCommerce/Classes/POS/Presentation/PointOfSaleEntryPointView.swift [hunk 3]
```diff
@@ -44,12 +45,13 @@ struct PointOfSaleEntryPointView: View {
                                  totalsViewModel: totalsViewModel,
                                  cartViewModel: cartViewModel,
                                  itemListViewModel: itemListViewModel)
-            .onAppear {
-                onPointOfSaleModeActiveStateChange(true)
-            }
-            .onDisappear {
-                onPointOfSaleModeActiveStateChange(false)
-            }
+        .environmentObject(posModalManager)
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/Presentation/PointOfSaleEntryPointView.swift:48]: This looks like the perfect case to use `.environmentObject()`, so we do not need to pass the object explicitly to all the views that might need a modal 💯

File: WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalManager.swift [hunk 4]
```diff
@@ -0,0 +1,19 @@
+import SwiftUI
+
+class POSModalManager: ObservableObject {
+    @Published private(set) var isPresented: Bool = false
+    private var contentBuilder: (() -> AnyView)?
```
Comment (iamgabrielma) [inline WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalManager.swift:5]: Not necessarily something that affect us or should be changed, just a note: I recall [reading](https://www.swiftbysundell.com/articles/avoiding-anyview-in-swiftui/) about performance issues due to `AnyView` usage. 

I gave it a couple of tries to attempt to remove the `AnyView` type in favour of using a generic constraint to `View`, but it just seems to make make everything more complicated, since now we have to pass the `<ModalContent: View>` generic types everywhere this is used, so it feels a bit of pre-optimization for no real benefit 😅

**Review by iamgabrielma — APPROVED** [review]
Nice work! This is a pretty cool change and will make our lives much easier when working with modals moving forward 🎉 

I've tested this on an iPad running iOS 15.3.1, and a simulator running iOS 16.4. I did see a small flickering at the top of the screen once when running it on iPad and tapping on the Simple Products only banner info button, but I couldn't replicate it on further attempts.

✅ Connect your reader
✅  Tap the Simple Products only banner or info button on Products
✅  Tap Exit POS in the ellipsis menu

File: WooCommerce/Classes/POS/Presentation/PointOfSaleEntryPointView.swift (hunk 3 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/PointOfSaleEntryPointView.swift:48]: I'd still like to neaten it up more, perhaps it's possible to do something in the `posRootModal` modifier so we don't have to remember to do both. 

It's really sensitive to where you do it as well - I can't inject it in the Dashboard, regardless of modifier order, it has to be a level up from that (which might prevent us doing the above.)

File: WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalManager.swift (hunk 4 above)
Comment (joshheald) [reply WooCommerce/Classes/POS/Presentation/Reusable Views/POSModalManager.swift:5]: Thanks for trying. I suspect a single AnyView which is only sometimes presented is fine, but it would be an issue if we started putting them in cells, etc.
