### PR TITLE
Login: Disable Continue button on the store picker if no site has Woo

### LINKED ISSUE #7511: [Login] Continue button is enabled when only Other Sites displayed
**Describe the bug**
When the user only has Other Sites, the Continue button is displayed as enabled but tapping on it doesn't do anything.

**To Reproduce**
1. Login as a user with only "Other Sites"
2. See that Continue button is enabled
3. Tap on Continue button - see that nothing happens

**Screenshots**
other sites only

**Expected behavior**
The button should be disabled since the user can't continue on the app with those sites.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.5
- WooCommerce iOS version: v9.9

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #7511 

### Description

This PR adds a simple fix to disable the Continue button if all sites in the store picker don't have WooCommerce.

### Testing instructions

Prerequisite: Make sure that you have a WP.com account with access to only sites without WooCommerce.
1. Log out of the app if necessary and select Continue with WordPress.com.
2. Log in to your WP.com account.
3. After the login succeeds, notice that you are navigated to the store picker with only sites in the Other sites section, and the Continue  button is disabled.

### Screenshots

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jaclync — APPROVED** [review]
LGTM! Tested with WP.com accounts with and without Woo sites plus non-Woo sites and the site picker works as expected ✅

File: WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift [hunk 1]
```diff
@@ -369,9 +369,12 @@ private extension StorePickerViewController {
             updateActionButtonAndTableState(animating: false, enabled: false)
             enterSiteAddressButton.isHidden = false
             newToWooButton.isHidden = false
-        default:
+        case .available(let sites):
             enterSiteAddressButton.isHidden = true
             newToWooButton.isHidden = true
+            if sites.allSatisfy({ $0.isWooCommerceActive == false }) {
+                updateActionButtonAndTableState(animating: false, enabled: false)
+            }
```
Comment (jaclync) [inline WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:377]: forgot to mention, it might be nice moving this logic to the view model for unit testing 🙂

Comment (itsmeichigo) [reply WooCommerce/Classes/Authentication/Epilogue/StorePickerViewController.swift:377]: Good idea! However it seems that `updateActionButtonAndTableState` is called in quite a few places, which means this would require a bigger refactor to move the old logic from the view controller to the view model. I'd say we do this in a separate task to be able to write more thorough tests.
