### PR TITLE
[Woo POS] Fix cart header having a white background when scrolling up the list in dark mode

### LINKED ISSUE #14414: [Woo POS] In dark mode, the cart header becomes not readable when scrolling up items in the cart
**Describe the bug**

Only an issue in dark mode: when the items in the cart becomes scrollable, the cart header turns white after scrolling up the list.

**To Reproduce**

Prerequisite: the store is eligible for POS, and has at least one purchasable product

- Go to Menu > Point of Sale Mode
- Switch to dark mode
- Add at least one product to the cart so that the list becomes scrollable (doesn't have to fill the height, just one item makes the list scrollable)
- Scroll up the items in the cart --> notice that the cart header changes color and the text is barely readable

**Screenshots**

https://github.com/user-attachments/assets/12ccfb8b-7fbb-47c3-9b8e-08959c5c32ea

**Expected behavior**

The cart header background color should stay the same when scrolling the list.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Pro 11in 3rd gen
- iOS version: iOS 17.5.1 device / iOS 18.0 sim
- WooCommerce iOS version: 20.9

### PR DESCRIPTION
**Pull request by jaclync**
Closes: #14414

## Description

The issue is when scrolling up the items in the cart in dark mode, the cart header becomes white and the text isn't readable anymore.

It took me a while to figure out the root cause, I was in the wrong direction trying to find alternative ways to observe the scroll view offset by `overlay` and `ZStack` to no avail (shadow stops working). Then I tried adding another view above the cart header view and there was no white color when the offset was negative (scrolling up), which indicates that the issue is from something in the cart header view. It turns out the white color is from the POS bottom shadow modifier `POSBottomShadowViewModifier`, I'm not sure why it's set to white but we can't use a clear color because clear color doesn't render any visible area for the shadow in SwiftUI. In this PR, the background color in the shadow modifier is now DI'ed from the use case, so that the background color matches the cart background.

This PR also fixes another visual issue where there is redundant bottom content padding in the cart items list in the cart building stage. The additional padding is from `floatingControlAreaSize`, which is from observing the floating elements at the bottom of POS. This is only necessary in the cart finalizing stage, when the checkout CTA isn't present.

The `CartView` SwiftUI preview was also updated to fix a crash from not having the aggregate model environment object.

## Steps to reproduce

- Switch to a store eligible for POS & with at least one purchasable product
- Go to Menu > Point of Sale mode
- Add multiple items to the cart, so that the list is scrollable
- Scroll up and down --> there should be no extra bottom padding like in trunk, and the cart header shouldn't become white in dark mode. The cart header should have a shadow when scrolling up (negative content offset)
- Check out --> the bottom padding in the cart view should remain the same as in trunk

## Testing information

Tested in iOS 18.0 simulator and iPad Pro 11 in 3rd gen device.

## Screenshots

Notice the extra bottom padding in the order building stage before.

\ | before | after
-- | -- | --
order building - dark | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 50 32 | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 36 33
order building - light | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 50 21 | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 37 02
order finalizing - dark | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 53 03 | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 58 44
order finalizing - light | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 53 12 | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-10 at 15 58 33

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/POS/Presentation/CartView.swift [hunk 1]
```diff
@@ -109,7 +108,8 @@ struct CartView: View {
                         .accessibilityAddTraits(.isHeader)
                 }
             case .finalizing:
-                EmptyView()
+                Spacer()
```
Comment (staskus) [inline WooCommerce/Classes/POS/Presentation/CartView.swift]: > This PR also fixes another visual issue where there is redundant bottom content padding in the cart items list in the cart building stage. The additional padding is from floatingControlAreaSize, which is from observing the floating elements at the bottom of POS. This is only necessary in the cart finalizing stage, when the checkout CTA isn't present.

Do we need this for the finalizing stage? Before the items would go behind the floating button. I think that's expected behavior or isn't it?

| Before            | After           |
| ------------------ | --------------- |
| image | image |

**Review by staskus — APPROVED** [review]
Thanks! The white shadow issue is fixed.

However, I'm not sure we need this padding for the finalizing stage. WDYT?

File: WooCommerce/Classes/POS/Presentation/CartView.swift (hunk 1 above)
Comment (iamgabrielma) [reply WooCommerce/Classes/POS/Presentation/CartView.swift]: > Before the items would go behind the floating button. I think that's expected behavior or isn't it?

I recall this was requested on purpose by design, yes.

Comment (jaclync) [reply WooCommerce/Classes/POS/Presentation/CartView.swift]: Great catch on this issue, thanks for clarifying the expected design both. It looks like we'd want a scroll view bottom inset instead of a fixed bottom padding. Updated in https://github.com/woocommerce/woocommerce-ios/pull/14643/commits/ffea8b365ec5fbc8bbb64dccc7237c46027c132c

finalizing - top | finalizing - bottom | building
-- | -- | --
Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-12 at 10 06 12 | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-12 at 10 06 14 | Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-12-12 at 10 06 27

Comment (staskus) [reply WooCommerce/Classes/POS/Presentation/CartView.swift]: Looks good, thanks for addressing this 👍
