### PR TITLE
Blaze: Update layout for Blaze campaign list item to display human-readable values and fix clipped off layout

### LINKED ISSUE #13864: Blaze: Format the click-through rates on the detail card to human-readable format
Now | Expected
--- | ---
 | 

Note: we should also collapse the content to a vertical stack when the text is too long to avoid cutoff.

Internal thread: p1725547339131059-slack-C03L1NF1EA3

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #13864 

## Description

This PR updates the Blaze campaign list item with some UI enhancements:
- Display the number of impressions and clicks in human-readable format.
- Introduce `CollapsibleHStack` and replace `AdaptiveStack` in the item layout with this new stack to display content in a VStack when the screen width is small.

## Steps to reproduce

- For the human-readable value, it might not be straightforward to test the large number of impressions and clicks on real ads. Instead, update the values in the preview view of `BlazeCampaignItemView` to see how they are displayed.
- For the card layout, test the Blaze campaign list on different screen sizes and fonts to ensure that no content is cut off.

## Testing information

Tested on simulator iPhone 15 iOS 17.4 with different font sizes for the collapsible layout.
Also tested the campaign list in split view mode on iPad 10th-generation simulator.

## Screenshots

Item layout:

Before | After 
--- | ---
 | 

Human readable values on preview view:

Screenshot 2024-09-12 at 12 56 45

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/Extensions/BlazeCampaignListItem+Customizations.swift [hunk 1]
```diff
@@ -7,6 +8,16 @@ extension BlazeCampaignListItem {
         status == .pending || status == .scheduled || status == .active
     }
 
+    var humanReadableImpressions: String {
+        let doubleValue = Double(impressions)
+        return doubleValue.humanReadableString(shouldHideDecimalsForIntegerAbbreviatedValue: true).uppercased()
```
Comment (selanthiraiyan) [inline WooCommerce/Classes/Extensions/BlazeCampaignListItem+Customizations.swift:13]: TIL about this method. 👏

**Review by selanthiraiyan — APPROVED** [review]
LGTM 🚀
