### PR TITLE
Background image upload: Fix issue showing uploaded images while saving is in progress

### LINKED ISSUE #15093: Background image upload: Product form is empty when opened before saving is done
**Describe the bug**
There's a UI glitch when you open the product form just when background image uploads are done but the product form is not done saving with the new images.

**To Reproduce**
1. Create or open an existing product with no images.
2. Select a few images to upload, save the changes and navigate back to the product list.
3. Wait a bit for the upload to complete but before the saving is done.
4. Open the product form and notice that the image list is still empty.
5. Navigate out and back again.
6. Notice that the image list is filled with the uploaded images.

**Screenshots**

https://github.com/user-attachments/assets/90716607-40c4-4157-8317-449fa67fa538

**Expected behavior**
The product form should display the uploaded image even before product saving is done.

### PR DESCRIPTION
**Pull request by itsmeichigo**
Closes: #15093 

## Description

This PR fixes the issue when uploaded images are not displayed when background image saving is in progress. 

The solution:
- Enable reusing the action handler even when there are no pending uploads.
- Persist the product saved in the background and use it to determine `hasUnsavedChangesOnImages`.
- Remove product from active uploads when all images are done uploading. This is to make the logic simpler.

## Steps to reproduce

1. Create or open an existing product with no images.
2. Select a few images to upload, save the changes and navigate back to the product list.
3. Wait a bit for the upload to complete but before the saving is done (notice the loading indicator is removed but the cover photo is not updated yet).
4. Open the product form and notice that the image list is filled with the uploaded images.
5. Navigate back and confirm that you're not asked to save any changes (neither when background saving is done or not).
6. Repeat the steps 1-4. Remove the new images and tap Save. Confirm that everything works correctly - the Save button is hidden after saving is done.

## Testing information

Tested on simulator iPhone 16 Pro iOS 18.2 and confirmed that:
- Reopening product before background image saving is done shows uploaded images correctly.
- Background image saving handles the saving automatically.
- Saving the product after background image saving works correctly.
- No regression for loading animation on products with pending uploads.

## Screenshots

https://github.com/user-attachments/assets/3e994f6b-87f6-48ae-bfcf-c7fc793eb2c6

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift [hunk 1]
```diff
@@ -58,6 +58,14 @@ final class ProductsTabProductTableViewCell: UITableViewCell {
...
         updateDefaultBackgroundConfiguration(using: state)
     }
+
+    override func prepareForReuse() {
+        super.prepareForReuse()
+        syncingOverlayView?.removeFromSuperview()
+        selectedProductImageOverlayView?.removeFromSuperview()
+        syncingOverlayView = nil
+        selectedProductImageOverlayView = nil
+    }
```
Comment (itsmeichigo) [inline WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift:68]: Attempt an additional fix for the [reuse issue](https://github.com/woocommerce/woocommerce-ios/pull/15052#issuecomment-2649713593) mentioned in #15052.

Comment (pmusolino) [reply WooCommerce/Classes/ViewRelated/Products/Cells/ProductsTabProductTableViewCell.swift:68]: This seems to have fixed the issue, I'm not able to replicate it anymore! 👏

**Review by pmusolino — APPROVED** [review]
Everything works as expected 👏
